### ISSUE TITLE
Adjust chiventure start-up so that users can decide to run a graphical user interface (which will call start_gui instead of start_ui)

### ISSUE THREAD

**Issue by eao10000** [uchicago-cs/chiventure#1000]
This will entail looking through the ui.c and how it is loaded into chiveture and then reciprocating this for gui.c I will have to talk to the cdl team and discussing how I plan to implement the new gui.c file, in a way such as the ui.c so that chiventure can run an graphic version. 
Assignees: Elijah
Team:gui

**Comment by eao10000** [comment]
I am entering the cli team and seeing when I can discus this integration with them.

**Comment by eao10000** [comment]
After talking with my team leader I have created both a gui.h stating what the start_gui function is, as well as the gui.c where I have a basic start_gui function and the skeleton of a stop_gui.

**Comment by eao10000** [comment]
Went into chiventure.c and made additions to check, if the user is asking for gui with a graphically Boolean. While adding another response to when the user loads a game and asking for gui, checking that it asked for 3 arguments and making sure it was gui.

**Comment by eao10000** [comment]
The gui.c and gui.h has been implemented, where it includes the basic start_gui function, and a skeleton of stop_gui. In this issue chiventure.c has been updated now to call start_gui if gui is flagged (--gui). I am closing this issue, start_gui and stop_gui will be expanded upon in future issues.

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Great work! Your updates are particularly useful. One note for next time: please make sure you change the summary to get rid of relics from the project board (i.e. "assignees:")
