### ISSUE TITLE
Provide input suggestions to user when input is misspelled 

### ISSUE THREAD

**Issue by mberamendiconde** [uchicago-cs/chiventure#1004]
Want to create a feature by which if a user types in a word not supported by chiventure but similarly spelled to a supported input, it will be suggested to the user. 

For example, if the user meant to type 'take" but types "tak" , the user will see "did you mean: take" printed to the window

**Comment by mberamendiconde** [comment]
Work for this happening in the cli/suggestions branch

**Comment by mberamendiconde** [comment]
Currently when full words are input, the action word is returned to the screen.
Now, when loading an example game, there is a seg fault. No sure where it could be coming from. All new functions are in src/cli/src/operations.c

**Comment by dchen0258** [comment]
The bug was fixed by using a for loop instead of a while loop.
Also a different use of strncat fixed another bug.

**Comment by dchen0258** [comment]
Submitted pull request.

**Comment by dchen0258** [comment]
Branch merged!

**Comment by dchen0258** [comment]
There are possible enhancements to the issue: allowing multiple suggestions, not only based on the number of matching letters, but also the size of the words. This would require a much more length function, and probably can be an enhancement for the future!

**Comment by ecoble** [comment]
Issue Score: ✔️++

Comments:
Great work! Nice documentation, and thoughts on possible enhancements!
