### ISSUE TITLE
Fix Indentation Error

### ISSUE THREAD

**Issue by mjgoodman321** [uchicago-cs/chiventure#1005]
When in the ui, every instance of the arrow ">" (except the first) begins at the far left of the screen instead of slightly indented. Entering any character updates the ui and the arrow moves to the correct place. Fix the indentation issue.

**Comment by mjgoodman321** [comment]
Added two spaces before the arrow in the last line of code in the print_cli function in print_functions.c in ui

**Comment by mjgoodman321** [comment]
Set the third variable in the mvwprintw call in the last line of print_cli to 0 (previously 2). Issue appears to be fixed.

**Comment by mjgoodman321** [comment]
Closing Statement:
Linked Pull Request #1006 has been approved, and the branch with its relevant changes merged into dev. No further follow ups should be necessary for this issue

**Comment by ecoble** [comment]
Issue Score: ✔️++

Comments:
Great job! I know the UI code can be pretty difficult to work with, nice fix!
