### ISSUE TITLE
Creating Troubleshooting Documentation and Preparing Docs for Future Sound Teams

### ISSUE THREAD

**Issue by jiguba** [uchicago-cs/chiventure#1017]
The purpose of this issue is to prepare future sound teams by equipping them with struggles we faced throughout Sprints 1 to 3 when implementing the sound module. 

Various troubleshooting and guides will include: set up of the SDL2 library, locating the files within the CS Linux system, and audio troubleshooting steps on NoMachine.

**Comment by gypark23** [comment]
The current status and to-do list for next team had been updated on README.md.

**Comment by jiguba** [comment]
Closing Remarks:
The troubleshooting wiki has been created and has been placed under the sidebar as References. It includes information of how to access the SDL files, a command to run to verify if audio drivers are present within the computer system, and the primary error we ran into when trying to compile audio programs in the CS server through SSH.

**Comment by ecoble** [comment]
Issue Score: ✔️++

Comments:
Great job creating this documentation! I know it will be extremely helpful to future teams.
