### ISSUE TITLE
Find/create sound files for Chiventure

### ISSUE THREAD

**Issue by vivianwu00** [uchicago-cs/chiventure#1018]
assignees: Vivian and Shuwen
team:sound

**Comment by vivianwu00** [comment]
Creating and finding sounds for Chiventure bgm, game sound effects that can be loaded into the sound module.

Collaborating on a team wide basis for aesthetics of game sounds.

**Comment by vivianwu00** [comment]
Royalty free music found from: https://patrickdearteaga.com/
Pushed 6 sound samples to src/sound/sandbox to sound branch of file type .wav and .mp3
We'll decide as a group later this week to see which file type can be integrated more smoothly.

**Comment by vivianwu00** [comment]
Both file types are available for demo next week. Closing out issue.

**Comment by DemS2000** [comment]
Update: uploaded 3 more sound effect type files in .wav format to sandbox.

**Comment by DemS2000** [comment]
Added 3 more sound files (.wav format) for sound effects.

**Comment by ecoble** [comment]
Issue Score: ✔️+

Comments:
Great work finding sound files for Chiventure, it really fit the theme of the game! Be sure that the summaries of issues have a description of the task, not just the assignees.
