### ISSUE TITLE
Implement additional functions for the npc_battle struct

### ISSUE THREAD

**Issue by amymorrill** [uchicago-cs/chiventure#1025]
Now that the npc_battle struct has been created and added to the npc struct, there are several functions that would be helpful to have. 

The first is a function to add an npc_battle to an existing npc struct because npc_new defaults npc's to have a NULL pointer in the npc_battle field. Along with this, I will edit the npc_free function to free the npc_battle field if it is not set to NULL. 

The second is a function to check if an npc's will_fight status matches its npc_battle status (ie if an npc has will_fight = true, it's npc_battle shouldn't be NULL but if an npc has will_fight = false, it doesn't matter). 

Finally, I want to create several functions to get/change key fields in an npc's npc_battle struct. I will consult with the battle team to determine which npc_battle fields need to be updated / retrieved often in battle.

**Comment by amymorrill** [comment]
After a discussion with @Elsa-Athiley and @lczielinski from the battle team, we decided that it is sufficient to have one get_npc_battle() function as opposed to an individual "get" function for each parameter in npc_battle. However, because it already exists, I'll keep the get_npc_health() function.

In terms of "set" functions, I decided to have one for each parameter in npc_battle to avoid having to create an entirely new npc_battle struct every time one of those parameters changes.

Finally, I have decided to make add_battle_to_npc() take the parameters for an npc_battle struct, internally create an npc_battle, and then add that npc_battle to the npc (as opposed to taking a previously created npc_battle and adding it to the npc). This will make it easier for other teams because they'll only have to call one function (add_battle_to_npc) to add an npc_battle to an npc instead of two (npc_battle_new and add_battle_to_npc). 

The next step is to begin implementing these functions.

**Comment by amymorrill** [comment]
After considering it, I will only include a "set" function for health because there are rules for that function (can't be less than 0 or greater than the max health for that npc). However, for other parameters, they can easily be changed with one line of code (npc->npc_battle->_____ = _____), which I hadn't considered before.

**Comment by lilyehsani** [comment]
Issue Score: ✔️++

Comments:
Great work overall! The summary and updates of this issue are very thorough.
