### ISSUE TITLE
Write tests for npc/battle integration

### ISSUE THREAD

**Issue by amymorrill** [uchicago-cs/chiventure#1026]
Over the past couple of sprints (and during this sprint) we've created many functions to help integrate the npc and battle modules. For more information about these functions see #883, #992, and #1025. 

Now we need to implement both unit tests for our functions and integration tests between npc and battle. Note that the integration tests will rely on the battle team incorporating our functions into their module, which they are working on this sprint. We will discuss this with them and may defer integration testing to them or leave it to the backlog if we run out of time.

**Comment by amymorrill** [comment]
I've written tests for the npc_battle struct's new, init, and free functions. The next step will be to write tests for the additional functions outlined in #1025.

**Comment by northofsophia** [comment]
I have added multiple tests for the transfer_all_npc_items() function that will help in looting dead bodies. I will now issue a pull request to push these tests to dev.

**Comment by lilyehsani** [comment]
Issue Score: ✔️++

Comments:
Great work overall! The summary of this issue is very thorough.
