### ISSUE TITLE
WDL path seg fault

### ISSUE THREAD

**Issue by samdonio** [uchicago-cs/chiventure#1030]
Currently when the user inputs an incorrect wdl file path chiventure causes a segfault, instead of just saying something along the lines of "Invalid file path!"

**Comment by samdonio** [comment]
It seems that right now the load_wdl_operation in operations.c will load correctly, but the seg fault is caused when the str_to_objtype function is called eventually when trying to load the objects from the wdl file. It tries to compare strings that don't exist I think and this causes the seg fault. I'm not really sure why right now load_wdl_operation checks if the token is null instead of checking if the file path exists.

**Comment by samdonio** [comment]
I've edited the load_wdl_operation function so now it checks whether the path that the user inputs even points to a real file, and if it doesn't the cli displays the message "Invalid Input, Loading WDL file failed". I'm going to see if I can have the function also check if the file is specifically a .wdl

**Comment by samdonio** [comment]
I've added the function validate_wdl_filename that checks if a file has the .wdl file type, it is based off the validate_filename that checks if a file is of .dat file. There may be an issue where the cli always believes the file path is incorrect, however this may be from the wdl not correctly loading the file, I'm not exactly sure.

**Comment by samdonio** [comment]
The wdl module hasn't been fully implemented loading from ingame it seems, so right now the cli will just say "Invalid Input, Loading WDL file failed, loading not yet implemented" when the user enters an incorrect file path or even a correct one. This seems to be a better alternative than an immediate seg fault in both cases. Once wdl has implemented loading games, this can quickly be edited so that the load_wdl command can load games. There is no wdl team currently, otherwise I would have contacted them about working on this.

**Comment by mjgoodman321** [comment]
Modified load_wdl_operation so it now recognizes valid file paths. Previously, the paths had been made all caps by the current implementation of case insensitivity in the parser, which the access() function used to check file paths could not recognize as valid paths

**Comment by mjgoodman321** [comment]
Cleaned up load_wdl_operation so it can now use the valid file paths to load games. Using load_wdl from the cli interface now allows players to load games mid-chiventure run, although the intro text does not play.

**Comment by ecoble** [comment]
Issue Score: ✔️++

Comments:
Great job fixing this, and nice documentation on this issue!
