### ISSUE TITLE
Migrate CI from Travis to GitHub Actions

### ISSUE THREAD

**Issue by borjasotomayor** [uchicago-cs/chiventure#1031]
chiventure currently uses Travis, which tends to result in delays in builds for pull requests, since we are on their free plan. We should migrate to GitHub Actions, which we now cover in class (which means students will be more familiar with it) and which seems to have much more generous resource limits.

**Comment by borjasotomayor** [comment]
I've created a [github-actions](https://github.com/uchicago-cs/chiventure/compare/github-actions) branch for this. The build [currently fails](https://github.com/uchicago-cs/chiventure/runs/2611609469) because of some battle tests that are failing; I suspect these are not failing in the current Travis build because it uses Ubuntu 16.04, and there may be a bug somewhere that only manifests itself when running on Ubuntu 16.04.

Besides fixing those bugs, we may want to cache the Criterion and Raylib files, so they don't have to be downloaded for every single build.

**Comment by borjasotomayor** [comment]
Verified that the tests fail in the CS environment, which uses Ubuntu 20.04, so this definitely looks like something that is just not being caught in the current Travis Ubuntu 16.04 environment:

```
2: Test command: /home/borja/repos/chiventure/build/tests/battle/test-battle
2: Test timeout computed to be: 10000000
2: [----] /home/borja/repos/chiventure/tests/battle/test_battle_flow.c:16: Unexpected signal caught below this line!
2: [FAIL] battle_flow::set_battle_player: CRASH!
2: [----] /home/borja/repos/chiventure/tests/battle/test_battle_move_maker.c:10: Unexpected signal caught below this line!
2: [FAIL] class_moves::bard: CRASH!
2: [----] /home/borja/repos/chiventure/tests/battle/test_battle_move_maker.c:77: Unexpected signal caught below this line!
2: [FAIL] class_moves::knight: CRASH!
2: [----] /home/borja/repos/chiventure/tests/battle/test_battle_move_maker.c:43: Unexpected signal caught below this line!
2: [FAIL] class_moves::wizard: CRASH!
2: [====] Synthesis: Tested: 60 | Passing: 56 | Failing: 4 | Crashing: 4 
 2/14 Test  #2: test-battle ......................***Failed    0.99 sec
```

**Comment by borjasotomayor** [comment]
The issue with the battle code is related to a missing declaration for `set_player` which should be fixed by #969

**Comment by firatciftci** [comment]
#969 has just been merged into `dev`, so this issue should be fixed now.

**Comment by borjasotomayor** [comment]
Confirmed that #969 has fixed the issue with the failing tests in the GitHub Actions workflow.
