### ISSUE TITLE
Create documentation for the openworld module in chiventure/docs

### ISSUE THREAD

**Issue by ahmed-sumaiya** [uchicago-cs/chiventure#1032]
Create a .md file for the openworld module which would ideally include a brief summary of:
 - The openworld module
 - Each file and their functionalities in the openworld module
 - Any changes made to the openworld module this quarter
 - Feature wishlist for the openworld module for next year

**Comment by ahmed-sumaiya** [comment]
Closing statement:
The relevant pull request (#1087) has been approved, and the openworld.md document, which contains a list of system and product documentation wiki pages for the openworld module and a list of the directories and their functionalities, has been merged into the dev branch. This marks the end of this issue.

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Great work! You did a particularly good job providing relevant wiki and issue links when relevant.
