### ISSUE TITLE
Openworld: Convert room_generate() into a general purpose, single-room loading + connecting function

### ISSUE THREAD

**Issue by Justin08784** [uchicago-cs/chiventure#1033]
Currently, the room_generate() function is only able to generate rooms around the `room_t* curr_room` field specified in `game_t`. room_generate() should be converted into a general-purpose function for generating a single room around _any_ given room in the game. We can achieve this by adding a `room_t* pivot` parameter that specifies the room to serve as the generation center. 

In addition to changing all room_generate() function calls, we will refactor recursive_generate() by replacing its redundant code with a call to room_generate().

A new branch (openworld/refactor-room-gen) will be created for these changes and merged into `dev` using a PR.

**Comment by Justin08784** [comment]
Finished adding new parameter to room_generate(). Modified dependent documentation, function calls, and tests.

**Comment by wmingyan** [comment]
Justin and I met on Zoom today. We decided to transfer room_generate into a helper function that can be used by both multi_room_generate and recursive_generate to reduce redundant code. To achieve this, we will
- add parameters for directions to room_generate
- move random direction picking and path_exists_in_dir checking functionalities out of room_generate and into multi_room_generate
- modify the tests to accommodate the changes

**Comment by Justin08784** [comment]
Summarizing changes in 28793b3:
- recursive_generate() takes a gencontext instead of a speclist parameter
- room_generate() no longer takes a gencontext; it now takes `char* dir_to_new` (direction to to-be-generated room) and `char* dir_to_curr` (reverse)
- moved random dir picking/path checking functionality out of room_generate() and formed a new helper called pick_random_dir()
- multi_room_generate() now calls pick_random_dir() ; recursive_generate() now calls room_generate()

Tests haven't been updated yet so they do not compile.

**Comment by Justin08784** [comment]
Summary of ef2d4d9:

## Modifications
- tests updated to make use of new room_generate() and recursive_generate() functions (all pass now)
- added recursive_gen test case for radius 2

## Bug Fixes
1. random_items()
Passing a `roomspec_t` whose `item_hash_t *items` field is NULL (i.e. no items) to random_items() caused it to crash. [cause + fix](https://github.com/uchicago-cs/chiventure/commit/ef2d4d98125cf938843405a908215840bab31895#r51143060)

2. room_generate()
In test room_generate_failure, trying to generate a room in a direction that is already full (full as in a path exists for that direction) crashed the program.  [cause + fix](https://github.com/uchicago-cs/chiventure/commit/ef2d4d98125cf938843405a908215840bab31895#r51143120)

3. recursive_generate()
recursive_gen tests for radii ≥ 2 were crashing and/or failing. next_room was not being updated to contain the newly-generated room. [cause + fix](https://github.com/uchicago-cs/chiventure/commit/ef2d4d98125cf938843405a908215840bab31895#r51143154)

**Comment by Justin08784** [comment]
Tests for pick_random_dir() added.

A good followup task is to simplify/reorganize tests so that next year's team don't have a migraine.

**Comment by Justin08784** [comment]
The relevant pull request (#1077) has been approved, and the refactored room_generate() function as well as the new helper pick_random_direction() (along with relevant tests), has been merged into the dev branch. This marks the end of this issue.

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Excellent work! Your summary did a particularly good job noting the specific subtasks being accomplished in this issue.
