### ISSUE TITLE
Openworld: Reorganize level-oriented generation structs into a new levelspec_t struct

### ISSUE THREAD

**Issue by Justin08784** [uchicago-cs/chiventure#1034]
Level-oriented generation structs are not organized optimally. Firstly, multi_room_level_generate() takes too many parameters (6)–– 2 just for level-oriented generation. Secondly, `difficulty_level_scale_t` is just an integer array combo-d with its length–– it seems excessive to create a new struct for it.

It is much less cognitively demanding for both level-oriented generation structs to be wrapped inside a new struct called `levelspec_t`. `difficulty_level_scale_t` will be divided into an int array and int array length.

A new branch (openworld/add-levelspec) will be created for these changes and merged into `dev` using a PR.

**Comment by Justin08784** [comment]
Created `levelspec_t` and renamed `room_level_t` to `roomlevel_t`. Refactored all level-oriented generation functions (+ documentation) so that they no longer take difficulty_level_scale_t, and instead accept the new struct.

Openworld library compiles normally.

To do:
- update level-gen tests (explains why they currently fail)
- delete `difficulty_level_scale_t` and associated helpers (new, init, free)
- create `levelspec_t` helpers

**Comment by Justin08784** [comment]
Deleted `difficulty_level_scale_t` and related helpers. Added `levelspec_t` helpers. Openworld library compiles normally.

Need to add tests for new helper functions.

**Comment by Justin08784** [comment]
Discovered a bug

**Comment by Justin08784** [comment]
Discovered a bug in filter_speclist_with_difficulty(). Can be reproduced in commit adb74ce, in which all tests involving filter_speclist except valid_multi_room_level_3 have been commented out. Print statements have been added too.

Explanation:
In the DL_FOREACH loop, once it reaches the first roomspec in the speclist whose difficulty level matches the given level, it adds that to the filtered_speclist but stops the loop and ignores the rest of the speclist. This is the case even when the function is given a `roomlevels` hash table which contains multiple roomlevels of the correct difficulty_level.

**Comment by Justin08784** [comment]
Bug was fixed by replacing DL_FOREACH with with DL_FOREACH_SAFE in 3b5f6f6. Exact mechanism is not fully understood.

**Comment by Justin08784** [comment]
multi_room_level_generate() tests have been finally despaghettified. Similar changes can be made for multi_room_generate() tests (implemented last year), which are ridiculously verbose, complicated, and confusing. This is a likely followup task.

**Comment by Justin08784** [comment]
The relevant pull request has been approved, and the refactored code, including bug fixes and the new helper function pick_random_dir(), has been merged into the dev branch. This marks the end of this issue.

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Great job! YOur list of remaining todos in your issue updates were particularly helpful for tracking progress.
