### ISSUE TITLE
Create openworld demo "game" (Spring 2021 team)

### ISSUE THREAD

**Issue by Justin08784** [uchicago-cs/chiventure#1039]
Create a sample "game" that demonstrates the work that the openworld team has done since sprint 1–– level-oriented generation and recursive generation. Since the openworld module is not properly integrated into chiventure, monkeypatching will be necessary. We expect to add more features and do some refactoring in the current sprint so production of the demo game will need to be delayed/adjusted accordingly.

Concurrent issues:
Refactoring: #1033, #1034, 
New: #1032, #1035 

This demo will be utilized in our final presentation. We will create a new branch (openworld/demo-spring-2021) for the demo and merge it into `dev` using a PR.

**Comment by ahmed-sumaiya** [comment]
The three of us met today over zoom and decided to work on having the following features displayed in our demo game:
1. Autogeneration of rooms within a radius (n) where n number of rooms are generated randomly around the current room in each direction (north, south, east and west)
2. Level oriented room generation where a room is generated randomly but according to the player's level
3. Item generation with a random probability of appearing in a certain room at a random quantity

**Comment by Justin08784** [comment]
Discovered a bug where filter_speclist_with_difficulty() removes nodes from the original, unfiltered speclist and inserts them into the filtered speclist output.

Steps for reproduction:
In c62c1cb, I added a test to check filter_speclist_with_difficulty() does not alter the original, unfiltered speclist. Simply compile tests and confirm that test unfiltered_unchanged fails.

**Comment by Justin08784** [comment]
Summary of 487abb2:

- hardcoded rspecs, speclist, context, and levelspec 'placeholder variables' that are initialized and referred to by functions
- introduced initialize_sample_structs() to initialize placeholder variables before game execution

_New/Modified CLI commands_
- LEVELNEW <int>, updates player level to given integer
- NUKE, removes and frees all rooms in the game hash except for the original room, "room1". Resets num_built of all rspecs to 0 as well.
- LEVELCHECK, outputs the current player level and the corresponding difficulty level of rooms that will be generated
- COUNT, outputs the number of rooms (total and per difficulty level)
- Changed LEVELGEN so that it takes an integer token to specify number of rooms to be loaded (4 is maximum because it only generates in the compass directions)

**Comment by Justin08784** [comment]
53d669f:
- renamed openworld_example.c (and executable) to openworld-demo-2021.c
- Bug: discovered that 'nuke' CLI command doesn't reset game->curr_room to original room. Fixed to do so.

This bug can be reproduced in 20d64d6 with the steps:
1. generate some rooms
2. move way from the original room (like "go north")
3. nuke.
4. count. Observe that one of the levelled (lvl0, 1, 2, or 3)rooms is still in the game. At this point, the original room has been deleted and freed.

**Comment by Justin08784** [comment]
82afba1:
- refactored delete_all_paths() to take a room_hash_t** parameter and changed dependencies
- nuke in demo game now calls delete_all_paths()
- lowercased directions because it was conflicting with directions defined within the scope of recursive_generate() (I believe that this is a consequence of the recent 'lower case insensitivity' implementation, PR #1124>

**Comment by Justin08784** [comment]
Closing Statement:
The relevant pull request (#1148) has been approved and merged into `dev`; now the demo game can now be made and run in the `build/src/openworld/examples` directory. This demo game demonstrates level-oriented generation and recursive generation. 

Unfortunately, we weren't able to include itemspecs/probability-based generation in the demo due to time constraints–– branch `openworld/add-itemspec` was merged into dev just recently.

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Excellent work! Your closing statement is particularly well-done, especially since you've linked relevant issues, comments, and PRs.
