### ISSUE TITLE
Work with rpg-battles so that skilltrees/effect_v2 builds correctly

### ISSUE THREAD

**Issue by rohangupta2806** [uchicago-cs/chiventure#1040]
The implementation of most skeleton methods in effect.c has been completed in effect_v2.  However, this code does not build because of certain dependencies in rpg-battles which are causing issues.  We need to resolve these issues and ensure that our code builds properly so that we can submit a pull-request.

**Comment by rohangupta2806** [comment]
Had a meeting with Elsa Athiley from rpg-battles yesterday where an issue regarding class_t was identified.  rpg-battles is now working on fixing this.

**Comment by rohangupta2806** [comment]
rpg battles renamed the keyword from class to class_type but that did not fix the issue.  We think the issue originated in playerclass itself.  Playerclass has been alerted and we are working over slack to figure out what to do.

**Comment by rohangupta2806** [comment]
@jackcasey067 was able to narrow down the issue to a circular dependency and corrected it by making changes to certain files.  The code builds correctly now.  We should be able to finish implementing tests and submit a pull request in the coming days.

**Comment by rohangupta2806** [comment]
Tests were added and all tests so far pass.  We also had to add forward declarations to action_management and added some includes to their files.  As a result I have added @WPDolan from action_management on the submitted pull request which now builds correctly.  The pull request has been submitted and this issue will now be closed

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Great work on this! The updates that you have provided give a really detailed overview of your work.
