### ISSUE TITLE
Refactor the class_t struct to be a hashtable.

### ISSUE THREAD

**Issue by jackcasey067** [uchicago-cs/chiventure#1042]
This is the first step for being able to load in classes from the WDL++ format.  We need someplace in memory to store all of the classes are in the JSON-style game files.

I am currently thinking about the following changes.  It is possible that some will not make it into this issue:
- Turn class_t into a hashtable.
- Add convenience functions for accessing and manipulating the hashtable.
- Add a field to the game_t struct to store the hashtable (this is where stats_hash_t and effects_hash_t lives).
- While I am refactoring the class struct, it might be a good time to finalize the class_t struct.  We have been thinking about combining the two skill inventories, for example.  Attributes may also be on the chopping block.  Also, we might want a field that denotes whether or not a class is for players or for NPCs/enemies.

Note that these changes would be followed by updating tests and documentation.

**Comment by jackcasey067** [comment]
The action-management team approved of adding the hashtable to the game_t struct.  I will add them as a reviewer to any PR that results from this issue.

**Comment by jackcasey067** [comment]
Update:
 -  The hashtable struct was added.
 - The following functionality exists and have passing tests:
   - Add classes to a hashtable
   - Add classes, replacing in case of a name clash (instead of returning FAILURE)
   - Count classes in hashtable
   - Delete and Free classes in hashtable
   - Find classes in hashtable
 Overall, I want using the class hashtable to feel less forbidding than using the MACROS.

**Comment by jackcasey067** [comment]
Update on changes to the `class_t` struct:
- The two skill inventories (`combat` and `noncombat`) are being fused.  This will mean that a skill tree can have skills of both types with dependencies on each other.
    - This will require a change to the `player_t` as well, since it also has two skill inventories.
    - These changes were approved by the skill-trees and action-management teams.
- The `attributes` field stays, even though we currently don't use it much.  It could be especially useful in the future if classes are extended for use generating npcs and enemies (some enemies could have the "undead" trait, for example, and this could have gameplay effects regarding the use of certain items or skills (ie: "Holy Water")).
- The `effects` field also stays, more so as something that future teams could use.
- To clear up confusion, I am changing `stats` to `base_stats`, but the functionality is the same.

**Comment by jackcasey067** [comment]
I implemented those changes, which meant changing very small parts of a lot of files.  I am going to open a PR, and then this issue will be closed.

**Comment by jackcasey067** [comment]
Closing comment:
The code in the branch `playerclass/hashtable` is now up for review (PR #1061).  I will likely continue working towards WDL to in-memory conversion of classes, probably by specifying what JSON classes should look like.

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Great job on this!
