### ISSUE TITLE
update weapons for more easy integration to existing code in battle_logic

### ISSUE THREAD

**Issue by sonnykaiyuenlee** [uchicago-cs/chiventure#1046]
currently, weapons are an item that cannot be used as we had planned before. the existing code in battle_logic uses an item to update a players health, attack, or defense. We want weapons to be able to decrease health, attack, or defense of an enemy. This will involve adding code to the existing function within battle_logice (use_battle_item) to verify that the item is a weapon and calling consume_item given an enemy rather than the player. Additionally we need to update default objects module to produce default weapons in line with this new idea. 
team:battles

**Comment by sonnykaiyuenlee** [comment]
worked on fixing the get_random_default_weapon function in battle_default_object module. There are now 5 default weapons along with descriptions. Each weapon will reduce the enemy's HP, attack stat, or defense stat. Unclear on whether or not we want to keep/assign the effectiveness_decrement to decrement durability of weapon with each use. Will discuss with Laura who is also working on weapons this week.

**Comment by sonnykaiyuenlee** [comment]
Issue with battle_logic: right now there is no way to find a combatant's enemies therefore no way that after checking if an item is a weapon, to call consume_battle_item given an enemy. I think the only solution is to add an additional parameter battle_t to the function use_battle_item so that an enemy combatant can be fed to consume_battle_item

**Comment by sonnykaiyuenlee** [comment]
Add battle_t parameter to use_battle_item so that the function can look for the enemy and feed it to the consume_battle_item function when a weapon is being used. Updated tests for default objects as well as tests for battle_logic to ensure that the function can distinguish between a weapon and a consumable. all tests pass. Did git pull before making and no problems seem to arise.  making pull requests soon

**Comment by firatciftci** [comment]
Issue Score: ✔️+

Comments:
Great work! I only have one thing to comment on:
- When an issue is done, you should include a final comment summarizing what was done, and why the issue is being closed.
