### ISSUE TITLE
(actually) finish basic implementation, documentation and testing of multiclassing

### ISSUE THREAD

**Issue by farm-zaq** [uchicago-cs/chiventure#1047]
This task picks up from where issue 910 (Finish the implementation and integration of multiclassing) left off. It includes the following tasks:
1) Properly combine the attributes of the two classes. Multiclasses have NULL as their attributes right now, which obviously isn't desirable.
2) Update documentation. This includes including all information about multiclassing in relevant readmes, updating the wiki page with any changes that have been made, and moving the todo of the wiki page to issues (which may have to be backlogged).
3) Implement testing for multiclassing. This would also include examining how testing currently works in chiventure.
4) Address concerns raised in the PR.

Further, minor changes (which were part of task 5 in the previous issue) are an important part of multiclassing, but they will be addressed after these more important tasks are addressed.

**Comment by farm-zaq** [comment]
I have created and integrated a helper function to combine the attributes of two classes, meaning that task 1 is complete. I have also added all of Firat's suggestion for the PR, meaning that there is no current work for task 4, although some may be raised.
Because of the completion of task 1, I have updated the name of the PR. This implementation, while certainly in need of work, technically does combine all elements of two or more classes, meaning that it is no longer truly "partial." I have changed this to say "initial."

**Comment by farm-zaq** [comment]
The wiki page has been updated. The large TODO section has removed and (if these do not get finished by the end of the quarter) these will be added to the backlog.

**Comment by farm-zaq** [comment]
The README for playerclass has also been updated to include changes to the player struct and the multiclass function.

**Comment by farm-zaq** [comment]
All merge conflicts have been resolved, meaning that the PR can finally be integrated into the main branch of Chiventure.

**Comment by farm-zaq** [comment]
At the end of this sprint, here is the status of these tasks.
1) This is more or less complete. The current implementation may have to change based on future implementations of class attributes, but attributes are currently being combined.
2) Documentation has been updated. The important parts TODO sections of the wiki page have been converted into backlogged tasks.
3) No testing has been made for multiclassing, meaning no work has really been done on this task. It has been added to the backlog.
4) All concerns and suggestions with the PR were addressed and it was merged into dev.

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Great work on this! The updates that you have provided give a really detailed overview of your work.
