### ISSUE TITLE
Create game demo featuring NPCs, actions, and dialogue

### ISSUE THREAD

**Issue by jeyeong** [uchicago-cs/chiventure#1049]
In preparation for our final presentation, we aim to create a game demo featuring NPCs, actions, and dialogue. This will ideally be a loadable, playable Chiventure game.

**Comment by jeyeong** [comment]
Created a very simple game example featuring only rooms and items. The WDL file has been placed in src/npc/examples.

**Comment by andrewg23** [comment]
After a team meeting we decided on creating a demo based on the Pokemon video game.
The main purpose of this demo is to show the capabilities of NPC dialogue. 
The demo will:

- Have 5 different rooms plus an end room
- Have 3 NPCs, one of which is a Pokemon
- Use dialogue options and conditions in order to simulate a battle with a Pokemon

**Comment by jeyeong** [comment]
Matias, Dylan, and I have developed the backbone of our "Prof. Oak" character, as well as set up all the rooms that are in the game.

Prof. Oak has two key dialogue trees, both of which are conditional: (1) Let the player select their starter pokemon, (2) After the player has captured the Pokemon (Pidgey), give the player the end room codeword, which allows him to end the game.

We will now proceed to develop the dialogue that achieves these two things.

**Comment by jeyeong** [comment]
Room descriptions have been written. In the process of doing so, I realized that when we traverse to a new room, the text that is printed out thereafter is limited to 100 characters, which is too small a limit for our purposes.

To accommodate a longer text prints, I revised the value of BUFFER_SIZE in the `actionmanagement` module from 100 to 300.

**Comment by jeyeong** [comment]
I have finished writing descriptions for rooms. In the process of doing so, I realized that when we traverse to a new room, the text that is printed out thereafter is limited to 100 characters, which is too small a limit for our purposes.

To accommodate a longer text prints, I revised the value of BUFFER_SIZE in the actionmanagement module from 100 to 300.

**Comment by matiasp-10** [comment]
Added in end game dialogue for Prof. Oak. Fairly certain this works, but still need to wait on the development of the "catching Pidgey" sequence to completely verify that the player is indeed given the end room codeword to end the game.

**Comment by pkasner** [comment]
Andrew and I have added a conversation/"battle" with Pidgey. We added items for the starter pokemon and a pokeball to support all the conditional dialogue edges. These items currently are placed in Oak's lab, and can be taken with the take action.

**Comment by MaDDylan** [comment]
Added conditional dialogue for choosing starter pokemon, I also added a Pokeball to oak's inventory and support for giving the player the Pokeball when starting the Pidgey sidequest. A full playthrough was completed.

**Comment by jeyeong** [comment]
Pull request has been merged.

**Comment by lilyehsani** [comment]
Issue Score: ✔️++

Comments:
Great work overall! The updates of this issue are very thorough.
