### ISSUE TITLE
Implement player action making NPC move (definite movement)

### ISSUE THREAD

**Issue by mbutera17** [uchicago-cs/chiventure#1050]
Currently for npc movement, no framework exists for deciding when to move an npc. Existing code that will move npcs between rooms and that handles all other aspects of npc movement exists in either the dev branch or in current pull requests, but does not contain a specific framework for when to move npcs.

Based on the two types of npc movement: definite and indefinite; we can create a framework for definite movement now, and indefinite must be implemented by future teams. From discussion in our meetings, we figured that one possible way to design this framework would be to make the npc move when a game event (in the form of a player action) happens, for example if the player switches rooms. This design is not finalized and is still open for discussion, expect a comment on this issue when we come to a conclusion on the exact framework.

There is also a chance that we are unable to finish this framework by the end of Sprint 4 because of potential difficulties along the way. If this happens, npc movement can still be displayed through monkeypatching.

**Comment by torresszy** [comment]
After the meeting today and our discussion previously, it seems like we need the following functions for our demo:

1. `npc_prints` which will print out all the NPCs in a given room
2. `npc_one_move` which calls the definite/indefinite move functions to move the NPC along its path, remove the NPC from its previous npc_in_room struct, and add the NPC to its new npc_in_room struct

**Comment by mbutera17** [comment]
Xavier's [comment above](https://github.com/uchicago-cs/chiventure/issues/1050#issuecomment-849970692) details the npc_one_move function when given an `npcs_in_room_t *old_npc_room` and  `npcs_in_room_t *new_npc_room`

I was able to rewrite this function without the need for these two, and also renamed the function introduced in Xavier's comment above. 
Thus, in the rooms-npc module, the following two functions exist:
```
/* Moves an npc one step down its path
 *
 * Parameters:
 *  - npc_t: Pointer to NPC
 *
 *  Returns:
 *   - SUCCESS on success, FAILURE if error or NPC cannot be moved
 */
int npc_one_move(npc_t *npc);

/* Moves an npc one step down its definite/indefinite path, 
 * deletes it from it's old room, and adds it to its new one
 *
 * Parameters:
 *  npc_t: Pointer to an NPC
 *  npcs_in_room_t: Pointers to the old and new npcs_in_room structs
 *
 * Returns:
 *  SUCCESS on success, FAILURE if an error occurs or if NPC is cannot be moved
 *
 *  NOTE:
 *   - This function is only useful if the npcs_in_room structs for the current
 *   and next rooms are already known. If not, call npc_one_move
 */
int npc_one_move_helper(npc_t *npc, npcs_in_room_t *old_npc_room,
                npcs_in_room_t *new_npc_room);

```

**Comment by mbutera17** [comment]
We also did a lot of brainstorming in this sprint about the possibility of moving all NPCs in one function (which would have allowed us to reach our final goal), but we were unfortunately not able to start implementation due to time constraints. Thus, we will leave much of our brainstorming on this feature on our [Wiki page](https://github.com/uchicago-cs/chiventure/wiki/NPC-~-Independent-Feature:-NPC-Movement-Design-Document) for future chiventure teams working on NPC movement.

**Comment by torresszy** [comment]
I also added a new CLI function, `npcs_in_room_operation`, in `operation.c` and `operation.h` that prints out all the NPCs whose health is above 0 (i.e, alive) in the current room:
```
/*  
* 
* Parameters: 
*  - tokens: parsed input string 
*  - ctx: pointer to a chiventure context struct 
* 
* Returns: 
* - lists NPCs that are in the room a player  
* is currently in as a list 
*/
char *npcs_in_room_operation(char *tokens[TOKEN_LIST_SIZE], chiventure_ctx_t *ctx);
```
We will also showcase this feature in our demo.

**Comment by lilyehsani** [comment]
Issue Score: ✔️++

Comments:
Great work overall! The summary and updates of this issue are very thorough.
