### ISSUE TITLE
Implement quests into the game state

### ISSUE THREAD

**Issue by dillonoloughlin** [uchicago-cs/chiventure#1052]
We plan to implement quests into the game state through adding the following:

- Add an all_quests hash table in the game struct
- Creating a load_quest.c file in the wdl/src directory with an add_quests_to_game() function, that will be called by the load_yaml_game() function in wdl/load_game.c file
- Adding an add_quest_to_game() function to game_state/game.c file which will be iteratively called by add_quests_to_game()
- Adding a get_quest() function to game_state/game.c file
- Adding a delete_all_quests() function to quests/quest_state.c

Assignees: Dillon, Zach
team:quests

**Comment by dillonoloughlin** [comment]
In order to create a very basic but usable version of quests in the game struct, we have decided to first implement the all_quests hash table field in the struct and then a function to add quests to that table called add_quests_to_game, and then another function to pull quests from the table called get_quest(). We have implemented these features and submitted a PR.

**Comment by lilyehsani** [comment]
Issue Score: ✔️+

Comments:
Great work overall! I have one comment:
- For a task of this size, we would've expected to see more status updates and/or status updates that were more detailed, such as what we will be done about the incomplete tasks in the summary.
