### ISSUE TITLE
Allow player_t to store and gain moves

### ISSUE THREAD

**Issue by adinilfeld** [uchicago-cs/chiventure#1053]
Currently, there is no way for a player to unlock moves for future use in battle. To pave the way for future implementation of this functionality, we will add a linked list of `move`s to the `player_t` struct, and refactor the `add_move` function to take in a `player_t` instead of a `combatant_t`.

**Comment by adinilfeld** [comment]
So far, I added a "moves" field to the player_t struct, and transferred the `add_move` function from battle_move_maker to player. Next steps will be figuring out how best to integrate the `execute_move_effect` function, as well as figuring out how to transfer the unit tests for `add_move` (which are currently inside of `tests/battle/`).

**Comment by adinilfeld** [comment]
After moving the tests over to `test_player`, there seems to be some issue with the tests crashing, which I'll have to look into further.

**Comment by adinilfeld** [comment]
Managed to fix the unit tests in `test_player` -- one of them had been adding an item to the player before adding the move, but it was a `battle_item_t`, which `player_t` wasn't meant to hold. So now those work, and @tgao564 to finish up the integration with skilltrees.

**Comment by adinilfeld** [comment]
This issue has now been completed. The `player_t` struct now has a field to store a linked list of moves; the `add_move` function has been refactored to take in a `player_t` instead of a `combatant_t`; and `add_move` has been moved from battle to player. Lastly, the unit tests associated with `add_move` were moved from battle to player as well, and now pass successfully.

This issue will be closed when the associated pull request in approved.

**Comment by tgao564** [comment]
The abovementioned pull request Skilltrees/effect_v2 #1110 has been initiated. Due to its size, it may not go through before the code soft-lock goes into place. Will finish the tests for move-based skills if the PR goes through in time. Otherwise, will leave a backlog issue for next year to finish my implementation.

**Comment by adinilfeld** [comment]
A pull request has been opened which closes this issue. See the summary message from above: 

> This issue has now been completed. The `player_t` struct now has a field to store a linked list of moves; the `add_move` function has been refactored to take in a `player_t` instead of a `combatant_t`; and `add_move` has been moved from battle to player. Lastly, the unit tests associated with `add_move` were moved from battle to player as well, and now pass successfully.

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Great work on this! The updates that you have provided give a really detailed overview of your work.
