### ISSUE TITLE
Create sandbox example for demo of the DSL feature

### ISSUE THREAD

**Issue by tessied** [uchicago-cs/chiventure#1054]
Our goal is to create a sandbox with example files to demonstrate the features of the DSL we have been working on this quarter. This demo will be presented during the final presentation.

Note: while adding this issue to the backlog, we considered the fact that this issue would depend on how far we get in terms of our implementation. 

Assignees: John and Tessie
team:dsl

**Comment by tessied** [comment]
We had a team meeting where we discussed what we wanted to include in the demo. We decided that we wanted to have a standard DSL file that has the main features of the grammar. One thing we noted was that we cannot use custom actions as they are not currently supported in chiventure. Once we finish up the DSL file, we will test it with the parser and attempt to load the game in chiventure.

**Comment by tessied** [comment]
I created a new branch `dsl/demo` and made a new directory `demo_example` where you can find the `demo.dsl`. I was able to successfully load it into chiventure after fixing the errors, but actions currently do not work (commit [`48e77f0`](https://github.com/uchicago-cs/chiventure/commit/48e77f07ed1203cc08b541b912c27994c7b4976d)) For example, when I specify the action `TAKE` under an object, in the game it says the action is not supported for the object.

**Comment by tessied** [comment]
I received help from @r-e-stern and fixed the issues regarding actions (commit [`3daa30a`](https://github.com/uchicago-cs/chiventure/commit/3daa30ae1978f0eb432d666d85ab5548d9b09f3e)). I changed all calls to `USE`, `DRINK`, and `EAT` to `CONSUME`, and now the actions can be run in chiventure. We will add a backlog issue specifying that in the future, the parser should be able to convert all calls to USE`, `DRINK`, and `EAT` to `CONSUME` on its own.

**Comment by tessied** [comment]
The pull request linked to this issue reflects the changes made, that is, a demo file `demo.dsl` is now included in `src/dsl/examples/dsl` which has our standard example of a game written in our DSL that we will present. Pull request has been merged, closing the issue.

**Comment by tessied** [comment]
The pull request linked to this issue reflects the changes made, that is, a demo file `demo.dsl` is now included in `src/dsl/examples/dsl` which has our standard example of a game written in our DSL that we will present. Pull request has been merged, closing the issue.

**Comment by ecoble** [comment]
Issue Score: ✔️++

Comments:
Great work creating this demo, and updating this issue with your progress!
