### ISSUE TITLE
Create a load_npc module to load NPCs from a wdl_ctx struct

### ISSUE THREAD

**Issue by jeyeong** [uchicago-cs/chiventure#1055]
Currently, Chiventure is able to load rooms and items from a wdl_ctx struct. By extending this to NPCs, we can add NPCs to the game from a WDL file.

**Comment by jeyeong** [comment]
Created a preliminary load_npc module (within wdl) that allows Chiventure to load NPCs from a WDL file. In order to make this module work, I had to make changes to a series of other files, including:
- wdl/load_game.c
- wdl/parse.c
- wdl/validate.c
- Their associated header files

The implementation of load_npc is analogous to load_item. In order for Chiventure to build, I also had to modify CMakeLists.txt.

All these changes are performed under the npc2/npc-wdl branch.

**Comment by jeyeong** [comment]
I have completed the implementation of the load_npc module, and have adapted it to work with the new libobj implementation. NPCs may now be loaded from WDL files using the "NPCS" key. Here is an example of how NPC objects should be formatted:
<img width="177" alt="Untitled" src="https://user-images.githubusercontent.com/7861185/119271519-86d62800-bbc7-11eb-8d95-91a14373c766.png">

**Comment by jeyeong** [comment]
I should note that currently, NPCs have not been integrated into rooms yet. I am working with NPC team 1 to get that implemented. Once that is done, I will update the load_npc module to add NPCs to rooms.

**Comment by jeyeong** [comment]
Given the recent merging of two pull requests: (1) conditional dialogue + actions, and (2) NPC room integration, I have been working on giving us the ability to load into Chiventure those features.

Node actions can now be loaded into Chiventure, via this syntax:
![image](https://user-images.githubusercontent.com/7861185/119605552-9cf60b00-bdb6-11eb-960b-2787268e6580.png)

**Comment by jeyeong** [comment]
`load_npc` now supports the loading of both conditional dialogue and dialogue actions. They should be loaded in the following manner:
![119824394-7a99e580-bebb-11eb-872a-f48748d08dd1](https://user-images.githubusercontent.com/7861185/119830552-00209400-bec2-11eb-95cf-4191743fdf77.png)

Since NPCs have now been integrated into rooms, I have also revised the code to add NPCs to rooms. This is required for the \<talk to> command to work correctly.

**Comment by jeyeong** [comment]
As a note, since NPCs cannot currently belong to two hash tables (1. game->all_npcs and 2. room->npcs, for instance), I took caution to avoid adding NPCs to two different hash tables. However, as this is not ideal, I have added the appropriate comments to inform future classes of why specific code are omitted, and to uncomment them once the multiple hash tables are supported for NPCs.

**Comment by jeyeong** [comment]
As a note, since NPCs cannot currently belong to two hash tables (1. game->all_npcs and 2. room->npcs, for instance), I took caution to avoid adding NPCs to two different hash tables. However, as this is not ideal, I have added the appropriate comments to inform future classes of why specific code are omitted, and to uncomment them once multiple hash tables are supported for NPCs.

**Comment by lilyehsani** [comment]
Issue Score: ✔️+

Comments:
Great work overall! I have one comment:
- The summary for this issue is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/policies.html#tasks-issues for examples). If this issue was generated from a Scrum board card, please remember that the summary you write in the Sprint meeting is meant to be a quick draft; it needs to be fleshed out when you convert the card to an issue.
