### ISSUE TITLE
Create the design for attribute modification effects

### ISSUE THREAD

**Issue by mariakravtsova** [uchicago-cs/chiventure#1056]
The design for attribute modifying effects (as it turned out, the confusing naming of different effect types and the inventory module resulted in incorrect implementation of attribute (object) modifying effects) was flawed, so it needs modification so that attribute and statistic modifying effects are different.

**Comment by rohangupta2806** [comment]
We decided to split item effects into 2: item attribute effects, and item statistic effects.  Item attribute effects are now implemented and we are writing tests for it.

**Comment by rohangupta2806** [comment]
Tests for item attribute effects were written and a pull request that shows the implementation of attribute modifying effects has been submitted and linked to this issue.  We also ended up creating a new atomic effect called item statistic mod that should be implemented next.

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Great work!
