### ISSUE TITLE
Implement talk to NPC operation

### ISSUE THREAD

**Issue by pkasner** [uchicago-cs/chiventure#1059]
For the implementation of NPC actions, we've determined that actions that implement game logic at a higher level than just changing an attribute or transferring possession of an item should have there own operation always added to chiventure's lookup table. This includes the talk action, which needs to change chiventure to conversation mode and start the npc's conversation. We will implement that operation.
Assignees: Peter, Dylan
team:npc2

**Comment by pkasner** [comment]
I've added basic mode switching to the talk_operation function, but additional parsing/case handling is still necessary. Additionally, PR #999  must be merged before the talk_operation can be tested in any capacity.

**Comment by pkasner** [comment]
I've added parsing to the talk_operation function, so it now accepts the format "talk ___ npc_id", where the blank is presumably the word "to". If not in this format, the function prompts the user to identify someone to talk to. I'm not sure what the best response is if the user enters "talk randomtext npc_id", so for now it still initiates a conversation.

**Comment by pkasner** [comment]
Currently, the room where an npc resides is not stored by chiventure, but @jeyeong has a pull request to fix this. Once this pull request is merged, the talk_to_operation branch should be able to be merged quickly.

**Comment by lilyehsani** [comment]
Issue Score: ✔️++

Comments:
Great work overall! The summary and updates of this issue are to-the-point.
