### ISSUE TITLE
Integrate our code with Action Management

### ISSUE THREAD

**Issue by ecoble** [uchicago-cs/chiventure#106]
Once a command has been validated, create an action struct from it using action management's functions, and pass the action along to action management's operation functions

**Comment by efraimdahl** [comment]
Just updated our pass on functions to match the new kind of supported actions by action_management

**Comment by Tianlel** [comment]
We need to add the function that takes in action management's list of supported actions and returns our action hashtable.

**Comment by ecoble** [comment]
UPDATE: Having a lot of issues with the Makefile and trying to include action management's functions, working on changing the makefile

**Comment by ecoble** [comment]
UPDATE: The Makefile was finally fixed and we were able to include action management's functions. get_supported_actions is being used to fill the hashtable from the specified actions list, do_action_item, do_path_action, and do_item_item_action are being used in type 1, 2, and 3 operations respectively.

**Comment by ecoble** [comment]
CLOSING STATEMENT: We were able to link with action management's library (hooray!). Each action operation (type 1, 2, and 3) first verifies that an object/path/objects are in a room via game state's macros, and if they are, action management's functions are called with the current game, an action struct that is looked up from the hashtable, and the item/path/items being acted on. 

Validation updates are not included on this issue as they were part of issue #105, validating commands and objects exist.

As mentioned in a previous update, action management's action will not work until they update their list of actions.

**Comment by lydiafilipe** [comment]
Issue Score: ✓+

Comments:
Good work!
