### ISSUE TITLE
Create new CLI context struct (pending history command merge)

### ISSUE THREAD

**Issue by dchen0258** [uchicago-cs/chiventure#1060]
Currently the command_history is set to be in the chiventure_ctx struct, however, if more cli specific features are to be added, it makes sense to create a new cli_ctx struct to contain this information. The command_history and lookup table should both be placed in this new struct, and any future cli specific information.

**Comment by dchen0258** [comment]
This issue should consist of: 
- Creating new struct in a new header file (similar to how the ui context struct is constructed)
- Putting the look up table and command history
- Refactoring all code that references ctx->lookup or ctx->command_history to reference the cli_ctx struct

**Comment by Beza20** [comment]
The creation of a new module: cli_ctx.c to handle the new struct was a good idea and is now in the cli/ctx branch. The module now has 2 functions to allocate and free the struct. I am trying to see whether or not to add a particular function to initialize the struct like we have almost all other structs. We will address this issue after further correspondence with @dchen0258 and maybe @ecoble

**Comment by dchen0258** [comment]
Pull request submitted.

**Comment by dchen0258** [comment]
Closing statement:
This struct was aimed at making it easier for future cli specific components to be added, so hopefully future classes will find some cool enhancements!

**Comment by ecoble** [comment]
Issue Score: ✔️++

Comments:
Excellent work making the new context struct!
