### ISSUE TITLE
Create documentation for next year's group

### ISSUE THREAD

**Issue by r-e-stern** [uchicago-cs/chiventure#1063]
Expand the documentation already created for the DSL grammar (user stories, wiki page) to cover all code and design done this quarter

**Comment by r-e-stern** [comment]
Things we should do:
- [ ] Update the [DSL grammar wiki page](https://github.com/uchicago-cs/chiventure/wiki/DSL-~-DSL-Grammar) with the additional features we've added this year (like #998)
- [ ] Document the "integration" of the DSL feature with `chiventure` by writing a "how to write a Chiventure game with DSL"-type wiki page
- [ ] Fully comment the grammar, parser, and to-wdl files
- [ ] Write an informal "intro to the DSL" document explaining how the current design works

**Comment by r-e-stern** [comment]
In the process of preparing to merge #938, @jacknugent1529 and commented the code, and updated the [`README.md`](https://github.com/uchicago-cs/chiventure/tree/dsl/to-wdl/src/dsl#readme) file in the `src/dsl` directory to include instructions on how to install the Lark parser, write a DSL file, and convert a DSL file to WDL.

**Comment by r-e-stern** [comment]
I've updated the [wiki page](https://github.com/uchicago-cs/chiventure/wiki/DSL-~-DSL-Grammar) with sections on:
* [Connections](https://github.com/uchicago-cs/chiventure/wiki/DSL-~-DSL-Grammar#connections)
* [Actions](https://github.com/uchicago-cs/chiventure/wiki/DSL-~-DSL-Grammar#actions)
* [Variables](https://github.com/uchicago-cs/chiventure/wiki/DSL-~-DSL-Grammar#variables)
* [Default properties](https://github.com/uchicago-cs/chiventure/wiki/DSL-~-DSL-Grammar#defaults)

**Comment by Mich0608** [comment]
After discussing with the team, I will be helping out with the documentation by creating a "intro to the DSL" wiki page that explains the directory structure and modules of the DSL feature, including the functionality of the different files.

**Comment by Mich0608** [comment]
I wrote the [Intro to the DSL Feature](https://github.com/uchicago-cs/chiventure/wiki/DSL-~-Intro-to-the-DSL-Feature) wiki page that introduces the DSL feature and its various modules.

**Comment by r-e-stern** [comment]
Gonna call this one done. The `src/dsl` directory, our code, our example files, and the wiki are all pretty well-documented now, to the point where I think (read: hope) that other will be able to fairly easily pick up where we left off. A recap of where all the documentation lives as of now:

- The `chiventure` repository
    - General notes in the README file at [`src/dsl/README.md`](https://github.com/uchicago-cs/chiventure/tree/dev/src/dsl#readme)
    - Inline code comments within each Python file in the [`src/dsl/src`](https://github.com/uchicago-cs/chiventure/tree/dev/src/dsl/src) directory
    - Comments explaining relevant parts of the test `.dsl` files in the [`src/dsl/examples/dsl`](https://github.com/uchicago-cs/chiventure/tree/dev/src/dsl/examples/dsl) directory
    - The `.lark` files (and especially the autogenerated `.wdl` files) are poorly documented by comparison
- The project wiki
    - The general structure of the DSL feature's design is written up in the **[Intro to the DSL](https://github.com/uchicago-cs/chiventure/wiki/DSL-~-Intro-to-the-DSL-Feature)** wiki page
    - The current syntax specifications of the DSL, along with an outline of supported features, is written up in the **[DSL Grammar](https://github.com/uchicago-cs/chiventure/wiki/DSL-~-DSL-Grammar)** wiki page
    - Our general goals and ambitions for the DSL, most of which have since been achieved, are archived in the **[DSL User Stories](https://github.com/uchicago-cs/chiventure/wiki/DSL-~-User-Stories)** wiki page
- Other sources
    - Our archive of [issues and pull requests](https://github.com/uchicago-cs/chiventure/labels/x%2Fdsl) may be useful reference material for future groups 
    - The [Lark parser's documentation](https://lark-parser.readthedocs.io/en/latest/) might come in handy

Closing the issue.

**Comment by ecoble** [comment]
Issue Score: ✔️++

Comments:
Great job creating such thorough documentation! This will be super helpful to future teams!
