### ISSUE TITLE
Implement changes to Branch Blocks and do_branch_block

### ISSUE THREAD

**Issue by LapsededPacifist** [uchicago-cs/chiventure#1068]
Currently in Custom Actions, Branch blocks are not implemented in a manner that lets them be ran. The struct needs to be modified and then an evaluation function needs to be written.
See [the wiki](https://github.com/uchicago-cs/chiventure/wiki/Custom-Actions-~-Current-State-and-Future-Plan-of-Custom-Actions) for exact specifics for the new intended struct format.

There needs to be an update to the exist branch block functions with the new format, and then integration into run_custom_action with a  do_branch_block function that runs a branch block.

**Comment by LapsededPacifist** [comment]
Since [PR 1065](https://github.com/uchicago-cs/chiventure/pull/1065) was just merged, work can begin on do_branch_block and modifications of the tests. This was delayed before to avoid integration mistakes.
Concerns before implementation begins, for loops might be painful. The attribute compare functions only compare two attributes, so branch blocks with for loops are going to need a dummy attribute that starts at 0 and counts up to a specific number. A helper function will almost certainly have to be made for this since it will probably end up requiring several steps in order to make properly. Unless implementation for adding a constant to an attribute is added, there will also need to be a incrementing attribute created as well.

**Comment by LapsededPacifist** [comment]
I deleted most of the branch block tests. Previously there had been tests for each of the possible conditional enums, which didn't make any sense. The conditional enum field of branch blocks was replaced with the control type field, but I did not move the tests over to the control type field. The different enums don't have any functional difference when initializing or freeing, so the extra tests were removed.
Tests will need to be written for the different enums when actually executing a branch block.

**Comment by LapsededPacifist** [comment]
The execution of for loops is the same as while loops in branch blocks currently. They just currently require a specific method of being set up. I believe that it will be best if a function to create for loops is create since they will be creating a lot of their own attributes. This will probably require the branch_block_free function to be modified for freeing the attributes that are unique to the for loop.

**Comment by LapsededPacifist** [comment]
Overview of updates made:
Successfully modified branch blocks to be in line with [the wiki](https://github.com/uchicago-cs/chiventure/wiki/Custom-Actions-~-Current-State-and-Future-Plan-of-Custom-Actions). All corresponding existing functions were updated.
Do_branch_block was also implemented to all for the use of loops and ifs.
 - Things to note here, loops only take one AST_block as inputs since it is a list. Ifs take as many AST_blocks (Or +1 for else) as there are conditionals, so that there is a block corresponding to each if/elif.
 Updated TRUE to 1 and FALSE to 0. It was conflicting with the definitions in CLI, which was causing errors when building. 
 
 Created an [issue](https://github.com/uchicago-cs/chiventure/issues/1132) for creating FORENDFOR blocks. Currently, their implementation is the same as WHILEENDWHILE blocks in terms of how they run. However, they should have a function that makes them easier to create as the standard definition of a for loop is going to make the creation of every for loop basically the same.

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Great work overall! While it's helpful to link to the wiki in the summary, when there's one key piece that a reader needs to know (in this case, a struct definition) it may be helpful to copy and paste that in as well.
