### ISSUE TITLE
Design document for NPC visuals and dialogue visuals 

### ISSUE THREAD

**Issue by eao10000** [uchicago-cs/chiventure#1071]
Currently the GUI module does not include non-player characters (NPCs) graphics or dialogue graphics. Since we hope to fully integrate GUI into chiventure, and GUI should be able to support all aspects of game generation.  For the future of GUI it is crucial that GUI is compatible with other modules. With the main focus in this instance being the NPC modules. 

In this sprint, we plan to write a design document discussing how to include and create the graphics of NPC and their dialogue. Doing this by looking through NPC wikis and player.h structs to see how to successfully utilize and create NPC in the GUI for chiventure.

**Comment by eao10000** [comment]
When into NPC's dev chat and figured out the usage of the npc_id. Plan to use this npc_id to help with the graphic and dialogue and will be writing the design soon.

**Comment by eao10000** [comment]
When discussing with npc found out that in the future GUI and NPC will have to work together setting images and npc_id when creating a new game as the npc_id is unique every game.

**Comment by eao10000** [comment]
With this not be tied to a pull request here is the link to the wiki https://github.com/uchicago-cs/chiventure/wiki/Graphics-~-Design-Document-for-NPC-Graphics-and-Dialogue.

**Comment by eao10000** [comment]
With this comment I will be closing this issue. In this issue Justin and I were able to create the wiki page to help future GUI teams when they plan to make the NPC and dialogue graphics. The wiki contains image examples, information needed, as well as a rough draft of the h file to help guide the future coders when they fulfil this implementation.

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Excellent work! Your updates are particularly clear, concise, and useful.
