### ISSUE TITLE
Fix attribute_new in custom-action-cond.c

### ISSUE THREAD

**Issue by GravitasFreeZone** [uchicago-cs/chiventure#1072]
Currently the function: `attribute_t *attribute_new(enum attribute_tag tag, attribute_value_t value)` does not function properly.
It does not have a return value and it does not strdup the attribute key as it is just being set to null. 
A return value needs to be added, so it functions at all. I am not sure how it actually doesn't crash now.
Strduping the attribute key will allow it to be freed using attribute_free, since that attempts to free the attribute_key.

This function should also probably be moved to item.c, since that is where all of the other functions for creating attributes are. 
Since there are an array of other new_attribute functions already in item.c,  attribute_new could also be removed and all the tests updated to use the already existing functions.

**Comment by HarrisonD123** [comment]
Reading through code in both the custom-actions directory and the game-state directory to better understand what an attribute is. Maybe more documentation is needed to make things clearer?

I understand what the creator of this issue means by "I am not sure how it actually doesn't crash now." The function attribute_new is set to have a return value of type attribute_t (found in the chiventure/include/game-state/item.h file), but the code doesn't break despite not having any return value in the function. Perhaps an include error?

**Comment by Don-Osipov** [comment]
Took the following advice from initial issue comment: "Since there are an array of other new_attribute functions already in item.c, attribute_new could also be removed and all the tests updated to use the already existing functions."
Removed the bugged function in question (attribute_new) and updated all tests that previously used the function to instead use the attribute-type-specific attribute creator functoins found in item.c.

**Comment by Don-Osipov** [comment]
**Closing Statement**

This issue has been completed by removing the bugged function (attribute_new) and updating all the tests that previously used the function to instead use the attribute-type-specific attribute creator functions found in item.c. Implementation was completed by Don Osipov, but Harrison Dong and Kendrick Xie contriuted to the decision-making process and understanding of the code.

**Comment by ecoble** [comment]
Issue Score: Excellent

Comments:
Nice job debugging this backlog issue!
