### ISSUE TITLE
Work on loading classes from WDL

### ISSUE THREAD

**Issue by jackcasey067** [uchicago-cs/chiventure#1079]
The goal of this issue is to be able to load classes from WDL.  Depending on what hurdles I encounter along the way, I may not finish this in its entirety.  A partial implementation (perhaps using stubs for tricky steps like loading stats or skills) would be a reasonable outcome.  Alternatively, a specification of what a class should look like in WDL would probably be good too.

**Comment by jackcasey067** [comment]
The branch `playerclass/WDL-loading` has been set up for these changes.  Most of the code will actually live within the wdl module.  Also, this branch pulled in changes from my last branch `playerclass/hashtable,` since we need a hashtable to store loaded classes together.

Finally, I figured out how to test the wdl files.  I will make a new file in the `tests/wdl/examples/wdl/` directory, and run something similar to this command from the build directory:

`./chiventure ../tests/wdl/examples/wdl/connected-rooms.wdl`

**Comment by jackcasey067** [comment]
```
"CLASSES": {
        "Warrior": {
            "short_desc": "Warrior's short description",
            "long_desc": "Warrior's long description",
            "attributes": {
                "noble": true,
                "hot-headed": true
            },
            "base_stats": {
                "health": {
                    "current": 100,
                    "max": 200
                },
                "mana": {
                    "current": 20,
                    "max": 100
                }
            },
            "effects": null,
            "skill_tree_t": null,
            "starting_skills": null
        },
        "Rogue": {
            "short_desc": "Rogue's short description",
            "long_desc": "Rogue's long description"
        }
    }
    ```
    
    Here is my current example JSON object for a game's classes (taken from `tests/wdl/examples/wdl/classes.wdl`).  I have some reservations about stats right now, and depending on how far I get I might just leave / ignore effects and skills.

**Comment by jackcasey067** [comment]
I have run into one of the most infuriating and nonsensical linking errors possible.  If I can't figure it out, I may abandon trying to load prefab classes.

```
class_t* class = NULL;
    if (obj_get_type(class_obj, "prefab") == TYPE_BOOL && obj_get_bool(class_obj, "prefab")) {
        class = class_prefab_new(game, "monk"); // Still messing around
    }
```
Under normal conditions, the linker complains when it tries to build the chiventure executable.
```
 49%] Building C object CMakeFiles/chiventure-bin.dir/src/chiventure.c.o
[ 49%] Linking C executable chiventure
/usr/bin/ld: src/wdl/libwdl.a(load_class.c.o): in function `load_class':
/home/jcasey/cs/cmcs22000/chiventure/src/wdl/src/load_class.c:10: undefined reference to `class_prefab_new'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/chiventure-bin.dir/build.make:114: chiventure] Error 1
make[1]: *** [CMakeFiles/Makefile2:961: CMakeFiles/chiventure-bin.dir/all] Error 2
make: *** [Makefile:95: all] Error 2
```
This is despite the fact that the playerclass library has already been built, and that (without the call to class_prefab_new here), this function is well tested in the player class tests (the linking for those is completely fine).
Also (using a vscode extension) I went into the libraries to see if class_prefab_new is actually undefined.  It is not; it is defined where you expect it.

What is weirder is the accidental 'solution' I found.  The class_prefab_new function lives in class_prefab.c, but functions from class.c are linking fine.  If you put this:
```
void please_dont_touch_my_trash() {  
    class_t* my_trash = class_prefab_new(NULL, "");
    class_prefab_add_skills(my_trash); // This function is also having trouble linking
    return;
}
```
in class.c, the whole thing compiles and works.  Simply adding a reference in an unrelated file seems to fix things.
This function is never called.  It is not even exposed in any .h files.  This should not work, but it does.

**Comment by jackcasey067** [comment]
I found a much more tenable solution:
```
# Adding playerclass and skilltrees prevents certain undefined reference errors
# the chiventure executeable.
target_link_libraries(wdl libobj playerclass skilltrees ${JSONC_LIBRARIES} ${LIBZIP_LIBRARIES})
```

**Comment by jackcasey067** [comment]
load_class is essentially done: 
 - I am leaving out effects for now, since I am unsure about their interaction with class.
 - I am also leaving out skills, since the skill structs (namely, skill effects) are rapidly changing, and the skilltrees team would be better suited for defining skill and skilltree structure in JSON.  Arguably, these should go in a new top-level attribute, SKILLS.

**Comment by jackcasey067** [comment]
The validation and the tests have been improved.  The branch `playerclass/WDL-load` is now being reviewed as part of PR #1086.
I did not implement effects or skill loading, which will probably have to wait for next year.

I'll leave this issue open for a little bit, I may decide to update documentation as part of this issue.

**Comment by jackcasey067** [comment]
Closing Statement:

I did decide to create a wiki page, which explains the current state of the WDL format for classes (https://github.com/uchicago-cs/chiventure/wiki/Player-Class-~-Loading-Classes-from-WDL).  As such, this issue is now closed.

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Great work!
