### ISSUE TITLE
Add input sanitizing to parser

### ISSUE THREAD

**Issue by ecoble** [uchicago-cs/chiventure#108]
Small issue, add input sanitizing to parser so that user does not input malformed command

**Comment by ecoble** [comment]
UPDATE: Added input sanitization to the parser, if the user tries to enter more than the allowed amount of words (currently 4), an error message is printed and the parser returns NULL

**Comment by ecoble** [comment]
UPDATE: Added a null catch in the function cmd_from_string which calls parse. The hashtable cannot handle NULL as an input, so if parse returns NULL there is an if statement to catch this that will return NULL for the function cmd_to_string. Anyone using cmd_to_string should check if the command returned is NULL and display an error message accordingly.

**Comment by ecoble** [comment]
UPDATE: The first word the user inputs is now capitalized, this will help on matching user input to commands. User input is no longer case sensitive, before the user would have to type "QUIT" to quit, now they can type both "quit" and "QUIT" (or any variation of lower and uppercase letters if they so choose)

**Comment by ecoble** [comment]
CLOSING STATEMENT: The parser now checks that the user has not inputted more than 4 words, and if they have an error is printed and the parser returns NULL. The entire first word the user inputs (the command word) is capitalized (e.g. help -> HELP) before it is outputted, so that the user does not have capitalize it on their own for the command to properly match with other lists of actions being used later on in the program.

**Comment by lydiafilipe** [comment]
Issue Score: ✓+

Comments:
Good work! Great details and updates
