### ISSUE TITLE
Update help text to reflect recent changes

### ISSUE THREAD

**Issue by mjgoodman321** [uchicago-cs/chiventure#1084]
Assignees: Marcus

Updating help text to include recently added or implemented changes

**Comment by mjgoodman321** [comment]
Updated help text to include the QUIT and HIST commands, implemented in issues #273 and #271, respectively, and modified LOAD [PATH] to reflect its implementation in issue #1030

**Comment by mjgoodman321** [comment]
Problem with cli/update-help-function branch: for some reason it includes changes made in the cli/case-insensitivity branch that are causing it to fail tests and otherwise not work as intended. In the process of removing.

**Comment by mjgoodman321** [comment]
After removing unexpected insensitivity additions, added three more entries to help function for ITEMS, TALK, and CREDITS commands

**Comment by ecoble** [comment]
Issue Score: ✔️+

Comments:
Great job updating the help text! Be sure to include closing statements on issues, even if they are closed through a PR.
