### ISSUE TITLE
Update the openworld feature wishlist

### ISSUE THREAD

**Issue by ahmed-sumaiya** [uchicago-cs/chiventure#1085]
Update the [Feature Wishlist](https://github.com/uchicago-cs/chiventure/wiki/Open-World-~-Feature-Wishlist) wiki page with changes made to the openworld module this year and make a list of potential new features to be implemented for next year

**Comment by ahmed-sumaiya** [comment]
The [feature wishlist](https://github.com/uchicago-cs/chiventure/wiki/Open-World-~-Feature-Wishlist) wiki page has been updated with a list of changes made to the openworld module this quarter:
- Level-oriented room generation (issue #882)
- Autogeneration of rooms within a radius (issue #925)
- Item-Room Association Structs (issue #1035)
- Refactoring (issues #982, #1033, #1034)

as well as a list of potential new features for next year, e.g. static generation, dynamic generation, environmental effects, theme structs, etc.

This marks the end of the issue.

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Great work! Your closing summary is particularly well-done.
