### ISSUE TITLE
Map-Drawing: Add unit tests for functions related to assigning coordinates

### ISSUE THREAD

**Issue by adomiter** [uchicago-cs/chiventure#109]
This issue is a continuation of the previous task related to assigning coordinates for map drawing (#47). For this issue, unit tests will be implemented using criterion to check the functions that were written for assigning coordinates. Also, any conflicts between the dummy structs and the structs created by game-state should be resolved. As part of this task, any new functions that relate to map drawing will be supplemented with tests as well. We would like for our functions to pass all tests, so that not only will WDL be able to call on our 'check_valid_map' and have it work, we will also be able to move onto integrating these functions with the map module.

**Comment by adomiter** [comment]
**First Set of Unit Tests:** 
The first set of unit tests were written using the dummy structs and thus relied on the structs that were present within the h file that we had initially written. 

Problems: the dummy structs did not coincide with the structs that game-state was using.

**Comment by adomiter** [comment]
**Second Set of Unit Tests:**
After the team meeting, I moved the "dummy" structs into its own h file within the test folder. This allowed me to call on structs that only included necessary 

Problems: We realized that Sam had written different versions of the same structs that we wrote. Thus, after deciding to on which structs were better suited to map drawing, I rewrote the unit tests to take in structs similar to Sam.

**Comment by adomiter** [comment]
**Last Set of Unit Tests:**
At the moment, I am refactoring the unit tests to reflect the changes that Sam and Olivia made in regards to creating a foundation for "up" and "down" directions and how this appears as an extra coordinate. 

Problems: As I was writing the tests, I realized that there was a possibility of an infinite loop within the DFS function given that the 'adjacency list' which game state wrote as a hash table consists of pointers to rooms which then have their own 'adjacency list' with pointers to other rooms and so on. So far, the way that we have written the function prevents this issue from happening, but I would like to make more elaborate maps to test the function on.

**Comment by adomiter** [comment]
Things to Note:
As we continue to refactor other map related functions, these tests are likely to evolve and change. Right now, it is safe to say that our fundamental functions are working correctly and have been called upon the map-drawing functions successfully. 

Game-State: In regard to game-state's function that they provided us with, I am assuming that this function works completely and will not prove to cause any issues in our function. I have written the tests to assume that this function returns the right value. 

DFS: The tests for this function will need to be revisited and refactored as the "up" and "down" directions will be added in the next sprint. This will not prove to be a huge issue as I will only need to add more test cases.

**Comment by adomiter** [comment]
The Context Struct: When the context struct is merged into master, I will revisit the tests and modify them to take in the values within the context struct.

**Comment by adomiter** [comment]
_Another Note: I am having trouble pushing my code, which may have to do with the feature branch that I created based on the previously made ui/assign-coordinates branch. This is the reason why I haven't been able to close this issue. I will ask for help regarding this problem during lab tomorrow._

**Comment by adomiter** [comment]
I was able to push my branch to the repository, but it is empty at the moment for some reason. (https://github.com/uchicago-cs/chiventure/tree/ui/coordinate-unit-tests) I will try to retrieve my past commits.

**Comment by adomiter** [comment]
Closing: My code has successfully been pushed to the repository. My last commit is present, but I don't see my previous ones. I used git reflog as per Mark's suggestions. Anyways, the current tests will need to be refactored to include game-state's function "find_room_from_dir" as well as updated to test the directions 'up' and 'down'. Sebastian will take over refactoring in the next sprint.

**Comment by adomiter** [comment]
@mpcsh Can I close this issue and continue on to another one (e.g. Refactoring Unit tests to account for new context struct, directions, and function from game-state) for this last sprint that will be done in collaboration with Sebastian?

**Comment by mpcsh** [comment]
Issue Score: ✓+

Comments:
Excellent work!
