### ISSUE TITLE
Create backlog issues for future teams

### ISSUE THREAD

**Issue by vivianwu00** [uchicago-cs/chiventure#1097]
Assignees: Vivian and Shuwen
team:sound

**Comment by vivianwu00** [comment]
Created backlog documentation for residual issues: will publish to README within the repository as well as a page within the Github

**Comment by vivianwu00** [comment]
Added to README as well as Sound Implementation page on Github following final pull request

**Comment by ecoble** [comment]
Issue Score: ✔️+

Comments:
Great job updating the documentation for next year's teams! Be sure that the summary portion of issues has a description of the issue, rather than just the assignees. Also be sure issues have milestones properly associated with them.
