### ISSUE TITLE
Update Player Class/Item Interaction Documentation

### ISSUE THREAD

**Issue by ideclue** [uchicago-cs/chiventure#1099]
In Issue #959, we successfully developed a framework for further integrating player classes with items, to eventually be used in gameplay (and specifically combat situations). However, the Player Class Wiki Pages and README.md files do not yet reflect all these changes. In order for future developers to understand our framework and design choices, further documentation is necessary. 

Thus, the purpose of this issue is to ensure these details are clarified throughout the chiventure documentation. Additionally, user stories that demonstrate the usefulness of this feature as well as suggestions for further integration (see Issue #1024) will be included, and the chiventure documentation will be added to the `docs` directory for easier visibility.

**Comment by ideclue** [comment]
I updated some of the documentation in the Player Class README.md file to provide a clearer explanation of player class-item interactions. While doing this, I realized that many modules had added their documentation to the `docs` folder, so I moved our Player Class documentation to this folder and added more features, including:

- Direct links to relevant Wiki Pages
- Outline of Player Class Modules
- Links to the relevant directories

This documentation update is ready for a (relatively short) Pull Request, as the remaining portion of the work on this issue lies in updating wiki pages.

**Comment by ideclue** [comment]
I've successfully update the following wiki pages with more information on player class-item interactions as outlined above:

1. [Player Class Requirements](https://github.com/uchicago-cs/chiventure/wiki/Player-Class-~-Requirements,-User-Stories,-Dependencies)
2. [Player Class Design](https://github.com/uchicago-cs/chiventure/wiki/Player-Class-~-Design)

Once PR #1103 is merged, this issue can be closed.

**Comment by ideclue** [comment]
Closing Statement: PR #1103 was successfully merged, and all relevant player class documentation it up to date for future developers.

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Great work on this! The updates that you have provided give a really detailed overview of your work.
