### ISSUE TITLE
Write tests for statistic modifying effects and attribute modifying effects in test_effect.c

### ISSUE THREAD

**Issue by rohangupta2806** [uchicago-cs/chiventure#1105]
We must write tests to check the implementation of statistic modifying effects and attribute modifying effects in effect.c and effect.h.  This involves testing the behaviour of the functions define_player_stat_effect, make_player_stat_effect, execute_player_stat_effect, define_item_att_effect, make_item_att_effect and execute_item_att_effect.  We should test that the function provides correct output when all arguments are correct, and that it does not crash if an argument is invalid.

**Comment by rohangupta2806** [comment]
Tests for these functions were added.  All tests pass.  The tests added are pretty superficial and do not test all possibilities.  In the future, we should look into adding even more tests for these functions.  Tests can be viewed in the linked pull request.

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Good work!
