### ISSUE TITLE
Create new a GUI sample game to display new GUI features

### ISSUE THREAD

**Issue by perenewang** [uchicago-cs/chiventure#1107]
We created a gui module and draw_images module for an graphic interface with split screen and map. Now we want to create a sample game using these new gui features.

**Comment by perenewang** [comment]
Created gui_sample_game.c with a sample game that has three rooms and has code for the map in the top left corner that updates when the user changes room.

**Comment by grkapoor17** [comment]
I added code to the main() function in gui_sample_game.c that draws a room on the upper-half of the split-screen for each room of the sample game. I also added three images named "room1.png", "room2.png" and "room3.png" to src/ui/examples. The sample game now displays a map as well as an image of a room on the upper-half of the split screen.

**Comment by grkapoor17** [comment]
The sample gui game has now been implemented. The game demonstrates what the gui team has worked on this year. Specifically, it displays a graphical split-screen with the lower half displaying an output and input text box that relays and inputs information respectively. The upper half of the split screen displays an image that changes concurrently as a user moves into a new room. Similarly, a map of the game is displayed at the upper left hand corner of the screen that updates as the user moves into a new room.

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Great work! Your updates are particularly well-done.
