### ISSUE TITLE
Update battles wiki pages to reflect code

### ISSUE THREAD

**Issue by adinilfeld** [uchicago-cs/chiventure#1109]
Over the course of this quarter, we (the Battles team) have done a considerable amount of refactoring, including renaming structs such as `game_t`, `item_t`, and `player_t`. Because of this, our wiki pages have become outdated. For this issue we will update the pages to reflect our current code, so that future students can use the wiki for reference.

**Comment by adinilfeld** [comment]
There are only 5 Battles wiki pages. Out of these, two ("User Stories" and "Text Based Combat in Other Games") are unrelated to the details of our code, so they won't have to be modified. It seems like the page most in need of editing is "Design Document", which contains a detailed description of all of our structs and functions. We'll also have to remove any completed tasks from the "Wishlist" page.

I'm also going to check with the Battles team whether we should delete the "Existing Code Review" document. It seems very out-of-date and overlaps significantly with the Design Document.

**Comment by adinilfeld** [comment]
@sonnykaiyuenlee @Elsa-Athiley @lczielinski @jintae412 

Could you each please check over the [Wishlist](https://github.com/uchicago-cs/chiventure/wiki/Battles-~-Wishlist) wiki page and delete any items which you've implemented this quarter? Thank you!

**Comment by adinilfeld** [comment]
I updated the first half of the Design Document to reflect changes in the naming of structs.

**Comment by jintae412** [comment]
> @sonnykaiyuenlee @Elsa-Athiley @lczielinski @jintae412
> 
> Could you each please check over the [Wishlist](https://github.com/uchicago-cs/chiventure/wiki/Battles-~-Wishlist) wiki page and delete any items which you've implemented this quarter? Thank you!

Wishlist has been updated concerning temporary stat changes. Considering that the code for such has been written but not yet integrated into the currently existing code, I decided not to delete the entry yet, but instead wrote an addendum that makes note of this as a future task.

**Comment by lczielinski** [comment]
> @sonnykaiyuenlee @Elsa-Athiley @lczielinski @jintae412
> 
> Could you each please check over the [Wishlist](https://github.com/uchicago-cs/chiventure/wiki/Battles-~-Wishlist) wiki page and delete any items which you've implemented this quarter? Thank you!

I deleted creating default items, since we accomplished that this quarter!

**Comment by Elsa-Athiley** [comment]
> @sonnykaiyuenlee @Elsa-Athiley @lczielinski @jintae412
> 
> Could you each please check over the [Wishlist](https://github.com/uchicago-cs/chiventure/wiki/Battles-~-Wishlist) wiki page and delete any items which you've implemented this quarter? Thank you!

Looks good to me

**Comment by adinilfeld** [comment]
After discussing with the Battles team, we've decided to delete the "Existing Code Review" wiki page, as it's outdated and likely more confusing than helpful to future Battles students. We think that the Design Document fulfills the same role, and is much more comprehensive and up-to-date.

**Comment by sonnykaiyuenlee** [comment]
We have cross referenced the design document to update it so that it accurately reflects the code currently in battles. This should be helpful for next year's incoming battle team

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Great work on this! The updates that you have provided give a really detailed overview of your work.
