### ISSUE TITLE
Create backlog issues for future DSL teams

### ISSUE THREAD

**Issue by r-e-stern** [uchicago-cs/chiventure#1115]
What it says on the tin: create backlog issues for future DSL teams.

**Comment by r-e-stern** [comment]
Created #1114.

**Comment by r-e-stern** [comment]
Created #1122.

**Comment by r-e-stern** [comment]
Calling this one done too. We aren't actively developing the DSL feature, so I doubt we'll have more ideas for backlog issues. The two that we created are hopefully enough to give a new DSL group a running start to pick up where we left off in development.

Closing the issue.

**Comment by ecoble** [comment]
Issue Score: ✔️++

Comments:
Great work! Thanks for making these issues, I think it will definitely help future teams get started!
