### ISSUE TITLE
Fix a bug where trying to add an item to two hash tables causes errors

### ISSUE THREAD

**Issue by jeyeong** [uchicago-cs/chiventure#1116]
Trying to add an item to two hash tables causes a bug because it requires two hash handles, when the item struct currently only has 1.

In order to fix this issue, I will add a second hash handle to the item struct and modify related functions accordingly.

**Comment by jeyeong** [comment]
To solve this issue, I have added a second hash handle to the item struct:
![image](https://user-images.githubusercontent.com/7861185/119832617-f861ef00-bec3-11eb-809b-97cbb5ae9ef4.png)

This hash handle is to be used solely by game->all_items.

To make game->all_items use this hash handle, I had to modify the `add_item_to_game()` function, and introduce: `add_item_to_all_items_hash()`. The former is located in `game.c`, and the latter in `item.c`. With these changes, any call to `add_item_to_game()` will use the second hash handle, whereas any other call (e.g. `add_item_to_room()`, `add_item_to_player()`) will use the original hash handle.

**Comment by jeyeong** [comment]
A tricky part is freeing the item struct correctly. The freeing process is as follows:
1. Items are removed from the player->inventory, npc->inventory, room->items hash tables, but **not freed**.
2. Items are then removed from the game->all_items hash table, and freed at the same time.

In order to facilitate this, we cannot use the macro HASH_DEL(), as HASH_DEL() does not specify which hash handle to use, resulting in errors. Instead, we use HASH_DELETE(hh, ...), which takes the hash handle as its first parameter. In this way, items can be correctly freed.

**Comment by jeyeong** [comment]
To simplify the freeing process, I changed the delete_all_items() (in the item module) implementation to use HASH_CLEAR instead of HASH_DELETE, under the suggestion of @pkasner. This, combined with delete_all_items_from_game() (in the game module), will ensure that all items are freed when Chiventure is exited.

The function remove_item_from_hash() (in the item module) works as before.

**Comment by lilyehsani** [comment]
Issue Score: ✔️++

Comments:
Great work overall! The updates of this issue are very thorough.
