### ISSUE TITLE
writing tests for parse_r function in the parser module

### ISSUE THREAD

**Issue by Beza20** [uchicago-cs/chiventure#1119]
the parse_r function implement to resolve issue #275 currently has no tests. Tests can be useful as future iterations of CLI team will be interacting with this function quite a lot

**Comment by Beza20** [comment]
Initially, I thought I could follow the same way the parse function has its output checked but since we have a linked list here we can't do a manual iteration by using indices. So I built a helper function that takes in a string to be parsed, the number of cmds I expect to be tokenized and the array of strings where I will put the expected tokenized arrays to compare with each node of the list. The helper function utilizes LL_FOREACH to change the head of the list as it goes through and compares with the corresponding array and makes sure that it is either the same as the expected cmd or the expected yield of NULL. With the commit that was just made, I am having issues where all the tests are crashing.

**Comment by Beza20** [comment]
The spacing around cmds that are being parsed have to be paid attention to when only applying our parse_r function. Because since the strtok function that parses using spaces as a delimiter is not yet applied to the cmd line our expected output needs to be set up in a way to account for the spaces that might be present or not before the connecting word "AND." Not realizing this earlier made my tests fail continuously but is not fixed. if the input is "ab and xy" the output is "ab " -> " xy"

**Comment by ecoble** [comment]
Issue Score: ✔️++

Comments:
Great work with these tests and updating this issue with your progress! Be sure to include the CLI label.
