### ISSUE TITLE
Add sample functionality from new features from this year to the monkeypatched demo game

### ISSUE THREAD

**Issue by adishpan** [uchicago-cs/chiventure#1126]
Turn the existing barebones demo in action-management/examples into a full demo incorporation sample functionality that showcases the progress made by the action-management team during this year.

**Comment by WPDolan** [comment]
We have created a monkeypatched demo to highlight changes. This demo highlights our work in custom-actions integration and the player module. Specifically, this demo showcases the creation of custom actions and the stats portion of the player interface.


We have added the following monkeypatched commands

- `SEEDMG` Prints the damage of the player's currently held sword.
- `RAISEDMG` Raises the damage attribute of the player's sword by 3.
- `MYSTRENGTH` Prints the strength of the player
- `LEARNLEVEL` Adds the strength stat to the `player_stats` field used by the player
- `CHANGELEVEL X` Adds X  to the player's strength stat

**Comment by jasulcaf** [comment]
Closing statement:

The demo illustrates functionality for running a custom-action IFELSE branch block and modifications made to the player struct and module, specifically stats (which emulates how other components of the player struct would work such as skills and effects). These functionalities are demonstrated with the following commands:

- SEEDMG
- RAISEDMG
- MYSTRENGTH
- LEARNSTRENGTH
- CHANGESTRENGTH

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Good work! This is a great closing statement for a small issue.
