### ISSUE TITLE
Create testing for multiclass.

### ISSUE THREAD

**Issue by farm-zaq** [uchicago-cs/chiventure#1141]
Currently, there is no formal testing for multiclassing. A few bugs have been found and resolved for the demo, but this implies that there may be more. Proper testing should be implemented so that we know that the current implementation of multiclassing works, and so we know if future changes to chiventure break this implementation. This testing should include tests to ensure that classes are properly combined and tests to ensure that multiclasses do not lead to bugs in places where normal classes are known to function properly. The second kind of test can likely be done by adapting tests that are currently used for normal classes. This is the most important task for the improvement of multiclassing.

**Comment by wellingtj** [comment]
See issue #1402. This is outdated so I'm closing this issue
