### ISSUE TITLE
Update multiclass string concatenation in descriptions to avoid overflow.

### ISSUE THREAD

**Issue by farm-zaq** [uchicago-cs/chiventure#1142]
Currently, multiclass string concatenation in multiclass_shortdesc and multiclass_longdesc do not check to ensure that concatenations do not exceed the maximum size of these descriptions. This means that multiclasses composed of roughly 6 or more subclasses (depending on the length of their names and short descriptions) will have bugs, which is undesirable. This should be updated so that there is either a cap on the number of parent classes to avoid this or the maximum length of a description is variable, so that the limit can be adjusted and overflow can be avoided.

**Comment by jroven** [comment]
The functions multiclass_shortdesc and multiclass_longdesc in src/playerclass/src/class.c have been updated to compute the length of the descriptions before they are returned and raise an error if the length exceeds the maximum size of the descriptions. There is still no preemptive measure that caps the number of parent classes or allows the maximum length of the description to vary.

**Comment by jroven** [comment]
Moving to sprint 2 to create a preemptive measure in the functions that call multiclass_shortdesc and multiclass_longdesc

**Comment by jroven** [comment]
The functions multiclass_shortdesc and multiclass_longdesc have been updated to raise an error and return only the description of the base class if the concatenated length would exceed the max length.

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work! The issue was started in one sprint, but was not completed until the next one.
