### ISSUE TITLE
Update multiclass_shortdesc to have proper grammar.

### ISSUE THREAD

**Issue by farm-zaq** [uchicago-cs/chiventure#1143]
Currently, multiclass_shortdesc returns a list of parent classes, although the list simply separates each parent class with a comma. It does not use the word "and" anywhere, and it will separate only two elements with a comma (which is incorrect). For example, a multiclass of warrior and wizard will be "Multiclass of Warrior, Wizard." and a multiclass of warrior, wizard, and bard will be ""Multiclass of Warrior, Wizard, Bard.". The multiclass_shortdesc() function should be updated so that these short descriptions are grammatically correct.

**Comment by wellingtj** [comment]
I've implemented a basic fix but I still need to clean it up and test it a bit

**Comment by wellingtj** [comment]
I'm not really sure how to progress any further without any testing for multi-classing. I believe we were told not to pick up that issue but I'm not sure how to complete this issue without completing the issue to make some test cases

**Comment by wellingtj** [comment]
This has been implemented, but still needs to be tested. I will reopen this issue when I am more familiar with how to create testing

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work! Status updates on an issue should have something tangible to share. For example, when you say you've implemented a basic fix, it would be helpful to describe a bit about what the fix entailed.
