### ISSUE TITLE
Finish execute_move_effect() Implementation

### ISSUE THREAD

**Issue by tgao564** [uchicago-cs/chiventure#1152]
The execute_move_effect() implementation in src/skilltrees/effect is incomplete as we were waiting for the moves struct to be transferred from the battles combatant struct to the player ctx struct. This was done in PR #1127 but the PR was submitted right before the soft-lock deadline so the move effect implementation isn't completely done yet. Need to finish the execute function and also finish testing for it.

**Comment by nbilaver** [comment]
Progress check: The line has been uncommented and changed, as the original gave the ctx->game->curr_player->moves struct when the function calls for a player struct, not a move.

A simple test has also been implemented. There aren't completely encompassing tests for the function yet, like for when moves is an empty  although given that this function is effectively a wrapper for the add_move() function, it shouldn't be hard to implement the rest of the tests based on the add_move() function's tests.

**Comment by nbilaver** [comment]
Tests have been written, and the function works!

**Comment by jacknugent1529** [comment]
Issue Score: E

Comments: Nice work on this issue! The tests look thorough and well-written. In the future, even for relatively straightforward issues, try to give a more in-depth closing statement describing which work was performed by each assignee on the task.
