### ISSUE TITLE
Finish implementing the get_supported_actions function using utlist.h

### ISSUE THREAD

**Issue by yoonsjeong** [uchicago-cs/chiventure#116]
We started but didn't finish creating this function last sprint. At the moment our thinking for this function is that it outputs a list of action structs given an input of enum action kind (ITEM = 1, DIRECTION = 2, ITEM_ITEM = 3). This will enable other groups to see all of the available actions that they find relevant and also be able to search them by canonical name or by synonyms, if they find necessary.

**Comment by yoonsjeong** [comment]
ADDITIONAL task that crosses over into this task:
Update the action_t struct in these ways (after discussing with Borja and Mark we discovered these were necessary changes)

    = rename the action_t struct the action_type_t struct, since that represents it better
    = remove the enum action_type parameter from action_type_t struct
    = remove the synonyms parameter from action_type_t struct
    = remove enum, synonyms parameters from action_init, new, free functions

**Comment by lucyyutingli** [comment]
Should we add @SnowballAntrobus to this task as well? Since he hasn't been assigned something yet.

**Comment by yoonsjeong** [comment]
This issue can be closed as the pull request completing it has been merged with actions/dev. See https://github.com/uchicago-cs/chiventure/pull/122

**Comment by mpcsh** [comment]
Issue Score: ✓

Comments:
Skimpy progress updates and closing statement.
