### ISSUE TITLE
Create a graphical/textual display of quest trees so that the player can see objectives

### ISSUE THREAD

**Issue by gabigarc03** [uchicago-cs/chiventure#1161]
There currently exists no way to represent quests visually in the CLI or GUI. It'd be nice to have one to show our lovely trees! See the [current implementation wiki](https://github.com/uchicago-cs/chiventure/wiki/Quests-~-Current-Implementation) for more details.

**Comment by elizabethli31** [comment]
Messaged CLI and graphics team about the possibilities of adding command line option to view the tasks involved with a particular quest.

**Comment by elizabethli31** [comment]
The graphics team has created a display of the task tree (see issue #1295), and we are still trying to see if anything can be done from the CLI end to trigger the actual display of the quest.

**Comment by elizabethli31** [comment]
CLI design: https://github.com/uchicago-cs/chiventure/wiki/Quests-~-CLI-and-GUI-Display

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great job! Just make sure that you issue a proper closing statement summarizing what was done, and why the issue is being closed.
