### ISSUE TITLE
Strengthen quest tests to better test tree functionality

### ISSUE THREAD

**Issue by gabigarc03** [uchicago-cs/chiventure#1165]
The tests for quests (in `test_quests_state.c`) were really only refactored when non-binary achievement trees were implemented. They don't fully test whether `add_achievement_to_tree`, `complete_achievement`, and `is_quest_completed` actually use tree functionality effectively. See the [current implementation wiki](https://github.com/uchicago-cs/chiventure/wiki/Quests-~-Current-Implementation) for more details.

**Comment by JSerf02** [comment]
When updating these tests, we should also add tests against the updated quest id system [(Pull Request #1237)](https://github.com/uchicago-cs/chiventure/pull/1237) to make sure it works

**Comment by jakeziqiwei** [comment]
We have added extra tests to add coverage to the above functions, but new functions we have written(in the ctx branch). Closing this issue now since it has already been merged into dev

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great job! My only comment here is that you did not include an update when you linked the Quests/add ctx PR to this issue. You should explain the significance of this PR in this issue.
