### ISSUE TITLE
Document Action-Management Status

### ISSUE THREAD

**Issue by sabinecodes15** [uchicago-cs/chiventure#1166]
The action-management team needs to become more familiar with the code base to understand how actions in chiventure are tracked and used, what may or may not need to be fixed, and what can be improved upon/added as a new feature. For this issue, all developers need to comb through the action-management and custom-actions directories to get a feel for the structure of the modules. We will be deciding which of these two features we want to focus on.

The conclusion of this issue will yield comprehensive documentation of the current state of the action-management directory, with some additional notes on the custom-actions modules to the extent that they are relevant. These docs will also contain ideas for what the team is looking to implement throughout the rest of the sprints.

**Comment by sabinecodes15** [comment]
**Notes on the action management branch:**

**action_structs.h:** Contains structs for actions including:
- A string encoded name of the action
- An enum to classify the action type (e.g. “OPEN”, “CLOSE”)
- An enum for the kind of action (e.g. 1, 2, or 3)
- A pointer to the room struct that the item unlocks/allows access to upon use
- A string encoded direction for path actions

**actionmanagement.c:** Contains functions to initiate and free action structs, as well as a function for enacting each type of action (kind 1, 2, or 3) with error messages for specific cases

**get_actions.c:** Contains helper functions to create a list of supported actions (and free the list when done)

**Comment by sabinecodes15** [comment]
**Closing statement:** 
We now have a much better grasp on the structure of both the action-management feature and the custom-actions feature. 

The previous customs actions team provided [comprehensive documentation](https://github.com/uchicago-cs/chiventure/wiki/Custom-Actions-~-Existing-Code-Review) of the state of the action-management directory, and as it is still relevant we felt no need to rewrite this information.

We created updated documentation for the state of the custom-actions module that can be found [here](https://github.com/uchicago-cs/chiventure/wiki/Custom-Actions-~-Current-Module-State-(2022)). It contains the current directory structure of the feature and details about the role of each module. It also contains indications about what has and hasn't been implemented. Future work will require more conversation within the group to determine exactly how we'd like to proceed in subsequent sprints.

**Comment by ecoble** [comment]
Issue Score: Excellent

Comments:
Great job on this issue, especially with the thorough documentation!
