### ISSUE TITLE
Write initial document for the current setup of custom scripts and for the future direction

### ISSUE THREAD

**Issue by jackjackkimkim** [uchicago-cs/chiventure#1168]
Documentation - Ramarko, Jack

**Comment by RamarkoB** [comment]
The Documentation of the Custom Scripts seems fairly clear. I think Writing down the future possible path of the Custom Script Module is our best goal

**Comment by RamarkoB** [comment]
The goal for the Custom Scripts module is an independent module is comprised of methods that allows for special actions linked to individual objects, inventory items and locations, or conditions associated to the player, such as health, number of coins, level. Our goal over this quarter to to attempt to find the most efficient way to integrate Custom scripts into Chiventure as to make it as simple as possible to integrate special actions when designing levels

**Comment by RamarkoB** [comment]
The WIki Page for the Planned Goal of the Custom scripts team is avaiable here: https://github.com/uchicago-cs/chiventure/wiki/Custom-Scripts-~-Goal

**Comment by ecoble** [comment]
Issue Score: Satisfactory

Comments:
Nice job creating the documentation for the custom scripts' plan this quarter! In the future, be sure to add the milestone for the sprint to the issue, and make sure that you have a fleshed out summary beyond just what is automatically generated from the card. Also be sure to have a clear closing statement with a brief summary of what was accomplished.
