### ISSUE TITLE
Creating Static Library for WDL

### ISSUE THREAD

**Issue by victor-a-a** [uchicago-cs/chiventure#117]
We have written functions to load and type check the YAML file.  However, these functions are largely inaccessible given the organization of our working directory and our method for building the code.  We intend to make these functions accessible by:
1. Configuring our directory to meet project standards.
2. Modifying the Makefile to create a static library instead of an executable.

**Comment by victor-a-a** [comment]
Update:
I accomplished both parts of this task.  I am currently awaiting for my pull request to wdl/dev to be approved.  I intend to close this issue once I merge to wdl/dev.

**Comment by victor-a-a** [comment]
Update:
Changes were merged to `wdl/dev`.

**Comment by lydiafilipe** [comment]
Issue Score: ✓-

Comments:
The title and summary are good, but there is no closing statement and the updates contain very little detail.
