### ISSUE TITLE
sound: Familiarize yourself with code and run demo provided by last sound team, create documentation on questions and current state

### ISSUE THREAD

**Issue by jwschroeder21** [uchicago-cs/chiventure#1170]
The goal is to familiarize ourselves with the existing documentation from the previous sound team and create documentation about the current state of the feature and questions. 

members: everyone familiarize, documentation - Jake, Rhea

**Comment by sangerr** [comment]
Initial review of documentation:
In the include/sound directory, we have a sound.h file which contains a few data structures and functions that need to be implemented for the sound. In the src/sound directory, we have a README.md file and CMakeLists.txt file. In the src/sound/src directory there is a sound.c file, however none of the functions are implemented yet. In the src/sound/examples directory there is a demo.c, demo.h, and Makefile. In the src/sound/sandbox directory, there is a main.c, README, and Makefile. There is no sound directory in the docs or tests directories, which we will need to add once we implement the sound functions.

**Comment by sangerr** [comment]
When running the demo in the examples directory, I am getting an issue and unable to make it work. We will need to fix this issue in the next sprint.
I initially ran:
$ make
$ ./demo

which returned these errors:
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
MixPlayChannel: Mix_LoadWAV_RW with NULL src
MixPlayChannel: Mix_LoadWAV_RW with NULL src

**Comment by jwschroeder21** [comment]
I get the same error as well in addition to a few others:

ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
Unable to open audio: ALSA: Couldn't open audio device: No such file or directory

This was after running the following:
make clean
make
./main

**Comment by sangerr** [comment]
Summary of sound.h file documentation: 
The previous team has created a enum SoundType structure for either Background or Sound Effect sound. They also created a sound_t struct that contains the SoundType, the wavSpec, wavLength, and *wavBuffer, an id number, and its hash handle. There are three functions: a load_wav function which is meant to load sound to the SDL queue, a sound_free function that frees sound from the memory heap, and a play_sound function that plays sound from SDL queue.

**Comment by sangerr** [comment]
I am unsure exactly how the SDL data base works and that is something I would like to further explore next week to gain understanding into how it can be utilized to integrate sound into chiventure.

**Comment by jwschroeder21** [comment]
I think the general idea I've gathered from the files Rhea described above is that there are two main functions that the previous team designed: a loading function and a playing function. 

These function takes in the sound struct (sound_t) which contains the data concerning the composition of a sound file in addition to a hash table piece that identifies the specific sound. When the function completes, a sound is loaded to something called an SDL queue, or the sound is played. In each function, a 0 or 1 is returned to represent success or failure of execution. 

To my knowledge, SDL stands for "Simple DirectMedia Layer", which is a library you can use in C. (source: https://www.geeksforgeeks.org/sdl-library-in-c-c-with-examples/) 

In terms of the loading function, both the length and buffer are included in addition to the file's information, and it seems this model was heavily influenced by this article: https://gigi.nullneuron.net/gigilabs/playing-a-wav-file-using-sdl2/

**Comment by sangerr** [comment]
This issue is closed as we reviewed all of the existing code and documented our questions. We closed this issue in our meeting and decided to make issues for the next spring on researching the SDL further and figure out how to make the demo work.

**Comment by ecoble** [comment]
Issue Score: Excellent

Comments:
Great job on this issue, especially with the detailed and frequent updates! While the summary you have here is descriptive, in the future see if you can flesh it out a bit more. Also, if you have not done so already, please create a Wiki page for the documentation you've created and link it here, no need to reopen the issue you can just add a link as a comment
