### ISSUE TITLE
sound: come up with ideas/goals for direction of sound team

### ISSUE THREAD

**Issue by jwschroeder21** [uchicago-cs/chiventure#1172]
The goal for this issue is to come up with ideas/goals for direction of sound team.
members: Parker, Jake

**Comment by jwschroeder21** [comment]
A thing Parker and I discussed that would be interesting to think about is different levels of intensity for background music depending on the current state/stakes of the game. For example, if a player is in a moment of high intensity, really dramatic music may fill the space whereas when a player enters a less intense state, lighter music plays 

Here is an example of a selection/spectrum of music based on tension:

- Most tension: https://www.youtube.com/watch?v=upgAIOsipLA (The player is battling another, about to die, moments of high drama)
- Medium tension: https://www.youtube.com/watch?v=73C7iDlYQ1Q (The player is on their adventure, neither in a moment of high drama or personal growth. Perhaps they are at the market, solving a puzzle, or talking to a stranger)
- Least tension: https://www.youtube.com/watch?v=CvFH_6DNRCY (The player is in a field, thinking introspectively, moment of self discovery or growth)

What could be interesting to think about is how to tag moments of higher/lower intensity in the game. Could we think of a design or module that tracks intensity for a player throughout?

**Comment by parkerbroz** [comment]
For dialogue audio, we brainstormed two options that are feasible and still allow stylistic flexibility for the developer to choose dialogue content, emotion, etc.
- text to speech
- simlish style "talking" (examples: [1](https://www.youtube.com/watch?v=S7-njGsKmTI&ab_channel=GameSam), [2](https://www.youtube.com/watch?v=hc4a0dic2yo&ab_channel=SimsVIP), [3](https://www.youtube.com/watch?v=TjAg-8qqR3g&ab_channel=FandangoFamily))
If we go down the text-to-speech path, we would likely have to research and implement another library with tts capabilities. For simlish, we could either loop different source audios or generate audio ourselves by randomly cutting the source audios together.

Another important feature would be smoothly mixing in event noises. The current sandbox documentation hints that event noises interrupt background audio. This would be jarring for the player. Ideally, a noise like a sword slash or a door opening could be overlayed on top of the background song.

**Comment by jwschroeder21** [comment]
In terms of goals, it would be both exciting and attainable to get the demo to run and/or to write the code for the loading/playing functions described in the .h file. 

The other way we could go would be to design modules that support different types of sound implementation throughout the game.

This should be something we discuss at our next team meeting!

**Comment by jwschroeder21** [comment]
Closing statement:

This issue covered the ideas of text to speech and background music (and its varying intensity). In our team meeting we decided to further explore text to speech, and created a new issue to do that. Hence, this issue is closed.

**Comment by ecoble** [comment]
Issue Score: Excellent

Comments:
Nice job brainstorming ideas for the sound team this quarter! Please also link the Wiki documentation for your plans, you do not need to reopen the issue you can just leave it as a comment.
