### ISSUE TITLE
Create list of pros and cons of creating new or modifying existing Chiventure demo, research and document beginning steps

### ISSUE THREAD

**Issue by mxu24** [uchicago-cs/chiventure#1173]

**Comment by calvinytcheong2020** [comment]
Description: The existing demo for custom scripts creates a sample game that exhibits the use of a custom type (in this case , a custom string) that is associated with an action and can change depending on user input. For this task, we aim to explore several things, based off of our observations on this demo: the example of Lua in action (which could provide more insight as a whole into its significance for this feature), how other existing custom types might be demonstrated, and what other features are compatible with custom scripts. 

Also, the most recent commit message for the demo, "Hopefully bugs are fixed :(", is possibly a cause for concern. Running the demo and making sure that it functions is another avenue for the near future, though familiarization is currently our priority.

**Comment by mxu24** [comment]
Closing Statement
- The issue is closed now that we have successfully compiled and run the current custom scripts example demonstration.
- We decided to continue with and modify the current demonstration provided by the prior team. While there are a few core issues (listed below), the general setup of the demo is acceptable and should be more feasible to build upon than completely restart.
- Issue we ran into with the demo: Use of custom scripts is highly limited and should be expanded upon.
- Difficulties experienced during the task: Missing custom-type.h file when compiling. We realized it wasn’t an issue with the cmake files, but rather that we had to compile the larger chiventure directory along with the smaller examples directory.
- Other issues in the demo that we can communicate with other teams for help and fixing: inaccurate map (6 rooms that you cannot actually access), limited functionality (e.g. can only move from the first to the second room, after which you cannot move in any direction, no objects in room except for a rock that you cannot interact with).
- Next steps: Further investigating the purpose of the gold.c file and how to compile and run it with Lua, since it is a more direct example of custom scripts specifically (as instructed in the README).

**Comment by ecoble** [comment]
Issue Score: Excellent

Comments:
Great job on this, you summary and closing statement are very thorough! In the future try to put the description in the "description" section of the issue, you can edit this after turning the card into an issue.
