### ISSUE TITLE
Create feature wishlist for rpg-OpenWorld

### ISSUE THREAD

**Issue by jsssengonzi** [uchicago-cs/chiventure#1174]
In this issue we need to:
1. familiarize ourselves with the existing OpenWorld code base  
2. identify tasks that we want to tackle in our future sprints

A starting list of things to get done:
 1. get the codebase up and running on our devices
 2.  Get a sense of where the codebase/feature set is now
 3. get a sense of where we would like the codebase/feature set to be
 4. split the difference into achievable and (hopefully) interesting tasks

**Comment by lukasg8** [comment]
After looking at the code base and the Wiki page, here are some big picture features that we agreed would be great that we could accomplish during this entire quarter. These features are a bit aspirational but we will use them to create smaller subtasks for each sprint. 
1. Statically implementing the open-world module into the rest of the code base. 
2. Further developing the autogenerate algorithm to make it less random and more logical. That is to say, rooms being autogenerated should be similar to rooms they are situated near. 
3. Making the Wiki more concise. We believe it is a bit repetitive and could use visuals so we are looking to making it easier for future teams to understand the module.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great job on this issue!
