### ISSUE TITLE
GUI: Familiarize myself with graphics library Raylib and Chiventure Raylib Wiki

### ISSUE THREAD

**Issue by dhirpalshah** [uchicago-cs/chiventure#1175]
I understand that the past year graphics team has created and contributed to a Raylib section in our Wiki, but I would like to further research Raylib. I hope to find extra functionalities on the Raylib website itself and come up with some features in Raylib that would assist solving the issues that our team will open. For now, we haven't opened many issues, but as we do, I will add them.

This is the link to the previous issue relating to Raylib.
https://github.com/uchicago-cs/chiventure/issues/457

**Comment by dhirpalshah** [comment]
This is an issue that has yet to be resolved from a previous year. Let's see if I can find anything in Raylib that would assist with this.
https://github.com/uchicago-cs/chiventure/issues/973

**Comment by dhirpalshah** [comment]
This issue was resolved because I have a greater understanding on raylib thanks to the wiki that the past years have provided. The next steps for me are to figure out how I can incorporate it into the functions that we want to implement, then draft out some pseudocode in order to implement those functions. One issue the team has been having was in actually downloading raylib via ssh to get it running. We will explore that in future issues.

**Comment by philipchenaux** [comment]
Issue Score: Satisfactory

Comments:
Great work Dhirpal! Just a few minor issues that you should try to fix up in future issues:
1. Status updates on an issue should have something tangible to share.
2. Make sure to assign new issues to the sprint they are worked on (by selecting the appropriate sprint under "Milestone")
