### ISSUE TITLE
npc- actions: Review state of NPC actions and update existing documentation/create wishlist

### ISSUE THREAD

**Issue by junasano** [uchicago-cs/chiventure#1177]
members: Jun
task: Review state of NPC actions and update existing documentation/create wishlist
Notes: There is currently no documentation on npc-actions, but there are some implementations including the structure on npc-action branch.
Wishlist: Create some sort of documentation, review existing code for errors and improvements, and finish implementing Kind 5 and 6 actions.

**Comment by junasano** [comment]
After looking at the code base, I found that there is a branch called npc-actions. The header file was complete with a detailed explanation of the data structures as well as specific functions. The implementation file was also created and around a third of it was done. This would branch out to the following next steps:
 1. Finish the implementation for Kind 5 and 6 actions
 2. Create tests for Kind 4, 5, and 6 actions as mentioned on another issue
 3. Create a documentation for what npc-actions does since there is currently none

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work! Make sure to assign new issues to the sprint they are worked on (by selecting the appropriate sprint under "Milestone").
