### ISSUE TITLE
Create tests for WDL validation code

### ISSUE THREAD

**Issue by mewthew** [uchicago-cs/chiventure#118]
We have written code to validate the object attribute types from a YAML file found in #56. Now, we would like to write tests to ensure that the validation process runs correctly. To do so, we will be creating a testing directory within the WDL repository and adding a unit testing script within the directory that tests our existing validation functions.

**Comment by mewthew** [comment]
We have implemented code for testing found [here](https://github.com/uchicago-cs/chiventure/blob/wdl/improved_validation/src/wdl/tests/test_validation.c). So far, these tests check whether the game, room, and item object fields are valid from the YAML file located within the wdl/examples/sample_yaml directory. We will be updating and adding more tests in the future once actions are finalized.

**Comment by lydiafilipe** [comment]
Issue Score: ✓

Comments:
Good job with a lot of the details included, however there are no progress updates.
