### ISSUE TITLE
DSL: familiarize with python

### ISSUE THREAD

**Issue by baigh1** [uchicago-cs/chiventure#1181]
Set up python library and write some elementary functions to get started. Those assigned to this task had either no previous or extremely limited experience with the language. The goal here is to understand Python syntax and Python-specific data types/ functionality.

**Comment by alexlee0422** [comment]
Read through the article and tutorial on the website: https://hackernoon.com/intermediate-python-refresher-tutorial-project-ideas-and-tips-i28s320p

**Comment by alexlee0422** [comment]
Did practice problem and exercises on CodingBat to further familiarize with python syntax and simple functions. Some exercises and problems done:
```
#Given a number n, return True if n is in the range 1..10, inclusive. 
#Unless outside_mode is True, in which case return True if the number 
#is less or equal to 1, or greater or equal to 10.
def in1to10(n, outside_mode):
  if outside_mode:
    if n <= 1 or n >= 10:
      return True
    return False
  if n in range(1, 11):
    return True
  return False

#You are driving a little too fast, and a police officer stops you. Write code
#to compute the result, encoded as an int value: 0=no ticket, 1=small ticket, 
#2=big ticket. If speed is 60 or less, the result is 0. If speed is between 61 
#and 80 inclusive, the result is 1. If speed is 81 or more, the result is 2. 
#Unless it is your birthday -- on that day, your speed can be 5 higher in all cases.

def caught_speeding(speed, is_birthday):
  if is_birthday:
    speed -= 5
  if speed <= 60:
    return 0
  if speed >= 61 and speed <= 80:
    return 1
  return 2
```

**Comment by baigh1** [comment]
I have never used Python before, so I created a .py file titled python-practice which contains various function declarations/implementations. Each function implemented had a specific purpose in getting me accustomed to python syntax or using Python arguments. The following is a link to a google document containing the Python code.

https://docs.google.com/document/d/1TvVYKiMP4QJ6w3KJsbWO9KC8ZG5UtWwE6qBqygj_s5k/edit?usp=sharing

**Comment by baigh1** [comment]
Youtube Videos Utilized:

https://www.youtube.com/watch?v=rfscVS0vtbw : Python Course for Beginners
https://www.youtube.com/watch?v=_uQrJ0TkZlc : Python Course for Beginners
https://www.youtube.com/watch?v=AGnECmJFA9U : Introduction to Python Syntax
https://www.youtube.com/watch?v=GqBoZZ6ZJxk : Reading/Writing to Files in Python

Websites and Tutorials Used:
https://www.learnpython.org/
https://www.w3schools.com/python/

These were all helpful in learning basics. I utilized the parts of each website/video that felt most applicable to what I may be using in the project.

**Comment by awliu2** [comment]
Refamiliarized myself with python, mostly by doing practice problems online. 

```
Given a string s, find the length of the longest substring without repeating characters.
class Solution:
    def lengthOfLongestSubstring(self, s: str) -> int:
        charSet = set()
        l = 0
        rv = 0
        
        for r in range(len(s)):
            while s[r] in charSet:
                charSet.remove(s[l])
                l += 1
            charSet.add(s[r])
            rv = max(rv, r - l + 1)
        return rv
```

Implement the myAtoi(string s) function, which converts a string to a 32-bit signed integer (similar to C/C++'s atoi function).

```
class Solution:
    def myAtoi(self, s: str) -> int:
        numStack = []
        nums = False
        positive = True
        digitdict = {"0" : 0, "1": 1, 
                     "2" : 2, "3" : 3, 
                     "4" : 4, "5" : 5, 
                     "6" : 6, "7" : 7,
                     "8" : 8, "9" : 9}
        for c in s:
            if not nums:
                if c == ' ':
                    continue
                elif c == '-':
                    positive = False
                    nums = True
                elif c == '+':
                    nums = True
                elif c in digitdict:
                    nums = True
                    numStack.append(digitdict.get(c))
                else:
                    break
            
            else:
                if c in digitdict:
                    numStack.append(digitdict.get(c))
                else:
                    break
        
        res = 0
        scale = 1
        while numStack != []:
            res += scale * numStack.pop()
            scale *= 10
            
            
        if not positive:
            res *= -1
        
        if res > 2147483647:
            res = 2147483647
        if res < -2147483648:
            res = -2147483648
            
        return res          
```

You are given an integer array height of length n. There are n vertical lines drawn such that the two endpoints of the ith line are (i, 0) and (i, height[i]).

Find two lines that together with the x-axis form a container, such that the container contains the most water.

Return the maximum amount of water a container can store.
```
class Solution:
    def maxArea(self, height: List[int]) -> int:
        res = 0
        left = 0
        right = len(height) - 1
        
        res = min(height[left], height[right]) * (right - left)
        while left < right:
            res = max(res, min(height[left], height[right]) * (right - left))
            if height[left] < height[right]:
                left += 1
            else:
                right -= 1
        return res
```

**Comment by jacknugent1529** [comment]
Issue Score: S

Comments: Very nice job with the updates (note that for formatting, three backticks will create a code block)! Remember to add closing statements and to paste the contents of a google doc into the issue, since google docs might be deleted and therefore don't work well for documentation purposes.
