### ISSUE TITLE
DSL: familiarize yourself with lark library. Create examples involving parsing and creating grammars, and create a wiki page

### ISSUE THREAD

**Issue by baigh1** [uchicago-cs/chiventure#1183]
Read through the Lark documentation, samples from outside, and familiarize yourself with the current /dsl codebase. Create examples that showcase usage of lark's grammar rules and parsing, and also create a wiki page describing how Lark works.

**Comment by baigh1** [comment]
Spent time reading through the documentation and creating my own simple calculator file using Lark.
Since I was unable to download the Python file, I have attached a google doc containing my code. I still have a few questions about the Lark library, which I hope to get addressed later on.

https://docs.google.com/document/d/1LSgdqndpcGeuInwFydj8m4-PGNUM1MGS1CoZlN22xwo/edit?usp=sharing

**Comment by awliu2** [comment]
Been reading through the documentation, will work on creating an "Intro to Parsing" wiki page as Jack suggested.

**Comment by jhsivadas** [comment]
Created a wiki page for LARK:

https://github.com/uchicago-cs/chiventure/wiki/DSL-~-LARK-Documentation

**Comment by awliu2** [comment]
Just wrote the sections "evaluating the tree" and "optimizing."

**Comment by awliu2** [comment]
Wiki page has been completed for now! Everyone has finished writing their respective sections. We now have a wiki page [here](https://github.com/uchicago-cs/chiventure/wiki/DSL-~-LARK-Documentation) with 5 sections: "grammar", "creating the parser", "shaping the tree", "evaluating the tree", and "optimizing." We (and hopefully also future groups) will continue to update and revise the wiki page throughout the rest of the course.

**Comment by awliu2** [comment]
Wiki page has been completed for now! Everyone has finished writing their respective sections. We now have a wiki page [here](https://github.com/uchicago-cs/chiventure/wiki/DSL-~-LARK-Documentation) with 5 sections: "grammar", "creating the parser", "shaping the tree", "evaluating the tree", and "optimizing." We (and hopefully also future groups) will continue to update and revise the wiki page throughout the rest of the course.

**Comment by jacknugent1529** [comment]
Issue Score: E

Comments: Excellent work! The wiki page looks like it will be very helpful for your own team and future teams. When using google docs, try to paste the contents into the issue directly so it can act as documentation for the future
