### ISSUE TITLE
Review user stories and identify which have been implemented and which need more work

### ISSUE THREAD

**Issue by vanolson** [uchicago-cs/chiventure#1191]
There are 5 current user stories in the player class wiki (https://github.com/uchicago-cs/chiventure/wiki/Player-Class-~-Requirements,-User-Stories,-Dependencies), and we will evaluate how well each has been implemented by previous chiventure team members.

Members: Vincent, Katie, Van

**Comment by Vincent-Zhang4135** [comment]
We have decided to split our user stories task between the three of us in the following way, and will update the issue as we go along:

Katie:
1. As a game developer with some technical skill, I would like to be able to create my own fully-functional classes.
2. As a game author with no technical background, I would like to be able to add classes that I do not need to design from the ground up.

Vincent:
1. As a player, I would like to be able to choose different player classes which allow me to interact with the game state in distinct manners
2. As a player, I love having a branching (combat) skill tree unique to/based on my class

Van:
1. As a player, I want my choice of class to have direct meaningful changes on my character that represent the class I’ve chosen

**Comment by Vincent-Zhang4135** [comment]
I have looked over the two user stories that deal with functionalities we would want players to have, and have came to some details about how we can improve upon current features on this side of our player class. In particular, I think that we would want to improve in branching out the skill trees to tailor to each unique class type (so that player decisions in player classes feels meaningful and significant) and this might need partnership/intersection into the SKILLTREES feature, as well as develop a combat skill tree and this may intersect into ACTIONS. We might also consider adding support on the CLI side to inform players about the descriptions of each class. These are just some things that are possibly paths forward for us to look into

**Comment by vanolson** [comment]
My observations in relation to this user story: As a player, I want my choice of class to have direct meaningful changes on my character that represent the class I’ve chosen.

ALREADY IMPLEMENTED:

- The class_t struct features a number of character attributes determined by their class, impacting much of that character’s abilities
- Base stats are determined by class, directly determining a character’s strengths
- Starting skills are also determined by class, affecting a character’s abilities from the very beginning 
- Multiclass structures allow for the combination of multiple classes, allowing for the integration of the above attributes
- Characters have different competencies with certain items based on their class, with the item multiplier feature
- The hard-coded prefabs ensure differences in characters if the developer chooses to use that

COULD BE IMPLEMENTED:

- Dialogue can’t be an inherent part of the character attributes due to its dependence on a game’s situation, but class could still have more of an impact on it
- We could work with the NPC team to make names and responses more dependent on player class
- Could expand on the prefabs to give developers greater options for different characters and ensure variety
- In addition to item multipliers, there could be additional features with item interaction (special uses, repeated uses, maybe this falls under skills?) that are dependent on class

**Comment by katie-gao** [comment]
Having reviewed the user stories on the game developer side, there is implementation of a hashtable that adds stats. There is also some case sensitivity in retrieving the names of classes. There is also implementation of adding, removing, and multiplying items. Things that could be implemented are more thorough structs that are case sensitive, and more developed doubly linked lists for the move_list and new_move_list structs. Class_show only displays the class name and description. Currently, there is also little implementation of the display system - everything comes out on the console. The only class with more functionality is warrior and should expand beyond that. Also, basic initialization of a class needs progress - relating to skills, and class_new can have better implementation beyond deep copies.

**Comment by vanolson** [comment]
We looked through all 5 user stories and evaluated how much they were reflected in the implementation, as commented on this issue (Katie did the first two, Vincent the next two, I the last).

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work! Make sure to assign new issues to the sprint they are worked on (by selecting the appropriate sprint under "Milestone").
