### ISSUE TITLE
npc: Review state of NPC dialogue and update existing documentation/create wishlist

### ISSUE THREAD

**Issue by sglenn-uchi** [uchicago-cs/chiventure#1192]
members: Sydney
task: Review state of NPC dialogue and update existing documentation/create wishlist
status: There is developed documentation on the npc-dialogue module but less documentation on the integrated modules (mainly introductions/links to their respective wiki pages). The header file is fleshed out fully. The source file is nearly complete aside for quest and battle functionality (dependent on the implementation of those modules first). Added links to dependent modules in wiki.
wishlist:  Communicate with the quests and battles teams to assess progress on those modules. Based on those teams' goals for the next sprint, decide whether implementing some degree of quest and battle integration into conversations is feasible. If it is, implement functionalities and either update existing demos or create new ones to test. Create more complex edge disabling logic. Add more actions for conversations (for example, recruiting NPCs to join player character on adventures, maybe unique behavioral actions that trigger certain dialogue responses). Test demos thoroughly to establish current state of functionality and identify potential bugs. Create new ones if necessary (especially if designing new actions).

**Comment by sglenn-uchi** [comment]
There is developed documentation on the npc-dialogue module but less documentation on the integrated modules (mainly introductions/links to their respective wiki pages). The header file is fleshed out fully. The source file is nearly complete aside for quest and battle functionality (dependent on the implementation of those modules first).

**Comment by sglenn-uchi** [comment]
Added links to dependent modules in wiki.

**Comment by sglenn-uchi** [comment]
Updated design doc. Existing Wiki page was written before `mode.h ` was created (solution to the issue of potential battles and quests being started and overlapping with dialogue by having game states switch between modes for each one) so that future members of NPC team know that a course of action has been decided.

**Comment by sglenn-uchi** [comment]
Noticed that although `add_start_quest` and `add_start_battle` functions are designed, functions are not implemented. Similarly, the `START_QUEST` and `START_BATTLE` cases of the `do_node_actions` function are not implemented. This is because at the time these functions were designed, quests and battles had not been developed enough for them to be integrated into the dialogue module.

Future work will require communication with the quest and battle team to learn about their plan for the quarter. If they are planning to flesh out these features of the game engine this quarter, consider implementing these functions and developing updated tests and demos to check their functionality.

**Comment by sglenn-uchi** [comment]
**Battle and Quest Integration:**
Dependencies:
- game-state: Also for implementing conditional dialogue, particularly for item usage, which could be connected to conversation-instigated quests or dialogue (condition.h).
- cli: For switching between "conversation" and "normal" modes (mode.h), the latter of which would enable battles and quests to be initiated after pressing certain dialogue options. 

Wishlist: 
-  Communicate with the quests and battles teams to assess progress on those modules. Based on those teams' goals for the next sprint, decide whether implementing some degree of quest and battle integration into conversations is feasible. If it is, implement functionalities and either update existing demos or create new ones to test. 

**General Wishlist:**
- Add more actions for conversations (for example, recruiting NPCs to join player character on adventures, maybe unique behavioral actions that trigger certain dialogue responses).
- Create more complex edge disabling logic. 
- Test demos thoroughly to establish current state of functionality and identify potential bugs. Create new ones if necessary (especially if designing new actions).

**Comment by sglenn-uchi** [comment]
Finished updating documentation and researching code.

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this issue!
