### ISSUE TITLE
rpg-skilltrees:  assess how well skilltrees are integrated into chiventure and directions for future work regarding integrating skilltrees with other chiventure features

### ISSUE THREAD

**Issue by KabirDubey** [uchicago-cs/chiventure#1194]
We will ...
-study how the idea of skilltrees (as described in version one here https://github.com/uchicago-cs/chiventure/blob/dev/docs/skilltrees.md) could be used in the chiventure world and make record of how it has been used so far
-follow mentions of skill trees in issues and pull requests to understand the functionalities in the existing skilltrees library that are of most interest
-specific areas of interest include: the WDL libraries for global skill tree integration, the other RPG features
-plan future integration tasks

team members: arya, chelsea, kabir

**Comment by KabirDubey** [comment]
"Summary of Skill Tree Integration 2022" wiki page was created after an initial review of the player class module, previous wiki pages, and the entire repository on face. 

The description of the first version of the skill trees module refers to a front-loaded design that is supposed to be good for integration; we should comment on what this means and if it has been effective so far. We should also elaborate on what parts of the skill trees module are of the most interest. Lastly, we should review my formatting and proofread .

**Comment by arya32hub** [comment]
Integration of Skill trees

https://github.com/uchicago-cs/chiventure/wiki/Skill-Trees--Integration

**Comment by arya32hub** [comment]
Updating and finalising wiki page. Issue will be revisited if any new integration possibilities come up in the future.

https://github.com/uchicago-cs/chiventure/wiki/Skill-Trees-~-Summary-of-Skill-Tree-Integration-2022

**Comment by jacknugent1529** [comment]
Issue Score: S

Comments: Nice work on the wiki page! For the updates and closing statements, please be sure to give details about what has been accomplished since the last update.
