### ISSUE TITLE
gui: identify feature wishlist and trajectory of what graphic elements to implement

### ISSUE THREAD

**Issue by imadejski** [uchicago-cs/chiventure#1195]
In this issue, I will go through the existing Wiki and look at the design plan and documentation as well as the wishlist from 2021 to see what the future direction of the gui team is and what next steps we should be taking.

**Comment by imadejski** [comment]
Some things that were noted from the previous year as wishlist items that we could work on:
Now: Split screen (previously in progress) - shows image of room with `chiventure`
- implementation of draw_object

Later: Personal information (i.e. inventory, HP, etc), Dialogue, Map on screen

**Comment by cyruszzhou** [comment]
- NPC Graphics
    - Motion
    - Facial Expression
    - Modular Design for Game Designer
- Interface Personalization
    - Brightness
    - Color Theme
    - Size
- Fixing (Juxtaposing) Item
    - Map on the screen
    - Holding an Object
- Converting existing images to be terminal-displayable
    - Cutscene
    - Intro
    - Potential library: Chafa

**Comment by nicholaswlee** [comment]
Nafis and I created the [Battle Planning 2022](https://github.com/uchicago-cs/chiventure/wiki/Battles-~-Battle-Planning-2022) page that outlines our goals and wishes for this Spring, as well as how these could be implemented and where they can implemented.

**Comment by cyruszzhou** [comment]
We formed rudimentary ideas on what to do next. This issue is closed.

**Comment by philipchenaux** [comment]
Issue Score: Satisfactory

Comments:
Great work, there are just two minor tweaks that you can make to improve your issues for next time:
1. Make sure to assign new issues to the sprint they are worked on (by selecting the appropriate sprint under "Milestone")
2. Remember that Scrum board cards should be converted to issues shortly after the Sprint meeting. Think of the Scrum board card as a rough outline of the issue, which you then need to flesh out with a more descriptive title and summary when converting it to an issue.
