### ISSUE TITLE
GUI: Design an inventory for users/game devs

### ISSUE THREAD

**Issue by dhirpalshah** [uchicago-cs/chiventure#1196]
Chiventure needs players to be able to have a inventory when going on their adventures, so we want to create a visual representation of the inventory for players. Ideally, we use raylib to create a set of boxes within a box. Each box will be able to hold one item, which players can interact with by clicking on it. Hopefully we are able to integrate this into the WDL to fit the desired specs of the game developer.

**Comment by dhirpalshah** [comment]
4/28 Meeting:
Urunna and I have been looking at how we can design this inventory. It relies heavily on the inventory struct that the Action Management team have been implementing. Depending on that, we can tailor the creation of the inventory display. In the meantime, we are encountering this issue when trying to run raylib still:
`draw_images.c:3:10: fatal error: 'raylib.h' file not found
#include "raylib.h"
         ^~~~~~~~~~
1 error generated.`
This means that we cannot actually go in and implement raylib.h functions. In the meantime, we will continue figuring out the parameters for the functions required to make an inventory display.

**Comment by ukanyanwu** [comment]
4/28 Meeting:
@dhirpalshah and I made a first pass consideration of some functions that would represent the inventory. open_inventory (to open it), close_inventory (to close it), move_item_inventory (to have a visual representation of moving items in inventory if that is allowed in the inventory implementation), and populate_inventory (to add items into the inventory). These are barebones design ideas as we still need to understand how the inventory is represented internally in chiventure, how much of the visual aspects are up to the developer's discretion, and our access to raylib in seeing that we've properly used different structs within the library.

**Comment by dhirpalshah** [comment]
We have successfully come up with a barebones idea of how we will go about implementing this inventory design. We realized that we are going to need help from the action management, so I contacted them and they will report back to me with the struct that they use to create an inventory, then we will use that struct to fully determine how to display the inventory.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Excellent issue, just make sure to add the correct milestone next time!
