### ISSUE TITLE
Review State of NPC Movement and Update Existing Documentation/Create Wishlist

### ISSUE THREAD

**Issue by bvvill** [uchicago-cs/chiventure#1197]

**Comment by bvvill** [comment]
Upon inspection of npc.md, in the docs folder, it was apparent that the file hadn't been updated in quite some time, and did not include documentation of the npc_move or npc_battle modules. In the npc/move/update-documentation branch, I have added the general features of both of those modules as well as a possible next step for the npc_move module. In the npc/move/update-documentation branch, I have also implemented a get_npc_mov function, as the npc_mov_t member of the npc struct was the only one that didn't have an implementation of a "get _____" function. I also slightly rearranged a few of the functions in the npc.h/.c modules in order to group those functions with those similar to them.

**Comment by bvvill** [comment]
> Upon inspection of npc.md, in the docs folder, it was apparent that the file hadn't been updated in quite some time, and did not include documentation of the npc_move or npc_battle modules. In the npc/move/update-documentation branch, I have added the general features of both of those modules as well as a possible next step for the npc_move module. In the npc/move/update-documentation branch, I have also implemented a get_npc_mov function, as the npc_mov_t member of the npc struct was the only one that didn't have an implementation of a "get _____" function. I also slightly rearranged a few of the functions in the npc.h/.c modules in order to group those functions with those similar to them.

this was my closing statement

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work! The issue did not include a descriptive summary (see https://uchicago-cs.github.io/cmsc22000/project/issue-pr-grading.html#descriptive-summary for more details and concrete examples)
