### ISSUE TITLE
GUI : Familiarize with Raylib and modules within GUI Feature

### ISSUE THREAD

**Issue by ukanyanwu** [uchicago-cs/chiventure#1198]
An important goal for the first sprint is getting an introduction and building knowledge to the Raylib Library and its integration into the gui.c/.h and draw_images.c/.h for the GUI feature. This will provide smoother progression in future sprints as time is focused into actually implementing and fixing modules that have been made, and will be made in the future, such as inventory, NPCs, or drawing objects.

**Comment by csraffaga** [comment]
Status update: connected with @ukanyanwu between 4 and 7 CST on Sunday 4/24. Read through the raylib wiki page, focusing on library design (architecture, syntax analysis, enumerated types), identified and analyzed common functions and their documentation (InitWindow(), while loops with !WindowShouldClose(), BeginDrawing(), as well as data structures: Vector2, Image, Texture etc... Reviewed common examples of these implementation in publicly-availible games.

**Comment by ukanyanwu** [comment]
@csraffaga and I met on Monday to go over Raylib's use in the draw_images module and it's possible issues related to Issue #973. Though our first pass of the module did not show any glaring issues for it not working, it did allow a deeper dive into a practical implementation of the abilities that Raylib has to offer in chiventure. DrawRectangle, DrawTexture, and UnloadImage are identified as staple functions that will be useful for implementing future graphics in chiventure. Though specific for gui features relating to rooms, the parameters of room_t structs are properly acknowledged without a need to seeing its official definition.

**Comment by csraffaga** [comment]
@ukanyanwu and I wrapped up our study of raylib this morning with a series of tutorials from SkyVault Games on Youtube. We are now set to lead the implementation of new features for future sprints; this first sprint provided there required knowledge for the development of inventory and other object features!

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great work on this issue, especially the thorough set of updates.
