### ISSUE TITLE
Design the system for adding quests/achievements as prerequisites for other quests

### ISSUE THREAD

**Issue by JSerf02** [uchicago-cs/chiventure#1199]
Currently, the quest prerequisite system is a little bit messy and only supports specifically hard-coded prerequisites for quests/achievements. We would like to create a new design for this system that support other quests and achievements as prerequisites so completing a quest can unlock other quests. Also, since each of the current prerequisites can be represented through either active or passive achievements, we can also look into removing the current prerequisites and replacing them with the new achievement system so code isn't repeated.

**Comment by JSerf02** [comment]
Created a [Wiki](https://github.com/uchicago-cs/chiventure/wiki/Quests-~-Prerequisite-System-Redesign) for the new redesign and added an overview of the intended functionality of the new system

**Comment by JSerf02** [comment]
Updated the [Wiki](https://github.com/uchicago-cs/chiventure/wiki/Quests-~-Prerequisite-System-Redesign) with info about the data structure changes Charlie and I decided on during our meeting.

**Comment by JSerf02** [comment]
Added the other changes required for the new prerequisite system redesign to the [Wiki](https://github.com/uchicago-cs/chiventure/wiki/Quests-~-Prerequisite-System-Redesign)

**Comment by JSerf02** [comment]
Completed the prerequisite system redesign and documented it in the [Wiki](https://github.com/uchicago-cs/chiventure/wiki/Quests-~-Prerequisite-System-Redesign).

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great work! One minor comment though: If, as part of an issue, you have a meeting or conversation with other developers, make sure to include a summary of that conversation, with an emphasis on any decisions that were made in that conversation. It is not enough to just state that you talked with someone and add a link the wiki.
