### ISSUE TITLE
Reintroduce support for action synonyms

### ISSUE THREAD

**Issue by yoonsjeong** [uchicago-cs/chiventure#120]
We removed synonyms from our action struct due to some complication in creating structs in get_supported_actions function. Here are the three actions that would require synonyms.

    TAKE,    // synonyms: "pick up"
    CONSUME, // synonyms: "use" "drink" "eat"
    GO,      // synonyms: "walk" (as in WALK east)

**Comment by isaacfink21** [comment]
I will be resolving this issue for this sprint.

**Comment by isaacfink21** [comment]
Action synonyms have been re-introduced as legal for the following actions:
```
/* KIND 2: <PATH> */
GO, // synonym: WALK
/* KIND 1: <ITEM> */
CONSUME // synonyms: USE, EAT, DRINK
```
The `WALK` synonym is now fully functional, and the other three synonyms are legal but require implementation from CLI. As there are now two versions of the 'use' action, the original version (kind `ITEM_ITEM`) has also been refactored to `USE_ON`.

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Great job picking up this backlogged issue!
