### ISSUE TITLE
Create Test for new functionality "delete one or all quest"

### ISSUE THREAD

**Issue by jakeziqiwei** [uchicago-cs/chiventure#1203]
We wrote a function for deleting one or all quests. However, we still need to create tests to see if the functionality is working properly.

Action items for this issue for spring 2
1)understand how testing is done for chiventure
2)refer to the current implementation wiki for more details
3)create actual tests

**Comment by jakeziqiwei** [comment]
Elizabeth and I met up to write tests for the remove_quest function which we wrote in sprint one. We used this [documentation](https://criterion.readthedocs.io/en/master/parameterized.html) and quest wiki to aid in our understanding. In this week's sprint, we mainly looked into two things. 
1)writing tests for the function 
2)understanding current tests and if they are sufficient. 

Firstly, we have written the test for the sprint 1 function. However, because of the ongoing reformatting of quest_ID, we were reluctant on testing the code until we catch up with other team members' week 2 sprint tasks. Since it is their current task, we needed to wait till the next sprint to see what they have accomplished.

Secondly, we have realized that all of the functions in quest_state that involve hashtables have not been properly tested. We have decided not to add it to this week's official sprint tasks, but we have already started to prep writing tests for those.

**Comment by philipchenaux** [comment]
Issue Score: Satisfactory

Comments:
Great work! Here are two ways you could improve the issue for future sprints:
1. When an issue is done, you should include a final comment summarizing what was done, and why the issue is being closed.
2. Make sure to assign new issues to the sprint they are worked on (by selecting the appropriate sprint under "Milestone")
