### ISSUE TITLE
Rename "achievements" to "tasks" in the quest code and documentation

### ISSUE THREAD

**Issue by JSerf02** [uchicago-cs/chiventure#1204]
The current use of the term "achievement" is extremely misleading, as even though achievements in games typically refer to large, overarching goals that persist throughout gameplay, achievements in Chiventure refer to smaller goals that are local to individual quests. This can become incredibly confusing if Chiventure ever implements a true achievement system. To fix this, we propose renaming "achievements" to "tasks", which is a term we believe better describes the feature.

**Comment by JSerf02** [comment]
Renamed all instances of "achievement" in the code to "task", including in quests_state.h, quests_structs.h, quest_example.c, quests_state.c, and test_quests_state.c. Also double checked tests and they all pass!

**Comment by JSerf02** [comment]
Renamed all instances of "achievement" in the wiki to "task".

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great job! In the future try to offer a more comprehensive closing statement to the issue though.
