### ISSUE TITLE
Path Generation: Designing a pathgenerate function

### ISSUE THREAD

**Issue by williamhu314** [uchicago-cs/chiventure#1206]
This issue aims to determine how the item will be determined in a randomly generated path. This issue is related to issue #1178.

Update: The purpose of this issue has changed. I am now aiming to determine how to generate a path and the item in the path in a somewhat random way but not automatically-the generation will rely on a provided list of path specifications.

**Comment by williamhu314** [comment]
I think that creating something like a pathspec struct similar to the roomspec one might work for item generation. It is not ideal but it will make implementing a path generate function much easier and I think that making sure such a function exists is more important right now than improving the autogeneration algorithms currently in place. 

Additionally, a path generate function, along with the current room generate function, that rely on path and room specifications, could still be very useful if the user would like to generate a room with very specific specifications but that still has a little bit of randomness involved (e.g. maybe the user wants some main rooms in the game to have a certain specification and to only vary between a few different types of rooms between games). So a path generate function that relies on a list of path_specs as an input is probably still going to be important-the generate functions will still create rooms that vary from game to game more than the room_new and path_new functions (which create fixed paths and rooms), but it won't be as random as rooms and paths completely autogenerated based on the neighboring ones (which we hope to potentially implement later)
 
If time allows, we may try and find a way to create new autogenerate algorithms that generate rooms more autonomously later on. This will be useful for someone trying to make a game as they can have certain main rooms and paths in the game near where the player starts be fixed using room_new and path_new, have rooms farther away with certain specifications to make the game interesting but to still have some consistency, and then allow the game to autogenerate as many rooms as needed with no specifications for the rooms farthest away. 

Our pathspec struct will likely need the following fields:

1. A list of item specifications
2. A list of possible conditions or a list of condition specifications (I do not think a condition_spec struct currently exists so we might need to implement one)
Additional Possible Fields:
1. Descriptions (maybe short and long like for room_spec)
2. A name (might not be necessary but maybe this can be an optional field as some really important paths might need names)
3. A list of possible directions (maybe the user wants to restrict the possible directions this path goes in). Might be unnecessary.

I will now aim to figure out exactly how to generate the item once the pathspec struct exists based on the room_generate function.

**Comment by williamhu314** [comment]
As for the item field, I think I may have misinterpreted it as looking at the room.h module in game-state, it seems like it just specifies whether the door is open or not. I will need confirmation from the game-state team to make sure this is the case, but if it is, then there is no need to worry about generating an item.

If this is the case, a path_generate function may also be unnecessary as in that case most of the functionality is provided by the roomgenerate function and there is not much that needs to be generated randomly. I think that instead, adding more functionality to the room_generate function by adding a list of possible conditions as in input would be more appropriate. This would achieve the same goal of allowing paths to change between games with much less work.

**Comment by williamhu314** [comment]
After talking to Lukas about how we plan to autogenerate rooms and eventually paths, I have decided to save this issue for the next sprint. After we complete more of the room autogeneration tasks, I think it will be much clearer as to what the exact purpose of our pathgenerate function will be. I am thus moving this issue to the backlog for now.

**Comment by williamhu314** [comment]
We are not currently working on automation for generating the conditions for paths randomly so we will close this issue.

**Comment by williamhu314** [comment]
We are not currently working on automation for generating the conditions for paths randomly so we will close this issue.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Excellent work on the issue, especially with the comments. In the future make sure to close the issue at the end of the sprint!
