### ISSUE TITLE
Design NPC Figure/Image Developer Tool

### ISSUE THREAD

**Issue by cyruszzhou** [uchicago-cs/chiventure#1209]
The NPC graphics is something no team has touched upon previously. We are trying to figure out a way to store all relevant information for displaying NPC graphics in a proper data structure and design the whole npc graphics module in a way that it collaborates well with the main program (and the parser).

**Comment by imadejski** [comment]
This issue wasn't previously closed, but Cyrus, Urunna, and I planned out how to display npc graphics for the npc graphics module. This was a design process within the npc graphics module.
We decided on creating a struct for the NPC info as well as a hashed/linked list that uses the action name as a key and the path to the image and the frame numbers of that image as the values. The module will pull the action struct, line struct, graphics info, and npc info to put into the npc graphics structs which will be used to run the runNPCgraphics function.
Module design completed.

**Comment by cyruszzhou** [comment]
We close this issue as everything specified is completed and the whole NPC module is now in a good shape!

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great work! Next time it is worth adding links to wikis/code that outline the exact specifications so that anyone who reads through this issue can follow what is going on.
