### ISSUE TITLE
GUI: Design the implementation and adjustments necessary for a stats feature with information on the user's character

### ISSUE THREAD

**Issue by csraffaga** [uchicago-cs/chiventure#1210]
Adventure games involve characters interacting with their environment, but it may also be the case that the environment of a player impacts him or her in some way. This is apparent with the introduction of multiplayer, NPCs, battles, etc... As such, there should be an option for the user to view his/her health or other similar statistics (strength, level/quality of armor, hydration, nutrition etc...). These features can be presented on screen with support from Raylib either as a graphical meter, displayed value, or in some other form. The challenge of this task is to decide what statistics ought to be present by default, how to enable custom statistics, how to display these statistics, and what dependencies need to be adjust / are affected by this feature.

**Comment by csraffaga** [comment]
Met with @milesgardner from the CLI team and @jbrouwer5 from action-management to develop an outline for the implementation of graphical statistics feature that would depend on updating the cli and game-state/action-mangement modules and functions. This was very similar in spirit to the design warm up exercises.

**Comment by csraffaga** [comment]
Successfully outlined a display_stats.h/c set to provide the foundation of a statistics feature as part of an enhanced GUI. These files are also very general purpose and can potentially integrate other GUI features such as viewing inventory which @dhirpalshah and @ukanyanwu are currently working on. Next steps include implementing this feature with use of raylib (likely to be done in Sprint 3 if it can be reconfigured to function again). Moreover, I have contacted the CLI and Action-Management teams to begin to provide support for this feature.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great work on this issue, make sure that if, as part of an issue, you have a meeting or conversation with other developers, you include a summary of that conversation, with an emphasis on any decisions that were made in that conversation. It is not enough to just state that you talked with someone. Try to explain more concretely about what was discussed!
