### ISSUE TITLE
Reorganize Wiki links to make information more central

### ISSUE THREAD

**Issue by elizabethli31** [uchicago-cs/chiventure#1211]

**Comment by elizabethli31** [comment]
I combined the "current implementation" and old design document onto one page. I also changed the API documentation to differentiate between where quests are integrated and where we hope to include them

**Comment by philipchenaux** [comment]
Issue Score: Satisfactory

Comments:
Great work! Here are a couple of aspects that you could improve upon:
1. Even though you can add labels to issues to categorize them, you should avoid titles that could plausibly apply to multiple teams.
2. The issue did not include a descriptive summary (see https://uchicago-cs.github.io/cmsc22000/project/issue-pr-grading.html#descriptive-summary for more details and concrete examples). Make sure to add one next time!
