### ISSUE TITLE
rpg-skilltrees: communicate with other teams and specify possible future features (wiki page)

### ISSUE THREAD

**Issue by KabirDubey** [uchicago-cs/chiventure#1212]
We will use Slack (group chats, dev-rpg channel) to reach out to other chiventure teams. We're interested in how they plan on scaling their features and how their ideas require further development of skilltrees. We will specify modules and functions of interest, updating the wiki page accordingly. 

Team members: Kabir, Arya

**Comment by arya32hub** [comment]
So far have made contact with command line team, and actions management team.

**Comment by arya32hub** [comment]
Creating a google form and trying to get each team to fill it out

**Comment by arya32hub** [comment]
Reached out on slack with google form to RPG-quests, RPG-openworld, RPG-battle and RPG-NPC.

**Comment by KabirDubey** [comment]
The WDL team reached out to us with some questions. I updated the wiki page with a section that explains the way skilltrees would be integrated with WDL and points out some files and lines of code that they can look at. We will try to understand how WDL++ works (i.e. the libobj organization) to see their perspective and make any updates on our end more seamless.

Also slightly changed the formatting of the wiki page for readability.

**Comment by KabirDubey** [comment]
Google form has been released and wiki page finished. We're starting with the prefabs backlog tasks as ordered in the action items section. The wiki page will be updated as we learn more about integration.
