### ISSUE TITLE
DSL: create a feature wishlist, and communicate with other teams about features to add to the dsl

### ISSUE THREAD

**Issue by baigh1** [uchicago-cs/chiventure#1214]
team members: Alex, Andi, Hira

Want to converse with the
- NPCs
- Sound
- GUI/Graphics
- Battles
- Skill Trees
- Quests

teams to determine what they are currently supporting in the WDL/ how they would like to be represented in the WDL. Then we can convert such a format in the DSL.

-----------------------------
### **Sound Team:**

The audio files used by the game are in .wal format. The sound Team is in extremely early stages of development. This means that implementation into a WDL format is further down the line for this team. A current format is in the works for what integration would look like. For example, it is likely that entering a new room would trigger a new sound effect, so in addition to a "short" and "long" description, there would be an extra field denoting which audio file should trigger. Additionally, an action resulting in a success or failure might trigger different audio files. Additionally, talking to an NPC or beginning a battle would cause an audio to play. As a result of the complex interactions between teams for the sound module, it is imperative that once a WDL format begins to take shape we discuss the different parsing strategies needed to incorporate sound in the DSL. It may be simplest for our DSL to have an audio field for each room/action, although this can be discussed in more detail.

As of the time of this writing, the Sound Module parsing is unable to move forward.

### **NPC Team:**

In the npc/ directory in chiventure, there exist some example JSON/WDL files that depict how NPCs will/are currently implemented in the game. These files are not completely up-to-date with the module's progress, but it serves as a great stepping stone to begin parsing development related to NPCs. NPCs are quite a complex element in the game, so there are many things to consider (including their movement (may be tied in with AI), quests/battles triggered by dialogue options, differing dialogue options based off location, etc). As such, it will be necessary to do a deep-dive of their current implementation in WDL format and create a detailed design document. NPCs in our DSL will likely be a separate object, with it's own short and long descriptions, player class, battle attributes, etc. Additionally, since some NPCs move depending on whether an event has taken place, this also needs to be considered.

At the current stage, a new upcoming task can be to focus on implementing NPCs in the DSL (starting from a design document).

**Comment by baigh1** [comment]
Had a short meeting with the Sound Team today. We discussed where they are currently at in development with the game and how possible implementation would look. We have identified some ways they would incorporate sound into the WDL file that we can take a look at, primarily with "actions" and "rooms." Further details listed in documentation.

**Comment by baigh1** [comment]
Had a short meeting with the NPC team. In their directory, there exists a WDL/JSON file depicting the way NPCs would be represented in the file. I believe it would be very helpful for the team to look at this and make this one of our upcoming tasks to implement in the DSL. I obtained a lot of information on the role of NPCs in the game (their locations, movement, AI) which will be detailed in the documentation.

**Comment by awliu2** [comment]
Reached out to the battles and graphics teams a few days ago. Still waiting on a response from graphics team, will follow up today. Also reached out to one of the members on the battles team who I've worked with before to talk with them about exactly what features they have/want that we can potentially implement.

**Comment by alexlee0422** [comment]
Also reached out to the skilltrees and quests teams and asked if they currently have any features that are represented in the WDL format or if they have any potential features that can be represented in the WDL format. Still waiting on their response and will update when response received.

**Comment by alexlee0422** [comment]
So far only the quests team replied. This is what they said "I'm not sure exactly what parts of quests interact with the WDL file format, but I'm sure that there is a way to specify the creation of quests there in some capacity (and if there isn't that something important that you all might want to work on ig). Being able to convert quest information from plaintext to the WDL file would probably be quite useful from a user perspective. You might want to take a look at the quest_structs.h file in include/quests, or the respective wiki page, which should give you a good understanding of how quests are structured in Chiventure, which in turn would help you decide how you would want to implement it in your own tools. However, we are currently in the process of making a few changes to this structure, so the exact specifics are subject to change. Hope this helps!"

**Comment by awliu2** [comment]
I've created a document with some potential ideas that I came up with, as well as ideas suggested by the sound and battle teams. Let's put all the ideas we come up with here!
https://docs.google.com/document/d/1MQB3eiYH9IULgNNgstEHH0wjD5kYBGQ01em_41DzTZc/edit?usp=sharing

**Comment by awliu2** [comment]
Added some comments/notes on the ideas document, i.e what would be easier/harder/interesting/fun to design and implement.

**Comment by baigh1** [comment]
Added notes in Google Doc as well as in this issue. As communication with other teams continue, the DSL team can update as needed.

**Comment by baigh1** [comment]
Added notes in Google Doc as well as in this issue. As communication with other teams continue, the DSL team can update as needed.

**Comment by jacknugent1529** [comment]
Issue Score: S

Comments: Nice work on this issue! The updates are especially thorough and will be useful as documentation. Try to avoid using google docs, since it's not as accessible for future teams to view. Also, the closing comment should give a brief summary of what was accomplished and why the issue is complete
