### ISSUE TITLE
DSL: produce a design document for player classes (similar design warmups 1 and 2)

### ISSUE THREAD

**Issue by baigh1** [uchicago-cs/chiventure#1215]
We wish to figure out how player classes are represented in the WDL, and design the grammar and conversion rules in order to support player classes in DSL, and have a foundation to work from for future implementation.

Team members: William, Jay, Hira

**Comment by jhsivadas** [comment]
William, Hira, and I developed an outline for defining a new Player class within the to_wdl.py file. We used the struct from teh Player Class design wiki as reference for how to outline the instance variables and functions. The player class takes into account the general values (contents, defaults) and also allows for Player specific attributes like the parent class and player name. The functions encompass the general functionalities of the wdl classes but also build lists for attributes, stats, skill_trees, etc... that are unique to the player. Below is how we designed the class:

In to_wdl.py:

```
class Player:
	def __init__(self, contents: dict, default: str):
		Self.parent_class = parent_class
		Self.name = name
		Self.contents = contents 
		Self.default = default
		
		Self.wdl_contents = {}
		
	def to_json(self) -> str:
		
			#For internal testing only: converts an item to its json format

	def to_wdl_structure(self) -> dict:
	

	def generate_defaults(self):


	def attributes_list (self) -> list:


	def base_stats_list (self) -> list:


	def actions_list (self) -> list:
```

Change lark line to support player class.
	
In dsl_garmmar.lark:
playerclasses: (Identify grammar parsing for each element needed in a playerclass struct (short descr, long descript, list of attributes, skills, etc.)	

Reference for Player Class
Reference: https://github.com/uchicago-cs/chiventure/wiki/Player-Class-~-Design
```
class_t struct
char* Name
char* Short description
char* Long description
obj_t* Attributes
stats_t* Base Stats
effects_hash_t* Effects
skill_inventory_t** Combat Actions
```
UT_hash_handle Field for use by UTHASH macros

CLASSES_WDL_PATH depicts whether game has been successfully loaded from WDL
"../tests/wdl/examples/wdl/classes.wdl"

**Comment by baigh1** [comment]
The playerclasses module has the following Wiki page describing what their current WDL support looks like, along with an example WDL file. 

https://github.com/uchicago-cs/chiventure/wiki/Player-Class-~-Loading-Classes-from-WDL

Supported class_t fields are:

"prefab": Marks whether a prefab class should be loaded in.
"short_desc"
"long_desc"
"attributes"
"base_stats"

EXAMPLE:

{
    "GAME": { ... },
    "CLASSES": {
        "Knight": {
            "short_desc": "Knight's short description",
            "long_desc": "Knight's long description",
            "attributes": {
                "noble": true,
                "hot-headed": true
            },
            "base_stats": {
                "health": {
                    "current": 100,
                    "max": 200
                },
                "mana": {
                    "current": 20,
                    "max": 100
                }
            },
            "effects": null,
            "skill_tree": null,
            "starting_skills": null
        }
}

**Comment by baigh1** [comment]
Using the current features supported in the WDL from playerclasses (information above) in addition to the design document, we are able to move forward with implementing the support for playerclasses in the DSL.

**Comment by jacknugent1529** [comment]
Issue Score: E

Comments: Well done! The updates are detailed and linking the relevant wiki pages is useful as reference. In the future, try to be more specific in the closing statement about the work that was done and why the issue is now complete
