### ISSUE TITLE
cli: reach out to other teams, and create a feature wishlist 

### ISSUE THREAD

**Issue by bzeng6** [uchicago-cs/chiventure#1216]
Team members: Faruk, Miles, Brianna

We would like to form a list of ideas for CLI features that other groups would like to see implemented/improved for use in their own functions. We should reach out to them to get their input and also meet with them to get information on their specifications.

**Comment by bzeng6** [comment]
I created a Google Form that could be circulated to the other teams
https://forms.gle/KvMNcBu2HY8YbtYw9

view responses: https://docs.google.com/forms/d/1uKwP97Dk7KJWmErdDCqMhLU8midFSlyH9wZv52i4tT4/edit?usp=sharing

**Comment by milesgardner** [comment]
I just spoke with GUI team member Gabe Raffa, and we're in the works for developing a popup screen that shows advanced stats on a users' character.  On our end, we'd have to be able to parse a command like 'view stats' or 'view the stats', and subsequently call the related function.

**Comment by milesgardner** [comment]
> I just spoke with GUI team member Gabe Raffa, and we're in the works for developing a popup screen that shows advanced stats on a users' character. On our end, we'd have to be able to parse a command like 'view stats' or 'view the stats', and subsequently call the related function from the GUI team.

Also, I've spoken with a member on Action management - we may also need to identify the required action (i.e. view).

**Comment by bzeng6** [comment]
RPG Battles group has published a page where they detail how they would like to integrate CLI into a "run battle" function for NPC battles to streamline selecting actions and items during battle:
https://github.com/uchicago-cs/chiventure/wiki/Battles-~-CLI-Integration-Design-Document
I think it would be best to discuss with them personally how they plan to do this, and design/implement improved CLI functionality if necessary—I just contacted them on Slack.

**Comment by bzeng6** [comment]
05/02/22: Hopefully we can plug the Google Form and/or encourage people to reach out to us with collaboration ideas today at the all-hands meeting.

**Comment by bzeng6** [comment]
I created a page that lists out the ideas we've collected so far, access it [here](https://github.com/uchicago-cs/chiventure/wiki/Enhanced-CLI-~-Feature-request-wishlist-from-other-teams).

**Comment by bzeng6** [comment]
We have reached out to other groups and documented the ideas they have for CLI features onto a Wiki page. I'm closing the issue because we have collected a few ideas and have spoken with other groups about it, but we can reopen it/update the feature wishlist if more groups reach out.

**Comment by jacknugent1529** [comment]
Issue Score: E

Comments: Excellent work! Nice job summarizing various meetings and discussions that occurred. The closing statement is also good, although another thing to add would be to state the work each group member did.
