### ISSUE TITLE
sound: fix demo compiler errors

### ISSUE THREAD

**Issue by parkerbroz** [uchicago-cs/chiventure#1218]
For this issue, we are going to try to fix any bugs in the demo that was created last year and then compile it to be able to run on the CSIL machines without errors.

members: Parker, Rhea

**Comment by sangerr** [comment]
I was able to get the demo to run in the src/sound/examples directory on the CSIL computers.

**Comment by sangerr** [comment]
The reason that the demo was unable to compile through ssh is based on the way that the makefile is designed. In lines 2 and 3 of the Makefile, it has the path directory to the SDL libraries which is different on the CSIL computers than when ssh-ing. I am trying to change the path and then re-run it on ssh.

**Comment by sangerr** [comment]
The main.c is able to compile in the sandbox, but when running the main program on the CSIL computers, I am getting errors regarding the inability to load the wave files. We need to fix the load function to be able to target this issue in the future as loading files is essential to the sound function.

**Comment by sangerr** [comment]
This issue is being closed as the demo was able to run smoothly on the CSIL computers with no compiler errors. We will be using VM in future sprints and will make sure that the demo is working there as well.

**Comment by ecoble** [comment]
Issue Score: Satisfactory

Comments:
Nice job debugging this, compiler issues are not easy! Please be sure to include the milestone on the issue, and additionally in the future see if you can flesh out the summary a bit more.
