### ISSUE TITLE
Create a design document for integrating NPC actions and dialogue

### ISSUE THREAD

**Issue by sglenn-uchi** [uchicago-cs/chiventure#1220]
Dialogue in Chiventure currently lacks any custom actions that can be taken in conversation. As of now, users can respond with standard dialogue options, give items, or take items. However, adding a range of custom actions could enhance the variety of potential conversations. Designs for a couple of new actions, including `STEAL`,`TRADE`, and `BUY` within the could easily be integrated into the `node_actions` struct in the `dialogue` module to represent actions. We will then create a design document explaining a future implementation of these actions into conversation.

**Comment by junasano** [comment]
We had a meeting to discuss directions on the documentation and decided to focus on the following aspects: 
   1. Explain implementation with actions and dialogue modules
   2. Explain the design for NPC types corresponding to different actions (kinds 4-6)
   3. Mention ideas/wishlist for a module such as on currency/currency use/exchange in NPC interactions
   4. Adding general documentation for the action module

**Comment by sglenn-uchi** [comment]
Made first draft of design doc. Includes introduction to existing and new design in NPC Dialogue and Actions as well as a wishlist for 2 potential new features– currency and NPC personality and mood.

**Comment by junasano** [comment]
Made first draft of action document which is linked with the dialogue-action documentation. [NPC Action Documentation](https://github.com/uchicago-cs/chiventure/wiki/NPC-~-Action-Documentation)

**Comment by sglenn-uchi** [comment]
We finished the npc_action and npc_dialogue design doc (wiki page), npc_action documentation (wiki page), and a wishlist. We decided to finish integration of npc_action in future sprint first, then integrate npc_action with npc_dialogue.

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this issue!
