### ISSUE TITLE
sound: research SDL library

### ISSUE THREAD

**Issue by jiaoboxuan** [uchicago-cs/chiventure#1222]
The goal for this sprint is to research the SDL sound library that we are planning on implementing.
members: Jake, Victor

**Comment by jwschroeder21** [comment]
Notes from https://wiki.libsdl.org/Introduction

- CMake builds the library
- Supports the following:
    - Windows, Mac OS, Linus, iOS, android
- What SDL can access (does not only allow for access sound-related things!):
    - Video
        - 3D graphics
        - Creates and manages multiple windows
    - Input events
        - Mouse
        - Keyboard
        - Joystick
    - Force feedback
    - Audio (as expected)
        - Runs independently in a separate thread
    - File I/O abstraction
        - Built-in support for files and memory
    - Threads
    - Timers
    - CPU feature detection
    - Endian independence
    - Power managements

**Comment by jwschroeder21** [comment]
Victor mentioned this on our team's google doc, but I wanted to float the idea on the GitHub as well -- the access to SDL library is low-level, and could be of use for other teams – this library could be an easy thing for them to use if they wanted !

Also, I added this research / information to the wiki to keep up our progress there as well !

**Comment by jiaoboxuan** [comment]
Some hyperlinks first:
- [SDL website](https://libsdl.org/)
- [SDL wiki (pretty much useless)](https://wiki.libsdl.org/)
- [SDL GitHub Page](https://github.com/libsdl-org/SDL)
- If you want to clone it onto your computer: https://github.com/libsdl-org/SDL.git
- In-depth notes below are extracted from: https://wiki.libsdl.org/Introduction
In-depth notes
- Supports a lot of systems, macOS and Linux included. Not sure if we have to do different things to build on different systems.
- Uses CMake to build library (as one could expect)
- It does not only provide access to sound, it also provides access to the control of joystick, mouse, and other accessories. Access is low-level. Could very possibly be useful for other teams – we might be doing them a quick favor.

Audio support
- Set audio playback of 8-bit and 16-bit audio, mono stereo or 5.1 surround sound, with optional conversion if the format is not supported by the hardware
- Audio runs independently in a separate thread, filled via a user callback mechanism
- Designed for custom software audio mixers, but SDL_mixer provides a complete audio/music output library

File I/O Abstraction
- General purpose abstraction for opening, reading and writing data
- Built-in support for files and memory

Some stuff about the SDL_mixer, bolded above:
- Website: https://www.libsdl.org/projects/SDL_mixer/docs/SDL_mixer.html, talks about how to install and compile. Download links are also present.

**Comment by ecoble** [comment]
Issue Score: Satisfactory

Comments:
Nice work researching the SDL library! In the future try to flesh out the summary a bit more, and be sure that you have a clear closing statement that briefly summarizes the work that was done. Also please link any documentation Wiki pages that you created as a comment on this issue.
