### ISSUE TITLE
Create C and Lua Sandbox Example

### ISSUE THREAD

**Issue by tatmaca** [uchicago-cs/chiventure#1226]
Description: As an exercise in implementing Lua into existing C code, the custom-scripts team has decided to create a sandbox in which we can experiment with small Lua implementations of C functions. Through this, we aim to both gain practice with Lua (as it is new to all custom-scripts members) and experiment with ideas that can later be incorporated into Chiventure.

This task will be complete when we have at least one working example of a Lua/C implementation that can accomplish a simple in-game task. This will serve as the foundation for future, more advance, implementations.

Members: All

**Comment by RamarkoB** [comment]
One issue that We've Discovered as a team is that custom scripts are generated at initialization instead of at runtime. Both @jackjackkimkim and myself have ran into this issue. As of right now, we are hoping to find a way to dynamically generate and change custom scripts at the runtime of the function itself

**Comment by tatmaca** [comment]
This issue has been closed. We have created one new build that runs with Lua script, as well as updated the demonstration from two years ago with increased functionality. Future steps after this goal involve creating more demos with more complex scripts in the hopes of creating a strong final demonstration. This demo can be found in the gold.c file!

**Comment by ecoble** [comment]
Issue Score: Excellent

Comments:
Nice job creating this demo and documenting future goals!
