### ISSUE TITLE
Design documentation for combined and sequential skills

### ISSUE THREAD

**Issue by anchristensen** [uchicago-cs/chiventure#1230]
Think through and design header files/functions/structs to support the implementation of combined and sequential skills, two types of complex skills as described [here ](https://github.com/uchicago-cs/chiventure/wiki/Skill-Trees-~-Integrating-complex-skill-(combined,-random,-sequential,-etc.)-implementation)

**Comment by anchristensen** [comment]
@nbilaver and I added a new complex skill enum with COMBINED and SEQUENTIAL as options, and a general complex_skills_t structure was designed with three parts; a complex skill enum indicating which kind of complex skill it is, a list of skills used in that complex skill, and the number of complex skills it uses. We created a complex skills header file which includes supporting functions to allocate, initialize, free, and execute a sequential/combined skill.

**Comment by jacknugent1529** [comment]
Issue Score: S

Comments: Nice work on designing the skills! The code framework on the branch should set you up well for the implementation task. However, be sure specify a tangible goal in the issue summary (the first comment), and to add progress updates.
