### ISSUE TITLE
Create a design document for a run battle function and CLI integration

### ISSUE THREAD

**Issue by aliu65803** [uchicago-cs/chiventure#1231]
members: Emilio, Angela
task: Create a design document for a run battle function. This should include steps to implement the function and structs that need to be updated to match with code from other teams.

**Comment by emiliolevinspage** [comment]
We want to make a function to run the battle loop that allows the game developer-user of chiventure to specify their own turn structure. Our function would read through the specified turn structure (likely a linked list of enums specifying specific turn components e.g. MAKE_MOVE, USE_ITEM, CHECK_STATUS_EFFECTS, INCREMENT_STATUS_EFFECTS) and call the appropriate functions to carry out the turn.

**Comment by emiliolevinspage** [comment]
Note: we need to coordinate with the other battles subteam to implement battle flow/logic functions for checking and changing status effects.

**Comment by aliu65803** [comment]
Similarly, we want to take out the requirement that a player or battle NPC can only use an item or use a move in case the game developers would like to allow for an item (one or more) to be used and an attack (one or more) to be used in one turn.

**Comment by aliu65803** [comment]
We would like to use a universally combatant struct for NPCs and players, with the only difference being that the player will take in CLI instructions and the NPCs will rely on the ai to make their moves.

**Comment by aliu65803** [comment]
We have discussed a problem pertaining to how the battles are currently unable to provide a game developer with many choices when they are designing their game. For example, they are unable to decide whether they want a move to give different amounts of damage dealt. While this does not directly affect the way we are implementing the run battle function, we believe this problem must be resolved when a battle is created.

**Comment by aliu65803** [comment]
Emilio and I have discussed some new helper functions and structs that we will need to create in order to implement this function, including a apply_status_effects function and a run_turn function.

**Comment by aliu65803** [comment]
Emilio and I have decided we will need to work with the CLI team to implement this function.

**Comment by aliu65803** [comment]
We believe we have created a design document that will allow us to implement the run battle function. This document includes steps to implement the function, declarations for helper functions, and new and old structs. [Here](https://github.com/uchicago-cs/chiventure/wiki/Battles-~-Run-Function-Design-Document) is our design document for the run battle function.

**Comment by aliu65803** [comment]
I reopened this issue to include the design document for the integration of CLI features. This design document will detail how we will like to integrate the CLI with NPC battles. We have already created a design document with how we would like to run the battles themselves, but now we will need the CLI team to help us integrate features that will allow players to choose their own moves or items while battling an NPC.

**Comment by aliu65803** [comment]
We are closing the issue as we believe we have a design document that has battle-specific CLI commands that will allow for the user to choose their own moves and items. We have also incorporated winning/losing messages. There is also an example for easier understanding. [Here](https://github.com/uchicago-cs/chiventure/wiki/Battles-~-CLI-Integration-Design-Document) is our design document.

**Comment by lilyehsani** [comment]
Issue Score: Satisfactory

Comments:
Great work! Two comments:
1. The summary for this issue is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/issue-pr-grading.html#descriptive-summary for examples). If this issue was generated from a Scrum board card, please remember that the summary you write in the Sprint meeting is meant to be a quick draft; it needs to be fleshed out when you convert the card to an issue. One thing you could have talked about in the summary is the plan to take inspiration from NPC dialogue mode, like we discussed at the sprint meeting. The first 4 comments on this issue could all be part of the summary.
2. The issue was closed before it was done, and then reopened. Remember to only close an issue when the task is complete.
