### ISSUE TITLE
Create a Design Document for Implementation of More Additional Specialized Stats

### ISSUE THREAD

**Issue by nicholaswlee** [uchicago-cs/chiventure#1233]
We will evaluate the current implementation of stats, consider how we could update it, and what effects a possible update would have. The product will be a design document on the subject.

Members: Fatimah, Nafis, Nicholas

**Comment by corian-jal** [comment]
We, along with the other two members of our group, agree that while the D&D stat system (strength, dexterity, etc) offers a lot of flexibility in roleplay in a table-top setting, it lacks the clarity and structure needed for coded battles. The standard RPG implementation of Health, Physical Attack, Magical Attack, Physical Defense, Magical Defense, Speed, and Special Points (a resource magic and skills are limited by; a damage-source-agnostic mana) might work better and we will next check how this change would be implemented.

**Comment by corian-jal** [comment]
We have decided to look into including Luck/Critical Hit Chance and Accuracy stats to the player for additional options in combat.

**Comment by corian-jal** [comment]
We created a Stat Changes Design Document in the wiki [here](https://github.com/uchicago-cs/chiventure/wiki/Battles-~-Stat-Changes-Design-Document).

**Comment by corian-jal** [comment]
An initial draft of the document is complete and will be reviewed by other teammates later.

**Comment by nicholaswlee** [comment]
We have closed and completed this document. Our document lays out the changes we would like to make to stat_t, including critical damage, accuracy, skill points, and splitting up physical and special stats. We have also provided where in the code we would have to alter to accommodate for these changes. We hope to implement this design in the coming sprint.

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work! This issue was closed before it was done and then reopened. Remember to only close an issue when the task is complete.
