### ISSUE TITLE
action-management team plan document

### ISSUE THREAD

**Issue by HarrisonD123** [uchicago-cs/chiventure#1235]
action-management: create doc outlining plan for sprints 3 and 4 and direction of action-management team

members: Harrison

**Comment by HarrisonD123** [comment]
The main questions with the action-management team is whether we should focus our time more on the action-management module or more on the custom-actions module. After looking over the amount of documentation and the number of available issues in both modules, we as a team decided on the action management route.

**Comment by HarrisonD123** [comment]
**Closing Statement:**

After scanning through the open issues for action management, we decided that the main issues we will focus on in sprints 3 and 4 will be the following:

- **Sprint 3:** Working on major existing issues implementing actions such as abstracting action functions to involve and handle NPCs and implementing teleportation, location checking, and inventory checking. We recognize that many of these issues will require heavy collaboration with other teams.
- **Sprint 4** Wrapping up any unfinished work within the issues from Sprint 3. We will then brainstorm other actions we think should be implemented within Chiventure. The rest of Sprint 4 will be dedicated to implementing these new issues and creating new documentation for them for future action management teams to refer to.

All of this is detailed in this Wiki page: https://github.com/uchicago-cs/chiventure/wiki/2022-Action-Management-Team-Sprint-3,-4-Plan

**Comment by ecoble** [comment]
Issue Score: Satisfactory

Comments:
Nice work documenting this issue and creating a plan! Please remember to include milestones on issues for what sprint they belong to. Additionally, when you convert a card to an issue be sure to flesh out the summary a bit more than the brief description that is auto generated from the card.
