### ISSUE TITLE
Cli: parsing specification document

### ISSUE THREAD

**Issue by katyashchukina** [uchicago-cs/chiventure#1239]
Write up a parsing specification document (wiki page) with specific requirements for the enhanced cli:
-synonyms of existing chiventure commands 
-prepositions
-miss spells and different forms of words  (e.g. plurals)
-etc

**Comment by katyashchukina** [comment]
I have created the wiki page:
https://github.com/uchicago-cs/chiventure/wiki/Enhanced-CLI-~-Parsing-Specification-Doc

And added some basic specifications. I am a little limited in how accurate I can be as we have not yet decided on a parsing library (the goals we have so far should be doable regardless but I am unable to go into specifics about functions and structures)

**Comment by fkbad** [comment]
We have finished adding the information on the page. 
Specifically have included many working examples with both current output and desired output to act as tests for implementation.

Faruk and Kate both worked together, Kate publishing the wiki page and both of us adding examples and general specifications.
https://github.com/uchicago-cs/chiventure/wiki/Enhanced-CLI-~-Parsing-Specification-Doc

**Comment by majorsylvie** [comment]
We have finished adding the information on the page. 
Specifically have included many working examples with both current output and desired output to act as tests for implementation.

Faruk and Kate both worked together, Kate publishing the wiki page and both of us adding examples and general specifications.
https://github.com/uchicago-cs/chiventure/wiki/Enhanced-CLI-~-Parsing-Specification-Doc

**Comment by jacknugent1529** [comment]
Issue Score: E

Comments: Nice work! The updates explain well your progress and limitations. Remember to convert cards to issues shortly after the meeting
