### ISSUE TITLE
Fix bug with having repeated rooms in an npc's movement path

### ISSUE THREAD

**Issue by bvvill** [uchicago-cs/chiventure#1240]
members: William

**Comment by bvvill** [comment]
Right now it seems like there would be many issues that would arise if there were to be an NPC that has a movement path that makes it so they go to the same room multiple (/more than once) times in their lifespan. Because searching through an NPC's movement path compares only the room_id for each step in the path, like in move_npc_definite and move_npc_indefinite within npc_move.c, if a room were to appear multiple times in an npc's movement path, the LL_SEARCH macro within these functions would only ever set the current_room pointer to the first iteration of the room in the path.

**Comment by bvvill** [comment]
To solve this, I think there needs to be another way of identifying rooms within a particular path.
Maybe creating a struct with

- traditional room_id
- index position of this room compared to all of the other iterations of this same room within the same path

could work? I see now that this would (possibly) require having to update this struct for every iteration of a certain room in a path if the same room were to be added again or deleted, which could get messy

**Comment by bvvill** [comment]
> 

I'm fairly sure the consequence of this bug is that if a room appears more than once in an npc's path, that npc will forever be stuck in the segment of path in between the first two iterations of the room in question

**Comment by bvvill** [comment]
> Right now it seems like there would be many issues that would arise if there were to be an NPC that has a movement path that makes it so they go to the same room multiple (/more than once) times in their lifespan. Because searching through an NPC's movement path compares only the room_id for each step in the path, like in move_npc_definite and move_npc_indefinite within npc_move.c, if a room were to appear multiple times in an npc's movement path, the LL_SEARCH macro within these functions would only ever set the current_room pointer to the first iteration of the room in the path.

I'm fairly sure the consequence of this bug is that if a room appears more than once in an npc's path, that npc will forever be stuck in the segment of path in between the first two iterations of the room in question

**Comment by bvvill** [comment]
Now I think the best way to go about this is to just add a member to the npc_mov_t struct that gives the index of the position in the movement path that the npc is currently in, and then just not use the LL_SEARCH macro, which uses the room_id

**Comment by bvvill** [comment]
When executing a (single/step) move down a path, this (unsigned int) index would just increment by +1.
So far I have encountered two hypothetical problems:
Moving multiple steps / skipping steps in a movement path. I could see something like this happening as a conditional of a quest outcome, which affects the NPC's location.
Going backward in the path. I don't think this should be a problem for definite-path NPCs, as I would think any repeat rooms in the path would be defined to be later in the path if necessary (as opposed to going backwards), but for indefinite-path NPCs it is possible to reverse the path once the end has been reached. The problem is that there is currently no way to tell if a path has been reversed, and the path_pos index could be set to decrement if we did know. Hopefully adding a "dirty" bit/byte to tell whether or not the path has been reversed should solve this particular problem.

**Comment by bvvill** [comment]
> Going backward in the path. I don't think this should be a problem for definite-path NPCs, as I would think any repeat rooms in the path would be defined to be later in the path if necessary (as opposed to going backwards), but for indefinite-path NPCs it is possible to reverse the path once the end has been reached. The problem is that there is currently no way to tell if a path has been reversed, and the path_pos index could be set to decrement if we did know. Hopefully adding a "dirty" bit/byte to tell whether or not the path has been reversed should solve this particular problem.

okay my memory served me incorrectly and definite-path NPCs can have their path reversed (and the reverse_path() function is only for NPCs with a definite path, I have yet to see the code for the path-reversal of indefinite-path NPCs), so instead of having the "dirty" reversal byte in the npc_mov_indefinite_t struct as I had planned, it will just be in the npc_mov_t struct along with the npc_path_pos index that I added earlier

**Comment by bvvill** [comment]
>Moving multiple steps / skipping steps in a movement path. I could see something like this happening as a conditional of a quest outcome, which affects the NPC's location.

For this, I suggest that we implement a separate room_tree struct (instead of the 1D linked list of rooms) for NPC movement paths to better reflect/organize the tree structure of paths that NPCs (in many games) have. In my mind the node of the room_tree struct would just be a pointer to a room itself, and then the branches would be an array of pointers to room_tree structs.

**Comment by bvvill** [comment]
> For this, I suggest that we implement a separate room_tree struct (instead of the 1D linked list of rooms) for NPC movement paths to better reflect/organize the tree structure of paths that NPCs (in many games) have. In my mind the node of the room_tree struct would just be a pointer to a room itself, and then the branches would be an array of pointers to room_tree structs.

OR just keep the linked list structure, making it such that it only contains unique rooms, and but then add an extra parameter with the char* room_id to the functions that move NPCs. Either way, that will have to be its own issue, for now I'm just going to assume that repeated rooms in the path is okay and skipping steps is not a thing

**Comment by bvvill** [comment]
summary of changes:

- addition of `unsigned int npc_path_pos` into the `npc_mov_t` struct, which keeps track of the current location of the NPC within its movement path
    - a function to get this value, `track_npc_path_pos`, has also been implemented
- addition of `uint8_t npc_path_reversed` into the `npc_mov_t` struct, which is 0 if the movement path is in the original order/direction, or 1 if the path is in the reverse/opposite order/direction
    - a function to get this value, `track_npc_path_reversed`, has also been implemented
    - for NPCs with definite paths, the `reverse_path` function was edited to flip this member between 0 and 1 whenever called.
- `npc_mov_init` was edited to assign the initial values of the newly added members to be 0
- To fix the bug described earlier, functions using the `char *room_id` to search through the movement path (which is in a linked list), such as `mov_npc_definite` and `mov_npc_indefinite`, were edited to go through the linked list using the values of the `npc_path_pos` and `npc_path_reversed` members, and to (in/de)crement an NPC's `npc_path_pos` accordingly.
- `get_npc_num_rooms` now uses the efficient `LL_COUNT` macro instead of using `LL_FOREACH` and explicitly defining the counting

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work! The summary for this issue is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/issue-pr-grading.html#descriptive-summary for examples). If this issue was generated from a Scrum board card, please remember that the summary you write in the Sprint meeting is meant to be a quick draft; it needs to be fleshed out when you convert the card to an issue. It is possible that you intended the comment that starts with "Right now it seems like..." to be the summary, and it is a good summary, but it must be part of the very first comment (which currently just says "members: William". Remember that the first comment can be edited.
