### ISSUE TITLE
Battles ~ Create a design document for a CLI mode when running battles (Closed to avoid splitting)

### ISSUE THREAD

**Issue by emiliolevinspage** [uchicago-cs/chiventure#1241]
members: Emilio, Angela
task: Create a design document for a CLI mode (similar to NPC conversation mode). This should include steps to implement the function, structs that need to be updated to match with code from other teams, and possible questions to ask the CLI team to work on to implement this feature.

**Comment by aliu65803** [comment]
Emilio and I have discussed and created a design document for the run battles function and realized we will need help from the CLI team to implement it. For example, we need their help to allow a player to choose their move or the item that they will use. This design document will take note of what we need their help with and how we will integrate their code into ours.

**Comment by aliu65803** [comment]
We are closing this issue to avoid splitting our task, the design document for CLI Integration can be found on the wiki page.
