### ISSUE TITLE
Create A Design Document For Complete Integration with Skilltrees

### ISSUE THREAD

**Issue by Vincent-Zhang4135** [uchicago-cs/chiventure#1242]
Our task is to create a design document for complete integration with skill-trees. Using this design, we hope to be able to. implement some integration between player classes and the unique skill trees each player class offers in the upcoming sprints.

**Comment by Vincent-Zhang4135** [comment]
Van and I met to discuss how we can create a design document for integrating skill-trees with player class, but we have been struck with a roadblock that likely requires discussing with the skill-trees team for more clarity and direction:

We considered that the player class in general, seems to be a rather static object, and as a result, besides implementing more player classes, there may not be much we can do on our end in terms of integrating with the deeper implementations of skill trees. Additionally, we also found trouble in identifying the relationship between player classes and skill trees that already exist, and how the two are actually linked.

However, we came to an example suggestion that we think can be integrated between player classes and skill trees:

In the skill-example.c file, we see that the implementation of effects is not fully fledged out: in particular,  ```effect_diss_track```,```effect_fireball```, ```effect_sword_slash``` , are just example effects that return characters but we do not really see where these lie in actually implementation, and think it would be create to see how player classes that hold different effects will be interacting with these effects. We also thought about how we could create a general function for this instead. 

In general, we aren't sure of what we can do on our side, and thus came to the conclusion that in order to do any integration. we should first reach out to Skill-trees for suggestions

**Comment by vanolson** [comment]
Here is the design document: https://docs.google.com/document/d/1X7ciI1g-MyMHN0JXYYRJhqVyrCj253uQD6DQIJ9HQvU/edit

**Comment by vanolson** [comment]
We completed the design document, though we weren't able to make a complete integration design due to the changes that would be needed on the skill trees team (which we're less familiar with). If we want to implement some of these changes we may need to discuss a bit with them, especially the potential proposed changes on their module. Vincent and I worked on all parts of this together.

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work! While using Google Docs to sketch out some of the documentation, you should avoid posting links to those Google Docs from an issue, as it may cause confusion as to whether that document (or some future update to the wiki) is the most up-to-date version of that documentation. You should instead transfer the contents of the document to the wiki, and then link to the wiki when updating the issue.
