### ISSUE TITLE
room_autogenerate function brainstorming

### ISSUE THREAD

**Issue by williamhu314** [uchicago-cs/chiventure#1245]
In this issue, we aim to brainstorm ideas for autogenerating rooms without necessitating a list of room_specs from the user. The goal is for the function to only need an input of a starting room from which we will branch out of to create the new room. The new room generated should be somewhat similar to nearby rooms.

Additional optional inputs may include:

1. An optional input containing a list of allowable items in case the user wants to restrict the types of items in the generated set of rooms, 
2. An optional input for direction in case the user wants to input a specific direction.
3. An optional input for a list of conditions in case the user want a specific list of conditions

The default for the optional inputs can be random generation that takes into account the specification of nearby rooms.

**Comment by williamhu314** [comment]
To make the items in a room similar to those nearby, I think one method is to change the probability of certain items appearing based on the items present in nearby rooms. How greatly an item in a room affects the probability of that item or a similar item appearing in a nearby room can be specified by the user with some kind of a coefficient. Similarity of items can be quantified using either something similar to item_spec or some kind of an adjacency matrix. We can also allow the author to make item groups where items in the same group are considered similar.

To implement this, we would need to work with the game-state team to add to the room struct lists containing items in nearby rooms.

For example, we can have a list called items_nearby1 containing a list of all items in adjacent rooms. We can have additional lists called items_nearby2 and items_nearby3 containing a list of items that require taking 2 or 3 paths to get to. However, for now, 

We can update the items_nearby1 lists for the rooms every time room_new or path_new is called. When room_new is called, the items in the new room can be added to the list of items in the starting room. The new room's list will consist of the items present in the starting room.

When path_new is called, for the 2 rooms we are connecting, we can add the list of items in the rooms to each other's items_nearby1 lists.

I am not yet sure how we would update the items_nearby2 lists as this is less clear. Maybe using the paths associated to the room to figure out what rooms a room is adjacent to is one idea. We could then copy over the items_nearby1 lists of adjacent rooms is a good idea but I'm not so sure how to implement that.

**Comment by lukasg8** [comment]
After conversation with William, we decided that room_spec is actually necessary because the purpose of room_specs is to provide human-written short and long descriptions of rooms. In other words, at our level, it would not be possible to autogenerate such descriptions. The other variables in room_specs are items, for which there are already autogenerate functions.

**Comment by williamhu314** [comment]
After further conversation with Lukas and Jesse, we have decided that one method for autogeneration is to allow the game author to input some roomspecs and for the room generation algorithm to generate rooms from the provided list of room specs, putting rooms similar rooms near each other. The similarity of rooms can be based on the title of the room, and the author can somehow specify which room types are similar to which. To make sure similar rooms are near each other, we can make sure that when a new room is created, it is more probable that it will be of that same or a similar room type to rooms nearby. The game author may also need to specify the number of rooms they want in the game.

**Comment by williamhu314** [comment]
We have finished brainstorming and have settled on the idea mentioned in the previous comment. Thus, we are closing this issue and will now be working on designing the function in issue #1266.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Excellent work with a great set of updates throughout.
