### ISSUE TITLE
Document overlap between custom actions and custom scripts

### ISSUE THREAD

**Issue by jackjackkimkim** [uchicago-cs/chiventure#1246]
Description: The review of custom actions code was deemed necessary as there may be code from custom actions that we may want to bring into custom scripts. 
There are functions for creating custom actions that will be necessary when we make our LUA/C demo. The current idea for demonstration will require that the custom action of "opening a previously locked door" be available only when the user is holding a certain object (have not decided upon a concrete object as of yet).
It is unclear as of yet if the conditional codes can also be recycled to check for the condition of the user holding a certain item

**Comment by jackjackkimkim** [comment]
While the previous custom actions team may have also explored the option to perform an action given a conditional, the code proved to be disorganized and we arrived at the conclusion that we want to write our own code instead of recycling code from custom actions team.

**Comment by ecoble** [comment]
Issue Score: Excellent

Comments:
Nice job on this, especially with the thorough description! If you created documentation like a Wiki page, please link it as a comment on the issue.
