### ISSUE TITLE
Implement item_stat_effect_t

### ISSUE THREAD

**Issue by arya32hub** [uchicago-cs/chiventure#1247]
item_stat_effect_t was left to do for 2022.

**Comment by arya32hub** [comment]
typedef struct item_stat_effect {
    //TODO (2022)
} item_stat_effect_t;

**Comment by chelseaegbarin** [comment]
Description: item_stat_effect_t refers to the type of effect that modifies the statistics of an item (as opposed to the stats of a player) and the functions that go along with it (including make_item_stat_effect and executie item_stat_effect) remain unfinished. So we want to do those.

**Comment by chelseaegbarin** [comment]
I made the item_stat_effect_t type very similar to how the player_stat_effect was made, with a name (char*), an array of stats (stats_t**), a number of modifications (double*), an array representing the duration of the effect (int*) and a number fr the statistic to be modified (int). The thing is though I'm not sure why the player stat effect type was made like this, with these values. So might change it? I have to read more probably.

**Comment by chelseaegbarin** [comment]
Ok so I just wrote the make_item_stat_effect function. I didn't do the effect_type for the stat effect it creates yet (I started it but commented it out) but I handled the error situations and I assigned the data type. Exciting

**Comment by arya32hub** [comment]
I implemented a define_item_stat_effect,

**Comment by arya32hub** [comment]
I implemented a make_item_stat_effect

**Comment by arya32hub** [comment]
execute_item_stat_effect

**Comment by arya32hub** [comment]
I implemented an execute_item_stat_effect

**Comment by arya32hub** [comment]
Need to send for review

**Comment by chelseaegbarin** [comment]
Implementation written, but one test does not pass when a statistics field for item stat effects was added. Future print could to be debug tests.

**Comment by jacknugent1529** [comment]
Issue Score: Ungradable

Comments: This issue was continued in 1391, so that issue will be graded instead.
