### ISSUE TITLE
gui: Look into ways in which the graphical interface interacts with the WDL file

### ISSUE THREAD

**Issue by imadejski** [uchicago-cs/chiventure#1250]
Hi, I'm on the DSL team and we're planning ahead and trying to figure out what features we should implement. As of right now, our tool can take plain text descriptions and convert it to a WDL file (but only for rooms, games, and items). We are looking to see if we could add graphical support to this tool as well, so I was wondering if there's any way in which the graphical interface interacts with the WDL file?
-From Andi Liu on the DSL team

**Comment by imadejski** [comment]
Update: It seems as though the graphical interface interacts only with the context struct and not at all the WDL file. This means that there isn't any additional information currently that would make a lot of sense to incorporate into the plain text description to WDL file conversion. If this changes or there are more possible ways to incorporate graphical support this page will be updated. 

We are currently working on ways to create structures for the WDL that can hold information about graphical specifications, so this is something that is still in progress, but could be incorporated into the plain text descriptions once it is completed.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great work! In the future, I would advise issuing some sort of closing statement (even if it is just temporary). You should include a final comment summarizing what was done, and why the issue is being closed.
