### ISSUE TITLE
dsl: implement playerclasses based on design doc

### ISSUE THREAD

**Issue by wzeng0** [uchicago-cs/chiventure#1252]
We finished outlining what the player classes will look like in dsl so now it is time to implement it into the code base. Here is the outline for reference: https://docs.google.com/document/d/1wLXOiy6Tc8Bkr2w9BNqHDsU-cYn7rT04TsqsHLrub2A/edit

**Comment by baigh1** [comment]
Created a document outlining the conversion from WDL to DSL for player classes. [https://docs.google.com/document/d/1wLXOiy6Tc8Bkr2w9BNqHDsU-cYn7rT04TsqsHLrub2A/edit?usp=sharing](url)

**Comment by baigh1** [comment]
Updated the grammar documentation for player classes. Hoping for some feedback on the correctness of the changes.

**Comment by wzeng0** [comment]
Updated ```dsl_parser.py``` to be able to take in player_class and places all its values in a dictionary. Right now, we are supporting only short description, long description, attributes, and base_stats.

**Comment by jhsivadas** [comment]
Updated ```to_wdl.py``` to include functionality for player class. Updated the Player Class for actual specifications for the DSL input. Also updated  ```parse_dict_to_json``` to include creation and loading to the wdl file given a proper input. Ran tests (manual dictionary input for player) to test if wdl conversion works. All tests ran successfully for one class and multiples classes.

**Comment by baigh1** [comment]
Modified ```dsl_grammar.lark``` and created a new file in examples ```play-class-2.dsl```. Keep running into issues in the grammar implementation.

**Comment by baigh1** [comment]
Changed base_stats in dsl parser to reflect similar style. ("base stats" instead of "base_stats"). Additionally, the DSL grammar for player class was split off into a second issue.

**Comment by wzeng0** [comment]
Got all the grammar working. Some features such as boolean was changed back to being just a phrase for simplicity. The parsing still does not work and I am unsure how to get data from dsl file to put into wdl.

**Comment by jhsivadas** [comment]
Edited the transformers so that the input would be outputted properly as a dictionary of dictionaries for the intermediate output. Mostly spent time changing attributes to be parsed properly. Ready to be processed in dict_to_json

**Comment by jhsivadas** [comment]
Finished the implementation of the player class parsing in dict_to_json. Changed some of the player_class structure in order to process the actual input more efficiently and properly. Example DSL and WDL file output are included inside the repository. Should be ready for a pull request

**Comment by jacknugent1529** [comment]
Issue Score: Satisfactory

Comments: Nice work on this issue! I know parsing can be tricky, but it looks like you were able to work through it well, and the updates documented your progress. Be careful not to to use google docs because they may not be available in the future for others to reference as documentation. Also, this issue was started in sprint 3, but not completed until sprint 4.
