### ISSUE TITLE
dsl: design dsl specifications for npc (both grammar and conversion to wdl)

### ISSUE THREAD

**Issue by wzeng0** [uchicago-cs/chiventure#1253]
The NPC team has put together a sample WDL specification for NPCs. In order to implement NPCs in DSL, we will need to design the grammar for NPCs and also how to use lark to parse the conversion.

team members: andi, alex, jay

**Comment by awliu2** [comment]
Link to design document is here: https://docs.google.com/document/d/1aq3eS4vwEB0Agioyb8GoEEdNdueOPAV1j1sxQsdfVTQ/edit?usp=sharing

**Comment by awliu2** [comment]
We have mostly designed out the DSL specification for an NPC. We are currently working on figuring out how to parse this DSL using Lark. The main challenge seems to be parsing the dialogue, which is represented as graphs and nodes. Furthermore, we are worried that the NPC team is continually making developments on their WDL specification and may change the format in which they represent an NPC in wdl format (as we are currently working with an older example from last year).

**Comment by awliu2** [comment]
A couple small changes have been made to the design as we work on implementation. I think the design has been solidified and this issue can be closed.

The grammar for NPCs is found below.

```
NPC OAK IN Pallet Town
    Short desc: “Kanto’s premier Pokemon expert”
    Long desc: “Enjoys exploring human-Pokemon relationships”
    Age: “25”
    Gender: “Male”
    ITEM CHARMANDER
    ITEM SQUIRTLE
ITEM BULBASAUR
ITEM POKEBALL
```

**Comment by jacknugent1529** [comment]
Issue Score: Excellent

Comments: Nice work on this issue. Avoid using google docs, since they may not exist in the future, and in this way aren't great for documentation purposes.
