### ISSUE TITLE
Strengthen quest tests to better test quest_ids

### ISSUE THREAD

**Issue by elizabethli31** [uchicago-cs/chiventure#1258]
Currently, the quest_ids are the same in all the tests. We should change the quest_ids so they are different and we can check if the testing actually works

**Comment by jakeziqiwei** [comment]
We have edited the quest ID in the test functions to not all just have "test" as an identifier in order to cover our basis. and increase coverage. The changes did not affect the result of the test and is pushed/merged along with the Quest_hash test issue/pull request. Ready to be closed!

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great work, a minor issue, but great nonetheless!
