### ISSUE TITLE
Write tests for all quest hash table functions

### ISSUE THREAD

**Issue by elizabethli31** [uchicago-cs/chiventure#1259]
Currently, none of the hash table functions have tests written for them. We need to write tests for get_quest_from_hash, and add_quest_to_hash

**Comment by elizabethli31** [comment]
We had to fix the implementation from last year for two of the hash table functions and wrote multiple tests which all passed. Everything works and is now ready to be closed.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great job on this issue! Clear and concise.
