### ISSUE TITLE
Update Action Management Specifications

### ISSUE THREAD

**Issue by SnowballAntrobus** [uchicago-cs/chiventure#126]
Using the feedback provided by Game State in issue [#77](https://github.com/uchicago-cs/chiventure/pull/77#pullrequestreview-238209734). And including the refactoring of the action management module to remove NPC actions and synonyms.

**Comment by lucyyutingli** [comment]
I just updated the file by removing synonyms and actions relating to NPC’s. There are details to which synonyms I removed and what kinds of actions I removed in the description of the commit. 

This was all done in commit 7242f393f8f72a96f8179b248a3a18922b2e441e

**Comment by mpcsh** [comment]
Issue Score: ✓

Comments:
The title is pretty vague here. Could've used a little more detail in the update(s) too. Other than that, good work.
