### ISSUE TITLE
Implement the new quest/task prerequisite system

### ISSUE THREAD

**Issue by JSerf02** [uchicago-cs/chiventure#1260]
Implement the new quest redesign as outlined in this [Wiki](https://github.com/uchicago-cs/chiventure/wiki/Quests-~-Prerequisite-System-Redesign). Everything from this design document should be implemented except for the quest search functions, which should be implemented along with the integration of quests into the player module.

**Comment by JSerf02** [comment]
Added the new structs from the Wiki to quest_structs.h

**Comment by JSerf02** [comment]
We added the headers for all of the new, init, and free functions for the new data structures along with comments

**Comment by JSerf02** [comment]
We added and implemented all of the functions from the design (though we didn't implement the `find_task` and `find_quest` functions yet since those rely on the player module change). 

We still need to fix all of the tests. Many of these changes invalidated the tests and many of the tests appear to already have contained many errors. For example, the test for the stat_req system that is now the prereq system was checking for xp when the original stat_req class only contained hp and levels. I have no idea how this went unnoticed.

**Comment by JSerf02** [comment]
Fixed most of the tests. There was one test for the `can_start_quest()` function which was replaced with the `meets_prereqs()` function which we cannot test since it relies on the player class. Once that is complete, we can create a pull request and close this issue!

**Comment by JSerf02** [comment]
Also as a side note, we definitely need to test these features more, but that can be added throughout the process of rewriting all of these tests, since there are a number of glaring issues with the current tests, including that they barely test the features of the quest module and that there are some testing functions that serve the purpose of regular functions (for example, there was a `create_sample_stat_req()` function that did everything `stat_req_new()` did. Obviously, we removed this when switching stat_reqs to prereqs and replaced it with `prereq_new()`).

**Comment by JSerf02** [comment]
We finished implementing the redesign and submitted a pull request for it. All features from the Wiki are implemented and partially tested, though when we improve tests overall, it wouldn't hurt to add even more tests.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great job! Excellent updates -- an exemplary issue.
