### ISSUE TITLE
GUI: Update Raylib in Chiventure

### ISSUE THREAD

**Issue by dhirpalshah** [uchicago-cs/chiventure#1264]
The reason we haven't been able to get Raylib working is because we have been using an older version of it, and the wiki instructions have not been updated. This is a priority - without raylib, we won't be able to use any of the implementations for our designs. 

See previous issue here:
https://github.com/uchicago-cs/chiventure/issues/1198

**Comment by cyruszzhou** [comment]
We decided to discard the original version as it is hardcoded. However, the original codes would still help us as reference. The issue is thus closed.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great work (although relatively brief)! Just make sure to add a milestone to the issue next time.
