### ISSUE TITLE
room_autogenerate function design

### ISSUE THREAD

**Issue by williamhu314** [uchicago-cs/chiventure#1266]
In this issue, we aim to complete the design for a new room_autogenerate function. 

Our goal is for the function to be able to generate a new room, with this new room having a greater probability of being similar to rooms next to it.

Similarity will be quantified by the roomspecs that the author provides and, for each room type, a list of similar room types, also provided by the author.

This will eventually be used as a helper function to autogenerate an entire game based on a list of room specs/types and a list, for each room type, of similar rooms.

Subtasks include:

1. Updating the roomspec struct (potentially adding a room type field and a field for a list of similar room types)
2. Determining the specific inputs for our function
3. Completing a full description of the function

**Comment by williamhu314** [comment]
Based on the current roomgenerate function, I have decided that room autogenerate should take the following inputs:

1. A game_t struct
2. A room _t struct
3. A char* indicating the direction from the new room to the current room
4. A char* indicating the direction from the current room to the new room

I have also decided to put all autogeneration work into a separate module from the current generation functions since these functions will be much more autonomous than the current ones. 

I will now work on completing a full description of the function in the new module.

**Comment by williamhu314** [comment]
I have finished writing the description for the function and the function declaration in the header and c files for this new function and will be submitting a pull request.

**Comment by williamhu314** [comment]
We have decided to use an adjacency matrix within the speclist struct to quantify simialrity instead of adding a list of similar rooms into room_spec. So I remove the changes to room_spec and have decided that roomautogenerate will also take gencontext as an input, which contains the speclist. The function will now take the following inputs:

1. A game_t struct
2. a gencontext struct
3. A room _t struct
4. A char* indicating the direction from the new room to the current room
5. A char* indicating the direction from the current room to the new room

**Comment by williamhu314** [comment]
I will also keep room_autogenerate in the autogenerate module now. The autogenerate module is definitely too big but I think there is a better way to refactor-maybe one module for general autogeneration, one for multiroom autogeneration, and one for level oriented generation for example. We will figure out the best refactoring method later, but I don't think room_autogenerate and roomgenerate belong in different modules.

**Comment by williamhu314** [comment]
I am going to close this issue and start working on implementation in #1321. Instead of doing a pull request now, I will do it after the function is completed in case any further edits to the design are needed.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great work! A very thorough set of updates and a clear goal to start with.
