### ISSUE TITLE
gui: identify issues with the current code, go through the raylib library, and plan for future modifications

### ISSUE THREAD

**Issue by cyruszzhou** [uchicago-cs/chiventure#1267]
As I tried to come up with modular designs for NPC graphics, I went through the existing code and found that most codes are hardcoded and would not be flexible enough for us to come up with new features. I thus summarized the modifications needed to make new changes possible. I also proposed other ways to make the game engine both more game-developer-friendly and gamer-friendly.

**Comment by cyruszzhou** [comment]
I primarily went through the existing code and the raylib library and planned for future development and modifications.
Here are my primary plans:

1. Better integrate graphics into the game engine as a tool for game developers

a)     Coming up with WDL data structures to store the developer’s graphical specifications
b)     Parsing WDL inputs to know the specifications from the developer side (e.g., Customizable display window positions and sizes)

2. Making graphics resources more accessible for the Chiventure community

a)     Creating a graphics database (with PostgresSQL) that is easy for developers to use (e.g., NPC graphics, scenes, objects, inventories…)
b)     Making an executable for connecting to the database and uploading graphics resources

3. Making NPCs displayable

a)     This one is relatively easy, we can do the same as we do for scenes and inventories

4.   Enhancing current inter-modular and intra-modular design

a)     The current design is somewhat unstructured, need better architecture

**Comment by cyruszzhou** [comment]
After identifying the issues and planning out the modifications, I am now beginning to rewrite modules to adapt to our new features and to better integrate the graphics into the game engine.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great work, just remember that Scrum board cards should be converted to issues shortly after the Sprint meeting. Think of the Scrum board card as a rough outline of the issue, which you then need to flesh out with a more descriptive title and summary when converting it to an issue.
