### ISSUE TITLE
gui: Write UI module for pulling all modules together

### ISSUE THREAD

**Issue by cyruszzhou** [uchicago-cs/chiventure#1269]
The current ui and gui modules are composed of very long and hard-to-follow functions. They are hard-coded and not suitable for integration intot the main game engine and incorporating new features.

**Comment by csraffaga** [comment]
The ui.main module has been designed to read from the GDL file into large graphics struct from which individual pop-up/subscreens can pull information. This choice allows for all GDL specific information to be accessible in one place, just as the game state struct serves the WDL file.

**Comment by cyruszzhou** [comment]
As the multi window version of raylib has failed to be pull requested, this module is no longer possible to be implemented. We wish future developers can figure out a way in which the multiwindow function can be realized without pulling the whole library (though tweaked) into the dev branch. We now close this issue.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great job on this issue, but note that next time try to make the issue summary more comprehensive by clearly explaining the issue.
