### ISSUE TITLE
cli: get Bison actually running @CSIL on the Sandbox branch 

### ISSUE THREAD

**Issue by majorsylvie** [uchicago-cs/chiventure#1270]
have bison take in a command strings and output the parsed list of tokens according to the current implementation of the action functions in operations.c

team members: Kate, Faruk, Miles

**Comment by majorsylvie** [comment]
- Created the `cli/sandbox` branch, to be used when doing sandboxing implementations
  - You should be able to access with `git checkout cli/sandbox`
- Created a `sandbox` folder inside `chiventure/src/cli/src` (where all other c files are located).
- Created a small `README.txt` within the sandbox folder to document the purpose of the folder

**Comment by katyashchukina** [comment]
Currently bison isn't working on CSIL machines (which is obviously an issue for chiventure), we are trying to work out (asking Borja) how to fix this

EDIT: resolved this issue!

**Comment by katyashchukina** [comment]
We have created the parser-bison.l and .y files along with the files created by yacc at compilation. Currently it is able to take in letters, numbers and symbols (but doesn't do anything with them). The next step would be to implement the token structure from the current cli structure, however we are having issues with it sometimes working and sometimes not for as of yet unknown reasons which is slowing down progress significantly.

**Comment by katyashchukina** [comment]
Bison now runs on CSIL machines! We have created a very basic bison example file and it runs with no issues, therefore we are closing the issue.

**Comment by jacknugent1529** [comment]
Issue Score: Excellent

Comments: Nice work on this issue! Even though it took part of 2 sprints, it's good to resolve these difficulties so they hopefully won't be a problem in the future.
