### ISSUE TITLE
cli: implement "view stats"

### ISSUE THREAD

**Issue by majorsylvie** [uchicago-cs/chiventure#1271]
Implement the "view stats" function in current cli code. Involves updating header file and c file. 
Will be added to operations.c
Specifications from the actions management & UI teams

team members: Faruk, Miles, Matteo

**Comment by majorsylvie** [comment]
Link to corresponding Action Management Card: 
https://github.com/uchicago-cs/chiventure/projects/1#card-81402489

**Comment by majorsylvie** [comment]
Created branch for implementation `1271-cli-implement-view-stats`
Access with:
```
git fetch origin
git checkout 1271-cli-implement-view-stats
```

**Comment by majorsylvie** [comment]
Added and pushed the `view_operation` function to `operations.c` on the previously mentioned `1271-cli-implement-view-status` branch. 
As of now, it is merely a shell which has basic error cases, whose format was taken from other functions.
Supports matching to a second token of "stats" and nothing else yet. Will need further specification from action/ui on what they actually want.

**Comment by milesgardner** [comment]
In addition to a "view stats" function, the GUI team also will require a "close stats" function or something similar.  Additionally, GUI needs support for an "advanced stats" function.  While GUI still finishes these functions, shells for them will be written by our team.

**Comment by milesgardner** [comment]
Added and pushed edits to `view_operation` function in the `1271-cli-implement-view-status` branch.  Added support for "view advanced" commands.

When we have access to the function, we would also want to support commands like "view advanced stats"

**Comment by majorsylvie** [comment]
Adjusted the help command to include a note about the view status function. Pushed to the `1271` branch. 

Currently trying to track down where our functions are called so I can add the view_operation as an option.

**Comment by majorsylvie** [comment]
Added `VIEW` to the list of command at the top of operations.c
Also updated the `NUM_ACTIONS` constant

**Comment by majorsylvie** [comment]
added `view_operation` to the `lookup_t_init` call within `cmd.c`. 
This is the place where strings are matched to the functions. 

Does not yet compile as current push. Trying to find what I need to adjust such that it recognizes the view_operation function

**Comment by majorsylvie** [comment]
Used gdb to debug in order to find what actually needs to be changed.
Specifically using the first example chiventure run on a gdbserver. Will edit with actualy commands

I know that in the end, commands are ran with the `do_cmd` function. They key to get new actions that are not kind1 2 or 3 is to deal with do_cmd. Doing further debugging to see if I can get more information.

**Comment by majorsylvie** [comment]
update! met with the action_management team, they have implemented a new type of command:
`kind4` which deals with actions of type `ACTION [player.attribute]`, chief among them being `VIEW stats`.

This class is concerned with actions related to player attributes, as of now view is the only actual action that fits this category, containing `stats` and `quests` as well as potentially `inventory`.

We made a shared note doc to document what each group has to do!:
https://docs.google.com/document/d/1XEtIJlm0A2CyZ-WRf0a7PABN_FjYQ_BLR5ccnZuM8H4/edit

This details how we are to restructure our `view_operation` function into `kind4_operation`, slightly reformat the control flow, and giving the action_management team's `do_self_action` function the input types it needs.

Along with this, it entails adjusting the lookup table initialization to include kind4.

**Comment by majorsylvie** [comment]
Pushed the necessary changes to lookup table related function `add_action_entries` and `lookup_t_init`.

This assumes that there is a kind4 operation supported, which is not currently true in branch, but is true for action-management.

**Comment by majorsylvie** [comment]
changed view_operation to `kind4_action_operation` and added necessary function header to operations.h

**Comment by majorsylvie** [comment]
refactored old `view_operation` implementation to match the control flow needed to call action managements `do_self_action` operation.

Specifically we are now only checking that the game and second argument are present, having decided that validating the self_attribute is up do *action_management*. 

This resulted in removing some control paths from our implementation as they are situations now handled by action_management

**Comment by majorsylvie** [comment]
commented out old code from view_operation control paths that are no longer valid. To be removed when the view_operation work within the dev branch.

At this point, the codes next step is to be integrated with action managements progress, until they signal they are ready.

as a result, I will write basic tests for the kind4 operation that test our current control paths. 

commit `d0299478571bfa18eeac707700b9c513f062bb03` is where I commented out the code that relies on action_management to have work done such that I can write tests of current control flow.

**Comment by majorsylvie** [comment]
added the testing file `test_operation.c` and updated the CMakeList to include it as a source

Still need to ensure that the test is running and compiling properly

**Comment by majorsylvie** [comment]
renamed `create_sample_ctx()` to `maketest_ctx()`. 
Adjusted type declarations in `test_operation.c` in order to compile. 
Pushed to look at workflow output

**Comment by majorsylvie** [comment]
in workflow https://github.com/uchicago-cs/chiventure/runs/6462507526?check_suite_focus=true for commit `39a1675c458d7dbd9ec144e970e8b57b6aa90be7` 

the following is printed for cli testing:
```test 3
      Start  3: test-cli

3: Test command: /home/runner/work/chiventure/chiventure/build/tests/cli/test-cli
3: Test timeout computed to be: 10000000
3: [====] Synthesis: Tested: 25 | Passing: 25 | Failing: 0 | Crashing: 0 
 3/14 Test  #3: test-cli .........................   Passed    0.72 sec```

Marked down to be sure tests are being added

**Comment by majorsylvie** [comment]
as of most recent commit `5eb4bd4ba9c174433222f9a7ed376a2031a9af78`, (run https://github.com/uchicago-cs/chiventure/runs/6462853996?check_suite_focus=true)

the test_operation.c file is working and running tests, along with the game==NULL test passing

will now be writing more tests then making a PR!

**Comment by majorsylvie** [comment]
updated kind4 implementation to check for there being 2 or more arguments and raising an error.
This can be removed if actions/another team wants there to be more arguments.
Then onus for checking argument amount would go to the `do_self_action` command
AND the function header would have to change to **accepting a string array instead of an individual string**

**Comment by majorsylvie** [comment]
added 2 more tests for there being 2 or more arguments. On workflow https://github.com/uchicago-cs/chiventure/runs/6463100490?check_suite_focus=true all tests pass :)

gonna add tests for normal control flow

**Comment by majorsylvie** [comment]
test added for normal control flow, everything compiles and passes!
https://github.com/uchicago-cs/chiventure/runs/6463188263?check_suite_focus=true

time for PR :)

**Comment by majorsylvie** [comment]
actually, needed to update the return values for the different control paths to make them more descriptive. 

At this point, I am making a PR to dev. 
What will need to be done after this is that action-management must uncomment the line involving the `do_self_action` command call. This is noted in the code.

After action implements their `do_self_action` function fully, then it is up to both of us to figure out how to get chiventure to recognize the commands.

**Comment by majorsylvie** [comment]
Actual closing comment! 
Faruk did most of the implementation and testing
Miles helped with both implementation and communicating with other teams about what they needed from `view stats`
Matteo reviewed the code to make sure documentation was okay

**Comment by jacknugent1529** [comment]
Issue Score: Excellent

Comments: Great work on this issue! The updates are very thorough and are great for documenting your progress. The task description could be a bit more thorough to clarify what the specifications from the action management team and UI team are exactly.
