### ISSUE TITLE
Enhance WDL file to allow author input regarding on-screen statistic displays

### ISSUE THREAD

**Issue by csraffaga** [uchicago-cs/chiventure#1272]
Chiventure contains a number of player statistics but limited screen space. As such, authors should be able to specify the most important statistics / which they desire to display on screen and where. They will do so in the WDL file, and therefore this functionality needs to be added as it does not currently exist.

**Comment by csraffaga** [comment]
After some review of the WDL file, I, after gauging the opinion of my teammates, have devised a new proposition and addition to Chiventure. I propose allowing authors to specify graphical preferences for representations of their game through a "GDL" file. This would follow a similar JSON styled format as the WDL to make specifications easier for the author. A sample wiki draft is present in the graphics_sandbox branch in include/gdl.

**Comment by philipchenaux** [comment]
Issue Score: Satisfactory

Comments:
Great job! One thing to work on for future issues would be to add some status updates to this issue between the opening and closing statements. If you make any intermediate progress before finishing the task, then it should be documented on the GitHub issue via a comment. These updates should be substantial and describe your thought process, etc.
