### ISSUE TITLE
Implement display_statistics module

### ISSUE THREAD

**Issue by csraffaga** [uchicago-cs/chiventure#1273]
In Sprint 2 I collaborated and consulted with the CLI and Action Management teams to design the shell of an on-screen statistics feature. In Sprint 2 I successfully designed the outline for this module. It is now time to implement the functions required to produce this effect.

**Comment by csraffaga** [comment]
The implementation for the display statistics module will require completion and approval of the GDL framework and the implementation of the scene graphics feature (as on screen stats will be overlayed on this. As of now this item is on the back burner and may not be in use until sprint 4.

**Comment by csraffaga** [comment]
Thus far the display statistics module has not been acted on yet as it requires completion and formulation of the scene module and the newly approved gdl system. The representation of the on screen statistics is now specified in the gdl file and function headers have been designed in read_gdl.h that can be found in /include/gdl.

**Comment by csraffaga** [comment]
A key aspect of the future of GUI in Chiventure, unfortunately displaying statistics did not receive the attention it deserved. This was due to some complications with other modules (inventory) and the creation of a new GDL module which took priority. The GDL as it stands provides some foundation and direction for future teams to edit and improve Chiventure, but also leaves substantial design and implementation leeway.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great work! Note that ideally an issue started in one sprint will be completed by the end of that sprint and not drag onto the next one.
