### ISSUE TITLE
Use design document to implement specialized stats in the battle module

### ISSUE THREAD

**Issue by nicholaswlee** [uchicago-cs/chiventure#1275]
Our task is to implement our new specialized stats. This includes adding magical attack/defense, critical damage, accuracy, and skill points. The full struct and functions changes are outlined in this [document](https://github.com/uchicago-cs/chiventure/issues/1233). This will look like not only changing our struct but modifying other areas of the code to accommodate and use these new stats.

Members: Nicholas, Fatimah

**Comment by corian-jal** [comment]
We have created a battle-stat-changes branch and started making the implementation changes.

**Comment by nicholaswlee** [comment]
After implementing some of our code, it is apparent the move_t and battle_item_t will have to change in order to accommodate these new stats. We will soon need to create a new design document for these changes.

**Comment by nicholaswlee** [comment]
Fatimah and I have completed most of the changes. This includes in the structs, updating in code documentations, and realigning functions to accommodate for these stats.

**Comment by nicholaswlee** [comment]
These are the current c files that have been edited:
- battle_state.c
- battle_logic.c
- battle_ai.c
- battle_structs.h
- battle_print.c
- battle_default_object.c
This implies that we will have to make test changes to the following and possibly more files:
- test_battle_ai.c
- test_battle_flow.c
- test_battle_logic.c
- test_battle_state.c
- test_battle_default_objects.c

**Comment by nicholaswlee** [comment]
We have implemented tests and commented out all of our examples and have closed this issue. These changes have allowed battles to become more customizable, including have magical attack/defense, critical damage, accuracy, and skill points! Our current branch passes all the [checks](https://github.com/uchicago-cs/chiventure/actions/runs/2283397844)! We did have to change some NPC tests and examples, but those were only 2-4 lines that is just a field rename. We have submitted a [pull request](https://github.com/uchicago-cs/chiventure/pull/1304) to get out new changes approved.

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this issue! Ordinarily, an issue associated with a PR shouldn't be closed when the PR is opened, but when the work associated with that issue is done (i.e., when the PR is complete and merged).
