### ISSUE TITLE
Design reader effect

### ISSUE THREAD

**Issue by anchristensen** [uchicago-cs/chiventure#1279]
Based on the reader effect described here (https://github.com/uchicago-cs/chiventure/wiki/Skill-Trees-~-Integrating-complex-skill-(combined,-random,-sequential,-etc.)-implementation) we will design a more thought out way to later implement this reader effect. The reader effect essentially looks at the world to evaluate if a certain condition is met as specified by the game developers. For instance, the reader effect might take an argument of SINGLE_TARGET and "undead" to tell the reader to go to whatever the player is targeting and check the attribute of being "undead." A wiki page will be added which specifies this design.

**Comment by anchristensen** [comment]
Closing statement: We added a wiki page here https://github.com/uchicago-cs/chiventure/wiki/Skill-Trees-~-The-Difficulty-of-the-Reading-the-World describing how we might implement the reader effect as well as some of the difficulties of doing so. A quick summary of the wiki page and what we discussed: With the way C implements structs, there is no way one could “iterate” over every possible struct we have in chiventure in order to find the statistic or attribute we're searching for. For every possible variable or statistic one may want to check, there must be a line in the function pointing to that object/statistic, for instance if the player has x object in their inventory, if the room has y item, if the player has z health. Given the amount of potential stats to check, if everything were included, we would quickly create bloated, hard to read code. We are forced to include a limited amount of objects to look at and there is no way for users to create their own custom reader. All three of us met up to work on this in person, and we typed up notes on a google doc reflecting our discussion before pasting them on the wiki.

**Comment by jacknugent1529** [comment]
Issue Score: Satisfactory

Comments: The wiki page looks very thorough (note that you can use triple backticks ``` for code blocks). However, you should add a few comments to the issue to describe what parts of the code you were exploring, and how you approached the issue.
