### ISSUE TITLE
Create design document for new fields of move_effect_t struct

### ISSUE THREAD

**Issue by anchristensen** [uchicago-cs/chiventure#1280]
We will collaborate with the rpg-battles team to design a way to fill out the move_effect_t struct in the effect.h file. The move_effect_t struct already includes a pointer to a move that specifies the move that will be unlocked but after speaking to rpg-battles we will evaluate what, if any, fields should be added to this structure so it will better suit the functions/ways we use it.

**Comment by anchristensen** [comment]
Closing comment: It is unclear from previous years what, if any, other functions were meant to use the move_effect_t struct--they only noted "More fields will probably be added after speaking with the rpg-battles team / TODO - Add more fields." From the documentation in the file, it is unclear what other fields were intended to be added and how else this struct was intended to be used after the past year met with their respective rpg-battles team. We met with the rpg-battles team to attempt to figure out how this struct was meant to be updated, however they didn't have any suggestions or understanding of what was meant to be added. Therefore we have determined that this struct doesn't have any clear way to be updated and, for now, it fulfills all the purposes it was intended to meet. It is possible we may update this struct if we figure out another way to use this struct but for now we will not update it. We described this decision on the wiki here: https://github.com/uchicago-cs/chiventure/wiki/Skill-Trees-~-Summary-of-Skill-Tree-Integration-2022 We met over zoom to discuss this and each made notes on our discussion on a google doc which was then added to the wiki page.

**Comment by jacknugent1529** [comment]
Issue Score: Satisfactory

Comments: Nice job exploring the issue and documenting your findings! It's unfortunate that last year's documentation doesn't provide a clear direction. Keep in mind that as you're looking into the code and meeting with other teams you should try to comment on the issue to describe your progress.
