### ISSUE TITLE
Design npc player classes by consulting playerclass team and add to design document

### ISSUE THREAD

**Issue by emilybae1705** [uchicago-cs/chiventure#1282]
Currently there is no implementation of npc `class_type` as well as the different levels of player classes that can fight with an npc. Some design choices we need to make include: 1) npc class_types that will engage in battle (needs integration with `hostility_t` struct); 2) different class_types for players who will fight with a hostile npc and a conditional friendly npc, respectively. By collaborating with the RPG-Playerclass team, we will add to our previous design document the implementation details and clear up the ambiguities mentioned above.

**Comment by emilybae1705** [comment]
On 05/06/2022 I met with the RPG-Playerclass team and discussed the design for NPC `class_t`. Currently, there is no concrete layout of the design for NPC class types, but Playerclass is working on implementing an NPC "vanilla" type, which is just a standard NPC with no special skilltrees associated. The meeting log can be seen in this [document](https://docs.google.com/document/d/1Jbnhc9uAHyTTw3JtAzor__g8URMxm557J4N_vC42b5Y/edit). The playerclass design document can be referenced in #1236. We concluded that NPCs and standard players can have the same class types. To distinguish between an NPC and a standard player, however, the `DEFAULT_CLASS_NAMES[]` struct will include a flag indicating whether a player is an NPC or not. Next steps following this meeting include assigning different class types to each of the hostility levels FRIENDLY, CONDITIONAL FRIENDLY, and HOSTILE. This could be done in one of two ways:
1. FRIENDLY, CONDITIONAL FRIENDLY, and HOSTILE _modes_ for each class
2. Different classes are assigned different hostility levels.

While our team is currently leaning toward the 2nd implementation, I will leave updates following my meeting with RPG-Skilltrees.

**Comment by srydbergcox** [comment]
On 5/10, Emily and I met with the Skill Tree team to discuss NPC integration. We realized that their current focus is on improving the effects of skills to be more complex, not class-specific skills which would be more in line with NPCs. Further, it seems that skill trees are designed with the player in mind not NPCs. In the future, we may be able to create static NPC skill combinations that are determined by a combination of player class and level of difficulty. But, for now, we decided that we will focus on NPC integration with battles and player class.

**Comment by emilybae1705** [comment]
Following up on https://github.com/uchicago-cs/chiventure/issues/1282#issuecomment-1121634947, we concluded that class types and hostility levels can be separate. NPCs in each class can have different hostility levels and a CONDITIONAL FRIENDLY NPC can turn HOSTILE when provoked by a player during a conversation. We will include all of these details in the design document.

**Comment by emilybae1705** [comment]
We have updated a new [design document](https://github.com/uchicago-cs/chiventure/wiki/NPC-~-NPC-Battle-Integration-Changes-Design-Document). Please refer to it for details on changes to npc_battle and npc modules.

**Comment by emilybae1705** [comment]
This sprint we created a [design document](https://github.com/uchicago-cs/chiventure/wiki/NPC-~-NPC-Battle-Integration-Changes-Design-Document) detailing 1) the changes to be made to npc and npc_battle modules, 2) the development of npc class types and 3) the provocation of npcs in dialogue. In order to increase compatibility among `npc_t`, `npc_battle_t`, and `combatant_t` structs, we decided to make several design choices such as adding battle_item_t and class_t to npc_battle_t. Please see the pull request on #1283 for details on what specific changes were made to npc and npc_battle modules following this design plan. As for `class_type`, @srydbergcox and I met with Player Class and Skill Trees to discuss what class types are currently designed for npcs and what distinct skills and stats do they have compared to players. Player Class said they created a basic/vanilla case for npcs and during our meeting we decided to have npcs share the same class types as players with a flag just indicating whether the given character is an npc or not. Skill Trees seemed to have a different focus from us currently, so we decided to collaborate with them in the next sprint if time allows. Because there's a variety of default class types listed in `class_prefabs.c`, instead of having a predetermined `hostility_level` for each class, we decided to keep `hostility_t` and `class_t` as separate attributes. Each class will have players with a variety of hostility levels. 

Finally, @sglenn-uchi added to the dialogue provocation section of the document which elaborates how an npc's `hostility_level` will change from CONDITIONAL_FRIENDLY to HOSTILE during a conversation with a player. Sydney and I discussed implementing a `tone_t` enum that identifies which tone a player is speaking in. If it's a negative tone like `ANGRY`, the npc can take the dialogue as a provocation to start fighting. Our main next step closing this issue is to work on dialogue provocation with Sydney and Jun to figure out how dialogue can both change an npc's `hostility_level` and trigger a series of actions such as starting a battle. (Note: Sydney and I met and worked on the design document right before the sprint meeting on 05/16 which is why she was assigned to this issue relatively late)

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this issue! The updates and closing statement are incredibly thorough. One comment:
1. While using Google Docs to sketch out some of the documentation, you should avoid posting links to those Google Docs from an issue, as it may cause confusion as to whether that document (or some future update to the wiki) is the most up-to-date version of that documentation. You should instead transfer the contents of the document to the wiki, and then link to the wiki when updating the issue.
