### ISSUE TITLE
Create Multiclass Module within Playerclass Feature

### ISSUE THREAD

**Issue by wellingtj** [uchicago-cs/chiventure#1287]
Currently, the class.c file contains a lot of code on multi-classing. This includes functions like multiclass_shortdesc, multiclass_longdesc, multiclass, has_component_class. This code could be contained within its own module, multiclass.c. From there, it would be easier and ideal to implement testing for multiclassing

**Comment by wellingtj** [comment]
it appears the code won't compile. I will debug this tomorrow

**Comment by wellingtj** [comment]
I ahce

**Comment by wellingtj** [comment]
I have fixed the issue and submitted a pull request. I believe I accidentally had some code from another issue I worked on which I removed

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work! One comment:
1. For a task of this size, we would've expected to see more status updates and/or status updates that were more detailed. For example, it would have been nice to get updates about the debugging and what the bug was/how it was fixed.
