### ISSUE TITLE
Prefab an NPC class to represent a "base level" class

### ISSUE THREAD

**Issue by wellingtj** [uchicago-cs/chiventure#1288]
It doesn't make conceptual sense to have every npc have some elite sounding fighter class like "warrior" or "wizard". Therefore, it would be ideal to prefab a more vanilla class for NPC's that aren't intended to be something special. This would be a kind of "base" class that modeled after the other prefabs in class_prefabs.c and is prefabricated for NPC's in this issue here.

**Comment by wellingtj** [comment]
met with @emilybae1705 from the npc team and we discussed implementation details. I will add a vanilla class and look into whether it is feasible to add a NPC_FLAG within the class struct to flag for NPC's

**Comment by wellingtj** [comment]
I have completed the implementation for the NPC class. I will discuss logistics with lily for a pull request tomorrow

**Comment by wellingtj** [comment]
I had a bug that was stopping the code from compiling but Lily helped me find it. I missed an else on line 187 of class_prefabs.c. We are good to go. The code now compiles

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this issue! Good job particularly on the updates about the bug.
