### ISSUE TITLE
gui: first-drafting a better modular design for adding more content on to the user interface

### ISSUE THREAD

**Issue by cyruszzhou** [uchicago-cs/chiventure#1289]
The original modular design seems hardcoded and not suitable for adding new content to the user interface. I am thus planning to come up with a better modular design overall.

**Comment by cyruszzhou** [comment]
![image](https://user-images.githubusercontent.com/69405365/166950532-4e8c135e-6eb5-4e98-8efb-b041718bc5f5.png)

**Comment by cyruszzhou** [comment]
Copying from slack:
I have written the Splitscreen module and the update module. The main UIGraphics module would not be a problem, the same for textbox module. Now I think the main task is to tweak the original UI_CTX module into our context module (Why tweak? Because now we need more information: NPC, Inventory, WDL game developer setting, etc.). Then we can proceed to refine each sub-splitscreen modules (Map, Inventory, NPC, Scene), and I guess that would be easy.

Note: I completed the synthesizing UPDATE function, not each update function from each individual module

The synthesizing update function would be a switch function. I have come up with enums for different content, so that would be an easy one

**Comment by cyruszzhou** [comment]
I will discuss with my teammates further on this modular design in today's evening meeting. The issue for first-drafting is closed for now.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great work on this issue. One comment I have is that make sure all of your updates are relevant to the issue. The update that was just copied straight from Slack can be interpreted as slightly out of context and can be confusing to interpret.
