### ISSUE TITLE
Update WDL Specification with for condition objects and more extensive item examples

### ISSUE THREAD

**Issue by bansals10** [uchicago-cs/chiventure#129]
In this issue, we will be adding conditions for the room object in order to specify when the user is allowed to exit a room. We will also update the syntax for this object in order to make the sub-objects more accessible for validation and loading into game structs. We will also add further explanation with clearer readability for other teams in our specification so that there is no confusion as to which fields are being inputted by the game developer.

**Comment by bansals10** [comment]
Updated Room definitions and examples as per conversation with game_state this week. Provided new examples with clear syntax for game designer and more clarity for other groups.

**Comment by Kate32815** [comment]
Updated Item specification by standardizing syntax used for detailing the actions that can be done on an item. Provided more extended examples that utilized every possible attribute in order to clarify the item object for game designer. Added specification on which item attributes were optional and increased explanations for the purpose behind various attributes like "conditions" and "set".

**Comment by bansals10** [comment]
Closing statement: We expanded on our specification for the WDL by provided more extensive examples and descriptions for the three object files (Game, Room, and Items) after communicating with game-state. We modified the syntax for the object files for ease of parsing when loading into game structs and during validation. We will continue updating in future sprints as deemed necessary.

**Comment by bansals10** [comment]
Closing Statement:
We expanded on our specification for the WDL by provided more extensive examples and descriptions for the three object files (Game, Room, and Items) after communicating with game-state. We modified the syntax for the object files for ease of parsing when loading into game structs and during validation. We will continue updating in future sprints as deemed necessary.

**Comment by lydiafilipe** [comment]
Issue Score: ✓+

Comments:
Good work!
