### ISSUE TITLE
Implement Chiventure example of player teleportation with custom actions

### ISSUE THREAD

**Issue by jbrouwer5** [uchicago-cs/chiventure#1291]
Player teleportation has been toyed with my previous action management teams. One promising solution is to leave teleportation as an action implemented using custom actions. We will create an example of using custom actions to do player teleportation to test its feasibility.

**Comment by jbrouwer5** [comment]
Pushed skeleton files in a custom-actions/examples folder. One file contains function headers for creating a game sample and teleportation sample. The other file is a wdl file describing a pokemon game. I updated the wdl to have the necessary components for teleportation which included a new room.

**Comment by jbrouwer5** [comment]
I implemented teleportation as a custom action. To do this I had to allow action blocks to take arguments besides attributes, namely rooms and games. Therefore I made a struct to hold parameters that can hold all three types, called action_params.

**Comment by jbrouwer5** [comment]
I had to change a lot of test cases to allow for the change in the function parameters. I made some errors and there are currently failing tests. I realized the mistake and am going through now to fix the test cases for action blocks and AST.

**Comment by jbrouwer5** [comment]
I have since fixed all of the test cases and pushed the code so that the TELEPORTATION custom action is now implemented. I'm now going to try to create an example.

**Comment by jbrouwer5** [comment]
After inspecting previous examples from other modules such as npc, I realize that an example isn't appropriate for a custom action since it is such a short series of events. The applicable tests are equivalent to the examples for teleportation. That being said, the teleportation is implemented in custom actions and the appropriate tests have been written. I will now be closing this issue.

**Comment by ecoble** [comment]
Issue Score: Excellent

Comments:
Nice job! I know it can be tricky to work with custom actions code, great work!
