### ISSUE TITLE
Create and Edit Current Tests in RPG Battles to accommodate for stat_t Changes

### ISSUE THREAD

**Issue by nicholaswlee** [uchicago-cs/chiventure#1292]
We need to create and change the tests for our implementations for stat_t in reg battles. This will look like editing the following files:

test_battle_ai.c
test_battle_flow.c
test_battle_logic.c
test_battle_state.c
test_battle_default_objects.c

After implementing these, there is a chance we will have to continue doing more if we realize other tests need to be changed.

**Comment by nicholaswlee** [comment]
Fatimah and I are meeting to add and fix the current tests.

**Comment by nicholaswlee** [comment]
Fatimah and I have fixed all of the tests. We did change two tests for NPC, test_npc_battles.c and test_npc.c

**Comment by nicholaswlee** [comment]
Here is the [action](https://github.com/uchicago-cs/chiventure/runs/6316709509?check_suite_focus=true) where all of our tests compiled. Unfortunately we are unable to move forward until the examples have been changed.

**Comment by nicholaswlee** [comment]
We have finished and now have made a pull request. All of our current tests have passed [here](https://github.com/uchicago-cs/chiventure/actions/runs/2283397844)! Our testing currently supports minor accuracy and critical rate checks. We will need to create a separate pull request to make these tests. These tests also should go with move_t and battle_item_t when those get created.

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this issue! Ordinarily, an issue associated with a PR shouldn't be closed when the PR is opened, but when the work associated with that issue is done (i.e., when the PR is complete and merged).
