### ISSUE TITLE
GUI: Making maps displayable, Part 1

### ISSUE THREAD

**Issue by cyruszzhou** [uchicago-cs/chiventure#1296]
In this sprint, we will be making maps displayable in an individual window with testing inputs. We want the map to run in a separate window, and display the player position and the whole map (from the current game state) properly and informative. Therefore, it would be crucial for us to come up with a proper modular design and think about relevant data structures/algorithms/programs to realize this function.

**Comment by csraffaga** [comment]
Formatting, as well as data structures (a map_graphics struct) in addition to written new and free functions have been pushed to Github from my local repository. A few adjustments need to be made to the draw_map_graphics struct in order for it to compile and output as we want, but this is progress!

**Comment by ukanyanwu** [comment]
The map_graphics struct has its new/init/free functions implemented, along with tests that assert that they work correctly. In a separate main.c file, the function to run map_graphics is also implemented. Something important is that the map_graphics use coordinates of the player to help develop the map, but there is currently no implemented function to pull said coordinates and. have them updating. Future developments for the map_graphics will be on how to better retrieve coordinates of the player in the game's world.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great work! But note that for a task of this size, we would've expected to see more status updates and/or status updates that were more detailed.
