### ISSUE TITLE
GUI: Making Scenes Displayable, Part 1

### ISSUE THREAD

**Issue by cyruszzhou** [uchicago-cs/chiventure#1300]
In this sprint, we will be making Scenes displayable in a separate window taking in testing inputs.

**Comment by cyruszzhou** [comment]
Note: I am just creating the issue. There are only three assignees for this issue, as shown.

**Comment by csraffaga** [comment]
The modular design for scene is complete and pushed to GitHub. This push consists of a scene data structure with information required to output the desired screen with author customizations. New and free functions have also been written  and only require a few minor adjustments to ensure they are working as desired. The draw_map_function just needs to be updated to call the new function and reference new fields in the struct. One that is accomplished the module will be complete.

**Comment by csraffaga** [comment]
The pull request has been sent and approved. This issue is closed.

**Comment by philipchenaux** [comment]
Issue Score: Satisfactory

Comments:
Great work! There are just two notable issues:
1. The issue was started in sprint 3 and ended in sprint 4
2. The summary of the issues is too terse, you should at least explain what scenes are.
