### ISSUE TITLE
GUI: getting the team on the same page by helping them installing Raylib and write corresponding Makefile

### ISSUE THREAD

**Issue by cyruszzhou** [uchicago-cs/chiventure#1301]
Our team has been struggling to install and run the proper version of Raylib, and that is why our progress is stuck. I finally got Raylib working on my Mac, so (as there exists almost no dependency among the newly designed modules) I ask them work locally first. After the deployment lecture week, we may be using a virtual environment to run the game.

**Comment by cyruszzhou** [comment]
As we are all using Macbook, I think we have no trouble brew installing raylib and using the Makefile. I messaged my teammates through Slack on how to use raylib in detail.

**Comment by cyruszzhou** [comment]
We finally got raylib working for us. This issue is closed.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great job! I would advise that status updates on an issue should have something tangible to share. So in this case including brief documentation about how to get raylib loaded would be helpful.
