### ISSUE TITLE
Complete implementation of NPC actions (kind 5 and kind 6)

### ISSUE THREAD

**Issue by sglenn-uchi** [uchicago-cs/chiventure#1302]
members: Jun, Sydney

We discovered that the npc_actions branch already contains partial implementations of NPC actions, but they're not complete. The goal of this issue is to finish the implementation of kind 5 and 6 actions so that we move one step closer to submitting a pull request.

**Comment by sglenn-uchi** [comment]
After looking through npc_actions.c, we realized the code has many implementation errors and is generally nonsensical, so we'll have to rewrite it from scratch before we can complete implementation for kind 5 and 6 actions. We will try to complete implementation for performing kind 4 actions by the end of the sprint and aim to revisit kinds 5 and 6 in sprint 4.

**Comment by sglenn-uchi** [comment]
After merging the changes to npc_actions, Jun realized there was an already an existing implementation for kinds 4-6 in the action management files that was supposed to be adapted into npc_action. Jun and I familiarized ourselves with the code and we started working on fixing errors in the implementations. I also worked at updating npc_dialogue for the code in action_management.

**Comment by sglenn-uchi** [comment]
Rolled over into Sprint 4. Need to modify code so that tests pass.

**Comment by junasano** [comment]
We finished adding onto the already exisiting implementations of kind 4-6 actions and have it is updated on the npc/actions_original branch. Our next step would be to have the tests pass and this links to the issue here:
https://github.com/uchicago-cs/chiventure/issues/1339

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work! One comment:
1. The issue was closed before it was actually done. Issues that involve writing code should be closed by their associated pull request.
