### ISSUE TITLE
GUI: Writing a displayable input box

### ISSUE THREAD

**Issue by cyruszzhou** [uchicago-cs/chiventure#1310]
It would be nice if we all can input our text commands through a better, visualized, interactive input box! I will be coding up an individual displayable input window and adapting it to the game in general in the future. To this end, it would be good to create a buffer to contain the user input, so that we can interact with the main program. Also, the input box should be properly animated with graphics matching the style of Chiventure

**Comment by cyruszzhou** [comment]
Update: I have finished writing the textbox and enabled it to transfer data to the main game through a buffer. Now the textbox is limited to 14 characters but we can change it if we see fit. The color theme and holistic style/ animation of the input box matches those of chiventure. I am waiting for the response from the TA to merge this feature into the master branch.

**Comment by cyruszzhou** [comment]
This issue is closed for now as the feature is successfully implemented.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great work, the issue is thorough and concise.
