### ISSUE TITLE
Modify the quest struct to make quests global and create a Wiki explaining the changes

### ISSUE THREAD

**Issue by JSerf02** [uchicago-cs/chiventure#1311]
When working on incorporating quests into the player struct, we encountered a really bad circular dependency issue that requires a massive redesign to resolve. Essentially, the player module relies on the quest module, but the quest module also relies on the player module, which is what causes the problem. 

When attempting to fix this issue, we quickly realized that it is impossible to remove the quest module's references to the player module, so we need to instead remove all references to quests from the player module while maintaining quest functionality. This means quests will need to be stored globally in game_state (as they already are) and accessed via their ids by the players. This solution should work, but the quest module was not designed with this in mind, so we need to read through all of the quest functions and structs and modify them to fit with this new design. 

This issue should cover the design and documentation aspects of this change while Issue #1163 should cover the actual implementation once this is finalized.

**Comment by JSerf02** [comment]
After a bit of analysis, we determined that the main change in the quest module is that the `int status` component in the `quest` struct needs to be removed so quest status can be stored along with quest ids in the player struct for each player. This way, the same global quests can be used for every player while still leaving the current status functionality. The same change also needs to be made for tasks with `bool completed`. 

The following functions will need to be updated or potentially removed to support these changes: `quest_new`, `quest_init`, `start_quest`, `fail_quest`, `is_quest_completed`, `get_quest_status`, `task_init`, `find_task`, and `complete_task`.

We will document all of this info in a wiki page

**Comment by JSerf02** [comment]
Documented the redesign in this [Wiki](https://github.com/uchicago-cs/chiventure/wiki/Quests-~-Globalization).

**Comment by JSerf02** [comment]
We finished redesigning and documenting these changes to the quest struct (see the Wiki linked in the previous comment). We also managed to implement them successfully, though we need to submit a couple of other pull requests before we can PR these changes.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great work on this issue, very thorough and a nice link to a wiki.
