### ISSUE TITLE
Create a design document to update move_t to accommodate different types of moves, including defensive, magical, physical, and stat changing moves.

### ISSUE THREAD

**Issue by nicholaswlee** [uchicago-cs/chiventure#1312]
We would like to update the current move_t struct to accommodate for physical versus magical moves, moves that change the stats of the user, target, or both, and add a stub for possible future effects. We also need to make changes to moves as they currently exist in order to integrate them with our previous update to stats. The product will be a design document with our plans for implementation.

members: Fatimah and Nicholas

**Comment by nicholaswlee** [comment]
Fatimah and I are currently discussing how we can change move_t. Currently we have decided to add to enums to help capture what a move does, damage_type_t, that defines if a move does physical or magical damage. We also have target_type_t, that defines if the move(that is not an attacking move) targets the user, opponent, both or none. The target_type_t would be reserved for moves that are for stat changes and status effects.

**Comment by corian-jal** [comment]
Nicholas and I have fully fleshed out our plan for the implementation of the new move_t struct and located all of the functions that will need to be updated to accommodate this change in [this document](https://github.com/uchicago-cs/chiventure/wiki/Battles-~-Move-Changes-Design-Document). Our next step is to actually implement this change, which we will do once our previous PR is approved.

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this issue!
