### ISSUE TITLE
add wdl support for openworld structs

### ISSUE THREAD

**Issue by lukasg8** [uchicago-cs/chiventure#1313]
In order to move towards statically integrating the openworld module into chiventure, it needs to be fully wdl-supported so that all of the necessary structs and types can be parsed into the game during the startup. Otherwise, the autogenerate module will not have all the information it needs to generate the world.

**Comment by rohandeme** [comment]
We have ultimately to close this issue and split it into 3 sub-issues related to formatting the WDL for openworld, designing a load_openworld file in the WDL src library, and implementing functions for that file to read from a WDL file.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Well done including a closing statement explaining the split task.
