### ISSUE TITLE
add gencontext_t struct to game_t struct to prepare for dynamic integration of openworld module

### ISSUE THREAD

**Issue by lukasg8** [uchicago-cs/chiventure#1314]
Eventually we will want the openworld to be dynamically integrated into the rest of chiventure. That is to say, the autogenerate algorithm is executed as the player navigates the world and generates rooms with the context of the entire game state. This means the autogenerate algorithm with need to have access to said context (e.g. current room, current player level, items owned) while the game is running. Therefore, we need to add the gencontext_t struct to game_t so that the autogenerate module can continuously access the data it needs. 

Also, with reference to the openworld Wiki from last year, we may have to modify the gencontext_t struct to add more openworld specific structs (such as levelspec). This would allow for level-oriented generation.

**Comment by lukasg8** [comment]
Ended up not incorporating the levelspec_t struct within the gencontext_t struct. Instead, added the two structs seperately to the game_t struct. This will allow for greater flexibility when openworld is integrated with chiventure because the game will be able to autogenerate with and without level-oriented generation.

**Comment by helenastc** [comment]
Updated wiki under "Deciding an integration approach" to reflect changes and explain current integration status.

**Comment by lukasg8** [comment]
Added and documented.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Good work with this issue, next time adding a direct link to the wiki will be helpful.
