### ISSUE TITLE
changing speclist from linked list to adjacency matrix to allow for less random room generation

### ISSUE THREAD

**Issue by lukasg8** [uchicago-cs/chiventure#1317]
We are looking to change the speclist_t struct which contains the prewritten roomspec_t structs from which the autogenerate algorithm picks from into an adjacency matrix. This is so that we can represent the similarity and likelihood of side-by-side occurrence of different rooms. We are planning to make the matrix weighted and undirected since different rooms will have different likelihoods of being next to each other. For example, a library and dungeon will never show up next to each other.

**Comment by lukasg8** [comment]
After discussions with the team, we decided to change the matrix from **undirected** to **directed** to allow for the possibility of checkpoints and having rooms that the player needs to pass before being able to reach the other.

**Comment by williamhu314** [comment]
We have completed the design and implementation of the new specgraph struct and have incorporated it into the gencontext struct, which will allow us to use the adjacency matrix information stored in the specgraph struct in our autogenertion functions.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great work! Good set of updates and closing statement.
