### ISSUE TITLE
Write init/interface functions for other teams to use

### ISSUE THREAD

**Issue by a-matai** [uchicago-cs/chiventure#132]
The goal of this issue is to put together the interface/init functions for other teams to use. We will map out the workflow for each module (player, game, room, etc) and write the expected functions accordingly.

_Example:_

**UI/AM request** 
- Given ptr to room struct and direction, return ptr to the adjacent room struct in that direction or NULL if no room in that direction.
- Skeleton of above for all other functions.

**WDL**  
- Ensure there are functions that take in ids and create new structs, as well as to create 'lists' (abstracting away whether they are actually hashtables or lists).

**Comment by borjasotomayor** [comment]
This needs to be broken into smaller tasks. It would make more sense to have one task per individual request from each team. So, if Team X comes along and says "we need a function that does Y", then writing that function should be a single task.

**Comment by a-matai** [comment]
@borjasotomayor we realized that we didn't have full coverage for most things so it's pretty general and we need to re-map the workflow and make sure we have these functionalities for everything. 

Should we then open them by module, have it be one large task, or open per request?

**Comment by jessxia** [comment]
The game struct now contains char *start_desc to support the starting description of the game requested by WDL (issue 171). Game_new() takes in this argument, and the field is currently set to a maximum character length of 300 chars.

**Comment by lindsey-hsi** [comment]
This issue turned out to be obsolete, as collaboration with other teams regarding this general topic resulted in the opening of more finely-grained issues that we addressed throughout this sprint, such as issues #171, #157, #151, etc.
