### ISSUE TITLE
sound: create example using Chiventure structs

### ISSUE THREAD

**Issue by jiaoboxuan** [uchicago-cs/chiventure#1320]
In this issue, we are planning on creating an example of sound using sound in chiventure through using the existing Chiventure structs. This will be done through installing VM and then looking at the existing structures in other parts of the game. 

First, we will open a new issue 'research and create chiventure structs needed for the sound example' to first make the game in which we will integrate the sound. After installing VM and finishing this issue, we will incorporated the sound to round out issue #1320 (this one!).

Assignees: Jake, Rhea, Jason

**Comment by sangerr** [comment]
I was able to successfully download the virtual box on my computer.

**Comment by sangerr** [comment]
I am unable to run the chiventure demo through VM, and am getting the same errors I got when running it through my terminal.

**Comment by jwschroeder21** [comment]
I tried writing some code for this sprint that makes an example game and runs the sound and SDL library. It is not finished and ready for a pull request but I pasted it below. 

The code follows the structure of the chiventure/src/npc/examples/npc_example.c and incorporates methods of SDL library integration from the chiventure/src/sound/examples/demo.c files. For the duration of this sprint, I will try to get the code to run. I wanted to update my progress before the meting today though!

`#include <stdio.h>
#include <cli/operations.h>
#include "common/ctx.h"
#include "ui/ui.h"
#include "sound/sound.h"

const char *banner = "THIS IS A SOUND EXAMPLE PROGRAM";

// sample conversation
convo_t *sample_conversation()
{
    convo_t *c = convo_new();

    add_node(c, "1", "NPC: What's up?");
    add_node(c, "2a", "NPC: No thank you. Please leave.");
    add_node(c, "2b", "NPC: Who are you?");
    add_node(c, "2c", "Go forward.");
    add_node(c, "3a", "NPC: Sounds good. You can go now.");
    add_node(c, "4", "Beware.");

    return c;
}

// check loaded game
char *check_game(char *tokens[TOKEN_LIST_SIZE], chiventure_ctx_t *ctx)
{
    game_t *game = ctx->game;
    if (game == NULL || game->curr_room == NULL) {
        return "Error\n";
    }
    if (tokens[1] != NULL) {
        return "What?\n";
    }
}

// load audio
void load_audio(SoundType type) 
{
    SDL_Init(SDL_INIT_EVERYTHING | SDL_INIT_VIDEO); 
    Mix_OpenAudio(44100, MIX_DEFAULT_FORMAT,2, 2048);

    SDL_Window *window = SDL_CreateWindow("This is a music window", SDL_WINDOWPOS_UNDEFINED, 
                                            SDL_WINDOWPOS_UNDEFINED, WIDTH, HEIGHT, SDL_WINDOW_OPENGL);

    SDL_Renderer *renderer = SDL_CreateRenderer(window, -1, SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC);
    SDL_SetRenderDrawColor(renderer, 255, 0, 0, 255);
    IMG_Init(IMG_INIT_PNG);

    SDL_Texture *texture = IMG_LoadTexture(renderer, "../../../../sound_library/chiventure.png");
    Mix_Music *backgroundSound = Mix_LoadMUS("../../../../sound_library/Spring Village.mp3");
    
    Mix_PlayMusic(backgroundSound, -1); 
    bool running = true;                
    SDL_Event event;
    while (running) {
        SDL_RenderCopy(renderer, texture, NULL, NULL);
        SDL_RenderPresent(renderer);
        while (SDL_PollEvent(&event)) {
            if (event.type == SDL_QUIT) {
                running = false;
            }
        }
    }

    SDL_DestroyRenderer(renderer);
    SDL_DestroyWindow(window);
    Mix_FreeMusic(backgroundSound);
    Mix_CloseAudio();               
    SDL_Quit();
    return;
}

// create sample game
chiventure_ctx_t *create_sample_ctx()
{
    chiventure_ctx_t *ctx = chiventure_ctx_new(NULL);

    game_t *game = game_new("Welcome to Chiventure!");

    load_normal_mode(game);

    // make room
    room_t *room1 = room_new("room1", "Room One","Welcome.");
    add_room_to_game(game, room1);
    game->curr_room = room1;

    // make npc
    char *npc_id = "suzanne";
    npc_t *suzanne = npc_new(npc_id,
                             "suzanne is in the corner. Hopefully you can hear the 
                             music play while you decide whether or not to go talk to her.");
    convo_t *c = create_sample_convo();
    add_convo_to_npc(suzanne, c);

    game_free(ctx->game);
    ctx->game = game;

    return ctx;
}

int main() {
    chiventure_ctx_t *ctx = create_sample_ctx();

    // sound operations
    sound_t *sound_file = malloc(sizeof(sound_t));
    sound_file->type = BACKGROUND;

    load_audio_demo(sound_file->type);

    start_ui(ctx, banner);

    game_free(ctx->game);
    
    return 0;
}`

**Comment by sangerr** [comment]
I am creating a battle_sound_example.c file in the src/sound/examples directory, which has been adapted from the NPC battle example. I have made some progress in writing the implementation, but it is not ready for a pull request yet.

**Comment by jwschroeder21** [comment]
I also have the same status as Rhea - have downloaded the virtual box and ran the demo through VM! Just working on getting my example code to run.

**Comment by jwschroeder21** [comment]
Update: we have submitted a PR and are waiting for approval before the merge!

**Comment by jwschroeder21** [comment]
closing statement: 

we created an example of sound using sound in chiventure through using the existing Chiventure structs. First, we opened a new issue 'research and create chiventure structs needed for the sound example' to first make the game in which we would integrate the sound. After installing VM and finishing this issue, we incorporated the sound to round out the issue!

NOTE: The pull request for this issue was submitted before the end of Sprint 3, but there were over a week delays in getting them reviewed. As such, the issue appears to be closed late but was actually "completed" on time.

**Comment by jwschroeder21** [comment]
I prematurely closed this issue and am waiting until the pull request is merged before closing it!

**Comment by sangerr** [comment]
The pull request for this issue was submitted prior to the end of sprint 3, however the PR had delays in being reviewed and has yet to be merged. We will close the issues as soon as it is!

**Comment by jwschroeder21** [comment]
closing statement: In this issue, we created an example of sound using sound in chiventure through using the existing Chiventure structs. We installed the VM and then looked at the existing structures in other parts of the game.

**Comment by ecoble** [comment]
Issue Score: Excellent

Comments:
Great job getting this working, I know there was quite a lot to debug, and great job on the updates! There is a penalty for the issue starting in sprint 3 but completing in sprint 4. Additionally, issues with associated PRs should not be closed until the PR is merged, but I can see that you realized this later on and corrected it. Nice job!
