### ISSUE TITLE
Implement room_autogenerate function

### ISSUE THREAD

**Issue by williamhu314** [uchicago-cs/chiventure#1321]
The goal of this issue is to implement a new room_autogenerate function that generates a room based an adjacency matrix quantifying the similarity of different room types. This is related to #1266.

**Comment by williamhu314** [comment]
My plan for this issue is to use the room_generate function as a helper function. Thus, the main thing that will need to be done is to extract the row in the adjacency matrix within speclist in gencontext corresponding to the similarity scores associated with the curr room type, After extracting this row, the weights, in addition to a random number generator, can be used to determine the room_spec. Once the room_spec is determined, this can be inputted into the room_generate function which will take care of the rest of the generation.

**Comment by williamhu314** [comment]
I think that a helper function roomspec_autogenerate would be helpful. This will take care of all the algorithms we are using to determine the new roomspec. This will make the room_autogenerate function less complex.

**Comment by williamhu314** [comment]
I have updated the gencontext struct to include 2 new fields, one for the number of different types of roomspecs available, and another for an array of pointers to roomspecs. This is needed for the roomspec_autogenerate function.

**Comment by williamhu314** [comment]
I finished implementing and making the headers for both the roomspec_autogenerate and the room_autogenerate functions. I jsut need to fix some bugs at this point.

**Comment by williamhu314** [comment]
There are no more bugs in the roomspec_autogenerate or room_autogenerate functions. However, the code does not yet compile because of issues with functions previously using speclist. We will fix that in #1318 and then submit a pull request. I am closing this issue since the room_autogenerate function is finished.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great work on this issue!
