### ISSUE TITLE
Implement a run_turn_component function based on the run battle design document, will include CLI integration

### ISSUE THREAD

**Issue by emiliolevinspage** [uchicago-cs/chiventure#1322]
We will implement a run_turn_component function, which will be the heart of the run_battle function. Our run_turn_component function will take a turn component, print out the possible actions for a player to take based on the ints in the turn component, accept user input, understand what action was inputted, run that action, and display the results of the action. This will involve editing battle_ctx_t and battle_t to provide a record of the overall turn structure as well as the current turn component.

**Comment by aliu65803** [comment]
We have created a battle/run-battle branch. I have created a turn_component_t struct that has three ints (move, item, pass) and a turn_component_list_t struct that is a linked list of turn components and will represent a whole turn. I have also implemented the necessary new, init, free functions.

**Comment by aliu65803** [comment]
After going through the code, we have realized we will need to add more support for battle mode to set_game_mode.

**Comment by aliu65803** [comment]
After consulting with Lily, we have decided it will be appropriate to change the issue to only include the implementation of a function called run_turn_component.

**Comment by emiliolevinspage** [comment]
I wrote a get_legal_actions function that uses the given turn_component and battle structs to determine which moves and items are available for a combatant to use

**Comment by emiliolevinspage** [comment]
I added print_battle_action_menu in the battle_print module to print a labelled menu of action options for the user.
I also updated the print_battle_move function and added a print battle_item function to be used to report action results.

**Comment by aliu65803** [comment]
Emilio and I have been working to implement the run_turn_component function. Our implementation includes the helper functions to get legal actions, convert those lists into strings and print them, take in user input, and make that effect and report the changes.

**Comment by emiliolevinspage** [comment]
We are getting a mysterious implicit definition error for print_to_cli, even when we include the module it comes from (ui/print_functions.h). We have temporarily replaced the calls to print_to_cli with printf. Will revisit this tomorrow.

we also are not sure how we should get user input- right now we are scanf-ing. this seems to janky.

**Comment by emiliolevinspage** [comment]
we also commented out two tests for print_battle_move for which it was unclear why they were failing.

**Comment by emiliolevinspage** [comment]
We replaced calls to printf() with calls to callback_func() and our code is compiling! **This complete's the run_turn_component implementation**, so we are closing the issue. Some dependencies (e.g. full CLI integration) need to be resolved when we make the run_battle function to wrap around this one.

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work! Next time, make sure to link the issue to its related Pull Request.
