### ISSUE TITLE
GUI: Coming up with data-structures/algorithms to better position and visualize Tasks in a quest

### ISSUE THREAD

**Issue by cyruszzhou** [uchicago-cs/chiventure#1323]
The current challenge is to read from a task tree and come up with a design of that task tree with no tasks or edges overlapping with/crossing each other. Also, we need to make sure that the sizing of the whole visualized tree is proper, not too small and not overflowing.

**Comment by cyruszzhou** [comment]
In last week's meeting, Irene proposed that we could only show the branch in which the current task is at. We feel like this is an amazing idea and decided to implement it.

**Comment by cyruszzhou** [comment]
I decided to use a single integer to store the required steps. Each bit (in reverse order) represents sequentially the next move required to navigate to the demanded (0 represents downwards, 1 represents rightwards). We also record the total number of steps required in that data structure. I have successfully implemented this data strcture.

**Comment by cyruszzhou** [comment]
I successfully integrated this data structure into the main drawing loop. Everything seems to be drawn in right proportions. I will close this issue for now.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great job, and good to see that you reopened the issue to provide an update on a change to this issue.
