### ISSUE TITLE
implement coordinates in the room_t struct

### ISSUE THREAD

**Issue by lukasg8** [uchicago-cs/chiventure#1326]
The autogenerate module will run into the situation below:
![IMG_1553](https://user-images.githubusercontent.com/102938476/167450133-ae47f4bd-6ac7-4120-b518-818d9d52cc58.jpg)
where it has generated two rooms which are beside each other from a global view but they are not automatically connected because they were not generated from one to the other. 

In this example, autogenerate algorithm created room 1, then room 2 towards east, then it stopped generating rooms east and started its chain south where it created rooms 3 and 4. 

Being able to know whether rooms not generated right after each other are right next to each other would be easy if the game_t struct had a list of coordinates of generated rooms. 

At this point, the autogenerate algorithm would have to refer to specgraph_t struct to check the relationship between the two rooms (in this case, rooms 2 and 4). Finally, it could autogenerate whether or not a path is generated between the two rooms based on their weighting in the graph (e.g. if their relationship is 0, no path would be generated but if it was 4/5, the likelihood would be high).

**Comment by lukasg8** [comment]
As referenced to our designs for Static Integration (#1351) and Dynamic Integration (#1374), we have finalized how the coord struct will be used in the autogeneration of rooms when the game is either loaded up initially or as it continues to generate rooms while the player is playing. 

We have split this issue into two smaller sections. The first being the implementation of coord struct and all of its functions #1393 which will remain this issue. The second part which is adding the hash table functionality will be moved to #1449

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Really happy with how this issue looks: a thorough summary and good closing statement.
