### ISSUE TITLE
cli: implement current chiventure grammar in bison sandbox

### ISSUE THREAD

**Issue by bzeng6** [uchicago-cs/chiventure#1328]
team members: Kate, Brianna, Matteo

Previously, the CLI implementation has not used a parsing library and instead relies on a custom parsing mechanism (module parser). This makes it very difficult and impractical to expand upon. Our goal is to re-implement the current parsing functionality using the Bison/Flex parsing library so that it can be expanded upon more easily in the future using the library.

**Comment by bzeng6** [comment]
I just created a pushed into the cli/sandbox branch a y file for the parser using bison. It has a basic outline of what we need to include in the y file and also I've sort of designed/brainstormed the things we need to consider for our implementation:

- Can Bison recognize separate words as individual tokens? Do we need to come up with a mechanism for it to recognize a space as end of word?
- The command line should stop looking for input when user types in newline. 
- We need to create a mechanism for splitting the string from the command line into smaller strings and putting each string into the tokenized commands list. Bison should stop looking for words to add to the linked list of strings when it reads a new line. 
- We need to create a l file

**Comment by bzeng6** [comment]
Currently following these instructions to allow Bison to parse strings:
https://stackoverflow.com/questions/39133560/how-to-parse-a-c-string-with-bison

This has great lex documentation for the lex rules:
https://docs.oracle.com/cd/E19504-01/802-5880/6i9k05dgk/index.html#lex-36741

**Comment by bzeng6** [comment]
I created a bison-parser.l file with some basic syntax. It should be able to recognize all letters (upper and lower), numerical digits, space, and newline, and ignore tab. I also included the string parsing functions from the link in the previous comment.

I also updated the y file with just some dummy syntax. We need to properly flesh out the syntax. I also realized that I think the functions in operations.c actually take in arrays of token strings, not tokenized_cmd linked list structs? So we may need to consider this when making our grammar.

**Comment by katyashchukina** [comment]
To make bison file:

$ yacc parser-bison.y
$ yacc -d parser-bison.y
$ lex parser-bison.l
$ cc lex.yy.c y.tab.c -o parser-bison

**Comment by bzeng6** [comment]
I think that we can just make TOKEN_LIST_SIZE a larger, more reasonable limit, like 20 words (so 20 array items) or something, rather than 4.

**Comment by bzeng6** [comment]
I've created a Makefile for the parser-bison sandbox.

I've defined a linked list of strings struct call word_ll ([thanks](https://github.com/jacknugent1529/bison-example/tree/word_parser) Jack 🥹) that contains each of the tokens in the input.

I've created a parser-bison.c file and a parser-bison.h file, in it with functions that are called when a certain token is inputted, as specified in the parser-bison.y grammar. The parser-bison.l file has been changed so that it recognizes the full words "go", "to", and "fight", along with all letters A-Z and a-z and newline character.

I can't figure out how to make bison non-case sensitive for tokens that are specific strings, for example having GO vs go being the same token, without explicitly specifying each string in the l file.

**Comment by bzeng6** [comment]
I've also included CREDITS as a new token that is recognized as the string "credits", and I'm trying to figure out how to get the parser to call a function handle_credits_cmd in parser-bison.c that will call the credits_operation function in operations.c. 

Currently I'm having trouble with including header files from different directories.
When I write #include "cli/operations.h", which is what other files in chiventure do, I get:
<img width="548" alt="Screen Shot 2022-05-23 at 3 07 28 AM" src="https://user-images.githubusercontent.com/96360414/169773322-39d9ff8c-0607-4e11-bb2c-9b071532146a.png">
When I write #include "../../../include/cli/operations.h", specifying the exact path, I get:
<img width="627" alt="Screen Shot 2022-05-23 at 3 08 11 AM" src="https://user-images.githubusercontent.com/96360414/169773465-810e2130-46c8-4566-ad35-6e1d98ce22d4.png">
I'm hesitant to change the includes in other files/directories because upon merge that may affect compilation for all other teams. Currently in my Makefile I've included a flag -I., so I'm wondering if I should include other -I paths for every include.

**Comment by bzeng6** [comment]
I've fixed the header file issues by including more -I paths in the Makefile.

I've fixed some issues with type mismatch in the y file.

I've also defined a function, ripped from cli/test_game.c file in tests, that creates a sample chiventure_ctx_t struct to use in the call to credits_operations.c.

However, when I make, I get issues where it says certain functions are "undefined reference", even though they're defined in the files I've included. 

<img width="773" alt="Screen Shot 2022-05-23 at 3 35 32 AM" src="https://user-images.githubusercontent.com/96360414/169778641-0843138e-f9e0-4b93-81d0-c1933bfba760.png">

I feel like my problem is actually that I don't need to be creating an ctx struct... but I don't know how else to make the function execute credits_operation!

**Comment by bzeng6** [comment]
The undefined reference issue is fixable by also compiling the c file which the function is defined in the make.

But then if you run the executable and you type "credits", you get a seg fault on the call to parse()

<img width="669" alt="Screen Shot 2022-05-23 at 5 49 16 AM" src="https://user-images.githubusercontent.com/96360414/169803499-1ba97d91-6b27-4722-941a-733bedfa87dd.png">

<img width="495" alt="Screen Shot 2022-05-23 at 5 50 24 AM" src="https://user-images.githubusercontent.com/96360414/169803662-b06b077c-08b3-4c75-9688-f6ce0d0cc73a.png">

**Comment by bzeng6** [comment]
So now I've just made it so inputting "credits" functions exactly as credits_operation does, but now I'm not sure how to proceed. Should the next step be to call operations_c functions straight from the sandbox, or to make the sandbox functions create arrays of tokens?

**Comment by bzeng6** [comment]
Oh, also I added parser-bison.c to the CMakeFiles.txt file in sandbox directory in build.

**Comment by bzeng6** [comment]
I created a function handle_cmd that takes any phrase words_ll and tokenizes it into an array of strings (like parse in parser.c). The screenshot demonstrates that it puts every word from input into the array, as it prints out the items in the array as they are initialized. I'm a bit confused why it's able to take more than 4 strings, though.

<img width="416" alt="Screen Shot 2022-05-23 at 6 54 09 AM" src="https://user-images.githubusercontent.com/96360414/169813695-cd9360f2-df72-4ed0-b490-da1e9caa600c.png">

**Comment by bzeng6** [comment]
I updated the code to make sure it only stores up to TOKEN_LIST_SIZE number of strings, and if the input has more than TOKEN_LIST_SIZE number of strings, it returns NULL (like current grammar). We can see if we can make TOKEN_LIST_SIZE a larger number, maybe like 15?

**Comment by katyashchukina** [comment]
I have added the kind 3 and kind 4 commands and gotten them working! Next step is to generalise the commands to each kind of instruction rather than having separate functions for each command.

**Comment by katyashchukina** [comment]
Brianna and I have ran into an issue where it takes 2 in puts for it to register? 
<img width="212" alt="Screenshot 2022-05-27 at 20 41 47" src="https://user-images.githubusercontent.com/54959846/170804896-d85d651d-ee26-4c73-aa1c-e09a6f3f0e56.png">

**Comment by katyashchukina** [comment]
We implemented the current chiventure grammar! As seen in the demo, it now works with all prior commands, therefore we are closing this issue. We set up the commands to be recognised by kind, making it easier to add new commands. The code is currently in cli/sandbox branch in src/cli/sandbox, and includes the .l , .y , .c , .h file and a Makefile!

**Comment by jacknugent1529** [comment]
Issue Score: Excellent

Comments: Excellent work on this issue! It's really cool to see bison work in this way and it has a lot of potential to improve chiventure. The updates are great overall, although if you bring up a question or issue, be sure to address it in a future update.
