### ISSUE TITLE
Design a module for an easier interface for Custom Scripts

### ISSUE THREAD

**Issue by RamarkoB** [uchicago-cs/chiventure#1330]
Custom-scripts currently supports the usage of Lua scripts for more complicated actions in chiventure. We want to design an module that abstracts away the rest of custom scripts to make easier for other teams and game authors to integrate custom scripts into their own work. 

Hopefully, this will prevent information leakage and make it easier to use custom scripts

**Comment by RamarkoB** [comment]
After further research into this issue, it seems that an easier to understand interfacing module is not necessary. What was missing was better documentation of the conceptual understanding of the actual functions used in custom scripts. As of right now, all that is necessary is adding a page to the Wiki to make understanding the functions in custom scripts easier to understand

**Comment by RamarkoB** [comment]
The Updated Wiki page with documentation is available [here](https://github.com/uchicago-cs/chiventure/wiki/Custom-Scripts-~-Using-Custom-Scripts). Closing This issue for now

**Comment by ecoble** [comment]
Issue Score: Excellent

Comments:
Nice job creating documentation and pivoting on this task when you realized there was a different need.
