### ISSUE TITLE
cli: associate words in quotes into a single item (token)

### ISSUE THREAD

**Issue by milesgardner** [uchicago-cs/chiventure#1334]
Currently, there is a limit of four tokens per input, which limits the possible inputs. While there is no need for it right now, we want to be able to say, for example, go to "ring of fire", and have that be counted as three tokens instead of five. This will allow for more tokens, but also for games to have special names beyond north, south etc... We edited the current parsing framework such that if the command line input contains something in quotes, whatever is inside is considered its own token, no matter how many words are inside.

Assignees: Miles, Matteo

**Comment by milesgardner** [comment]
After doing more research on creating separate tokens with the delimiter of quotation marks, we've realized that it is not possible with strtok in C.  Instead, we decided it may be more effective to turn items within < and > into one token.

This would likely have to be noted in the chiventure readme, as it is important to note for the user

**Comment by milesgardner** [comment]
After second look, it may be possible to delimit the tokens with ' instead of ".

**Comment by mrestuccia1** [comment]
We figured out it was possible to use '/"' to delimit the string inside, and so our efforts were successful. We will be editing the parse function in the chiventure/src/cli/scr/parser.c, to allow it to take multiple words as a single item when they are grouped inside of quotes.

**Comment by mrestuccia1** [comment]
We used strtok() separately, once populating an array with tokens separated by a ' ' character, and once populating another array with tokens separated by the '\"' character. Afterward, we went through and checked for NULL characters in the array of tokens separated by ' ', and once we found a NULL spot we inserted into this spot the token we found in between the two double-quotes. This allows for us to use double quotes to associate different words into a single item, whereas they would have been counted as individual tokens before. This assumes that air quotes are not used at the very beginning, as this will not work, but could easily be implemented. The comment below will contain all the relevant code.

**Comment by mrestuccia1** [comment]
`char **parse(char *input)
{

    if(strcmp(input, "") == 0)
    {
        return NULL;
    }

    case_insensitize(input);

    char **words;
    words = (char**)malloc(sizeof(char*)*TOKEN_LIST_SIZE);
    char **temp;
    temp = (char**)malloc(sizeof(char*)*TOKEN_LIST_SIZE);

    //Initializes all words to NULL
    for(int i = 0; i < TOKEN_LIST_SIZE; i++)
    {
        words[i] = NULL;
    }

    char *token2 = strtok(input, "\"");
    int pos = 0;

    for(int i = 0; i < 4; i++)
    {

        temp[i] = token2;
        token2 = strtok(NULL, "\"");

    }

    char *token = strtok(input, " ");

    for(int i = 0; i < 4; i++)
    {

        words[i] = token;
        token = strtok(NULL, " ");
     
    }

    for (int j = 0; j < 4; j++) {
        if (!(words[j])) {
            words[j] = temp[1];
            break;
        }
    }


    //If there are more than 4 words, parser returns NULL and does not attempt
    //to pass the first four words as tokens
    if(token != NULL)
    {
        return NULL;
    }

    return words;
}`

**Comment by mrestuccia1** [comment]
We added comments and functionality for the quotes to be at the beginning of the input, provided that only one pair of quotes is present. Below is the updated relevant code:

`/* See parser.h */
char **parse(char *input)
{

    if(strcmp(input, "") == 0)
    {
        return NULL;
    }

    case_insensitize(input);

    char **words;
    words = (char**)malloc(sizeof(char*)*TOKEN_LIST_SIZE);
    char **temp;
    temp = (char**)malloc(sizeof(char*)*TOKEN_LIST_SIZE);
    char **temp2;
    temp2 = (char**)malloc(sizeof(char*)*TOKEN_LIST_SIZE);

    //Initializes all words to NULL
    for(int i = 0; i < TOKEN_LIST_SIZE; i++)
    {
        words[i] = NULL;
        temp[i] = NULL;
        temp2[i] = NULL;
    }

    char *token2 = strtok(input, "\"");
    int pos = 0;

    //Populates temp array with tokens separated by " character
    for(int i = 0; i < TOKEN_LIST_SIZE; i++)
    {

        temp[i] = token2;
        token2 = strtok(NULL, "\"");

    }

    //If the first character of the input is not "
    if (input[0] != '\"')
    {
        char *token = strtok(input, " ");

        //Populates words array with tokens separated by space (" ") character
        for(int i = 0; i < 4; i++)
        {

            words[i] = token;
            token = strtok(NULL, " ");


        }

        // iterates through words array until it finds a null, inserts the temp value
        // corresponding to words in between the two quotes ("example"). This assumes
        // only one pair of double quotes is used
        for (int j = 0; j < TOKEN_LIST_SIZE; j++) 
        {
            if (!(words[j])) 
            {
                words[j] = temp[1];
                break;
            }
        }

        //If there are more than 4 words, parser returns NULL and does not attempt
        //to pass the first four words as tokens

        if(token != NULL)
        {
        return NULL;
        }

        return words;

    //If the first character of the input is "
    }else{

        // tokenises using spaces the contents between the two airquotes
        // which have already been tokenized into temp array.
        char* token3 = strtok(temp[0], " ");

        //Populates temp2 array with tokens separated by space (" ") character
        for(int i = 0; i < TOKEN_LIST_SIZE; i++)
        {

            temp2[i] = token3;
            token3 = strtok(NULL, " ");

        }

        //If there are more than 4 words, parser returns NULL and does not attempt
        //to pass the first four words as tokens

        if(token3 != NULL)
        {
        return NULL;
        }

        return temp2;
    }

}`

**Comment by milesgardner** [comment]
This has been merged into dev and all code is complete.  Unit tests are complete as well.

Matteo and I plan on building upon this framework, allowing for quotes within quotes in the future. For this pull request, Matteo worked on the implementation and I worked on adding testing for it.

**Comment by mrestuccia1** [comment]
After fixing suggestions and concerns from Faruk and Jack: The updated, and final code that was merged by Jack into dev is:

`char **parse(char *input)
{

    if (strcmp(input, "") == 0)
    {
        return NULL;
    }

    case_insensitize(input);

    char **words;
    words = (char**)malloc(sizeof(char*)*TOKEN_LIST_SIZE);
    char **by_quotes;
    by_quotes = (char**)malloc(sizeof(char*)*TOKEN_LIST_SIZE);


    //Initializes all words to NULL
    for (int i = 0; i < TOKEN_LIST_SIZE; i++)
    {
        words[i] = NULL;
        by_quotes[i] = NULL;
    }

    char *token_quotes = strtok(input, "\"");

    //Populates by_quotes array with tokens separated by " character
    for (int i = 0; i < TOKEN_LIST_SIZE; i++)
    {

        by_quotes[i] = token_quotes;
        token_quotes = strtok(NULL, "\"");

    }

    //If the first character of the input is not "
    if (input[0] != '\"')
    {
        char *token = strtok(input, " ");

        //Populates words array with tokens separated by space (" ") character
        for (int i = 0; i < 4; i++)
        {

            words[i] = token;
            token = strtok(NULL, " ");
 
        }

        // iterates through words array until it finds a null, inserts the by_quotes value
        // corresponding to words in between the two quotes ("example"). This assumes
        // only one pair of double quotes is used
        for (int j = 0; j < TOKEN_LIST_SIZE; j++) 
        {
            if (!(words[j])) 
            {
                words[j] = by_quotes[1];
                break;
            }
        }

        //If there are more than 4 words, parser returns NULL and does not attempt
        //to pass the first four words as tokens

        if (token != NULL)
        {
            return NULL;
        }

        return words;

    //If the first character of the input is "
    }
    else
    {
        
        char* token;
        int len = strlen(input) - 1;
        // tokenises using spaces the contents between the two airquotes
        // which have already been tokenized into by_quotes array.
        words[0] = by_quotes[0];


        if (input[len] != '\"') 
        {
            
            token = strtok(by_quotes[1], " ");

            //Populates words array with tokens separated by space (" ") character
            for (int i = 1; i < TOKEN_LIST_SIZE; i++)
            {

                words[i] = token;
                token = strtok(NULL, " ");

            }
        
        }
        else
        {
            words[1] = NULL;
        }

        //If there are more than 4 words, parser returns NULL and does not attempt
        //to pass the first four words as tokens

        if (token != NULL)
        {
            return NULL;
        }

        return words;
    }

}`

**Comment by jacknugent1529** [comment]
Issue Score: Excellent

Comments: Excellent work on this issue! Nice job updating the issue with your progress. However, it's not necessary to include all the code you changed. If there's a particular line that's relevant (since it represented a major development, was a source of confusion, etc.) that's fine, but reviewing the entire code is done in the PR.
