### ISSUE TITLE
rpg-skilltrees: implement conditionals (based on design doc)

### ISSUE THREAD

**Issue by nbilaver** [uchicago-cs/chiventure#1335]
team members: Kabir, Nikola, Chelsea

Work on implementing conditional skills using the groundwork laid for complex skills, and using dummy readers, as that will be solved in a different task.

**Comment by KabirDubey** [comment]
The following functions related to conditional skills were implemented and pushed to the branch:
1. Changed old complex_skill new, init, free functions to use reader.
2. Create dummy new, init, free functions for reader.
3. Create execute_conditional function.

All that remains is to write tests.

**Comment by jacknugent1529** [comment]
Issue Score: Satisfactory

Comments: It looks like you did great work implementing and writing tests based on the pull request. However, you should be a bit more descriptive both in writing the summary of the task and the updates in order to better describe your progress.
