### ISSUE TITLE
cli:  implement basic synonyms based on current wiki design document using Bison in sandbox

### ISSUE THREAD

**Issue by majorsylvie** [uchicago-cs/chiventure#1336]
team members: Brianna, Faruk, Kate

IN THE SANBOX BRANCH/directory, get bison to take in a single string input and output an adjusted string list where the synonym has been turned into some other command

eg: the string: "move south" gets processed into "go" "south"

**Comment by bzeng6** [comment]
There is actually an already-existing function in operations.c that makes two words synonyms of each other. It makes use of a CLI context struct cli_ctx_t. cmdlist.h contains a struct of a linked list of command strings and cmd.h contains a hashtable struct of action entries, both of which are used in the context struct.

**Comment by katyashchukina** [comment]
The command Brianna is talking about is name_operation which looks like this:

char *name_operation(char *tokens[TOKEN_LIST_SIZE], chiventure_ctx_t *ctx)
{
    case_insensitize(tokens[1]);
    case_insensitize(tokens[2]);
    if(find_entry(tokens[1], (ctx->cli_ctx->table)) == NULL)
    {
        return "New words must be defined using only words that are already defined!";
    }
    if(find_entry(tokens[2],(ctx->cli_ctx->table)) != NULL)
    {
        return "You can't change the meaning of a word that's already defined!";
    }
    add_entry(tokens[2],(find_operation(tokens[1],(ctx->cli_ctx->table))), (find_action(tokens[1],(ctx->cli_ctx->table))), (ctx->cli_ctx->table));
    return "The two words are now synonyms!";
}

Which adds synonyms manually. We can use a similar framework through Bison, with the steps being:
-sanitise the two inputs (known word, and synonym being added):this function should be changed to work through Bison
- check that the known word is already defined: again this can be kept the same
- check that the synonym isn't defined: also can be kept the same
- add the synonym to the hash table of action entries (ctx->cli_ctx->table): this I think will also need to use the Bison file

**Comment by bzeng6** [comment]
Using bison this would be straightforward—just match the two synonyms to the same token

**Comment by katyashchukina** [comment]
Bison grammar makes defining synonyms pretty simple. To do this, in the parser.l file you note the different version of the inputs separated by '|'.  For example: ^put|PUT { return PUT; } will recognise both put and PUT as the PUT command. This is a lot easier than the previous implementation

**Comment by majorsylvie** [comment]
since the method is simple, we've added a lot of synonyms! 
such as:
```
close,shut

take,grab 

look,where

put,place
```
among others.

these are specified in the `.l` lex file!

**Comment by katyashchukina** [comment]
We have implemented synonyms! A lot of the coding overlapped with the implement-current-grammar task , but once we did that, amending the grammar to add synonyms was a case of adding the synonyms separated by '|' to call each command in the .l file.

**Comment by jacknugent1529** [comment]
Issue Score: Excellent

Comments: Nice work on this issue! The updates are well-written and demonstrate how you resolved the issue. (One comment on the grammar itself – `^` refers to the start of a string, so, `^put|PUT` will recognize `put` only at the start of the string but will recognize `PUT` anywhere in the string. I'm not sure if this is intentional or not).
