### ISSUE TITLE
NPC: merge the npc/actions branch with dev branch and submit a pull request

### ISSUE THREAD

**Issue by junasano** [uchicago-cs/chiventure#1339]
The current npc/actions branch is over 900 commits behind the dev branch and thus does not pass the tests. Our task is to merge the two and solve potential conflicts to get the branch stable, so we can move on with implementing kind 5 and 6 functions as well as letting action management push their test file.
members: Jun, Sydney

**Comment by junasano** [comment]
Updated the NPC Action documentation to reflect some of the struct changes we had.

**Comment by junasano** [comment]
Was able to successfully merge the dev branch and npc/actions branch. However, there seems to be some issues relating to the action management structs which are not allowing the building of the tests on git hub actions. 
Will need to look further into it and perhaps consult with action management if the issue is complicated.

**Comment by junasano** [comment]
We found out that there was already an existing implementation of KIND 4, 5, 6 (was not fully complete) actions in the actionmangement branch. However, there many issues that arose while building such as circular dependencies and lots of conflicting types (which was due to a new struct called agent_t being introduced). 
The branch is now called "npc/actions_original" and we got it to build but some of the tests still do not pass since there were so many changes made in various files. 
If we were to get all of the tests to pass, the PR would be very large so we would need to figure the next steps out carefully.

**Comment by junasano** [comment]
Although the branch successfully builds, we were having trouble with having the tests pass. Therefore, we had our senior developer look into the issue.

**Comment by junasano** [comment]
After some feedback from Lily regarding getting the tests to pass, it was suggested that the PR would be too big if submitted as one. Therefore, we will be creating a new brach called npc/actions_dev where new implementations of npc-actions will be slowly transferred, while making sure the tests pass. 
Once a decent amount of work is done, a PR will be submitted. The first step is to add the agent struct (which can hold a npc or item) and modify the existing dev branch code so that the agent struct is implemented.

**Comment by junasano** [comment]
The a new union agent was successfully added and the struct game_action_effect was changed as well to account for the new agent. After tweaking many files, the branch builds and passes all the tests. 
The next step is to change functions that currently take in item_t as a parameter to agent_t instead (specifically those that will be used by both item related things as well as npc-action functions)

**Comment by junasano** [comment]
Finished changing the functions that were mentioned in the previous comments and the tests all pass. 
A PR was submitted and once approved, this issue will be closed automatically.

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this issue! The updates are very thorough.
