### ISSUE TITLE
Create Tests for game-state modules

### ISSUE THREAD

**Issue by a-matai** [uchicago-cs/chiventure#134]
Create tests for all modules using criterion:

Stages:
- Test init functions: new/add_to_list(catch all)/free
- Test struct modifying functions: move room/change health/etc.
- Test internal hashtable functions
- Test interface modifying functions

**Comment by borjasotomayor** [comment]
This has to be broken down into smaller tasks. Instead of a monolithic "write the tests" task, you should have tasks for each of the parts of your code you will be writing tests for.

**Comment by borjasotomayor** [comment]
Please remember that, in this Sprint, you should aim for fine-grained tasks with 1-2 persons each. Do not create mega-tasks without first discussing it with @lydiafilipe or with me.
