### ISSUE TITLE
Implement reader effect

### ISSUE THREAD

**Issue by anchristensen** [uchicago-cs/chiventure#1340]
This task will entail implementation of the reader effect, a supporting feature used by conditional skills (a type of complex skill) to check the state of the game, for instance whether a player has x item or if the opponent is "undead". As described in the wiki page, this implementation will inherently be limited in scope because it is extremely difficult to ensure we will cover every single condition a game developer would possibly want to check to then execute the conditional skill.  Therefore we are aiming for a broad, surface level implementation of useful conditions. Further description is available here: https://github.com/uchicago-cs/chiventure/wiki/Skill-Trees-~-The-Difficulty-of-the-Reading-the-World

**Comment by anchristensen** [comment]
Closing statement: A pull request was just created to finish this issue; we filled in the body of the functions we wrote as part of the design process, including a new, init, free, xp_up, level_up, and execute function for complex skills. Tests have also been added in a new complex_skill_test file for each of these functions.

**Comment by anchristensen** [comment]
Brief update: Please note the mention for issue 1382 was accidental, I meant to link a separate issue. For this issue (1340), a .h and corresponding .c file has been added and all of the function headers and bodies have been written. We are about halfway through writing the tests and hopefully will get the pull request in soon.

**Comment by anchristensen** [comment]
Another update: the execute functions have proved more difficult than expected (the tests weren't the issue, the functions were). Everything except the execute functions is passing the tests. We will move this issue to sprint 4 and aim to submit a pull request today for the code.

**Comment by anchristensen** [comment]
Closing statement: We implemented the reader effect as described in the opening statement--we wrote functions so that the reader effect can examine certain conditions of the world which can then be used by conditional skills (a type of complex skill) to determine if a condition is met. Specifically, this included a statistics reader for things like a player's xp, and an attribute reader for things like the player's class, or the room id. As described in the wiki page, this implementation is inherently limited in scope because we cannot ensure we will cover every single condition a game developer would possibly want to check to then execute the conditional skill. Therefore we aimed for a broad, surface level implementation of useful conditions which can be further fleshed out later. @nbilaver wrote the structs we used as well as the new, init, free, and execute functions for the stat reader, and I wrote the new, init, free, and execute functions for the attribute reader and wrote the tests. We both worked on a lot of debugging.
Further description is available here: https://github.com/uchicago-cs/chiventure/wiki/Skill-Trees-~-The-Difficulty-of-the-Reading-the-World

**Comment by jacknugent1529** [comment]
Issue Score: Excellent

Comments: Great work! The updates for this issue could be a bit more frequent and thorough (e.g. what was difficult about writing the execute functions?). The closing statements and task summary were very well done, and linking the wiki page was helpful.
