### ISSUE TITLE
GUI: enabling object image customization into the slots

### ISSUE THREAD

**Issue by cyruszzhou** [uchicago-cs/chiventure#1341]
The raylib codes we adapted originally seemed to be incompatible with texture renderings and customizable inventory object images. I decided to help with this issue (though I am not mainly responsible for this module) to 1) enable unloading; 2) empower flexible texture rendering; and 3) keep sizes matched.

**Comment by cyruszzhou** [comment]
I successfully recoded parts of the inventory module. Mainly, I adjusted the parts for loading image, loading texture from image, resizing image, drawing rectangles, keeping track of slots' positions and sizes, and rendering textures. I also removed some redundant codes.

**Comment by cyruszzhou** [comment]
The issue is currently closed. Please refer back to the main sprint-3 task on inventory_graphics for future updates.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great work, but I would have liked the summary to expand a bit more on what those three aspects are. Specifically explaining what unloading and texture rendering are would be helpful.
