### ISSUE TITLE
dsl: implement grammar of NPC dialogue graphs

### ISSUE THREAD

**Issue by awliu2** [uchicago-cs/chiventure#1343]
NPC dialogue is stored as a graph. We want to be able to represent these graphs in our DSL file, which requires us to implement the grammar rules and the parsing of the grammar rules.

**Comment by awliu2** [comment]
Design document is [here](https://docs.google.com/document/d/1aq3eS4vwEB0Agioyb8GoEEdNdueOPAV1j1sxQsdfVTQ/edit?usp=sharing)

**Comment by awliu2** [comment]
We have decided to first focus on just implementing the graph itself, and we will save the implementation of dialogue conditions and actions (i.e you must have a certain item in your inventory to reach some of the nodes) for a later project.

**Comment by alexlee0422** [comment]
We defined the grammar in the dsl_grammar.lark file for NPCs based on the design docs we linked above. More specifically, we added dialogue, node , edge with their respective grammar we defined. It seems as what we have now could work but we are not entirely sure and need it to be checked/looked over.

**Comment by alexlee0422** [comment]
We also implemented the recommendation to include the dialog description at the bottom of each dialogue node after the list of edges that it is connected with. This is just to prevent a large cluster of texts before the edges and to make the format easier to read.

For example:
NODE 1 “Hello ASH. How are you?”
	EDGE 1 TO 2 desc: “Good” 
	EDGE 1 TO 3 desc: “I have an ENCYCLOPEDIA that belongs to you.” 	
EDGE 1 TO 4 desc: “I’ve caught the PIDGEY you asked for!” 

Becomes:
NODE 1
	EDGE 1 TO 2 desc: “Good” 
	EDGE 1 TO 3 desc: “I have an ENCYCLOPEDIA that belongs to you.” 	
EDGE 1 TO 4 desc: “I’ve caught the PIDGEY you asked for!” 
desc: “Hello ASH. How are you?”

**Comment by alexlee0422** [comment]
We identified and changed the grammar for NPC dialogue graphs so that it is easier to implement and clearer in formatting. We also implemented the grammar in the dsl_grammar.lark file in src/dsl/grammars for NPCs and its respective elements (dialogue, node, edge). Our goal for our next task is to potentially implement conditions and actions of the NPC such as the items in their inventory.

Our final grammar definition is as follows:
```
NPC OAK IN Pallet Town
    Short desc: “Kanto’s premier Pokemon expert”
    Long desc: “Enjoys exploring human-Pokemon relationships”
    Age: “25”
    Gender: “Male”
    ITEM CHARMANDER
    ITEM SQUIRTLE
ITEM BULBASAUR
ITEM POKEBALL
DIALOGUE: 
NODE 1
    EDGE 1 TO 2 desc: “Good” 
    EDGE 1 TO 3 desc: “I have an ENCYCLOPEDIA that belongs to you.”     
EDGE 1 TO 4 desc: “I’ve caught the PIDGEY you asked for!” 
desc: “Hello ASH. How are you?”

NODE 2 “Have a nice day!”
NODE 3
    EDGE 3 TO 6a desc: “I’ll take Bulbasaur.”
    EDGE 3 TO 6b desc: “I’ll take Squirtle”
EDGE 3 TO 6c desc: “I’ll take Charmander”
    desc: ”. . . Would you like a Bulbasaur, Squirtle, or Charmander?”

NODE 4 desc: “ Wonderful, you’re on your way . . . to complete your journey.”
NODE 6a desc: “Here is your Bulbasaur. . .”
NODE 6b desc: “Here is your Squirtle. . .”
NODE 6c desc: “Here is your Charmander. . .”
```

The associated pull request can be found here:
https://github.com/uchicago-cs/chiventure/pull/1410

**Comment by awliu2** [comment]
The pull request associated with this issue is #1410

**Comment by awliu2** [comment]
This issue has been closed. As we were implementing the grammar, the design changed slightly to ensure that everything compiles.
Below is the finalized grammar we are using:
```
npc: _NL "NPC" id "IN" location property* inventory dialogue
    | _NL "NPC" id  property* inventory dialogue
    | _NL "NPC" id "IN" location property* inventory
    | _NL "NPC" id "IN" location property*

inventory: _NL "INVENTORY" property*


dialogue: _NL "DIALOGUE" node*

node: _NL "NODE" id edge* property

edge: _NL "EDGE" id "TO" id property

phrase: (STRING+ | NUMBER)
```
Note that phrases have now been changed to be either STRING+ or a number. This allows us to label nodes and edges with numbers instead of alphanumeric strings.

An example of an NPC, with dialogue, in the DSL is given below:
```
NPC OAK IN room B
  short desc: "Kanto’s premier Pokemon expert"
  long desc: "Enjoys exploring human-Pokemon relationships"
	age: "25"
	gender: "Male"

  INVENTORY
    item_id1: "CHARMANDER"
    item_id2: "SQUIRTLE"
    item_id3: "BULBASAUR"
    item_id4: "POKEBALL"
      
  DIALOGUE
    NODE A
        EDGE 1 TO 2 
          desc: "Good" 
        EDGE 1 TO 3 
          desc: "I have an ENCYCLOPEDIA that belongs to you."
        EDGE 1 TO 4 
          desc: "I’ve caught the PIDGEY you asked for!"
        desc: "Hello ASH. How are you?"
    NODE B
    ...
```

**Comment by jacknugent1529** [comment]
Issue Score: Excellent

Comments: Great work on this issue! The comments are detailed, and the additional comment describing later changes prevents confusion for future teams. As mentioned before, use wiki pages for design documents rather than google docs.
