### ISSUE TITLE
dsl: make a design document for quests (grammar and wdl conversion)

### ISSUE THREAD

**Issue by awliu2** [uchicago-cs/chiventure#1344]
We want the dsl tool to support the quests provided by the quest module. As such, we will need to devise and specify grammar rules as well as design the conversion rules from lark tree to WDL json format. Also, look into whether the quests team has used the libobj library described [here](https://github.com/uchicago-cs/chiventure/wiki/Accessing-data-in-a-JSON-WDL-file)

**Comment by awliu2** [comment]
Created a document to draft out ideas [here](https://docs.google.com/document/d/1zTgqiiFw44DPD6rAPXb_14TJ_iWqHgxium3iavruZQk/edit?usp=sharing). It appears that the quest team has yet to specify a WDL representation of quests, however we can still design grammar rules so that future implementation of quests in the DSL is possible.

**Comment by awliu2** [comment]
Just had a meeting with the quests team. It looks like they are planning to refactor the entirety of the quest struct. As such, I do not believe that it would be a good idea to continue with this task, at least not until they finish refactoring their code and reorganize the way that quests, missions, quest requirements, etc are represented.


For future reference, here are the ideas we discussed, and the grammars we considered.

Quests are made up of a tree of tasks
A task is composed of a mission and a reward

**Types of missions**
_Passive Mission_
Reach a health, xp, level milestone
_Active Mission_

- Collect an item
- Meet an npc
- Kill an npc
- Visit a room

Task rewards can be xp, items, or both
Tasks have stat requirements, hp, level, or both

A task is a struct containing a mission and a reward, as well as a task id

Below would be an example of a task tree

Task Tree:
```
Find the chest
    Req: Level 1
    Active Mission: Collect the gun
    Reward: 50 xp
    Kill the wolf
        Req: 200 hp, level 2
        Active Mission: kill the wolf
        Reward: 100 xp, rare claws
        Task 2 A, Wolf Killed
            Req: Level 5
            Active Mission: give claws to scientist
            Reward: Rare coat
            Quest Ends
        Task 2 B, Wolf not 
            Req: Level 5
            Active Mission: report to scientist
            Reward: none
            Quest Ends
            Failed Quest
```

**Comment by awliu2** [comment]
whoops, clicked the wrong button. This issue should remain closed.

**Comment by awliu2** [comment]
Clicked the wrong button. This issue should remain closed.

**Comment by jacknugent1529** [comment]
Issue Score: Excellent

Comments: Nice work looking into this! Even though it wasn't possible to produce a design document, you were able to summarize your ideas well, which will be helpful for someone looking at this in the future. I know this has been mentioned before, but google docs are generally not the appropriate tool when working with github. Instead, try to use wiki pages and issue updates to create discussions that anyone can view and also act as documentation.
