### ISSUE TITLE
Redesign quest missions

### ISSUE THREAD

**Issue by JSerf02** [uchicago-cs/chiventure#1347]
Quest missions currently don't function to the point where they should never have been approved. The current mission structure uses a union of pointers to passive and active mission structs, but this makes it so it is impossible to tell which type of mission is active at a given time and, therefore, impossible to safely dereference any of the pointers. We need to redesign this struct so it is actually possible for a function to check whether a mission is complete. This issue should cover creating and documenting the redesign in a Wiki.

**Comment by JSerf02** [comment]
We created a [Wiki](https://github.com/uchicago-cs/chiventure/wiki/Quests-~-Redesign-Missions) documenting our redesign earlier today and I just finished adding explicit code references to make it easier to tell what we need to edit when we implement these changes.

**Comment by JSerf02** [comment]
We have finished redesigning missions and we documented the redesign in this [Wiki](https://github.com/uchicago-cs/chiventure/wiki/Quests-~-Redesign-Missions).

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great job, next time adding a quick explanation about what you added to the wiki during the update would be helpful.
