### ISSUE TITLE
Implement quest mission redesign

### ISSUE THREAD

**Issue by JSerf02** [uchicago-cs/chiventure#1348]
Once we finish creating the mission redesign, we need to add it to the quest module and adjust all other functions and tests accordingly

**Comment by JSerf02** [comment]
Added in the new structs and modified the functions so everything will work (for more detailed info, see this [Wiki](https://github.com/uchicago-cs/chiventure/wiki/Quests-~-Redesign-Missions)). Still need to add new tests, especially since removing passive missions brought us down to 26 tests!

**Comment by Castel-Jaloux** [comment]
Tests have been added and verified for functions that relate directly to the mission struct itself. All of those tests pass.

**Comment by JSerf02** [comment]
Mission redesign is properly implemented and tested. We will close this issue now, though we still have to wait for the prereq system pull request's acceptance before we can submit a pull request for these changes.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great work on this issue -- straightforward but important nonetheless.
