### ISSUE TITLE
quest/Refactor quest_state

### ISSUE THREAD

**Issue by jakeziqiwei** [uchicago-cs/chiventure#1349]
The current quest_state.c is not the best and it is really confusing for people to understand the data structs and code. We will be refactoring it to make it more user friendly.

**Comment by jakeziqiwei** [comment]
All the files have been properly refactored. Currently trying to figure out cmake with Philp

**Comment by elizabethli31** [comment]
Properly refactored everything in dev to the new modules task, prereq, quest, quests_hash, and quests_state. Updated cmake files to include these new modules. Currently merging with the add_status_enum branch which is creating some syntax errors that will need to be fixed

**Comment by elizabethli31** [comment]
Properly merged with the add_status_enum branch and included samples module which is used to create samples for testing. In this issue, we changed the quests feature from having two modules (structs and functions) to six modules (prereq, task, quest, quests_hash, quests_state, and samples) which are each elements of the quest feature and hold both structs and functions. We also changed the cmake files and dependencies in game-state modules (player.h and game.h)

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great work, but I would have liked to see a more detailed summary explaining what was difficult about the original code and what you intended to refactor.
