### ISSUE TITLE
Tests for Game Module

### ISSUE THREAD

**Issue by a-matai** [uchicago-cs/chiventure#135]
Write criterion tests for all functions in our game module to ensure they are working and make necessary changes to functions that are broken.

**Comment by jessxia** [comment]
Updated game tests to reflect the added start_desc field in the game struct, which contains a string description to be given at the start of the game (per WDL's request). Most game module functions now have tests. Add_player_to_game() and add_room_to_game() not yet done.

**Comment by jessxia** [comment]
Fixed the get_player() function to match the find_room() function (uses HASH_FIND not HAS_FIND_STR). Also added comments for each test. All changes are being made on game-state/dev rather than game-state/game-tests.

**Comment by a-matai** [comment]
This issue was mostly writing a lot of testing, working out bugs, making sure our functions were, well, functional.

Key changes:
- updated game_new();
- changed move_room to return int for SUCCESS/FAILURE
- worked out bugs in HASH_FIND functions (removed add_*_to_hash functions)
- added lots of tests!

**Comment by lydiafilipe** [comment]
Issue Score: ✓

Comments:
Good work! I would have liked to see a bit more detail in the progress updates (e.g., which game module functions did you add tests for, what were the bugs you found/fixed). It also seemed that there were quite a few commits before your first progress update, it would have been good to have more granular ones before.
