### ISSUE TITLE
Static Game Autogeneration: Brainstorming/Design

### ISSUE THREAD

**Issue by williamhu314** [uchicago-cs/chiventure#1351]
In this issue, we aim to begin developing functions that can generate an entire game given a few parameters including the roomspecs that will be used, the number of rooms the author would like to create, and an adjacency matrix providing information about how similar different roomspecs are. 

Subtasks include:

1, Determining which helper functions we will be using.
2. Determining any additional helper functions or adjustments to structs that we may need.
3. Completing the header and shell for the function.

Note that as of now, the function we are planning to implement will create a bare-bones game without any items, keys, levels, quests, battles, etc. The only thing automatically generated will be the rooms and the paths connecting them. Once this function is finished we can start thinking about adding addition autogeneration features.

**Comment by williamhu314** [comment]
We are thinking about putting the game autogeneration functions in a separate game_generate module that only contains functions that the game author would want to use.

We plan on adding a static_game_autogenerate and dynamic_game_autogenerate function to this module and may add additional ones later. 

This will hide the complexity of all the other functions and algorithms that we have in the autogenerate module.

**Comment by williamhu314** [comment]
I think that for this function we can have a starting room, either picked by the game author or generated randomly. We can then use a recursive method to, for every room, generate new rooms in all the directions where there is not currently a room. This will continue until we have generated enough rooms (enough will be based on how many rooms the game author wants).

For example, let's say we start with a room with coordinates (0,0) at the origin. let's say the author wants 121 rooms. We can call room_autogenerate once to make a room east of the current room, then call static_game_autogenerate on the new room. We can keep doing this until we have either the x-coordinate or y-coordinate equal to 10, at which point we will be more restricted in the direction for which new rooms can be created (we will have a room at each coordiante in the rectangle created by  (-10,-10) and (10,10)). 

The only issue with this design is determining what the roomspec of the current room was. To deal with this we might want a hashtable called something like room_spec_hash that has the room_id as the key and that provides the room_spec of that room. Another option would be to somehow save the roomspec when making the room and using the fact that we are using recursion to our advantage, but I think the former method is better since it also will work for creating a dynamic game.

**Comment by williamhu314** [comment]
A new idea we have come up with is to use a coord struct that denotes the coordinates of the room and has a field for the name of the roomspec of the room,. This will allow us to find the roomspec of a coord struct easily. We can then have a field in each coord struct denoting the other coords that are connected to it with a path. Once all the coords are autogenerated, we can easily generate the actual rooms and paths from the coord structs.

**Comment by lukasg8** [comment]
We will work on the room to roomspec functionality mentioned above by William on issue #1392

**Comment by williamhu314** [comment]
As we noted in #1374, we are changing our design and will put the coordinate and roomspec information inside the room struct. 

As we have completed our brainstorming, we will now complete the header for this function. We expect the function to take the following inputs:

1. A gencontext struct (that includes all the specgraph and roomspec information)
2. The number of rooms the game author would like the game to contain

The function will output a pointer to a game struct that contains all the rooms and paths that were autogenerated. 

We will also create a new game_autogenerate module for this and the dynamic game generating function.

**Comment by rohandeme** [comment]
We created a new branch called openworld/game_autogenerate. In this branch, we added a header file called game_autogenerate.h in the openworld module, where we wrote a skeleton function for the function that statically autogenerates a game. We also edited the original parameters to include a pointer to game_t  and output an integer that indicates the success of the autogeneration.

**Comment by lukasg8** [comment]
After looking reviewing the function roomspec_autogenerate, we decided we need to modify it to implement percentage based generation to fully utilize our adjacency matrix in our specgraph struct. 

We will implement functionality which considers the edges in a row all at once using percentages to fairly represent the relationships between the roomspec and the rest of the roomspec list in issue #1546

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Another exemplary issue -- great work!
