### ISSUE TITLE
Openworld - Design code for loading Openworld Attributes from WDL files

### ISSUE THREAD

**Issue by rohandeme** [uchicago-cs/chiventure#1352]
For the next step in a three stage process of making Openworld WDL-compatible, we will be designing the code for loading/generating Openworld structs from a WDL file. This will involve the following: 
1. Creating header and c files named load_openworld in the WDL module. 
2. Writing skeleton functions that gather data from the WDL file and create openworld data structures.  

By completing this task, we will be able to then go into actually implementing the functions that will finally allow for openworld data to be read/loaded from a WDL file.

**Comment by rohandeme** [comment]
We created a new branch called wdl/openworld, where we added the openworld.c/.h files.

**Comment by rohandeme** [comment]
Branched from the wrong branch initially, so we created a new branch called wdl/openworld2 , where we will create the load files for openworld

**Comment by rohandeme** [comment]
Wrote skeleton functions and added them to the load_openworld.c file in the wdl/openworld2 branch.

**Comment by rohandeme** [comment]
Finished creating the design for load_openworld sub-module in the wdl module. In the branch wdl/openworld2, there is now a load_openworld.c/.h files which contain functions for loading various openworld attributes into their respective structs.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great job, next time I would have liked to see inclusion of the specific functions that you wrote and any other design decisions that you had to make.
