### ISSUE TITLE
Create a design document for tests for move_t, stat_t, and battle_item_t.

### ISSUE THREAD

**Issue by nicholaswlee** [uchicago-cs/chiventure#1356]
This will need to be able to test the following things:
- Physical Attack vs Magical Attack
- Further testing on accuracy and critical hits
- SP usage and running out of SP
- Stat-changing moves
- Surrender Level Actions

**Comment by nicholaswlee** [comment]
Here are some tests to consider adding so we do not forget in the future:

Moves:
- Moves that do physical damage
- Moves that do magical damage
- Moves that consume SP
- Moves that change stats of a user
- Moves that change stats of an opponent
- Moves that change both stats of a user and a opponent
- Moves that change both stats and do damage

battle_item_t:
- Items that change other user stats
- Items that change other opponent stats

battle_equipment_t:
- Setting all equipment NULL
- Setting some equipment NULL and others not to observe stat change

A lot of battle_print.c tests should also be conducted i.e. for crits, misses, stat changes, etc.

There are many other tests that can/should be considered but these are some of the key things that are not tested at all.

**Comment by nicholaswlee** [comment]
Fatimah and I are meeting to create the design document. We are looking through each file to see what tests need to be made.

**Comment by corian-jal** [comment]
Nicholas and I have created the design document [here](https://github.com/uchicago-cs/chiventure/wiki/Battle-~-Test-~-Moves-~-Items-~-Equipment-~-Design-Document) listing all of the tests that need to be created or updated in each module. The next step is to actually implement these test updates, which we can begin immediately.

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this issue! Status updates on an issue should have something tangible to share.
