### ISSUE TITLE
Implementing and writing tests for new specgraph functions (new, init, and free)

### ISSUE THREAD

**Issue by williamhu314** [uchicago-cs/chiventure#1357]
In this issue, we aim to implement specgraph_new, specgraph_init, and specgraph_free functions and also create new tests for these function in the test_structs.c file.

**Comment by williamhu314** [comment]
We finished writing headers for and implementing the new, init, and free functions. We are now working on writing the tests.

**Comment by rohandeme** [comment]
Finished writing the tests for specgraph init, free, and new functions. We also changed the the new function so that only static implementation is used.

**Comment by rohandeme** [comment]
Finished writing the tests for specgraph init, free, and new functions. We also changed the the new function so that only static implementation is used.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
A relatively straight forward issue, well done.
