### ISSUE TITLE
sound: fix the sandbox file path issues

### ISSUE THREAD

**Issue by jiaoboxuan** [uchicago-cs/chiventure#1365]
Last year's team didn't push their sound files into Git and so the sandbox is a little big buggy, and I fixed that with files within the sandbox folder.

**Comment by ecoble** [comment]
Issue Score: Needs Improvement

Comments:
Good job fixing this issue! The summary here could use some fleshing out, additionally there are no updates on the issue and no closing statement summarizing the outcome of the issue.
