### ISSUE TITLE
Dynamic Game Autogeneration: Brainstorming/Design

### ISSUE THREAD

**Issue by williamhu314** [uchicago-cs/chiventure#1374]
In this issue, we aim to begin developing functions that can generate an entire game dynamically given a few parameters including the roomspecs that will be used, the number of rooms the author would like to create, and an adjacency matrix providing information about how similar different roomspecs are.

Subtasks include:

1, Determining which helper functions we will be using and how we will call them.
2. Determining any additional helper functions or adjustments to structs that we may need.
3. Completing the header and shell for the function.

Note that as of now, the function we are planning to implement will create a bare-bones game without any items, keys, levels, quests, battles, etc. The only thing automatically generated will be the rooms and the paths connecting them. Once this function is finished we can start thinking about adding addition autogeneration features.

**Comment by williamhu314** [comment]
The goal will be to use the static game generating function to first create a static game and then to create new rooms on demand whenever a player attempts to move in a direction where a room does not currently exist.

**Comment by lukasg8** [comment]
After discussion with William, we decided to add a tag to room_t struct which matches the position of the roomspec_t in the specgraph_t struct, allowing us to know from which roomspect_t the room_t was generated. This way, we can reference the specgraph while dynamically autogenerating new rooms (while the player reaches the end of the map) to make sure we only generate rooms which are allowed to be connected with each other.

**Comment by williamhu314** [comment]
As we have completed our brainstorming, we will now complete the header for this function. We expect the function to take the following inputs:

1. A gencontext struct (that includes all the specgraph and roomspec information)
2. A char* denoting the name of the roomspec the author would like the starting room to be associated with. The author will also have the option to input the char* "randomlygenerate" if they would like the first room the be automatically generated as well.

The function will output a pointer to a game struct that at first contains just the first room and that will continuously get updated as the player begins moving around within the game.

We will also create a new game_autogenerate module for this and the static game generating function.

**Comment by rohandeme** [comment]
In the openworld/autogenerate branch, we wrote a skeleton function for the function that dynamically autogenerates a game. We also edited the original parameters to include a pointer to game_t and output an integer that indicates the success of the autogeneration.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
An excellent issue!
