### ISSUE TITLE
Make and create tests for new functions to create and free coord structs

### ISSUE THREAD

**Issue by williamhu314** [uchicago-cs/chiventure#1376]
In this issue we aim to make coord_new and coord_init functions for our new coord struct. The goal is to have the coord_new function take in 2 integers as coordinates and output the coord struct. We also aim to make tests for these new functions.

**Comment by helenastc** [comment]
The functions and tests were implemented and the pull request for it has been approved and closed.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
A nice and simple issue -- well done!
