### ISSUE TITLE
sound: research and create chiventure structs needed for the sound example

### ISSUE THREAD

**Issue by jwschroeder21** [uchicago-cs/chiventure#1377]
In order to create a demo, we need to research the existing chiventure structs and determine which components would be necessary. After researching these structs, we identified the key structs and created any other structs that would be required. Then, we will create a pull request that runs a demo game before introducing sound, to make sure that we have developed a full understanding of the chiventure structs.

Assignees: Jake, Rhea

**Comment by jwschroeder21** [comment]
There is a sample_game.h file that creates a sample 1 player 2 room game struct. The file includes "game-state/game.h". Maybe we can use this to build our sound example into?

**Comment by jwschroeder21** [comment]
There are test_game.c, test_item.c, test_room.c, and test_validation.c files that validate the building of a game.

**Comment by jwschroeder21** [comment]
Looking at some of the other teams examples, there are instances where the NPC team created an entire game that demonstrated a conversation and there are instances where they only used the convo_t structs necessary for the demo. For our case, would it be more beneficial to build an entire game before demonstrating sound, or simply to just jump into sound using the appropriate structs?

**Comment by jwschroeder21** [comment]
I am sitting with Rhea right now, we just drafted a pull request that we will submit shortly for this issue.

**Comment by jwschroeder21** [comment]
Update: we submitted the pull request and are waiting for approval ! we will close this issue once the pull request has been approved.

**Comment by jwschroeder21** [comment]
Closing statement: In this issue, we researched the appropriate chiventure structs from all of the code that are necessary to building a sound example. We created a pull request that runs a demo game before introducing sound. The pull request has been submitted and went through revisions.

**Comment by ecoble** [comment]
Issue Score: Excellent

Comments:
Great job diving into the Chiventure code and updating this issue with your findings!
