### ISSUE TITLE
Fix roomgenerate tests

### ISSUE THREAD

**Issue by williamhu314** [uchicago-cs/chiventure#1385]
In this issue, we aim to create new roomgenerate tests for the roomgenerate function that accounts for the change from speclist to specgraph.

**Comment by williamhu314** [comment]
We have completed the room generate tests to account for the specgraph struct, which we pull requested in #1427

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great job, next time I would have liked to see a more thorough summary explaining what exactly needs to be changed in the tests.
