### ISSUE TITLE
GUI: making maps displayable for open-world display

### ISSUE THREAD

**Issue by cyruszzhou** [uchicago-cs/chiventure#1386]
I am trying to come up with a proper data structure and drawing algorithm that would enable the new open-world coordinate data structure. The original version of the map only supports coordinates hashed to different rooms. This would be incompatible with the coordinate struct the open world team wants to implement right now. Therefore, it would be good to unify both types of coordinates through the parser and let the top-level graphics function to only care about the location in the image/texture.

**Comment by cyruszzhou** [comment]
I have successfully enabled texture rendering for maps and represented the current position of the player with a red circle. I am currently getting coordinates from the movement of the WASD keys and arrow keys. I will try to request a pull to get this into the dev branch to directly use the "getCoord" function of the open-world team.

**Comment by cyruszzhou** [comment]
The issue is closed for now and I will wait for the permission on the pull request to update the module.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great job on this issue, straight to the point!
