### ISSUE TITLE
GUI: unifying top-level graphics data structs for all modules

### ISSUE THREAD

**Issue by cyruszzhou** [uchicago-cs/chiventure#1387]
I am trying to tweak the top-level data structs of all modules so we can have a unified protocol of implementation when we try to run all modules together. This would benefit current and future developers as now their knowledge of one module easily generalizes to all modules. This would also yield an advantage for GDL parsing, as now the parser would know exactly which fields to fill with the passed-in JSON data.

**Comment by cyruszzhou** [comment]
I have now successfully done the unification or input_box_graphics, inventory_graphics, map_grapihcs, npc_graphics, and quest_graphics. I am waiting for others to complete their modules.  I also tweaked the struct in ui_main to suit the purpose.

**Comment by cyruszzhou** [comment]
It seems like in order for all modules to be integrated, every module should be assigned a context_id  and should strictly begin with BeginDrawing(context_id) and end with EndDrawing().

**Comment by cyruszzhou** [comment]
This issue for Sprint 3 will be continued to Sprint 4.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great job splitting this issue between the two sprints and including sufficient updates!
