### ISSUE TITLE
Load a given game parsed from a WDL file into structs provided by game_structs

### ISSUE THREAD

**Issue by thoranderskow** [uchicago-cs/chiventure#139]
Parse the Game file object from a WDL file, and load into the game_t struct provided by game_structs.

**Comment by thoranderskow** [comment]
Will need function:
load_rooms(attr_list_t *rooms,  attr_list_t *all_items, game_t *g)

for each room in list, must call 
 - create_room
 - find_items_in_room(gives a list)
   - then for each item in that list, call:
      - create_item
      - add_item_to_room
 - then add the room to game with add_room_to_game.

**Comment by thoranderskow** [comment]
Created header file with one function in it.
Might combine header files with load room and load item.

**Comment by thoranderskow** [comment]
Discussed with team, function's purpose is now to create a game pointer that will be filled in using Kate and Shriya's functions.

**Comment by thoranderskow** [comment]
Will now create another function, game_set_start(char *room_id) that sets the location of the beginning of the game.

**Comment by thoranderskow** [comment]
Made a new issue, #171 to work with game-state to add functionality to structs and their provided functions.

**Comment by thoranderskow** [comment]
The changes were made, and game_set_start and create_game were adjusted.

**Comment by thoranderskow** [comment]
Functions were made correctly, with game_set_char and create_game now in wdl/load_into_structs.

**Comment by lydiafilipe** [comment]
Issue Score: ✓

Comments:
Good job with all the updates! I think the updates and closing statement could use some more details though. For example, what exact changes were made? How was game_set_start adjusted? What are Kate and Shriya's functions (if someone from outside this class were too look, they wouldn't know what that means)?
