### ISSUE TITLE
Designing Item statistic effect

### ISSUE THREAD

**Issue by arya32hub** [uchicago-cs/chiventure#1390]
Item statistic is one of the 4 main atomic effects in the effect.c file. We need to make necessary modifications and implement new functions to execute this skill. This may be tricky as most of the stats.h functions are catered towards the player.h file and not really the item.h.

**Comment by arya32hub** [comment]
Created wiki for design

**Comment by arya32hub** [comment]
https://github.com/uchicago-cs/chiventure.wiki.git

**Comment by arya32hub** [comment]
https://github.com/uchicago-cs/chiventure/wiki/Design-for-item_statistic_function

**Comment by arya32hub** [comment]
Closing statement: Overall the implementation of item_stat will be very similar to that of player_stat. There is a bit of confusion on how to go about the design of an items statistics as most of the stat hash tables seem to have been targeted and made for a player rather than an item.

**Comment by arya32hub** [comment]
Update: Implementation of Item statistics hasn't been succesful. Future implementation requires the item_t struct to be modified to accomodate a `stats_hash_t *item_stats` field. Beyond that Implementation should work if you follow the wiki.

**Comment by jacknugent1529** [comment]
Issue Score: Satisfactory

Comments: Nice work on this issue. If you need to split an issue, try to do that as early as possible in the sprint, so you can get help from other teammates in figuring out the problems.
