### ISSUE TITLE
Implemention of item_stat effects

### ISSUE THREAD

**Issue by arya32hub** [uchicago-cs/chiventure#1391]
We will implement the 3 functions discussed in the design of item statistic effects and then test to check if implementations are successful. This function is meant to alter the statistic of an item.
Check Wiki for design here: https://github.com/uchicago-cs/chiventure/wiki/Design-for-item_statistic_function
Subject to change.

**Comment by arya32hub** [comment]
completed implementation but tests are not passing

**Comment by arya32hub** [comment]
Define item stat test is crashing.

**Comment by chelseaegbarin** [comment]
Implementation is complete, and tests no longer crash but one does fail. Leaving the tests for a future sprint.

**Comment by chelseaegbarin** [comment]
The asignees met to discuss and plan and implement implementation by the way. We also all tried to debug the tests but to no avail.

**Comment by jacknugent1529** [comment]
Issue Score: Satisfactory

Comments: Nice work looking into this! However, this issue was initially split without the senior developer's approval. Additionally, the updates are brief and the closing of the issue doesn't provide the implementation.
