### ISSUE TITLE
GUI: adapting multiple window display version of raylib

### ISSUE THREAD

**Issue by cyruszzhou** [uchicago-cs/chiventure#1398]
The current version of raylib does not take multiple window display as a core feature. However, by making several changes to the raylib code itself, we can enable this function. I am currently trying to make a connection from the current program to the multiple window version raylib. (Raysan has something similar implemented but that no longer works on the current versions of OS, therefore manual modification would be necessary).

**Comment by cyruszzhou** [comment]
I have successfully pulled the whole raylib under the raylib_itself folder. I have made changes to the codebase according to a corresponding raylib issue. I am now trying to figure out a proper way to write Makefile s to make this version of raylib adapted.

**Comment by cyruszzhou** [comment]
I have cloned the raylib codes for multiwindow display and debugged the codebase itself. However, it seems like the linking files only run on MacOS with versions lower than 11.0. I plan to pull the newest codes and redo the process again.

**Comment by cyruszzhou** [comment]
I successfully modified the latest raylib codebase and got multiple windows running. The code can be seen on the graphics_sandbox_integration branch, where I experiment with modular integration. This issue is now closed.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great work on this issue!
