### ISSUE TITLE
Create testing for multiclass module functions multiclass_shortdesc() and multiclass_longdesc to test the new implementation

### ISSUE THREAD

**Issue by wellingtj** [uchicago-cs/chiventure#1402]
We will move previous bug fixes to updated version of the multiclass module, from class.h and class.c to multiclass.h and multiclass.c. Also, the implementations of multiclass_shortdesc() and multiclass_longdesc() have been updated to fix some bugs in issues #1142 and #1143 so tests for these functions must be written.

**Comment by wellingtj** [comment]
I have gotten the file going and the preliminary void functions that are necessary for testing, but I have to meet with Jonathan to get any further because I don't know the name of his branch

**Comment by wellingtj** [comment]
this is failing to compile due to some code from the openworld team apparently. I'll try to figure this out after implementing tests

**Comment by wellingtj** [comment]
We have implemented testing but we have a strange conflict with the open world code that we have to resolve. This will be a separate issue

**Comment by jroven** [comment]
Jake moved the new versions with fixed bugs of multiclass(), multiclass_shortdesc() and multiclass_longdesc() from class.h and class.c to multiclass.h and multiclass.c. Both Jake and I also implemented tests for multiclass_shortdesc() and multiclass_longdesc() in test_multiclass.c.

**Comment by wellingtj** [comment]
Multiclass_shortdesc is now working perfectly and the code is compiling. I believe there is an error in Jonathan's part of the code so I'm leaving the rest of the debugging to him

**Comment by jroven** [comment]
I finished debugging `multiclass_shortdesc()` and `multiclass_longdesc()` so all the tests are passing. Unfortunately, there is still a bug in `multiclass()` that results in an infinite loop when the function is called on something that is already a multiclass. We don't have time to debug it unfortunately so we removed the tests for this function and have made a new issue on the backlog #1608 for this.

**Comment by lilyehsani** [comment]
Issue Score: Satisfactory

Comments:
Great work! Two comments:
1. The issue was closed before it was actually done and reopened repeatedly. The appropriate time to close the issue is when the PR is merged.
2. The issue was started in one sprint, but was not completed until the next one.
