### ISSUE TITLE
Load a given item object from WDL file into game_state's structs

### ISSUE THREAD

**Issue by bansals10** [uchicago-cs/chiventure#141]
In this issue, I will be loading the updated item objects into the game_state team's item structs. These will then be loaded into the room object created in issue #140. When given one item, a game_state struct item is created.

**Comment by bansals10** [comment]
Updated wdl/load_into_structs to contain the YAML file that we will parse by the end of this sprint. It is here: src/wdl/examples/sample_yaml/simplified_wdl.yaml.

**Comment by bansals10** [comment]
Closing issue #141 after implementing load_items and load_actions. load_items calls game_state function item_new and initializes the item with an id, short desc, and long desc. We then utilize the find_room function to associate the item with the room it is located in. Because these functions depend on game_state's find_room function, we have temporarily included it in our load_items.c file, but we will remove it after their PR to master has been approved. We then add the various actions associated with an object as attributes to the item. We will modify this code in future issues to add conditions for actions.

**Comment by lydiafilipe** [comment]
Issue Score: ✓

Comments:
Good work, however you do not have enough progress updates. It looks like you made a lot of changes, and you should be documenting these as you make them.
