### ISSUE TITLE
Making room_autogenerate tests

### ISSUE THREAD

**Issue by williamhu314** [uchicago-cs/chiventure#1411]
In this issue, we aim to create tests for our newly implemented room_autogenerate function. The room_autogenerate function takes in a roomspec and a specgraph, generating another roomspec based on the adjacency matrix within the specgraph. We aim to make sure that the function can correctly generate a roomspec and that the roomspec is being determined based on the numbers in the adjacency matrix. We will consider making lots of tests covering edge cases where the adjacency matrix has only 1s and 0s to make sure the algorithm we are using works.

**Comment by lukasg8** [comment]
Went through all the tests and changed them from testing speclist_t functionality to specgraph_t functionality. The main focus was making sure to not just copy the previous tests but have them actually tests features of a adjacency matrix versus a linked list.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Brief but to the point -- well done!
