### ISSUE TITLE
Implementing static game autogeneration

### ISSUE THREAD

**Issue by williamhu314** [uchicago-cs/chiventure#1413]
In this issue, we aim to implement a static game autogeneration function that we have been designing in #1351.  The goal is to have a function that can make a game given inputs on the number of rooms needed and a gencontext struct that includes information about the roomspecs used and the adjacency matrix. Specifically, the function will have the following inputs:

1. A pointer to a game_t struct, which will be modified within the function to store the rooms and paths in the autogenerated game.
2. A gencontext struct, that will provide information on what roomspecs will be used in the game and the relationship between rooms.
3. An integer denoting the number of rooms the game author wants.

The function will modify the game_t struct and will return SUCCESS on a success and FAILURE on a failure. A failure may result if the adjacency matrix contains too many 0s and this results in a divide by zero error in our probabilities (i.e. if a room is of a roomspec where the whole corresponding row of the adjacency matrix is 0).

**Comment by williamhu314** [comment]
Our plan for this function is to allow it to choose an existing room randomly, then choose a random unused direction, and make a room in that direction. If a room already has rooms on all 4 sides of it, the algorithm will just choose another room at random until it finds a room where there are vacant adjacent spaces. We may create different static generation algorithms later, but this method seems to be best for now as it will create a very random structure for the rooms.

**Comment by williamhu314** [comment]
Here are the details of our plan for the implementation:

**First room**
1. We will pick the roomspec of the first room randomly using random_room_lookup
2. We will use the roomspec_to_room function to create the first room from the roomspec.

**Creating new rooms**
1. To create the new room, we will select the starting room randomly. We plan on doing this by making a helper function that chooses a random room from a game struct by using the hash table of rooms in the game struct.
2. We will then pick a random direction. There is currently a pick_random_direction function, but it does not suit our needs because with our new design using coordinates, it is possible that 2 rooms are adjacent but do not have a path connecting them. Thus, we will need to modify this function to pick a random direction that is not a direction with a room already occupying that coordinate.
3. If the room we chose has no open directions, the algorithm will pick another room at random and repeat this until it picks a room with an open direction.

Note: To reduce complexity in the game_autogenerate module, we will create a helper function, likely called something like random_room_and_direction that handles all the above functionality.

4. Once we have the starting room and the direction, we will extract the roomspec information from the room struct and then use the room_autogenerate function to generate a new room.

**Creating paths**

1. Whenever a new room is created, we will also create the associated paths. 
2. First, we will need to create a path connecting the current room to the new room. This is already taken care of with the room_autogenerate function
3. If the newly created room is adjacent to other rooms, we will then need to determine which additional path connections to make. We will make these connections with a probability that is based on the correlation between different roomspecs as denoted in the adjacency matrix.

Note: We will likely create a path_autogenerate helper function to handle all the path functionality.

**Additional Considerations**

1. Every time we use room_autogenerate, we will need to make sure we do not encounter a divide by zero error. I think the easiest thing to do it to incorporate the error functionality into the room_autogenerate function by allowing room_autogenerate to return FAILURE if the sum of all weights in a particualr row is 0.

2. Lots of the lower-level functionality that we want in this function overlaps with dynamic game generation. The main difference between these 2 functions will be how the game struct gets updated, but these 2 functions could definitely use the same or similar helper functions. Thus, we will be creating many helper functions for our static game autogeneration function so that we can reuse them in dynamics game autogeneration.

**Comment by williamhu314** [comment]
There are many helper functions that we need to address before we actually begin working on manipulating the inputted game struct appropriately, and this will be too much to accomplish in this issue. Thus, I have made a new issue that involves creating helper functions for static and dynamic game autogeneration in #1471. After the helper functions are implemented, the main static game generation function will just have to feed the appropriate variables into the appropriate helper functions, have a for loop that runs the process as long as needed based on how many rooms are needed, and correct return values and error handling. This will make the function very easy to understand for the game author.

**Comment by williamhu314** [comment]
The helpers are now completed. The plan is to first make the first room of the game as follows:

1. If the char* is not "pickrandomly", the function will look up the roomspec with the given name using a for loop, make the first room with roomspec_to_room and room_generate, and set the first room to have that roomspec. If the name of the roomspec is not a roomspec in the specgraph, the function will output an error.

2. If the char* is "pickrandomly" we will use the random_first_room function

Then we will make the other rooms as follows:

1. Call autogenerate_room_in_game. If the return value is -1 (indicating a failure) return an error. If the return value is 0 (indicating no open directions) call the function again until we successfully generate a room. If the return value is 1, move on to the next step.

2. Call path_autogenerate to generate the new paths that connect to and radiate out of the newly created room.

3. Continue calling the 2 above functions until the desired number of rooms has been reached.

We will also need to account for tags, which we will work on in #1526.

**Comment by williamhu314** [comment]
As an update, the path_autogenerate functionality mentioned above has actually now been incorporated into the autogenerate_room_in_game as this is the simpler implementation. Otherwise the implementation has proceeded as planned.

**Comment by williamhu314** [comment]
We have finished implementing the static game autogenerate function that creates all the rooms in a game automatically given a pointer to a game struct, a gen_context struct, the number of rooms, and the name of the roomspec of the first room. We will now test this function and the associated helper functions in #1415 and #1473.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Excellent work on this issue!
