### ISSUE TITLE
Implementing Dynamic Game Autogeneration

### ISSUE THREAD

**Issue by williamhu314** [uchicago-cs/chiventure#1414]
In this issue, we aim to implement a dynamic game autogeneration function that we have been designing in #1374. The goal is to have a function that can make a starting room and then make more rooms as the player moves around in the board on demand. These rooms will be generated based on the provided gencontext struct that includes information about the roomspecs used and the adjacency matrix. Specifically, the function will have the following inputs:

1. A pointer to a game_t struct, which will be modified within the function to store the rooms and paths in the autogenerated game.
2. A gencontext struct, that will provide information on what roomspecs will be used in the game and the relationship between rooms.
3. A char* that denotes the name of the first roomspec the game author wants the player to start at. There will also be an option to make the first room random.

The function will modify the game_t struct recursively, every time the player moves, and will run silently on a success and FAILURE on a failure. A failure may result if the adjacency matrix contains too many 0s and this results in a divide by zero error in our probabilities (i.e. if a room is of a roomspec where the whole corresponding row of the adjacency matrix is 0).

**Comment by williamhu314** [comment]
As I noted in #1351, there are many helper functions that we need to address before we actually begin working on manipulating the inputted game struct appropriately, and this is being done in #1471. These helper functions will be helpful for both static and dynamic game generation, and may also be helpful if we want to support other generation algorithms in the future.

**Comment by williamhu314** [comment]
We were unable to finish the implementation but future work could implement this function based on the plan outlined above.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great work on this issue!
