### ISSUE TITLE
Making tests for static game autogeneration function

### ISSUE THREAD

**Issue by williamhu314** [uchicago-cs/chiventure#1415]
In this issue, we aim to make tests for our new static game autogeneration function. These tests will also go into a new test file, test_game_autogeneration.c.

The tests will determine both whether the function can create a valid game without errors and whether the function can create a game based on the adjacency matrix. To determine whether to adjacency matrix is being taken into account correctly in room generation and path generation, we may use lots of edge cases where the matrix contains mostly 0s and some 1s.

We will also determine whether the function can handle errors appropriately when a particular row of an adjacency matrix is all 0s.

**Comment by williamhu314** [comment]
We have made a couple tests to make sure the function works and that it makes the correct number of games and correct roomspecs. We are now working to fix bugs in our functions since the tests are not passing.

**Comment by williamhu314** [comment]
We have finished making test for this function. Future work could include making more tests for this function.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great work!
