### ISSUE TITLE
Making tests for dynamic game autogeneration function

### ISSUE THREAD

**Issue by williamhu314** [uchicago-cs/chiventure#1417]
In this issue, we aim to make tests for our new dynamics game autogeneration function. These tests will also go into a new test file, test_game_autogeneration.c.

The tests will determine both whether the function can dynamically modify the game validly and without errors and whether the function can modify/update a game based on the adjacency matrix. To determine whether to adjacency matrix is being taken into account correctly in room generation and path generation, we may use lots of edge cases where the matrix contains mostly 0s and some 1s.

We will also determine whether the function can handle errors appropriately when a particular row of an adjacency matrix is all 0s.

**Comment by williamhu314** [comment]
We were unable to finish the implementation of the dynamic autogeneration functions but if it is implemented in the future these tests will be important.

**Comment by williamhu314** [comment]
We were unable to finish the implementation of the dynamic autogeneration functions but if it is implemented in the future these tests will be important.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great work!
