### ISSUE TITLE
dsl: create documentation for next year's group

### ISSUE THREAD

**Issue by wzeng0** [uchicago-cs/chiventure#1418]
Create a document and update the README detailing all progress (past and present) in the DSL. This should be in-depth and help others entering the codebase for the first time to get quickly up-to-speed on where the current status is. Additionally, we hope to make a second document indicating the direction next year's group can take the project. This should be a comprehensive list of all the items we hoped to work on/didn't get to, and what might be possible depending on where other teams get in developing their own aspects of the game. 

team members: Andi, William, Hira

**Comment by baigh1** [comment]
Created a preliminary document for brainstorming/organization: https://docs.google.com/document/d/1_RoKQjGd1FpDaKnpMvBDOJwe5BrgAvSMt9eikE6HX2w/edit?usp=sharing

**Comment by awliu2** [comment]
Things to do

- [x] Update the [dsl grammar page](https://github.com/uchicago-cs/chiventure/wiki/DSL-~-DSL-Grammar) with npcs, player class
- [x] make sure that all new files are fully commented and documented, standardize header comments across the board.
- [x] Add instructions for running tests to the [README.md](https://github.com/uchicago-cs/chiventure/blob/dev/src/dsl/README.md)
- [x] Add instructions for running tests to the [DSL tutorial](https://github.com/uchicago-cs/chiventure/wiki/DSL-~-DSL-Tutorial)
- [x] Update tutorial with new grammars [here](https://github.com/uchicago-cs/chiventure/wiki/DSL-~-DSL-Tutorial#what-is-currently-supported-in-the-dsl)

**Comment by awliu2** [comment]
created `dsl/documentation` branch for updating documentation. Also updated the readme in this branch.

**Comment by baigh1** [comment]
Updated the [dsl grammar page](https://github.com/uchicago-cs/chiventure/wiki/DSL-~-DSL-Grammar) with NPCs and Player Class (all sections).

**Comment by baigh1** [comment]
Updated the [Tutorial DSL](https://github.com/uchicago-cs/chiventure/wiki/DSL-~-DSL-Tutorial#what-is-currently-supported-in-the-dsl) with the new information on NPCs and Player Classes. This included created a new example with the NPCs and Player Classes implemented (both a WDL and DSL example).

**Comment by awliu2** [comment]
Looks like this task has been completed, as all the checklist items have been resolved. A pull request for the readme has also been submitted, and I'll close this issue now.

**Comment by jacknugent1529** [comment]
Issue Score: Excellent

Comments: Fantastic work on this issue! Breaking down the various aspects of the documentation and creating a checklist was a great way to approach this and ensure that the documentation is consistent.
