### ISSUE TITLE
Write GDL

### ISSUE THREAD

**Issue by csraffaga** [uchicago-cs/chiventure#1419]
The Graphical Description Language (GDL) system in Chiventure allows for game developers to customize aspects of how the game is graphically. This file is distinct from the WDL (World Description Language) file, but follows a similar JSON format for ease of use. We will devise a module to parse this information.

**Comment by csraffaga** [comment]
@imadejski and I have currently updated all that is required for the header file of gdl and have begun to implement. The module works as follows. A single read_gdl() function will take in the gdl file and fill necessary structures that other graphics modules will require! This will run through the file once over and output an initialized and completed graphics struct.

**Comment by csraffaga** [comment]
The GDL file is nearly set to go, with modular design complete and necessary new / init / free functions. The main read_gdl function is being refactored and multiple helper functions are being implemented and designed to facilitate ease of reading for future developers.

**Comment by imadejski** [comment]
The GDL module resulted in 3 pull requests that are in the process of being closed. There are tests for all of the structs that were created within the graphics struct for the news, inits, and frees. The read_gdl function is completed with tests.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great work on this issue with a good set of updates!
