### ISSUE TITLE
Update WDL validation functions for updated WDL specs

### ISSUE THREAD

**Issue by mewthew** [uchicago-cs/chiventure#142]
Our team updated the specifications for rooms (found in #129). We need to update the WDL validation functions to comply with their updates on the room object.

**Comment by mewthew** [comment]
Updates:
So far, the only thing that has been updated are the room objects. Awaiting further confirmation with the spec drafters for item objects before updating the item validation functions.

**Comment by mewthew** [comment]
Items have been validated per issue #141 and #179 to ensure items are correctly translated to game-state structs. Thus, this implementation includes only the changes indicated on the changes in the spec draft for rooms. Specifically, conditions were updated (in the spec draft), which caused the existing validation and printing functions for rooms to be updated. The YAML file has been updated according to the room specs found [here](https://github.com/uchicago-cs/chiventure/blob/wdl/improved_validation/src/wdl/src/validate.c), and the implementation for the updated room structs can be found [here](https://github.com/uchicago-cs/chiventure/blob/wdl/improved_validation/src/wdl/examples/sample_yaml/connected_rooms.yaml). 

After running `make` and `make examples` in the wdl directory, inputting `./typecheck_demo.c sample_yaml/connected_rooms.yaml` within the examples folder will output a series of successful validations/prints.

**Comment by lydiafilipe** [comment]
Issue Score: ✓

Comments:
Good work! However I think more progress updates would have been good as things were being updated, and more detail given on what exactly the updates were.
