### ISSUE TITLE
dsl: refactor `dsl_parser.py` and `to_wdl` into multiple modules

### ISSUE THREAD

**Issue by alexlee0422** [uchicago-cs/chiventure#1421]
Currently, new Chiventure features all must be added to these two files and could potentially make these files very long and convoluted in the future. Therefore, we want to divide these files into modules that are more specific to each feature, and create subdirectories for conversion to intermediate dictionary form, and for conversion from the dictionary to WDL/JSON format. (ie. NPC, rooms, items, etc.) 
team members: Jay, Alex, Andi

**Comment by alexlee0422** [comment]
We have made progress on refactoring the to_wdl module. We're going to put all code that deals with intermediate to wdl conversion in its own subdirectory, as well as move classes into their own modules to prevent the to_wdl file from getting too long.

**Comment by awliu2** [comment]
A pull request for part of this task was submitted yesterday, and we are currently going through reviewer suggestions to improve the code (i.e adding header comments, using a common definitions file, etc)
https://github.com/uchicago-cs/chiventure/pull/1456
This pull request specifically refactored the to_wdl module

**Comment by awliu2** [comment]
Making progress on refactoring the dsl_parser module in the dsl/dsl-parser-refactor branch. We've separated the utility modifiers from the game/item/action/room transformers, and separated all that from the main transformer class that operates upon the entire dsl file. We now need to make sure everything runs as expected.

**Comment by awliu2** [comment]
We've completed our pull requests and closed this issue. We now have two modules, `to_wdl` and `dsl_parser` that contain implementations conversion to json format, and grammar parsing, respectively. It is now easier to access the outward facing functions while we abstract some of the nitty gritty detail work (i.e parsing grammar) to separate files.

**Comment by jacknugent1529** [comment]
Issue Score: Excellent

Comments: Great work on this issue! The refactoring was much needed. When writing updates, try to include tangible progress or explain the motivation for refactoring in the manner you chose.
