### ISSUE TITLE
Incorporate quests into NPC dialogue and NPC struct

### ISSUE THREAD

**Issue by elizabethli31** [uchicago-cs/chiventure#1424]
We contacted NPC team last sprint and will be meeting with them to see how quests can be included in their dialogue. Our current ideas are included in the wiki page "Incorporating Quests into NPC"

**Comment by elizabethli31** [comment]
Met with the NPC team today to discuss how feasible it is to include different dialogues with quests. Currently, we are hoping to have a list of quest ids and task ids in each NPC struct along with different dialogue options. These dialogue options would only be triggered if the player has the necessary prereqs

**Comment by elizabethli31** [comment]
We debugged some of the NPC code that was giving us errors and also merged our branch, so that the functions we wrote (npc_can_give_quest and npc_can_give_task) will work with their functions. Our functions have also been merged with dev, so everything should be up to date now on our end (quests).

**Comment by sglenn-uchi** [comment]
I added WDL implementation for NPCs with dialogue within each quest and task in their list. Currently WDL files can run, I just need a way to test the new parts of the JSON that need to be parsed. I will do this by making a test .WDL file with an NPC with a list of quests and tasks with unique dialogue in each quest and task.

**Comment by sglenn-uchi** [comment]
With help from the quests team, the new functions and WDL integration are now complete. Additionally, the current WDL files all run correctly. We have opened a pull request to get these changes merged into the dev branch. When our PR is approved, this issue will close automatically.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great work on this issue, especially the many updates!
