### ISSUE TITLE
Quests: Implement WDL parsing

### ISSUE THREAD

**Issue by JSerf02** [uchicago-cs/chiventure#1426]
We have designed the WDL interface for quests. Now we need to implement it!

**Comment by Castel-Jaloux** [comment]
We have wrote all the WDL parsing functions to load quests and sub-elements of quests, as well as some basic type-checking validation functions. However, we still need to provide more thorough testing to make sure these functions work as intended. To do this, we will need to write a script to input WDL files into these functions, have the functions parse and interpret them, and print information to confirm whether or not they are transmitting the correct information.

**Comment by JSerf02** [comment]
We added a comprehensive test and WDL example file for WDL parsing that ensures every possible situation is properly accounted for.

**Comment by JSerf02** [comment]
After many hours of pain, the WDL parsing tests finally pass! If you ever have to debug WDL, I'd HIGHLY recommend using gdb (and even better, the VSCode gdb GUI).

**Comment by JSerf02** [comment]
WDL parsing functions for quests are implemented and substantially tested

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great job and good to see so many updates.
