### ISSUE TITLE
Follow up with CLI to display list of all quests player has and the task tree within a single quest

### ISSUE THREAD

**Issue by elizabethli31** [uchicago-cs/chiventure#1428]
We will need to have two functions:
- view quests to see the list of all quests that the player has
- display quest to show the task tree for each quest

**Comment by elizabethli31** [comment]
We met with the cli and action management team to figure out exactly what they need from us in order to display the quests. We decided that we want to display all the quests a player has, the task tree affiliated with a particular quest, and the components in a task. We need to write three functions that return what we want printed as a string. Also, provided cli and action management with the function headers.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
A brief but good issue! Note that next time, you should include an explicit closing statement.
