### ISSUE TITLE
Quest: Update the current implementation Wiki with the changes from this quarter and add a "issues to work on" section at the bottom"

### ISSUE THREAD

**Issue by JSerf02** [uchicago-cs/chiventure#1433]
To help future quest teams get associated with the quest module, we need to make sure our documentation is updated and makes it easy for them to find out how everything works and what they should be working on. We already have a Wiki that documents our current implementation, though we made it at the start of the quarter, so we need to update it with our barrage of changes and we need to add suggested issues to the bottom.

**Comment by jakeziqiwei** [comment]
Currently updating task changes

**Comment by elizabethli31** [comment]
Added all the code from this year and updated wiki pages regarding integration with other teams. Everything should be up to date with our code. We'll still need to add some issues for next year to the wiki

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great job on this issue, next time try to make your updates tangible!
