### ISSUE TITLE
Fix warnings related to new specgraph functions

### ISSUE THREAD

**Issue by williamhu314** [uchicago-cs/chiventure#1434]
The goal of this issue is to fix the warnings related to the new specgraph functionalities that have popped up from pull request #1384.

**Comment by williamhu314** [comment]
We fixed the warnings that were caused by our new specgraph functions.

Specifically, we recognized that the edges field in the specgraph struct was causing the warnings. This is because we wanted to make edges a 2D array, but accidently made it an int** instead of an int*. We have now changed edges to an int* in all instances in gen_structs.h and gen_structs.c.

**Comment by williamhu314** [comment]
Actually, I have reopened this issue because we realized a better idea was to keep edges as an int** but to make it a pointer to a 2D array. In our tests, we will make a static 2D array and then pass the pointer to that 2D array into specgraph_new and specgraph_init using &.  We also realized there was one more warning in our code due to declaring edges** as an int*[3] instead of an int**. So we decided to make edges dynamically allocated using malloc.

**Comment by williamhu314** [comment]
We have now successfully updated edges to be dynamically allocated. We have also updated the specgraph_free function to account for this. We have realized that it is currently not easy to make an edges 2D array so we may make some functionality to make it easier to make a new one. All warnings have been resolved with the new dynamic allocation.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Good issue that immediately addressed a bug in the dev branch!
