### ISSUE TITLE
Quests: Modify quest functions to manage trees and add reward functions

### ISSUE THREAD

**Issue by JSerf02** [uchicago-cs/chiventure#1439]
Currently, certain key functions of existing quest features are missing. These include, but are not limited to: 
- tasks are not checked for completion when they are added
- quests are not checked for completion when a task is completed
- rewards are never actually given to the player
This issue should cover addressing these 3 problems and adding any similar functionality that the quest module needs

**Comment by JSerf02** [comment]
Changed `start_quest()` so it checks task completion when adding tasks. Also changed `complete_task()` so it adds the next tasks from a quest into the player's task hash table and also so it checks quest completion.

**Comment by JSerf02** [comment]
Added `accept_reward()` which gives the player a reward. Also added a comprehensive test for this function

**Comment by JSerf02** [comment]
Modified add_task_to_player() to add all of the tasks in the prereq list as well

**Comment by JSerf02** [comment]
Finished implementing the addition of tree management functionality to the quest creation and verification functions and also finished adding a function to collect rewards from a reward struct

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Excellent work on this issue!
