### ISSUE TITLE
GUI: Enabling Dynamic display of scenes.

### ISSUE THREAD

**Issue by cyruszzhou** [uchicago-cs/chiventure#1442]
We are trying to enable scene display by getting player coordinates and reading parameters from the GDL file. The player coordinates would be the center of the part of the texture displayed in the window. The idea is to mainly have a "camera" that captures only the parts of the textures necessary for the current game state. With such a graphics design, it would be easy for the playercoordinates to be updated concurrently with the main game program.

**Comment by cyruszzhou** [comment]
We currently take in a SceneName, an image path, window parameters, scene size, and player position (which we will read from the coordinate struct in the main program and turn into Vector2). I have successfully implemented a testing version of this module. Game developers would be required to provide information not captured by the main program through the GDL file. Future developers on this game engine can easily add more fields/information to the current struct.

**Comment by cyruszzhou** [comment]
This issue is currently closed. We will try to make everything de facto dynamic during the next sprint.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great work on this issue!
