### ISSUE TITLE
Implement battle_item_t changes and the new battle_equipment_t struct using design document in the battle module.

### ISSUE THREAD

**Issue by nicholaswlee** [uchicago-cs/chiventure#1443]
The goal of this issue to create a pull request that implements the changes as described in this [document](https://github.com/uchicago-cs/chiventure/wiki/Items-~-Equipment-~-Design-Document). This includes changing the battle_item_t struct to allow more fields to be changed and for combatants to wear equipment. These changes will enhance battles even further, allowing for more uses for battle items and battle equipment which enhances a combatant's stats.

**Comment by corian-jal** [comment]
**Division of Work**
_battle_default_objects.c - Fatimah_
get_random_default_weapon() //needs to account for new fields
get_random_default_consumable() //needs to account for new fields
And add: get_random_equipment_weapon, get_random_equipment_armor, get_random_equipment_accessory

_battle_flow.c - Angela_
set_battle_player() //needs to account for equipment stat changes.
set_enemy() //needs to account for equipment stat changes.
battle_flow_item() //needs to account for new fields

_battle_flow_structs.c - Angela_
new_ctx_player() //needs to account for equipment

_battle_logic.c - Nicholas_
consume_battle_item() // needs to account for new fields
use_battle_item() // needs to account for new fields
stat_changes_add_item_node // needs to account for new fields
And add: apply_stat_changes() //move from battle_flow.c

_battle_print.c - Nicholas_
print_battle_items() // needs to account for new fields
print_battle_action_menu() // needs to account for new fields

_battle_state.c - Nicholas_
combatant_new() // needs to account for new fields
combatant_init() // needs to account for new fields
combatant_free() //needs to account for new fields

**Comment by aliu65803** [comment]
We will need to wait until the NPC team is done with updating their npc_battle_t in order to fully update set_enemy as the npc_battle_t does not currently have equipment. We cannot make this change ourselves since we know that the NPC team is updating their battle code, but do not know the specifics of their implementation yet.

**Comment by nicholaswlee** [comment]
In battle_print.c, we have decided to add a new function called "int *print_battle_item_details". This gives a full description of an item and its stat changes. The function "print_battle_items" now just print the names of all the battle items and their quantities. This will help reduce issues with too much text in a screen.

**Comment by nicholaswlee** [comment]
All of the code has compiled. We now are working on getting the tests to compile. Since equipment has become a thing, some of these tests have become obsolete and will need to be changed.

**Comment by nicholaswlee** [comment]
All the code and tests have now compiled. We will now be working on getting all the examples to compile.

**Comment by nicholaswlee** [comment]
All the examples compile, now it is time for all of the tests to pass.

**Comment by nicholaswlee** [comment]
We have been able to get all tests to pass and have filed a pull request.

**Comment by aliu65803** [comment]
We have fixed all the comments on the pull request and resolved all the merge conflicts. Since we have completed implementing all of the changes outlined in our design document such as adding/updating structs and updating functions, we are now done. The pull request has been approved by Emilio, Lily, and Jun. When the pull request gets merged to dev, it should close this issue as well.

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this issue! The updates are very thorough.
