### ISSUE TITLE
Completely implement run_battle function using run_turn_component and by integrating CLI

### ISSUE THREAD

**Issue by aliu65803** [uchicago-cs/chiventure#1444]
task: Finish integrating run_turn_component into run_battle and CLI

For this issue, we will finish implementing the run_battle function, and we will use our design document to guide our code. We will use our previous PR for run_turn_component as the backbone for this function and add in more functions to complete a turn. Some additions include running an enemy's turn and returning the result and integrating our code with the CLI mode operations, which the CLI team created. We also hope to be using this code in our demo.

**Comment by aliu65803** [comment]
We met yesterday to start our implementation of the run_battle function. During this meeting, we restructured our run_turn_component function to only do half of what it did before in order to make sure that our run_battle function is compatible with CLI integration.

**Comment by aliu65803** [comment]
We are done implementing run_battle_mode and adding a way to switch into battle mode. We are waiting for CLI to finish their battle_operation function before moving on.

**Comment by aliu65803** [comment]
We have finished our integration with CLI, meaning we are now done implementing the run battle function. Our code compiles and passes all tests. Due to this, we are now done with this issue. We are creating a PR, which will be reviewed by Lily and Fatimah, and will close the issue once our code gets merged to dev.

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this issue!
