### ISSUE TITLE
Create a wiki page outlining how the mode operation works

### ISSUE THREAD

**Issue by aliu65803** [uchicago-cs/chiventure#1453]
While we were working on the run_battle function, Emilio, Nafis, and I needed to learn how to convert to battle mode and what exactly that does. In this issue, we hope to outline how to change the mode and how that works together with the CLI. We will create a wiki page outlining how CLI uses modes, what is a mode, what is a CLI_callback function, and how to implement a mode. We will use the battle mode as an example throughout the page.

**Comment by emiliolevinspage** [comment]
First we should give a background on how cli works with respect to the modes. 

Whenever the CLI receives user input, it checks the mode struct that is stored in its chiventure context. It then runs the mode operation affiliated with that mode. after the mode operation runs, the cli prints the string given in the callback function. then the CLI waits for another input and the cycle repeats

**Comment by aliu65803** [comment]
We have created a wiki page documenting how to create a new CLI mode, which can be found [here. ](https://github.com/uchicago-cs/chiventure/wiki/Game-State-~-How-to-implement-a-new-CLI-mode)

**Comment by emiliolevinspage** [comment]
Finished the intro sections and its done!

**Comment by aliu65803** [comment]
We are closing the issue now since we have created and documented all of the sections outlined above in the introduction. This will make it clearer for future developers how to create and use more modes.

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this issue! The wiki page looks great too.
