### ISSUE TITLE
Update Error Messages For View Stats in Action-Management and CLI Modules

### ISSUE THREAD

**Issue by sabinecodes15** [uchicago-cs/chiventure#1455]
The `"view"` action created by the action management team (and used by the CLI team) needs to have errors indicating when functions are called with the wrong action target (e.g. `view iphone`). These will be implemented in the `do_self_action` function in `actionmanagement.c.` At the conclusion of this ticket, the `do_self_action` function will return the correct error message on receiving the wrong action target, which will be picked up by the CLI team and sent to the command line.

**Comment by HarrisonD123** [comment]
After speaking with the CLI team and sifting through their code, we've determined that previous teams have already set up a method of sending error messages to the CLI team through action management functions. The string pointer parameter `ret_string` will be returned to the caller from the CLI module. It will either be assigned to the correct value on a successful command or the correct error message on an error, which we will implement here.

**Comment by HarrisonD123** [comment]
Just thinking about this, we'll need an error message for incorrect commands too. So currently, since the only `SELF` action is view, anything other than `view` passed into our `do_self_action` function should return a general error message. Might need to implement a new error checking function for this.

**Comment by HarrisonD123** [comment]
It turns out the CLI team already runs a test to make sure the self action matches an available action (e.g. `view`). No need to add new testing for this.

**Comment by HarrisonD123** [comment]
We've added error checking into our conditionals in our `do_self_action` function. Upon an invalid action or action target, we now simply assign the return string to our error message, which the CLI team then picks up. We've decided to expand this issue to also include a display option for stat effects as well as just stats. Our function now supports but `"view stats"` and `"view effects"`.

**Comment by HarrisonD123** [comment]
### Closing Statement
Given that our `do_self_action` function now has an if-else logic chain to test what the user wants to view (based on `strcmp`'s), we now have a way to error check the item that the user wants to view. This means that if the user types `view porta-potty` into the command line, we will be able to return an error message. We also have an error message to check for the action itself in the rare case in which CLI passes us an invalid action (currently anything other than `"view"`).

We've also added a new nested if-statement under the conditional that checks for `"view"`, that supports the statement `view effects`. Upon this command, the `do_self_action` function will now call the `do_stat_effect` function from the `game-state/stats` module. For this specific command, we did not need to collaborate with any other teams. We currently have plans to support even more view actions in the near future in collaboration with other teams.

Don implemented the new `view effects` logic in the `do_self_action` function. Harrison and Sabine worked on the error messages.

**Comment by ecoble** [comment]
Issue Score: Excellent

Comments:
Nice job! Great work adding error checking and diving into the CLI code to get this integration working.
