### ISSUE TITLE
Create a design document for demo

### ISSUE THREAD

**Issue by sglenn-uchi** [uchicago-cs/chiventure#1457]
We need to begin designing our demo in advance of the quarter's end. We will begin by creating a document brainstorming our ideas. We will then schedule some type of meeting to discuss these ideas in depth, what our demo would look like concretely, and how it would incorporate all the work we've done over the duration of this quarter.

**Comment by sglenn-uchi** [comment]
We met over the weekend to discuss demo ideas and divvy up work. We ended the meeting with a plan of which aspects of what NPC modules we'll display and how they'll interact, as well as a plan of how we'll divvy up the work.

**Comment by emilybae1705** [comment]
We've written up a [Wikipage](https://github.com/uchicago-cs/chiventure/wiki/NPC-~-NPC-Demo-Design-Document) for the demo design document. It's still a work in-progress but a rough sketch of what we're thinking right now. We're planning on integrating all NPC subteams (dialogue, action-management, battle-integration, and movement) so our demo showcases how all those NPC features work together.

**Comment by emilybae1705** [comment]
We have created a [demo design document](https://github.com/uchicago-cs/chiventure/wiki/NPC-~-NPC-Demo-Design-Document) that lists the NPC features that are being integrated for the demo, which includes movement, dialogue, and battle-integration. Unfortunately, we decided to exclude action-management as most of its functions have not been tested yet. The general goal of the demo is to integrate across NPC subteams as we found past years' demos to mostly be separate showcases of what each subteam worked on. This year, the scenario we've drawn is to have different types of NPCs in different rooms where one is CONDITIONAL_FRIENDLY and another is HOSTILE such that the HOSTILE NPC can initiate a battle and the CONDITIONAL_FRIENDLY NPC can be provoked into initiating a battle. To start a fight, the player and NPC need to have a dialogue with each other where certain keywords will trigger a battle given the `add_action_to_node` function. Players can also exchange items with NPCs using `add_give_item` and `add_take_item` functions in `dialogue.c`. Through an integration of various NPC features, we hope to show how NPC fits into Chiventure as a whole and introduce the dynamic aspects an NPC can contribute to the game engine. Please see #1587 for the demo implementation.

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this issue! The closing statement is very thorough.
