### ISSUE TITLE
Create a wiki for the new implementation of complex skills

### ISSUE THREAD

**Issue by anchristensen** [uchicago-cs/chiventure#1461]
We want to create a wiki page describing complex skills and their new implementation, as well as some examples of how they can be used. This will help other teams understand these skills so they can better evaluate how their feature might use these new skills.

team members: Nikola, Annika

**Comment by anchristensen** [comment]
Update: We have determined the broad subjects which need to be addressed in the summary of complex skills wiki page. We are going through specifics of each subject now and writing up a summary of this information.

**Comment by anchristensen** [comment]
Closing statement: We wrote up a brief summary of complex skills on a wiki page here: https://github.com/uchicago-cs/chiventure/wiki/Skill-Trees-~-Complex-Skills-Summary. This summary aims to help other teams understand and navigate complex skills so that they can better use these complex skills for their own purposes. It briefly describes the four types of complex skills (sequential, combined, conditional, and random), examples of the usages of these, an explanation of the complex_skill_type_t struct, and a description of why a new field was added to the skill_t struct and how this can be used with nesting complex skills. We each took notes on a google document before pasting it in the wiki page (to be precise, I wrote the complex skill types and fields sections, and @nbilaver wrote the nested complex skills and new field in skill_t explanation).

**Comment by jacknugent1529** [comment]
Issue Score: Excellent

Comments: Nice work on this issue! The wiki page will certainly be useful for people using skill trees. Keep in mind that when writing updates, try to include specific and tangible items (e.g. which "broad subjects").
