### ISSUE TITLE
Create demo file

### ISSUE THREAD

**Issue by anchristensen** [uchicago-cs/chiventure#1462]
We will create a demo file, using the example from last year to better understand what must be done, which reflects our work from this year. This will entail looking at last year's demo, examining what work we can use from this year in the demo, and creating the new file using this information.

team members: Nikola, Arya, Annika

**Comment by nbilaver** [comment]
Update, we've created a file for the demo, and we've created a lot of surrounding functions necessary for putting in complex skills. Still need to add more rooms, but the demo is at a good spot where adding the rest of the features that we want to show off shouldn't be too bad.

**Comment by nbilaver** [comment]
Update 2: We now have a usable version of this demo. There is still room for improvement, mainly that there are more things that were done this year that could be added, but as is the demo could be used for the final demonstration.

**Comment by jacknugent1529** [comment]
Issue Score: Excellent

Comments: Nice work on this issue! The demo file was very well made. In the comments, try to be a bit more specific – rather than vague statements such "Still need to add more room," include what rooms could be added and why these would be relevant.
