### ISSUE TITLE
Make "view" action more flexible, coordinate with CLI team to make interface more usable

### ISSUE THREAD

**Issue by HarrisonD123** [uchicago-cs/chiventure#1463]
As it stands, the do_self_action function is inefficient, because it has redundant parameters and uses an enum to check the target of the view action (e.g. STATS in view stats). This makes it difficult for the CLI team to call our function given the input from the user's command line. We need some way to make this smoother. Currently, the only action this function can handle is view, which may change in the future.

**Comment by HarrisonD123** [comment]
After communicating with the CLI team and looking through their code, we've determined that it would be best to remove the `player_t` parameter from the `do_self_action` function, as the `chiventure_ctx_t c` parameter already includes its own `player_t` member. This keeps the CLI team from having to do too much parsing on their end.

The current idea is to implement a switch given the `view` action to ensure that the object being "viewed" is valid. This switch will use `strcmp` on the string representing the target of the `view` action, passed to us by the CLI module.

**Comment by Don-Osipov** [comment]
After trying to implement a switch statement given the target action, we have realized that a switch statement is not the right tool and have instead implemented an if-else statement to parse the target actions. I have also added possible future actions that this function can support.

**Comment by HarrisonD123** [comment]
### Closing Statement
We made several changes to our new do_self_actions function to make it easier for the CLI team to call and to make it easier to have our function support many new viewing actions.

- Our do_self_actions function now only contains the parameters `chiventure_ctx_t *c`, `action_type_t *a`,
                   `char* target`, and `char **ret_string`
- The `target` parameter decides what the user wants to view. We were able to remove the previous version's `player_t` parameter because we realized that the `chiventure_ctx_t` struct already contains a player.
- We also implemented a deeper if-else statement structure to allow for viewing of other interfaces (i.e. skills, quests, inventory, etc.) in the future.

Harrison coordinated with the CLI team to determine what changes were needed. Then all members assigned to the issue addressed the needed changes.

**Comment by ecoble** [comment]
Issue Score: Excellent

Comments:
Great work! Nice job reworking your code to be more flexible!
