### ISSUE TITLE
rpg-skilltrees: design and implement example file(s) for complex skills

### ISSUE THREAD

**Issue by KabirDubey** [uchicago-cs/chiventure#1465]
We will write example files for the complex skills features implemented in #1382. We aim to have at least one example for each type of complex skill: sequential, combined, conditional, random. We will write our examples in accordance to the examples that will be introduced in the upcoming wiki page for complex skills (see #1461).

Team members: Arya, Chelsea, Kabir

**Comment by KabirDubey** [comment]
We met as a team and concluded the following:

1. Issue #1627 is necessary
2. The current `skill-example` file is obsolete. It references battles in a way that lacks documentation. The include statements do not make sense and may cause errors down the line
3. Our construction of complex skill examples overlaps heavily with the demo file #1462 

To resolve (2) we will totally refactor in `skill-example.c/.h` and write new tests. If the tests pass then we will make a PR and include the file in our demo file. If the tests fail then we will copy paste the ideas in the examples into the demo file and handle the issue independently.

**Comment by KabirDubey** [comment]
Update: we're not going to make an example for random skills because they're not done yet.

**Comment by KabirDubey** [comment]
Update: refactored the battles examples and complex skills examples into separate files. Fixed various errors in documentation (see commit history). Finalized implementation of conditional skills. All that remains is to ensure that the new files are included correctly. Moving forward to PR.

**Comment by chelseaegbarin** [comment]
Closing statement: Implementation of conditional skills was finalized. The example files were written for all types of skills except random, which might be left as a future issue, as the random skills stuff is quite hefty and might entail refactoring into its own module at some point. Battles and complex skills examples were refactored into separete files for ease of understanding.

**Comment by KabirDubey** [comment]
Arya wrote examples for combined and sequential skills. Kabir wrote the conditional skill example and re-organized the module. Chelsea ensured the new files were integrated correctly and finalized the additions.

**Comment by jacknugent1529** [comment]
Issue Score: Excellent

Comments: Great work! The comments are very detailed and present your progress and thoughts very clearly.
