### ISSUE TITLE
Quests: Refactor WDL design with new mission changes (the new mission struct)

### ISSUE THREAD

**Issue by charlieweiler** [uchicago-cs/chiventure#1467]
Since our initial WDL design, the mission_type struct has changed into a more compact struct. The WDL should be refactored to account for these changes.

**Comment by JSerf02** [comment]
This was finished over a week ago, we just forgot to update the issue...

**Comment by JSerf02** [comment]
We finished updating the WDL design document with the quest mission re-redesign
