### ISSUE TITLE
GUI: Creating Proper Tests for NPC Structs

### ISSUE THREAD

**Issue by ukanyanwu** [uchicago-cs/chiventure#1469]
To integrate graphical elements for NPCs, their available lines and frames of expressions need to be accounted for.  As such structs for npc_actions, lines, and a list to hold them all have appropriate structs to hold their information. With these structs, they have new, init, and free functions that are used. They need to be properly tested to make sure that they are used and developed correctly as they are used in draw functions to represent NPC graphics in Chiventure.

**Comment by ukanyanwu** [comment]
Unfortunately there are issues with Criterion to make tests, so functions are being tested in main files that will print to stdout. The NPC_action and NPC_line structs are currently printing the correct values to stdout when prompted with a printf to the appropriate parameters for their structs. Memory is also being deallocated correctly with their respective free functions, as well. NPC_info list structure has been recognized as having its own tests within npc_graphics.c, but an important step later on is testing functions that operate with that struct such as iterating through it and collecting lines/actions from the list.

**Comment by ukanyanwu** [comment]
A new npc_graphics_t struct has been added to the npc_graphics module which compiles necessary information when it becomes time to call the draw_npc function, such as window dimensions and information about the current NPC being displayed when using chiventure. With this new struct, proper new/init/free tests need to be made to confirm that the function works properly.

**Comment by ukanyanwu** [comment]
Tests have been written to confirm that the npc_graphics struct can properly new/init/free. It'll be worthwhile to restructure the testing files for these tests in order to make them more readable, but overall, the goal of writing tests that pass for the different structs has been achieved.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great work on this issue!
