### ISSUE TITLE
Create helper functions for static and dynamic game autogeneration

### ISSUE THREAD

**Issue by williamhu314** [uchicago-cs/chiventure#1471]
In this issue, we aim to create helper functions that will help us with our static and dynamic game autogeneration functions. Specifically, we would like the following functions:

1. A function that creates the first room in the game randomly. This can be done fairly easily using the random_room_lookup and the roomspec_to_room functions. We will need this function for both static and dynamic game autogeneration.

2. A function that creates a new room given only a game struct and a gencontext struct. This function itself will require 2 helper functions:

a. A random_room_from_game function that returns a random room within the game 
b. Update the pick_random_direction function to account for our new coord struct.

We may need to call this function recursively in case we choose a room with no open directions.

3. A function that generates paths randomly. This function will need to determine from the adjacency matrix the relationship between 2 roomspecs and from that value determine whether to create a path connecting the 2 rooms.

**Comment by williamhu314** [comment]
The function for creating the first room has been implemented

**Comment by williamhu314** [comment]
For 2b, to update the pick_random_direction function to account for our new coord struct, we will need to add a new helper function called room_exists_in_direction that determines whether there exist an adjacent room in the given direction based on the coord struct information.

**Comment by williamhu314** [comment]
The room_exists_in direction and pick_random_room functions have been implemented and we are working on fixing some bugs with these functions

**Comment by williamhu314** [comment]
I have added a new helper in autogenerate.c related to room_exists_in_direction called find_room_in_direction. This function will actually output the pointer to the adjacent room in the given direction rather than just returning true of false like room_exists_in_direction

**Comment by williamhu314** [comment]
I have finished implementing the path_autogenerate function. Thus, we have successfully implemented all necessary helper functions required for our game autogeneration functions.

We still need to update the functions to account for tags and will do that in #1526. We will make tests for our functions to catch and fix any bugs in #1473.

**Comment by williamhu314** [comment]
I have finished implementing the path_autogenerate function. Thus, we have successfully implemented all necessary helper functions required for our game autogeneration functions.

We still need to update the functions to account for tags and will do that in #1526. We will make tests for our functions to catch and fix any bugs in #1473.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great work on this issue!
