### ISSUE TITLE
Brainstorming/Designing Different Variations of Static and Dynamic Game Autogeneration

### ISSUE THREAD

**Issue by williamhu314** [uchicago-cs/chiventure#1472]
In #1351 and #1374 we are implementing our "default" static and dynamic game generation algorithm that will make the entire game completely randomly. 

In the static case, the function generates the game starting by creating a random room, and then choosing a random room in the game to generate new rooms from. 

In the dynamics case, the function makes rooms and paths on demand whenever the player wants to move into an area without an existing room.

In this issue, our goal is to brainstorm and design different versions of static and dynamic game autogeneration that will provide the game author with more options when generating their game.

**Comment by williamhu314** [comment]
Some factors to consider are:

1. The randomness of the algorithm. We may make functions that generate a game "less randomly" and give the author more control 
2. The structure of the game. We may make functions that make the graph of all the rooms, paths, and coords resemble a particular shape, such as a square, rather than having the structure be completely random.
3. The number of rooms in the game. We may want to create a function allowing for a range in the number of rooms rather than a set amount of rooms.
4. The connectivity of the game. We may want to provide functions allowing the game author to have some control over how many paths the game contains.

**Comment by williamhu314** [comment]
Some possibilities are making the function generate games with a square or circular shape, changing the algorithm for roomspec autogenerate, and changing the forumla for path autogenerate to affect the connectivity and structure of the game.

**Comment by williamhu314** [comment]
We have completed brainstorming for other generation methods. Future work could include designing and implementing some of these functions.

**Comment by williamhu314** [comment]
We have completed brainstorming for other generation methods. Future work could include designing and implementing some of these functions.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great work on this issue, especially the updates.
