### ISSUE TITLE
Creating tests for game autogeneration helper functions

### ISSUE THREAD

**Issue by williamhu314** [uchicago-cs/chiventure#1473]
In #1471, we are aiming to create helper functions that will aid us in our static and dynamic game autogeneration functions in addition to providing flexibility in case we want to create different versions/variations of these autogeneration functions.

In this issue, our goal is to create tests for all of the helper functions. Specifically, we need tests for the following functions:

1. The function that creates the first room in the game

2. The function that generates a new room given only a game_t struct and a gencontext struct. We also need tests for it's helper functions, which include:

a. The random_room_from_game function that returns a random room within the game
b. Update the pick_random_direction function to account for our new coord struct if needed

3. The function that generates paths randomly, with probability based on the adjacency matrix.

**Comment by williamhu314** [comment]
We have finished #1473 and implemented a few additional functions that will require tests. The full list of functions needing tests is now as follows:

**In game_autogenerate.c**
1. random_first_room (Creates a random first room for the game)
2. The random_room_from_game (returns a random room within the game)
3. autogenerate_room_in_game (picks random room in a game and generates a room in a random direction)
4. path_generate (determines whether to make a path between 2 rooms of given roomspecs based on the adjacency matrix)
5. path_autogenerate (generates new paths randomly from a current room)

**In autogenerate.c**
1. Update the pick_random_direction tests to account for the new implementation with the coord struct
2. room_exists_in_direction (new helper to determine whether a room exists in a certain direction from a current room)
3. pick_random_direction (new helper to return the pointer to the room in the given direction from a current room)

**In specgraph.c**
1. roomspec_correlation, which determines the correlation between 2 roomspecs based on the adjacency matrix

**Comment by williamhu314** [comment]
I have created tests for the random_first_room, random_room_from_game, and autogenerate_room_from_game functions.

**Comment by williamhu314** [comment]
We have finished the following tests:

1. random_first_room (Creates a random first room for the game)
2. The random_room_from_game (returns a random room within the game)
3. autogenerate_room_in_game (picks random room in a game and generates a room in a random direction)

**In autogenerate.c**
1. pick_random_direction
2. room_exists_in_direction

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great work on this issue, especially the updates.
