### ISSUE TITLE
Refactoring NPC movement by getting rid of separate definite movement and indefinite movement structs

### ISSUE THREAD

**Issue by bvvill** [uchicago-cs/chiventure#1475]
Currently, the only difference between the `npc_mov_definite` and `npc_mov_indefinite` structs is that the indefinite one has a hash table of "room times", `npc_room_time_hash_t`, which is just has the room IDs and an integer value for the amount of milliseconds an indefinite NPC is supposed to be in that room. Although a hash_table is technically a doubly-linked list (per uthash's documentation), mapping these time values in the hash table to the steps in the movement path has some problems:
1. If an NPC has a particular room in its path multiple times, it will always stay in that room for the exact same amount of time as before (as opposed to spending 15000 ms in it the first time and 20000 ms the second time, for example), because all values in the hash table must be unique
2. Is unnecessarily complex, and serves as a speed bump in further development of NPC movement

**Comment by bvvill** [comment]
My current plan to alleviate this is to add a time field to the existing `room_id_dll` struct, so that it isn't necessary to have separate structs for definite and indefinite moving NPCs and taking the `mov_type` enum into consideration (where appropriate) will be sufficient, and considerably less complex.

**Comment by bvvill** [comment]
The time field I mentioned in the previous comment will come in the form of the `time_ray_t` struct, which have `time_t start` and `double assigned_time` fields, representing the start time of when an (indefinite) NPC enters a room and the number of seconds that NPC has been assigned to be in that room

**Comment by bvvill** [comment]
This `time_ray_t` struct will be a new member of the `npc_path_dll_t` struct, which I am renaming from `room_id_dll_t`

**Comment by bvvill** [comment]
definite NPCs will have this `time_ray_t` field to be `NULL`, whereas it will actually be initialized for indefinite NPCs

**Comment by bvvill** [comment]
> definite NPCs will have this `time_ray_t` field to be `NULL`, whereas it will actually be initialized for indefinite NPCs

added init(), new(), and free() functions for the `time_ray_t` struct

**Comment by bvvill** [comment]
removed the `move_npc_indefinite` and `move_npc_definite` functions as it's no longer necessary to have separate functions, `move_npc_mov` takes care of both types perfectly

**Comment by bvvill** [comment]
Ran into a little bit of a change amplification problem from going from `int room_time` to `double room_time` in reference to the amount of seconds (which used to be milliseconds, and is being switched in order to be similar to the output of `difftime()` in the standard `time.h` header, which will soon be utilized to its full extent) an indefinite NPC spends in each room along its path, mainly in npc_move.c and room.c

**Comment by bvvill** [comment]
removed the `register_npc_room_time` function and its test, as `npc_mov_init` accomplishes the same purpose.

**Comment by bvvill** [comment]
updated `extend_npc_path_indefinite()` and `extend_npc_path_definite()` (and their tests) to reflect changes in the `npc_mov` struct. I've decided to let these functions stay separate because they get called upon often and there's an extra parameter used in `extend_npc_path_indefinite` that would often be unused if the functions were generalized. This makes me really wish there was a good way to do optional arguments in C lol

**Comment by bvvill** [comment]
also, forgot to mention that I've implemented init(), new(), and free() functions for the `npc_path_dll_t` struct, although I've decided to abstract them away to solely reside in `npc_move.c`, since they're basically helper functions

**Comment by bvvill** [comment]
Finally, did some rearranging of the functions in the `npc_move` module so that the functions are sorted by their type of operation, like struct, "get", compare, and "do something" (I could think of no better name, even update didn't totally apply lol) functions

**Comment by bvvill** [comment]
> also, forgot to mention that I've implemented init(), new(), and free() functions for the `npc_path_dll_t` struct, although I've decided to abstract them away to solely reside in `npc_move.c`, since they're basically helper functions

The init(), new(), and free() functions for `time_ray_t`s have also been extracted away into `npc_move.c`, for the same reason

**Comment by bvvill** [comment]
``` strcpy(npc_mov->track, room_id);
    npc_mov->npc_path_pos = 0;
    npc_mov->npc_path_direction = NPC_MOV_ORIGINAL;
    npc_mov->path = NULL;
    npc_path_dll_t *elt = npc_path_dll_new(mov_type, room_id, room_time);
    DL_APPEND(npc_mov->path, elt);
    return SUCCESS;
```

basically all of the failed builds on this branch are because I had set up `npc_mov_init` like the above code, instead of the below. Letting this serve as a painful reminder that initializing the head of a utlist is essential, as sussing this out took me 2 excruciatingly-long hours

```
int npc_mov_init(npc_mov_t *npc_mov, npc_mov_enum_t mov_type, char *room_id,
                 double room_time)
{
    assert(npc_mov != NULL);
    npc_mov->mov_type = mov_type;
    strcpy(npc_mov->track, room_id);
    npc_mov->npc_path_pos = 0;
    npc_mov->npc_path_direction = NPC_MOV_ORIGINAL;
    npc_path_dll_t *head = NULL; // these next few lines are VERY important
    npc_path_dll_t *elt = npc_path_dll_new(mov_type, room_id, room_time);
    DL_APPEND(head, elt);
    npc_mov->path = head;
    return SUCCESS;
}
```

**Comment by bvvill** [comment]
> ` strcpy(npc_mov->track, room_id); npc_mov->npc_path_pos = 0; npc_mov->npc_path_direction = NPC_MOV_ORIGINAL; npc_mov->path = NULL; npc_path_dll_t *elt = npc_path_dll_new(mov_type, room_id, room_time); DL_APPEND(npc_mov->path, elt); return SUCCESS;`
> 
> basically all of the failed builds on this branch are because I had set up `npc_mov_init` like the above code, instead of the below. Letting this serve as a painful reminder that initializing the head of a utlist is essential, as sussing this out took me 2 excruciatingly-long hours
> 
> `int npc_mov_init(npc_mov_t *npc_mov, npc_mov_enum_t mov_type, char *room_id, double room_time) { assert(npc_mov != NULL); npc_mov->mov_type = mov_type; strcpy(npc_mov->track, room_id); npc_mov->npc_path_pos = 0; npc_mov->npc_path_direction = NPC_MOV_ORIGINAL; npc_path_dll_t *head = NULL; // these next few lines are VERY important npc_path_dll_t *elt = npc_path_dll_new(mov_type, room_id, room_time); DL_APPEND(head, elt); npc_mov->path = head; return SUCCESS; }`

why on earth does it look like this

**Comment by bvvill** [comment]
> ` strcpy(npc_mov->track, room_id); npc_mov->npc_path_pos = 0; npc_mov->npc_path_direction = NPC_MOV_ORIGINAL; npc_mov->path = NULL; npc_path_dll_t *elt = npc_path_dll_new(mov_type, room_id, room_time); DL_APPEND(npc_mov->path, elt); return SUCCESS;`
> 
> basically all of the failed builds on this branch are because I had set up `npc_mov_init` like the above code, instead of the below. Letting this serve as a painful reminder that initializing the head of a utlist is essential, as sussing this out took me 2 excruciatingly-long hours
> 
> `int npc_mov_init(npc_mov_t *npc_mov, npc_mov_enum_t mov_type, char *room_id, double room_time) { assert(npc_mov != NULL); npc_mov->mov_type = mov_type; strcpy(npc_mov->track, room_id); npc_mov->npc_path_pos = 0; npc_mov->npc_path_direction = NPC_MOV_ORIGINAL; npc_path_dll_t *head = NULL; // these next few lines are VERY important npc_path_dll_t *elt = npc_path_dll_new(mov_type, room_id, room_time); DL_APPEND(head, elt); npc_mov->path = head; return SUCCESS; }`

![Refactoring NPC movement by getting rid of separate definite movement and indefinite movement structs by bvvill · Pull Request #1483 · uchicago-cs_chiventure - Google Chrome 5_20_2022 12_25_45 AM](https://user-images.githubusercontent.com/102555942/169456849-17a62414-c57d-47ea-adbf-fe87079b12b8.png)
red_code = bad;
green_code = good;
return 0;

**Comment by bvvill** [comment]
But if someone could explain to me exactly why the code on the top doesn't work that would be so dope

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this issue! The updates are fantastic.
