### ISSUE TITLE
dsl: implement player_class grammar in dsl_grammar.lark for player_class implementation

### ISSUE THREAD

**Issue by wzeng0** [uchicago-cs/chiventure#1479]
While implementing player class, the grammar needs to be updated for the conversion to happen

**Comment by wzeng0** [comment]
Initially the Lark grammar did not support the player_class. I changed it so that the game looks for a class called player_class. Player class is able to take in short description, long description, multiple attributes, and base stats now. The grammar is updated in ```dsl_grammar.lark``` and we created a new file called ```player-class-grammar-ex.dsl``` for testing. I'm closing this issue now because we are at a checkpoint. In the future, we can implement effects, skill_trees, and starting_skills into player_class.

**Comment by jacknugent1529** [comment]
Issue Score: Satisfactory

Comments: Nice work implementing this feature! Even though this task was split from the single task, it still needs a detailed description and updates as you make progress on the issue.
