### ISSUE TITLE
GUI: Creating Proper Tests for Scene Structs

### ISSUE THREAD

**Issue by ukanyanwu** [uchicago-cs/chiventure#1485]
Scene graphics utilises its own scene_graphics structs in order to visually represent them in chiventure. This struct is used in the draw function for scene graphics, and in order to fully verify that it can and will work as intended, scene graphics must show that its new/free functions properly allocate and deallocate memory, respectively.

**Comment by ukanyanwu** [comment]
Scene graphics structs have proper structs that show that the structs can properly new/init/free with those appropriate functions. Recently, scene_graphics were pulled into the dev branch of chiventure, confirming that the tests written for the structs were written well and accomplished what they needed to do.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great job on this issue -- simple but important!
