### ISSUE TITLE
cli: create documentation for next year's group 

### ISSUE THREAD

**Issue by majorsylvie** [uchicago-cs/chiventure#1486]
team members: Matteo, Miles, Brianna

This task involves detailing what we have done this quarter, which would include talking about the research and motivation behind using Bison, along with the improvements to the current code we have added.

Probably be good to make a wiki page detailing this!

**Comment by milesgardner** [comment]
We plan on splitting this task up 3 ways:

Improvements to current code - Miles Gardner
General Bison information/going forward - Brianna
Matteo - Intro and general info/ going forward

**Comment by milesgardner** [comment]
A wiki page for documentation for future CLI teams has been created : https://github.com/uchicago-cs/chiventure/wiki/CLI-~-Future-Documentation

**Comment by milesgardner** [comment]
Currently, we only have updates for the parsing module.  Next, we are going to add commentary on our work with Bison, and general information about the existing codebase.

**Comment by milesgardner** [comment]
We've added an overview of what we've changed in parsing, commands, and operations.  Additionally, we added a section for going forward.  Matteo, Brianna, and I all split up the work evenly 3 ways.

**Comment by jacknugent1529** [comment]
Issue Score: Excellent

Comments: Great work on this issue! The documentation looks well organized, and it looks like you split it up well to cover all aspects.
