### ISSUE TITLE
cli: documentation for adding a new "function" 

### ISSUE THREAD

**Issue by majorsylvie** [uchicago-cs/chiventure#1487]
team members: Faruk, Brianna, Kate

once the `view` function work is done, we can document the process that went into creating a new function, as in:

* what is the goal of the new function (to work with a new action type from AM)
* what we as CLI have to code
* what we have to update about the existing architecture (updating global action variable list, updating the lookup table)

This would take the form of a [wiki page](https://github.com/uchicago-cs/chiventure/wiki/Enhanced-CLI-~-How-to-Implement-a-New-Action-Operation)!

**Comment by majorsylvie** [comment]
As of now, it is unrealistic to work on this until the `view` function is fully implemented, because until then we will not have not actually fully implemented a new function, and would not be aware of the full process.

**Comment by majorsylvie** [comment]
The view function has now been fully implemented! So we can start making documentation!
I will be beginning on this by making a wiki page that describes the general process. 
Will likely make a branch to test the addition of an independent type of function to follow along with the page

**Comment by bzeng6** [comment]
I just wrote up directions on how to get chiventure to recognize a desired action and call a new operation function, in the cases that the operation does not fit into any of the four action kinds. I explained how how you have to call `add_entry` to associate the action and operation together and add it into a hash table of commands, explaining what the different arguments in the function call are. I then explained how to add the action to the suggested actions list.

**Comment by majorsylvie** [comment]
Added sections on how to add a new kind and update an existing kind

**Comment by majorsylvie** [comment]
Finished documentation for adding a new kind.
https://github.com/uchicago-cs/chiventure/wiki/Enhanced-CLI-~-How-to-Implement-a-New-Action-Operation

Closing now:
Faruk created the page and contributed to the documentation
Brianna contributed to the documentation
Kate looked over what we wrote and offered suggestions

**Comment by jacknugent1529** [comment]
Issue Score: Excellent

Comments: Great work on this issue! This documentation could be very useful to future teams.
