### ISSUE TITLE
Add NPC-specifc prefabs into class_prefab.c inside Playerclass

### ISSUE THREAD

**Issue by Vincent-Zhang4135** [uchicago-cs/chiventure#1490]
Jonathan, Katie, and I are adding in friendly NPC's into the playerclass module in class_prefabs.c. Currently, all the playerclass prefabs are very combat and skill heavy, and there aren't many supportive classes. Therefore, we are going to add some classes into the code with the stats of these new classes, alongside a short and long description. Although there is room for refactoring, we will primarily be focused on just adding these new classes in the class_prefab.c file inside Playerclass.

**Comment by Vincent-Zhang4135** [comment]
The NPC team wants to code in friendly NPC's which would need friendly classes like healer or something of that sort. We met with Lily to discuss the motivation and reasoning behind this, and decided that because all the playerclass prefabs are geared more towards actions and skills that players actually have, it can also be helpful to add in prefabs that are directed towards non-hostile NPCs. We have decided on a few NPC-like prefabs:

- alchemist
- chef
- healer
- shopkeeper
- fisherman
- lord

We are considering adding 6 new npc prefabs

**Comment by Vincent-Zhang4135** [comment]
Jonathan and I synced and added four new prefabs, and will notify Katie to finish the last two (Lord + Healer). While implementing, we thought of possibly ways of refactoring our these player classes into two modules separately for npc and players alike. This change might require a lot of work, and so we decided to push this off and left a comment on the document if future devs want to delve into how to refactor it. Another possible suggestion we thought of was including more stats to better tailor towards friendly NPC class types. We thought this was more feasible as working solution for now, and might delve into that during this sprint

**Comment by katie-gao** [comment]
I have finished the Lord and Healer implementations, alongside fixing some of the strings to match the 80 character mark. For now, we have finished a good baseline for these new npc's. I also think we can fix up the wiki documentation to correspond with these new classes, if these changes get approved. I fixed up the code so that there is only now one failing test, but not sure where the error is.

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this issue!
