### ISSUE TITLE
GUI: writing new and free functions and tests for scene_graphics

### ISSUE THREAD

**Issue by cyruszzhou** [uchicago-cs/chiventure#1495]
We have come up with the structs of scene graphics but haven't written any new/free function or test yet. Now we are trying to make up for this and change the original hardcoded memory allocation as well. This would benefit future developers to come up with new functionalities based on the current structs. Also, this makes eyeball testing the rungraphcis function for scene-graphics module much more easier and formal!

**Comment by cyruszzhou** [comment]
We have sucessfully written functions and tests for scene graphics (new/init/free functions). All tests pass, so we are assured that they are functioning properly. We also found out a way to adapt the criterion macro (in regard to Makefile and test.c), which our teammates can use as a template.

**Comment by cyruszzhou** [comment]
We are now trying to pull request these functions and tests before the draw function (which makes more sense). The issue is closed.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
A brief, but nonetheless good issue!
