### ISSUE TITLE
rpg-skilltrees: expand reader effect

### ISSUE THREAD

**Issue by nbilaver** [uchicago-cs/chiventure#1496]
team members: Chelsea, Nikola, Kabir

This issue seeks to add more to the reader module, mainly by creating more readers for useful aspects of the game. At the moment, the reader module is undergoing a PR, so at the time of writing this issue cannot be started, but will be able to be worked on soon.

**Comment by chelseaegbarin** [comment]
Closing statement: everyone on the team met to finalize the use of the reader in the demo and also thought about how the reader could be expanded. Chelsea and Kabir developed the way conditional skills interacts with the reader whereas Nikola developed the reader itself. Future work will involve communicating the powerful functionality of the reader to other groups and expanding the context argument further.

**Comment by jacknugent1529** [comment]
Issue Score: Satisfactory

Comments: Nice job looking into this! Be sure to provide status updates, and ideally provide tangible outcomes to close the issue.
