### ISSUE TITLE
Cli: strengthening unit tests for older and newly added code in CLI

### ISSUE THREAD

**Issue by mrestuccia1** [uchicago-cs/chiventure#1497]
Currently, the unit tests in Chiventure do not cover many cases and are thus quite weak. This is cause for worry, as they might be missing errors that could create issues down the line. We aim to bolster these tests by adding more both to the previously written functions of the CLI code, as well as to the new functions we are adding (multiple words in quotes, removing fillers, multiple commands...).

Team: Matteo, Miles, Kate

**Comment by milesgardner** [comment]
As a team, we've identified various aspects of the `parser.c` , `cmd.c`, and the `operations.c` which need more rigorous testing.  We are currently writing tests for the basic tokenization, quote tokenization, the removal of filler words, and the functionality of multiple commands, in various contexts and edge cases.

**Comment by katyashchukina** [comment]
We have added 30 tests, which test the parse_r, cmd_from_string, and parse functions. Our tests covered edge cases that were not covered in the initial testing framework, so we feel that our new tests better make certain that the Chiventure code works as it should. For this task, Matteo, Miles and Kate all worked on the implementation of new tests, and all of us worked on documentation

**Comment by jacknugent1529** [comment]
Issue Score: Excellent

Comments: Great work on this issue! Additional testing will certainly help the reliability of the cli.
