### ISSUE TITLE
Write tests for get_supported_actions module

### ISSUE THREAD

**Issue by yoonsjeong** [uchicago-cs/chiventure#150]
A follow-up to issue #116, which implemented the function get_supported_actions. To make sure these functions will work for other teams, we need to implement tests, confirming that it is possible to:
1. iterate through a list
2. the list contains the proper number and types of actions
3. it is possible to search through the list using a c_name string

**Comment by yoonsjeong** [comment]
The pull request into actions/dev has been completed along with the tests associated with this task. Hooray for teamwork!

**Comment by mpcsh** [comment]
Issue Score: ✓

Comments:
Good work, just missing progress updates.
