### ISSUE TITLE
GUI: Edit GDL wiki and format

### ISSUE THREAD

**Issue by csraffaga** [uchicago-cs/chiventure#1500]
The GDL wiki as well as the GDL structure need to be updated to facilitate increased author design ability. This includes adding a field for camera width and height to be compatible with customized scene display and a reworking of the module to increase efficiency. Previously the file was being read by multiple functions - but this would require passing through multiple times and doing additional work. We are updating the read_gdl() function to make one pass through the file and minimize work.

**Comment by imadejski** [comment]
https://github.com/uchicago-cs/chiventure/wiki/Graphics-~-GDL
Wiki is updated with more specifics of the statistics section of the GDL file as well as the addition of a camera width and height section. The sample is updated accordingly.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
A minor issue, but well done!
