### ISSUE TITLE
Quests: Readability Improvements (Quest Completion Enum and Streamlined Reward Delivery)

### ISSUE THREAD

**Issue by Castel-Jaloux** [uchicago-cs/chiventure#1501]
Quests currently represent status as integer values from -1 to 2, which makes it difficult to tell what each status value actually means. We want to change this to an enum so the status is more understandable.

In a similar vein, the complete_task() function returns a reward struct, which is almost always immediately passed into accept_reward(). While we don't want the accepting of the reward to be forced, for increased readability and simplicity, we would like to have a function that performs both of these operations in sequence. This should reduce the complexity of the function call line, making the code easier to understand.

**Comment by JSerf02** [comment]
We added the enum and added the update_task() function

**Comment by JSerf02** [comment]
Fixed more tree management issues so prereq tasks are now properly added to the player

**Comment by JSerf02** [comment]
The quest status enum and update_task() function have successfully been added

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great work, but next time add a closing statement to your issue to indicate it is finished.
