### ISSUE TITLE
Create design document for the demo  

### ISSUE THREAD

**Issue by katie-gao** [uchicago-cs/chiventure#1503]
Jake, Van and I are discussing the demo based on the changes we have made throughout this quarter. As we individually had worked on different tasks, we are going to design a demo that includes the breadth of ideas/code we worked on to present in the future. This is a preliminary issue and a brainstorming session.

**Comment by katie-gao** [comment]
After discussing, we decided to demo the multi-class module (Jonathan and Jake have been working on this all quarter), and two classes with the new skills/stats (the rest of us have worked on the prefabs module). That way, we can demonstrate the entire team's work, and the two classes can be encapsulated in a multiclass. We are continuing to be in contact with the skillstree team to see their progress on the skill functions we need for this demo. If it doesn't seem possible that their team will be finished with the functions, we will demo the classes similar to how the previous year did with the warrior class. As of now, we are closing this issue, and referencing a new issue that discusses the implementation/changes we need at issue #1545.

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this issue! Even though you can add labels to issues to categorize them, you should avoid titles that could plausibly apply to multiple teams
