### ISSUE TITLE
GUI: writing new, free, and tests for quest_graphics functions

### ISSUE THREAD

**Issue by cyruszzhou** [uchicago-cs/chiventure#1505]
We have written graphics structs and draw functions for the quest module, but have not yet written new and free functions and tests for that module. We are now trying to enable the quest_graphics module for pull request. This would not only benefit future developments by formalizing the process of malloc/init/free, but also making our own testing on the rungraphics functions easier.

**Comment by cyruszzhou** [comment]
We have written new, init, and free functions for the quest modules. We also wrote tests for them. After debugging, they all passed. The usage of these functions are straightforward and has just enough information needed. We have committed the change to git, and we are one step forward to pull request our quest_graphics module.

**Comment by cyruszzhou** [comment]
As this task is finished, we now close the issue. We will wait for pull request to take place.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great job on this issue with a good set of updates!
