### ISSUE TITLE
GUI: pullrequesting everything

### ISSUE THREAD

**Issue by cyruszzhou** [uchicago-cs/chiventure#1509]
We have developed our features in a separate folder on a separate branch. Now we need to pullrequest everything into the dev branch. It is thus necessary to create new branches that contain every step of pullrequest in order for everything to be pull requested in different steps.

**Comment by cyruszzhou** [comment]
I have submitted pullrequests for raylib tweaked version, part1 of scene_graphics, and part1 of quest_graphics. I am waiting for the review.

**Comment by cyruszzhou** [comment]
Seems like we need a better way to figure out how to incorporate the tweaked version of rayilb

**Comment by cyruszzhou** [comment]
I have also pull requested input_box_graphics

**Comment by cyruszzhou** [comment]
Previous versions returns 1 and 0 instead of SUCCESS and FAILURE, and some pullrequests involve undesired DSStore. I have now resolved these issues.

**Comment by ukanyanwu** [comment]
On Wednesday, @csraffaga and I were able to make pullrequests for the second parts of map_graphics and scene_graphics. After making changes that @philipchenaux requested of us, they were successfully pulled into the dev branch of chiventure.

**Comment by csraffaga** [comment]
Pull requests required the compilation of multiple makefiles in addition to refining code and tests etc... For each of the modules pushed our code built successfully and performed as desired. This issue can be closed.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great job, but I would have liked to see some tangible outcomes on some of the updates.
