### ISSUE TITLE
Write find_room fxn for UI

### ISSUE THREAD

**Issue by a-matai** [uchicago-cs/chiventure#151]
Given game struct and direction, return pointer to room struct

**Comment by a-matai** [comment]
This issue has been dealt with with the following steps:

- created a path_to_room function that takes in a room and direction and returns path
- created a find_room_from_path that takes in path struct and returns room associated
(this included a helper function that can find a room from the list of all rooms given a room_id
- created an abstract function that finally took in a game struct and direction, returning the room associated with that function

Testing for this function will be an additional issue.

**Comment by a-matai** [comment]
After closing, we received request for the function to work given any ptr to room. Have updated to do so.

need to update documentation so will keep open.

**Comment by a-matai** [comment]
@omorkved An update!

We'll be updating the path struct to simply have pointer to the room in dest given direction, instead of a room_id. This shouldn't affect your end, really, but wanted to let you know!
Will complete soon.

**Comment by omorkved** [comment]
hello! @a-matai Any estimate on when this will be put into a PR to master? Is this on-track to be included in the prototype at the end of this sprint? Thanks!

**Comment by a-matai** [comment]
@omorkved hey, yes! We had to refactor our code so that the path struct has the room pointer stored in it. I'm working on it right now. 
The major change is that the path struct will now give you a room pointer so that reduces all the functions.

To make sure, I think you need this function?
- Given room and direction, return ptr to room in that direction.

Do you need it abstracted further?

**Comment by a-matai** [comment]
Function written:
room_t *find_room_from_dir(room_t *curr, char* direction) 

found in game.c.

Will update documentation shortly.

**Comment by omorkved** [comment]
> @omorkved hey, yes! We had to refactor our code so that the path struct has the room pointer stored in it. I'm working on it right now.
> The major change is that the path struct will now give you a room pointer so that reduces all the functions.
> 
> To make sure, I think you need this function?
> 
> * Given room and direction, return ptr to room in that direction.
> 
> Do you need it abstracted further?

That's perfect! (At least on the assigning-coordinate end of things). If the directions are sent in as strings, is there a comment in the code on how we should capitalize everything? Thanks

**Comment by a-matai** [comment]
ALL WRITTEN YAY @omorkved .

Documentation is also updated, all the functions are in room.c! Please let us know if this is not what you want. 

Final function that you need:
room_t *find_room_from_dir(room_t *curr, char* direction)

Other helpers in case you need:
room_t *find_room_from_path(path_t *path);
path_t *path_search(room_t *room, char* direction);

There is also a find_room in game.c in case you have a room_id. 
room_t *find_room(game_t *game, char* room_id)

**Comment by Sshatzkin** [comment]
What are the allowable input direction chars for find_room_from_dir()? 'n','s','e','w'?

**Comment by a-matai** [comment]
Uhhh we don't have restrictions! WDL's spec does.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by lydiafilipe** [comment]
Issue Score: ✓

Comments:
Good work and discussion. It would have been good to see some of the other issues, files, and pr's being mentioned to be directly linked from the comments. Also, it would have been good to see some more fine-grained updates- e.g. after each helper function was created. The summary should be a full sentence and should probably mention that the new room is based on the direction (I know it is implied but it's good to have that detail).
