### ISSUE TITLE
Create a Wiki page for Action Management's action functions

### ISSUE THREAD

**Issue by HarrisonD123** [uchicago-cs/chiventure#1512]
We've noticed that sorting through the actionmanagement module took a significant amount of time, given the lack of documentation. It will be beneficial to future actionmanagement teams for us to create a Wiki page for each of our action functions, especially as more are added in the future. This page will describe how values are passed into each of `do_item_action,` `do_path_action,` `do_item_item_action,` `do_self_action,` and basic functionality. A huge point to highlight is how at the basic level action management collaborates with CLI within the code base.

**Comment by HarrisonD123** [comment]
After thinking about it a bit, we plan on breaking each function explanation into a parameters section and a "how it works" section. It will be separated into multiple subheadings and bullet points.

**Comment by HarrisonD123** [comment]
### Closing Statement
We were able to write up an [entire wiki page](https://github.com/uchicago-cs/chiventure/wiki/Action-Management-~-Do-Action-Functions) describing the functionality of our action functions. We ended up describing the first three action functions as best we could. Our description of the new do_self_action is written much more in-depth, but framed as a work in progress. We made sure to include descriptions of each of `view stats`, `view quests`, `view skills`, and `view inventory`. Our hope is that many more self actions will be implemented in the future. I wonder if anyone will look at these anymore. Curious to see if Chiventure is fully revamped in Python or something.

Harrison, Kendrick, and Don all worked on the descriptions of functions.

**Comment by ecoble** [comment]
Issue Score: Excellent

Comments:
Nice work creating documentation for your new functions! I am sure this will be helpful to future teams.
