### ISSUE TITLE
Design and implement a hostility_level conversion function and a tone_t struct for dialogue provocation of conditional_friendly NPCs

### ISSUE THREAD

**Issue by emilybae1705** [uchicago-cs/chiventure#1514]
Currently the `hostility_t` enum includes three types of NPCs: FRIENDLY, CONDITIONAL_FRIENDLY, and HOSTILE. As stated in our [design document](https://github.com/uchicago-cs/chiventure/wiki/NPC-~-NPC-Battle-Integration-Changes-Design-Document) FRIENDLY NPCs will remain friendly throughout the game, players can provoke CONDITIONAL_FRIENDLY NPCs into becoming HOSTILE, and HOSTILE NPCs are mainly fighters that can challenge players to a battle. We plan to use NPC dialogue structs to lay out the situation of a player provoking a CONDITIONAL_FRIENDLY NPC. To make this plan more concrete, we will design a hostility_level conversion function that converts a CONDITIONAL_FRIENDLY NPC into becoming HOSTILE as well as a `tone_t` struct (exact struct name and content is subject to change after team-wide meeting) that identifies a tone a player is speaking in and if it is generally negative (ex. ANGRY, ANNOYED, etc.) then the conversion function will be invoked such that the CONDITIONAL_FRIENDLY NPC will become HOSTILE and challenge the player to a battle.

**Comment by srydbergcox** [comment]
The function to change `hostility_level` has been added, it is called `make_npc_hostile()`. It was straightforward, now we can focus on integrating with the dialogue to figure out when this function should be called.

**Comment by sglenn-uchi** [comment]
We successfully implemented the convert_hostility and the tone_t struct and created a pull request. We ran into a problem where a teammate's commits from another branch ended up on ours and are trying to use revert to remove them. As of now, we're working through a lot of merge conflicts, but when they're solved and the PR goes through, this issue will be closed automatically.

**Comment by emilybae1705** [comment]
All chiventure files and example files build successfully and all tests pass. In order to solve the problem of having another teammate's commits show up on our npc/dialogue-provocation branch, with our TA Lily's approval, I created another called npc/npc-provocation and set HEAD as the latest commit on our previous npc/dialogue-provocation branch. However, our teammate's commits for the demo branch still showed up on the new branch, so I'm trying to find a way to have only my commits for the `tone_t` and `change_npc_hostility()` function show up on the PR. Once we resolve this problem, this issue will be complete.

**Comment by emilybae1705** [comment]
We decided to keep the same npc/dialogue-provocation branch but I `reset --hard dev` which cleared all previous commits and reset commit history to dev HEAD. I committed the same set of changes I made before but on the newly reset branch so npc/dialogue-provocation now only contains the commits related to `hostility_level` conversion and the `tone_t` struct. Specifically, We added the `change_npc_hostility`, `make_npc_hostile`, and `make_npc_cond_friendly` function as well as the `tone_t` struct and made associated changes to different files using these functions and struct.

**Comment by emilybae1705** [comment]
We created a [design document](https://github.com/uchicago-cs/chiventure/wiki/NPC-~-NPC-Battle-Integration-Changes-Design-Document) that details the changes we planned for creating a `tone_t` struct and hostility conversion function. Following this document, we implemented those changes by making a `tone_t` enum in `dialogue.h` and creating `make_npc_hostile()`, `make_npc_cond_friendly()`, and `change_npc_hostility()`. The two functions `make_npc_hostile()` and `make_npc_cond_friendly()` are called in `change_npc_hostility()`. As for calling `change_npc_hostility()`, we were planning on integrating it with `add_start_battle()` in `dialogue.c` which is currently designed to add a `START_BATTLE` action to a node during a conversation. It hasn't been implemented yet so we left a note for future implementation that `change_npc_hostility()` can be called in the function such that if the NPC becomes HOSTILE due to a NEGATIVE tone in the player's edge, `START_BATTLE` is added to the NPC's node. (Note: `edge_t` reflects player's dialogue and `node_t` reflects NPC's dialogue in a conversation struct `convo_t`). As such, calling `change_npc_hostility()` is left as a TODO for future implementation. By adding these functions, it's now possible for a player to provoke a CONDITIONAL_FRIENDLY NPC by talking in a NEGATIVE tone, which triggers the NPC to convert `hostility_level` to HOSTILE in `change_npc_hostility()`. According to our design, FRIENDLY NPCs remain FRIENDLY throughout the game, not being able to change hostility_level. HOSTILE NPCs can become CONDITIONAL_FRIENDLY once the tone becomes POSITIVE.

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this issue! The summary, updates, and closing are very thorough. The issue was closed before it was actually done. Remember that a PR resulting in code should be closed automatically when its PR is merged.
