### ISSUE TITLE
Create Tests for Item Inventory Conditions

### ISSUE THREAD

**Issue by sabinecodes15** [uchicago-cs/chiventure#1516]
Issue #236 allows game developers to specify items that players must have in their inventory to perform certain actions. This functionality needs tests to ensure that inventory conditions are properly created. The current issue will be closed when these tests are implemented

**Comment by sabinecodes15** [comment]
While looking at ways to implement these tests, we realized there were some redundant function calls in the wdl test functions. We're refactoring the code to define the `__get_doc_obj()` function in a header file included by all the tests (rather than having each test copy the function), and adding the parameters "name" and "file_path" so each test file can specify what file they'd like to parse.

**Comment by HarrisonD123** [comment]
We created a new `test_wdl.c` file to hold the implementation of the `__get_doc_obj()` function. We figured out that the new .c files we created needed to be added into the `CMake` file for `tests/wdl.` We added `test_wdl.c` and `test_conditions.c`

**Comment by sabinecodes15** [comment]
In `test_conditions.c`, we created a new function `conditions_check()` as a helpful generalization of conditions test. In subsequent tests, we can use this function to specify an item and one of its associated actions to check, and `conditions_check()` will verify that the list of conditions provided in the wdl matches the list of conditions allocated to the action when the game is loaded. 

Now that PR #1492 has been integrated, we can ensure that these tests work; currently, the function is having issues parsing the wdl and building the game. This may be because we are passing a wdl file rather than a wdz file into the `__get_doc_obj()` function; more investigation is needed to verify this.

**Comment by sabinecodes15** [comment]
The above issue was resolved by using `load_obj_store()` in place of `__get_doc_obj()`. With this change, three of the four conditions tests that we wrote are now passing. We're currently still getting the following issue: 

"Assertion failed: Action TAKE for item TABLE has no conditions specified in wdl, but action condition list is not NULL"

There _is_ a condition specified in the wdl, so I'm not sure why it's not being found by the tests. We need to dig into this more, but once this is resolved we should be good to open a PR.

**Comment by sabinecodes15** [comment]
The issue was resolved- it turns out there were a few errors in the way I was parsing the WDL fields in the test. 
- I needed to ensure that any string comparisons were being done between strings of the same case (e.g. two completely lowercase strings), so I added `case_insensitized_string()` where applicable.
- I had to iterate through the list of actions to find out which one matched what I was looking for (`obj_get_attr()` was not sufficient when the value I was searching for was a value, rather than a key)

Now that this has been addressed, the approval of PR #1576 will close this issue.

**Comment by sabinecodes15** [comment]
### Closing Statement
Tests for inventory conditions have been fully implemented and integrated with chiventure, so the issue is now closed.
Harrison consolidated the __get_doc_obj() function into a header file, I wrote the tests, and we both debugged merge issues in the PR.

**Comment by ecoble** [comment]
Issue Score: Excellent

Comments:
Excellent work! Great job on thorough updates as well!
