### ISSUE TITLE
Implement Testing for speed auto_gen_movement functionality inside test_npc_move.c

### ISSUE THREAD

**Issue by Vincent-Zhang4135** [uchicago-cs/chiventure#1519]
In Issue #1306 , we adjusted the auto_gen_movement() function in npc_move.c to include a multiplier based on the speed stat of the NPC's class that affects the time spent in each room on an indefinite movement path. The corresponding test Test(npc_mov, auto_gen_movement_indefinite) does not currently account for the implementation of this feature and is thus crashing, so we have commented it out for now and are creating a new issue to adjust this test so it correctly tests the implementation of this new feature. The testing for the auto_gen_movment of NPC_MOVEMENT_INDEFINITE broke after we changed the implementation of how speed is generated. 

We have decided to repudiate these tests to reflect the changes we made from a previous issue

**Comment by Vincent-Zhang4135** [comment]
As a part of PR #1458, william has also been able to fix the NPC_MOVEMENT_INDEFINITE test by changing the time parameter to be double, and initatializing a `stat_global_t` and changing the `room_t` room to get a generated one rather than testing aut_gen_movment on all_rooms separately. This test now pasts due to Williams fix, and as a result we will be closing this Issue now.

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this issue!
