### ISSUE TITLE
Cli: Implement Suggestions for not found commands based on Levenshtein distance

### ISSUE THREAD

**Issue by mrestuccia1** [uchicago-cs/chiventure#1520]
Currently, when a command is not found in Chiventure a function is called to give suggestions. These suggestions are calculated simply by comparing characters. However, this is not a very accurate method, as length can also play a part in similarity. As such, we aim to implement a fuzzy search system (specifically Levenshtein's Distance) in order to better predict what word a user might have been trying to input, and suggest it.

Assignees: Miles, Matteo

**Comment by mrestuccia1** [comment]
The formula I used for this task was this one:

![6224efffbe9a4e01afbddeeb900bfd1b3350b335](https://user-images.githubusercontent.com/102557721/169674041-7bfa068d-6773-4d2f-bbb0-e374dbc56255.svg)

Linked here:

https://en.wikipedia.org/wiki/Levenshtein_distance

This clearly lent itself to recursion, so I started editing the suggestions operation in the src/cli/scr/operations.c file. I quickly noticed I needed to make a helper function, called Levenshtein. Here is that function. To write this function, a helper function that took the minimum between three values was helpful. Since it is not a built-in function in C, I built it from scratch. In the comment below I will upload the code for both the Levenshtein and the mini helper functions. Below are the helper functions, in a .pdf file:

[Helper_Functions_Operations.c.pdf](https://github.com/uchicago-cs/chiventure/files/8748600/Helper_Functions_Operations.c.pdf)

**Comment by mrestuccia1** [comment]
Finally, I simply built  function that repeatedly called the Levenshtein helper, for each of the 29 commands, and then picked the one with the lowest score as the suggestion. Below is the code for this:

` // This function returns a string which is the suggestion
  // It finds the suggestion by using Levenshtein's
  // Distance formula linked here:
  // https://en.wikipedia.org/wiki/Levenshtein_distance

char* suggestions(char *action_input, char** actions)
{

    int min = levenshtein(action_input, actions[0]);
    int index = 0;
    for (int i = 1; i < NUM_ACTIONS; i++) 
    {
        int temp = levenshtein(action_input, actions[i]);
        if (temp < min) 
        {
            min = temp;
            index = i;
        }
    }
    return actions[index];

}`

**Comment by mrestuccia1** [comment]
After implementing requested edits, which mostly consisted of style comments, we got our PR reviewed by Faruk, and subsequently approved by Jack, who merged it into the main branch. To illustrate the difference between the previous suggestion system and ours, here is a screenshot of the old suggestion system (on top), and the new one (onthe bottom):

![Screenshot (12)](https://user-images.githubusercontent.com/102557721/170841343-562395aa-5731-4e94-88af-86b249ccce7f.png)
![Screenshot (13)](https://user-images.githubusercontent.com/102557721/170841378-a5bf0392-9927-4c38-8326-bb1995a11f99.png)

**Comment by mrestuccia1** [comment]
The main advantage of this new system is that it doesn't break when the first letter doesn't match the suggestion, and thus still suggests something useful. With the old system, if you wrote the first letter wrong, the suggestions would be of no help.

**Comment by mrestuccia1** [comment]
This issue can now be closed, since we implemented the intended suggestions system, based on the Levenshtein Distance formula (linked above). This calculates the number of changes it would take to get two words to equal each other, so the lower the score, the more similar the words are. For this task, both Matteo and Miles worked on implementation and testing, and Matteo worked on the documentation.

**Comment by jacknugent1529** [comment]
Issue Score: Excellent

Comments: Excellent work on this issue! The updates are detailed and demonstrate your progress and the usefulness of this feature.
