### ISSUE TITLE
Reformat player stat representation in WDL

### ISSUE THREAD

**Issue by csraffaga** [uchicago-cs/chiventure#1521]
As it stands, it is unclear where the author can specify what the default statistics of a player are, whether it should be in the WDL or the GDL, how they should be represented, and how to track which player statistics are going to be displayed on screen with the scene. I need to meet with action management to understand the broader implementation of statistics in the game from the WDL and how to translate that information into a statistics_display struct as well as determine what is missing from the WDL. This will allow us to reorganize and enhance author specifications by editing the GDL, WDL, and player statistics modules.

**Comment by csraffaga** [comment]
After conversing with @jbrouwer5 20 minutes ago, there is no indication of statistics in the WDL. Therefore, the GDL is not able to customize in-game statistic visuals as there is nothing to base a customization off of. A first step is for a game state team to implement some facility for authors to specify the statistics that are included in a game. From there, the GDL has been pre-designed to read certain statistics from the game-state. In the future, groups will need to implement and test the functions that would implement GDL stat customizations. For the time being, the foundation has been laid.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great job on this issue -- simple but important!
