### ISSUE TITLE
Research Previous Implementation of Lua in WDL

### ISSUE THREAD

**Issue by RamarkoB** [uchicago-cs/chiventure#1524]
As of right now, all custom scripts are run at initialization. Our goal as custom-scripts to make actions more dynamic, and so we want the custom scripts to instead be called when the function itself is called. To deal with this, we want to store custom scripts within WDL, so that the custom scripts will only be callled at runtime

**Comment by RamarkoB** [comment]
There are past examples of Loading Lua into the WDL, for which we can find documentation [here](https://github.com/uchicago-cs/chiventure/wiki/WDL-~-Lua-Scripting-and-WDL) and [here](https://github.com/uchicago-cs/chiventure/wiki/WDL-~-Current-Integration-in-Chiventure)

**Comment by RamarkoB** [comment]
As of right now, I am attempting to create a demo by storing a custom action into the WDL, but I'm struggling with compiling the game while including "load_game.c"

**Comment by RamarkoB** [comment]
Splitting up this task into multiple tasks to simplify keeping track of progress on integration of Lua into the WDL. As of right now, we were able to find previous integration of loading Lua into the WDL, for which we can find documentation [here](https://github.com/uchicago-cs/chiventure/wiki/WDL-~-Lua-Scripting-and-WDL) and [here](https://github.com/uchicago-cs/chiventure/wiki/WDL-~-Current-Integration-in-Chiventure). Marking this issue as closed for right now, and moving into looking into extending future integration of WDL and Lua

**Comment by ecoble** [comment]
Issue Score: Excellent

Comments:
Nice job researching this task!
