### ISSUE TITLE
GUI: writing new/init/free functions and testing for npc_graphics

### ISSUE THREAD

**Issue by cyruszzhou** [uchicago-cs/chiventure#1525]
We are now trying to write new/init/free functions for the npc_graphics module and will test them. This is done to benefit future development and for the whole module to be able to be pulled into the dev branch. This would also make eyeball testing on the module much more convenient.

**Comment by cyruszzhou** [comment]
We have finished writing new/init/free functions and we are waiting for tests to be finished. NPC_graphics structs are relatively complicated so this may take a little bit more time.

**Comment by ukanyanwu** [comment]
Tests have been written for the original structs available in the npc_graphics module, but a new struct, npc_graphics_t, has been added recently that compiles information into a struct that hold relevant information when using the draw_npc function. This struct is currently having its tests written to confirm whether its current new/init/free functions are written correctly.

**Comment by cyruszzhou** [comment]
We have successfully written all functinos and tests! We close this issue with success.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great job on this issue!
