### ISSUE TITLE
Create a design document for tests for run_battle

### ISSUE THREAD

**Issue by nicholaswlee** [uchicago-cs/chiventure#1528]
For this issue, we will create a design document in the Wiki that will lay out tests for the new functions that were implemented for the new run-battle function. Each module will have the new functions laid out, as well as a brief description of what needs to be tested. A few features we will need to test is whether CLI works properly, printing is correct, correct items and moves were selected, and many more.

**Comment by emiliolevinspage** [comment]
We have outlined the modules and functions to test, as well as where those tests should go.

**Comment by aliu65803** [comment]
We have created a Wiki document with our modules and functions to test, which can be found [here](https://github.com/uchicago-cs/chiventure/wiki/Battles-~-Run-Battle-Testing-Design-Document).

**Comment by aliu65803** [comment]
We are now closing this issue since we have created and fleshed out the intended design document. Now, it will be easy for whoever implements these tests to view all they need to test in one document.

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this issue!
