### ISSUE TITLE
Implement and Update Battle Tests for Stat, Move, Item, and Equipment Changes

### ISSUE THREAD

**Issue by corian-jal** [uchicago-cs/chiventure#1529]
We will update existing and create new battle tests to accommodate all of our changes and additions over the course of the quarter, to culminate in a pull request.

Members: Nicholas, Fatimah, Nafis

**Comment by corian-jal** [comment]
test_battle_ai.c has been updated and a new test_battle_common.c/.h file was created to house functions and static information I plan to reuse in other tests, but no pushes have successfully compiled due to numerous compilation and unexpected signal errors. Given the time left before the code freeze and the projected number of line changes, Nicholas and I are planning to meet later today and discuss possibly prioritizing specific tests and/or testing functionality in other ways.

**Comment by nicholaswlee** [comment]
Because we are realizing that there a lot of tests we will be prioritizing these four files: battle_flow.c, battle_ai.c, battle_print.c, and battle_logic.c

**Comment by corian-jal** [comment]
We have pulled and resolved merges with the files pushed to the dev branch earlier today and are now working to integrate them while solving previous and new compiling and linking errors.

**Comment by corian-jal** [comment]
All of the tests we decided to prioritize have been added and updated, and the code compiles. We are now simply resolving criterion crashes and assert failures.

**Comment by nicholaswlee** [comment]
All issues have been resolved and a PR has been submitted. We have made tests for battle_print.c, battle_ai.c, battle_logic.c, and battle_flow.c. Our design document has tests outlined for other files, but we were not able to complete it for this sprint.

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this issue! The summary for this issue is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/issue-pr-grading.html#descriptive-summary for examples).
