### ISSUE TITLE
GUI: writing tests for map_graphics

### ISSUE THREAD

**Issue by cyruszzhou** [uchicago-cs/chiventure#1532]
The structs and new/init/free functions for the map_graphics module have been written. I am now trying to write tests for these functions. This would not only benefit future development by formalizing the whole process, but also yield an advantage when it comes to testing the run_map_graphics function. This is also necessary for the whole module to be pullrequested.

**Comment by cyruszzhou** [comment]
I have written tests for the funcrtions and I debugged the functions based on the testing results. Now they all seem to pass! I believe they are in a good shape to be pull requested. We are still waiting for gdl module for these functions to be truly completed. But as for now we can first pull request this in.

**Comment by cyruszzhou** [comment]
This issue has been closed. We are waiting for the pull request to make further progress.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great work, but I would have like to see a more detailed summary explaining what exactly you intend to test.
