### ISSUE TITLE
Document the use of conditionals field for actions in prior action-management demo (spring 2020) 

### ISSUE THREAD

**Issue by jackjackkimkim** [uchicago-cs/chiventure#1535]
Description: Upon looking through previous demos for any implementations of conditionals for actions, we came across 2020 action-management team's demo which tried to hard code a conditional attribute to actions. We were particularly interested in their add_inventory_conditions function which required an item in the inventory before performing an action. This will be particularly useful if it can be implemented as our demo will utilize the same concept to allow users to open a certain door only when a certain object is present in their inventory.

**Comment by jackjackkimkim** [comment]
Instead of using the 2020 Demo from the action management team, we decided to take the inventory condition implemented by this year's action management. The current implementation involves putting in the inventory conditional in a WDL file and works perfectly with what the custom scripts team demo needs.

**Comment by ecoble** [comment]
Issue Score: Excellent

Comments:
Nice job researching past work, even if you ended up not utilizing it I hope the information was helpful!
