### ISSUE TITLE
GUI: writing new/init/free and tests for input_box_graphics

### ISSUE THREAD

**Issue by cyruszzhou** [uchicago-cs/chiventure#1540]
We have already written a top-level struct for input_box_graphics. To pull request the input_box_graphics we need to write new init and free functions for this struct. We also need to test that these functions work correctly. Proper documentation would also be required for this to be a part of the holistic program. It is also important for us to follow the standard of the whole program in implementation.

**Comment by cyruszzhou** [comment]
I have successfully written new/init/free functions for this module. I have also written tests for them and they all passed. What is noteworthy (for future reference) is that the color struct in raylib has fields following the order of r,g,b,a, and to test them we need to cr_assert_eq for each field.

**Comment by cyruszzhou** [comment]
This issue is currently closed, and we look forward to the pull request.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great work, but I would have like to see a more detailed summary explaining what exactly you intend to test.
