### ISSUE TITLE
Making sure Header Files are Properly Defined and Terminated

### ISSUE THREAD

**Issue by bvvill** [uchicago-cs/chiventure#1542]
Recently, I've realized that my habit of deleting any empty lines at the end of a file could cause problems with many historical Unix utilities. So, I've decided to take it upon myself to go through every header file in chiventure has a newline at the EOF and is properly defined with `#ifndef ... #define ... #endif`

**Comment by bvvill** [comment]
To summarize, the changes made in this branch were to ensure that the header (AKA `*.h`) files within chiventure are properly defined and terminated with `#ifndef`, `#define`, and `#endif` statements, followed by a newline at the EOF, such as:
```
#ifndef  HEADER_FILE_H   // insert header file name here
#define HEADER_FILE_H
...
...
...
#endif /* HEADER_FILE_H */

```
This was done in order to avoid possible issues with legacy / historical UNIX utilities and to help optimize compiling so that headers aren't defined multiple times

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this (minor) issue!
