### ISSUE TITLE
percentage based autogeneration of rooms

### ISSUE THREAD

**Issue by lukasg8** [uchicago-cs/chiventure#1546]
Based on the review of our Static Game Autogeneration Design in #1351 we decided to change the logic of the function roomspec_autogenerate so that it considers the entire list of roomspecs and is fair to the edges for each room without prioritizing the rooms which are located earlier in the list. 

The current implementation randomly generates a number from the number of roomspecs in the list which therefore does not consider the higher weightings of some of the roomspecs in the list. 

Furthermore, since it iterates through the list and if `randomint>=row[count]` then `randomint-=row[count];`, this creates a problem where for example, randomint = 5 and count[1] = 4. Therefore, randomint changes to 5-4 = 1. But count[2] = 3. Therefore, it would have been not been selected as the roomspec. Simply put, this method prioritizes rooms earlier in the roomspec list.

**Comment by williamhu314** [comment]
The function has now been updated to account for percentage based roomspec generation (the denominator has effectively been changed from the number of roomspecs to the sum of the values in the appropriate row of the adjacency matrix).

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great job on this issue -- simple but straightforward.
