### ISSUE TITLE
Reach out to open world team to discuss potential collaboration

### ISSUE THREAD

**Issue by calvinytcheong2020** [uchicago-cs/chiventure#1547]
Description: Custom scripts would ideally provide game developers with more versatility, with varying interactions between items and locations (and other aspects of the game state). As a prelude to the full integration of custom scripts into Chiventure (a task which could be taken up by a future team), we decided to reach out to the open world team, since customization could prove useful in an open world setting. For example, rooms far apart could be linked via an item, or perhaps an item could be used to bypass a room's difficulty threshold (as defined by their roomLevel struct).

This issue will be complete when we have either collaborated and determined a plan to move forward with the open world team, or we have collectively decided that our features would be incompatible.

**Comment by mxu24** [comment]
Discussed potential collaboration ideas through Slack with the open world team, but decided not to proceed due to time limitations for both teams. We may move this issue to the backlog for future years.

**Comment by ecoble** [comment]
Removing milestone as this issue was not completed and will be ungraded.
