### ISSUE TITLE
sound: fixing sound module warnings

### ISSUE THREAD

**Issue by JaStarbuck** [uchicago-cs/chiventure#1551]
The sound.c file that was pushed to dev accidentally compiles with warnings. the task is to fix the code in sound.c so the warnings are removed. By removing the warnings while maintaining the structure and integrity of the code, we will be able to write more functions to increase functionality of the sound module while keeping the same coding philosophy used in the sound load/free/play functions. Also, later groups and other groups that want to use the sound module will be able to use these functions without running into unresolved issues within the code.

Assignees: Jason, Victor, Jake

**Comment by JaStarbuck** [comment]
From initial inspection, it looks like everywhere sound->name was passed into one of the Mix... functions it gives an error. sound->name is of type char* (a string) but the functions need type struct Mix_Chunk*. The next step is to find out what is needed instead of the name of the sound to be passed into these functions.

**Comment by JaStarbuck** [comment]
I've created a new branch for this issue called sound/warnings

**Comment by JaStarbuck** [comment]
After some playing around, there are a few observations I've made:
The load and free functions cannot just return integers. Loading the sounds in the demo produce structs depending on whether they are background sounds or sound effects. These structs are then passed into the play function. So, if we are to make separate load and play functions, we would need the load function to return the struct (different type of struct depending on whether its music or a sound effect!) so that it can be passed into the play function. Obviously, this is an issue because I'm not sure if we can have conditional returns in C. 
So, we can make separate load/free/play functions for whether it's music or a sound effect (this makes it the developers job to know what type of sound they're using so they use the correct function, which, after writing this out, doesn't seem too bad or like too much to ask of chiventure users), or we can consolidate the load/free/play function into one big function in sound.c (this seems not ideal since this would likely make it much harder to implement new features like stop/pause) just like in demo.c.

**Comment by JaStarbuck** [comment]
Instead of conditional returns, I've instead created a union that can contain either a sound effect or music. This will make it easier to be able to distinguish between sound types in later functions. Some playing around with the inputs to the free function was needed to get it to work and the load function now returns the union called sound_type_t.

**Comment by JaStarbuck** [comment]
After creating the union and fiddling with the inputs to various functions, I have a version which returns no warnings or errors. I have submitted a merge request to merge the branch sound/warnings to dev.

From the pull request, thought it'd be helpful here too:
As Rhea said, this comment will be about what was changed that helped with the error: Originally, we were passing in the string name of the music to the function to play the music. This was incorrect as it needed the music struct to be passed into it. Then, the problem we experienced was that we needed to distinguish between the music struct and sound effect struct being passed into the built in SDL functions. This is why we created the union so that either the music or sound effect struct was contained and could thus be conditionally passed into the SDL functions. Then any other changes were just fixing the functions so that they were returning/taking in the correct structs and unions.

**Comment by jwschroeder21** [comment]
Update: Linked pull request #1583 to this issue, merging on the development front.

**Comment by JaStarbuck** [comment]
Closing statement: The changes made to the sound module have successfully been merged into dev. Adding the union will prove to be very helpful in the future as it will help us and other groups more easily distinguish music and sound effects in game without making the implementation of those overbearingly difficult. We will still need to test these functions in the future and also find a way to potentially implement these into the demo or chiventure as a whole. We will also be able to use the union to help with the structuring and creation of new functionality such as pause/stop.

**Comment by ecoble** [comment]
Issue Score: Excellent

Comments:
Great job debugging this issue and adapting your code along the way! Nice job updating the issue too!
