### ISSUE TITLE
cli: document changes needed to implement `view quests` group of commands

### ISSUE THREAD

**Issue by majorsylvie** [uchicago-cs/chiventure#1554]
the quests team wants to implement a group of `view quests` commands. 
This task will be do document what team needs to do what because the implementation of a 4th kind of action makes what the quests team wants more complicated to implement, and by meeting and documenting, we avoid having integration issues between the involved teams

**Comment by majorsylvie** [comment]
We have scheduled a meeting between reps from each team after our team meeting 5:30pm May 23rd!

**Comment by majorsylvie** [comment]
https://docs.google.com/document/d/1XEtIJlm0A2CyZ-WRf0a7PABN_FjYQ_BLR5ccnZuM8H4/edit?usp=sharing
Here is the shared google document to be used during the meeting for notes!

**Comment by majorsylvie** [comment]
We met with AM and Quests and made this google doc:
https://docs.google.com/document/d/1XEtIJlm0A2CyZ-WRf0a7PABN_FjYQ_BLR5ccnZuM8H4/edit?usp=sharing
We all specified what each team needs to do, on our end we need to:
* update the call to `do_self_action` to take in a target array of strings instead of an individual string
* pass in the tokenized string array (minus the first term) into `do_self_action` as the target
* remove the check from `kind4_action_operation` that doesn't run `do_self_action` if there are more than two arguments being passed into it

**Comment by majorsylvie** [comment]
Documentation is complete! All the teams know what they need to do, and we will now be implementing!

Faruk organized the meeting
Faruk, Brianna, and Kate all spoke at the meeting to clarify what needs to be done by each group

There should not be any more documentation to do on our end, closing

**Comment by jacknugent1529** [comment]
Issue Score: Excellent

Comments: Nice work on this issue! Keep in mind that google docs doesn't work very well for documentation purposes. This is explained in the pr grading page:
> While using Google Docs to sketch out some of the documentation, you should avoid posting links to those Google Docs from an issue, as it may cause confusion as to whether that document (or some future update to the wiki) is the most up-to-date version of that documentation. You should instead transfer the contents of the document to the wiki, and then link to the wiki when updating the issue.
