### ISSUE TITLE
sound: DEMO

### ISSUE THREAD

**Issue by jiaoboxuan** [uchicago-cs/chiventure#1555]
Everyone is assigned, and this is not deemed as a part of Sprint 4. It's, however, a vital component of our final presentation.

**Comment by jwschroeder21** [comment]
We are having a great time with the text to speech feature and would love to incorporate it into our demo. Potentially, we can have classmates come up and write sentences to test text-to-speech implementation.

**Comment by JaStarbuck** [comment]
I'm creating a branch called sound/jason_demo for me to play around with and try to get stuff working

**Comment by sangerr** [comment]
This issue was generally for us to begin thinking about the demo, the more concrete issue that addresses this demo is #1437. I am closing this issue as it is no longer needed.

**Comment by ecoble** [comment]
Since this ended up being a duplicate issue, the milestone has been removed and it will be ungraded.
