### ISSUE TITLE
GUI: Preparing for the DEMO

### ISSUE THREAD

**Issue by cyruszzhou** [uchicago-cs/chiventure#1560]
We have written individual rungraphics functions. For the final presentation of this class, we need to create a demo that chains all modules. To have a good demo we would also like to collect relevant resources (images, texts, maps, scenes, etc.) and correct for concurrency issues.

**Comment by csraffaga** [comment]
Added a GDL file to the demo to showcase reading

**Comment by cyruszzhou** [comment]
We tried to implement a multithreading version of the demo, which can be found here[https://github.com/Cyrus-Zhou2302/GraphicsDemo.git](url), However, we decided to not continue with it as it may be too much work during the final week. We will try to go through each module instead in the final presentation. Each of us will be responsible for 1-2 modules as specified by the work split. We followed the tweaked version for presentation, and have noted down important points to make during the DEMO for our respective parts.

**Comment by cyruszzhou** [comment]
We close this issue as we are ready to go for the demo.
