### ISSUE TITLE
Update Documentation and Goals Page on Wiki

### ISSUE THREAD

**Issue by RamarkoB** [uchicago-cs/chiventure#1563]
Given that Custom-Scripts is more of an abstract goal for a team, we designed a [Goals Page](https://github.com/uchicago-cs/chiventure/wiki/Custom-Scripts-~-Goal) on the wiki early in the quarter. Moving forward, we should attempt to increase documentation of what we've accomplished and possible goals moving forward for future teams. Alongside this, it would be prudent to update the [documentation page](https://github.com/uchicago-cs/chiventure/wiki/Custom-Scripts-~-Using-Custom-Scripts) that contains information on how custom scripts works and how to use custom scripts. As we approach the end of the quarter, we should update both pages to make sure that future custom scripts teams can start off on the correct foot. This Task should be marked as complete when both pages have been updated

**Comment by RamarkoB** [comment]
The [goals page](https://github.com/uchicago-cs/chiventure/wiki/Custom-Scripts-~-Goal) and the [documentation page](https://github.com/uchicago-cs/chiventure/wiki/Custom-Scripts-~-Using-Custom-Scripts) have both been updated to include changes made by the custom scripts team over the course of this year, so that future teams have a better starting off point for custom scripts moving forward

**Comment by ecoble** [comment]
Issue Score: Excellent

Comments:
Nice job updating the documentation, I'm sure this will be helpful in the future!
