### ISSUE TITLE
Update Wiki with our final implementation status

### ISSUE THREAD

**Issue by helenastc** [uchicago-cs/chiventure#1564]
For this issue, we plan to add to the Openworld Source Document Wiki what we have accomplished this quarter. This includes updating the old speclist_t struct to a specgraph_t and writing new autogenerate functions. With this, we hope that the next openworld team can start working on this module right where we left off.

**Comment by rohandeme** [comment]
For this issue, we plan to add to the Wiki what we have accomplished this quarter. This includes updating the old speclist_t struct to a specgraph_t and writing new autogenerate functions. With this, we hope that the next openworld team can start working on this module right where we left off.

**Comment by rohandeme** [comment]
Updated the Openworld Source Document wiki to contain implementation information about the specgraph_t and coords_t struct. We also included areas of unfinished business, including WDL implementation and autogenerate functions.

**Comment by rohandeme** [comment]
Our implementation status has officially been updated in the wiki, under Openworld ~ Source Document. The wiki now contains information about the specgraph_t struct and coords, along with features that we hope the next team implements, such as WDL and autogeneration. We will continue to update this wiki in case we make any updates to our module.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great job on this minor issue!
