### ISSUE TITLE
Quests: Create Functions to work with CLI Output

### ISSUE THREAD

**Issue by Castel-Jaloux** [uchicago-cs/chiventure#1566]
Currently, the Quests module and Quest features have no way of being displayed in the actual Chiventure game through CLI. To remedy this issue, we need to work with the CLI and Action Management Teams. After meeting and discussing this issue with their teams, we determined which functions were necessary, and now implementation and testing are the only steps remaining.

**Comment by elizabethli31** [comment]
I wrote the function for taking a task and converting all of its elements into a string that can be displayed by action management/display

**Comment by JSerf02** [comment]
Researched a non-binary multitree printing algorithm, but it seems that this data structure is so complex that whenever people use it, they typically install a graphics library to display its contents. This seems like overkill for the time being, especially considering the graphics team is working on a function for this exact purpose (though it will likely not be ready in time for the final presentations), so I am going to instead implement a complex algorithm to display this tree instead.

**Comment by JSerf02** [comment]
Added functions to display the task trees! The display works by first figuring out the dimensions of the rectangular area of text where the tree will be created. Then, it creates 2 matrices to show where the tasks will go on the screen and which areas of the tree are connected. Then, the task matrix is iterated through to produce arrays of 3 strings called "blocks" that store the important info about each task that needs to be displayed. Finally, the algorithm puts these blocks in the correct places in a string along with lines denoting tree branch connections as denoted by the task matrix and the line connection matrix.

**Comment by JSerf02** [comment]
Debugged the task tree display function to fix memory leaks

**Comment by elizabethli31** [comment]
I fixed problems with the show_task function that resulted when certain elements (like missions or prereqs) were initialized as null. Also tested the function with print statements and it currently shows what needs to be displayed.

**Comment by charlieweiler** [comment]
Added show_quest function to print out the player's quest hash table, quest by quest with status and ID displayed. Also created a function for converting quest status enums to strings, which might be useful for other purposes. Each still needs to be tested.

**Comment by elizabethli31** [comment]
Finished up all the functions and tested by just printing the string. While writing the show_quests, show_task_tree, and show_task functions, we changed the quest_id max length from 100 to 50. Also, made a minor change to the player module in player_quests (changed completion type from int to completion_status). Our next steps now are to follow up with CLI and action management because their code depends on our functions

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Excellent job on this issue, but next time make sure to include a closing statement.
