### ISSUE TITLE
Quests: Design Demo Game

### ISSUE THREAD

**Issue by Castel-Jaloux** [uchicago-cs/chiventure#1567]
We need to create a demo game involving the quests module to display the functionality we have added to the quest module over the past quarter. Before we can make this game, however, we must design it. We need to create a common quest "theme" or "storyline" to improve the presentation's overall authenticity and audience engagement. Additionally, we need to plan how the different tasks and quests interact with each other, as well as with NPCs, items, and rooms within the game.

**Comment by JSerf02** [comment]
We designed the demo last Friday (forgot to update here) and needed to wait for NPC team and Action Management to submit their PRs before we could send ours

**Comment by JSerf02** [comment]
Got the demo pulled into dev!

**Comment by JSerf02** [comment]
We finished designing our final demo themed around vanquishing Steve the Dangerous: Master of Deceit and we got our demo pulled into dev!

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great work, but ideally the status updates should have something tangible to share!
