### ISSUE TITLE
Modify skill_node struct to include class prerequisites

### ISSUE THREAD

**Issue by wellingtj** [uchicago-cs/chiventure#1568]
Lets say someone was a warrior and a wizard. They can use fire and swords. Maybe they could light their sword on fire. Going along this intuition, it would therefore be cool to provide an implementation for skills that require more than one class. I therefore think it would be beneficial to include a field in the skill node struct for the required classes to use a skill, as well as the number of said classes. We then would need to change the corresponding functions that act on skill_nodes in order to maintain functionality

**Comment by nbilaver** [comment]
The changes outlined have been added, only task that could be added is related to the class_prefabs.c file in playerclasses, as it uses skill_node_new, and the usage of it looks like it could actually benefit from the addition of the new fields. Will contact people working on the file about potential changes.

**Comment by KabirDubey** [comment]
I was the chosen one for @nbilaver's mission. I added the new fields to the add_skill function and refactored the calls to add_skill accordingly. I also standardized 80 character lines in some places, but not everywhere. Next steps are for things to be finalized on playerclass' end.

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this issue! For a task of this size, we would've expected to see more status updates and/or status updates that were more detailed. Particularly, the final update seems to indicate that another update should have followed it.
