### ISSUE TITLE
Bring calculate crit out of battle_ai.c and instead have it be calculated in battle_flow to have crits be communicated to the user better.

### ISSUE THREAD

**Issue by nicholaswlee** [uchicago-cs/chiventure#1569]
The goal of this PR is to change our code to calculate critical damage in battle_flow.c. When creating the demo, we found that our print statements do not differentiate if our damage if calculated with or without a crit. We will also make it so that a different message will print if critical damage is successful. This will primarily change three functions, battle_flow_move, enemy_make_move, and print_battle_damage.

**Comment by nicholaswlee** [comment]
We are meeting and changing this now. Emilio and I have talked about how this will need to change to fully show how critical damage is working in a battle. I am handling the coding and Emilio is handling the compilation errors and testing.

**Comment by nicholaswlee** [comment]
The code itself has been implemented. Emilio will be doing the rest.

**Comment by nicholaswlee** [comment]
We have deleted the tests in battle_ai.c as crit is no longer calculated in damage.

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this issue!
