### ISSUE TITLE
 Update item struct and item_new function for WDL

### ISSUE THREAD

**Issue by bansals10** [uchicago-cs/chiventure#157]
The WDL team would like the item structure to contain the following fields:
- id
- short desc
- long desc
- state
- value
- list of actions

The specification for each of these can be found in the item portion of this document: https://github.com/uchicago-cs/chiventure/blob/wdl/improved_validation/docs/wdl.md

With this, we also require an item_new function that has the following signature:
item_t* item_new(char* id, char* short_desc, char* long_desc, char* state, char* value, action_list_t actions). 

As described in the specification above, the action_list_t may contain a list of the following struct:

typedef struct 
{
      char* action_name;
      char* text_fail;
      char* text_success;
      char* allowed;
      cond_list_t* conditions;
      set_list_t* set_items;
} action_t;

cond_t and set_t would be defined as follows:

typedef struct
{
     char* id;
     char* state;
     char* value;
} cond_t;

typedef struct
{
     char* id;
     char* state;
     char* value;
} set_t;

Please let us know if you have any questions.

**Comment by a-matai** [comment]
@bansals10 hey Shriya, did you check in with AM about the action_t struct? We would like to make sure the request is consistent with their needs!

Once you've verified with them that the action_t satisfies their needs as well we'll get on it.

Additionally, we are currently not using our condition_list_t in the path_t for this sprint until we're clearer on everyone's needs.

**Comment by MTUC08** [comment]
As we discussed on slack, the action struct is of the definition:

typedef struct
{
char* c_name; // the string name of the action
enum action_kind kind; // action_item, action_item_item, or action_path
} action_type_t;

However, we agree that the item struct should have:
 - an id // string name of the item
 - some sort of description of the item
 - a list of actions that can be done with the item

**Comment by MTUC08** [comment]
In addition, will WDL be dealing with actions like "look" or "examine" which only print the description of an item?

**Comment by bansals10** [comment]
Hi game-state,

WDL and Action-Management talked and we would like you to add the "in" and "list of action" fields into the item struct. The list of actions will be composed of action structs that action management has already created.

Thanks!

**Comment by bansals10** [comment]
Can you please also include the find_room function from game.c in game.h as well?

**Comment by lindsey-hsi** [comment]
Hello!

I'm working on implementing what you guys requested, but just wanted to run an idea by you. We have an attributes field already implemented in our item struct, and I think that the actions you want included can be very easily incorporated into this field. The attributes field is a hash table keyed by string names, and currently supports 5 different types of values. I think it would make a lot of sense to add the 3 kinds of actions as three new types in the attributes table. We have a number of functions to find attributes that you can use to find out what actions can be performed on an item. Please let me know if that works for you guys ASAP so that it can be ready for you to use in Sprint 3! Also, if the "in" field you specified represents the room that the item is in, we can't implement it due to the organization of our modules -- we do have a function to search a room's inventory for a specific item, hope that's okay!

**Comment by MTUC08** [comment]
I think, at least on the end of action management, that should be fine as long as you additionally provide a function that will taken in the said item and action and return whether the action can be used on the item, as per issue #172 @lindsey-hsi

**Comment by patrickkoopmans** [comment]
Functions for adding and checking the existence of actions associated with an object have been written. They are called add_allowed_action(item_t* item, char* action) and allowed_action(item_t* item, char* action) respectively. 

As requested from WDL and AM, add_allowed_action() returns SUCCESS or FAILURE depending on whether or not the action was successfully associated with the item, and allowed_action returns SUCCESS or FAILURE depending on whether or not the action is associated with the item. 

The interfaces for these functions are located in item.h, and both have been duly tested. 

Next steps: WDL and AM need to confirm that this issue can be closed, then I will initiate pull request.

**Comment by patrickkoopmans** [comment]
This issue is complete because, as per my last comment, WDL and AM have confirmed that the interface provided fulfills the function they require. 

Next steps: pull request to master

**Comment by lydiafilipe** [comment]
Issue Score: ✓+

Comments:
Good detail and discussion!
