### ISSUE TITLE
Move the npc/action implementations onto the stable branch with agent_t and submit a PR

### ISSUE THREAD

**Issue by junasano** [uchicago-cs/chiventure#1574]
Currently, the npc/action functions are on an unstable branch. The first step was to move a new agent struct onto the dev branch. And now that's complete, the next and last step is to move the remaining functions for npc/actions onto that stable branch.

**Comment by junasano** [comment]
A new branch was created based off of npc/actions_dev, which is the stable branch with the agent struct. This new branch is called npc/actions_final and this is where the npc/action functions will be implemented.

**Comment by junasano** [comment]
In the new branch, a couple of changes were made to some header files and the action functions were moved. It builds successfully and all of the tests pass. 
The next step is to make sure the functions are fully accurate and complete while waiting for the previous PR to be updated.

**Comment by junasano** [comment]
The previous PR was approved and we were able to move forward with the final steps before submitting a PR related to this issue. 
The PR is now submitted and once it is approved by a peer and TA, this issue will close automatically.

**Comment by junasano** [comment]
Another reviewer from team action management was added.

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this issue!
