### ISSUE TITLE
Tests for Room Module

### ISSUE THREAD

**Issue by a-matai** [uchicago-cs/chiventure#158]
Write criterion tests for all functions in our room module to ensure they are working and make necessary changes to functions that are broken.

**Comment by a-matai** [comment]
This issue was mostly writing a lot of tests, working out bugs in room.c. 

Key changes:
- updated init and new functions (standardised across all modules)
- worked out bugs in HASH_FIND functions (removed add_*_to_hash functions)
- added lots of tests!

**Comment by liuyifan-eric** [comment]
Macros for iterating the hashtables (that being said, users do not need to know we are using hashtables) are not tested yet. Need tests for ITER_ALL_ROOMS, ITER_ALL_PATHS, and ITER_ALL_CONDITIONS

**Comment by liuyifan-eric** [comment]
ITER_ALL_PATHS and ITER_ALL_CONDITIONS should be in test_path, so #138 need to reopened as well.

**Comment by liuyifan-eric** [comment]
Closing comment again:
This issue was mostly writing a lot of tests, working out bugs in room.c. 
Key changes:
- updated init and new functions (standardized across all modules)
- worked out bugs in HASH_FIND functions (removed add_*_to_hash functions)
- added tests for all the functions and macros in the room module

**Comment by lydiafilipe** [comment]
Issue Score: ✓

Comments:
Good work. It would have been good to make more progress updates and provide a bit more detail in your summary/closing as you were going through the issue. What bugs were you finding? How did you resolve them? What exact functions were you working on? Which ones were broken?
