### ISSUE TITLE
Changing inventory position elements in item_t struct from pointers to unsigned int

### ISSUE THREAD

**Issue by KendrickXie** [uchicago-cs/chiventure#1588]
The position elements in the item_t struct were originally for holding the coordinates of an item within an inventory, but the graphics team no longer requires these elements so we are removing them.

**Comment by KendrickXie** [comment]
Due to some miscommunication, I initially thought the elements for the positions in item_t should be removed entirely. Instead, the graphics team needs them to be unsigned ints rather than pointers.

**Comment by dhirpalshah** [comment]
We do not want there to be a pointer to an unsigned int because we want the value to be directly stored within the item struct itself, so that we can access it for inventory display purposes.

**Comment by KendrickXie** [comment]
**Closing Statement**
Position elements in item_t were changed to be unsigned ints.

The idea for the change came from Dhirpal and the code was changed by Kendrick

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great job on this issue, good that you resolved this confusion before implementing the change!
