### ISSUE TITLE
cli: make WDL file that showcases what we've worked on!

### ISSUE THREAD

**Issue by majorsylvie** [uchicago-cs/chiventure#1592]
wdl file should have player info, 
places with longer names to be parsed as "[longer name here]"

**Comment by majorsylvie** [comment]
made branch
```
git fetch origin
git checkout cli/demo2022/wdl-file
```

**Comment by majorsylvie** [comment]
added readme file! 
as of now contains info on WDL file

**Comment by jacknugent1529** [comment]
Issue Score: Excellent

Comments: Great work writing the demo! Even though the task might be clear to yourself and there may be documentation elsewhere, it would still be better to expand on the issue description to give others a better idea of what you intended with this task
