### ISSUE TITLE
Create a Demo for the Action-Management team

### ISSUE THREAD

**Issue by HarrisonD123** [uchicago-cs/chiventure#1593]
For our Spring 2022 demo, we will want to above all showcase the work we've done in implementing our new 4th action kind and all the functionality we've implemented around it. This will mean we will want to create a monkeypatched demo .c file in our action_management/examples directory and manually assign values to the structs contained in the game struct.

For this demo, we will want to show the functionality of `view stats`, `view skilltree`, `view quests`, and `view inventory`. In order to do this, we will need to manually assign items to each associated struct in our demo .c file. We will also want to show off some of the other functionality we've implemented, such as inventory conditionals and teleportation.

**Comment by HarrisonD123** [comment]
Created rooms and added items to them in the demo file

**Comment by HarrisonD123** [comment]
Created and assigned skills to the player struct we're using. This required adding skills to a skill tree manually

**Comment by HarrisonD123** [comment]
Created and assigned quests and respective tasks to their hash tables in the game struct and the player struct

**Comment by HarrisonD123** [comment]
Added items to the player's inventory hashtable. Some bugs regarding item names and CLI inputs were fixed. Demo now works for all view functions

**Comment by jbrouwer5** [comment]
**Closing Statement**

We have fully implemented a demo with different rooms in Crerar along with items with conditional taking such as a rolex and a trophy. The demo is fully functional and also allows us to show off new actions such as view skills, view quests, view task, and view inventory. We have merged the pull request and this issue is now closed.

**Comment by ecoble** [comment]
Issue Score: Excellent

Comments:
Great job creating a comprehensive demo that showcases your work!
