### ISSUE TITLE
sound: create a text to speech struct

### ISSUE THREAD

**Issue by parkerbroz** [uchicago-cs/chiventure#1596]
Summary:  We intend to implement a struct which can be used to more easily use the TTS functionality earlier unlocked by the espeak library. We plan on creating new tts.h and tts.c files in order to implement all the necessary functions. The tts struct will be included in these files. This struct will prove to help with ease of use and readability in the text to speech module.

comment: Including the espeak library in all the right places was a challenge, so we ran into struggles with building, but then resolved them. In the end everything was successful, although we had to make some slight tweaks to the struct right before the demo.

**Comment by jwschroeder21** [comment]
Update: we are working on implementing this struct, running into an error with including the e-speak library. We are trying to resolve this error to get the TTS working for our demo.

**Comment by parkerbroz** [comment]
Success. The struct works and one of the other groups commented that it was easy to interface with.

**Comment by JaStarbuck** [comment]
Closing statement: The text to speech struct was made in its own module and the functions have been demonstrated to work. We hope that other teams in the future will be able to expand on these functions, create new functions, and facilitate their usage by other teams.

**Comment by ecoble** [comment]
Issue Score: Excellent

Comments:
Nice job creating an easy to use interface and debugging the e-speak library issues!
