### ISSUE TITLE
Create tests for NPC-specific prefabs inside class_prefab.c 

### ISSUE THREAD

**Issue by katie-gao** [uchicago-cs/chiventure#1597]
Jonathan, Vincent, and I wrote friendly npc-specific prefabs inside the playerclass module. All of our code has compiled with the six new classes we created (alchemist, chef, healer, shopkeeper, fisherman, lord). We now plan to write tests specific to these new classes in tests/playerclass/test_class_prefabs.c to ensure that all of the new descriptions and stats are suiting for the current chiventure structure. We also want to make sure that the code can still compile and doesn't interfere. The changes we made to class_prefab.c is detailed in issue #1490. This issue is dedicated to writing tests for the code written in #1490.

**Comment by katie-gao** [comment]
As there are no skills for these new npc-specific prefab classes, the tests for these were much shorter. We wrote tests geared towards each of the new prefabs in playerclass/test_class_prefabs.c, and it mainly checks if the class can load and that the max health is accurate. I am also thinking about adding to wdl/test_class.c to check on the descriptions of these classes as well.

**Comment by katie-gao** [comment]
I wrote some tests that were short and not sure if it was completely correct, but I thought it would be helpful to check that everything still works with the new npc-specific classes.

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this issue!
