### ISSUE TITLE
Reach out to rpg-playerclass team for potential player class use in custom actions

### ISSUE THREAD

**Issue by mxu24** [uchicago-cs/chiventure#1598]
Building off of action-management's implementation of conditional actions, we would like to consult with the rpg-playerclass team to further understand player class, and how we may involve it in our conditional scripts and actions. As a general opening idea, users may input their player class by pressing a given key associated with the class. Based on that input, they may receive certain scripts or have access to certain actions. This issue will be complete once we have met with the rpg-playerclass team, exchanged ideas, and formulated an action plan.

**Comment by mxu24** [comment]
Discussed with player class team, and looked through their documentation and current projects/goals. The primary class information that may be useful for us is found in the file class_prefabs.c, which contains class descriptions and stats, which we may also consider using for our conditions. There were originally 6 player classes, currently 10 pushed to the dev branch, and the team is aiming to have 12 by the end of their sprint. Our next steps are continuing to discuss what we want to do with the different player classes, and implementing our ideas through a following issue. We also discussed with player class about their ongoing work with other teams involving conditionals and items, in order to make sure our goals did not overlap too much.

**Comment by ecoble** [comment]
Issue Score: Excellent

Comments:
Great job on cross team collaboration here and using this info for your demo!
