### ISSUE TITLE
Fixing ut_hash_handle Mistake regarding NPCs in Rooms

### ISSUE THREAD

**Issue by bvvill** [uchicago-cs/chiventure#1599]
One of the bugs I have come across while playing with `battle_move_example_2021` is that NPCs don't seem to respond very well to some move commands, and I was able to trace the issue to discrepancies between the hash_handle being used during some functions dealing with NPCs in rooms. Currently, there are two hash_handles included in the `npc_t` struct, the usual `hh` as well as `hh_room`, which the previous developers designated to be used for dealing with NPCs in rooms. I found that the use of `hh_room` has been neglected in `operations.c`, and intend on fixing that in this issue.

**Comment by bvvill** [comment]
Another thing I've done in this branch is optimize `npc_one_move()` in `room.c`, such that it takes a `strcmp()` of the room_id that occupied an NPC's `npc->movement->track` before and after a call to `move_npc`, so that if an NPC stays in the same room, it will just return `SUCCESS` and not have to unnecessarily go through a couple hash functions.

**Comment by bvvill** [comment]
Also, in trying to prevent mysterious seg faults resulting from improperly-initialized hash structs, I've went ahead and explicitly NULL-initialized the `npc_hash_t` member of the `npcs_in_room_t` struct in the `npcs_in_room_init()` function, like so:
```
npc_hash_t *npcs = NULL;
npcs_in_room->npc_list = npcs;
```

**Comment by bvvill** [comment]
in summary: the goal of this pr was to make sure the correct `ut_hash_handle`s were being used regarding items held by NPCs, items in rooms, and NPCs in rooms, as well as making sure explicit NULL hash table initialization was consistent in these areas. This issue/PR achieved this goal and has been closed/merged

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this issue!
