### ISSUE TITLE
Implement direct game-state actions in the operation module

### ISSUE THREAD

**Issue by efraimdahl** [uchicago-cs/chiventure#160]
Let us implement a few game-state related functions, we need to implement the operation type, check out how we can solve it using game-state's code, or request some additional changes or functions from game state.

Implement a LOOK action -> takes an optional argument that will define what will be described, otherwise just describe the room
Implement a INV action -> takes no additional arguments

Any other game_state related actions we should add ?

**Comment by efraimdahl** [comment]
Update: Implemented a LOOK and a INV function. 
LOOK first checks whether an item was specified, if not return room description, else check if item is there, if item is there return long description of item.
INV gets the item_hashtable, then iterates over it in order to print the functions.

**Comment by Tianlel** [comment]
Closing statement:

We implemented all parts of the operation functions that are related to the game-state using their provided macros. We might revert the macros back to using the get_item() function if they provide it to us in the future.

**Comment by lydiafilipe** [comment]
Issue Score: ✓+

Comments:
Nice work!
