### ISSUE TITLE
GUI : Making New/Init/Free for Stats Structs

### ISSUE THREAD

**Issue by ukanyanwu** [uchicago-cs/chiventure#1601]
Stats_graphics has a set of structs that are used to make up the module. Right now, those structs do not have any new/init/free functions to them, so they will be created to make using these structs more flexible and easier when they're being called and used in other functions in the stats_graphics Module.

**Comment by ukanyanwu** [comment]
Header files for new/init/free structs have also been added for the on_screen_stat struct within stat_graphics. This struct is used within the screen_stats_t struct, which currently has its own new/init/free functions. screen_stats_t will be continued to be worked on in order to implement its new/init/free functions once work with on_screen_stat is completed to account for this dependency.

**Comment by ukanyanwu** [comment]
new/init/free functions have been written for screen_stats_t and pop_up_t. To confirm if any further work is needed for these functions, tests will be written as referenced in issue #1602.

**Comment by ukanyanwu** [comment]
With the tests written for stats new/init/free functions, the functions themselves are currently stable. In future developments with the stats_graphics module, these functions can be useful as the structs themselves will have a lot of use when implementing the drawing functions within the stats module. It may also provide a starting point in implementing the rest of the module, as currently, the stats module is merely a skeleton of possible functions that would be used. Overall, the new/init/free functions allow another step towards completion for the module, which can be taken a step further in a future iteration of this course.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great job on this issue with a good set of updates!
