### ISSUE TITLE
GUI: Testing New/Init/Free Functions for Stats_Graphics Module

### ISSUE THREAD

**Issue by ukanyanwu** [uchicago-cs/chiventure#1602]
There are currently new/init/free functions being made for the stats_graphics module in gui. Once they are made, they need to be tested to ensure that they initialize and work correctly so any changes can be made when used in other functions that make up statistics_graphics.

**Comment by ukanyanwu** [comment]
Tests have been created and currently pass for stat graphics structs. Tests were made to validate that the new/init/free functions for pop_ups and screen_stats properly allocated and initialized values when their respective functions were called. As a whole, stat_graphics is not a fully implemented module within graphics. However, the inclusion of new/init/free functions, and their tests confirming that they work, can provide a starting point when another team may approach this module in the future. This also leads to a completion to the actual new/init/free functions as referenced in issue #1601.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great job on this issue -- simple but important!
