### ISSUE TITLE
Quests: Develop function to print the id and status of every quest in the player’s player_quest hash table

### ISSUE THREAD

**Issue by charlieweiler** [uchicago-cs/chiventure#1606]

**Comment by JSerf02** [comment]
Charlie finished designing and implementing 2 functions for this purpose (one for printing status enums and another for printing the all of the quests with their statuses) a couple of days ago

**Comment by JSerf02** [comment]
We debugged this function and made it bug free in time for our demo

**Comment by JSerf02** [comment]
We finished designing and implementing the function to print the id and status of every quest in the player's hash table
