### ISSUE TITLE
Update Legacy Demonstration with Refactored Code

### ISSUE THREAD

**Issue by tatmaca** [uchicago-cs/chiventure#1610]
With the newly refactored code in place, the custom-scripts team has decided to update our team's demonstration from two years ago so that it is usable with our new codebase. This includes renaming our include modules and updating both the name of function calls and inputting the correct parameters.

This issue is completed when we are able to run the demonstration.c such that a game of chiventure is loaded and playable.

**Comment by jackjackkimkim** [comment]
We were able to make updates to the legacy demonstrations to function correctly with the refactored code. The old demonstration can now make with the new refactored code design.

**Comment by ecoble** [comment]
Issue Score: Satisfactory

Comments:
Great job updating the old code! Please provide status updates as you work.
