### ISSUE TITLE
Create a Battle Item Stats Wiki Document to describe stat multipliers for each playerclass + item combination

### ISSUE THREAD

**Issue by Vincent-Zhang4135** [uchicago-cs/chiventure#1612]
While working on Integrating Player Class/Item Interactions with Battle Logic, we realized that there are a lot of different specifications that need to detailed in regarding how certain battle items could affect **depending** on which playerclass the battle item is being used on. We should expect different multipliers for all the different stats depending on which playerclass-battleitem combination was interaction with, and so I have created a separate issue to develop the documentation for this.

**Comment by Vincent-Zhang4135** [comment]
Jonathan has created a basic template for the warrior class stat effects after using a Strength Up consumable, and I have linked below the Player Class Battle Item Stat wiki that will include these multipliers below, and decided for simplicity, that I will work only with Warrior and Wizard player classes for now to make sure we have a work stats functionality first:

[Battle Item Stats](https://github.com/uchicago-cs/chiventure/wiki/Battles-~-Battle-Item-Stats)

**Comment by jroven** [comment]
Vincent, Katie, and I met synchronously to come up with eight class-based multipliers for stat changes due to items. Integrated classes include warrior, wizard, bard, and rogue. Integrated items include the consumables strength up, defense up, elixir of life, and healing potion.

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this issue!
