### ISSUE TITLE
Adding and Updating Functions dealing with Items in Rooms and held by NPCs

### ISSUE THREAD

**Issue by bvvill** [uchicago-cs/chiventure#1614]
There are currently a few bugs involving items within rooms or held by NPCs, one being that duplicate items are allowed to be added to a room's or NPC's `item_hash_t`, which is an error according to UTHash's documentation. There are also a couple of useful functionalities that have yet to be implemented, such as "getting" an item from an NPC's inventory given the `item_id`. There are also a couple hash implementations regarding items that could use optimization

**Comment by bvvill** [comment]
As I said I would do in my opening comment, I've implemented `item_t *get_item_from_npc(npc_t *npc, char *item_id)` in npc.h/.c, which returns an item in an NPC's inventory given the `item_id`, if it exists.

**Comment by bvvill** [comment]
I've also implemented `delete_all_items_from_npc` and `free_all_items_from_npc`, which delete and (delete, but also) free the given NPC's inventory, respectively. The difference in the use of these functions is that solely deleting an NPC's inventory doesn't free the items that were in it, so that the items can still be used in other places or conveniently added to other hash tables, as is done in `transfer_all_npc_items()` (found in room.h/.c)

**Comment by bvvill** [comment]
in `game.c` and `item.c`, I've also went ahead and explicitly initialized every hash table member of the `game_t` and `item_t` structs to be `NULL` when either of those two structs is created. Doing so is incredibly important for ut_hash table maintenance and stability, and can lead to mysterious seg faults if not done properly. The new lines added to `game_new()` are:
```
    room_hash_t *rooms = NULL;
    item_hash_t *items = NULL;
    quest_hash_t *quests = NULL;
    npc_hash_t *npcs = NULL;
    stats_global_hash_t *stats = NULL;
    effects_global_hash_t *effects = NULL;
    class_hash_t *classes = NULL;

    game->all_rooms = rooms;
    game->all_items = items;
    game->all_quests = quests;
    game->all_npcs = npcs;
    game->curr_stats = stats;
    game->all_effects = effects;
    game->all_classes = classes;
```
And the new lines in `item_init()` are:
```
    game_action_hash_t *actions = NULL;
    attribute_hash_t *attributes = NULL;
    effects_hash_t *stat_effects = NULL;

    new_item->actions = actions;
    new_item->attributes = attributes;
    new_item->stat_effects = stat_effects;
```

**Comment by bvvill** [comment]
in `add_item_to_npc()` (in npc.h/.c), I've also explicitly implemented the function instead of using `add_item_to_hash()`, since it assumes the hash handle to be hh and doesn't check that the input parameters aren't NULL.

**Comment by bvvill** [comment]
in `game-state/test_rooms.c` and `npc/test_npc.c`, I've updated the tests regarding adding duplicate items to rooms and NPCs, such that the functions now appropriately return `FAILURE` if a duplicate item is attempted to be added

**Comment by bvvill** [comment]
This issue has been closed because of the successful merge of the changes made above, as duplicate items can no longer coexist in the same hash table

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this issue! The updates are very thorough.
