### ISSUE TITLE
GUI : Creating New/Init/Free Functions for Slot Struct

### ISSUE THREAD

**Issue by ukanyanwu** [uchicago-cs/chiventure#1618]
To make up the "items" of the inventory_graphics player_inventory struct, there is a 2D array of slot_t structs. These slots contain a status, either FULL or EMPTY,  and an item, either pointing to NULL or pointing to a heap allocated item_t struct. These will then help make the 2D array for player_inventory_t. Right now, they need their own new/init/free functions to create and free their structs to make their use easier in inventory_graphics development.

**Comment by ukanyanwu** [comment]
Currently, there are functions written to test the new/init/free functions for slot_t structs for the inventory. We're currently having some issues with building these tests to confirm that they accomplish what they need to, as mentioned in #1459, but an important step has been accomplished in actually writing all of these tests.

**Comment by ukanyanwu** [comment]
These tests for slots are now working correctly as this part of the GDL is going through the steps of being pullrequested. We recently cleaned up the tests to have the proper header comments as well, to make it clear for those who read the test file. The tests currently work as they should, giving confidence that the new/init/free functions for slot_t structs work correctly.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great job on this issue with a good set of updates!
