### ISSUE TITLE
integrating reader effect execution with conditional skill execution

### ISSUE THREAD

**Issue by KabirDubey** [uchicago-cs/chiventure#1627]
In the `complex skills.c` file, conditional skills depend on the implementation of the reader effect (see lines 101). Now that reader effects have been implemented (see #1340 and #1279), we will implement the reader effect functionality and test conditional skills accordingly.

**Comment by KabirDubey** [comment]
Added these lines

```
    if(execute_reader_effect(skill->reader, ctx)) {
         rc = skill_execute(skill->skills[0], ctx);
    }
    else {
         rc = skill_execute(skill->skills[1], ctx);
    }
```

See branch 1465 complex skills examples.

**Comment by KabirDubey** [comment]
Closing statement: Nik and Kabir thought of the idea. Kabir wrote the new lines and refactored the reader files accordingly. Arya reviewed the work and tested it.

**Comment by jacknugent1529** [comment]
Issue Score: Satisfactory

Comments: Nice work on this minor integration issue! I don't recall approving this issue; be sure to check in before creating a new issue.
