### ISSUE TITLE
Implement a new action "view quests" along with the quests team

### ISSUE THREAD

**Issue by HarrisonD123** [uchicago-cs/chiventure#1628]
Our goal here is to allow the user to view the names of the quests.

In order to implement this, the quests team would have to create a display quests function in the `game-state/player` module that we can call from the `action_management/actionmanagement` module. We would have to modify the logic within the if-statement of our `do_self_action` function to accommodate this and to call this display function.

The quests team also wants the ability to view all of the tasks within a specific quest, using their quest id string. In other words, we also need to implement a `"view quests "quest-id""` command.

**Comment by HarrisonD123** [comment]
Talked with the CLI team and the quests team. We will need to change the `string *target` parameter of our do_self_action function to accommodate a third parameter (the quest-id string). If the input passed from the CLI team contains 2 elements (i.e. "quests" and "[quest-id]", then we will call the quests team's show_task_tree with the quest list and quest-id as inputs. Each quest has a task tree.

**Comment by HarrisonD123** [comment]
Quests also wants to be able to view a specific task from a quest's task tree with a new view command: `view task ["task-id"]`.

**Comment by HarrisonD123** [comment]
We changed the parameter of our `do_self_action` function and implemented the if-statement logic within the function to accommodate `view quests` (which calls `show_quests` in the quests module), `view quests ["quest-id"]` (which calls `show_task_tree`), and `view task ["task-id"]` (which calls `show_task`)

**Comment by HarrisonD123** [comment]
### Closing Statement

We modified our do_self_action function to first take in multiple string inputs by converting string *target to an array of strings, string **target. We then modified our if-statement logic:

If the first string in the array is "quests" and the second element is null, we call the quests module's function show_quests, which prints all quest names out.

If the first string in the array is "quests" and the second element is a string, we call the quests function show_task_tree, passing in the second string as the quest name. This displays the tree of tasks that completing the specified quest entails.

If the first string in the array is "task" and the second element is a string, we call the quests function show_task, passing in the second string as the task name. This displays one specific task's of a particular quest and its description, so that the player knows what it entails.

Harrison changed the parameters of the do_self_action function and communicated with the CLI and quests teams. Jackson and Sabine coded up the if-statement logic and called the skilltree team's functions.

**Comment by ecoble** [comment]
Issue Score: Excellent

Comments:
Great job collaborating with other teams on this issue! Nice job on the thorough updates and closing statement as well!
