### ISSUE TITLE
Write function that takes in two room ids and a direction and creates a connection between those two rooms

### ISSUE THREAD

**Issue by Kate32815** [uchicago-cs/chiventure#163]
This function takes in a pointer to a game struct, two room ids and a direction, and adds the connection to the game state room struct of the first room

Parameters:
- g: pointer to a game state game struct
- src_room_id: the room ID of the "source" room 
- to_room_id: the room ID of the "to" room
- direction: the direction of the connection (i.e. north)

Output:
- 0 upon SUCCESS
- 1 if the first room ID does not exist
- 2 if the second room ID does not exist

Side Effects:
- Adds the pointer to the "to" room and its direction to the connection field belonging to the "source" room struct

`int create_connection(game_t* g, char* src_room_id, char* to_room_id, char* direction);`

**Comment by borjasotomayor** [comment]
A function like this should not cause the program to exit unconditionally (nor should it print error messages on its own). Instead, the function should return an error code. For example, the function could return 1 if the first room is invalid, and 2 if the second room is invalid.

**Comment by Kate32815** [comment]
Okay thank you. I have modified the function description.

**Comment by a-matai** [comment]
@Kate32815 quick question, do you want room_id or ptrs to rooms?

**Comment by a-matai** [comment]
@Kate32815 i've done it as per your spec but let me know if you'd like room pointers instead!

**Comment by a-matai** [comment]
Function create_connection has been added per request
/*
* Function to connect two rooms
* Parameters:
* game, Source room_id, destination room_id, direction
* 
* Returns:
* SUCCESS if all okay, exit(1) if src room_id not found, exit(2) if dest not found
* 
*/
int create_connection(game_t *game, char* src_room, char* dest_room, char* direction)

there is a side note. As per current spec and requirements of sprint 3, there is no condition_list added. This may have to be updated in the future, although a function to find and modify the path struct can be easily created.

**Comment by a-matai** [comment]
Updates @Kate32815 : 
now returns 0 if successful, 2 if src not found, 3 if dest not found, and 1 if there's an error in creating the path.

**Comment by lydiafilipe** [comment]
Issue Score: ✓

Comments:
Good work! However there weren't really any progress updates
