### ISSUE TITLE
Update Battle User Stories and Battle Wishlist

### ISSUE THREAD

**Issue by aliu65803** [uchicago-cs/chiventure#1630]
For this issue, we will update the battle user stories and wishlist wiki pages. Over the course of the quarter, we have implemented a lot of new changes and would like to add/remove items from these two documents to reflect the state that battles is currently in. We will also include places that the future battle teams may start at.

**Comment by aliu65803** [comment]
We have met up and created a google doc to plan out this wiki page. We will not be linking that google doc, but we will be transferring the information from the doc into the respective wiki page soon

**Comment by aliu65803** [comment]
We have added quite a few changes to the battle wishlist. Some of these items include:

- Auto battle mode, which will activate when a user inputs a certain command
- Full integration of sound effects (work with them to find a way to run the feature on non-CSIL devices)
- Multi enemy parties so the player can fight more than one enemy at a time
- Party battles so the player can play with other players or at least have ai part members
- Ability to change battle equipment during a battle
- When support for multi enemy parties gets implemented, moves that will target one enemy vs moves that will target multiple
- When party battles get implemented, moves that can heal/help multiple vs one person in the party
- Different classes playing specified roles in battle ex: a healer healing team members, a knight attacking the other enemies
- Different ways for battle ai to choose a move, especially now that different types of moves have been implemented
- Once multiplayer games become an option, a player should be able to battle other players
- A way for the player to flee a battle/surrender once hp goes below a certain percent

Moreover, we have taken out items from the wishlist that we believe have been implemented.

We have also made changes to the user stories. Some of these items include:
- I want there to be a numbered menu of possible actions, so the action's input will be a simple 2-character string that will either correspond to a move, an item, or the option to pass.
- I want to have more flexibility on what makes up a turn, meaning it is possible for a turn to be broken down into multiple components so I can potentially use multiple moves/items in one turn.
- I want to be able to fight multiple enemies at once and/or fight in a party, either with other players or with npcs
- I want to be able to battle other players once multiplayer games have been implemented

When updating the user stories, we had to modify a few to reflect the changes we have made this term.

**Comment by aliu65803** [comment]
We have also decided that it might be nice to include a small section on the wishlist with a few items that future years can start with.

**Comment by emiliolevinspage** [comment]
We have completed the [wishlist](https://github.com/uchicago-cs/chiventure/wiki/Battles-~-Wishlist) and [user stories](https://github.com/uchicago-cs/chiventure/wiki/Battles-~-User-Stories) updates. We added the section Angela referred to above, as well as an updated battle example in the wishlist. Future teams should be well-set up to pick up where we left off!

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this issue!
