### ISSUE TITLE
Adding the actions "fireball" and "slash" to the Chiventure actions list

### ISSUE THREAD

**Issue by jackjackkimkim** [uchicago-cs/chiventure#1638]
The custom-scripts team would like to add the actions "FIREBALL" and "SLASH" so that we may include these actions on a WDL file. Without the addition of these actions in the main Chiventure actions list, we cannot load in the WDL file properly. These two actions should be added to the list of actions on the load-actions.c file as well as the header file action-struct.h

**Comment by jackjackkimkim** [comment]
The actions were added and needs to be reviewed by the action management team!

**Comment by jackjackkimkim** [comment]
The pull request associated with this issue is #1640

**Comment by jackjackkimkim** [comment]
Ramarko was able to monkey patch in the custom actions "fireball" and "slash" for our demo so it is no longer necessary to hardcode them into Chiventure.

**Comment by ecoble** [comment]
Removing the milestone as this issue ended up being replaced by a different one, so this will be ungraded.
