### ISSUE TITLE
Create an Advanced Lua Demo with 3+ Args passed through Lua Script

### ISSUE THREAD

**Issue by tatmaca** [uchicago-cs/chiventure#1643]
As the custom-scripts team works towards its final demo for the quarter, we wanted to practice writing more advanced scripts that could interact with more game items and player inputs. Our goal is to create a demo that passes at least 3 parameters through at least 3 Lua scripts. This way, we can have our scripts interact with one another and perform more complex actions.

This issue is complete when we have a completed pull request which features a demonstration contained in a .c file and its corresponding .lua files. The demo should successfully run in Chiventure and pass 3+ variables through Lua scripts.

**Comment by tatmaca** [comment]
This issue is completed! We've successfully merged a branch which contains the "lost_order.c" demo. This is critical in the development of our final demo, as this demo is able to input three arguments into our Lua script and create unique outputs and in-game events as a result. While this issue is closed, we look forward to presenting this smaller demo in the greater context of our final demo.

**Comment by ecoble** [comment]
Issue Score: Satisfactory

Comments:
Great job creating a more advanced demo with Lua! Please provide status updates for issues as you make progress.
