### ISSUE TITLE
Writing New Test Cases for Refactored Code

### ISSUE THREAD

**Issue by tatmaca** [uchicago-cs/chiventure#1645]
In our refactoring of the legacy code, we realized that we also had a large amount of test cases which relied on the old data types. These test cases essentially made sure that all the data types work as described while also interacting with Lua in the correct manner. This issue is complete when all the test cases are updated such that the merge request succeeds.

**Comment by tatmaca** [comment]
This issue is now closed! With the refactored code in place, the custom-scripts team is now able to merge our numerous demos which demonstrate the capabilities of Lua scripting as well as our final Demo which runs Lua in a sample Chiventure game!

**Comment by ecoble** [comment]
Issue Score: Satisfactory

Comments:
Great job writing these tests! Please provide status updates for issues as you make progress.
