### ISSUE TITLE
Create a demo where two arguments are passed into Lua script

### ISSUE THREAD

**Issue by tatmaca** [uchicago-cs/chiventure#1646]
In an effort to increase our familiarity with Lua as well as build a greater volume of scripts in our sandbox for future developers, our team decided to create a more advanced script compared to what already exists at present. All of our previous samples in the sandbox were isolated pieces of code which passed one argument into a static Lua script. The goal is to create a demonstration that runs in Chiventure which dynamically responds to the user's input (i.e. their name) as well as the specific item which they are holding.

This issue is completed when a successful merge request occurs. This merge request should include the demonstration .c file as well as its corresponding .lua file which contains the customized script.

**Comment by RamarkoB** [comment]
A new demo has been added to the custom-scripts folder which can take in multiple arguments and then pass it to Lua. The demo file is called gold.c and is in the examples folder of custom-scripts. Marking this issue as closed

**Comment by ecoble** [comment]
Issue Score: Satisfactory

Comments:
Great job creating a multi-argument Lua script! Please provide status updates as you go.
