### ISSUE TITLE
Custom scripts- demonstration 2022 with torch functions and monkeypatched custom actions "fireball" and "slash" 

### ISSUE THREAD

**Issue by jackjackkimkim** [uchicago-cs/chiventure#1655]
We want to update our demonstration to include the torch function that can be interacted with through LUA (user can be lit and then unlit). Additionally, we are monkey patching custom actions called "fireball" and "slash" instead of asking the action management team to hardcode it into Chiventure which may lead to convoluting the actions list in Chiventure.

**Comment by RamarkoB** [comment]
We were able to add the two custom actions to the demo without hardcoding them in chiventure. This is visible in the demo_2022.c demo. Marking this issue as closed

**Comment by ecoble** [comment]
Issue Score: Satisfactory

Comments:
Great job monkeypatching these actions for the demo! Please provide status updates as you go.
