### ISSUE TITLE
Write new, modify existing helper functions for class_prefabs.c

### ISSUE THREAD

**Issue by vanolson** [uchicago-cs/chiventure#1656]
Issue #1066 mentioned a number of functions that could be added to `class_prefabs.c`, which, since that issue is closed, I am pasting in here to start a new issue. I will add a `class_prefab_add_items()` function which adds some default items to each class (e.g. a wand for the wizard, a rusty sword for the warrior), by creating items, documenting them on the wiki, coding these items, and adding tests. I will also separate the existing `class_prefab_new()` function so that it is possible to create classes which only contain a short and long description. I may also create a function where the dev can specify which fields of the prefab class they would like filled out, which will be more relevant as there are more ways to prefab classes (i.e. prefab items), but this might get pushed to a later issue depending on time.

**Comment by vanolson** [comment]
I've begun writing the `class_prefabs_add_items()` function, it's outlined in `class_prefabs.h`. Since items aren't an inherent part of classes, the function returns items (in a hash table I think) that can be added to a player in the game state module. The next step is to fully develop the function in `class_prefabs.c`

**Comment by vanolson** [comment]
I've created the first item in the function. It seems not to cause any problems, so hopefully that will keep happening with the other items, especially once I add testing.

**Comment by vanolson** [comment]
Still working on the `class_prefabs_add_items()` function. I will also test the issues and document them, but I think I will have to put the `class_prefab_new()` portion of this issue on hold, both for time reasons and because I don't entirely see its relevance.

**Comment by vanolson** [comment]
The `class_prefabs_add_items()` function is complete, barring issues found in testing.

**Comment by wellingtj** [comment]
I am updating documentation for this code as requested by Van

**Comment by vanolson** [comment]
The item prefab tests all work. All that's left for this issue is updating documentation, since I don't believe the `class_prefab_new()` portion of this to be necessary. Could be done in a later issue though

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this issue!
