### ISSUE TITLE
Update Pull requests to reflect changes to add_action function

### ISSUE THREAD

**Issue by RamarkoB** [uchicago-cs/chiventure#1659]
Many of the demos that were made by custom scripts used the add_action function to add new actions to an item in a running game instance of chiventure. However, the add_action function has been updated to use different function arguments. To prevent merge conflicts once the branches have been pulled into the repository, we should go through our open pull requests to make sure all function calls to add_action are updated to the function format. This issue can be marked closed once all open Pull Requests have been updated.

**Comment by RamarkoB** [comment]
This issue was found as unnecessary. We will integrate these corrections into existing branches.

**Comment by RamarkoB** [comment]
This issue was found as unnecessary. We will integrate these corrections into existing branches.

**Comment by RamarkoB** [comment]
This issue was found as unnecessary. We will integrate these corrections into existing branches.

**Comment by ecoble** [comment]
Removing milestone for unnecessary issue.
