### ISSUE TITLE
Compile multiple Custom Scripts Demos with Lua at once

### ISSUE THREAD

**Issue by RamarkoB** [uchicago-cs/chiventure#1667]
So far, Custom Scripts has been compiling one demo at a time due to demos not compiling with Lua Libraries correctly. The goal of this issue is to compile multiple demos with Lua at the same time using a single CMakeFiles.txt file. This issue can be marked closed when there is a single CMakeFiles.txt file that can compile multiple demos that use Lua.

**Comment by RamarkoB** [comment]
This issue was found as unnecessary. We will integrate this corrections into an existing branch.

**Comment by ecoble** [comment]
Removing milestone for unnecessary issue.
