### ISSUE TITLE
Update WDL spec to remove features that are not supported fully

### ISSUE THREAD

**Issue by thoranderskow** [uchicago-cs/chiventure#167]
Borja told us that we should not have anything in the spec that has not been supported either by our own code or any other teams', like game state.

**Comment by thoranderskow** [comment]
Started by removing conditions in both rooms and actions, and also the "allowed" field.

**Comment by thoranderskow** [comment]
Next, the attributes state and value were removed, as they are not currently supported by the goals set for the end of sprint 3.

**Comment by thoranderskow** [comment]
The spec in wdl/improved_validation has been updated, and conditions, allowed, state, and value were removed.

**Comment by lydiafilipe** [comment]
Issue Score: ✓

Comments:
Good work! I think the summary could have included a bit more detail on what was in there that is not supported. Also, for what you were removing, it would have been good to mention where exactly that was found originally
