### ISSUE TITLE
Create Final Demo for presentation

### ISSUE THREAD

**Issue by RamarkoB** [uchicago-cs/chiventure#1670]
Over the past Quarter, Custom-scripts has experimented with conditional WDL files, integrating Lua, and other ways of making Chiventure more dynamic. As we approach our final demonstration, this is the final demo that we will create and present during our final presentation. This issue should be closed when the final demo has been created that combines the smaller demos we have created over the course of this quarter.

**Comment by RamarkoB** [comment]
Duplicate Issue of #1648

**Comment by RamarkoB** [comment]
We successfully combined the gold.c demo with the demo_2022.c file to create a larger demo. This is visible in the demo_2022.c file. This demo_2022.c demo will be our final demo for our end-of-quarter demo. Marking this as closed.

**Comment by ecoble** [comment]
Issue Score: Satisfactory

Comments:
Nice work on the demo! Please provide status updates as you work on the issue.
