### ISSUE TITLE
Replace gencontext with specgraph

### ISSUE THREAD

**Issue by williamhu314** [uchicago-cs/chiventure#1677]
Currently, the gencontext struct is obsolete as all information needed to generate a game is inside specgraph. In this issue, we aim to remove all instances of gencontext and replace them with specgraph. This includes all functions, function headers, and tests.

**Comment by williamhu314** [comment]
gencontext has been removed from all functions and tests. I am working on updating function headers now

**Comment by williamhu314** [comment]
All instances of gencontext have now been replaced in the .c, .h, and test files.

**Comment by williamhu314** [comment]
All instances of gencontext have now been replaced in the .c, .h, and test files.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great work on this minor issue!
