### ISSUE TITLE
Update NPC Dialogue documentation

### ISSUE THREAD

**Issue by sglenn-uchi** [uchicago-cs/chiventure#1678]
There have been many updates to the NPC dialogue code this quarter. In addition, much of the pre-existing documentation in the code was outdated. In this issues, I will update the relevant wiki pages.

**Comment by sglenn-uchi** [comment]
I finished updating the wiki. I added sections documenting the inclusion of the `tone_t` struct as well as the Quests implementation. I also updated the [Loading NPCs from WDL Files](https://github.com/uchicago-cs/chiventure/wiki/NPC-~-Loading-NPCs-from-WDL-Files) page. I also created a list of interesting and logistical features that would improve the quality of Dialogue and NPC interactions in general in Chiventure.

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this issue!
