### ISSUE TITLE
Update class prefab documentation to include multiclass prefabs

### ISSUE THREAD

**Issue by wellingtj** [uchicago-cs/chiventure#1679]
We have prefabricated a few multiclasses for the demo but they not currently logged on the wiki. The classes are "hexblade" (wizard, warrior), "infernal" (elementalist, sorcerer), "paladin" (knight, monk), "enchanter" (bard, healer), and "assassin" (rogue, ranger). They should be logged for future integration purposes. The hexblade class was written from last year's demo with a very basic multiclass module. Now, the infernal, paladin, enchanter, assasin multi-classes are functional and should be updated to the wiki documentation.

**Comment by wellingtj** [comment]
The documentation on the class list page has been updated accordingly.

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this issue! For a task of this size, we would've expected to see more status updates and/or status updates that were more detailed. Particularly, it would have been good to link the page that you updated.
