### ISSUE TITLE
Make tests for action_type_new, action_type_init, and action_type_free

### ISSUE THREAD

**Issue by lucyyutingli** [uchicago-cs/chiventure#169]
Create multiple tests to ensure that action_type_new, action_type_init, and action_type_free are working properly. The tests will be formatted after the tests that we created earlier in the quarter, as in lab 5.

**Comment by lucyyutingli** [comment]
Made a new feature branch called actions/tests. Just finished creating the tests, working on the Makefile right now, so we can integrate it into our main actions Makefile.

**Comment by lucyyutingli** [comment]
I added a Makefile in commit 402b6025afbcfb13b73ef1b5fde22ad6cbb06b68, but it's still being worked on.

I added the tests in actions_management/tests/ folder in a file that's called tests_actionmanagement.c. However, at the moment I'm considering adding these tests in a separate file. You can see all the changes in commit 5699db0

**Comment by SnowballAntrobus** [comment]
Lucy asked me to help her because the testing suite not compiling properly. We thought the problem was the Makefile, but it turned out there were other errors both in the testing .c file and the src .c file.

**Comment by SnowballAntrobus** [comment]
The changes are currently in the branch actions/bugging which will now be merged with actions/test

**Comment by lucyyutingli** [comment]
An update on the test files, I’ve renamed the file tests_actionmanagement.c to tests_action_new_init_free.c since we’re going to be working on separate branches for different tests. Once the pull goes through, I’ll be deleting the actions/tests branch, as the other tests will be on branches that relate to them.

**Comment by mpcsh** [comment]
Issue Score: ✓+

Comments:
Great work!
