### ISSUE TITLE
integrate path module into room

### ISSUE THREAD

**Issue by a-matai** [uchicago-cs/chiventure#170]
given the decision to change path->dest to a room pointer, we need to integrate path header back into room. 

this will also reduce the number of modules.

the path.c file will remain separate

**Comment by a-matai** [comment]
Refactored path into room, updated documentation, search and find functions. 
Simple task, no large changes.

There has also been an update where we don't need the add_*_to_hash functions anymore and everything is implemented. 

While there are still some issues and errors with functions, the code has been refactored and so this particular issue is complete.

**Comment by lydiafilipe** [comment]
Issue Score: ✓

Comments:
Good work! However I think it is not particularly clear what you are integrating though. room module? room struct? "path header" is  also a vague term.  Maybe link the relevant files.
