### ISSUE TITLE
Add extra functionality and final changes to the demo

### ISSUE THREAD

**Issue by mxu24** [uchicago-cs/chiventure#1700]
Issue to track progress on changes that expand on the addition of custom actions based on classes (wizard/warrior itinerary example), lua scripts (chest and gold example), and booleans (torch example) through other small additions involving similar concepts based on the current integrated examples. 

Tied to pull request #1690.

**Comment by RamarkoB** [comment]
We restructured the map of our demo to create a more cohesive narrative of what the Custom Scripts team has accomplished this year. The demo will dynamically load a wdl file depending on input, as well as other examples that will change depending on input. Marking this issue as closed.

**Comment by ecoble** [comment]
Issue Score: Satisfactory

Comments:
Great job creating this demo! For a substantial issue like this one, please provide intermediate updates as you work.
