### ISSUE TITLE
Add string parameter to game_new() function, and update game_t struct so that it contains a string "intro"

### ISSUE THREAD

**Issue by thoranderskow** [uchicago-cs/chiventure#171]
game_new() should take a string parameter that is the intro, so that when the game_t struct is initialized, and it has been updated to have a new intro field in the struct, it initializes the new game_t with the given string.

**Comment by jessxia** [comment]
The game struct now contains char *start_desc to support this string. Game_new() takes in this argument. It is currently set to a maximum character length of 300 chars. Is this okay or do you want a longer possible starting description?

(These changes are on the game-state/dev branch if you've like to take a look at game.h and game.c.)

**Comment by thoranderskow** [comment]
Is it possible to change it to max character length 500? That's what it says on our specification in wdl/dev. Otherwise, everything looks good!

**Comment by jessxia** [comment]
Done!

**Comment by thoranderskow** [comment]
Game_t struct was updated to include intro string, and game_new now takes a string parameter.

**Comment by lydiafilipe** [comment]
Issue Score: ✓+

Comments:
Good work!
