### ISSUE TITLE
Add and Implement an action search function for action management

### ISSUE THREAD

**Issue by MTUC08** [uchicago-cs/chiventure#172]
Please update the item struct to have some sort of allowed_actions (ex:// list/array) (see conversation in #157) and create a function that will take in an action and an item and return whether the action can be performed on the item or not (can be in the form of SUCCESS/FAILURE or something else). Then, PR to master ASAP so action management can use it in their action kind function implementations (#115) for Sprint 3. Thanks!

**Comment by patrickkoopmans** [comment]
Functions for adding and checking the existence of actions associated with an object have been written. They are called add_allowed_action(item_t* item, char* action) and allowed_action(item_t* item, char* action) respectively. 

As requested from WDL and AM, add_allowed_action() returns SUCCESS or FAILURE depending on whether or not the action was successfully associated with the item, and allowed_action returns SUCCESS or FAILURE depending on whether or not the action is associated with the item. 

The interfaces for these functions are located in item.h, and both have been duly tested. 

Next steps: WDL and AM need to confirm that this issue can be closed, then I will initiate pull request.

**Comment by lydiafilipe** [comment]
Issue Score: ✓

Comments:
Good work on the summary and closing statement, however it would have been good to see more progress updates. Updates would have been good for each function, major changes, tests etc.
