### ISSUE TITLE
Make basic tests for do_item_action

### ISSUE THREAD

**Issue by lucyyutingli** [uchicago-cs/chiventure#180]
The object of this issue is to make multiple tests for do_item_action, covering all possible outcomes of the function in order to assure that it works correctly. Since the functions at this time are still fairly simple, the outputs of this tests will show whether they are printing the correct strings or not.

This was a branch off issue #177

**Comment by SnowballAntrobus** [comment]
Created task #192 to add new tests after function has been updated to use game state functions in #190

**Comment by lucyyutingli** [comment]
Since we forgot to add a closing statement, I'll be adding one now. 

Closing Statement:
As of now the these tests were created before we altered our functions to return ints instead of chars, so they're fairly simple and only test for the correct output. Later on, we'll be editing them so they test for correct conditions met as well, once we have Game State functions.

**Comment by mpcsh** [comment]
Issue Score: ✓

Comments:
Progress updates were skimpy (and only improved well after the fact).
