### ISSUE TITLE
Support stacking of multiple items in same room/player

### ISSUE THREAD

**Issue by patrickkoopmans** [uchicago-cs/chiventure#183]
Currently, the game-state modules do not support stacking of multiple items. For example, two apple items associated with a room cannot both be called "apple".

**Comment by ericyc16** [comment]
I have successfully integrated item stacking with issues #666 and #703 and pull requests #730 and #765. Therefore, I am closing this issue.

A summary of how item stacking is implemented:
- Introduced separate chaining in item hashtables to resolve collisions based on item ID
- Refactored old item hashtable code into functions `add_item_to_hash`, `remove_item_from_hash`, and `get_all_items_in_hash` (item.h)
- Updated code in these functions to properly handle separate chaining
- Updated the `ITER_ALL_ITEMS_IN_ROOM` and `ITER_ALL_ITEMS_IN_INVENTORY` macros (item.h).
- Updated `kind1_action_operation` and `kind3_action_operation` (operations.c) to try an action on all items with identical ids until a successful action occurs (or until all items have been tried)
- Updated `look_operation` (operations.c) to mention there being multiple of an item when the user inputs "look [item]"
- Wrote/updated tests

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Great job closing out this backlog issue! Your closing summary is very clear and useful.
