### ISSUE TITLE
Update do_item_item_action tests to reflect #188

### ISSUE THREAD

**Issue by SnowballAntrobus** [uchicago-cs/chiventure#189]
The goal is to add multiple tests for do_item_item_action, corresponding with the changes from #188 . The additional tests should cover checking conditions and attribute changes.
A test of special concern is checking that the direct item can act on the indirect.

This is the successor to #182

**Comment by SnowballAntrobus** [comment]
I had accidentally been linking to issue #188 in my commits that really correspond to this issue. This is a minor problem since the two go hand in hand. In fact they are on the same branch. So far due to the lack of GS functions. So far we have partial implementations for the effects tests. They are ready to go except for a comment needing to be replaced by a function call to the as of yet nonexistant add effect GS function.

**Comment by SnowballAntrobus** [comment]
As of now we have tests for conditions and effects separately. However, it is very easy to create compound tests if necessary you just need to change an argument in the testing function.

**Comment by SnowballAntrobus** [comment]
Closing Statement:
We have now finished writing tests that check the full functionality of the do_item_item_action function.  In this issue we added tests for effects and conditions. We will proceed by using this work as a template for the do_item_action tests and continuing to check for compatibility as the GS functions make it to master.

**Comment by mpcsh** [comment]
Issue Score: ✓+

Comments:
Great work!
