### ISSUE TITLE
Update do_item_action to incorporate condition checking and attribute changes

### ISSUE THREAD

**Issue by SnowballAntrobus** [uchicago-cs/chiventure#190]
Build upon the do_item_action basic prototype ( #115 ) to include condition checks, i.e. whether the item has the necessary attributes for the action to be performed, and attribute changes, i.e. the consequences of the action being requested. This will be done with game state functions.

**Comment by lucyyutingli** [comment]
Once #186 is approved, we will be using the following functions:

- In order to change attributes, we will use set_attribute() family of functions
- In order to check conditions, we will use get_attribute() family of functions

**Comment by lucyyutingli** [comment]
The functions have been changed for the most part but we'll have to wait for game-state's functions to be pulled to master before we can be sure that they're working properly. We'll be waiting on that before we can make any further progress.

**Comment by MTUC08** [comment]
Closing comments: in this issue, we updated the do_item_action function to handle conditions and effects. This was pulled into master with #364 . Looking forward, next years class can continue to evolve this function by adding more conditions (inventory, location) and effects (teleportation). Thanks for a great quarter!

**Comment by mpcsh** [comment]
Issue Score: ✓+

Comments:
Great work!
