### ISSUE TITLE
Update do_path_action to accommodate condition checking and attribute changes

### ISSUE THREAD

**Issue by SnowballAntrobus** [uchicago-cs/chiventure#191]
Build upon the do_path_action basic prototype ( #115 ) to include condition checks, i.e. whether the item has the necessary attributes for the action to be performed, and attribute changes, i.e. the consequences of the action being requested. This will be done with game state functions.

**Comment by yoonsjeong** [comment]
I've started work on this task, on a branch called `actions/do_path_191`.

**Comment by yoonsjeong** [comment]
Hi @MTUC08 @SnowballAntrobus @lucyyutingli I've defined a new macro called `#define NOT_ALLOWED_PATH (4)` just a heads up in case any other macros turn up.

**Comment by yoonsjeong** [comment]
PR #302 has been merged successfully into `actions/dev`.
Within this pull request was the implementation of the following
- do_path_function using game-state functions and chiventure_ctx struct
- tests with the appropriate game-state functions (as per #193)
- removal of the "ENTER" action_type_t
- refactoring of the do_item and do_item_item function to no longer take in the game_t struct
- refactoring of tests related to do_item and do_item_item

**Comment by mpcsh** [comment]
Issue Score: ✓+

Comments:
Great work!
