### ISSUE TITLE
Update do_item_action tests to reflect #190

### ISSUE THREAD

**Issue by SnowballAntrobus** [uchicago-cs/chiventure#192]
The goal is to add multiple tests for do_item_action, corresponding with the changes from #190 . The additional tests should cover checking conditions and attribute changes.

This is the successor to #180

**Comment by SnowballAntrobus** [comment]
These tests are being made using the tests from do_item_item_action as a template. Therefore if a bug is found in either of the test files it is a good idea to check the other one for it too.

**Comment by SnowballAntrobus** [comment]
Work for this issue is being done on the branch actions/updatedo_item

**Comment by SnowballAntrobus** [comment]
Closing Statement:
We have now finished writing tests that check the full functionality of the do_item_action function. In this issue we added tests for effects and conditions. We will proceed by checking for compatibility as the GS functions make it to master.

**Comment by mpcsh** [comment]
Issue Score: ✓

Comments:
Definitely missing some progress updates here
