### ISSUE TITLE
Update do_path_action tests to reflect #191

### ISSUE THREAD

**Issue by SnowballAntrobus** [uchicago-cs/chiventure#193]
The goal is to add multiple tests for do_item_item_action, corresponding with the changes from #191 . The additional tests should cover checking conditions and attribute changes.

This is the successor to #181

**Comment by yoonsjeong** [comment]
^ accidentally clicked the close issue button (I got too excited)

PR #302 has been merged successfully into `actions/dev`.
Within this pull request was the implementation of the following
- do_path_function using game-state functions and chiventure_ctx struct (as per issue #191)
- tests with the appropriate game-state functions (as per this issue)
- removal of the "ENTER" action_type_t
- refactoring of the do_item and do_item_item function to no longer take in the game_t struct
- refactoring of tests related to do_item and do_item_item

the tests are successful and don't crash!

**Comment by mpcsh** [comment]
Issue Score: ✓+

Comments:
Great work!
