### ISSUE TITLE
Update Makefile to compile into static library

### ISSUE THREAD

**Issue by SnowballAntrobus** [uchicago-cs/chiventure#198]
Currently our Makefile compiles into a dynamic library. The project specification says that it must be a static library. The goal of this issue is to make our Makefile in line with the project spec.

**Comment by SnowballAntrobus** [comment]
So the problem was that before we were generating a dynamic library and just sticking a .a extension on it like it was static. The new makefile will generate a .a file.

**Comment by SnowballAntrobus** [comment]
The changes are currently in the branch actions/bugging which will now be merged with actions/test

**Comment by SnowballAntrobus** [comment]
Decided to change this fix to a hotfix directly to master.

**Comment by SnowballAntrobus** [comment]
Closing Statement:
During our integration with CLI we noticed that our library was compiling incorrectly. We fixed it so that it followed the project standard of being a static library. In future work we will have to further change the makefile to accommodate integration with other groups such as UI and GS for the purposes of using their functions or just testing.

**Comment by mpcsh** [comment]
Issue Score: ✓+

Comments:
Great work!
