### ISSUE TITLE
Add starter code to repository

### ISSUE THREAD

**Issue by borjasotomayor** [uchicago-cs/chiventure#2]
We need to add the object library + YAML parser written by @dwahme, @MaxineK36, and @firatciftci. This also requires setting up an initial directory structure and Makefile for the project.

**Comment by borjasotomayor** [comment]
A few notes about the code I just added:

- The code seems to build fine without the libyaml object files and header files, as long as the right packages are installed (I tested it on my Ubuntu 16.04 desktop; it looks like the libyaml header files are missing from the CS machines, but I'll ask Techstaff to install them)

- Other than removing the libyaml files, and rewiring the Makefiles, I haven't made any changes to the libobj source code.

- The directory structure requires one directory per component inside `src/`. Each component can have their own `src/` and `include/` directories (the latter for any interfaces they want to expose to other components). There is no top-level `include/` directory because the final outcome of this project is an executable.

**Comment by borjasotomayor** [comment]
@MaxineK36, @dwahme, @firatciftci: I think this is basically ready to merge to master. Any objections to getting the ball rolling on a pull request?

**Comment by dwahme** [comment]
I have one more update for how obj handles string length. Currently, it truncates long strings to 60 characters, which doesn't appear to be long enough for some of the long descriptions. I'll add a longer length, and also reduce the length when possible to save memory.

Additionally, I'll be checking some of the memory management when handling strings to ensure there aren't egregious leaks.

**Comment by dwahme** [comment]
I've updated the string length macros to have better names and definitions and fixed how obj handles string freeing so there isn't a leak when searching for attributes. 

All obj items are now ready for review to push to master. Waiting for @MaxineK36's go ahead for parsing items.

**Comment by MaxineK36** [comment]
I'll also be quickly adding in free functions in my stack implementation to avoid too many memory leaks in the parser.

**Comment by MaxineK36** [comment]
I created free functions for stack_t and stackobj_t and included calls to them in the parser.c file. I also added a note about libyaml in the README.

All parse and obj items are now ready for review to push to master.

**Comment by borjasotomayor** [comment]
Starter code has been merged in #4
