### ISSUE TITLE
Create functions to return short and long string descriptions from items

### ISSUE THREAD

**Issue by jessxia** [uchicago-cs/chiventure#202]
Write functions to return the short and long descriptions stored in our item structs. This will be used in WDL's tests of their load_item functions (issue #179). It will also be useful for returning descriptions for actions like LOOK.

**Comment by jessxia** [comment]
Added said functions; then added condition so that NULL items to return NULL. Added tests for both created and NULL items in test_items.c.

**Comment by lydiafilipe** [comment]
Issue Score: ✓+

Comments:
Nice work! It seems like this was a small issue so progress updates weren't super necessary but make sure to keep up with those on bigger issues.
