### ISSUE TITLE
Change valid_actions to be compatible with CLI

### ISSUE THREAD

**Issue by SnowballAntrobus** [uchicago-cs/chiventure#208]
After talking to CLI we are changing our valid_actions such that all items will be in line with our actions enum. This means we are adding capitalization and replacing spaces with underscores.

**Comment by SnowballAntrobus** [comment]
Closing Statement:
CLI's Ryan Gold reached out to us to tell us that the way we were writing our actions in valid_actions was causing many issues with CLI's parser. We determined that the easiest fix would be to change our function since it was the one at fault. The parser is based on our spec and thus is correct. We changed it by adding capitalization and replacing spaces with underscores. In the future we must make sure to have a consistent format is the way we represent data. This is especially important when we are passing said data to other teams.

**Comment by mpcsh** [comment]
Issue Score: ✓-

Comments:
No progress updates, closing statement only well after the fact.
