### ISSUE TITLE
Design room, object, player modules

### ISSUE THREAD

**Issue by borjasotomayor** [uchicago-cs/chiventure#21]
Design modules to manipulate rooms, objects, and the player in a game. The game data structures (being designed in #20) will have to link to the rooms and to the player.

**Comment by jessxia** [comment]
Added files with room struct, which contains descriptions, a list of objects, and a list of exits found there. Also includes functions to create new rooms, free rooms, and extract descriptions/lists from each room.

**Comment by lindsey-hsi** [comment]
Added object.c and object.h files, which dictate object structs + helper functions to retrieve information from, create, allocate, and free objects.

**Comment by patrickkoopmans** [comment]
Added player.c and player.h files which dictate player structs & helper functions to initialize and free players as well as abstract various aspects of the player's attributes through "get" and "change" functions.

**Comment by patrickkoopmans** [comment]
We decided to represent "exits" to a room within the room struct as a list of door objects rather than pointers to other rooms due to the locked/unlocked feature of travelling between rooms, as well as to allow a door between two rooms to be locked on one side but unlocked on the other. This list-based implementation is also dynamic by nature which will let us add as many exits to rooms as we wish.

**Comment by borjasotomayor** [comment]
When adding any code, please make sure to do either/both of these:

1. Include the issue number in the commit message (e.g., "#21"). This will make the commit appear in the issue.
2. Mention what branch the code was pushed to (there are already a fair number of branches on the repository, and it's not clear where this code was pushed to)

**Comment by patrickkoopmans** [comment]
We decided to change the get_inventory and get_clothes functions in the player module from iterators to functions which return a linked list. We believe this would be more useful to the UI/CLI team which would ideally display all the items within the players inventory/ worn on their body so they can decide which items they would like to remove/ replace etc. We need to discuss this with the UI/CLI teams before implementation.

**Comment by lindsey-hsi** [comment]
In this sprint, we've sketched out a preliminary design for rooms, players, and objects within game-state. Further, we made several decisions regarding structures to map rooms + handle inventory, and laid a foundation for collaboration with other teams. Please let us know if this design is sufficient and if the task can be closed! @borjasotomayor @lydiafilipe @mpcsh

**Comment by lydiafilipe** [comment]
Issue Score: ✓+

Comments:
Great work!
