### ISSUE TITLE
Write tests for the cmd module

### ISSUE THREAD

**Issue by Tianlel** [uchicago-cs/chiventure#216]
Write unit tests for all cmd functions that are independent of functions from other teams

**Comment by Tianlel** [comment]
I've created tests for cmd_new, cmd_from_tokens and cmd_from_string. However, cmd_from_string crashes and I'm not sure of the cause. Since the pull request #258 will affect the cmd module significantly, I need to merge the cli/integrate-ui branch (once finalized) with mine before writing more tests.

**Comment by Tianlel** [comment]
I've fixed the Makefile for the tests. I resolved issues caused by circular dependencies.

**Comment by Tianlel** [comment]
Update: 
I've finished writing tests for the new, init, free functions of the cmd and lookup_t structs. A bug is found in the cmd_free function.

**Comment by Tianlel** [comment]
Closing statement:
I forgot to git add my 1st version of tests, and the tests for cmd_from_tokens and cmd_from_string were lost accidentally. Nevertheless, after this week's group meeting, I realized that I only need to create unit tests for the struct related functions and can leave other functions to integration tests. As stated in the previous update, I've finished writing all the necessary tests and the bug will be fixed in #319

**Comment by lydiafilipe** [comment]
Issue Score: ✓+

Comments:
Nice work!
