### ISSUE TITLE
Modify action loading to load a pointer to a specific action struct.

### ISSUE THREAD

**Issue by victor-a-a** [uchicago-cs/chiventure#217]
The current `load_action()` function adds actions to the game state `item_t` struct as items.  This struct has been updated to include the action management action struct.  Hence, we have to update our function to load a pointer to an action struct instead of a string.

**Comment by victor-a-a** [comment]
We have updated the function to load a pointer to a heap allocation action struct to the item struct.

**Comment by lydiafilipe** [comment]
Issue Score: ✓+

Comments:
Nice work!
