### ISSUE TITLE
Update WDL Spec to reflect action conditions and simplify room connections

### ISSUE THREAD

**Issue by Kate32815** [uchicago-cs/chiventure#218]
In the previous sprint, the WDL Specification was modified to reflect code that could only support simple actions without any pre-requisite conditions. In this sprint, we are adding conditions to items with three attributes: 
- item id (e.g. door1)
- state of item (e.g. pulled)
- value of attribute (e.g. no)
So each action can have a list of conditions with the above three attributes, in addition to the text_sucess and text_fail attributes it already has.

Also we are removing the "through" attribute for room connections because our code currently does not support that but it will be added to the backlog.

**Comment by thoranderskow** [comment]
Might need to specify that the "value" field in conditions is yes/no, to make it easier to understand.

**Comment by thoranderskow** [comment]
wdl.md was updated to the aforementioned changes. It is likely the spec will need to be updated again before the end of the project, to include more features.

**Comment by lydiafilipe** [comment]
Issue Score: ✓+

Comments:
Nice work!
