### ISSUE TITLE
Create top-level documentation directory (+ guidelines)

### ISSUE THREAD

**Issue by borjasotomayor** [uchicago-cs/chiventure#22]
Create a top-level `docs/` directory with some basic guidelines on how to add documentation, and guidance on what should be included in any developer-facing documentation. This directory can also eventually include user-facing documentation.

**Comment by borjasotomayor** [comment]
I've added a docs/ directory with some basic developer documentation (including the branching strategy documentation that @mpcsh wrote). Is there anything else we want to include in this first bit of documentation?

**Comment by mpcsh** [comment]
LGTM for now

**Comment by lydiafilipe** [comment]
Sounds good!

**Comment by borjasotomayor** [comment]
Closed by #33
