### ISSUE TITLE
Create tests for  WDL create_game() function using tests

### ISSUE THREAD

**Issue by thoranderskow** [uchicago-cs/chiventure#224]
Create tests to test create_game(), check if game is initialized correctly with intro string.

**Comment by thoranderskow** [comment]
Created test_game.c in wdl/load_into_structs to test create_game() function.

**Comment by thoranderskow** [comment]
created pull request #260 to merge tests into dev.

**Comment by thoranderskow** [comment]
Basic tests were written for load_game.c to test create_game()'s functionality and pull request to merge to dev.

**Comment by lydiafilipe** [comment]
Issue Score: ✓+

Comments:
Nice work!
