### ISSUE TITLE
Write new structs to store incremental save log

### ISSUE THREAD

**Issue by jarvislam1999** [uchicago-cs/chiventure#229]
As part of incremental saving, we need to be able to store and serialize the log of changed attributes, which needs to be represented by a general struct.

(only initiate task after pr success)

**Comment by jarvislam1999** [comment]
I added a few structs within game.proto to represent the logs that future classes have to use. The only new structs that game state would have to deal with potentially is Logs, which is an array of logs that they have to call functions to fill in. I'm including in the new structs' definition below:

message Logvalueunion {
    optional int32 int_val = 1;
    optional string str_val = 2;
    optional double double_val = 3;
    optional int32 char_val = 4; //NO CHAR TYPE SUPPORTED IN .PROTO, SO USING I\
NT INSTEAD
    optional bool bool_val = 5;
}

message Logvalue {
    optional string tag = 1;
    optional Logvalueunion value = 2;
}

message Log {
    optional string level = 1; // To specify whether it's in game, player, etc
    optional string level_id = 2; // Id of player, room, etc
    optional string member = 3; // Indicate which member, such as player's "xp"
    optional Logvalue old_value = 4;
    optional Logvalue new_value = 5;
}

message Logs {
    optional int32 logs_len = 1;
    repeated Log logs = 2;
}

**Comment by jarvislam1999** [comment]
I have also added a bunch of basic functions to help game state deal with the logging. The format is as follow:

/* Store a changed value information in our array of logs
 * Parameters:
 * - logs: the array of logs
 * - level: either "game", "player", "room", "item", etc
 * - player_id : the id of that level string
 * - member : member of the level string
 * - old_value: old value of that member
 * - new_value: new value of that member
 * Return: 0 if SUCCESS, -1 OTHERWISE
 */
int checkpointing_log_int(Logs *logs, char *level, char *level_id, char *member\
, int old_value, int new_value);

However, as one can see, the code right now only supports integer logging. Future classes can decide on whether they want to duplicate this for every other type or change my functions to the void* value. As of now, since we won't be fusing this into game state this sprint. This is issue is finished.

**Comment by jarvislam1999** [comment]
I am closing this issue as it appears that the rest of the team are fine with the function format that I wrote. I have made a pull request to checkpointing/dev and assigned @jonahdf as a reviewer, but we expect nothing but minor changes. Thus, I will close the issue and focus on other priorities for the team.

**Comment by mpcsh** [comment]
Issue Score: ✓+

Comments:
Great work!
