### ISSUE TITLE
Write first specification of WDL file format

### ISSUE THREAD

**Issue by borjasotomayor** [uchicago-cs/chiventure#23]
Write a document (to be added in the directory being discussed in #22) that specifies the WDL format, specifically what YAML objects/properties/etc. we would find in a valid WDL file.

**Comment by bansals10** [comment]
The initial draft of the WDL Specification can be found here: 
[WDL Specification.pdf](https://github.com/uchicago-cs/chiventure/files/3139390/WDL.Specification.pdf)

Questions relating to WDL Specification:
1. Do we have a set list of actions that the user can write in the WDL file?
2. Should we keep actions separate from objects?

**Comment by borjasotomayor** [comment]
Please add the draft to the repository as either a text file or a Markdown file. PDFs are not editable, nor can their changes be tracked easily via version control.

In the future, for something this short (1-2 pages), you may want to simply post that content as a comment in the issue, as a way to encourage discussion around that content.

**Comment by bansals10** [comment]
The Markdown file containing our draft can be found in the wdl/wdl_spec_draft branch. The file name is WDL_README.md.

**Comment by borjasotomayor** [comment]
Please move the specification into a src/wdl directory. It does not belong in the root of the repository.

Please avoid cluttering the commit log with multiple "Updated formatting" commits when editing a Markdown file. I'm guessing you were editing it directly through the GitHub website; this is fine for small edits but, for larger edits (specially when you're not sure whether Markdown will produce the desired formatting), you should edit the file on your own computer, and use a Markdown-capable editor to preview the formatting before committing your changes to the repository.

**Comment by borjasotomayor** [comment]
fyi, we will eventually be moving all documentation to a top-level `docs/` directory (see #22) but, for now, these kind of files belong in each component's directory inside the `src/` directory.

**Comment by borjasotomayor** [comment]
Finally, regarding the two questions you pose, you will have to discuss this with the action management team, but you do not need to do this in this first sprint. We will spend part of Monday's all-hands meeting identifying what teams need to collaborate during the second sprint.

**Comment by thoranderskow** [comment]
@borjasotomayor We're about to close and write closing statement, does everything look okay for sprint 1?

**Comment by borjasotomayor** [comment]
Yes, but please move the specification into the docs/ directory and merge it with the `wdl/dev` branch. Note: you will need to merge the latest changes from `master` for the `docs/` directory to appear. I suggest you do the following:

- Merge `wdl/wdl_spec_draft` into `wdl/dev`
- Merge `master` into `wdl/dev` (this will updated `wdl/dev` with the latest changes from `master`, including the new `docs/` directory)
- Then, in the `wdl/dev` branch, move the specification into `docs/`

**Comment by bansals10** [comment]
This has been completed. The spec draft is now located in docs/ within the wdl/dev branch.

**Comment by thoranderskow** [comment]
Closing Statement
Wrote up an early specification for WDL, mainly three object files called Game, Room, and Items(previously called objects). The two questions posed,
1. Do we have a set list of actions that the user can write in the WDL file?
2. Should we keep actions separate from objects?
were deemed to be more appropriate for the second sprint, and will be addressed accordingly.

**Comment by lydiafilipe** [comment]
Issue Score: ✓

Comments:
Great work! When you are doing iterative design though, it is important that updates are posted as comments on the issue or that the entire document has been under version control throughout the process.
