### ISSUE TITLE
Update code to use context struct, add Hashtable to context struct

### ISSUE THREAD

**Issue by ecoble** [uchicago-cs/chiventure#230]
Add the hashtable to the Chiventure context struct since it has to be used by the UI team, and update all functions currently taking the game struct and hashtable struct as a parameter to instead take the chiventure context struct

**Comment by ecoble** [comment]
UPDATE: I have added standard new, free, and init functions for the hashtable and command structs. Replaced places where we were using game_t parameters and some lookup_t parameters with the new chiventure_ctx_t struct. Having some circular dependencies between ctx.h and cmd.h, tried to separate the hashtable into it's own module but this seemed to cause even more circular dependencies.

**Comment by Gestalt-R** [comment]
Will be refactoring hashtable into its own module while still managing dependencies later today.

**Comment by ecoble** [comment]
UPDATE: Circular dependencies were fixed by moving around include statements. The hashtable has been added to the chiventure context struct so it can be used by other teams as well. A separate issue will be created to refactor the hashtable into its own module.

**Comment by ecoble** [comment]
CLOSING STATEMENT: The hashtable is now part of the chiventure context struct, and the chiventure context struct is being used in CLI code instead of game structs and hashtable structs individually. There are also standard new, init, and free functions for the hashtable and cmd structs now. A new issue will be created to try and refactor the hashtable into its own module, which will hopefully help with the circular dependencies.

**Comment by lydiafilipe** [comment]
Issue Score: ✓+

Comments:
Great work!
