### ISSUE TITLE
Write tests for parser module

### ISSUE THREAD

**Issue by ecoble** [uchicago-cs/chiventure#231]
Write tests for the parser, which does not reply on other team's functions

**Comment by ecoble** [comment]
UPDATE: Created a basic set up for tests, test folder, Makefile, main file to run the tests, empty test_parser.c file

**Comment by ecoble** [comment]
UPDATE: pulled in tests that Efraim wrote into this branch, updated the parser to catch empty input since this did not exist before

**Comment by ecoble** [comment]
UPDATE: Added a test for input with a lot of spaces between words, e.g. "LOOK      AT    ME       "

**Comment by ecoble** [comment]
CLOSING STATEMENT: There are now 7 tests for the parser module, a test for no input, a test for 1 word, 2 words, 3 words, and 4 words, a test for too more words than allowed (anything more than 4, in this case 5), and a test for input with excessive spaces surrounding words. All tests pass. In the process of making these tests, we added a catch in the parser if the user gives no input.

**Comment by lydiafilipe** [comment]
Issue Score: ✓+

Comments:
Nice work!
