### ISSUE TITLE
Create stub function for add_allowed_action(), allowed_action(), and path_search() to make sure tests compile

### ISSUE THREAD

**Issue by lucyyutingli** [uchicago-cs/chiventure#233]
While waiting for #186 to be approved, we will make a stub for add_allowed_action(), allowed_action(), path_search() in order to check that our tests are compiling. Once the PR is approved, we will work on issue #234 which is focused on refactoring these functions in.

**Comment by SnowballAntrobus** [comment]
Unnecessary since #186 went through!
