### ISSUE TITLE
Add check to see if action can be performed on direct item in function do_item_item_action

### ISSUE THREAD

**Issue by SnowballAntrobus** [uchicago-cs/chiventure#235]
Currently do_item_item_action only checks if the action can be performed on the the indirect item. We will be adding a check to see if the action can be performed on the direct item. This is done using the game state allowed_action function.

**Comment by SnowballAntrobus** [comment]
We have added this check. It will be tested in #242.

**Comment by SnowballAntrobus** [comment]
Closing Statement:
There was a major oversight when writing the do_item_item_action function that got through both the code writers and their reviewers. Fortunately, the issue was caught when looking through code to write tests. The issue was that the direct item was not being tested to check if it allowed the action it was being acted on by.  We added this validation step to the function. This means that for our next issue we will now be able to write tests that check that both the direct and the indirect item allow an action.

**Comment by mpcsh** [comment]
Issue Score: ✓

Comments:
Minimal progress updates. Closing statement only well after the fact.
