### ISSUE TITLE
Introduce the ability to mix and match conditions

### ISSUE THREAD

**Issue by yoonsjeong** [uchicago-cs/chiventure#240]
*this is a backlog issue and is not a current priority*
Here is a rough example of what we would expect from this issue.

We want to create a game in which you can "OPEN DOOR" either if you have performed the item "USE SKELETON KEY" or if you have visited "Fountain of Knowledge". Essentially this entails the ability to use an OR statement with WDL.

- WDL: a scheme for having either/or
- Game-State: would have to alter their parameters to have attributes set up to accommodate this
- Action-Management: would use game-state code to perform said action

Please feel free to comment on how this might be implemented since it is only a very rough sketch at the moment.

**Comment by MTUC08** [comment]
Given the way that we have ended up structuring conditions, this actually might be possible with the current design, i.e. both the use action under skeleton key and the go action under fountain of knowledge would have the effect of opening the door
