### ISSUE TITLE
Add tests for do_item_action checking for when an action is and isn't allowed on an item

### ISSUE THREAD

**Issue by SnowballAntrobus** [uchicago-cs/chiventure#241]
The goal is to make more tests for do_item_action that cover the possibility that the action cannot be performed on an item because it is not in its list of allowed actions.

**Comment by SnowballAntrobus** [comment]
Closing statement:
We wrote more tests for the function do_path_action. These tests focused on making sure that the correct string is being printed when allowed and un-allowed actions are used on the item, which we call direct. In future work we would make testing simpler by making the return value of the function an error code int. Additionally, we will make more tests for this function once it is updated to change game state.

**Comment by mpcsh** [comment]
Issue Score: ✓-

Comments:
No progress updates. Closing statement only well after the fact.
