### ISSUE TITLE
Refactor AM modules for ease of unit testing

### ISSUE THREAD

**Issue by MTUC08** [uchicago-cs/chiventure#245]
Refactor action functions (do_item_action, do_path_action, do_item_item_action) to pass the string to CLI in an output parameter, so we can have the functions return SUCCESS(0) or FAILURE(1) for ease of testing. This prevents complete test failure if we alter the passing string within the function. This will only alter the code in PR #244  so the functions do not deal with conditions or attributes yet. We will add conditions/attributes through issues #188 #190 and #191 .

Since this will directly impact CLI, this will be a joint venture with the CLI team. Their changes to preemptively fix the code this change will break will also be added to our feature branch actions/change_return_format, so that it can be carried into actions/dev and then master without creating a separate PR.

**Comment by MTUC08** [comment]
Update: just changed the description of the functions within actionmanagement.h and the reformatting within actionmanagement.c

**Comment by yoonsjeong** [comment]
I recall during the sprint meeting Borja proposed that we also have different error outputs -- for example, output the integer 1 when kind is incorrect, and integer 2 when not an allowed action.

**Comment by MTUC08** [comment]
@borjasotomayor just to confirm, should we still have different integer outputs if we are additionally outputting a message? Currently, the function will output 0 upon success, with a success message, and 1 upon failure, with different error messages. Since our functions will be used by CLI, who will likely just pass the outputted string to the user, are different integers needed for different errors?

**Comment by borjasotomayor** [comment]
Yes, different integers will allow your function to be more testable, because your tests can then check whether it is correctly distinguishing between the different types of errors.

**Comment by MTUC08** [comment]
Update: updated the action management.h file with descriptions of which errors produce which ints as output, and defined 1 as WRONG_KIND and 2 as NOT_ALLOWED within the code in actionmanagement.c

**Comment by ecoble** [comment]
UPDATE: Updated CLI's use of action management's functions, we now malloc a string to pass to each action management function, and then print this string after the function call.

Note: For now I have put in printf, but once the PR for CLI and UI integration is through I will be changing this to print to the UI window

**Comment by ecoble** [comment]
UPDATE: Changed CLI use of action management's functions, before I was using malloc to create a string to pass to AM, but realized this was unnecessary since they malloc a string. We are now passing a null pointer.

**Comment by borjasotomayor** [comment]
Please note that the `ret_string` parameter is meant as an *output* parameter, which means you have to pass `&str` and not `str`, so that the `str` variable will end up pointing to the string malloc'd by CLI. In fact, if you compile the code in this branch, it produces this warning:

```
note: expected ‘char **’ but argument is of type ‘char *’
```

Remember that compiler warnings are just errors that are bidding their time. You should aim to produce code that produces no compiler warnings at all.

**Comment by ecoble** [comment]
UPDATE: Fixed the above issue mentioned by Borja (thanks!)

**Comment by SnowballAntrobus** [comment]
All tests have been refactored to use the new function return value. Complies and all tests pass in branch actions_change_return_format_tests

**Comment by MTUC08** [comment]
Nice! I'll PR this stuff to actions/dev and master as soon as #289 goes through

**Comment by MTUC08** [comment]
Just added these files to PR #289 . 
Summary:
In this issue, we reformatted our functions to return an int for ease of testing,  moved the return string to an out parameter, and altered our test files to reflect that change.  CLI also added file changes to reflect the new parameter and return format.
Looking forward, we will add conditions/attribute handling to create the full implementation of our action functions (#188 #190 #191 ) and update our tests to reflect those changes (#189 #192 #193 )

**Comment by lydiafilipe** [comment]
Issue Score: ✓+

Comments:
Nice work! Great updates
