### ISSUE TITLE
Merge validate module into operations module

### ISSUE THREAD

**Issue by Tianlel** [uchicago-cs/chiventure#253]
Since our hashtable structs and game state macros easily allow us to check the validity of actions, we no longer need a validation module or it will be really shallow. So we decided to merge it into the operations module.

**Comment by Tianlel** [comment]
Closing statement:
Merging done.

**Comment by lydiafilipe** [comment]
Issue Score: ✓+

Comments:
Nice job! Generally it's good to have more detailed closing statements and updates but since this is a small issue this is sufficient.
