### ISSUE TITLE
Integrate game states get_item_in_room function in operations

### ISSUE THREAD

**Issue by efraimdahl** [uchicago-cs/chiventure#256]
Instead of iterating over game-states items in room hashtables ourselves we would like to  use game states get_item_in_room function.

**Comment by efraimdahl** [comment]
UPDATE: The branch cli/game-state-integration now has all changes made to operations.c and the Makefile in the example folder. 
Also the Makefile is made more modular by extracting the library linking into separate variables.

**Comment by efraimdahl** [comment]
CLOSING NOTICE
Pushed changes to cli/dev

**Comment by lydiafilipe** [comment]
Issue Score: ✓+

Comments:
Nice job! Generally it's good to have more detailed closing statements but since this is a small issue this is sufficient.
