### ISSUE TITLE
Modify room_new function in room.c in Game State to malloc space for short_desc, long_desc, room_id strings

### ISSUE THREAD

**Issue by Kate32815** [uchicago-cs/chiventure#265]
The current code for room_new (on line 6 of room.c) is as follows:

room_t *room_new(char *room_id, char *short_desc, char *long_desc) {
    room_t *room = malloc(sizeof(room_t));
    room->room_id = room_id
    room->short_desc = short_desc;
    room->long_desc = long_desc;
    room->items = NULL;
    room->paths = NULL;
    return room;
}

Here, the room_id, short_desc, and long_desc strings are not allocated memory so it may be throwing an error when the room_new function is used. Modifying the code to use the function "strdup" with the strings may fix the issue:

room_t *room_new(char *room_id, char *short_desc, char *long_desc) {
    room_t *room = malloc(sizeof(room_t));
    room->room_id = **strdup**(room_id);
    room->short_desc = **strdup**(short_desc);
    room->long_desc = **strdup**(long_desc);
    room->items = NULL;
    room->paths = NULL;
    return room;
}

**Comment by jessxia** [comment]
Which branch is this room.c code on? I believe the room_new and room_init functions in room.c on both master and game-state/dev use malloc and then strncpy

**Comment by Kate32815** [comment]
Sorry I made a mistake --I was looking at the wrong branch. The strings are being malloced already. I am closing this issue.
