### ISSUE TITLE
Coldfix: Moving operations

### ISSUE THREAD

**Issue by Gestalt-R** [uchicago-cs/chiventure#268]
In a previous commit to master, two operations (a CLI internal use type) were created in a file in src/ui. All operations should be only in "src/cli/src/operations.c". Thus, we should fix this by re-typing the two functions in UI (map and something else which I will find soon and update this issue with) to more appropriate things, as they currently have extra inputs, and by creating operations in operations.c that call on these two functions.

**Comment by lydiafilipe** [comment]
Issue Score: ✓-

Comments:
Nice summary! However, the title is a bit vague and there is no closing statement.
