### ISSUE TITLE
Support for Quit Command

### ISSUE THREAD

**Issue by ecoble** [uchicago-cs/chiventure#273]
As part of CLI/UI integration, we stopped supporting "QUIT" to quit from the game, and instead used UI's CTRL + D to quit. We can reintroduce "QUIT", this may require collaboration with UI since CLI is no longer in charge of the command prompt loop.

**Comment by samdonio** [comment]
Just met with Elizabeth, it seems like the print_cli function is what controls what is entered into the cli, and this in turn is called by the window_print function. Right now both of these functions are void, but one way of adding quit could be to test if the user enters "quit" and return some value through both of them and then have this value checked in the game loop where it is checked if the user pressed "CTRL+D"

**Comment by mberamendiconde** [comment]
^^^ I was also in this meeting with Elizabeth, and we bounced off approaches like Sam mentioned above

**Comment by samdonio** [comment]
Return values were added to several functions in order to determine if the user inputs QUIT, however now chiventure doesn't quit at all. After using gdb, the return values seem correct, so QUIT not working doesn't immediately make sense, but I will look into possibly using the getstr() function and if it the user types QUIT then end_win is called.

**Comment by samdonio** [comment]
Created the cli/quit-working-solution branch that now has a working solution to adding the quit command to chiventure. An out parameter was added to many of the functions that interact with the cli in the ui module and if the term "QUIT" is inputted by the user the pointer 'quitval' has value 0, and thus ends the ui loop effectively ending chiventure.

**Comment by mberamendiconde** [comment]
Success! This issue is now closed. The user can type "QUIT" into the command line rather than only using "Ctrl + D" to quit the game and exit the terminal.

**Comment by ecoble** [comment]
Issue Score: ✔️++

Comments:
Great job implementing this backlog issue! I know working with the UI code can be tricky, nice work!
