### ISSUE TITLE
Clean up dependencies in header files and sanitizes the makefiles

### ISSUE THREAD

**Issue by Tianlel** [uchicago-cs/chiventure#276]
Remove unnecessary includes and remove -Wl,--start-group/-Wl,--end-group  in tests/Makefile by correcting the linking order of the static libraries

**Comment by Tianlel** [comment]
Closing statement:
I cleaned up the header file dependencies and corrected the linking order of static libraries in tests/Makefile

**Comment by lydiafilipe** [comment]
Issue Score: ✓+

Comments:
Nice work!
