### ISSUE TITLE
Creating a sample game for testing purposes

### ISSUE THREAD

**Issue by Tianlel** [uchicago-cs/chiventure#278]
Use game-state and action management modules to create a 1-player 2-room sample game. 
There will be two items in the first room: an orb and a table. The orb can be taken by the player and can be placed on the table. 
There won't be any item in the second room when the game is initialized, but the orb can be taken to the second room and be dropped onto the floor.

**Comment by yoonsjeong** [comment]
Here are a list of the actions it seems like we'd need in this sample:
- "TAKE"
- "DROP"
- "PUT_ON" (so far this is still considered a one word action)
- "GO"

Is there a folder or branch where we can start writing the code for this sample game?

**Comment by Tianlel** [comment]
I've created new branch common/samplegame for this issue

**Comment by Tianlel** [comment]
Closing statement:
We created a very simple two-room sample game struct with 1 player and 2 items (item_orb and item_table). 
item_orb supports actions "TAKE", "DROP", and "PUT_ON".
item_table supports action "PUT_ON".
This game struct sample can be used by cli, action_management, and checkpointing for integration tests.

**Comment by lydiafilipe** [comment]
Issue Score: ✓+

Comments:
Nice work!
