### ISSUE TITLE
Update WDL spec to contain end condition.

### ISSUE THREAD

**Issue by thoranderskow** [uchicago-cs/chiventure#279]
The prototype will only end the game if the player enters a room that is specified in the WDL file as the final room. The spec must be updated to reflect this.

**Comment by thoranderskow** [comment]
Spec was updated, and I removed having an item in your inventory as an end condition.

**Comment by lydiafilipe** [comment]
Issue Score: ✓+

Comments:
Nice job! Generally it's good to have more detailed closing statements and updates but since this is a small issue this is sufficient.
