### ISSUE TITLE
remove dependency on path.h

### ISSUE THREAD

**Issue by a-matai** [uchicago-cs/chiventure#280]
After the refactoring of path.h into item.h, ensure there are no references to path.h in any teams' work so the file may be removed.

**Comment by a-matai** [comment]
Looked through all include files in all the /dev branches and we are almost clear!

@bansals10 wdl_common includes path.h so could you remove that whenever you get a chance?

**Comment by bansals10** [comment]
Done. @a-matai

**Comment by Tianlel** [comment]
Closing statement:
All dependencies on path.h have been removed as requested.

**Comment by lydiafilipe** [comment]
Issue Score: ✓+

Comments:
Nice work!
