### ISSUE TITLE
Prepare load_into_structs for merging into dev and master

### ISSUE THREAD

**Issue by bansals10** [uchicago-cs/chiventure#284]
We are working to resolve conflicts and testing issues in our code before sending a PR to dev and ultimately to master. The problems we are encountering have to do specifically with file placement within our organizational structure. Once the code compiles properly and all tests pass, we will make the PRs.

**Comment by mewthew** [comment]
Updates:
Commit SHA for code changes for this issue: 8c4793b
We currently fixed the test issues found in the above commit. 

Next Steps:
We will now make make our tests more thorough for unanticipated bugs.

**Comment by mewthew** [comment]
We have finished fixing game tests (they were failing because we weren't accessing the correct item within the yaml file). We are now ready to create a PR into dev and eventually to master with the load_into_structs branch.

**Comment by lydiafilipe** [comment]
Issue Score: ✓

Comments:
Nice work! I think the title could have been a bit more descriptive - the branch name itself doesn't say much about what's going on. The summary is also a bit vague about what the exact problems are. And including a summary of the changes in the updates would be good too. Nice job linking the SHA and explaining test failures!
