### ISSUE TITLE
Fix spacing and formatting according to style guide

### ISSUE THREAD

**Issue by jonahdf** [uchicago-cs/chiventure#290]
I have noticed that our spacing and formatting has gotten sloppy lately, so I want to do a massive sweep of all the code and fix mostly:
- Tabbing/spacing
- Commented out code
- white space

**Comment by ellynliu** [comment]
I just deleted a lot of unnecessary comments in save.c and deleted functions that were no longer being used in save.h

**Comment by ellynliu** [comment]
Just went through load.c and clarified some comments, deleted unnecessary commented out code, and moved some comments to the correct place as some comments were not in the right place.

**Comment by jonahdf** [comment]
I went back to load.c, and fixed some tabbing issues.

**Comment by jonahdf** [comment]
I added lots of spaces before curly brackets, and removed unnecessary whitespace from both files

**Comment by jonahdf** [comment]
I think the formatting looks good. Maybe more will be caught in the PR, but I have done a few checks so I'm gonna close the issue.

**Comment by mpcsh** [comment]
Issue Score: ✓+

Comments:
Great work!
