### ISSUE TITLE
Change the wdl spec once again to add that all actions must be in upper case.

### ISSUE THREAD

**Issue by thoranderskow** [uchicago-cs/chiventure#295]
Due to some internal functions, some within action-management, actions must be specified in all capitals.

**Comment by thoranderskow** [comment]
Also just specified that directions must be lowercase.

**Comment by thoranderskow** [comment]
Wdl has been updated, and a pull request was made #299

**Comment by lydiafilipe** [comment]
Issue Score: ✓+

Comments:
Good work! A lot of this was a bit brief but this is fine given the issue. In the summary it would have been good to specify which functions or action management modules
