### ISSUE TITLE
Implement basic action management module

### ISSUE THREAD

**Issue by borjasotomayor** [uchicago-cs/chiventure#30]
After conversing with other teams and looking at their preliminary functions, refactor action management struct and functions and begin implementation. This implementation will be a rough draft and evolve as other teams evolve their code as well.

**Comment by yoonsjeong** [comment]
The current list of "parent actions" we have are the following
{OPEN,CLOSE,PUSH,PULL,EXAMINE,TURN_ON,TURN_OFF,TALK_TO,GIVE,GO,TAKE,DROP,CONSUME,USE_ON}

These actions are how commands like "open <object>" or "close <object>" will be represented in the actual code. That means that "action synonyms" will be represented using these as well. For example, "walk <direction>" and "go <direction>" would be identical for the purpose of altering the game state, and therefore the enumerated variable "GO" would be used to represent both.

Here is our tentative list of synonyms (please feel free to critique/suggest)

EXAMINE: examine, look at
TALK_TO: talk to, talk
GIVE: give to, give
GO: walk, go
TAKE: pick up, take
DROP: drop
CONSUME: eat, drink, use

**Comment by yoonsjeong** [comment]
In our module, we use a number of "assumed structs" which the Game State team would be responsible for. Those structs include the npc_struct, room_struct, object_struct, and player_struct.

Within those structs we assume player_struct contains the information for the inventory, that the object_struct contains the actions allowed to be performed on that action, and that the room_struct contains the objects and npcs capable of being acted upon. 

Here is the file with all of the structs and details:
https://github.com/uchicago-cs/chiventure/blob/action_management/src/action_management/include/structs.h

**Comment by MTUC08** [comment]
Is this issue meant to be creating the c files based on the h files in #7?

**Comment by mpcsh** [comment]
Yes. Whoever is taking this task should fill in the description with a rough outline of what needs to be done, but that's the basic idea.

**Comment by yoonsjeong** [comment]
Assigned the following roles
inventory actions: Elly
world actions: Yoon
NPC actions: Melinda

**Comment by yoonsjeong** [comment]
Dependencies:

CLI
- we require CLI to store objects that can be acted on to have a portion, say called "enum object_type" that is within the object struct. objects include any word that can have an "action" used upon it. The following are examples 
> in the command WALK east -- east would be the object, with an object_type "direction"
> in the command TAKE ball -- ball would be the object, with an object_type "item"
> in the command TALK TO borja -- borja would be the object, with an object_type "character"

**Comment by ellychoi** [comment]
Game State:

- After meeting with Game State, it has been determined that any changes to the room struct we have regarding the map of the room will be done after Game State has decided in what manner they would like to store the information. Furthermore, before we require functions from game state, I showed them the functions in actionmanagement.h such as "int act_n_talk_to(action_struct *a, object_struct *o, npc_struct *n);" which alters the game state according to a "give" action. Based on this, game state will look at our functions and come up with a way to use the int values to necessarily update the game state. As we continue to write our implementations, we will discover the need for certain functions that we will communicate with Game State.

**Comment by yoonsjeong** [comment]
we need a "get_supported_actions()" function

**Comment by borjasotomayor** [comment]
@yoonsjeong: In general, please avoid curt statements like these. While it is good practice to update issues after an in-person/Slack discussion, something like "we need a get_supported_actions() function" provides very little information. You should aim to provide a summary of what was discussed at the meeting. What is the purpose of this function? What does this function return? Who would be calling it? etc.

**Comment by yoonsjeong** [comment]
I've implemented the get_supported_actions() function which takes in no inputs and outputs a list of our action struct action_t.
This is a function that should be used by other teams to get the full list of actions they have the ability to use.

**Comment by yoonsjeong** [comment]
We have split implementation of the functions into the following groups for convenience:

implementing individual actions:
Elly - OPEN to EXAMINE
Melinda - TURN_ON to CONSUME
Yoon - GO to USE_ON

implementing the other functions we have:
Elly - action new, init, free
Melinda - get_supported_actions
Yoon - action_type1, 2, 3, 4

**Comment by borjasotomayor** [comment]
Could you elaborate on what "implementing individual actions" refers to? If it refers to the "action type" structs we discussed in the meeting, that is fine. If it refers to actual functions, that suggests you're moving towards a less-general design. 

In particular, I am not sure why you need functions `act_open`, `act_close`, `act_push`, etc. *Do not* implement these functions before we discuss this further. If `get_supported_actions` returns a list of actions, then it should be enough for CLI to call the `action_typeN` functions; there should be no need to have a separate function per action type.

Also, please remember that you should either link your commits to the issue they correspond to (for this issue, it would be enough to include "#30" anywhere in the commit text) or, if you push any new code, post a comment in the issue that says what branch that code can be found in.

**Comment by MTUC08** [comment]
Just finished implementing action_npc, action_item_npc, and action_item_item (issue #72)

**Comment by MTUC08** [comment]
In this week's spring, we refactored our individual action functions into the functions action_item, action_direction, action_npc, action_item_npc, and action_item_item and altered our action struct to contain an enum of the action, the canonical name as a string, a list of synonyms, and an enum of the kind of action. We then implemented our new functions along with our action_new, action_init, and action_free functions. We also added get_action_cname, get_action_synonyms, get_action_kind, and get_supported_actions functions for use by other teams. However, this is still a rough draft. Looking forward to Sprint 3,  we will pass along to game state our expectations for functions we incorporated into our action implementation, and reach out to both game state and cli to flesh out a better understanding of the structs and functions we will have to implement our action functions, and refine our implementations.

**Comment by mpcsh** [comment]
Issue Score: ✓

Comments:
There seemed to be substantial confusion on what exactly this issue was supposed to entail, which should have been clarified early on with a more detailed summary. It looked like the assignees were too eager to start hacking and didn't spend enough time on the design. Also, commits related to this issue should've been referenced by including "#30" in the commit text.
