### ISSUE TITLE
Properly format CLI output

### ISSUE THREAD

**Issue by sebvil** [uchicago-cs/chiventure#303]
In this task I will modify the print_to_cli function so output is formatted correctly: all lines are properly indented, output is properly scrolled when the last line is reached, and if output does not fit the screen, then an option to press enter to show more output is given

**Comment by sebvil** [comment]
Closing Statement: the print_to_cli function was modified so that strtok divides input strings by their lines, and each line is properly indented when printed. If the output does not fit the screen, the user is prompted to hit enter to see more output, or to press q if they want to continue the game.

**Comment by mpcsh** [comment]
Issue Score: ✓+

Comments:
Great work!
