### ISSUE TITLE
Catching errors when game pointer not initialized

### ISSUE THREAD

**Issue by Gestalt-R** [uchicago-cs/chiventure#310]
Currently, the functions will segfault if the game pointer isn't initialized. In normal operations, they should be initialized, but this helps for bugfixing.

I hope to add code to each operation that accesses a game to output an error message if it isn't initialized.

**Comment by Gestalt-R** [comment]
This branch added in all the necessary code that was needed to output the errors in operations.c.

I consider the issue resolved with the merge.

**Comment by lydiafilipe** [comment]
Issue Score: ✓

Comments:
Nice job! Generally it's good to have more detailed closing statements and updates but since this is a small issue this is okay. However it would have been nice as part of the closing statement or an update to specify a bit more exactly what you did for the fix.
