### ISSUE TITLE
Create load_wdl function to load all of a wdl file into game-state structs

### ISSUE THREAD

**Issue by thoranderskow** [uchicago-cs/chiventure#312]
Basically we are creating a single function that will extrapolate all of our previous load functions to a high level for ease of use.

**Comment by thoranderskow** [comment]
Some of game-state's functions were making our tests crash, specifically all_items_from_game. We are going to make an issue so they may update their function.

**Comment by thoranderskow** [comment]
Load_wdl has been completed, and end conditions were added, but due to a PR of game-state's not getting through in time, it could not be added to master's code.

**Comment by lydiafilipe** [comment]
Issue Score: ✓

Comments:
Nice work on the issue! It would have been good to  see more detailed updates, particularly on the specifics of how you were dealing with this task.
