### ISSUE TITLE
Update inconsistency with return values

### ISSUE THREAD

**Issue by bansals10** [uchicago-cs/chiventure#314]
Throughout the validation code, boolean values are being used instead of the macros defined as SUCCESS (0) and FAILURE (1). The code must be refactored to reflect the macros instead of the boolean return values.

**Comment by ela-ine** [comment]
Updated validate.c and validate.h to reflect changes in return values. Pushed to branch wdl/return_values.

**Comment by ela-ine** [comment]
Submitted a pull request and discovered that I missed the test file and a few other wdl files that used the validation functions. Those files have since been updated to reflect the change to macros. Pull request has been reviewed by @noahklowden and @MaxineK36 and approved.

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Awesome job! In particular, the closing statement on this issue is a clear, concise, and incredibly useful.
