### ISSUE TITLE
Fix bug in cmd_free()

### ISSUE THREAD

**Issue by Tianlel** [uchicago-cs/chiventure#319]
Fix the bug discovered in #216.

**Comment by Tianlel** [comment]
Closing statement:
The bug was caused by the attempt to free token memory which is not dynamically allocated. I removed that part of the code. Now the test for cmd_free() passes.

**Comment by lydiafilipe** [comment]
Issue Score: ✓+

Comments:
Nice job! Generally it's good to have updates but since this is a small issue this is sufficient. Nice job referencing the other issue and also explaining the problem in the closing statement.
