### ISSUE TITLE
Make a checkpointing.md file inside the docs folder

### ISSUE THREAD

**Issue by ellynliu** [uchicago-cs/chiventure#323]
Write a checkpointing.md file that will go inside the docs folder in master. This documentation will be more specific than the README in checkpointing/src. Explain what the different modules do, how protobuf is used, how functions should be called, and other documentation for future developers to reference.

**Comment by ellynliu** [comment]
Update: this file will be replacing our README in our checkpointing folder. This file will include more information concerning make and how to call functions

**Comment by schin99** [comment]
Added more description to the README in checkpointing folder. We decided that checkpointing.md will be more descriptive in documentation for future developers to reference. The README will include documentation in how to make the makefile, dependencies and descriptions of save() and load().

**Comment by ellynliu** [comment]
Writing the checkpointing.md file makes you think about what others really need to know in order to understand what we are doing. Also, thinking about having a deep module, we will probably edit both save.h and load.h to only include one function call. save() and load() are the only functions that need to be called by other teams, which in turn calls a bunch of helper functions that other teams don't need to understand to use.

**Comment by ellynliu** [comment]
We are done writing the updated README and checkpointing.md file as of end of sprint 4. Hopefully this documentation helps explain the code, semi-incremental saving, and help future checkpointing groups be able to quickly pick up from where we left off.

**Comment by mpcsh** [comment]
Issue Score: ✓+

Comments:
Great work!
