### ISSUE TITLE
Hotfix: Remove the action "ENTER", so that there is only one do_path action "GO"

### ISSUE THREAD

**Issue by yoonsjeong** [uchicago-cs/chiventure#324]
This is really just a tiny fix but I've labeled this under game-state and CLI just in case it does affect their code as well.

We've opted not to use unique "path" actions, instead hoping that synonyms will have the same effect. As it stands currently, we have two different actions "ENTER" and "GO" (meant to be used for commands such as "ENTER cave" vs "GO south") but since there are not ways of differentiating path (e.g. "cave" and "south") we will simply use GO as the one and only action. This is a potential backlog issue, or it may be solved with the implementation of synonyms, a backlog issue #120.

**Comment by yoonsjeong** [comment]
To clarify I've altered two different branches that reflect the change in this issue:

**BRANCH actions/dev**
`src/get_actions.c`
- removed the ENTER action  

`tests/test_get_actions.c`
- NUM_ACTIONS has been set to 12

**BRANCH `actions/do_path_191`**
`tests/test_path_actions.c`
- removed instances of the action "ENTER" and substituted with "GO"

**Comment by mpcsh** [comment]
Issue Score: ✓+

Comments:
Great work!
