### ISSUE TITLE
Update loading rooms and game with latest type-checking and spec modifications

### ISSUE THREAD

**Issue by mewthew** [uchicago-cs/chiventure#327]
After our PR to master is approved for wdl/improved_validation and wdl/load_into_structs, we need to integrate the latest type-checking from improved_validation for rooms (item has been completed) into their respective load code. We aim to automatically type-check the yaml fields within the loading functions such that there are less function calls when we load from the WDL file into game-state structs.

**Comment by mewthew** [comment]
Update: the PR to master for both improved_validation and load_into_structs has been completed. We can now proceed to use the function `extract_objects` from the parse module to verify loading rooms.

**Comment by mewthew** [comment]
Update: We have updated the rooms loading to go through type_checking (with `extract_objects`). These changes can be found in: 02d56f2.

**Comment by mewthew** [comment]
We now support loading rooms and items type-checking before they are loaded into game-state structs. What this means is that we can verify that the inputs into the WDL file are correct, such as a string is entered for an ID rather than an integer. We have done this with the 'extract_objects' function in the parse module, which automatically type-checks a room or item object from a YAML file, and has been integrated with our loading rooms and items functions such that we type-checking is automated with loading rooms and items.

**Comment by lydiafilipe** [comment]
Issue Score: ✓+

Comments:
Great work!
