### ISSUE TITLE
Fix game-state makefile in AM PR to master

### ISSUE THREAD

**Issue by a-matai** [uchicago-cs/chiventure#329]
game-state needs to hop onto AM's actions/dev and fix the makefile so PR #325 build passes.

It seems the issue is that test_items is not compiling because it includes ctx.h which now includes ui_ctx.

copied over from travis:
../../common/include/ctx.h:12:20: fatal error: ui_ctx.h: No such file or directory
compilation terminated.
Makefile:25: recipe for target 'test_items.o' failed
make[1]: *** [test_items.o] Error 1
make[1]: Leaving directory '/home/travis/build/uchicago-cs/chiventure/src/game-state/tests'
Makefile:43: recipe for target 'tests' failed
make: *** [tests] Error 2
The command "make tests" exited with 2.
0.00s$ tests/test-libgamestate
/home/travis/.travis/functions: line 104: tests/test-libgamestate: No such file or directory
The command "tests/test-libgamestate" exited with 127.

**Comment by a-matai** [comment]
Added the include directories of all other teams into the game-state Makefile and the test Makefile to allow for future changes in the ctx header. Seems like everything works fine now on game-state's end for #325.

Closing the issue.

**Comment by lydiafilipe** [comment]
Issue Score: ✓+

Comments:
Nice work!
