### ISSUE TITLE
Add Color to the UI

### ISSUE THREAD

**Issue by Sshatzkin** [uchicago-cs/chiventure#333]
Having a green-on-black adds to the retro aesthetic.

**Comment by Sshatzkin** [comment]
Color was a feature that was implemented in the prototype UIs that we made during sprint 1. I thought it would be nice to bring it back to the current UI. It was a relatively small change  requiring the initialization of some color pairs and a few function calls to nurses functions that assign color pairs to windows.

**Comment by Gestalt-R** [comment]
I might be able to add multiple palette swaps. It shouldn't be too difficult. If your pull request gets through, I can add a command to swap on the fly.

**Comment by Sshatzkin** [comment]
We haven't really talked about dynamic coloring/ color swapping as a feature for this game. It sounds like a pretty big UI change that the UI team would at least like to get our hands on/ have a quick discussion about before we push it to master - especially if it will involve edits to UI code.

That being said, if it really is a simple addition, it sounds like a very cool feature and would definitely make for an exciting demo.

**Comment by ecoble** [comment]
Closing this issue as it seems the additions mentioned here have already been implemented.
