### ISSUE TITLE
Credits command

### ISSUE THREAD

**Issue by Gestalt-R** [uchicago-cs/chiventure#337]
Right now, the player of the game has no way of seeing who made the engine. The credits command would output the list of authors.

**Comment by mberamendiconde** [comment]
Have progress where the credits input on the cli line prints "Credits here" to the window. need to see which credits the window should ACTUALLY display to resolve this issue

**Comment by mberamendiconde** [comment]
Closing statement: Pull request has been approved, and now the user can use the "credits" command in the command line to display previous classes of CMSC 22000 who have contributed to and worked on chiventure.

**Comment by ecoble** [comment]
Issue Score: ✔️++

Comments:
Great work on this backlog issue!
