### ISSUE TITLE
Write function for loading action conditions and effects into game state structs

### ISSUE THREAD

**Issue by Kate32815** [uchicago-cs/chiventure#338]
After loading items and actions into game state item structs, item pointers and their action struct pointers are created. 

A function needs to be written to perform a second iteration of the WDL file to load in action conditions and effects that include pointers to different items to check and modify based on the action.

The function will take in a parsed WDL file object, and a game_t pointer, and will return an int based on whether the conditions were loaded successfully. 

I created a new branch **load_actions_info** for this issue

**Comment by Kate32815** [comment]
The code for loading action conditions and effects from a WDL file into game state structs is written and is in the **load_actions_info** branch, in load_item.h and load_item.c. However, the code was not able to be tested as the Game State PR containing the action condition and effect structs made it into master on the last day of the project.

I'm closing this issue now, but to the people who will be working on this in the future: there is fairly well-documented code already written for loading action conditions and effects, so please use it/ refer to it as needed!

**Comment by lydiafilipe** [comment]
Issue Score: ✓+

Comments:
Great work! Nice documentation of this.
