### ISSUE TITLE
Update Help Text to include "Map" and "Switch"

### ISSUE THREAD

**Issue by ecoble** [uchicago-cs/chiventure#350]
Update the help text to let the user know "map" and "switch" are commands that are available to them, and include brief descriptions of what these functions do.

**Comment by ecoble** [comment]
UPDATE: I have updated the help text to include 'map' and 'switch' and a short description of what they do. While updating the help text, I have also included a list of all supported actions available in action management's action list. I have no given a description of each of these because they are pretty self explanatory.

**Comment by ecoble** [comment]
CLOSING STATEMENT: The help text now includes "map" and "switch", so the user knows these actions are available to them. There is also a list of all available actions from action management. In the future we could try to automatically generate this list of actions using action management's array, so we don't have to manually change them when new actions become available.

**Comment by lydiafilipe** [comment]
Issue Score: ✓+

Comments:
Great work!
