### ISSUE TITLE
Add load_sample command

### ISSUE THREAD

**Issue by ecoble** [uchicago-cs/chiventure#360]
This command will load the sample game that was created for testing purposes, this is a worst case scenario for if a real game can't be loaded for the demos. The command will be called "load_sample" and it will map to a function that calls create_sample_game and assigns this sample game to the chiventure context struct game

**Comment by a-matai** [comment]
Updates: 

- #365 hotfix fixed the game-state seg fault
- moved create_connection after add_room_to_game
- added game_free in chiventure.c
- commented out AM's assert that caused an exit

**Comment by ecoble** [comment]
UPDATE: Game state fixed an issue that was causing a segfault, and CLI fixed an issue with calling actions. There are now two sample games with two rooms each, they can be loaded with the commands "load_sample" and "load_sample_2"

**Comment by ecoble** [comment]
CLOSING STATEMENT: There are three sample games -
- 'load_sample' loads a simple sample game with two rooms
- 'load_sample_cp' loads another simple sample game with two rooms, but no actions are supported on items
- 'load_sample_gs' loads a more complex sample game with five rooms

All of these commands and preset games exist only for demo and testing purposes, since currently loading a real game does not work

**Comment by lydiafilipe** [comment]
Issue Score: ✓+

Comments:
Great work!
