### ISSUE TITLE
Refactor Game Action Tests

### ISSUE THREAD

**Issue by lindsey-hsi** [uchicago-cs/chiventure#362]
Refactor game_action tests into game_actions.c, game_conditions.c, and game_effects.c in order to submit smaller pull requests and make merging into master more efficient.

**Comment by lindsey-hsi** [comment]
The tests for this issue have been refactored! See above for the specific commit.

**Comment by lindsey-hsi** [comment]
The tests for this issue have been refactored! See above for the specific commit.

**Comment by lydiafilipe** [comment]
Issue Score: ✓

Comments:
Good work! The summary and closing were a bit vague though, it would have been good to summarize what was done in the commit and how they were refactored.
