### ISSUE TITLE
Refactoring AM testing modules for updated GS fucntions

### ISSUE THREAD

**Issue by SnowballAntrobus** [uchicago-cs/chiventure#366]
In PR #335 GS changed the parameters for their functions add_action_effect and add_action_condition. The change is that they now take an attribute type as a parameter. The goal of this issue is to refactor our testing suite with this in mind.

**Comment by SnowballAntrobus** [comment]
Additionally, commits will include the fixing of the fifth parameter when calling both functions in testing. Previously, this was implemented incorrectly with a poor understanding of how unions work in C.

**Comment by SnowballAntrobus** [comment]
Forgot to tag commit that refactored item_item. The key is 1874a16.

**Comment by MTUC08** [comment]
The updated files will go to master with PR #364

**Comment by SnowballAntrobus** [comment]
Closing Statement:
We refactored the entire testing suite to account for the new Game State functions. As of now all tests for conditions and effects are implemented, compile, and succeed. No future work beyond continuing to add more tests are new features come about.

**Comment by mpcsh** [comment]
Issue Score: ✓+

Comments:
Great work!
