### ISSUE TITLE
Fix: Formatting of Help Text

### ISSUE THREAD

**Issue by ecoble** [uchicago-cs/chiventure#373]
The help text no longer formats correctly, restore this to how it was.

**Comment by ecoble** [comment]
UPDATE: Fixed this issue, the previous changes needed to be outside of the while loop

**Comment by ecoble** [comment]
CLOSING STATEMENT: The help text now prints and is formatted correctly, this issue was being caused by a call to move the cursor being inside of the while loop that handles large text blocks. That call has now been moved outside of the loop.

**Comment by lydiafilipe** [comment]
Issue Score: ✓+

Comments:
Great work!
