### ISSUE TITLE
Design basis for action verification

### ISSUE THREAD

**Issue by efraimdahl** [uchicago-cs/chiventure#39]
In order to figure out whether an action is verified or not we must make sure of the following.
Assert that the action exists,
If the action has an object/NPC it is applied to: (in case of move -> direction) 
Assert that this object/NPC exists
If the object has an indirect object/NPC associated with it:
Assert that this object/NPC exists
Make sure that the prepositions match (once the list of actions has been established) 

The Actions should support having precise enough error messages that the user will know what was wrong about his input.
E.g we should be able to differentiate between actions that fail because the object was not found, or because the action was not recognized.

This Issue does not focus on actually implementing any of these functions, the goal is to familiarize ourselves with what will be happening, how these functions will interplay with the other teams and to set up a basic design that will in cooperate these aspects.

**Comment by ecoble** [comment]
Removed the last step of creating an action struct, this has been pulled into a different issue

**Comment by ecoble** [comment]
These validation functions will exist in a new module

**Comment by efraimdahl** [comment]
UPDATED:
We wrote a couple of dummy functions to serve the different types of actions handled by action management. We will implement them as soon as the structs action management uses have been (more or less) finalized.

**Comment by efraimdahl** [comment]
CLOSING NOTICE:
Outlined the action validation in a new module: validate.c/validate.h
In this module there are functions that will support the verification of the action -> lookup in hash table of supported actions with supported synonyms. 
In this module there are functions that will support the verification/lookup of objects/npc's given the current game struct. 
In this module there is a functions that will checks whether a preposition is correct.
There is a function similar to the object verification that is associated with validating the indirect object.

Given each of these 4 validation steps, there are four distinct error messages that will tell the user what part of their input was wrong -> These error messages can be found in the operations.c structure where they act like operations, (where the error message is simply a return value) in order to make integration into the UI easier.

**Comment by lydiafilipe** [comment]
Issue Score: ✓

Comments:
Nice work overall. There needs to be a bit more detail in your progress updates. You could add more details on the functions as you're writing them. If you're moving stuff, it's good to specify where to. You could specify what kind of actions are you looking at.
