### ISSUE TITLE
Design basis for creating action structs

### ISSUE THREAD

**Issue by efraimdahl** [uchicago-cs/chiventure#40]
Design functions that will take a list of tokens, and use the functions provided by action management to return a single action struct

**Comment by ecoble** [comment]
Created four dummy functions for the four types of actions specified by action management. Currently these functions return void, but once the structs from action management are finalized they will take a list of tokens and return the type of the action struct to be passed on to action management.

**Comment by ecoble** [comment]
Closing Statement: Four functions have been created that will be used as the basis for using action structs and action functions from action management's modules. The create_type_functions will use action management's interface to retrieve a struct, and then this struct will be passed on to a type_action_operation function that will again use action management's interface to alter the state of the game. 

Note: Four separate create_type_functions may prove to be unnecessary, if so they will condensed to one function

**Comment by lydiafilipe** [comment]
Issue Score: ✓

Comments:
Good work! You could have included more progress updates as you were writing the functions, and maybe explain better what each function is as you write them
