### ISSUE TITLE
Add autocomplete to CLI

### ISSUE THREAD

**Issue by efraimdahl** [uchicago-cs/chiventure#41]
Used readline documentation [here](http://www.manpagez.com/info/rlman/rlman-6.2/rlman_45.php#How-Completing-Works) to implement an auto-complete for user commands with the tab key.

Things to add for future:
Potentially add field to command struct to mark a command as "secret" so that autocomplete doesn't work for certain commands.
Need to decide whether you can autocomplete invalid commands. Currently not differentiated and all written commands supported. This partially depends on how game state holds their valid actions.

Task is considered done once it is implemented and a user can complete commands with the tab key.

**Comment by dbarer** [comment]
This issue will go on the backlog for now. It's currently implemented with a hardcoded array storing every possible command. Going to look more into how to use a trie data structure to make autocomplete more efficient. Will hopefully get back to it by the end of Spring 3 or beginning of spring 4.

**Comment by dbarer** [comment]
Closing Statement:
In this task I implemented a basic autocomplete for the readline CLI. 
It works but currently would need to have every single valid action we want to autocomplete in a char* array. This could become inefficient with more commands added, and I want to change it around to work with a trie data structure to make this process more efficient. This code has not been integrated with cli/dev at all and lives on the dbarer/autocomplete branch. I'm going to close this issue for now, and revisit it later in this sprint or at the beginning of the next one.

**Comment by lydiafilipe** [comment]
Issue Score: ✓

Comments:
Good work on your title, summary, and closing statements. However, you are not posting many progress updates. You mentioned implementing various things but it's also important to be making progress updates as you are doing that
