### ISSUE TITLE
Design end conditions based on item attributes

### ISSUE THREAD

**Issue by ericyc16** [uchicago-cs/chiventure#422]
Currently, a game will end when the player moves to a "final room." Issue #347 introduces a potential improvement, which would be to "create end conditions based on item attributes using game_action's condition structs." Work on the design for such a feature, determining details such as how this can be implemented and where in the code it should go.

**Comment by ericyc16** [comment]
Currently, the game struct in game-state/game.h includes the field "room_t *final_room".  This could be changed to an action_condition_list_t (as defined in game-state/item.h).  There are several action_condition functions in game-state/game_action, which I can probably use in my design.  

For whatever design I come up with to work, I need to communicate with WDL so that they can create a way to specify conditions that result in the game ending.

**Comment by ericyc16** [comment]
Elizabeth Coble suggested that I "don't completely remove the option of having a final room being the end condition of the game, or make sure that being in the final room can be part of the action condition list you are creating."  Of these options, I have decided that I will leave the "room_t *final_room" field in the game struct.  I will add a field "action_condition_list_t *end_conditions" to the game struct to represent the list of end conditions.  I will also implement three new functions: 

1. int add_end_condition_to_game(game_t *game, game_action_condition_t *end_condition)
2. bool end_conditions_met(game_t *game)
3. int delete_action_condition_llist(action_condition_list_t *head)

My design document, which will contain more details, will be found [here](https://github.com/uchicago-cs/chiventure/wiki/Action-Management---End-Conditions-Design).  I plan to have it complete before the night of Saturday, May 2.  After completion, I plan on asking others to review my design.

**Comment by ericyc16** [comment]
Finished the first draft of my [design document](https://github.com/uchicago-cs/chiventure/wiki/Action-Management---End-Conditions-Design) (same link as in the last comment). I've requested feedback from my senior developer and my team. Once I consider and (potentially) incorporate their feedback, I will evaluate what issues I need to add to the backlog to realize this design.

**Comment by ericyc16** [comment]
I have decided that no changes to my design are currently necessary, so I am closing this issue.

A brief summary of the design:
- A list of action conditions (added to the game struct) represents end conditions.
  - A game will end when all of the conditions in the list are met and when the final room is entered. 
  - If a final room is not specified, then the game ending is only dependent on all action conditions being met (and vice versa).
- Functions will be created to add, check, and delete end conditions as necessary

**Todo**:

- Implementation and unit tests for end conditions (this has been created into separate issue #472, which has been backlogged)

After implementation is complete, the next steps will be as follows:

- Integration of implementation into current chiventure code
- Developing a way for WDL/WDL++ to specify end conditions (I have briefly talked to @namanhd1nh about this, but will be providing the WDL team with more details shortly)
- Further fleshing out end conditions (for example, potentially creating and adding a way to allow only one condition of the many on a list to end a game, rather than forcing all conditions to be met as specified by this design)

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Awesome job! This issue is well-described and well-documented, with a great closing statement. This is an excellent example of what a good design issue might look like.
