### ISSUE TITLE
Write User Stories for Open World Feature

### ISSUE THREAD

**Issue by CCalderon01** [uchicago-cs/chiventure#423]
The user stories for the open-world will focus on what high-level implementation of the RPG feature will look like in gameplay. The stories will delineate exactly what users can expect and especially how the open world interacts with other features (mainly the Battle Systems and Player Stats).

**Comment by CCalderon01** [comment]
New progress:
I added a wiki page with my second draft of User Stories. This is a resource that can now be referred to by the Worldwide team as well as other RPG teams that we'll be collaborating with.

**Comment by borjasotomayor** [comment]
Could you provide a link to the wiki page? (in general, any time you produce something as part of an issue, make sure you link to it from the issue, regardless of whether it is intermediate work or the final result of the issue)

**Comment by CCalderon01** [comment]
I edited the User Stories wiki page to include more examples of our relationships with the different project features. I referred to Nicole Avila's notes after her informal meeting/chat with the other teams. For the moment, I just added Battle Systems and WDL to the wiki. After our team meeting on Saturday (when hopefully members of these other features will come too), I'll update a more comprehensive outline of our expectations of the interaction between our features. 
The link to the wiki: https://github.com/uchicago-cs/chiventure/wiki/Open-world:-User-Stories

**Comment by CCalderon01** [comment]
See the final update to the document on the wiki, titled "Open world: User Stories": https://github.com/uchicago-cs/chiventure/wiki/Open-world:-User-Stories

After our team meeting on Saturday, I made sure my user stories matched the expectations outlined in the design document and our conversations with other teams. I added a Graphics/Open World section at the very bottom. The rest of the other user stories reflected well the intentions of our team and our feature. Having completed this task, I think that this part of our design process clearly gives us tangible goals to reach as we write and develop the code.

**Comment by dwahme** [comment]
✔️+
Remember that Scrum board cards shold be converted to issues shortly after the Sprint meeting. Think of the Scrum board card as a rough outline of the issue, which you then need to flesh out with a more descriptive title and summary when converting it to an issue.
