### ISSUE TITLE
Research the Libsdl (graphics library) to use as an UI/UX Framework

### ISSUE THREAD

**Issue by damonhines** [uchicago-cs/chiventure#424]
Eventually, there will need to be a graphics library used for implementing a UI in Chiventure. We would like to find out if the SDL library will provide us with APIs that are helpful in our design for the UI. The research should clearly explain some of the prime features and APIs of the library, an example program using the library, and a rating (1 bad -5 excellent) of the library.

**Comment by damonhines** [comment]
Found very informative example on how to use SDL with examples https://www.geeksforgeeks.org/sdl-library-in-c-c-with-examples/

**Comment by damonhines** [comment]
Currently, I'm updating the wiki with basic facts and steps on how to download the SDL library. I even added a tutorial from a site that is easy to follow.

**Comment by damonhines** [comment]
Upon further reading, SDL appears to be used as a lower-level type of library which will allow you to access your keyboard, mouse, and other hard ware type of functions. So, In chiventure, if we wanted to move our character with the keyboard, SDL can aid in the low level aspects of that.

**Comment by damonhines** [comment]
Upon further research, SDL video APIs provides references for 2d rendering and lots of different options. So, this partially satisfies the first half of the issue. I will now try to run an SDL example on my computer.

**Comment by damonhines** [comment]
In the process of testing one of the files to create a window using the sdl library. If i am ab to compile it correctly, i will send the file i made. If not, i'll redirect you to the code and sources I do have. I attempted to compile the other day, but ran into some issues.

**Comment by damonhines** [comment]
Having compiler issues. However, SDL seems to be a good source for pixel based games etc. I'd rate it a 4 or 5 for this project. We'd just need to dig deeper into how we want our game to look, and then figure out what we need to do with SDL.
Example:
https://www.youtube.com/watch?v=23rD7xdd9ZE

**Comment by ecoble** [comment]
Issue Score: ✔️

Comments:
Great job, especially with your frequent updates! Some things for the next time, be sure your summary clearly states your goal (in this case creating a research doc), and you have a clear closing statement.
