### ISSUE TITLE
Design what RPG Stats should look like

### ISSUE THREAD

**Issue by carlosazpurua1004** [uchicago-cs/chiventure#425]
Create a design doc to specify how RPG Stats should work. That is, what Stats we should have, and how they interact with other things in the game.

**Comment by carlosazpurua1004** [comment]
Made a basic outline for what Stats should look like, but some things are up in the air. We've decided we need to go to OH to ask some questions about WDL, and how implementing Stats would work for a dev, and the RPG-battle team, (to see how feasible custom stats are), before proceeding further.

**Comment by sumedhsarwate** [comment]
After meeting with @ecoble and the rpg-battle and rpg-playerclass teams, we've come up with a preliminary and tentative idea of including a stats struct in the player struct in player.h and modifying the stats through a stats module, and rpg-battle and playerclass will inform us of the stats that they want to include. In their design, playerclass will have an interface that will provide information on how classes modify stats, which we will relay to the battle team. Going forward, we will need to talk with the WDL team to figure out how we can add a feature for the game author to create custom stats.

**Comment by carlosazpurua1004** [comment]
We finished our design doc and added it to the wiki. Our goals for the functionality of the RPG stats feature are specified there.

**Comment by carlosazpurua1004** [comment]
I realized we ended up producing something much closer to a requirements document, rather than a design document, so I changed this issue and updated the wiki page title to reflect that.

https://github.com/uchicago-cs/chiventure/wiki/RPG-Stats-Requirements-Doc-Draft-1

**Comment by ecoble** [comment]
Issue Score: ✔️++

Comments:
Great work! I especially like your thorough updates on your thought process and progress, as well as your post meeting updates.
