### ISSUE TITLE
Create user stories outlining battle system

### ISSUE THREAD

**Issue by Isaaq-Khader** [uchicago-cs/chiventure#427]
We should know what battle system we want to base our battle system on and give a concrete example of possible actions along with an example of a battle.

**Comment by Isaaq-Khader** [comment]
I created an example of what we envision a battle looking like. Using commands in the terminal, it displays what we expect to see during a battle.

**Comment by Isaaq-Khader** [comment]
We created a battle system based on Pokemon with an example battle using commands and wants we list in the document. We added wants that will contribute to our framework of the battle system.

**Comment by alex-sheen** [comment]
We finished our user stories outlining the battle system. The link to the wiki page is below:

https://github.com/uchicago-cs/chiventure/wiki/RPG-Battle-Systems-%7C-User-Stories

**Comment by dwahme** [comment]
✔️+
Remember that Scrum board cards shold be converted to issues shortly after the Sprint meeting. Think of the Scrum board card as a rough outline of the issue, which you then need to flesh out with a more descriptive title and summary when converting it to an issue.

While using Google Docs to sketch out some of the documentation, you should avoid posting links to those Google Docs from an issue, as it may cause confusion as to whether that document (or some future update to the wiki) is the most up-to-date version of that documentation. You should instead transfer the contents of the document to the wiki, and then link to the wiki when updating the issue.
