### ISSUE TITLE
Research incremental saving

### ISSUE THREAD

**Issue by ellynliu** [uchicago-cs/chiventure#43]
Look into how we could go about saving incrementally. This could eventually affect how we write .proto file and how we load/save

**Comment by schin99** [comment]
Will be continued into sprint 3

**Comment by jarvislam1999** [comment]
So I tried to research incremental saving but not much showed up, so I'm not sure where to head next. I have some questions to pose at the meeting next week though. I'm still quite confused about what incremental saving does.

The first approach is to save the initial game state, and then save every command line after that. Then every time we load, we need to run the commands up till the saving point.

The second approach is that we only save the rooms where the changes and actions take place, save that room and then embed it into the room arrays when loading.

These are the two approaches that I have thought of. Once we get better detail of what incremental save is at the meeting, we can actually research it more carefully. I feel like this should be a continued issue for sprint3, though I will set it back to sprint2 for now in case we want to express the issue differently for sprint3.

**Comment by mpcsh** [comment]
Issue Score: ✓-

Comments:
The summary didn't include a description of what incremental saving actually means. There were also no progress updates here.
