### ISSUE TITLE
Explore existing code relating to battle

### ISSUE THREAD

**Issue by Purrsephone** [uchicago-cs/chiventure#431]
We will read through existing code and think about how rpg-battle system code might integrate with it. Specifically, how the current code would support battle systems, and what changes would need to be made. We will document our findings on the wiki. Completing this issue, along with issue #432 will help us as we continue refining our design.

**Comment by celiaanderson** [comment]
Met with @Purrsephone to discuss our readings of the current chiventure documentation and code. Notes on how battle systems might interact with the current implementation is on the new wiki page: https://github.com/uchicago-cs/chiventure/wiki/Battle-Systems---Existing-Code-Review

**Comment by celiaanderson** [comment]
We have documented our findings on the wiki page about how a battle systems design can be adapted to the current chiventure implementation, with focus paid to each particular component of chiventure. This documentation may be added to later on, as more specific issues crop up or as designs change, but this preliminary documentation has been completed.

**Comment by dwahme** [comment]
✔️+
Remember that Scrum board cards shold be converted to issues shortly after the Sprint meeting. Think of the Scrum board card as a rough outline of the issue, which you then need to flesh out with a more descriptive title and summary when converting it to an issue.
