### ISSUE TITLE
Communicate with other teams about battle systems

### ISSUE THREAD

**Issue by Purrsephone** [uchicago-cs/chiventure#432]
Set up meetings with other teams to discuss dependencies and opportunities for collaboration. Talk about how battle systems interface with other modules. Document our findings in the wiki. We hope to have a basic understanding of dependencies so that our team, and other teams affected, can move forward with our designs.

**Comment by Purrsephone** [comment]
brainstormed possible dependencies within team H

**Comment by Purrsephone** [comment]
Made a list of our ideas, specifically ones that involved other teams, and shared it with the dev-rig channel.

**Comment by Purrsephone** [comment]
1 meeting with playerstats in the process of being scheduled

**Comment by Purrsephone** [comment]
Had a phone call with Nicole from rpg-openworld, shared ideas and planned to share communication with team playerstats this weekend

**Comment by Purrsephone** [comment]
@celiaanderson and I met with @carlosazpurua1004 and @simrenk to discuss the dependencies among player stats, player classes, and battle. Our meeting notes have been posted on a new wiki page called RPG Collaboration. 
https://github.com/uchicago-cs/chiventure/wiki/RPG-Collaboration

**Comment by celiaanderson** [comment]
Ways in which battle systems might interact with other RPG teams has been documented on the RPG collaboration wiki page. While further collaboration will continue, this week we identified some of the initial basic overlapping between our teams.

**Comment by dwahme** [comment]
✔️+
Good job! Here are a few things you may want to improve in future issues:

The title of an issue has to convey what the issue will be producing. In the future, try using simple titles with a "Verb-Object" structure that clearly states what you will be doing in the issue (e.g., “Design and implement a ‘circle’ module”, “Research libraries for drawing simple geometric shapes”, etc.) Specifically, a meeting(s) is more of a means to an end for an task than the end goal itself.

Remember that Scrum board cards shold be converted to issues shortly after the Sprint meeting. Think of the Scrum board card as a rough outline of the issue, which you then need to flesh out with a more descriptive title and summary when converting it to an issue.
