### ISSUE TITLE
Create a model dialog tree and mock-up dialog program

### ISSUE THREAD

**Issue by ketchupkeith** [uchicago-cs/chiventure#433]
We plan to write a dummy program whose code is simplistic but creates output that looks and feels like a real dialog segment from an adventure game.  We think this will help conceptualize ways dialog can work in a text adventure game, and how to decompose the building blocks to generalize it for game makers.

We'll produce this dialog showcase program, along with a corresponding dialog tree that shows the possible interactions and routes through the scenes.

**Comment by ketchupkeith** [comment]
This is the flowchart I'm planning to work with for the dummy program! I have a few of the scenarios written out in Word to mock what the terminal might look like; I attached one that goes through the important nexus points so you can get the gist of how travelling the chart might work.  Right now I'm looking at it like we have purple scenes of NPC dialog where choices are given, the red "exit dialog" type of routes (leading to a fight or other dialog-end scenario), and the player's simple white choices just leading between them.  I gave the player choices small flavor quips to smooth the transition between the NPC's scenes, since I wanted those to be general enough to get led to from different paths

![NPCShowcase dTree FINAL](https://user-images.githubusercontent.com/59927704/80776075-027db680-8b27-11ea-86e6-262fbf5bccff.png)
![DialogTree flow example](https://user-images.githubusercontent.com/59927704/80776076-03164d00-8b27-11ea-9d0b-e6b1d1840bcc.PNG)

**Comment by ketchupkeith** [comment]
The showcase program is done!  In lieu of an easier way of sharing this, I've uploaded the files to a repository you can access [here](https://github.com/ketchupkeith/chiventure-dialog-showcase/tree/master). It should be simple enough to download the files and compile/run them on your own computer - if anything goes wrong or if you have any feedback or questions, feel free to comment!  I'm leaving this task "in progress" for now, to give a chance for feedback and improvements, but this update should fulfill the basic requirements of this task.

**Comment by ketchupkeith** [comment]
I've started a pull request to add our program's files to chiventure's src/npc/sandbox directory; once it's approved you should be able to find the files officially housed there!

**Comment by ecoble** [comment]
Issue Score: ✔️++

Comments:
Great work! Your updates are really thorough and I like that you included screenshots of your diagrams. One small thing, in the future if an issue is going to result in a pull request, you should wait until your pull request is merged to close the issue.
