### ISSUE TITLE
Create an informal requirements document outlining what the class system should look like to the player and game author.

### ISSUE THREAD

**Issue by PaulTreitel** [uchicago-cs/chiventure#434]
Assignees: Eric, Paul
team: rpg-playerclass

This should consist of a set of user stories showing how users will interact with the class system and how the class system will alter the ways the user interacts with other parts of the game. We will likely also add a game author story to show how a game developer will use/implement the class system.

**Comment by ericbre21** [comment]
### Progress Update:

Worked with the entire team to create a user stories / requirements high level document containing our goals for the playerclass system.

[This is the document.](https://docs.google.com/document/d/1GuZbQ7r99FTwGkbChTV52_wu2IXnwmMFZFcIbU-HksE/edit)

**Todo:** 
Finalize document and move it to the Wiki.

**Comment by PaulTreitel** [comment]
I've finalized the user stories document and moved it onto [its own wiki page](https://github.com/uchicago-cs/chiventure/wiki/Player-Class:-Requirements--&-User-Stories).

**Comment by dwahme** [comment]
Issue Score: ✔️+

Comments:
Good job! Here are a few things you may want to improve in future issues:

Remember that Scrum board cards should be converted to issues shortly after the Sprint meeting. Think of the Scrum board card as a rough outline of the issue, which you then need to flesh out with a more descriptive title and summary when converting it to an issue.
