### ISSUE TITLE
Write a design doc to explain the overall structure of the playerclass code

### ISSUE THREAD

**Issue by ethanwtai** [uchicago-cs/chiventure#435]
Writing a google doc to document how our playerclass structure will look like. This is an outline of the future modules, structs, and important functions we want our code to be organized into.

**Comment by ethanwtai** [comment]
Created a basic outline for [the design document ](https://docs.google.com/document/d/16EWQNab1ngn5qyAmOXhk20I4lQ1VNl4B4TSCWNLWciA/edit?usp=sharing)to serve as a launchpoint for a larger team discussion about the overall design of the code.

**Comment by ethanwtai** [comment]
@simrenk , @PaulTreitel , and I talked about how to integrate player stats into our design. We came up  with the idea of storing a local copy of the stats struct to hold the base stats for different classes. While we've fleshed out most of the design, I'm holding off on closing this issue in case anyone has extra feedback.

**Comment by ethanwtai** [comment]
From @NuclearWaffles' comment about using the attribute struct to make it easier for custom-actions to work with, I have added an attribute array to describe any attributes unique/related to a class as well as functions to go along with it.

**Comment by ethanwtai** [comment]
I have updated the chiventure wiki with [our initial design plan. ](https://github.com/uchicago-cs/chiventure/wiki/Player-Class:-Design-Plan)

**Comment by ethanwtai** [comment]
As there haven't been any major changes to our initial design, I am closing the issue.

**Comment by dwahme** [comment]
✔️+
Remember that Scrum board cards shold be converted to issues shortly after the Sprint meeting. Think of the Scrum board card as a rough outline of the issue, which you then need to flesh out with a more descriptive title and summary when converting it to an issue.
