### ISSUE TITLE
Familiarize with source code to consider possible methods to incorporate custom scripts and examine potential aspects to support customization for

### ISSUE THREAD

**Issue by hugo-chan** [uchicago-cs/chiventure#438]
Without knowledge of what the current structure of Chiventure is, it will be hard, if not impossible, for my team and I to brainstorm the ways we can incorporate custom scripts into the game engine. Therefore, it is important to have a fundamental understanding of the inner workings of the game engine. This will involve thoroughly reading the source code.

Doing this will enable us to brainstorm possible ways we can incorporate custom scripts as well as the possible aspects of the game engine we can support customization for. 

A document will be used to record the progress of this task. I will know this task is done when a list of potential ways to incorporate custom scripts + potential aspects to customize is fleshed out.

team: custom-scripts

**Comment by hugo-chan** [comment]
Task is done: I have recorded my notes on the current structure of Chiventure and the possible ways custom scripts can be incorporated here: https://drive.google.com/file/d/1DvQ8v3denTYcC7vO9BZnHXmk923M8IFu/view?usp=sharing

I will discuss my findings with my teammates and update when I receive feedback.

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Great job! The wiki page is really thorough and detailed, keep up the good work.
