### ISSUE TITLE
Plan integration of RPG-playerclass requirements & design into existing and planned Chiventnure 

### ISSUE THREAD

**Issue by simrenk** [uchicago-cs/chiventure#439]
Name: Simren
tean: rpg-playerclass

We would like to understand the existing Chiventure code so we can modify our design + reqs to be not only feasible but also, efficient. After understanding this better, we would also like to communicate with other teams so we can gain insight on aligning our design/requirements with theirs.

**Comment by simrenk** [comment]
5/1 update: scheduled team meetings with battlesystems (@Purrsephone @celiaanderson) and playerstat (@carlosazpurua1004)
5/2 update: team meeting with rpg-playerstat and rpg-battlesystems. better understanding of dependencies (playerclass tells playerstat how classes modify their stats --> passed to battlesystems). Created and posted meeting notes under RPG Collaboration wiki page)

**Comment by simrenk** [comment]
**5/3 update:** Met with @noahklowden from WDL. Will need to provide them with how we want possible actions to vary based on class. 

Posted notes on Chiventure Dependencies and Future dependencies on the wiki: https://github.com/uchicago-cs/chiventure/wiki/Player-Class:-Dependencies

**Comment by dwahme** [comment]
✔️+
Remember that Scrum board cards shold be converted to issues shortly after the Sprint meeting. Think of the Scrum board card as a rough outline of the issue, which you then need to flesh out with a more descriptive title and summary when converting it to an issue.
