### ISSUE TITLE
Serializing

### ISSUE THREAD

**Issue by ellynliu** [uchicago-cs/chiventure#44]
To save the game, we will use a similar process as was used in sprint 1, utilizing protocol buffers, the .proto file written in issue #42, and the structs provided by game state. Helper functions may be necessary, as there are many instances of a room, for example. A sample game state will need to be created and used to test the functions. The serialized game state produced here will be used to deserialize.

**Comment by schin99** [comment]
We all ended up working on this task together as it was a good way for all of us to understand how protobuf works and was a very code heavy task.

**Comment by ellynliu** [comment]
Update: we talked to game state and they will provide a function so that we can iterate through their hash tables so we can save/serialize and pack as an array. This will expedite our process, as protobuf only supports integers, strings, and arrays. Earlier, we ran into problems as we could not malloc or use pointers with protobuf, so saving a hash table would have been quite difficult.

**Comment by ellynliu** [comment]
Using protobuf and the .proto file made earlier, we finished building a prototype of serializing a game state using dummy structs that reflected game state's structs. Then we serialized a dummy game implementation. After game state structs have been pushed to master, we will be able to serialize the official game state structs.

**Comment by mpcsh** [comment]
Issue Score: ✓

Comments:
The title should have been more specific. At the very least, serializing *what*? There were no progress updates before Sheryl's, and that one didn't include any details of what work had been done.
