### ISSUE TITLE
Understand how the current wdl code is integrated into the rest of chiventure and create a write up summarizing the learned information on the wiki

### ISSUE THREAD

**Issue by noahklowden** [uchicago-cs/chiventure#440]
Part of Chiventure's fundamental structure is the World Description Language system used to write and store game files for users of Chiventure. Currently, Chiventure uses a YAML file to store this information. Due to the complex nature of converting a YAML file to objects in C, the WDL system requires a special set of parsing functions to be loaded.

The goal of this task is to create a detailed description of how the WDL system is integrated into the rest of the Chiventure code so that other team members can easily learn how the system works.

**Comment by noahklowden** [comment]
Wrote an explanation of the basics of the WDL format and how the WDL files in the wiki:
https://github.com/uchicago-cs/chiventure/wiki/Current-Integration-of-the-WDL-System-in-Chiventure

Next: Plan to add more information on the validation functions.

**Comment by noahklowden** [comment]
Added a summary of the uses of the print and type-check functions in validate.c to the wiki page.

**Comment by noahklowden** [comment]
Updated the explanation of the WDL format to include examples of a game object, room object, and item object.

**Comment by noahklowden** [comment]
I wrote [an explanation](https://github.com/uchicago-cs/chiventure/wiki/Current-Integration-of-the-WDL-System-in-Chiventure) of how the WDL system is integrated into the rest of Chiventure's code. The basic takeaways were:

The WDL system is build around a YAML file stored as <name>.wdl. Chiventure games are loaded from this file using a parser system to convert to game objects.

WDL files specify the game object, room objects, and item objects in the game. These are stored in a game struct for use when running the game.

**Comment by MaxineK36** [comment]
Issue Score: ✔️+

Comments:
Good work!
A few things to work on in the next few sprints: 
1. Remember that Scrum board cards should be converted to issues shortly after the Sprint meeting. Think of the Scrum board card as a rough outline of the issue, which you then need to flesh out with a more descriptive title and summary when converting it to an issue.
