### ISSUE TITLE
Survey what features WDL++ should have, decide if and how JSON should fit these requirements

### ISSUE THREAD

**Issue by namanhd1nh** [uchicago-cs/chiventure#441]
The current WDL is based on YAML, originally chosen for its human-readability. However, the focus is now on WDL as an easily computer-readable format, not to be edited by human authors. Therefore, WDL++ is proposed to be based on JSON for its ease of parsing and thus flexibility to add support for new engine features in the long run. 

The task is to evaluate (using test games and existing WDL feature requests in the backlog) and write up a design document detailing what engine features this JSON-based format should support as of now, and consider some JSON representations of existing WDL data.

**Comment by namanhd1nh** [comment]
I've written up a more [detailed wiki page](https://github.com/uchicago-cs/chiventure/wiki/What-WDL---will-look-like) of my takeaways, but the gist is

- Much of the existing YAML-based WDL can be trivially converted over to JSON WDL++. Some modifications need to be made for object definitions to support custom actions.
- The action definitions themselves require an overhaul into "action sequences" made of atomic action blocks. This will also be the interface through which custom scripts are called.
- A tentative representation of NPC dialog trees using line IDs and "next line ID" arrays seems to fit the bill.

For the last two features, we will still require communication with the features' respective teams before their spec is finalized in any way.

**Comment by namanhd1nh** [comment]
After discussing with @ericyc16 from Action Management, I've decided to also expand the tentative WDL++ spec with a section dedicated to "global conditionals". These will add support for global game conditions that trigger global game events (namely, winning or losing the game, but more events can be supported). This is in addition to the "local conditionals" that are part of the custom action sequences which are checked only on interactions with specific objects. I will update the wiki page with these plans shortly.

**Comment by namanhd1nh** [comment]
After feedback from @blakemoss who has tried writing games in old WDL, I've also added  to the wiki page our plans to pay attention to documentation and specification conflicts when transitioning to the new WDL++.

**Comment by namanhd1nh** [comment]
At this point, the design documentation for transitioning to WDL++ (the wiki page) is mostly complete (at least, relative to the initial goals set at the beginning of the sprint) and well-communicated with the most closely related teams (Custom Actions, Action Management, and NPCs). Moving forward, we'll be starting on official detailed documentation as well as more implementation design based on these transition plans, and the rest of the teams that require WDL++ integration should be able to just drop-in easily into our current tentative spec. These can be separate issues to work on for the next sprints, so this issue can be closed.

**Comment by MaxineK36** [comment]
Issue Score: ✔️+

Comments:
Good work! This issue does a particularly good job providing tangible updates after meetings.
One thing to work on in the next few sprints: 
Remember that Scrum board cards should be converted to issues shortly after the Sprint meeting. Think of the Scrum board card as a rough outline of the issue, which you then need to flesh out with a more descriptive title and summary when converting it to an issue.
