### ISSUE TITLE
Create a design document outlining how to implement NPC functionality

### ISSUE THREAD

**Issue by lilyehsani** [uchicago-cs/chiventure#442]
We plan to thoroughly analyze the current source code for Chiventure, and to come up with a way to best integrate NPC functionality into the current game struct. Some options that have been discussed are treating NPCs as objects, or creating a new entity specific to NPCs.

**Comment by lilyehsani** [comment]
I have created a Wiki page to encapsulate all of NPC design: https://github.com/uchicago-cs/chiventure/wiki/NPC-Design-and-Planning

**Comment by SadracUchicago** [comment]
[Design Doc.pdf](https://github.com/uchicago-cs/chiventure/files/4576969/Design.Doc.pdf)

The following design document details the implementation of the NPC feature within the existing framework and also explains the creation of a new module (and new data structures).

**Comment by lilyehsani** [comment]
The Design Document has been completed and uploaded to the Wiki. Additionally, the Wiki contains much of its contents in a Wiki format. In it, we outline the existing interfaces to be worked with, new modules to be implemented, and other teams to collaborate with. I am closing this issue, and I encourage anyone with updates to the design to add their thoughts onto the Wiki page, though the issue can be reopened if need be.

**Comment by ecoble** [comment]
Issue Score: ✔️+

Comments:
Great work on this design! Some things for the next time, be sure to convert your cards to issues at the beginning of the sprint, and make sure your goal (creating a design document) is clearly stated in the summary, not just the title (in fact the goal does not necessarily need to be in the title).
