### ISSUE TITLE
Create a design document outlining the structure of an NPC and future enhancements

### ISSUE THREAD

**Issue by lilyehsani** [uchicago-cs/chiventure#443]
We plan to create a design document outlining the features we hope to implement with NPCs. We will also design potential future enhancements (that while we may not get to implement, could be implemented by a future class).

**Comment by lilyehsani** [comment]
@alexjsun created a Google doc for design ideas here: https://docs.google.com/document/d/1g5NAXelgCi4JqmNQ2aAC_t-eAh8PnLgcUzSfG42Qmo4/edit. We are planning to migrate better-formatted documentation to a Wiki page.

**Comment by lilyehsani** [comment]
I have created a Wiki page to encapsulate all of NPC design: https://github.com/uchicago-cs/chiventure/wiki/NPC-Design-and-Planning

**Comment by alexjsun** [comment]
I updated the Google doc to include some more future design ideas, such as classes of hostile NPCs, the possibility of turning a friendly NPC into a hostile, and dynamics of merchant-type NPCs: https://docs.google.com/document/d/1g5NAXelgCi4JqmNQ2aAC_t-eAh8PnLgcUzSfG42Qmo4/edit?usp=sharing

**Comment by alexjsun** [comment]
The design document has been completed and its contents added to the NPC Wiki: [https://github.com/uchicago-cs/chiventure/wiki/NPC-Design-and-Planning](url). In the document, we outlined the structure of a new NPC module, possible dialogue tree modules, and possible future features. I'm closing this issue, but it can be reopened if we decide to use different structures.

**Comment by ecoble** [comment]
Issue Score: ✔️+

Comments:
Great work, especially with your updates and thinking of future features! Some things for the next time, be sure to convert your cards to issues at the beginning of the sprint, and try to keep all your docs on the wiki.
