### ISSUE TITLE
Write up on the feasibility of using Json-c and Libzip

### ISSUE THREAD

**Issue by dtbukowski** [uchicago-cs/chiventure#444]
Look into (https://github.com/json-c/json-c) and libzip (https://libzip.org/) and seeing if they make sense to use with the directory structure.

I will first look into the directory structure and then look into the features of json and libzip. Then I will write up reasons to use both that compare the pros and cons of using either json and libzip.

**Comment by dtbukowski** [comment]
After reading through the code in the wdl repository, I figured out that YAML is used in parser.c in libobj so libobj/parser.c will have to be changed along with the team that makes YAML documents. I've also realized that wdl passes along a doc object that it got from the parser.  

However, Libzip is a way to create zip archives, which contain multiple files for easy transportation. However, I don't see a use for this with WDL, as the doc objects that WDL passes in its various load files are contained in a single doc object and the file that WDL uses to look up to parse is in a single file that WDL uses the directory of the file in parse.

I've looked at:
https://www.json2yaml.com/yaml-vs-json
https://libzip.org/documentation/
https://github.com/json-c/json-c/blob/master/README.md
And various files within libobj and wdl

and my answer to using Json-c and Libzip will change as I improve my understanding of libobj, wdl, YAML, Json-C, Libzip and it will also change when I look into the interaction of wdl with different teams as I haven't done that yet.

**Comment by dtbukowski** [comment]
@borjasotomayor @MaxineK36 Maybe I can have some guidance on where in chiventure to look for a possible place to implement using libzip?

**Comment by dtbukowski** [comment]
Wrote up a design document on feasibility of Json-c and an alternative, cJSON: https://github.com/uchicago-cs/chiventure/wiki/WDL:-Comparing-options-for-parsers-for-JSON-files

**Comment by MaxineK36** [comment]
I'd recommend continuing to look in-depth at the existing WDL code and how it plugs into the rest of chiventure. The idea with libzip was that instead of specifying a game with as single YAML-based file, games could be specified according to a directory structure (so you could have a separate directory for graphic, one for sound, etc) and JSON files. Once this was all written out, it would be zipped into a single file that could then be distributed.

**Comment by dtbukowski** [comment]
Make the Libzip as a Spring 2 Task. Closing issue and marking as done as I wrote up a design document on Json-c

**Comment by dtbukowski** [comment]
Make changes to Json-c design doc

**Comment by MaxineK36** [comment]
Issue Score: ✔️+

Comments:
Good work! 
A few things to work on in the next few sprints: 
1. Remember that Scrum board cards should be converted to issues shortly after the Sprint meeting. Think of the Scrum board card as a rough outline of the issue, which you then need to flesh out with a more descriptive title and summary when converting it to an issue.
