### ISSUE TITLE
Create a test game in the current WDL

### ISSUE THREAD

**Issue by blakemoss** [uchicago-cs/chiventure#445]
In order to better understand the features and limitations of the current WDL, we need to go through the motions of creating a game file as the user would when using chiventure. This essentially equates to the generation of User Stories which will improve our understanding of what features we might be interested in implementing in WDL++.

**Comment by blakemoss** [comment]
While writing the test game, I'm running into some possibly conflicting information within the documentation for the WDL (specifically located at [wdl.md](https://github.com/uchicago-cs/chiventure/blob/master/docs/wdl.md) and [actions.md](https://github.com/uchicago-cs/chiventure/blob/master/docs/actions.md)). It seems as though there might be some updated functionality which has not been reflected in one or both of the documents. wdl.md specifies the following syntax for actions:

actions:  
    \- action: "ACTION NAME HERE"

while actions.md specifies a slightly different syntax:

actions:
    \- ACTION NAME HERE:

I'm currently unsure which is correct (or if both of them function the same within WDL, which is also not specified). I'll have to investigate this further- in any case, some documentation will need to be updated to reflect the correct syntax, and in general the documentation could probably be improved for clarity and more explanation of the "conditions" and "set" features of actions, specifically, as these are more complex.  

Similarly, the existing test game [distaff.wdl](https://github.com/uchicago-cs/chiventure/blob/master/games/distaff.wdl) hints at a few features:
- an "inventory" attribute for the end-game requirement (essentially, ensuring a player must have a certain item in their inventory to end the game)
- a "through" attribute for connections which specify the object through which a room must be entered (for example, a door or trapdoor). 

These features are commented out, and thus might be "wishlist" features that need to be implemented. I will check for their existence within the code and determine if this is the case.

**Comment by blakemoss** [comment]
I've finished writing the test game, which now runs in chiventure but does not function as expected, likely in part due to the aforementioned syntax and feature documentation confusion- despite this buggy functionality, I feel that my task has concluded as I have gained a concrete understanding of the functionality provided to users in writing chiventure games, and have a much stronger sense of what features might be useful going forward. I also discovered spotty and conflicting documentation for the current WDL, such as the aforementioned conflicting action syntax & missing features. These problems have been conveyed to @namanhd1nh who will either update his [wiki entry ](https://github.com/uchicago-cs/chiventure/wiki/What-WDL---will-look-like) on improvements for WDL++, or include them in our upcoming design document to be produced in the coming sprint.

The test game is attached- please advise on if I should attempt a pull request, given that aspects of the game do not function despite it running & being winnable in chiventure.

[test_game.txt](https://github.com/uchicago-cs/chiventure/files/4584677/test_game.txt)

**Comment by MaxineK36** [comment]
Issue Score: ✔️+

Comments:
Good work! Your updates are very well fleshed out, which makes it very easy for someone looking at this issue for the first time to catch themselves up.
One thing to work on in the next few sprints: 
Remember that Scrum board cards should be converted to issues shortly after the Sprint meeting. Think of the Scrum board card as a rough outline of the issue, which you then need to flesh out with a more descriptive title and summary when converting it to an issue.
