### ISSUE TITLE
Create a research document on how NPCs dialog trees work in other games and how these strategies can be used in Chiventure 

### ISSUE THREAD

**Issue by vallarymuhalia** [uchicago-cs/chiventure#446]
We are researching how NPCs and dialog trees work in other games and writing a document about the strategies used. We are also evaluating the effectiveness of such strategies and how they can be incorporated into Chiventure NPCs.

**Comment by vallarymuhalia** [comment]
I have found out about a strategy called branching dialog in NPCS. This strategy is used in games like Fallout 3 and 4.
**Branching Dialog**
Game dialogue becomes more interactive when conversations can take different paths. The player reads dialogue and chooses their response from a limited set of choices available to them. Conversation typically moves forward such that the player cannot go back to previous topics or responses.
In games where branching dialogue is the primary gameplay focus, the player's choices often affect the NPCs' attitudes toward the player one way or another, with the player attempting to guess the "best" response in order to maximize NPC disposition.
One common technique employed to give the player a greater illusion of freedom is to have multiple responses lead to the same path. This is usually done as an attempt to limit the quantity of dialogue that must be produced for the game. Therefore, branching dialogue usually curves back in on itself such that while an individual choice may immediately produce a unique response, the rest of the conversation is typically not unique to that choice.
This feature could be an effective tool in chiventure npcs, in which case we will develop dialog trees with more options instead of a directed graph with one option. 
For example, when a player enters a room, the NPC can ask:
NPC : Hi I am (). Welcome to the (room). What would you like to do?
1.	Look around
2.	Take an item
3.	Move to next room

Once the player makes a choice, the dialog tree branch advances. For instance, if the player selects option one, the next scene could be:

NPC : There is a lot to see in this room. There is a table, a bookshelf, a wide window and a television set. What do you wish to do?
1.	Switch on the TV
2.	Take a book from the shelf
3.	Open the window
This dialog can then be built until the player leaves the room or has done everything possible in that room.

**Comment by vallarymuhalia** [comment]
I have attached a sample of a multi-branch dialog tree that also limits quantity of dialog to be produced because multiple branches still lead to the same path. 
[Branching Dialog.docx](https://github.com/uchicago-cs/chiventure/files/4568530/Branching.Dialog.docx)

**Comment by ecoble** [comment]
Issue Score: ✔️

Comments:
Good job, especially with your thorough updates! Some things for the next time, be sure to convert your cards to issues at the beginning of the sprint, and make sure you have a clear closing statement. Also, any documents you create should be on the wiki and make sure to link to that instead of uploading the document directly.
