### ISSUE TITLE
Deserializing

### ISSUE THREAD

**Issue by ellynliu** [uchicago-cs/chiventure#45]
Take the serialized file and load back into game state.
More elaboration coming

**Comment by chrisfernandes18** [comment]
We took the file created from save.c function, imported it into the load function, deserialized it, and put all the fields back into the dummy structs implementation. Then we printed out all the fields to ensure the fields were all correctly loaded. Further, we added documentation for the load.c file as well as the logic we used to unpack the files throughout the load.c file.

**Comment by mpcsh** [comment]
Issue Score: ✓

Comments:
