### ISSUE TITLE
Design actions requiring an item in inventory

### ISSUE THREAD

**Issue by Dumplingz** [uchicago-cs/chiventure#452]
A possible action can have a prerequisite before it is being able to be performed (for example, only when holding a key can a chest be opened). We need to design a way to implement #236, so an action can scan through the player's inventory, and be performed only when the target item exists in it.

**Comment by Dumplingz** [comment]
Finished a design document detailing my plans for implementation [here](https://github.com/uchicago-cs/chiventure/wiki/Action-Management-Inventory-Item-Prerequisites). Since my work will likely build on top of my group members in action-management, I plan to meet with them to coordinate.

**Comment by Dumplingz** [comment]
After adding a a few more functions in the game_action module and about whether adding new conditions will affect my teammates' projects, I believe I have enough written to begin an experimental implementation.

**Comment by MaxineK36** [comment]
Issue Score: ✔️+

Comments:
Good work! This issue does a particularly good job referencing a previous issue without fully relying on it for the summary/updates. 
One thing to work on in the next few sprints: 
Remember that Scrum board cards should be converted to issues shortly after the Sprint meeting. Think of the Scrum board card as a rough outline of the issue, which you then need to flesh out with a more descriptive title and summary when converting it to an issue.
