### ISSUE TITLE
Create design layout documentation detailing what UI will look like with graphics 

### ISSUE THREAD

**Issue by xmvalencia** [uchicago-cs/chiventure#454]
Name: Abby/Xavier
team: graphics

**Comment by aherman33** [comment]
_A document of the following information can be found as a page on the wiki, titled "Graphical User Interface: Design Plan":_

Design ideas for a "current room" graphical user interface, a battle graphical user interface, and some graphics that can be added to enhance the "current room" interface, including a map of the "world," and a space for player stats, such as HP.

**Comment by xmvalencia** [comment]
_The document, found on the wiki, titled "Graphical User Interface: Design Plan":_

Has been updated and formatted to contain our ideas for UI layouts and new features. We will update soon with the potential interactions with other components as well

**Comment by xmvalencia** [comment]
_Regarding the original issue description:_

We've decided to split the original issue into two separate issues as it seems they would be addressing different issues and requiring different documentation. The original task separated is the "document potential interactions with other components/modules"

**Comment by xmvalencia** [comment]
_Regarding the overall status of this issue_

We have finished and renamed the wiki entry '[Graphics: Design Plan](https://github.com/uchicago-cs/chiventure/wiki/Graphics:-Design-Plan)'. This task was completed on 5/3/20

**Comment by ecoble** [comment]
Issue Score: ✔️

Comments:
Good job! Some things for the next time, be sure to convert your cards to issues at the beginning of the sprint, and your summary should describe the issue, your goal, and what you think you'll be working on.
