### ISSUE TITLE
Research an additional graphics library (Raylib) for both lower level and higher level functionality

### ISSUE THREAD

**Issue by ambikalv** [uchicago-cs/chiventure#457]
We would like to find out if the RayLib library will provide us with APIs that are helpful in our design for the UI. The research should clearly explain some of the prime features and APIs of the library, an example program using the library, and a rating (1 bad -5 excellent) of the library. Currently Chiventure is a text based game, and Raylib, compatible with C,  provides functionality for custom fonts, mouse tracking, audio effects, and other 2-d models which can be added.

**Comment by ambikalv** [comment]
Code for sample games as well as code for individual modules such as shape or color etc.
Support for audio effects
Support for backgrounds and environments
Support for models and shapes which are not included and/or commonly used

**Comment by seanrryan** [comment]
The raylib website has many worked examples and modules that show some of its capabilities. It seems like lower-level functionality like cursors, mouse/keyboard tracking, and possibly a two-dimensional camera environment could be implemented into chiventure. Features like 3D environments and VR support may be outside the scope of a text-adventure engine, but it is good to know that the library has a number of higher-level capabilities. That is to say, it seems that raylib has the features and longevity to survive many development cycles if we choose to use it.

**Comment by seanrryan** [comment]
raylib supports text input, custom fonts, and other text-based visual features that would be useful for displaying information and providing an interface for the player. For example, custom text could be displayed when entering a room or initiating an encounter, and a text input box could be used to command the player while simultaneously displaying relevant graphics/images.

**Comment by ambikalv** [comment]
added to wiki https://github.com/uchicago-cs/chiventure/wiki/Graphics-Raylib

**Comment by seanrryan** [comment]
Updated the wiki just now.
After playing around with some of the example programs I believe raylib is a viable option for moving forward with graphics. Being a native C library with plenty of foundational "building block" type features I think it would suit the game engine well. Taking some time to program and experiment would give us a better idea of what it might look like as part of chiventure, especially since we are starting to get some specific ideas of what we want to implement. I'd rate this library a strong 4 to a light 5.

**Comment by ambikalv** [comment]
A pro and con list:
Pro: 

- Native C Library
- Comprehensive cheatsheet which would make it easy to search for/ implement any functions
https://www.raylib.com/cheatsheet/cheatsheet.html
- Relatively easy to use and get started with (see wiki for installation and use instructions)

Cons
- 1) would have to see if we run into any problems while working with it/integrating it
- 2) Seems to be more modules/ focus for 3D features, models and backgrounds but that does not mean there is not a wide variety of functions and structs related to 2D objects and text

**Comment by ambikalv** [comment]
Here is a link to a series which provides a comprehensive step through about how to get started with Raylib

https://www.youtube.com/watch?v=JE7F7DLEjbo

**Comment by seanrryan** [comment]
Closing statement:
@ambikalv and I think raylib should be considered as an option going forward for future graphics implementation. So far, the benefits (features, compatibility with C, and extensive resources/documentation) outweigh any disadvantages that we see at the moment. To compare the viability of raylib to that of other graphics libraries, such as LibSDL, the libraries should be experimented with which may include collaboration with RPG, battle system, and/or CLI groups as well as further research within the graphics team.

**Comment by ecoble** [comment]
Issue Score: ✔️+

Comments:
Great work, especially with your frequent updates on discoveries! Some things for the next time, be sure to convert your cards to issues at the beginning of the sprint, and make sure your summary has a clear goal (in this case, writing a research document).
