### ISSUE TITLE
Plan interactions with other components/modules

### ISSUE THREAD

**Issue by xmvalencia** [uchicago-cs/chiventure#458]
Create and author a document will begin to plan interactions with other modules for proposed graphics

**Comment by xmvalencia** [comment]
A document of the following information can be found as a page on the wiki, titled "Graphics: module interactions":

This document is intended to aid in the implementation of graphics and the implementation of proposed functionality that can be found in document [Graphics: Design Plan](https://github.com/uchicago-cs/chiventure/wiki/Graphics:-Design-Plan)

**Comment by xmvalencia** [comment]
_Regarding the status of this issue:_

The document has been finished and is published on the wiki as [Graphics: Module Interactions](https://github.com/uchicago-cs/chiventure/wiki/Graphics:-Module-Interactions). The document will need updating as the modules listed in the interactions begin to change but this has been updated for the current sprint. The task was completed on 5/3/2020.

**Comment by ecoble** [comment]
Issue Score: ✔️

Comments:
Great work, especially with your closing statement! Some things for the next time, be sure to convert your cards to issues at the beginning of the sprint. Also, your title should be a bit more specific so it is clear it is more specific to your team, and your summary should be more fleshed out.
