### ISSUE TITLE
Module Creation (Map, Inventory, Logo Display)

### ISSUE THREAD

**Issue by Sshatzkin** [uchicago-cs/chiventure#46]
We have functioning map generation code and will be converting it into a module that can be displayed inside one of our split-screen game windows. This will involve cropping the map, and moving the point of view as the player moves throughout the map.

Other modules may also be generated in order to test swapping between the map and other modules.

**Comment by Sshatzkin** [comment]
The map module is now fully-functional. It exists as a map.h header and a map.c file. I've created a simple map interface that includes a map struct and can be operated with only 4 necessary functions, map_init, map_set_displaywin, map_refresh and map_crefresh.

1. **map_init** initializes a new map_t * and draws rooms inside it
2. **map_set_displaywin** takes row,column coordinates for the upper left and lower right corners of the window that the map will occupy.
3. **map_refresh** updates the map to show all of the rooms centered at a certain row/col number on the map
4. **map_crefresh** updates the map to show the room at room coords (x,y,z) at the center of the map. The z coordinate indicates current "floor number"

Using these functions, the map can now be displayed at any size, anywhere in the screen and resized. It can be navigated, one row/col at a time or jump to show any room. It can also accommodate rooms on multiple floors, showing only the rooms on the current floor.

**Comment by mpcsh** [comment]
@Sshatzkin I would rename `map_crefresh` to `map_center_on`. Other than that this looks great!

**Comment by mpcsh** [comment]
Issue Score: ✓

Comments:
Great work on this issue, but there were no updates!
