### ISSUE TITLE
Research the C API for Lua to try and highlight the key functions and aspects of the C API in a wiki document so as to further explain my familiarity with the code.

### ISSUE THREAD

**Issue by suday18** [uchicago-cs/chiventure#460]
I will be researching the C API for Lua to become more familiar with the language as it relates to C. This will include taking notes on the various modules and functions that I can use so as to gain a
more in-depth understanding of how to use Lua global variables, how to run pieces of Lua code, and calling various Lua functions. This will be documented in a wiki on Github.

Note:

This was the same issue as #449. I closed 449 because it was not connecting to a card on the sprint backlog and was, therefore, creating some confusion. This issue is tied to the one listed on the sprint backlog.

**Comment by suday18** [comment]
Here is the link to my wiki regarding this: https://github.com/uchicago-cs/chiventure/wiki/Research-on-the-C-API-in-Lua

**Comment by suday18** [comment]
Advait joined me on this issue and also did some further research and added it to the wiki document.

**Comment by suday18** [comment]
Closing Comment: We completed this task by having created the wiki which includes a number of details about the LUA C API and the various functions that can be used to access it. Here is the updated link of the wiki page: https://github.com/uchicago-cs/chiventure/wiki/Research-on-the-C-API-in-Lua

**Comment by firatciftci** [comment]
Issue Score: ✔️+

Comments:
Good work! The wiki page seems thorough and it's clear that you've put in a considerable amount of work. The only issue I see is the issue creation date — remember that scrum board cards should be converted to issues shortly after the sprint meeting on Monday.
