### ISSUE TITLE
Create a draft of a code design document.

### ISSUE THREAD

**Issue by Rusah1129** [uchicago-cs/chiventure#461]
Read through existing code, especially current player implementation, and figure out the structs/basic information needed to add player stats and write it on the wiki.

Name: Ruhi, Richard
team: rpg-playerstat

**Comment by Rusah1129** [comment]
I've completed the draft and added to the playerstat Wiki: https://github.com/uchicago-cs/chiventure/wiki/RPG-Stats:-Fitting-Initial-Stat-Ideas-into-Current-Code-Implementation---Code-Design. We've included a survey of the necessary modules currently in play, outlined a tentative list of features to include, and developed some modules and structs as a starting point. Closing it now, but we can definitely add on to it in the future.

**Comment by ecoble** [comment]
Issue Score: ✔️+

Comments:
Great work on this design doc! Some things for the next time, be sure to convert your cards to issues at the beginning of the sprint, and make sure your title is less generic that it clearly applies to your team.
