### ISSUE TITLE
Look into the NPC-related items in the feature wishlist to create a shortlist of features.

### ISSUE THREAD

**Issue by anshikab** [uchicago-cs/chiventure#462]
Name: Anshika

Team: rpg-npc

**Comment by anshikab** [comment]
I looked at some sources on how NPCs are structured and designed; so what features we want to include or keep in mind when creating the NPC feature, and what functionality we want to assign it (whether or not we implement it ourselves this quarter). We have decided to enable dialogue trees, but our design should also allow for future implementation of functionalities such as movement, carrying out specific tasks, and defining the “condition” of an NPC when a player encounters it in a game.

**Comment by firatciftci** [comment]
Issue Score: ✔️

Comments:
Good work! The wiki page seems thorough and it's clear that you've put in a considerable amount of work. The only issues I see are the issue creation date and summary description. Remember that scrum board cards should be converted to issues shortly after the sprint meeting on Monday, and make sure that your issue always has a summary description that displays the purpose and aim of the issue in a brief paragraph format.

**Comment by firatciftci** [comment]
Issue Score: ✔️

Comments:
Good work! Based on your description above it's clear that you've put in a considerable amount of work; however, a wiki page or a longer description of your findings would have been more helpful in terms of visualizing your research process. Apart from that, the only issues I see are the issue creation date and summary description. Remember that scrum board cards should be converted to issues shortly after the sprint meeting on Monday, and also make sure that you have a thorough summary description for the aim and purpose of your issue in a brief paragraph format.
