### ISSUE TITLE
Define the specific areas and task break-up between NPC and RPG teams to prevent overlap and inefficiency.

### ISSUE THREAD

**Issue by avianurag** [uchicago-cs/chiventure#463]
- Our initial sprint uncovered the fact that it isn't entirely clear what we should be working on, and what the other teams working on. 
- These teams include: rpg-npc (us), npc, rpg-battle, rpg-playerstat, rpg-openworld, rpg-playerclass, rpg-skilltrees.
- This must be resolved ASAP so that there is no overlap of work. We should also resolve whether it is feasible (if we are allowed to) for there to be cross-team issues.
- This issue will involve separately meeting the teams (over Zoom or slack) and fleshing out specific goals for each team.
- We will document these specifications on the Wiki.

**Comment by avianurag** [comment]
Update 1

We met with the other npc team on 05/05 and made progress with identifying separate tasks, which will be documented in greater detail in the wiki. 
Broadly:
- team-npc: will handle dialogue trees entirely
- team-rpg-npc: will handle the battle aspects as well as movement
- collaboration: both teams will work together on designing the structs needed for NPCs (in this sprint and the next). This will consist of 2 members from team-npc and 1 member from team-rpg-npc.

**Comment by anshikab** [comment]
Update: RPG Meeting 5/7

Representatives from all the different teams working on the rpg feature met to discuss overlap and allocation of tasks across teams. 

- Concrete common tasks were identified and assigned. These include the creation of wiki to document rpg dependencies, and writing a report on interfacing with WDL code. 

- Independent responsibilities for each team were also identified and discussed for effective designation.

- The RPG-State feature was fleshed out in detail.

**Comment by avianurag** [comment]
I forgot to attach the closing statement, doing so now:

- We conducted three separate meetings, involving the other NPC team, as well as all the RPG teams. 
- The results of these meetings were documented in the wikis described in the above updates.
- Overall, the issue was successful in allowing us to demarcate tasks that our team would handle alone. 
- Additionally, the meetings allowed us to spawn a few additional tasks for our team in the next sprint (such as the implementation of quests).

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
This issue looks great overall. I particularly like the extensive update comments you have listed. Keep up the good work!
