### ISSUE TITLE
Document a design document for quests and begin implementing basic structs

### ISSUE THREAD

**Issue by philipchenaux** [uchicago-cs/chiventure#466]
It is clear that there  is significant overlap between our npc teams and other npc/rpg team features. Therefore over the past two sprints we began to brainstorm ideas that are independent of other teams one of which is quests are be one of those features. This issue will document a design wiki of this feature which will later transition into creating sample code of this feature later on in this  sprint.

**Comment by philipchenaux** [comment]
This issue was moved from sprint 2 to sprint 3 following a discussion with other rpg teams referenced in the following issue #463 which outlined an opportunity to implement a quest module that relies heavily on npcs but may pull from aspects of rpg open-world and rpg-battle as well. First we will begin with creating a wiki that outlines a rough design implementation for how we wish to structure quests on a high level. Note that our initial implementation will be relatively basic but we will ensure we refactor our code so that as we progress through this sprint and into the following sprint we may be able to build upon the quests based on the features from other teams. Additionally, note that later in this sprint, this issue may be subdivided into several other issues following a creation of the design document.

**Comment by philipchenaux** [comment]
We have begun planning a rough outline as to how quests will be structured in the following wiki:
https://github.com/uchicago-cs/chiventure/wiki/RPG-NPC:-Independent-Feature:-Quests-Design-Document

The relevant insertions into the wiki are as follows:
> Structuring of a Quest
>On a high level we are planning on structuring a quest as a mere linked list of so-called achievements that must be unlocked in order. Below is the rough design of each of these elements:
```C
typedef union mission {
    item_t *item_to_collect;
    npc_t *npc_to_meet;
} mission_u;

typedef struct achievement {
    mission_u mission;
    bool completed;
} achievement_t;

typedef struct achievement_llist {
    achievement_t *achievement;
    struct achievement_llist *next;
} achievement_llist_t;

typedef struct quest  {
    UT_hash_handle hh;
    char* quest_id;
    achievement_llist_t *achievement_list;
} quest_t;

typedef struct quest quest_hash_t;
```
>This is basically the outline of the four structs that we will be using for quests. The mission is kept as a union for now, however upon implementation this may change into a struct in itself, and each achievement is then converted into a linked list so that it can be passed into a quests struct. The quest struct is then made hashable so that each quest can be reference by a quest_id.

Given that this is an entirely new feature, we are intending to keep the features relatively limited initially, however we can build upon the features in the following sprint. We will continue to build on this wiki in the coming days.

**Comment by philipchenaux** [comment]
We have just added the following two basic functions onto the wiki  as specified above:
```C
/* Adds an achievement to a quest
 * returns SUCCESS OR FAILURE
 */
int add_achievement_to_quest(quest_t *quest, achievement_t *achievement_to_add);

/* Checks if a quest is complete or not, and awards the necessary award if complete
 * returns SUCCESS OR FAILURE
 */
int quest_complete(quest_t *quest);
```
We are now thinking about how we should implement the beginning on a quest and how that will tie in to either what we have created with npcs or tying it into what the rpg open-world team has created

**Comment by philipchenaux** [comment]
We have changed two main things: one is changing the quest_t struct marginally to improve the clarity of the struct, and the second is we have added to the functions capabilities to extend its basic functionality:
```C
typedef struct quest  {
    UT_hash_handle hh;
    char* quest_id;
    achievement_llist_t *achievement_list;    //linked list struct holding a list of achievements that make up a quest
    item_t *reward;    //reward of the quest is an item
    bool started;    //true if the quest has been started
    bool completed;    //true if the quest has been completed
} quest_t;

/* Adds an achievement to a quest
 * returns SUCCESS OR FAILURE
 */
int add_achievement_to_quest(quest_t *quest, achievement_t *achievement_to_add);

/* Starts a quest
 * returns SUCCESS or FAILURE
 */
int start_quest(quest_t *quest);

/* Checks the status of a quest
 * returns status code for various status in the quest:
 * 0: quest has been completed
 * 1: quest has been started but not completed
 * 2: quest has not been started
 */
int quest_status(quest_t *quest);

/* rewards the prize to the player once the quest has been completed
 * returns an item (possible to be added into the inventory of the player
 */
item_t *quest_completed(quest_t *quest);
```
As always the changes can be found on [our wiki](https://github.com/uchicago-cs/chiventure/wiki/RPG-NPC%3A-Independent-Feature%3A-Quests-Design-Document/_edit). Now we are looking at how the battle team have implemented the initiation of their battles to similarly replicate the structure to quests.

**Comment by avianurag** [comment]
We realized we kept thinking of potential future features, and so decided to add a small section at the bottom of the wiki to document these as we think of them.
The relevant section of the wiki is below:

> Potential Future Features
Our current design (and implementation) of quests is simplistic by design, leaving room for several additional features that can be implemented in future sprints or development cycles. Below is a list of such features, broadly in increasing order of expected complexity of implementation.

1. The ability to have skill-based restrictions before allowing a player to attempt a quest.
2. Completely integrate battles as missions for the quest.
3. Coordinate quest stages based on rooms.
4. The current implementation includes missions/achievements that must be completed in order to finish a quest. However, this is in the form of a linked list, eliminating the possibility of completing a quest in multiple ways (a tree of missions). A future implementation could expand to include multiple paths to completing the same quest.

**Comment by avianurag** [comment]
A commit (c32c62d31a711f4c9dee23b35a011b8c6731463f) includes the implementation of the 3 basic functions for quests and the structures. 
Additionally, a small change was made to the quest struct, it was changed to:
```
typedef struct quest  {
    UT_hash_handle hh;
    char* quest_id;
    achievement_llist_t *achievement_list;    //linked list struct holding a list of achievements that make up a quest
    item_t *reward;    //reward of the quest is an item
    int status;    /* 0: quest has been completed
                    * 1: quest has been started but not completed
                    * 2: quest has not been started
                    */
 } quest_t;
```

**Comment by philipchenaux** [comment]
We have just submitted a pull request #638 which implements the basic structs of the quest module as specified on our [wiki](https://github.com/uchicago-cs/chiventure/wiki/RPG-NPC:-Independent-Feature:-Quests-Design-Document) (the structs are also shown above in a previous  post on this issue. In addition to the struct, we have also implemented the new, init, and free functions for the `achievement_t` struct and the `quest_t` struct. This is just an initial implementation that we will continue to implement more functions next sprint.

**Comment by philipchenaux** [comment]
We will close this issue as we are only waiting for the pull request to be  approved, which should be merged after a few minor changes. As we are closing this issue, we have opened another issue that we will cover in sprint 4 #646, which will address further implementation of this quest feature.

**Comment by avianurag** [comment]
Closing Summary:
- Although the pull request for this issue remains to be merged, we are closing this issue for the time being (as mentioned above).
- We were successfully able to create the Mission, Achievement, Achievement Linked List, Quest structs.
- The Achievement and Quest structs now also have new, init, and free functions associated with them. 
- We will be working on implementing more features into the quest module in the final sprint.

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Great work! I'm vert impressed by the work put into the update comments.
