### ISSUE TITLE
Research components of exemplary skill trees

### ISSUE THREAD

**Issue by jackandthebean** [uchicago-cs/chiventure#467]
# Research components of exemplary skill trees
### What
Document the design of skill trees from at least three different popular RPGs, in order to serve as inspiration for the kinds of skill trees Chiventure should be able to support.
### Why
Skill trees complement RPG narratives, empowering the game player to upgrade their avatar. One of the most important factors when considering skill tree design is the degree of player agency within the game. For example, Spider-Man (2018) implements a limited skill tree, allowing the player to develop a specific fighting style, while World of Warcraft implements a more flexible skill tree, because players are not confined to a single titular archetype (i.e. Spider-Man); rather, they can elect from a variety of player races/factions.

**Comment by jackandthebean** [comment]
# Sources
[A good summary of skill trees in well-known RPGs](https://medium.com/@kionay/video-game-skill-tech-trees-601e569fb775)

**Comment by jackandthebean** [comment]
# General Skill Tree Anatomy

* Top tree nodes are the easy-to-acquire skills from which a player develops more advanced skills
* Each of these nodes defines a skill category, such as player health, magic spells, combat moves, etc.
* Gating mechanisms define when a player can acquire a skill; good game design ensures skill acquisition progresses in a balanced way (@VannStrasen is specifically researching how to balance skill trees in Sprint 1)
* Skill tree nodes should communicate the effect of the specific skill, so that the player knows how to use it; some skill tree designs even contain previews of skills to follow in each existing node, so that the player knows what to expect/look for

**Comment by jackandthebean** [comment]
# Diablo Skill Tree
* Total number of skills a player can possess at any point in time is limited (a design choice that enhances/complicates gameplay)
### Skill Types
* Skills are categorized into **Active**, **Passive**, and **Active/Passive**
* Active skills must be manually activated and can either be **Channeled** (after activation, the player must maintain the effect of the skill (spell cast) with a repeated action) or a **Summon** (a minion character will materialize to help the game player in their battles/endeavors)
* Passive skills do not need to be activated; once acquired, their effect is lasting or triggered by other events in the game
* Active/Passive skills exhibit a blend of active and passive skill behavior (e.g. "auras" have a passive effect but can occasionally activated for player bonuses)
### Skill Organization
* Diablo skill trees are navigated with tabs that categorize the trees into "Druid Skills," "Elemental," "Shape Shifting," and "Summoning"
* Each tree displays the skills in rows, with each row signifying the level at which they become available for acquisition (the top row of skills is available at the game avatar's inception)
* Arrows between skills indicate which skills are prerequisites for others
* Possessing certain combinations of skills can passively enhance the effect of those skills

**Comment by jackandthebean** [comment]
# World of Warcraft
* Skills for professions can be "created" or "harvested," while riding skills must be purchased from riding trainers (i.e. active skill acquisition mechanisms, via construction, training, quest completion, or purchase, as well as chance skill acquisition mechanisms)
* The ability to use specific tools (e.g. weapons, armor) depend on the skills acquired by the player; skills indirectly empower the player by providing access to advanced technology
* Player races determine the starting skillset and the class of skills the player should strive to acquire (e.g. as a death knight, rune-forging skills are a prerequisite for engraving runes on weapons)

**Comment by jackandthebean** [comment]
# Path of Exile
### Methods for Acquiring "Skill Gems"
> * Earned through a quest reward
> * Purchased from town vendors once a certain quest is complete
> * Vendor recipes
> * Random drop from monsters, chests and strongboxes
> * Vaal skill gems are obtained from Vaal Vessels in corrupted areas or by corrupting a regular skill gem
> * As a reward for turning certain sets of divination cards
* Skill gems also have associated levels, so even after a skill is acquired, the skill can be upgraded to higher levels to result in better performance (usually by collecting experience points associated with using the skill)

**Comment by jackandthebean** [comment]
# Closing Issue #467
### Ultimately, the features of a good skill tree include:
* A unique skill tree for each distinct category of skills, unless the game supports only one category of skills (e.g. only magic spells)
* Gating mechanisms that determine how/when a skill can be acquired
* Short comments on each skill node with a description of the skill (what the player can use it for) and perhaps a hint at what the player can do to acquire the next skill after it
* Limited skill tree resetting abilities: a Chiventure game developer should be able to determine whether a player of their game can hold unlimited skills or only a limited number of skills at a time. If only a limited number at a time, the option to possibly remove skills to make room for other ones should be available. Otherwise, the game player will always have to face the consequences of electing certain skills over others, with no room for skill-selection error.
### Considerations for Design/Implementation of Skill Trees in Chiventure
* We should have templates for how Chiventure game developers can organize their skill trees, whether with only one category of skills or several, as well as templates for how skill trees should be displayed on the command line
* We should have gating mechanism events. The analogy here is to JavaScript events like onClick or onLoad, etc. So, in Chiventure, we could have "onPurchase" or "onQuestCompletion" as events that trigger skill acquisition. We would have to work with WDL++/DSL to decide on how these events would be specified.
* The skill trees library of functions should be focused on triggering skill acquisition (see above point) and supporting skill usage by game players.
* Down the line in Chiventure development, with multiplayer support, we should also be able to support the ability of players to trade skills.

**Comment by jackandthebean** [comment]
# Closing Issue #467
### Ultimately, the features of a good skill tree include:
* A unique skill tree for each distinct category of skills, unless the game supports only one category of skills (e.g. only magic spells)
* Gating mechanisms that determine how/when a skill can be acquired
* Short comments on each skill node with a description of the skill (what the player can use it for) and perhaps a hint at what the player can do to acquire the next skill after it
* Limited skill tree resetting abilities: a Chiventure game developer should be able to determine whether a player of their game can hold unlimited skills or only a limited number of skills at a time. If only a limited number at a time, the option to possibly remove skills to make room for other ones should be available. Otherwise, the game player will always have to face the consequences of electing certain skills over others, with no room for skill-selection error.
### Considerations for Design/Implementation of Skill Trees in Chiventure
* We should have templates for how Chiventure game developers can organize their skill trees, whether with only one category of skills or several, as well as templates for how skill trees should be displayed on the command line
* We should have gating mechanism events. The analogy here is to JavaScript events like onClick or onLoad, etc. So, in Chiventure, we could have "onPurchase" or "onQuestCompletion" as events that trigger skill acquisition. We would have to work with WDL++/DSL to decide on how these events would be specified.
* The skill trees library of functions should be focused on triggering skill acquisition (see above point) and supporting skill usage by game players.
* Down the line in Chiventure development, with multiplayer support, we should also be able to support the ability of players to trade skills.

**Comment by firatciftci** [comment]
Issue Score: ✔️+

Comments:
Good work! The wiki page seems thorough and it's clear that you've put in a considerable amount of work. The only issue I see is the issue creation date — remember that scrum board cards should be converted to issues shortly after the sprint meeting on Monday.
