### ISSUE TITLE
Document dependencies and ensure compatibility between custom scripts and WDL, Game State, and Action Management by communicating with relevant teams

### ISSUE THREAD

**Issue by hugo-chan** [uchicago-cs/chiventure#471]
The implementation of custom scripts in chiventure will depend on the implementations of WDL (how custom scripts are specified), Game State (how information about custom scripts are stored in the game struct), and Action Management (how custom scripts are run). To ensure other teams are aware of these dependencies of custom scripts, I will open and maintain communication with the relevant teams (WDL and Action Management) during this sprint.

I will reach out to these teams on Slack and discuss what medium of communication will be most appropriate and communication. I will create a document detailing the dependencies our team is envisioning, and I plan to discuss these dependencies with at least one member from each of these teams. I will record my notes from my communications with these teams in either the same or a separate document. I will know this task is done when I have discussed with the relevant teams and these documents are complete.

**Comment by hugo-chan** [comment]
I talked to Zachary Wu from custom actions on Thursday, Isaac Fink from action management on Friday, and Elaine Wan from WDL++ on Saturday. I will be writing up my document and posting it on the wiki.

**Comment by hugo-chan** [comment]
Closing issue: wiki document can be found [here](https://github.com/uchicago-cs/chiventure/wiki/Custom-Scripts:-Communication-Notes-and-Dependencies)

**Comment by firatciftci** [comment]
Issue Score: ✔️+

Comments:
Really good work! The only thing I'll have to mention is that you should post updates about your meeting notes in the issue itself. I see that you have information about it in the wiki page, but ideally these notes should be placed in the issue, so that there is a clearly visible chronological pattern of your work.
