### ISSUE TITLE
Implement end conditions based on item attributes

### ISSUE THREAD

**Issue by ericyc16** [uchicago-cs/chiventure#472]
Issue #422 developed a design for end conditions based on item attributes (found [here](https://github.com/uchicago-cs/chiventure/wiki/Action-Management---End-Conditions-Design)). This design specifies the introduction of a list of action conditions to the game struct.  A game will end when all of the conditions in the list are met and when the final room is entered.  If a final room is not specified, then the game ending is only dependent on all action conditions being met (and vice versa).

To realize this design, implementation of the following is necessary:
1. A field that stores a list of action conditions needs to be added to the game struct
2. Functions to add, check, and delete end conditions need to be implemented

Additionally, perform unit tests to ensure that this new mechanism functions as expected.

**Comment by ericyc16** [comment]
Talked to @Dumplingz about his plan to make action conditions more generalized (so that they can be applied to more than just items) and how this would affect the end conditions mechanism.  We believe that once he has gone through with this change, the implementation that I am working on for this sprint will barely (if at all) have to be changed.  Therefore, I will go through with the design as described in my design document and will update the code (if necessary) once his changes are made.

**Comment by ericyc16** [comment]
Added the `action_condition_list_t *end_conditions` field to the `game_t` struct. Additionally wrote/documented function headers to add end conditions to a game, check if all end conditions of a given game are met, and free/delete a list of action conditions. Next step is to actually write the code for these functions.

**Comment by ericyc16** [comment]
Discovered that there already was a function to free/delete a list of action conditions (`delete_action_condition_llist` in game_action.h), which is great because it makes my job easier.  Removed the redundant header that I had previously added to item.h. Also implemented `add_end_condition_to_game` in game.c.

**Comment by ericyc16** [comment]
Implemented the function end_conditions_met. All code compiles, so the next step is to write/run tests.

**Comment by ericyc16** [comment]
Test written for `add_end_condition_to_game`. Looks like that function works as expected, so now on to a test for `end_conditions_met`.

**Comment by ericyc16** [comment]
Test written for `end_conditions_met`. It had seemed that there was an issue with that function, but after staring at the code for a while it ended up just being a problem with the test I wrote. Now, all code compiles and all tests pass.

The only thing left to do to close this issue is the pull the code I have written into the dev branch. However, I will not be submitting a pull request until I have finished issue #521, where I will integrate the end conditions mechanism with the rest of the chiventure code. Until then, I will leave this issue open.

**Comment by ericyc16** [comment]
I have finished issue #521, so now all that's left to close the issue is to get the pull request approved.

**Comment by ericyc16** [comment]
Pull request #611 has been approved and merged, so I am closing this issue.

In summary, in this issue I accomplished the following:
- Added the `action_condition_list_t *end_conditions` field to the game_t struct
- Implemented the functions `add_end_condition_to_game` and `end_conditions_met`
- Wrote tests for the above two functions
- Merged this code with the dev branch

**Todo**:
- Develop a way for WDL/WDL++ to specify end conditions (a backlogged issue will be created to address this)

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Great work! This is a clear and easy-to-follow issue, and the links you've provided to the related issues make the progress easy to understand.
