### ISSUE TITLE
Researching game balancing in regards to skill-acquisition

### ISSUE THREAD

**Issue by VannStrasen** [uchicago-cs/chiventure#473]
Skill trees provide a developer both more avenues for creativity and more avenues for balancing problems. By researching the way other games balance their skills, we should come up with ways skill trees can help promote balanced games inside the chiventure editor so as to allow game creators to provide more creative games that are still tuned to the progression that they want.

**Comment by VannStrasen** [comment]
Over the weekend I looked at 6 different games (Pokemon, Super Mario Odyssey, Tetris, Skyrim, Runescape, World of Warcraft) to analyze game balancing in regards to skill trees. My notes on the topic based on user stories can be found [here](https://docs.google.com/document/d/1-aQiUbQY7y1qEaUSVZ-4F4B5Ur3J8nz3w1bGLsMU-MQ/edit?usp=sharing). 

One thing that I need to do is understand where I should be posting my research in that google document; I believe it shouldn't stay in this issue, but I'm not sure exactly where to put it. I need to talk with @firatciftci to make sure I understand where my research should go.

Here are some takeaways that I got from the research, some of which is in regards to game design, and some of which I gained coincidentally through my research:
1. Skills that are learned at a concrete point in time (instead of being improved over time) can be both temporary and permanent; if a skill is temporary, however, a good game will make sure that a user is never [softlocked](https://www.urbandictionary.com/define.php?term=Softlock). **We should discuss together how we can help developers avoid softlocking.**
2. Skills can be learned based in part on your class-type. Either throughout the gameplay, or even right at the start of the game, your class can determine your skills. However, a class should not be softlocked from the beginning because they cannot learn a skill. **We should talk with rpg-classtypes to inform them that, while class-based skills are possible, these class-specific skills should not hinder other classes from playing the game.**
3. Similarly, if learning one skill means not being able to learn another, this shouldn't mean that choosing to not learn one skill should stop you from playing. **We should talk with team open-worlds to let them know that if learning skills in the open world prevents a player from learning another, that the game shouldn't softlock.**
4. Progressive skill accrual can be flat through the whole game, or it can be increased or decreased on two factors: 1) The difficulty of the challenges being faced, and 2) the amount your character has already progressed in said sill. 
5. There is a fine line between progressive skill accrual skills and stats. For instance, one might argue that the level of a character is a stat, but is the level of a skill a stat? **We should talk with team rpg-stats to understand where team-skilltrees' projects stop and stats' projects begin.**

**Comment by VannStrasen** [comment]
Firat and @jackandthebean showed me that I should be posting my research on the wiki. I will leave up the google doc from the previous comment, but here is the wiki post that I made: https://github.com/uchicago-cs/chiventure/wiki/Research-on-game-balancing-in-regards-to-skill-trees

**Comment by firatciftci** [comment]
Issue Score: ✔️+

Comments:
Good work! The wiki page seems thorough and it's clear that you've put in a considerable amount of work. The only issue I see is the issue creation date — remember that scrum board cards should be converted to issues shortly after the sprint meeting on Monday.
