### ISSUE TITLE
Look into skill tree design in relation to other planned rpg features such as player classes and player races

### ISSUE THREAD

**Issue by steeltrapp** [uchicago-cs/chiventure#474]
Create wiki post with following information: for each planned rpg feature in chiventure, research and come up with ideas regarding player skill tree design in relation to the feature.

**Comment by firatciftci** [comment]
Issue Score: ✔️

Comments:
Good work! The wiki page seems thorough and it's clear that you've put in a considerable amount of work. The only issues I see are the issue creation date, summary description, and closing note. Remember that scrum board cards should be converted to issues shortly after the sprint meeting on Monday. Also, make sure that your summary description outlines both the aim and the purpose of the issue; what you have above gives brief information about the aim, but ideally it should be longer and more detailed. Lastly, make sure that you create a new comment for your closing notes after closing your issue, which should include a brief note about what you have accomplished, along with your link to the wiki page that you have created.
