### ISSUE TITLE
Designing How Stats Might Work with Other Implementations

### ISSUE THREAD

**Issue by jerrashi** [uchicago-cs/chiventure#475]
Ideas:
Different classes have different stats
Events in game lead to decrease in stats, inventory items can level up stats
Touch base with other RPG teams
How do stats affect game play?

Working with many teams in dev-rpg channel.

**Comment by jerrashi** [comment]
Read through design document about prospective implementation of player stats as well as list of team focuses to better understand how our implementation might overlap with other teams.

**Comment by jerrashi** [comment]
After reading through other team members documentation of the existing code (https://docs.google.com/document/d/18ZWZrPmjnD7ba28zNvvWp0n7KCrv42SXv3v9sOU6KM0/), as well as a possible player class design on the wiki (https://github.com/uchicago-cs/chiventure/wiki/Player-Class:-Design-Plan), I have come up with a few questions to address with other rpg teams during our next meeting. I have put this in the slack channel for my team as well.

Questions:
1) Should base stats of player be an array of stat_t pointers? I.e. players will have more stats than just one "base" stat. Also, should it be renamed to simply stats, assuming the player's stats will continually change throughout the game.
2) What is the difference between attributes and stats?
3) Will any stats besides hp be used during battle?

**Comment by jerrashi** [comment]
For now, this issue will be closed since the only remaining step is to discuss with other teams. This may be reopened if new, related issues come up.

**Comment by ecoble** [comment]
Issue Score: ✔️+

Comments:
Great work, especially with bringing up how your team is affected by other teams! Some things for the next time, be sure to convert your cards to issues at the beginning of the sprint, and make sure your summary has a clear goal (in this case, writing a design document).
