### ISSUE TITLE
Reintroduce "WALK" Synonym for "GO" Action

### ISSUE THREAD

**Issue by isaacfink21** [uchicago-cs/chiventure#476]
As described by issue #120, several synonyms were removed from the action struct to fix a complication in creating structs in get_supported_actions function. This implements the "WALK" synonym for the "GO" action.  This involved determining which structs and functions are affected by this change, and implementing the appropriate compatibility.

**Comment by isaacfink21** [comment]
Implemented synonym "WALK" and submitted PR for branch 'action-management/walk-synonym'.

**Comment by borjasotomayor** [comment]
Please don't close this kind of issues until the code you've written has been merged into chiventure via a pull request.

**Comment by isaacfink21** [comment]
Closed via PR #492. In addition to the `WALK` synonym for `GO`, action synonyms have been re-introduced as legal for the following actions:

/* KIND 1: <ITEM> */
CONSUME // synonyms: USE, EAT, DRINK
The WALK synonym is now fully functional, and the other three synonyms are legal but require implementation from CLI. As there are now two versions of the 'use' action, the original version (kind ITEM_ITEM) has also been refactored to USE_ON.

**Comment by MaxineK36** [comment]
Issue Score: ✔️+

Comments:
This is a great example of taking on part of a backlogged issue! However, this issue should have had many more updates considering its size.
