### ISSUE TITLE
Look into how skills can be parsed / integrated with existing WDL

### ISSUE THREAD

**Issue by ly-chen** [uchicago-cs/chiventure#477]
Info is stored in Chiventure using YAML files and parsing functions that load the files. This WDL affects and represents what interactions users can have in what rooms, among other things, and therefore affects how skills and skill trees can be implemented. In order to understand how to have skills that affect the environment, skills that are dependent on location, locations that can only be accessed with certain skills, etc. we need to first understand how skills can be parsed / integrated with the WDL system.

**Comment by ly-chen** [comment]
A write-up on how the existing system may support certain skills, and what skills cannot yet be supported can be found here: https://github.com/uchicago-cs/chiventure/wiki/Potential-Skill-Tree-Parsing---Integration-with-existing-WDL

**Comment by firatciftci** [comment]
Issue Score: ✔️+

Comments:
Good work! The wiki page seems thorough and it's clear that you've put in a considerable amount of work. The only issue I see is the issue creation date — remember that scrum board cards should be converted to issues shortly after the sprint meeting on Monday.
