### ISSUE TITLE
Writing sample lua script and .c file to gain familiairty with the LUA C API interface

### ISSUE THREAD

**Issue by suday18** [uchicago-cs/chiventure#478]
We will be working on writing sample LUA scripts and .c files in which LUA can be called to change certain fields in the .c struct. This will be placed into a sandbox on GitHub in a separate custom-scripts branch.

We will also be working with the WDL team to understand how to parse WDL files to work with LUA and C to create custom scripts for specific items.

**Comment by suday18** [comment]
Having spoken to the WDL team and made some sample LUA scripts and C files, we are now going to be collating all of our work into a larger research document which will be in the form of a wiki page.

**Comment by suday18** [comment]
I have added a sandbox in which the c files and Lua files can be located as well. 
https://github.com/uchicago-cs/chiventure/tree/custom-scripts/src/custom-scripts/sandbox

**Comment by suday18** [comment]
Closing Comment: During this sprint, we were able to successfully get a sample c file to interact with an LUA script and alter the contents of a C file. We also created documentation and sandbox to highlight this work and the research that we did to understand how structs in C can be passed to LUA. This research and practice will be integral to Sprint 3 when we start to actually implement functions to interact with WDL and action management as part of Chiventure.

**Comment by firatciftci** [comment]
Issue Score: ✔️+

Comments:
Good work! The only small pointer I have is about your the meeting update comment above: If your issue is about meeting with another team, you should list more information about the meeting itself; e.g. who you met with, when the meeting occurred, what exactly was discussed, what were the list of outcomes from the meeting, etc.
