### ISSUE TITLE
Revisit RPG Battle design document and update it with specific modules and stubs for the next experimental phase. 

### ISSUE THREAD

**Issue by alex-sheen** [uchicago-cs/chiventure#481]
At some point during the next sprint, Celia and I will meet with our TA Dawson and revisit the design document. We will be removing unnecessary modules, further specifying existing ones, and noting where our stubs will be located.

Design document: https://github.com/uchicago-cs/chiventure/wiki/RPG-Battle-Systems:-Design-Document

**Comment by celiaanderson** [comment]
Transferred an updated design document, with redesigned modules, to the wiki based off our meeting with Dawson. The modules are a Battle Flow module, which depends on the Battle State, Logic Handler, and AI modules. Their purposes and general ideas about possible structs & functions (e.g. a character struct in Battle State, move logic in the logic handler, player/enemy turns in Battle Flow, and hardcoding enemy moves in the AI module) have been written on the wiki (https://github.com/uchicago-cs/chiventure/wiki/RPG-Battle-Systems:-Design-Document). Right now, the wiki has a fairly high level description, and we will be updating the wiki to flesh out each module with structs and function names/descriptions.

**Comment by celiaanderson** [comment]
Added possible function names, with descriptions of what each function would do, for the four modules. The possible fields of battle and character structs in the Battle State module are further specified. All this information is documented on the wiki page.

**Comment by celiaanderson** [comment]
Closing this issue - the design document has been updated this week to have redesigned modules (Battle Flow/Battle State/Logic Handler/AI) with descriptions of each module's purpose and possible functions and structs and stubs. The most recent final changes have been to edit formatting/ordering of the document for some more clarity (e.g. moving location of struct descriptions) and to add an initial description of the battle design, with notes on possible stubs, like simulation of stats. This design document may be revisited later on to add more features, such as more details about an AI difficulty system, but for now, the necessary framework for a four-module battle systems design has been fleshed out.

**Comment by dwahme** [comment]
Issue Score: ✔️++

Comments:
Great job! Well done having solid updates whenever progress is being made, whether it be meetings or other pieces of work.
