### ISSUE TITLE
Start experimental coding for battle modules by creating Player/NPC and Stats

### ISSUE THREAD

**Issue by Purrsephone** [uchicago-cs/chiventure#482]
This week we will begin experimental coding for rpg-battle. We will focus on a few modules: 

Player/NPC—managing and storing information about the player and enemy during battle (Sophie and Nathaniel) 
Stats—how stat calculations that effect things such as HP, XP, and resilience/weakness will operate during battle. (Sophie and Nathaniel)

These modules will have many values hard coded in, but we want to get a sense of the structure of the code.

**Comment by Purrsephone** [comment]
Made a players_stats.c file that contains code to create a dummy player and implemented some useful helper functions for battle. Also made a structs.h file.

**Comment by nmartinez233** [comment]
Created a dummy enemy with an example inventory, armor list, and stats along with other functions to manage inventory organization during battle. These changes were made in enemy.c/enemy.h, along with minor changes in other files as necessary to implement these functions.

**Comment by dwahme** [comment]
Issue Score: ✔️++

Comments:
Great job! Well done being explicit about the modules you plan to implement ahead of time and what you plan to build for them.
