### ISSUE TITLE
Researching how other games avoid softlocking, and how we might implement warnings/help game developers avoid softlocks.

### ISSUE THREAD

**Issue by VannStrasen** [uchicago-cs/chiventure#483]
Continuing from my last issue on [game-balancing in regards to skill trees](https://github.com/uchicago-cs/chiventure/issues/473): 

[Softlocking](https://www.urbandictionary.com/define.php?term=Softlock): "A savestate in video games where you are placed in an inescapable situation, preventing progress forward in the game, and also preventing backtracking, leaving you stuck in a particular position with no hopes of escaping."

Softlocking is a sad consequence of creating intricate skill trees: If skills are required to get past obstacles and that skill is not obtainable, the game has to be completely restarted. 

We need to research 1) how skill-based softlocking are avoided in other games, as well as 2) brainstorming ways we can design the game engine so that game developers are aware of possible softlocks before they ship their code to users.

**Comment by VannStrasen** [comment]
I am closing this issue for two different reasons. Firstly, after working more with the team, it seems like we're not ready to begin working on a softlock compiler warning because more effort should be pushed to creating the code for skills. Secondly, I would need to talk with open world about this first before understanding if it's an idea that I should even research. As this isn't so much an existing bug with our code and is instead a hopeful piece that could be added to Chiventure, I am closing this issue and leaving this on the backlog in case someone else wants to pick it up.

**Comment by firatciftci** [comment]
As this issue has been left to the backlog, I have modified its milestone accordingly and reopened the issue. As a reminder, any issue that has not been resolved and has been left to the backlog should remain open, in case anyone would like to take a look at it in the future.

**Comment by rohangupta2806** [comment]
Further research was done on softlocking and a wiki page was made on the issue:
https://github.com/uchicago-cs/chiventure/wiki/Avoiding-soft-locks-in-skill-tree-integration
This issue will now be considered resolved and will be closed.

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Great job!

**Comment by VannStrasen** [comment]
wooo!
