### ISSUE TITLE
Document feasibility of implementing a "player" in chiventure

### ISSUE THREAD

**Issue by ela-ine** [uchicago-cs/chiventure#486]
Currently in chiventure, there is no defined "player," and as a result, there is no ability to save a game under a specific player and no accommodation for player levels, stats, etc.

However, these parameters are essential for many types of games, RPGs being one. This document will investigate current support for a player into the chiventure, and will be used in thinking about how WDL++ might integrate these capabilities.

**Comment by ela-ine** [comment]
Started compiling document (which can be found [here](https://github.com/uchicago-cs/chiventure/wiki/%22Player%22-Implementation:-Feasibility-and-Potential-Integration-with-WDL--)) — outlined needs for player integration and some current support from game-state.

**Comment by ela-ine** [comment]
After discussing the direction of the WDL++ design with @namanhd1nh and @blakemoss yesterday, it seems like a better decision to hand off the intialization/updates of the player struct to another team (since it seems a little outside the scope of WDL). Especially since actions usually trigger player stat updates, I think action-management might be suitable. Maybe the init can be handled by game-state?

**Comment by ela-ine** [comment]
Although this document wasn't able to fully flesh out the details of how WDL++ will represent players, I've tried to record the current state of the "player" in chiventure, and have gotten a better grasp on how the different modules in chiventure work together. For WDL++, we've tentatively defined the player as a sort of "special object," but the implementation details will be hammered out in the future.

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
This issue is well-written and easy to follow—great work!
