### ISSUE TITLE
Revise the world generation algorithm. Talking about the different stages of what is feasible to accomplish. What will it look like in Sprint 2 vs 4?

### ISSUE THREAD

**Issue by edward3-uchi** [uchicago-cs/chiventure#487]
Now that we are beginning to code some of the algorithm. We need to revise the world generation algorithm and start to think about what is possible during our length of time. Also, what is possible during each sprint? We may know a possible end goal but we need to know what our incremental goals are.

**Comment by edward3-uchi** [comment]
Updated the document quite a lot, which I will touch on here in a second. You can find the document in the [wiki](https://github.com/uchicago-cs/chiventure/wiki/Open-World:-World-Generation-Algorithm-Plan). 

First and foremost, I have added changes that talk about dependencies on teams and contingencies for features. The NPC functionality will depend on one team. Also, the parameters change quite a lot through the life of the algorithm which is due in part to the return type of the algorithm. The end goal return type is a FILE* that points to some WDL++ file. I believe this is the best return type if you want to use the algorithm. However, some discussion on whether or not you want to just make NPC's and rooms is valid,  which will need to be answered more clearly in the future.

**Comment by edward3-uchi** [comment]
Closing the Issue now. The document on the wiki will probably continue to be updated as we begin implementation. The document answers a few questions: 1. What is the end goal of our algorithm? 2. What will our algorithm return? 3. What types of parameters will it need? All of these questions are also answered in regard to the stage the algorithm is in.

**Comment by dwahme** [comment]
Issue Score: ✔️+

Comments:
Great job! Here are a few things you may want to improve in future issues:

An issue should have the goal of producing something tangible, such as code or documentation, which must be specified in the summary.
