### ISSUE TITLE
Graphics: animated text module using raylib

### ISSUE THREAD

**Issue by seanrryan** [uchicago-cs/chiventure#488]
After our group meeting, @xmvalencia and I are going to move forward with [raylib](https://www.raylib.com/) ([Wiki post](https://github.com/uchicago-cs/chiventure/wiki/Graphics:-raylib)) as our graphics library by making some features that one might find in a text adventure game. Since raylib supports keyboard and mouse input, as well as animating and displaying text, it could be possible to make a module that animates and displays a given message to the player, and dismisses the message and exits upon clicking or pressing a key. This module would be a useful way to convey important information to the player, such as level up messages, or it can serve as a transition for when the player begins an interaction or a battle. Ideally, this feature should have relatively few inputs/requirements (access to raylib library, a given message to display, etc.) so that in the future it could be implemented with fewer dependencies. 

We'll start by experimenting with the keyboard/mouse and text/animation on its own first, and then we'll continue with combining these features and potentially testing in a sandbox environment.

**Comment by seanrryan** [comment]
So far, example programs have been made to track mouse movement/clicks within the game window, keyboard presses, and display text to the game window.

The main issue that we are facing has to do with the installation and setup of the library. On Friday we discussed looking into installing and using raylib using a virtual box, which requires some additional setup but might be necessary for future integration with chiventure. Using raylib on our personal machines works for now as we experiment with more isolated examples. However, setting up raylib on Windows has proven to be very difficult.

**Comment by xmvalencia** [comment]
_Status of raylib: Working on Windows_
While looking at the use of raylib we looked at the capabilities on mac and linux, however, while attempting to close the issue and complete the task I ran into many problems while looking to work with raylib on a Windows machine. On windows, raylib needs to be run using specific compilers that aren't already installed and most likely haven't used before. This means that to work with raylib on windows there would be many steps necessary to begin using raylib. There are also other issues with raylib that weren't completely obvious while researching which library to use and are becoming evident as we start to implement. For the next sprint, a possible document to show window users how to install and run raylib may be necessary. But for right now it seems like any progress using raylib may need to be run on a Mac machine.

**Comment by seanrryan** [comment]
![image](https://user-images.githubusercontent.com/19596278/81530817-9c1b4400-932f-11ea-9d21-00a3922d5e24.png)

This is a very basic module which appears in a separate window. The size of the window can be customized easily, along with any sort of stylistic choices such as background, color, font, message, etc. For the sake of simplicity, this design is very simple (for now). Keys can be mapped to various functions, so the space bar is the "exit" key for this particular window. When incorporated with more graphics modules or within a chiventure game, this could mean that the loading screen or message is dismissed and the user is brought to the next scene or environment. In the case of a standalone module such as this one, continuing by hitting the space bar closes the window and terminates the program, as there are no further instructions being provided. 

Some important takeaways from this:

- From what I can tell, using raylib would almost certainly signal a departure from a direct command-line interface. In this case, text would be displayed through raylib's font/image/display related features and typing would be detected by raylib as text input. Although we are early in the process, this seems like a pretty serious topic to start discussing and thinking about as it pertains directly to the future of chiventure as a game engine. What we decide on would have a big impact on overall user experience as well as the design and implementation of chiventure itself.

- raylib seems to have a pretty intuitive environment when it comes to windows, which happens to be where all of the functionality occurs. There are several functions that handle window sizing, initialization, termination, and so on. This could be helpful for developing a modular design for types of windows corresponding to different processes. For example, this could mean that one type of window can have certain controls associated with it (i.e. spacebar as a "continue" button) while other windows can have their own controls and attributes.

- Now that we have gained some hands-on experience, the group should discuss what is and isn't working well and how that might affect our ideas for incorporating raylib's functionality into chiventure. This may include looking at SDL some more in order to reach a consensus on what library we should move forward with.

**Comment by ecoble** [comment]
Issue Score: ✔️++
Comments:
Great work on this issue! Both your summary and your updates are really in depth!
