### ISSUE TITLE
Begin writing a formalized design doc for skill tree implementation

### ISSUE THREAD

**Issue by michaelleestuy** [uchicago-cs/chiventure#497]
We will now begin to formalize a prospective design structure for our implementation of skill trees. The goal is to write a design document that documents the overall structure of this feature. Included will be the modules, the structs and functions that they contain, and interfaces to interact with both other features, as well as with the user.

**Comment by michaelleestuy** [comment]
Discussed potential designs with @steeltrapp @VannStrasen @ly-chen @jackandthebean. Initial ideas added to [wiki page](https://github.com/uchicago-cs/chiventure/wiki/Design-Documentation-for-Skill-Trees-Implementation), which is a work in progress, and will be updated along with changes and refinements to the design.

**Comment by michaelleestuy** [comment]
Updated the [wiki page](https://github.com/uchicago-cs/chiventure/wiki/Design-Documentation-for-Skill-Trees-Implementation) with a version 1.0 for the design document. The wiki will be updated as features and design decisions change, as we get a clearer picture of dependencies between teams.

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Great work with the design document! A minor comment: Your closing comment should ideally be a short paragraph that describe the progress you've had throughout your work on the issue, and the final output that you've reached, which in this case is the wiki page.
