### ISSUE TITLE
Document dependencies between RPG player stats and RPG battle system, player class, and  skill trees

### ISSUE THREAD

**Issue by richardxd** [uchicago-cs/chiventure#498]
The boundaries between different RPG teams are unclear, and the objectives of this week's sprint are ambiguous. This issue documents what the other RPG-teams envision how their part of the game would be and ensure what the player stats team will be providing them with the desired features.

**Comment by richardxd** [comment]
After meeting with the other RPG teams we come up with a Dev meeting notes that explain what each team requires. Specifically, the RPG player stats team has understood how the battle system will be designed. We understand that the RPG battle will involve turn-based battle mechanism, similar to Pokeman, and the basic stats requirement that other teams would want, which includes 
- Health
- XP
- Speed
- Physical Defense
- Physical Attack
- Ranged Attack
- Magic Defense
- Magic Attack
- Magic Energy.
And we will be providing functions that allow other teams to extract stats and modify them based on their needs. We may also need to design functions that auto-generate stats for NPCs, but the specificities remain unclear as we have not yet come to the basic designs. This will be further discussed with the player NPC teams for the next sprint after we have a more concrete design.

**Comment by ecoble** [comment]
Issue Score: ✔️++
Comments:
Great job, especially with your thorough meeting update! In the future try to use the wiki to create documents, not google docs.
