### ISSUE TITLE
Document format of a conversation structure and the functions used to build them

### ISSUE THREAD

**Issue by ketchupkeith** [uchicago-cs/chiventure#501]
We want to nail down the format that a conversation will be stored under in Chiventure and add that info to our wiki page.  This will include details about the structures used, along with functions for initializing/building these structures (ideally designed in a way convenient to the WDL team).  Once we are able to build a convo struct, we will be able to move on to subtasks like accessing a particular scene in a conversation based on user input and reworking our original dialog showcase program to function with our new architecture.

**Comment by ketchupkeith** [comment]
The conversation structs are done.  The implementation is basically a modified directed graph; a Convo has a list of Nodes (a chunk of NPC dialog being given with keywords for the player to use), and each Node has a list of potential Edges the player can take to other Nodes.  A writeup is available in our wiki page here https://github.com/uchicago-cs/chiventure/wiki/NPC-Design-and-Planning#dialogue-tree-implementation

**Comment by ecoble** [comment]
Issue Score: ✔️+
Comments:
Great job! Your summary especially is really thorough! You could maybe use a few more updates.
