### ISSUE TITLE
Produce+document scene-accessing functionality for conversation structs

### ISSUE THREAD

**Issue by ketchupkeith** [uchicago-cs/chiventure#502]
Pending strong progress in issue #501, we need to produce functions that, given a scene/node in a conversation, compares the user's input to the node's given valid options and performs the appropriate action (moving/printing a new node, ending conversation, etc). This task's functions won't need to be as concerned with external accessibility like #501's interest in WDL format. This information will be added to our wiki page.

**Comment by alexjsun** [comment]
I wrote some general functions for accessing the dialogue structs. There are functions for reading inputs, traversing to other nodes, and running appropriate actions in an entire conversation, such as ending a conversation. They are to be incorporated into the dialogue showcase file.

**Comment by alexjsun** [comment]
I updated the wiki page with information regarding the general structure of the dialogue graph as well as the functions for traversing through and accessing the nodes of the graph: https://github.com/uchicago-cs/chiventure/wiki/NPC-Design-and-Planning

**Comment by alexjsun** [comment]
The functions for accessing and traversing dialogue graphs have been implemented into the showcase file. For now, these functions serve their purpose in the showcase file, but this issue can be revisited if they need alterations/refactoring.

**Comment by ecoble** [comment]
Issue Score: ✔️++
Comments:
Great job, especially with your updates and references other relevant issues!
