### ISSUE TITLE
Convert dialog showcase program to use new conversation structures

### ISSUE THREAD

**Issue by ketchupkeith** [uchicago-cs/chiventure#503]
We want to practice using the conversation structures generated by #501 and the scene-accessing functions from #502 to refactor our dialog showcase program.  This will help show the struct's uses and functionality, as well as showing a working example of our progress in action.  We hope having this program will help us in future sprints, when we'll focus on assimilating our code into Chiventure's architecture.

**Comment by vallarymuhalia** [comment]
We have created structs for the NPC dialogue tree and have now refactored our earlier showcase program to use these new structs to run the NPC dialogue.

**Comment by vallarymuhalia** [comment]
Attached below is the refactored program.
[Showcase dialogue.docx](https://github.com/uchicago-cs/chiventure/files/4606361/Showcase.dialogue.docx)

**Comment by vallarymuhalia** [comment]
We have added color prints so that different parts of the dialogue are printed in different colors as it was in the showcase.
The changes are reflected in the showcase code file attached below. 
[Showcase dialogue.docx](https://github.com/uchicago-cs/chiventure/files/4606543/Showcase.dialogue.docx)

**Comment by vallarymuhalia** [comment]
The showcase program now runs as desired with the new structs. We intend to use this program as the project advances. A pull request to add the code to chi venture sandbox was initiated.

**Comment by ecoble** [comment]
Issue Score: ✔️+
Comments:
Great job, especially linking to other issues and updating frequently! A few small things, be sure to use the wiki not Microsoft docs or google docs, and if your issue is going to result in a pull request, you should wait until the pull request is merged before you close the issue.

**Comment by vallarymuhalia** [comment]
The pull request linked to this issue was merged into Chiventure. Our next step is to refactor our sandbox program to function as examples in the project. This will be done in sprint 4.
