### ISSUE TITLE
Preparing official WDL++ documentation: overall structure of the format

### ISSUE THREAD

**Issue by namanhd1nh** [uchicago-cs/chiventure#504]
We'd like to start work on the official documentation for WDL++ by first writing a complete description of its general structure: the top-level JSON object, the keys for GAME, PLAYER, ROOMS, OBJECTS, ACTIONS, and certain syntax notes.

The finer details and code interface within each of those sections we'll leave for next sprints since that depends on other teams' needs and our implementation down the line.

**Comment by namanhd1nh** [comment]
Our brainstorming meeting yesterday produced an outline of the detailed specifications of the file, along with some thought about minimizing our team's burden when integrating with other teams and how we could make it future-proof. 

Namely, rooms and objects, aside from baked-in data fields, will also have an attributes dictionary, and we'll provide a single interface to access that dictionary and get a value from a key (alongside other functions to access the baked-in fields). This way, when another team wishes to prototype and add a key-value pair to an object, they can do it all by themselves by writing it in their WDL file and calling our data-getting function, supplying their own key name.

The detailed specification will be put up in a branch in the repo folder for documentation soon. We will also be having a brainstorming meeting with Borja who will guide us further on how to make our design as general-purpose and flexible as possible.

**Comment by blakemoss** [comment]
On Thursday (May 7) we met with Borja and Maxine to discuss our ideas and design vision moving forward. He had a few suggestions for us which we agreed with- most significantly, a move towards an object retrieval function (as opposed to our original idea of providing functionality for teams to access specific attributes, but not entire objects) for generality and ease of use for other teams, along with a move towards a directory structure to contain game information, e.g.

![wdz_structure](https://user-images.githubusercontent.com/37815737/81514424-acfa9400-92f4-11ea-984f-95f381ebaf69.png)
(image by @namanhd1nh )

This allows for a higher degree of flexibility by allowing for accessing images/sound/etc within the WDL directly, and also simplifies future changes/additions by containing relevant  within their own files (e.g npc.json). We will reflect these changes in a specification to be placed in a branch for documentation very soon.

**Comment by namanhd1nh** [comment]
We've started a new branch wdl/documentation in the repo to write the new official [documentation](https://github.com/uchicago-cs/chiventure/blob/wdl/documentation/docs/wdl%2B%2B.md) The directory structure is present, along with the details of most of the json files, and a rough idea of the function interface to get WDL data. 

The initial requirement for this issue was to set out a structure for the file; we've so far managed to confirm that and have started on the finer details, the rest of which can become ongoing tasks that we will fulfill as we write our implementation and communicate with other teams. As such, this issue can be closed for now.

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
This issue looks great! Your post-meeting updates are very tangible and productive, which is awesome.
