### ISSUE TITLE
Graphics: visual map sandbox using raylib

### ISSUE THREAD

**Issue by damonhines** [uchicago-cs/chiventure#506]
Create a sandbox map module using raylib to test out the library and determine its capabilities for mapping. This sandbox should try and create a map with a person with one or more rooms.

**Comment by damonhines** [comment]
Beginning:

Installing the raylib library. The package is downloadable through git hub. I made it a static library and it has the cmake option. In the future, we need to look at how to link the raylib library into chiventure without having the user personally downloading the raylib library.

**Comment by damonhines** [comment]
To start the mapping process, I am going to test making rectangles and circles. This will help me understand how the draw functions work in raylib. To begin, there will be three rectangles.

**Comment by damonhines** [comment]
> To start the mapping process, I am going to test making rectangles and circles. This will help me understand how the draw functions work in raylib. To begin, there will be three rectangles.

Successfully made a map of 4 triangles.
![Screen Shot 2020-05-06 at 12 31 40 PM](https://user-images.githubusercontent.com/39503849/81209085-a509bf80-8f95-11ea-8263-d0449379e127.png)

**Comment by damonhines** [comment]
Now, I am going to restructure the way the rectangles are situated and base my new map design after a sketch I've made 
![IMG_9279](https://user-images.githubusercontent.com/39503849/81224582-8dd6cc00-8fad-11ea-9f73-14809c0119f5.JPG)

**Comment by damonhines** [comment]
Successfully got to represent my sketch via code. Next, I am going to try adding a character and object to the map. 
![Screen Shot 2020-05-06 at 3 52 59 PM](https://user-images.githubusercontent.com/39503849/81227360-e90abd80-8fb1-11ea-8b84-725fa4f44ec6.png)

**Comment by damonhines** [comment]
Currently, I am adding an ellipse to represent a person in room one. If successful, the sprint will be officially complete

**Comment by damonhines** [comment]
Completed. Now, I am able to play around and add more shapes if necessary. However, it seems that drawing shapes may be a good way to map the rooms.

![Screen Shot 2020-05-10 at 10 33 51 PM](https://user-images.githubusercontent.com/39503849/81521927-5d28c680-930e-11ea-99da-6a2e113d1894.png)

**Comment by ecoble** [comment]
Issue Score: ✔️++
Comments:
Great job! You are doing a great job updating things frequently and I like that you included images of what you're working on as well as your design sketches. One small thing, be sure to add the sprint milestone to your issues.
