### ISSUE TITLE
Create experimental code that controls battle flow and gives feedback to the user as they battle

### ISSUE THREAD

**Issue by Isaaq-Khader** [uchicago-cs/chiventure#507]
Battle flow—managing turns, starting and ending battle, logistics of a move, etc.
Feedback—printing feedback text, lets player know how effective their move was, what move their enemy used, etc.

**Comment by Isaaq-Khader** [comment]
Today I created and began working on the files feedback.c/.h and flow.c/.h. The feedback files are for print statements and the flow files are for controlling the flow of the game. These files are created in a branch I named called "battle-sandbox". These are not fully finished but have a framework of what the goal of this issue is.

**Comment by Isaaq-Khader** [comment]
Just to summarize all the commits I have made, flow.c and feedback.c have no errors and this portion of the sandbox should be set. Meaning, the foundation has been made for a battle and has stubs for areas such as attack damage.

**Comment by dwahme** [comment]
Issue Score: ✔️

Comments:
Great job! Here are a few things you may want to improve in future issues:

For a task of this size, we would've expected to see more status updates and/or status updates that were more detailed.

An issue should have the goal of producing something tangible, such as code or documentation, which must be specified in the summary.

Remember that Scrum board cards should be converted to issues shortly after the Sprint meeting. Think of the Scrum board card as a rough outline of the issue, which you then need to flesh out with a more descriptive title and summary when converting it to an issue.
