### ISSUE TITLE
Work on writing custom scripts for NPC dialogues and game state management.

### ISSUE THREAD

**Issue by canconger** [uchicago-cs/chiventure#508]
Go through other teams' specifications and look for possible uses of custom scripts in those modules. Then, work on writing provisional templates.

**Comment by DINO-ADV** [comment]
The Following is the wiki link analysing aspects of NPCs to be used for custom-scripts

https://github.com/uchicago-cs/chiventure/wiki/Overview-NPCs-in-context-to-Custom-scripts

**Comment by canconger** [comment]
The link below is a wiki exploring possible uses of custom scripts to modify the game state of players:

https://github.com/uchicago-cs/chiventure/wiki/Possible-uses-of-custom-scripts-to-make-changes-in-the-game-state.

**Comment by canconger** [comment]
We decided that we need to meet with other teams in the following weeks again to specify the needs for their modules. Then, we will start writing some scripts to fulfill their requests.

**Comment by firatciftci** [comment]
Issue Score: ✔️+

Comments:
Good work! A few things to keep in mind:

1. Make sure that your initial summary is at least a paragraph long. It should include details about why you're creating this issue, your final goal, and how you are planning to achieve it.
2. Your closing comment should be at least a short paragraph, summarizing your observations and providing a description of your final output, with any future expansion points regarding the task at hand, if appropriate.
