### ISSUE TITLE
Implement the basics of an NPC module

### ISSUE THREAD

**Issue by lilyehsani** [uchicago-cs/chiventure#510]
Create a branch for development and implementation of the basics of a NPC module as outlined here: https://github.com/uchicago-cs/chiventure/wiki/NPC-Design-and-Planning#new-npc-module. The design can be altered as necessary, but in short, the struct should be create in an npc.h file and new, init, and free functions (at least) should be fully implemented in an npc.c file.

**Comment by lilyehsani** [comment]
I created the branch npc/module-basics for development on this issue, and I added empty npc.h, npc.c and common-npc.h (trying to work out what this means with my TA) files in their correct places.

**Comment by lilyehsani** [comment]
I pushed the code for the NPC struct and the functions: npc_new, npc_init, npc_free, get_npc_health, change_npc_health, get_npc_inventory, add_item_to_npc,  and get_all_items_in_inv_npc. I was not sure how to test the functions, but most of the code was based directly on the corresponding functions in the player module.

**Comment by SadracUchicago** [comment]
I added test_npc.c which conducts validation for the npc module using the Criterion framework

**Comment by lilyehsani** [comment]
The npc.h, npc.c, and test_npc.c were moved to include/npc, src/npc/src, and tests/npc directories respectively. I removed the game-state portion of the name of this issue for clarity. This issue will soon be closed with the pull request #580 .

**Comment by lilyehsani** [comment]
The pull request has been merged. The basics of an npc struct have been implemented in the dev branch of chiventure. It took a bit longer than expected, but it was a large, important task that we wanted to do right. Updates to the npc module should be done in new issues and branches. I am closing this issue.

**Comment by ecoble** [comment]
Issue Score: ✔️++
Comments:
Great job! You especially did a great job updating and linking this issue to its pull request!
