### ISSUE TITLE
Meet with the action-management, rpg-playerstats, rpg-battle and wdl teams and produce meeting notes

### ISSUE THREAD

**Issue by NuclearWaffles** [uchicago-cs/chiventure#512]
I'm going to meet with representatives from the three teams that we foresee to be most closely integrated with custom actions, and produce meeting notes from each meeting as a deliverable. Specifically, the notes are going to be focused on functionality they need from custom actions and the interface functions they need. Also, I want to list what context objects we can acquire from the RPG battle and player contexts.

Afterwards, I need to integrate those notes and new requirements into our design before moving forward with implementation so as to minimize future unknown unknowns.

**Comment by NuclearWaffles** [comment]
Sent out invitations to all three teams for a meeting this week

**Comment by NuclearWaffles** [comment]
Met with custom-actions and custom-scripts, added in new entry to meeting notes at this [link](https://docs.google.com/document/d/1gdDvVfs3FWq6bOv9mLdG6gDKxSM35lrSfWs6gbVygsM/edit?usp=sharing)

**Comment by NuclearWaffles** [comment]
Met with RPG-playerstats and action-management, updated the notes at the above link

**Comment by NuclearWaffles** [comment]
Finished up last meeting with RPG-battle and updated meeting notes

**Comment by MaxineK36** [comment]
Issue Score: ✔️

Comments:
Good work with the summary on this! Linking to the wiki is also super helpful. One thing to look out for in the future: your status updates should be more detailed, even if there's a wiki linked. In this case, it would be useful to know exactly what was decided in each team meeting.
