### ISSUE TITLE
Create a sandbox program that utilizes raylib to take an input graphical image and display it to a window.

### ISSUE THREAD

**Issue by aherman33** [uchicago-cs/chiventure#513]
We would like to create an experimental sandbox program that uses the graphics library raylib to take an input image file and then create a window displaying that image, simulating how a game author might use a program to upload their own images for their game.

**Comment by aherman33** [comment]
The raylib library needs to be installed in order to use it. Like Damon mentioned in his issue, raylib will need to be installed on user machine to be used with chiventure. I have started by installing the raylib library on my machine.

**Comment by aherman33** [comment]
The raylib wiki comes with many useful tutorials for loading images and then displaying them to a window. I will be using this one in particular to model my basic sandbox program after.

https://www.raylib.com/examples/web/textures/loader.html?name=textures_image_loading

**Comment by aherman33** [comment]
Created a very basic program that takes an image file (note: my program could not work with a .jpg file, but did work with a .png file) and loads and displays it in a window. Here is an example of what the program output looks like:
<img width="804" alt="Screen Shot 2020-05-11 at 1 55 07 PM" src="https://user-images.githubusercontent.com/63211362/81600336-129b5e80-938f-11ea-8990-91d0a64ab131.png">

**Comment by aherman33** [comment]
Tested with some other images. Depending on the image, the size needs to be adjusted within the implementation. Will need to research ways in which the image can be adjusted to fit within the window size. Will also need to look into overlaying text boxes onto the images for the purposes of chiventure. Otherwise, this program works in successfully loading and displaying images.

**Comment by ecoble** [comment]
Issue Score: ✔️++
Comments:
Great work, especially with your frequent updates! I also like that you included a picture of what you're working on. One small thing, be sure to add the sprint milestone to your issues.
