### ISSUE TITLE
Experimental implementation for conditional connections between rooms

### ISSUE THREAD

**Issue by victoriavillalba** [uchicago-cs/chiventure#514]
We're going to try to implement the plan we made on the wiki (https://github.com/uchicago-cs/chiventure/wiki/Conditional-Connections-Between-Rooms-Design-Plan). This will involve altering code on our own branch. Since this task is something that involves the input of other groups and making changes to files outside of the action management realm, we may need to communicate our plans with other groups to see if they think it's a good idea and to make sure they're aware of what we're doing. We would be changing the action_type_t struct and working with the game state code.
Goals include:
1. Talking to game-state/wdl/etc. groups
2. Implementing code
3. Running tests

**Comment by victoriavillalba** [comment]
I updated the wiki with the outline of possible functions that would be added to our branch.

**Comment by victoriavillalba** [comment]
We didn't get as much as we would have liked done during this sprint due to a lot of searching through all the files and making sure we understand how this code will interact with many parts of game-state. We will be continuing this in Sprint 3 and hopefully concluding with tangible results. It will all be summarized in a new issue.

**Comment by MaxineK36** [comment]
Issue Score: ✔️+

Comments:
This was a generally very well-written issue! One thing to work on for next time: 
For a task of this size, we would've expected to see more status updates. It seems like there was work on the task which was mentioned in your closing statement but missing from your updates.
