### ISSUE TITLE
Convert Custom Actions Design into Code Files

### ISSUE THREAD

**Issue by brentd313** [uchicago-cs/chiventure#515]
We are going to convert our design document into header and C files, containing the data structures and function prototypes with descriptions. This is in order to make our design more concrete and to enable us to hit the ground running as we get closer to writing some real code. We also hope to continue developing our interface-implementation decisions, file structures, and any other design adaptations through this process.

Design document: [https://github.com/uchicago-cs/chiventure/wiki/Custom-Actions-Design-Document](url)

**Comment by brentd313** [comment]
Created a custom-actions/intial-headers branch (note that there is unfortunately a typo in initial) where we will include files outlining custom actions structures and functions

**Comment by brentd313** [comment]
Created "atomic.c" file containing empty functions for checking conditions and applying effects of an action. Each function includes a prototype as well as a function header, documenting the function's behavior.

**Comment by emmamedeiros** [comment]
Created "struct.h" file containing structs for custom actions implementation, as well as basic functions and headers (new, init, and free) for each of the structs.

**Comment by emmamedeiros** [comment]
Created "struct.c" file that currently contains skeleton functions for each of the basic struct functions outlined in "struct.h".

**Comment by annabelleperng** [comment]
Created "interface.h" and "interface.c" files which contain skeleton functions which have to do with custom actions as a whole (rather than smaller subunits, such as blocks). These functions should be the ones which will be called from other parts of the code, outside of the custom actions.

**Comment by MaxineK36** [comment]
Issue Score: ✔️+

Comments:
Great work! The updates on this issue are great. One thing to look out for in the future: when an issue is done, you should include a final comment summarizing what was done, and why the issue is being closed.
