### ISSUE TITLE
Begin converting skill tree research to tangible C – a design document.

### ISSUE THREAD

**Issue by jackandthebean** [uchicago-cs/chiventure#516]
# Begin converting skill tree research to tangible C – a design document.
### What
Read teammates' research from Sprint 1, meet with the other RPG teams, discuss with own team, and *consolidate* all the ideas that arise into a design document that will guide how we develop more tangible code in Sprint 3.

### Why
Our goal is to finish discussion of design in Sprint 2, so that we can focus on skill tree code in Sprint 3.

**Comment by jackandthebean** [comment]
The morning of May 7th I met with the other RPG teams; all the teams present gained a better sense of the directions each team would be going in individually. The evening of May 7th, our skill trees team also met, so I was able to fill my teammates in on what the other RPG teams might expect of us as we continue with our design/development process. During this second meeting, our team debated a lot over the way we would store our skill trees, ultimately deciding to store one general skill tree – one that contains every skill possible to acquire in the game – and individual lists with the skills a player currently possesses to keep track of their skill progress in the game. However, our discussion produced a lot of contentious design issues, so we plan to meet with Firat to resolve some of these issues and ask some questions.

**Comment by jackandthebean** [comment]
On May 9th, our team met with Firat. One of the most contentious design issues that arose during our discussion on May 7th was whether to store the effects of skills as function pointers or as strings to be parsed. After our discussion with Firat, we decided to try function pointers first, and if they proved to be too inflexible, we would return to the idea of storing strings. @michaelleestuy links our design document in #497 .

**Comment by jackandthebean** [comment]
We look forward to begin writing actual code in Sprint 3, now that we've hashed out our design concerns. Although at first we were concerned with the overlapping responsibilities of our team with other RPG teams, it seems Firat's advice to focus on our own team's work first, before we cater to the needs of other teams like `x/rpg-battle`, will be the best way to proceed.

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
This issue looks great overall. I particularly like the extensive update comments you have listed. Keep up the good work!
