### ISSUE TITLE
Design/Implement a stats struct

### ISSUE THREAD

**Issue by sumedhsarwate** [uchicago-cs/chiventure#520]
After meeting with other rpg teams, we will create a stats module and implement a stats struct inside it to hold information about player stats.

**Comment by sumedhsarwate** [comment]
After discussing with our team, we decided to implement the stats struct as a hash table. We will have a separate struct for effects (such as poisoned, stunned, etc.) that will also be stored in a hash table.

**Comment by richardxd** [comment]
8d7fd64 is a new commit that changes the stats struct. The purposes of this commit are 

1. documentation write-up
2. update the player struct so it corresponds to our current design i.e., the previous player struct still contains stats as in the type of int. This has been updated.
3. Redesigning the stats_t* affected and double val inside the effect struct to allow one effect to modify multiple stats at once. Now they have been updated as arrays whose indices link the stats affected and the modifier.

**Comment by sumedhsarwate** [comment]
We designed and implemented a stats struct and an effects struct in a stats module. Both will be stored in hash tables in the player struct. The stats struct currently has a stat value, the max value for the stat, and a modifier, along with the stat name. The effects struct has a bool for whether the effect is currently impacting a player and the duration for the effect. Currently, the effects struct also has one array of modifier values and another array of strings for each of the stats it affects, with the index of the modifier matching with the index of the string it affects. This is something we will likely need to update later to make it easier to pair each modifier to a stat and to make our code less error-prone.

**Comment by ecoble** [comment]
Issue Score: ✔️+
Comments:
Great job, especially with your frequent updates! Be sure to convert the card to an issue right at the start of the sprint!
