### ISSUE TITLE
Update chiventure code to utilize end conditions

### ISSUE THREAD

**Issue by ericyc16** [uchicago-cs/chiventure#521]
Issue #472 implemented the interface for end conditions in a chiventure game. This involved adding a field to the game struct and writing two new functions: one to add an end condition to a game, one to check if all end conditions of a game have been met. 

Now, this mechanism must be integrated with other modules so that the it can be used in chiventure games. This will mainly involve editing the `actionmanagement` module. More details can be found [here](https://github.com/uchicago-cs/chiventure/wiki/Action-Management---End-Conditions-Design#utilizing-this-mechanism).

Note that this issue does NOT include introducing a mechanism for WDL to load in end conditions from a file. That will be made into a separate issue once the code for this issue has been pulled.

**Comment by ericyc16** [comment]
Edited the headers of `do_item_action` and `do_item_item_action` to take a context struct, which will be necessary to check if end conditions are met after an action occurs. Also edited calls to these functions in `operations.c`, `test_item_actions.c`, and `test_item_item_actions.c`. All of the code compiles and the tests pass.

When I initialized the context struct in `test_item_actions.c` and `test_item_item_actions.c`, it seemed to cause a problem in the conditions_not_met tests (both direct and indirect tests in item_item) where the call to perform the action returned 0 instead of CONDITIONS_NOT_MET. This might be because I haven't actually done anything with the context struct in the functions, but it's something I need to keep in mind and may still have to debug later. I commented out the code so that a NULL context struct is being passed to the functions as a temporary fix to the problem.

**Comment by ericyc16** [comment]
Added code to the functions `do_item_action`, `do_path_action`, and `do_item_item_action` to check if all end conditions have been met before potentially declaring game over.

Tragically, the problem that I mentioned in my last comment does not seem to have fixed itself by me implementing code, so it looks like I actually have to address it. When I run `ctest --extra-verbose`, the following failures occur (copy-pasted from the terminal):

`1: [----] /home/ericyc16/cs/cmsc22000/chiventure/chiventure/tests/action_management/test_item_actions.c:249: Assertion failed: execute_do_item_action returned 0 for conditons not met, expected CONDITIONS_NOT_MET (4)`
`1: [FAIL] item_actions::conditons_not_met: (0.01s)`
`1: [----] /home/ericyc16/cs/cmsc22000/chiventure/chiventure/tests/action_management/test_item_item_actions.c:264: Assertion failed: execute_do_item_item_action returned 0 for conditons not met for direct item attribute, expected CONDITIONS_NOT_MET (4)`
`1: [FAIL] item_item_actions::conditons_not_met_direct: (0.01s)`
`1: [----] /home/ericyc16/cs/cmsc22000/chiventure/chiventure/tests/action_management/test_item_item_actions.c:280: Assertion failed: execute_do_item_item_action returned 0 for conditons not met for indirect item attribute, expected CONDITIONS_NOT_MET (4)`
`1: [FAIL] item_item_actions::conditons_not_met_indirect: (0.01s)`

This implies that passing in the context struct made it so that the functions believe all conditions are being met even when this is not actually the case. I will be working on finding a solution to this issue.

**Comment by ericyc16** [comment]
Added a line to `game_free` so that the `end_conditions` field is freed when freeing the game. That should be the last general update to chiventure code that I need to do to integrate end conditions. Now will work on the errors described in my last comment.

**Comment by ericyc16** [comment]
I tried changing the header of `do_item_action` to take a game instead of a context struct, and this seems to fix the problem with line 249 of `test_item_actions.c`, so I feel pretty safe in assuming that changing `do_item_item_action` would fix the other two errors. However, I would very much rather that parameter be a context struct, so I'm going to try to see if I can figure out what it is about it that's causing an issue.

**Comment by ericyc16** [comment]
I've also found that, in the `execute_do_item_item_action` function of `test_item_item_actions.c`, mallocing the context struct myself (rather than using `chiventure_ctx_new`) then using `game_new` to add a game to it gets rid of the error. However, this still doesn't explain to me why this error occurs, only that it somehow comes from creating a new context struct with `chiventure_ctx_new`.

**Comment by ericyc16** [comment]
Talked to @MaxineK36, and she and @ecoble looked over the code. According to Maxine, Elizabeth "was able to identify that it’s an issue with the return value of `add_action_condition` on line 54 of `test_item_action.c` ; the function seems to be returning `ACTION_NULL` in the case where the test fails." 

Upon further investigation, it seems like using `chiventure_ctx_new(NULL)` to malloc the context struct causes `add_action_condition` to return `ACTION_NULL` in both the `conditions_not_met` tests AND the `conditions_met` tests in both `test_item_actions.c` and `test_item_item_actions.c`. However, being unable to add a condition to an item does not change the results of the `conditions_met` tests, since an item with no conditions technically has met all conditions. Mallocing the context struct with `malloc(sizeof(chiventure_ctx))` instead causes `add_action_condition` to return the expected `SUCCESS` in all cases. 

Why this is happening is still unknown.

**Comment by ericyc16** [comment]
It seems like the problem is not originating in `add_action_condition` but instead exists right after using `get_action` to assign an action to `ga`. This seems to be happening in all tests, not just ones involving checking action conditions. However, it goes unnoticed in all other tests because only the action condition tests involve later searching through a hashtable for the action `ga`.

Right after assigning a value to `ga`, calls to `strcmp(ga->action_name, "dummy")`, `strcmp(ga->action_name, allowed_act_name)`, and `strcmp(ga->action_name, act_name)` all return 127. Again, this only happens when mallocing the context struct with `chiventure_ctx_new(NULL)`; mallocing with `malloc(sizeof(chiventure_ctx))` and then adding a game with `game_new` causes the `strcmp` calls to all return 0, as expected.

**Comment by ericyc16** [comment]
@MaxineK36 managed to find the source of the error - a line that closed a file deep in the UI module. We don't yet know why this line caused the error, so I will create a backlogged issue to determine why this error occurred. Now that all tests pass, I will create a pull request for the action-management/end-conditions branch.

**Comment by ericyc16** [comment]
Pull request #611 has been approved and merged, so I am closing this issue.

In summary, in this issue I accomplished the following:
- Added code to the functions `do_item_action`, `do_path_action`, and `do_item_item_action` to check if all end conditions have been met before potentially declaring game over
- Updated the headers of functions `do_item_action` and `do_item_item_action` to take a context struct
- Updated calls to calls to these functions in `operations.c`, `test_item_actions.c`, and `test_item_item_actions.c`
- Discovered and removed a bug where the UI's coordinate code caused some of the tests in `test_item_actions.c` and `test_item_item_actions.c`
- Merged this code with the dev branch

**Todo**:
- Develop a way for WDL/WDL++ to specify end conditions (a backlogged issue will be created to address this)
- Determine why the bug described above exists (see issue #612)

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Great work! This issue has a clear and specific title, and the updates throughout make the issue's progress very easy to follow.
The bulleted completed/todo lists in the closing statement are a great way to clearly lay out what's happened for anyone looking at this issue after its completion.

If you've created a backlog issue for wdl end conditions, you should also edit the closing statement to link to that.
