### ISSUE TITLE
Integrate a player class enum into the existing implementation of the NPC struct

### ISSUE THREAD

**Issue by anshikab** [uchicago-cs/chiventure#524]
The current implementation of the NPC struct does not include a feature for player class. An enum for player class indicating characteristics of an NPC in relation to a player needs to be created, and a feature for the player class to be included into the NPC struct. Complimentary additional functionality can be added (such as changing the class) as well. A sketch of the enum has been provided in this Wiki: 
https://github.com/uchicago-cs/chiventure/wiki/RPG-NPC:-Independent-Feature-Design-Document

**Comment by anshikab** [comment]
It has been decided that the player class will be stored in a struct instead of an enum. 

The rpg playerclass is in the process of finalizing and pushing code for the playerclass struct, which will be incorporated into the NPC struct in much the same way as the playerstats struct in the rpg-npc/struct-features branch.

**Comment by avianurag** [comment]
At this point, given the progress of both the NPC team and the Player Class team, it seems as though we will have to complete this issue in the next sprint.

**Comment by avianurag** [comment]
In accordance with the above update, we are moving this issue to Sprint 4.

**Comment by anshikab** [comment]
Update: Meeting 5/27 (via Zoom) 
I met with @simrenk from the playerclass team to discuss integration of the now complete playerclass struct into the NPC module.
- The playerclass struct will simply be included as a feature in the npc struct.
- The npc init, new and free functions will be modified to include the new feature.
- NPC tests will be updated accordingly.
- The playerclass struct includes the stats struct as a feature. This means that the stats struct will no longer need to be included as a separate feature in the npc struct and will, instead, be incorporated into the playerclass feature.

**Comment by anshikab** [comment]
I have created a new branch called rpg-npc/playerclass to implement these changes: https://github.com/uchicago-cs/chiventure/tree/rpg-npc/playerclass
I have pushed the necessary changes to npc.h and npc.c
The fields of functions is test_npc.c have been modified to take in NULL class_t structs as input. Tests need to be added to check correct initialization of non-empty class structs.

**Comment by anshikab** [comment]
Tests have been updated to test for correct creation and initialization of non NULL class_t struct inputs in npc_new and npc_init functions

**Comment by avianurag** [comment]
We have opened a pull request for this issue #700

**Comment by anshikab** [comment]
Closing remarks

Necessary changes to the npc module in order to accommodate the playerclass module have successfully been merged into dev through pull request #700 
The npc struct, npc related functions such as new and init, and tests have been updated to include the playerclass struct. 
The issue regarding duplicated stats structs in the npc struct was addressed and resolved in issue #699  

We are closing this issue.

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Good work!
