### ISSUE TITLE
Sandbox program (raylib) Command line input

### ISSUE THREAD

**Issue by ambikalv** [uchicago-cs/chiventure#526]
We are creating a sandbox program utilizing the graphics library in raylib to improve upon the current implementation of command line input. To this effect we hope to improve the user quality through better graphics and aesthetics for taking in command line input (as functionally, this currently exists in chiventure). We hope to be able to implement in this sandbox program, drawing text, an easy to find and use input box, a character counter with error messages, and mouse and text sensing

**Comment by ambikalv** [comment]
I had to install raylib on my personal computer in order to begin the sandbox program. I utilized this video to figure out how to set it up https://www.youtube.com/watch?v=JE7F7DLEjbo

**Comment by ambikalv** [comment]
I took the sample program that was given on their website to create a sample input page which would start a cursor once the mouse was placed over the input box as well as limit the number of characters a user could input
<img width="544" alt="Screen Shot 2020-05-11 at 10 42 32 AM" src="https://user-images.githubusercontent.com/46504083/81602806-3f557300-939b-11ea-976b-fa8f6a406575.png">

**Comment by ambikalv** [comment]
Overall I found the most difficult part just setting up raylib and making the tests run. Using their code as a model its fairly simple to customize and add extra effects and layers, and they give plenty of examples to get started/a cheatsheet to make the program customizable. Using this same model code it was easy to change the input chars or the colors and fonts on this page.

**Comment by ecoble** [comment]
Issue Score: ✔️+
Comments:
Great job! I liked that you included the reference you used to help set up. Be sure to convert the card to an issue right at the start of the sprint!
