### ISSUE TITLE
Begin implementation phase of skill trees.

### ISSUE THREAD

**Issue by VannStrasen** [uchicago-cs/chiventure#527]
After designing what our data strutures would look like, skilltrees needs to begin writing the code to hold skills. At the end of this sprint, the code will be saved onto a new branch of chiventure called 'skilltrees'. The end goal should be to fully write necessary structs for holding and creating skills, as well as designing structs for the skills themselves, and additional functions that allow for basic manipulation of skills like freeing, creating, testing if a skill is in a list, etc.

**Comment by VannStrasen** [comment]
I've upload the code I wrote to the skilltrees branch of chiventure. I am going to keep this issue open in case we want to continue working on this into sprint 3, and I will close it in case we want to create a new issue based off of the code I wrote.

**Comment by VannStrasen** [comment]
I initially wrote this code in a branch called 'skilltrees', which I realized was less descriptive than necessary, so I shifted the code over to skilltrees/skeleton_code. Because I also did not use the correct format for .c files and .h files (they were in a wrong folder), so the makefile was not formatted properly, so while it was compiling correctly on my makefile, I am not sure if it will compile correctly in the chiventure makefile because I haven't been able to work on that yet. As sprit #2 is ending now, I'm not issuing a pull request until the makefile is finished writing — that'll be work for the beginning of the next sprint.

**Comment by firatciftci** [comment]
Issue Score: ✔️+

Comments:
Good work! I like the extensive comments that you have above. The only thing I'll have to mention is that you should create a task mid-sprint the latest, and convert it from a scrum board item to an actual issue in 24 hours.
