### ISSUE TITLE
Identify necessary dependencies / interactions between skill-trees and WDL / battle teams

### ISSUE THREAD

**Issue by ly-chen** [uchicago-cs/chiventure#528]
To finalize the skill-tree design plan, we need to understand what the skill-tree design requires from WDL/WDL++ and/or the battle system design(s), and understand what these teams need from the skill-tree design.

**Comment by ly-chen** [comment]
After discussing our strategy with @firatciftci , we concluded that it would be better to put together a cohesive design document of how we plan to implement skill-trees first before collaborating with other teams in requesting and/or implementing our/their dependencies and interactions. Our design document is linked in #497 and can be used by other teams to conceptualize what they require from us; additionally, our design now opens the door for us to understand how we require other teams to structure their skill usage.

**Comment by firatciftci** [comment]
Issue Score: ✔️+

Comments:
Good work! I like the extensive comments that you have above. The only thing I'll have to mention is that you should create a task mid-sprint the latest, and convert it from a scrum board item to an actual issue in 24 hours.
