### ISSUE TITLE
Hard code 1 move per class for use in testing battle code

### ISSUE THREAD

**Issue by Purrsephone** [uchicago-cs/chiventure#530]
This week I will further develop and improve our existing move struct. Then I will hard code 1 move per player class. Moves will include descriptions of the move and the effect that the move has. This might also involve writing some helper functions for modules that use moves.

**Comment by Purrsephone** [comment]
Submitted a pull request that accomplishes the items described above.

**Comment by Purrsephone** [comment]
I have submitted a pull request that includes 1 hard coded move per class. These moves will be useful as we try to implement complete battle flow code in the coming sprint. I will make the requested changes to the PR for this issue as they come in, but since the PR is a separate issue, I am closing this issue.

**Comment by dwahme** [comment]
Issue Score: ✔️+

Comments:
Great job! Here are a few things you may want to improve in future issues:

Status updates on an issue should have something tangible to share- specifically, adding links to relevant pull requests.
