### ISSUE TITLE
Implement mock class system for use in testing battle code

### ISSUE THREAD

**Issue by Purrsephone** [uchicago-cs/chiventure#531]
This week I will need to implement a mock player class system for use in testing battle code. This will involve developing the player class struct, and then hard coding dummy player classes. Completing this issue will also help me as I code dummy moves.

**Comment by Purrsephone** [comment]
Committed code in the branch battle/battle-system. Moves.c contains init_class and new_class functions.  Main uses these functions to create 4 test class structs—one for each class. Moves.h has the function declarations. And structs.h has been updated with additional structs I used.

**Comment by Purrsephone** [comment]
Submitted a pull request that accomplishes the items described above.

**Comment by Purrsephone** [comment]
I have submitted a pull request that includes a mock class system. This class system will be useful as we try to implement complete battle flow code in the coming sprint. I will make the requested changes to the PR for this issue as they come in, but since the PR is a separate issue, I am closing this issue.

**Comment by dwahme** [comment]
Issue Score: ✔️+

Comments:
Great job! Here are a few things you may want to improve in future issues:

Status updates on an issue should have something tangible to share- specifically, adding links to relevant pull requests.
