### ISSUE TITLE
Produce .wdz games to test with parsing and import

### ISSUE THREAD

**Issue by namanhd1nh** [uchicago-cs/chiventure#536]
As part of the new spec, we need to produce example games in the new .wdz format. These will first be used to test our own parsing and importing (into object structs), and in later sprints can be modified to incorporate and test other teams' features.

Apart from being able to produce games that libzip can read, we also need to figure out a way to do so quickly and correctly (barring writing a full-blown WDL++ game creation program (however this is definitely still among the options worth considering!)).

**Comment by namanhd1nh** [comment]
I've written a shell script that automates the tasks of creating the .wdz directory structure, initializing skeleton JSON files, and zipping everything into a .wdz file. The script also handles updating an existing .wdz archive with new content from the corresponding folder, which will be used by authors to update the .wdz as they author their game.
I will figure out with the team and the senior developer on how to include it on the chiventure repository or provide it to other teams for everyone's use.

**Comment by namanhd1nh** [comment]
Update: the aforemention wdz script is now up in the repo in the branch "wdl/wdz_archive_test". (This branch will also be used for testing with libzip).

The script and its readme can be found here: https://github.com/uchicago-cs/chiventure/tree/wdl/wdz_archive_test/src/wdl/sandbox.

As of now, the member in charge of zip file handling has not gotten to it yet, so I will keep this issue open, and will be writing a test game using this wdz script workflow in the meantime. This test game will be adapted to other teams later on in later issues if needed.

**Comment by namanhd1nh** [comment]
I've written a complete test game (folder + wdz archive), found on https://github.com/uchicago-cs/chiventure/tree/wdl/wdz_archive_test/src/wdl/sandbox. This game lays down the basis of how the WDL++ JSON spec will work for many features existing from old WDL, as well as productive use of the new custom action sequences to define in-game interactions. Covering *most* chiventure features except the RPG ones, the game should provide a concrete target for development in Sprint 4 and later quarters to work towards and check feature coverage with.

**Comment by namanhd1nh** [comment]
The test game and shell script have been merged into the dev branch (see PR #630), and the files will now be in src/wdl/sandbox serving as reference tools for developers and authors to quickly prototype games in the new format. As such, this issue can now be closed.

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Great work! This issue is consistently clear, precise, and easy to follow.
