### ISSUE TITLE
Implementation of step by step battle flow with Battle Flow module specifications

### ISSUE THREAD

**Issue by celiaanderson** [uchicago-cs/chiventure#537]
Currently, there is some code in the sandbox for implementing a step by step runtime battle flow. However, given the updated four-module design, we would like to flesh out battle flow code to fit the specifications of the new Battle Flow module and separate battle flow functions from logic functions. This new implementation would add functions like player_move from the design document that follow a general REPL framework. Since a fully fleshed out implementation of the Battle Flow module, given that it is the highest level module in the design, would rely on the rest of design's implementation, this initial implementation would be subject to change and might have some substitutions for other module functions.

**Comment by celiaanderson** [comment]
I created a new branch to work with making the overall battle flow step by step loop, which is the branch battle/battle-loop. I've added in some comments in start_battle() to lay out what the overall procedure might look like within a battle loop, as the loop will be within start_battle(). After setting up the battle (as laid out in task #534), there will be a loop that runs until the battle is over, using a function from battle logic. Depending on whose turn it is as specified in the battle_t struct, the player/enemy will complete a move, which includes being prompted for the move (if it's the player), checking that the move and target are viable, evaluating the effects of the move for stats, and returning a message about the results of the move. If the battle is over, there will be a message about the end of the battle, the player could gain xp, and battle structs will be freed. One main to-do is to figure out the message system and how it will work with chiventure print functions outside of battle systems. 
I am planning on incorporating the functions from other battle modules, which can be tested after I can merge those modules into this branch. I will also change the set up for whose turn it is at the beginning of the battle with the function in battle logic that determines who goes first by the speed of the combatant. To test battle flow, in addition to merging with other battle modules, the stubs will also likely have to be modified, like item_t and player_t, so that I can include more chiventure functions outside of the battle system.

**Comment by celiaanderson** [comment]
Closing this issue - this issue is no longer relevant. This task was working under the impression that the entire battle would be self-contained within a step by step loop. Now that we have logic, battle state, and AI modules, for the next sprint, we will break the work up of running the battle flow by connecting to action management and message printing.

**Comment by dwahme** [comment]
Issue Score: ✔️++

Comments:
Great job! Well done recognizing how changing requirements affect your work and prioritizing accordingly.
