### ISSUE TITLE
Implement and create a context struct for the generation algorithm

### ISSUE THREAD

**Issue by edward3-uchi** [uchicago-cs/chiventure#538]
This context struct will hold the information necessary for autogenerating rooms. As of right now, it will hold just a few things: 1. int level (mock for player-stats) 2. room generation info 3. npc generation info. Later this will hold more info like a linked list of open rooms to be generated and previously generated rooms.

**Comment by edward3-uchi** [comment]
After meeting today, there have been quite a few changes to the structs for the generation algorithm. First, the context struct (gencontext_t) will contain the following fields: 
 - path_t *path: the given path that we need to connect our room to. 
 - int level: the level of the player which automates the level of the generated room
 - int openpaths: the number of open paths that should be generated into the new room
 - int numnpcs: the number of npcs that should be generated into the new room
 - speclist_t *list: a list of roomspec_t. roomspec_t holds the necessary specifications for making a new room. 

Second, the roomspec_t struct holds the values necessary for making a new room and looks  like this: 
 - char *short_desc: holds the short description for a room. 
 - char *long_desc: holds the long description for a room.
 - item_hash_t *items: the items in the room
 - pash_hash_t *paths: the paths connected from the room.

All of the roomspect_t's that will live inside a speclist_t will need to be hardcoded.

Lastly, the speclist_t struct will contain the following fields: 
 - llist *speclist;
 
 this linked list will contain all of the hardcode roomspec_t's

**Comment by bryan22lee** [comment]
Renamed sample_generation.h and sample_generation.c to [autogeneration.h](https://github.com/uchicago-cs/chiventure/blob/openworld/sample-generation/include/openworld/autogenerate.h) and [autogeneration.c](https://github.com/uchicago-cs/chiventure/blob/openworld/sample-generation/src/openworld/src/autogenerate.c) and moved the source code to the [src/openworld/src/](https://github.com/uchicago-cs/chiventure/tree/openworld/sample-generation/src/openworld/src) directory. This module uses the context structs defined in [gen_structs.h](https://github.com/uchicago-cs/chiventure/blob/openworld/sample-generation/include/openworld/gen_structs.h) by @edward3-uchi to determine if a game's current room has any paths and if not, generates and adds a generated room (from the context struct) to the game.

**Comment by bryan22lee** [comment]
See [test_autogenerate.c](https://github.com/uchicago-cs/chiventure/blob/openworld/sample-generation/tests/openworld/test_autogenerate.c) to see the tests for the functions that manipulate the structs defined in [gen_structs.h](https://github.com/uchicago-cs/chiventure/blob/openworld/sample-generation/include/openworld/gen_structs.h) by @edward3-uchi to create and add a desired room to a game. Work in progress.

**Comment by edward3-uchi** [comment]
Pull Request was made and updated. The final speclist_t struct was changed to contain double linked list functionality and synonymously updated to be defined as the rest. 

typedef struct speclist{
  roomspec *spec;
  struct speclist *prev;
  struct speclist *next;
} speclist_t;

**Comment by edward3-uchi** [comment]
Pull Request was approved this past weekend. Genstructs underwent many changes throughout this sprint. The gencontext struct now looks like this:

typedef struct gencontext {
    path_t *open_paths;
    int num_open_paths;
    int level;
    speclist_t *speclist;
} gencontext_t;

roomspec changed as well:

typedef struct roomspec {
    char *short_desc;
    char *long_desc;
    item_hash_t *items;
} roomspec_t;

These new changes remove definitions that won't be of use anymore. In the future, gencontext and roomspec may be subject to change. The new NPC pull request found [here](https://github.com/uchicago-cs/chiventure/pull/639) is visualizing some of those future changes from the NPC teams once we implement there code into our generation module.

**Comment by dwahme** [comment]
Issue Score: ✔️+

Comments:
Great job! Here are a few things you may want to improve in future issues:

An issue should have the goal of producing something tangible, such as code or documentation, which must be specified in the summary, not just the title.
