### ISSUE TITLE
Implement a single-room autogeneration module

### ISSUE THREAD

**Issue by bryan22lee** [uchicago-cs/chiventure#543]
Implement a single-room autogeneration module that randomly pulls from a group of [hard-coded rooms](https://github.com/uchicago-cs/chiventure/blob/openworld/sample-generation/include/openworld/sample_rooms.h) and adds this room to a given game when a new room is entered. Should handle (1) adding the room to the list of rooms in a game and (2) creating/adding a path that connects the new room to the current room. Incorporate into [sample_generation.c](https://github.com/uchicago-cs/chiventure/blob/openworld/sample-generation/src/openworld/sample_generation/sample_generation.c). Correctly link the new room into Chiventure and provide unit tests.

**Comment by edward3-uchi** [comment]
Progress thus far on [sample_generation.c](https://github.com/uchicago-cs/chiventure/blob/openworld/sample-generation/src/openworld/sample_generation/sample_generation.c): Implemented (1) from the description. We were able to figure out how to add the room to a game. Then, we ran into some problems with figuring out how to properly test the changes. We just need to properly code a CMake file in our [tests](https://github.com/uchicago-cs/chiventure/tree/openworld/sample-generation/tests/openworld) directory. We also were able to solve (2) which was adding a path to the previous room to the current room. @bryan22lee did this by using the func enter_new_room to check whether the games curr_room has the same hash id as the given room. You can find that func in [sample_generation.c](https://github.com/uchicago-cs/chiventure/blob/openworld/sample-generation/src/openworld/sample_generation/sample_generation.c) as well.

**Comment by CCalderon01** [comment]
Commit: 5f2df53 (found in openworld/sample-generation branch)
I wrote a generate_room function that returns a "random" new room from all hard-coded options available. I used the rand() function available in C to generate a random number from  0 to INT_MAX. Then I took this number (mod #of hardcoded rooms) to get a number from 0 to (#hard-coded rooms - 1) which correspond a different entry in the enumerated type room_tag. Finally, I return a new room with the room tag that I just generated.
My teammate can now use this functionality to test adding "random" rooms to the game.

**Comment by edward3-uchi** [comment]
Renamed all of the "sample_" files to not include the sample anymore. As we transitioned the code to newer files, we are changing some of the implementation and how it will work with the new openworld structs. For example, enter_new_room is no longer in use since a room is now generated based on a given path that points to one room but not to another room.

**Comment by bryan22lee** [comment]
Tests for this issue are further detailed in issue #602 . Renamed sample_generation.h and sample_generation.c to [autogeneration.h](https://github.com/uchicago-cs/chiventure/blob/openworld/sample-generation/include/openworld/autogenerate.h) and [autogeneration.c](https://github.com/uchicago-cs/chiventure/blob/openworld/sample-generation/src/openworld/src/autogenerate.c) and moved the source code to the [src/openworld/src/](https://github.com/uchicago-cs/chiventure/tree/openworld/sample-generation/src/openworld/src) directory. Redefined the functions in this module to work with the context structs defined in [gen_structs.h](https://github.com/uchicago-cs/chiventure/blob/openworld/sample-generation/include/openworld/gen_structs.h) by @edward3-uchi . Uses context structs to generate and add a new room to a given game. Compiles so far and any_paths function passes tests. Next step is to test the other functions in [autogeneration.h](https://github.com/uchicago-cs/chiventure/blob/openworld/sample-generation/include/openworld/autogenerate.h) to make sure they interact correctly with the context structs.

**Comment by bryan22lee** [comment]
New branch called [openworld/autogen](https://github.com/uchicago-cs/chiventure/tree/openworld/autogen) was opened, where the following can be found. Wrote a [CMakeLists.txt](https://github.com/uchicago-cs/chiventure/blob/openworld/autogen/tests/openworld/CMakeLists.txt) file for [test_autogenerate.c](https://github.com/uchicago-cs/chiventure/blob/openworld/autogen/tests/openworld/test_autogenerate.c) testing in [tests/openworld/](https://github.com/uchicago-cs/chiventure/tree/openworld/autogen/tests/openworld) directory. Dependency issues for [gen_structs](https://github.com/uchicago-cs/chiventure/blob/openworld/autogen/include/openworld/gen_structs.h) exists, but waiting for PR approval of gen_structs module and pulling dependencies thereafter should fix this problem. Otherwise, will request access to the [gen_structs](https://github.com/uchicago-cs/chiventure/blob/openworld/autogen/include/openworld/gen_structs.h) source code so I can finish the tests in [test_autogenerate.c](https://github.com/uchicago-cs/chiventure/blob/openworld/autogen/tests/openworld/test_autogenerate.c).

**Comment by bryan22lee** [comment]
Progress on the [autogenerate module](https://github.com/uchicago-cs/chiventure/blob/openworld/autogen/include/openworld/autogenerate.h) thus far: still working off of the [openworld/autogen](https://github.com/uchicago-cs/chiventure/tree/openworld/autogen) branch for this module. Completed implementation for single-room autogeneration, using a context struct, in [autogenerate.c](https://github.com/uchicago-cs/chiventure/blob/openworld/autogen/src/openworld/src/autogenerate.c). Wrote all tests for this module in [test_autogenerate.c](https://github.com/uchicago-cs/chiventure/blob/openworld/autogen/tests/openworld/test_autogenerate.c), fixed compiling issues, and got them all to pass. Ready for a pull request at this point, but waiting on the status of the [gen_structs](https://github.com/uchicago-cs/chiventure/blob/openworld/autogen/include/openworld/gen_structs.h) [pull request](https://github.com/uchicago-cs/chiventure/pull/617) since autogeneration heavily depends on this module. After feedback from Dawson, speclist_t was restructured to be a doubly linked list (in [gen_structs.h](https://github.com/uchicago-cs/chiventure/blob/openworld/autogen/include/openworld/gen_structs.h)) in order to add support from [uthash.h](https://github.com/uchicago-cs/chiventure/blob/openworld/autogen/include/common/uthash.h). Other stylistic and variable name changes were made as well to [gen_structs.h](https://github.com/uchicago-cs/chiventure/blob/openworld/autogen/include/openworld/gen_structs.h) in order to improve readability. See [this commit](https://github.com/uchicago-cs/chiventure/commit/6f8b7c2d9ee08c1596535359af1a1cd23de3ae22) to see these major changes and lines 106-120 in [gen_structs.c](https://github.com/uchicago-cs/chiventure/blob/openworld/autogen/src/openworld/src/gen_structs.c) to see how uthash was used.

**Comment by bryan22lee** [comment]
A [gen_structs.h](https://github.com/uchicago-cs/chiventure/blob/openworld/gen-structs/include/openworld/gen_structs.h) module made ready, which defines context structs to feed into the [autogeneration.h](https://github.com/uchicago-cs/chiventure/blob/openworld/autogen/include/openworld/autogenerate.h) module to generate a room and connect it to the current room by allocating a new path. Specifically, this should happen when the current room of the game is a "dead end" (i.e. there are no outward paths from the current room). A [pull request](https://github.com/uchicago-cs/chiventure/pull/617) was made for the [gen_structs.h](https://github.com/uchicago-cs/chiventure/blob/openworld/gen-structs/include/openworld/gen_structs.h) module, and I updated the [autogenerate](https://github.com/uchicago-cs/chiventure/blob/openworld/autogen/include/openworld/autogenerate.h) module to incorporate these changes and compile / run tests successfully. One thing we need to look into going into sprint 4 is correctly using [uthash.h](https://github.com/uchicago-cs/chiventure/blob/master/include/common/uthash.h) functions such as DL_APPEND() with our doubly linked list structure for speclist_t in [gen_structs.h](https://github.com/uchicago-cs/chiventure/blob/openworld/gen-structs/include/openworld/gen_structs.h) module, which defines context structs to feed into the [autogeneration.h](https://github.com/uchicago-cs/chiventure/blob/openworld/autogen/include/openworld/autogenerate.h). For now, linked list appending was done manually in [test_autogenerate.c](https://github.com/uchicago-cs/chiventure/blob/openworld/autogen/tests/openworld/test_autogenerate.c) to successfully compile, and pass the tests. We want to restructure speclist_t to incorporate [uthash.h](https://github.com/uchicago-cs/chiventure/blob/master/include/common/uthash.h) correctly and ensure proper usage of doubly linked lists (speclist_t). In sprint 4, the early goals are to include [uthash.h](https://github.com/uchicago-cs/chiventure/blob/master/include/common/uthash.h) in this way and make a PR for the [autogenerate.h](https://github.com/uchicago-cs/chiventure/tree/openworld/autogen/include) module. Later in sprint 4, we want to merge the [autogenerate.h](https://github.com/uchicago-cs/chiventure/tree/openworld/autogen/include)/[gen_structs.h](https://github.com/uchicago-cs/chiventure/blob/openworld/gen-structs/include/openworld/gen_structs.h) modules with [default_rooms.h](https://github.com/uchicago-cs/chiventure/blob/openworld/sample-generation/include/openworld/default_rooms.h)/[default_items.h](https://github.com/uchicago-cs/chiventure/blob/openworld/sample-generation/include/openworld/default_items.h) and [sample_npc.h](https://github.com/uchicago-cs/chiventure/blob/openworld/sample-generation/include/openworld/sample_npc.h) for specifying room generation. Further, we want to work on generating multiple rooms, i.e. a "wing".

**Comment by dwahme** [comment]
Issue Score: ✔️++

Comments:
Great job! Well done providing incremental updates and linking to tangible work done.
