### ISSUE TITLE
Outline game-state dependencies for openworld single-room autogeneration

### ISSUE THREAD

**Issue by bryan22lee** [uchicago-cs/chiventure#544]
We want to clearly define and outline dependencies from [game-state/](https://github.com/uchicago-cs/chiventure/tree/master/include/game-state) modules for our hard-coded mock structs ([sample_rooms.h](https://github.com/uchicago-cs/chiventure/blob/openworld/sample-generation/include/openworld/sample_rooms.h), [sample_items.h](https://github.com/uchicago-cs/chiventure/blob/openworld/sample-generation/include/openworld/sample_items.h)) and for our high-level [sample_generation](https://github.com/uchicago-cs/chiventure/blob/openworld/sample-generation/include/openworld/sample_generation.h) module. Clearly document these dependencies and address compilation issues in [sample_generation.c](https://github.com/uchicago-cs/chiventure/blob/openworld/sample-generation/src/openworld/sample_generation/sample_generation.c).

**Comment by bryan22lee** [comment]
First draft of the [dependency document](https://github.com/uchicago-cs/chiventure/wiki/Open-world:-Single-Room-Generation-Module-Design) made a as a wiki page, called "_[Open world: Single Room Generation Module Design](https://github.com/uchicago-cs/chiventure/wiki/Open-world:-Single-Room-Generation-Module-Design)_". So far, it outlines all dependencies for our [single-room sample-generation](https://github.com/uchicago-cs/chiventure/tree/openworld/sample-generation/src/openworld/sample_generation) project, as well as their hierarchy in terms of module hierarchy. Future drafts will include functions we will use _from_ these dependencies and pseudo-code on how we may implement this single-room addition feature.

**Comment by bryan22lee** [comment]
Second draft of the [dependency document](https://github.com/uchicago-cs/chiventure/wiki/Open-world:-Single-Room-Generation-Module-Design), "_[Open world: Single Room Generation Module Design](https://github.com/uchicago-cs/chiventure/wiki/Open-world:-Single-Room-Generation-Module-Design)_". Added specific functions from the previously-outlined dependencies that may be used in single-room autogeneration implementation. Further, I wrote pseudo-code for a possible way to implement this in [sample_generation.c](https://github.com/uchicago-cs/chiventure/blob/openworld/sample-generation/src/openworld/sample_generation/sample_generation.c). Visit the [document](https://github.com/uchicago-cs/chiventure/wiki/Open-world:-Single-Room-Generation-Module-Design) to see all changes.

**Comment by bryan22lee** [comment]
_[Open world: Single Room Generation Module Design](https://github.com/uchicago-cs/chiventure/wiki/Open-world:-Single-Room-Generation-Module-Design)_ document was added to the wiki. It clearly outlines all dependencies for our [sample_generation.h](https://github.com/uchicago-cs/chiventure/blob/openworld/sample-generation/include/openworld/sample_generation.h) module. Furthermore, it lists functions we may use in our [single-room autogeneration](https://github.com/uchicago-cs/chiventure/tree/openworld/sample-generation/src/openworld/sample_generation) implementation and their dependencies. Finally, it gives example pseudo-code as a possible way to implement this functionality. This dependency outline helped to resolve dependency/compiling issues in [sample_generation.h](https://github.com/uchicago-cs/chiventure/blob/openworld/sample-generation/include/openworld/sample_generation.h) and [sample_generation.c](https://github.com/uchicago-cs/chiventure/blob/openworld/sample-generation/src/openworld/sample_generation/sample_generation.c).

**Comment by dwahme** [comment]
Issue Score: ✔️++

Comments:
Great job! Well done providing links to tangible work that you completed.
