### ISSUE TITLE
Implementation of required functions and structs for the AI Module

### ISSUE THREAD

**Issue by nmartinez233** [uchicago-cs/chiventure#546]
I will create a basic AI that can be called to produce a move to be used by the enemy and may vary depending on difficulty. In order to do this, I will mostly hardcode functions that will return move. Implementing this will help out our group simulate an actual battle.

**Comment by nmartinez233** [comment]
Yesterday I created AI.c and AI.h files that include all of the necessary functions and implementations with the exception of 2 functions. I left find_easy and find_hard empty as I am consulting with my team to determine how we are going to calculate damage. Today, I am also in the process of consulting with rpg-playerstats to see if there is a system for calculating levels (used in the damage formula). Once I have these questions regarding the damage formula cleared up, I will finish the implementation of the 2 functions.

**Comment by nmartinez233** [comment]
After consulting with team-rpg-playerstats, we concluded that the system to calculate levels, while relevant, isn't an issue that is in our team's responsibility to solve. However, we did agree on adding an `unsigned int level` field to the player stats struct. I then relayed that info to my team, added the field, and I finished off the 2 functions necessary to complete the AI Module.

**Comment by nmartinez233** [comment]
With some changes to a couple of battle structs, I need to refactor some of the code & make the damage calculating function more universal. Once that is complete (along with some tests) I hope to make a pull request soon!

**Comment by nmartinez233** [comment]
A bit of integration hell has taken place over the past week - since my module is highly dependent on the battle structs and battle functions (like combatant_new and new_move, etc.) there have been small hiccups along the way. I've spent most of this past week refactoring much of my code after other teammates get their pull requests approved. Once the final necessary functions are created, I will finally be able to continue with the process of testing my code and submit for review. This is taking longer than expected due to the continuously changing structs, but after meeting today with teammates I am confident they won't change anymore.

**Comment by nmartinez233** [comment]
I was able to finish creating the AI module, its required functions and structs. It is composed of a give_move function which depending on the enum input to the function will return a move (either "greedy" (most damage) or "random" (random move)). The pull request linked with this will be closed shortly.

**Comment by dwahme** [comment]
Issue Score: ✔️++

Comments:
Great job! Well done keeping the issue updated as you ran into challenges.
