### ISSUE TITLE
Implement basic struct functions for custom-actions structs

### ISSUE THREAD

**Issue by emmamedeiros** [uchicago-cs/chiventure#547]
Create implementations for the new, init, and free functions for the custom-actions struct as outlined in the struct.h/struct.c files created during Sprint 2. During this process, the "new" functions for the structs should be updated to return a pointer value. Tests will also need to be created for these functions .

**Comment by emmamedeiros** [comment]
Basic struct "new" functions have been updated to return pointers to the structs. Additionally, attribute structs and the "attribute_free" function have been removed and the files now #include "item.h" attribute structs to prevent repetitiveness.

**Comment by emmamedeiros** [comment]
Files have now been reorganized, so that each block type has its own .h and .c file, with one struct.h file remaining to contain all of the structs. The first two block types have been implemented and are currently undergoing testing processes.

**Comment by emmamedeiros** [comment]
The files have been further reorganized and condensed, as well as moved into different directories in order to make their functionality less available to non-custom-actions implementation. The implementation and tests for the other four files have also been committed. Working on commits to debug and ensure code is working properly before running the tests and beginning to submit pull requests.

**Comment by emmamedeiros** [comment]
At this stage, we have decided that we are going to update our block structs, removing a pointer to an AST_block_t in other block structs where it previously existed. We will instead be added a pointer to an AST_block_t within the AST_block_t struct, which will allow for more streamlined user capability as Chiventure creates these AST_blocks. Because of this, we will be closing this issue and creating new issues as a result of this change to our implementation.

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Great work! This issue is clear and easy to understand, and the closing statement provides a clean explanation of why the issue is being closed. In the future, when new issues spawn of old ones, it's also helpful to link them to one another (for example, at the end of this issue you would include the issue numbers of the new ones you spawned, and then the newly spawned issues can reference this one)
