### ISSUE TITLE
Write sandbox code using uthash

### ISSUE THREAD

**Issue by ela-ine** [uchicago-cs/chiventure#548]
Explore the different functionalities/capabilities of uthash and write some sandbox code to test it out. This is in preparation for [Issue #549](https://github.com/uchicago-cs/chiventure/issues/549), where I will try to implement a hash table to store objects after parsing WDL++.

**Comment by ela-ine** [comment]
Opened up a branch ([wdl/uthash-sandbox](https://github.com/uchicago-cs/chiventure/tree/wdl/uthash-sandbox)) and wrote some basic hash functions to get a feel for how uthash works.

**Comment by ela-ine** [comment]
Wrote (and debugged) some more add/print/find functions using a struct as key

**Comment by ela-ine** [comment]
This sandbox includes: two hash table structs (one using a string key, another using a a cmpkey_t struct as key), functions to add, query, search, and free both structs, and a few simple tests to make sure everything is (more or less) working.
This increased familiarity with uthash will be helpful in designing the hash table for the object store.

**Comment by MaxineK36** [comment]
Issue Score: ✔️+

Comments:
Great work! This issue includes useful and tangible updates that make it easy to follow. One area for improvement: the title is fairly generic; many teams are using uthash and thus writing sandbox uthash code, so it would have been helpful to specify what the code would eventually be used for once it moved out of the sandbox.
For example: "Write sandbox code using uthash in preparation for hashing parsed wdz objects"
