### ISSUE TITLE
Implement hash for accessing objects in WDL++

### ISSUE THREAD

**Issue by ela-ine** [uchicago-cs/chiventure#549]
Using uthash, create a hash table for storing objects from WDL++, such that other teams are able to access and deal with the objects they need.

**Comment by ela-ine** [comment]
Started working on branch wdl/libobj-hash (using definitions from sample_obj_documentation.h from branch [wdl/libobj-interface](https://github.com/uchicago-cs/chiventure/tree/wdl/libobj-interface)) and copied over altered hash struct as well as query functions from sandbox.

**Comment by ela-ine** [comment]
Defined struct objstore_t as the hash table storing objects. Added functions to init, add, find, and free items in an objstore hash table.

**Comment by ela-ine** [comment]
Working on tests using criterion — currently, 4/6 tests are crashing due to some unknown error.

**Comment by ela-ine** [comment]
@MaxineK36 helped me fix the errors! It was a simple malloc error. I've written 7 tests so far for all functions in objstore (new, find, add, free). No tests failed thus far.

**Comment by ela-ine** [comment]
Added free_all() function and wrote a few more tests. HASH_DEL seems to be triggering seg fault in free_objstore(), not sure why as of yet

**Comment by ela-ine** [comment]
All tests pass! Will be waiting on obj_t to be finalized.

**Comment by ela-ine** [comment]
`obj_t` finalized a few days ago, submitted PR

**Comment by ela-ine** [comment]
I wrote an objstore module that included documentation and implementation for a hash table of objects as well as functions to query that hash table. I also wrote a test file that explored multiple success/fail cases for all fucntions.

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Great work! The summary on this issue is particularly useful and concise.
