### ISSUE TITLE
Write sample code that implements specific npcs generating in rooms

### ISSUE THREAD

**Issue by philipchenaux** [uchicago-cs/chiventure#555]
This features follows the design document from issue #468 which included the following wiki: https://github.com/uchicago-cs/chiventure/wiki/RPG-NPC:-Independent-Feature-Design-Document outlining the npc-openworld features that we are planning on implementing. This issue addresses the first feature on the document addressing npc spawning/generating in rooms based on the npc's player-class. I plan on begin the implementation of this feature based off the design document referenced above.

**Comment by philipchenaux** [comment]
I have just received some feedback from the rpg open-world team regarding my current design plan. There was a minor changes to the open-world structs that I have included notably regarding the room struct. Below are the key details from the exchange with the open-world team:

> "I just want to clarify that the room struct you see in sample_rooms.h is actually taken from include/game-state/room.h."
> "The room struct has been modified in one (1) very important way for sample_rooms.h ... I added the enumerated room_tag_t type as another parameter. But other than that, it's really the same. If you look in my sample_rooms.c file you can see how I'm initializing these hard-coded rooms."
> "Just from off the top of my head I'm thinking these characters would be loaded into the appropriate rooms like items?"

**Comment by philipchenaux** [comment]
We have created a branch for this implementation labelled "rpg-npc/npc_room_management", and are commencing with working on creating data structures to store the npcs in each room. We are making refinements to our design and will be updating the changes accordingly on the following wiki:
https://github.com/uchicago-cs/chiventure/wiki/RPG-NPC:-Independent-Feature-Design-Document

**Comment by shayna-k** [comment]
We have created some initial skeleton code for a struct that will enable us to implement this feature. Incremental correspondence will take place to clearly establish the additions we will have to make to this. We also have a temporary design structure in place in the npc.h file in our branch "rpg-npc/npc_room_management". This will be formalized in detail in the wiki linked above.
Updates shall follow.

**Comment by philipchenaux** [comment]
We have completed the struct that we will be using, as well as implementing basic functions for this struct, namely new, init and free, as well as a function that adds an npc into our struct which stores the list of npcs inside a certain room. The tests were also written for the relevant functions. We revised our initial plan as stated on the wiki, below are the relevant changes:

> Each room is associated with a room_tag which specifies what type of room it is, similarly each npc has a enum that specifies their class npc_class. The first step would be to associate an npc_class with a room_tag (but note that an npc_class can be associate with several different room_tags). Therefore some struct and function similar to the following:
```C
/* Struct that contains all the npcs in a given room with room_id */
typedef struct npcs_in_room {
    /* hh is used for hashtable, as provided in uthash.h */
    UT_hash_handle hh;
    char *room_id;
    npc_hash_t *npc_list; //hash table storing the npcs that are in the room
} npcs_in_room_t;

typedef struct npcs_in_room npcs_in_room_hash_t;

/* Adds an npc to the given npcs_in_room
 *
 * Parameters:
 *  npcs_in_room_t: pointer to the npcs_in_room struct
 *  npc_t: pointer to an npc
 *
 * Returns:
 *  SUCCESS if successful, FAILURE if an error occured.
 */
int add_npc_to_room(npcs_in_room_t *npcs_in_room, npc_t *npc);
```
>The function above adds an npc into the struct created above that essentially contains all the npcs that exist in a room.  This needs to be then further integrated into the room struct where the room struct will hold this specific npcs_in_room struct for each room. This would therefore contain a list of npcs that exist in the room.

The next issue will be to discuss how we can integrate our struct into the rooms module as specified by the openworld team.

**Comment by philipchenaux** [comment]
We have just submitted the first pull request for this issue, #610 . We will not close this issue yet, however given that we are planning on further developing this issue by possibly working with the custom scripts team. We will also begin working on the second feature of implementing npc movement between rooms.

**Comment by philipchenaux** [comment]
The pull request for this issue #610 has been merged with the dev branch therefore we have completed the  initial stages of this feature. We will close this issue and now focus towards submitting a pull request for the second npc-room related feature #572 , that we will most likely work on in the next sprint.

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Amazing work!
