### ISSUE TITLE
Get raylib to work on CS environment

### ISSUE THREAD

**Issue by seanrryan** [uchicago-cs/chiventure#558]
In order to move forward with raylib as chiventure's graphics library, it needs to actually run on the same dev environment. That being said, the sooner the graphics team can get our progress over to CSIL computers as opposed to our personal computers, the better. This will involve learning how to set up the remote environment, and then being able to install and use the library properly. One thing that needs to be considered is the fact that raylib operates out of its own windows on the desktop, rather than through the terminal like SDL or chiventure on its own. This may pose an initial challenge but will ultimately open up more possibilities for chiventure in the future.

**Comment by seanrryan** [comment]
As of today, raylib has been successfully built on my VM. I encountered a few difficulties so I'm going to make a wiki post outlining the steps to installing and building on a VM.

**Comment by seanrryan** [comment]
[Wiki Post](https://github.com/uchicago-cs/chiventure/wiki/Graphics:-Installing-and-Building-raylib-on-a-VM)

Here's a first draft of the guide. I have tested this a couple of times on my own VM successfully, but I would definitely like feedback on the readability of the guide, as well as if there are any issues in terms of functionality. The last thing I want is for someone to mess up their dev environment because of unclear, misleading, or incorrect instructions I gave to them.

**Comment by seanrryan** [comment]
Some further comments:

Going forward, I expect some changes and tweaks to be made to the guide to help make it more useful and easy to follow.

The next step is to start modifying chiventure code so that raylib is formally recognized as a dependency of chiventure by modifying CMake files and making some other changes. Then, when chiventure starts to incorporate features from raylib the foundation is already set and there are no dependency issues. This will allow us to shift our focus to designing graphics modules and other visual components of chiventure.

**Comment by ecoble** [comment]
Issue Score: ✔️++
Comments:
Great job here, I think this guide will definitely be helpful in the future.
