### ISSUE TITLE
Revise skill tree implementation to allow for skill effect functions of variable arity

### ISSUE THREAD

**Issue by jackandthebean** [uchicago-cs/chiventure#559]
# Revise skill tree implementation to allow for skill effect functions of variable arity
### What
In Sprint 2, @VannStrasen began working on the implementation phase of our skill trees module, following from our research and multiple discussions on design. The resulting skill trees "skeleton" code stores a function pointer within our skill struct that determines the tangible effect of the skill – the function pointed to is the function that will be called on execution of the skill by the player. However, the function pointer currently takes two parameters, so we aim to make this function pointer more flexible by allowing for variable arity. We will be taking inspiration from the existing code for [actions](https://github.com/uchicago-cs/chiventure/blob/master/docs/actions.md) in chiventure, which currently support three different kinds:
* Kind 1: ACTION `<ITEM>`
* Kind 2: ACTION `<DIRECTION>`
* Kind 3: ACTION `<ITEM>` `<ITEM>`.
### Why
We would like to be able to support as diverse a range of skills as possible; supporting skill effect functions of variable arity will help render the skill trees module more flexible for chiventure game developers.

**Comment by jackandthebean** [comment]
After reviewing the code written so far, another thing we can implement for added skill flexibility is rendering the effects portion to be an *array* of function pointers, instead of just one function pointer, so that a skill can be, not only one, but a combination of functions written in other chiventure modules (e.g. inflict greater damage in battle *and* receive less damage, say).

**Comment by jackandthebean** [comment]
I did a lot more research regarding ways to make function pointers as flexible as possible:
1. One idea was to implement an array of function pointers (necessarily of a single type) and then store the index for the array element that corresponded to the skill effect within the skill struct, but I didn't like this idea, because it didn't really improve flexibility in any way.
2. Another idea was to implement a union of function pointers. I liked this idea more, because it would allow for many different kinds of function pointers (with variable arity and parameter/return types) to be options for the skill effect. For a while, I played around with this idea, in conjunction with the use of `enum` tags, to implement a sort of tagged union. I ultimately let this idea go as well, because it seemed redundant to store tags for each function pointer, if each skill would already have its own function and unique skill ID.
3. Another idea was to use `void*`, but this was not really a solution, because the function pointer would still need to be re-cast with the appropriate parameter and return types, before use.
4. Ultimately, I decided to create a single function pointer type to be used as a struct field in `skill_t`:
```
/*
 * Skill effect function type
 *
 * Parameters:
 *  - Contained within a string for function pointer uniformity. Each skill
 *    effect function can read the string for parameters using sscanf.
 *
 * Returns:
 *  - A string describing the consequence of the skill execution, for the CLI
 */
typedef char* (*effect_t)(char*);
```
This final decision was inspired by the existing `cmd` module as specified in the `cli/` directory of `include/`: specifically, its use of a typedef'd `operation` function pointer, for all command-line interface commands. The rationale to return a string (`char*`) was directly a result of reviewing the cli cmd code, as, after all, chiventure is a **text-adventure** game engine, so, once *any* skill effect has been executed, we would want a string return that describes the consequences of that skill execution. Additionally, while function pointers themselves are fairly rigid in C and provide no straightforward mechanism for variable arity, the C library function `sscanf` allows for simple reading of formatted input from a string and can be used to transform a single string argument into multiple arguments of varying data types. Essentially, the `effect_t` function pointer type describes a wrapper function type that each skill function would take the form of, and once `sscanf` has acquired the appropriate arguments, each skill wrapper can make the appropriate calls to other chiventure functions in other modules (e.g. battle systems, player classes, etc.).

**Comment by jackandthebean** [comment]
4. Ultimately, I decided to create a single function pointer type to be used as a struct field in `skill_t`:
```
/*
 * Skill effect function type
 *
 * Parameters:
 *  - Contained within a string for function pointer uniformity. Each skill
 *    effect function can read the string for parameters using sscanf.
 *
 * Returns:
 *  - A string describing the consequence of the skill execution, for the CLI
 */
typedef char* (*effect_t)(char*);
```
This final decision was inspired by the existing `cmd` module as specified in the `cli/` directory of `include/`: specifically, its use of a `typedef`'d `operation` function pointer, for all command-line interface commands.
```
/* Operation data type */
typedef char *operation(char *tokens[TOKEN_LIST_SIZE], chiventure_ctx_t *ctx);
```
The rationale to return a string (`char*`) was directly a result of reviewing the cli cmd code, as, after all, chiventure is a **text-adventure** game engine, so, once *any* skill effect has been executed, we would want a string return that describes the consequences of that skill execution. Additionally, while function pointers themselves are fairly rigid in C and provide no straightforward mechanism for variable arity, the C library function `sscanf` allows for simple reading of formatted input from a string and can be used to transform a single string argument into multiple arguments of varying data types. Essentially, the `effect_t` function pointer type describes a wrapper function type that each skill function would take the form of, and once `sscanf` has acquired the appropriate arguments, each skill wrapper can make the appropriate calls to other chiventure functions in other modules (e.g. battle systems, player classes, etc.).

**Comment by jackandthebean** [comment]
4. Ultimately, I decided to create a single function pointer type to be used as a struct field in `skill_t`:
```
/*
 * Skill effect function type
 *
 * Parameters:
 *  - Contained within a string for function pointer uniformity. Each skill
 *    effect function can read the string for parameters using sscanf.
 *
 * Returns:
 *  - A string describing the consequence of the skill execution, for the CLI
 */
typedef char* (*effect_t)(char*);
```
This final decision was inspired by the existing `cmd` module as specified in the `cli/` directory of `include/`: specifically, its use of a `typedef`'d `operation` function pointer, for all command-line interface commands.
```
/* Operation data type */
typedef char *operation(char *tokens[TOKEN_LIST_SIZE], chiventure_ctx_t *ctx);
```
The rationale to return a string (`char*`) was directly a result of reviewing the cli cmd code, as, after all, chiventure is a **text-adventure** game engine, so, once *any* skill effect has been executed, we would want a string return that describes the consequences of that skill execution. Additionally, while function pointers themselves are fairly rigid in C and provide no straightforward mechanism for variable arity, the C library function `sscanf` allows for simple reading of formatted input from a string and can be used to transform a single string argument into multiple arguments of varying data types. Essentially, the `effect_t` function pointer type describes a wrapper function type that each skill function would take the form of, and once `sscanf` has acquired the appropriate arguments, each skill wrapper can make the appropriate calls to other chiventure functions in other modules (e.g. battle systems, player classes, etc.).

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Great work!
