### ISSUE TITLE
Develop a skill tree mockup for a test room

### ISSUE THREAD

**Issue by jackandthebean** [uchicago-cs/chiventure#560]
# Develop a skill tree mockup for a test room
### What
Test our skill tree module implementation by developing a mockup that uses the functions we've written. For more extensive integration testing, use functions written by other RPG teams as skill effects.
### Why
Developing a mockup that uses our module, as well as the modules of other RPG teams, will be the best way to test the successes and downfalls of our implementation.

**Comment by jackandthebean** [comment]
I had envisioned somehow integrating our functions with the `action_management` functions and using a test room from the chiventure code to allow simple interaction with skills, but in the process of doing so, I realized the time would be better spent developing more criterion unit tests and implementing the general skill trees data structure, as we had only implemented the individual skills and player inventories structs. I am now closing this issue but have opened a new issue to do all of the above: #663.

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Good work on this issue!
