### ISSUE TITLE
Create predefined sample NPCs for the Algorithm generation

### ISSUE THREAD

**Issue by navila-luna** [uchicago-cs/chiventure#562]
Consists of making a room with descriptions of a character when entering a room and distinguishing a hostile vs  non-hostile character. Created three kinds of NPCs: Generic, Hostile, and Friendly. Made three NPCs per each NPC type and called them into the default_rooms.c. Included the npc_t struct within the spec_rooms struct and modified functions (in default_rooms.c, genstruct.h, and test_defaults.h) that utilize this spec_rooms. These NPCs are mocks and are hard coded, so test functions are not necessary. The purpose for these NPCs is to give OpenWorld an idea about how NPCs will look like when generating multiple rooms. This will be particularly more necessary for the next sprint when there's more focus on creating the sample_generation.

**Comment by navila-luna** [comment]
The process consists of looking into the WDL and NPC files already available.

**Comment by navila-luna** [comment]
I decided to use the item.c from game state as a model in creating these functions. I still need to figure out what introduce_npc should return and take in in its parameter. Same goes for ask_And_action(). 
Currently I have the following :
`#include <stdlib.h>
#include <stdio.h>
#include <string.h>
//#include "game-state/item.h"
//#include "game-state/game_action.h"
#include "sample_npc.h"

/* See samples_npc.h */
int npc_init(npc_t *new_player, char *player_id, char *short_desc,
              char *long_desc)
{
   // plyr->level = 1;
    assert(new_player != NULL);
    strcpy(new_player->npc_id, player_id);
    strcpy(new_player->npc_sdesc, short_desc);
    strcpy(new_player->npc_ldesc, long_desc);

    return SUCCESS;
}

/* See samples_npc.h */
npc_t* new_npc(char *npc_id, char *npc_ldesc, char *npc_sdesc, char *npc_qdesc)

{
    npc_t *new_player = malloc(sizeof(npc_t));
    memset(new_player, 0, sizeof(npc_t));
    new_player->npc_id = malloc(MAX_ID_LEN * sizeof(char)); // tentative size allocation
    new_player->short_desc = malloc(MAX_SDESC_LEN * sizeof(char));
    new_player->long_desc = malloc(MAX_LDESC_LEN * sizeof(char));
   // new_player->npc_qdesc = malloc(MAX_QDESC_LEN * sizeof(char));

    int check = npc_init(new_player, npc_id, short_desc, long_desc);

    if (new_player == NULL || new_player->npc_id == NULL ||
            new_player->short_desc == NULL || new_player->long_desc == NULL)
    {
        return NULL; //npc struct not properly malloced
    }
    if(check != SUCCESS)
    {
        return NULL;
    }
   
    return new_player;

}


/* See samples_npc.h */
npc_t* introduce_npc()
{
}

/* See samples_npc.h */
npc_t* ask_And_action()
{
}`

**Comment by navila-luna** [comment]
The process consisted of:

1) Writing the hardcoded functions
   - Considering what kinds of NPCs would be needed according to a certain field of room.
      For some inspiration, look at what NPC team is also considering in implementing. 

2) Implement the npc_t struct within the room_spec 
   - Reason: room-spec considers what is inside the room (items, descriptions of rooms, NPCs).

3) Modify functions including specrooms to consider the npc_t
  - for instance, the spec_room_new function that initializes a room with descriptions (of the room    and of items).

4) Modified tests
  - to consider the npc_t modification

**Comment by navila-luna** [comment]
To conclude, hard coded mock NPCs were created and put into the default rooms. The spec_room struct and functions including it were modified to consider the npc_t struct.

**Comment by dwahme** [comment]
Issue Score: ✔️+

Comments:
Great job! Here are a few things you may want to improve in future issues:

Even though you can add labels to issues to categorize them, you should avoid titles that could plausibly apply to multiple teams
