### ISSUE TITLE
Implementing do_lua_function for lua action type within action management module

### ISSUE THREAD

**Issue by tammytran134** [uchicago-cs/chiventure#564]
After talking with action management team, we decide that action management will have a new kind of action - lua action - on top of the current three action types. Custom script will be in charge of implementing functions related to lua actions in action management module, specifically, I'm responsible for implementing the do_lua_function that takes in lua file path as one of its parameters and execute the actions as specified by Lua.

**Comment by tammytran134** [comment]
We've come to learn that implementing a new Lua action would involve lots of structural change in the current Chiventure base code, and decide that we would look for a more realistic goal of incorporating custom script support in the current Chiventure code by writing up a custom script module that allows Lua scripting changes on individual types like int, bool, char in a given chiventure struct. We realize that for now, custom script should focus more on supporting game state changes within the current base code than allowing game authors to add new actions or features to the game. As such, we intend to create a new issue and close this issue.

**Comment by firatciftci** [comment]
Issue Score: ✔️+

Comments:
Great work! The only thing I'll point out is that the issue should have had more content in terms of updates on your progress; with just a summary and a closing comment, it is difficult to quantitatively and qualitatively measure the work that you have put in.
