### ISSUE TITLE
Implement an interface for the new WDL—this involves both designing & writing the data structures in which to store JSON objects and media assets pulled from .wdz files, and the functions to pull the data themselves.

### ISSUE THREAD

**Issue by noahklowden** [uchicago-cs/chiventure#565]
In order to implement the WDL++ system into Chiventure, we must design a data structure in which the game data is stored and functions to access these.

We must determine what sort of data structure we are to use to store this information (e.g. hash table) and what format we consider to be the most accessible for other teams to use their relevant data. This includes determining if we want to store information as JSON objects or if we are to use another form of object (e.g. the game object or the libobj objects currently in use).

We must design functions for taking the parsed .wdz file as JSON objects and storing it and for accessing this data. The goal is to create a system for storing accessing game data that allows for other sub-teams to make modifications to their systems without requiring a change in the WDL code.

**Comment by noahklowden** [comment]
We met with the rest of the team yesterday to discuss the design of the structures for the objects upon parsing.

Our plan is to rely on three structures: object_t, attribute_t, and asset_t. These are for top level objects, the attributes of these objects, and sound/image files respectively. We found that our object_t and attribute_t designs are remarkably similar to the base design in the current libobj and action_management code. We need to read more into this code, particularly libobj, to decide how much we want. We also will want to speak to Maxine and other teams about how attributes are to be represented.

Very importantly, we want to speak with Borja/the TAs to discuss the relationship between WDL++ and the game state, as by updating WDL there will need to be modifications to transitions between WDL to game objects.

**Comment by noahklowden** [comment]
I created a [branch](https://github.com/uchicago-cs/chiventure/tree/wdl/libobj-interface/src/libobj/sandbox) for writing up the design and eventual implementation of the new objects for after parsing. To begin, we have a sandbox directory in src/libobj for writing up the test code. 

@blakemoss wrote up a [sample documentation](https://github.com/uchicago-cs/chiventure/blob/wdl/libobj-interface/src/libobj/sandbox/sample_obj_documentation.h) for what the new object system will look like, which I then modified. It currently is set up with 3 structs: object_t, which designates what type of thing the object is (such as a player or action); attribute_t, which contains the actual data associated with the object; and asset_t, which wraps image and sound files.

**Comment by noahklowden** [comment]
We created sample documentation for how the parsed objects will be stored based on libobj located [here](https://github.com/uchicago-cs/chiventure/blob/wdl/libobj-interface/src/libobj/sandbox/sample_obj_documentation.h) and created [a branch](https://github.com/uchicago-cs/chiventure/tree/wdl/libobj-interface) for this interface.

This object works similarly to the old libobj, but instead is built around objects that contain attributes. Each object stores a certain type of category of information (player, room, item, etc.) that are contained in a hashtable of attributes. These attributes can store booleans, ints, chars, strings, arrays of strings, and pointers to other objects.

**Comment by noahklowden** [comment]
Moving into sprint 4, this issue is being closed in order that this task may be broken down into smaller issues. These are: 
1. finalize the interface for the libobj structs (#685) 
2. create and implement the low level interface to access the objects and attributes (#687)
3. create and implement the higher level interface to access object attributes for other teams to use (#686)
4. Write up documentation on how to use the higher level interface (#688)
5. Implement the finalized interface for creating the game_t object and use to create example code (#689)

Thus, this issue will officially be closed without a pull request. #685 should contain the first pull request to be associated with the implementation of the new inteface.

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Great job! This is an excellent example of a well-documented issue that was broken up into multiple new issues.
