### ISSUE TITLE
Link Stats struct to NPCs module.

### ISSUE THREAD

**Issue by carlosazpurua1004** [uchicago-cs/chiventure#566]
In the current implemnation of stats, we associated particular stats and their values with a player by putting the stats struct as a field in player struct. We probably need to do something similar with NPCs.

The final result will probably be a pull request that updates NPC's code to contain our struct, updates relavent functions if necessary, and adds an assign_stats_npc function, assigning stats to NPCs.

**Comment by carlosazpurua1004** [comment]
Met with a team member from RPG-npc's today, who said they would reach out to the NPC's team, who are the ones that actually designed the NPC struct.

**Comment by carlosazpurua1004** [comment]
Met with the team emeber of NPC that wrote the NPC struct, they gave me the go ahead to modify the struct as necessary

**Comment by carlosazpurua1004** [comment]
Made edits and submitted a pull request.

**Comment by carlosazpurua1004** [comment]
Opened a new PR because I wanted to make the changes on a new branch to avoid merge conflicts and discard all the prior changes I had made

**Comment by ecoble** [comment]
Issue Score: ✔️+
Comments:
Great work handling all the cross team communication! Issues closed by PR do still need closing statements.
