### ISSUE TITLE
Meet with RPG Player Stats, Action Management, and RPG Battle teams, and meet with WDL to further figure out dependencies, then produce meeting notes.

### ISSUE THREAD

**Issue by annabelleperng** [uchicago-cs/chiventure#567]
I'm going to follow up with three teams we met up with last week to further discuss dependencies. More specifically, I will discuss the stat struct with RPG Player Stats, general concerns about the design doc with Action Management, and actions referencing the enemy object struct with RPG Battles. I will also meet with the WDL team to discuss the mechanics of parsing from json files.

I will use the notes from these meetings to inform design decisions to make sure requirements/restrictions from other teams are taken care of in the custom-actions code, and vice versa.

**Comment by annabelleperng** [comment]
Met with RPG Battle - meeting notes [here](https://docs.google.com/document/d/1gdDvVfs3FWq6bOv9mLdG6gDKxSM35lrSfWs6gbVygsM/edit). They expressed interest for custom in-battle moves, defined by the game author, where each move is available to players or enemies of a certain class.

**Comment by annabelleperng** [comment]
Met with WDL (refer to above link for meeting notes). They communicated that they will pass a custom struct (instead of passing the JSON, to prevent information leakage) where ordering is retained (Custom Actions needs sequence parsing because of the nature of our conditional blocks). Custom Actions will then work to parse it into the an abstract syntax tree (described on the last page of our [Design Doc.)](https://docs.google.com/document/d/1_VAf-vyxNfj53l-mtSIn-LS9nS6ABe5JAXjQWJhlhIE/edit#)

**Comment by annabelleperng** [comment]
Met with RPG Player Stats to discuss the structure of current stats. They communicated that there will be both local (Player) and Global stats and effects and they detailed the structs in the Stats and Player modules. As of now, Custom Actions can use certain methods such as display_stats, get_stat_current, and change_stat to modify player stats.

**Comment by annabelleperng** [comment]
Met with Action Management. They communicated that they would keep us updated in terms of overhauling effects and design changes. I communicated to them the possible need for collaboration between RPG Battle and Action Management (for custom moves made by enemies, which we have decided is out of Custom Actions' scope).

**Comment by MaxineK36** [comment]
Issue Score: ✔️+

Comments:
Nice work! This is a great issue overall, and an excellent example of tangible meeting updates. One area of improvement: When an issue is done, you should include a final comment summarizing what was done, and why the issue is being closed.
