### ISSUE TITLE
Integrate existing Map code with Raylib to generate potential rooms

### ISSUE THREAD

**Issue by damonhines** [uchicago-cs/chiventure#568]
This issue will result in studying and reviewing framework of the pre-existing map code within the UI section of chiventure. Once reviewed, the reviewer will attempt to write sample code that can be integrated with actual chiventure code. The sample code should include a rendering of a map from chiventure. If successful, a pull request will be needed. The reviewer must make sure that the map flows well and is accurate with chiventure code specifications.

**Comment by damonhines** [comment]
_Beginning:_

First, I must understand how to link the raylib library with Chiventure's UI code. It's important to make this work to even test out my code, and integrate it with chiventure. First, I will review Chiventure's wiki on how to build with cmake. I will then review Chiventure's cmake and determine the appropriate linking steps. Doing so will allow me to test out libraries feature.

**Comment by damonhines** [comment]
_Update:_ 
I tried to set up chiventure on my laptop, to even run the code, but Chiventure only works in linux so far. Raylib doesn't really like a linux environment, so a virtual box is the route we need to go. I learned that I need the CS virtual box to even test my code. I'm going to look into that, but first, I am going to try to review the UI code and see where I could add draw rectangles functions for the map display. Because the setting up task is taking longer than expected, I am going to speed up my productivity. Furthermore, I want to try and test my code before a pull request.

**Comment by damonhines** [comment]
_Update:_
I'm reviewing the code, and noticed that ncurses is the library used, and the code needs to be refactored to fit the constraints of raylib functions. We no longer are using text-based game at the moment.

**Comment by damonhines** [comment]
_Midway Point_
I'm reviewing the professor's code from Friday to make an in-memory game. I will use the structures from an in-memory game to use it in the api drawing.

**Comment by damonhines** [comment]
Update:

I'm creating an in-memory game that will contain rooms that have connections. In Chiventure, there is no direct location for a room, so you must use the DFS (a module in the UI directory) to find rooms. However, one of the functions in room.h will allow you to search a room based on a direction, so I will hardcode different options to test the sandbox

**Comment by damonhines** [comment]
Update: 
Downloaded the virtual machine and now Im going to try and run my code. I'm going to try and alter the cmake file, but first see if I can get chiventure to build first. Then Im going to alter the cmake file to add the raylib library

**Comment by damonhines** [comment]
Update:
My virtual machine finally downloaded after a day of cleaning my computer and clearing space for it. I'm attempting to recreate my sandbox program on the machine. However, I am encountering issues with the include states. I need to sort this out before running my program.

**Comment by damonhines** [comment]
Summary:
There was alot of components to even run a sandbox program and test. First, one must download a virtual box and make sure they have atleast (50 GBs of storage). Next, the person needs to redownload all of the packages as well as rebuild the code. Third, the person must make sure they link the correct dependencies for the project.

My takeaway is that this issue was an example of going in to a sprint with not enough vision and clarity. The main thing now is making sure the sandbox can actually run. The next step would to review the ui code and make sure there are functions that are friendly for composing the map using some of the already defined metadata. DFS would most likely need to be used.

**Comment by damonhines** [comment]
Still need to push code to a branch

**Comment by ecoble** [comment]
Issue Score: ✔️++
Comments:
Great job on this issue and with keeping it updated!
