### ISSUE TITLE
Create a general purpose UI

### ISSUE THREAD

**Issue by sebvil** [uchicago-cs/chiventure#57]
In this task, a general purpose UI will be created. This will consist of a general layout of the UI which will allow a user to choose which half of the screen should display maps/images and which will display the CLI, toggling views (between map and images, for example). Will try to incorporate  the CLI into the corresponding window.

**Comment by sebvil** [comment]
Just implemented several functions for a general purpose UI. First, the program now allows choosing the location of the CLI. I also implemented a switch_windows function that allows for the window that is being displayed to be switched. I added a window_t struct that contains a ncurses WINDOW struct as well as a print function that will be specific for the window. I also prevent CTRL+C from closing the program and instead CTRL+D closes it.

**Comment by sebvil** [comment]
In the last commit, I deleted the switch-windows function. Instead, I simply created a window_t (named  info) in main which will always point to the window_t we want to display. Thus, we can create separate window and to switch the displayed window, we just need to assign the window we want to print to info. Besides this I just cleaned the code a bit.

**Comment by mpcsh** [comment]
@sebvil nice! I like this strategy. 👍

**Comment by sebvil** [comment]
@mpcsh can I close this issue?

**Comment by mpcsh** [comment]
Yep, make sure to provide a closing statement.

**Comment by sebvil** [comment]
In this task, I generalized the UI. It now allows for switching between windows (right now can be done with Alt+m, though more Alt commands can be added as there are more windows). A window_t struct was added that provides the print function associated with the window. Lastly, the user can switch the position of the CLI (top or bottom half of the screen) by pressing Alt+s

**Comment by mpcsh** [comment]
Issue Score: ✓+

Comments:
Great work here as well!
