### ISSUE TITLE
Integrate skills and skilltrees into the player class struct

### ISSUE THREAD

**Issue by PaulTreitel** [uchicago-cs/chiventure#571]
We also want to start working on integrating skills and skilltrees into the player class struct. The class should probably have skilltrees both for all class skills and for player-unlocked skills. This would involve adding those fields to the struct and providing a set of functions for manipulating, using, and searching those skilltrees in the playerclass. This would replace some of the stubs in the existing class struct/functions.

This issue was originally to create a skill module, but this was redundant with the work that rpg-skilltrees has already done. Instead, this issue will focus on integrating that work into the class system.

**Comment by PaulTreitel** [comment]
A slightly belated update: the [first part](https://github.com/uchicago-cs/chiventure/pull/732) of this has been merged into dev. Some of the stubs have been replaced with the skilltree structs (the remaining are pending a skilltrees PR). `class_new `and `class_init `have had the skill-related inputs removed, since those will now be created internally by `class_skills_init`. The code does not yet actually create any skills or fill in the skilltree structs with them, but it does initialize the structs.

**Comment by jackcasey067** [comment]
Issue #817 took up the mission of integrating these two features.  It was closed when the integrating code was merged with dev, and so this feature is also closed.
