### ISSUE TITLE
Implementing struct and essential functions for enabling movement of NPCs between different rooms.

### ISSUE THREAD

**Issue by shayna-k** [uchicago-cs/chiventure#572]
This feature has been branched off from #468. 
Implementation of this will follow the issue #555, which is regarding enabling the creation on room-specific NPCs. This feature essentially involves implementing functionality for NPCs moving between rooms (and/or respawning). We plan on writing the structs, as well as implementing the basic functions for this feature.  There will be some extent of collaboration required with rpg-openworld in the future, when it comes to integration of the code.

**Comment by shayna-k** [comment]
We have currently begun working on this module. We had aimed to work on this in sequence with our previous feature, explained in issue #555. We have submitted a pull request for that issue and will continue to make minor changes, according to the requirements of this feature.
We have also been in correspondence with the custom-scripts team (@suday18), and will be thinking of a way to implement different paths for NPC movement through various room, using lua.
We are going to be updating the [design document](https://github.com/uchicago-cs/chiventure/wiki/RPG-NPC:-Independent-Feature:-NPC-Movement-Design-Document) regularly and adding updates to this issue as well.

**Comment by shayna-k** [comment]
We have thought through and added the necessary structs for the movement of NPCs through rooms. We have structured it such that there is a specification for the type of movement that the NPC should carry out - definite or indefinite:

- Definite: When the NPC has a specific task to carry out (maybe giving the player information or battle the player)

- Indefinite: When the NPC is expected to move through the world without a specific task to carry out.

We used a union data struct to keep track of the movement for that NPC:
`typedef union npc_mov_types {
    mov_def_t *mov_def;
    mov_indef_t *mov_indef;
} npc_mov_types_u;`

For implementing the indefinite movement, we have created a way to include how long an NPC should stay in a particular room (in seconds) before it moves on along the pre-specified path. This was done like so:
`typedef struct time_in_room {
    UT_hash_handle hh;
    int sec;
    char *room_id;
} time_in_room_t;`

Another thing we included was a tracker [`char *track`] that keeps track of which room the NPC is at that point in time. 

We will be wrapping all this functionality in one struct that we will include in the main NPC struct.

**Comment by philipchenaux** [comment]
We have included a description of each of the structs in the following wiki:
https://github.com/uchicago-cs/chiventure/wiki/RPG-NPC:-Independent-Feature:-NPC-Movement-Design-Document

To build upon what was previously said in this issue, and to add some clarification, we are distinguishing  between npcs  that have a `definite path' versus and `indefinite path', and we define these two as the following:
> A definite path (labelled mov_def_t): this is the first case when an npc is required to move from point A to point B for a specific reason (that being for a quest, etc.). In this case the npc is merely moving from point A to point B and the movement ends at point B.

> An indefinite path (labelled mov_indef_t): this is the second case when an npc is simply moving through the map but without a definite end point. This is simulate the open-world so that npcs will be continuously moving through the world. In this case the npc will also hold a linked list of rooms to move through, but in addition it must have contain a hash table that holds the time that it should spend in each room in seconds.

We have also outlined the two key  movement type structs as the following:
```C
/* struct for the definite path movement for npcs */
typedef struct mov_def {
    path_llist_t *npc_path;
} mov_def_t;

/* the struct for the indefinite path movement for npcs */
typedef struct mov_indef {
    path_llist_t *npc_path;
    time_in_room_hash_t *room_time;
} mov_indef_t;
```
Where the time_in_room_hash_t is a hash table containing each room and the time that should be spent in the room in seconds, which is shown above. One additional  important change is a slight modification to our npc_mov struct is the following:
```C
/* the main struct that deals with the movement of an npc */
typedef struct npc_mov {
    char *npc_id;
    npc_mov_types_u *npc_mov_type;
    mov_type_e mov_type; //an enum saying which type of movement the npc is doing, this is purely to simplyify the implementation
    char *track;
} npc_mov_t;
```
Finally, we have also included several struct specific functions in our wiki as well, that implement the movement of npcs between rooms.

**Comment by philipchenaux** [comment]
This feature is covered in the branch named rpg-npc/npc_room_movement.

**Comment by shayna-k** [comment]
We have created new files for spawning NPCs in a room ( #555 ) and for implementing NPC movement as well and will continue to make changes in our new branch ([rpg-npc/npc_room_movement](https://github.com/uchicago-cs/chiventure/tree/rpg-npc/npc_room_movement)) : 
- https://github.com/uchicago-cs/chiventure/blob/rpg-npc/npc_room_movement/include/game-state/rooms-npcs.h
- https://github.com/uchicago-cs/chiventure/blob/rpg-npc/npc_room_movement/src/game-state/src/rooms-npcs.c

All the structs pertaining to both the respective issues have been moved from the npc.h file to the rooms-npcs.h file, and the code to the respective .c file (both linked above). We thought this would help readability since it was a more modular approach and we were previously making changes in the npc.h and npc.c files.

We have also made minor edits to our previous code, including the code for NPC generation, just for increased ease of implementation, but the overall structuring of the code is in line with the implementation specified in the [wiki](https://github.com/uchicago-cs/chiventure/wiki/RPG-NPC:-Independent-Feature:-NPC-Movement-Design-Document).

A few initial implementations have been completed, including tailoring our structs according to what the code required, and we will continue the same. Updates shall follow.

**Comment by shayna-k** [comment]
[Another issue](https://github.com/uchicago-cs/chiventure/issues/629) has been opened regarding the testing of the generation and movement functionality combined.

While it is a little late in the sprint, it will be move to 'in progress' as soon as we are satisfied with the current feature implementations - this issue will be moved to be worked on in the fourth sprint as required.

**Comment by philipchenaux** [comment]
So far we are in the midst of the implementation phase, having included the main structs required for this feature, as well as a series of essential functions. The changes do not just include the new, init, and free functions, but are also include  following:
```C
int extend_path_def(npc_mov_t *npc_mov, room_t *room_to_add);

int extend_path_indef(npc_mov_t *npc_mov, room_t *room_to_add, int time);

int register_time_in_room(npc_mov_t *npc_mov, room_t *room, int time);

int reverse_path(npt_mov_t *npc_mov);

char* track_room(npc_mov_t *npc_mov);
```
Th full description of the issues can either be found on our [wiki](https://github.com/uchicago-cs/chiventure/wiki/RPG-NPC:-Independent-Feature:-NPC-Movement-Design-Document) or on our [branch itself ](https://github.com/uchicago-cs/chiventure/tree/rpg-npc/npc_room_movement). We are still unsure whether it is a good idea to combine the two exten path functions into a singular one even though they require  a different number of arguments.

**Comment by philipchenaux** [comment]
We have just submitted a pull request #641 for this issue. In this pull request we basically implemented everything mentioned above in the previous update. We believe that this provides a good foundation layer for this feature from which we can continue to build upon in the following sprint with more complex functionalities as  well as implementing the main function of npcs actually moving between the rooms. We will close this issue once this pull request has completed, and then we will open another issue that will cover the implementation of more complex features

**Comment by philipchenaux** [comment]
We will close this issue as we are only waiting for the pull request #641 to be approved after a few minor changes. As this issue will be closed, we have reopened one implementation issue that will build upon our existing functions #644, as well as two additional testing issues #629 and #645. All of the mentioned issues will be covered in the 4th sprint.

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Amazing work! I'm really impressed by the work put into the comment cards above.
