### ISSUE TITLE
Create and improve functions for game-state construction/saving

### ISSUE THREAD

**Issue by liuyifan-eric** [uchicago-cs/chiventure#58]
We will provide basic functions which simplify the process of constructing a game (reading from wdl files or saved files) and saving a game (to saved files). This will include new_game(), player_new(), object_new(), and we will write documentation about how to use them. In the end, wdl and checkpointing teams will be able to load a game like this: 
`

    void load_wdl_or_saved_file() {
        game_t *game = new_game();
        int player_id = 0;
        for each player parsed: //which reads from wdl files or saved files
            player_t *player = player_new((player_params));
            
            /* other parameters */
            // player->xp = 0;
            
            add_player_to_hash(game->all_players, player_id, player);
            for each object in inventory parsed: //which reads from wdl files or saved files
                object_t *object = object_new();
                add_object_to_hash(player->inventory, object_id, object) 
                
            ++player_id;
            
        int room_id = 0;
        for each room parsed: //which reads from wdl files or saved files
            room_t *room = room_new((room_params));
            
            /* other parameters */
            // room->desc = "";
            
            add_room_to_hash(game->all_rooms, room_id, room);
            for each object parsed: //which reads from wdl files or saved files
                object_t *object = object_new();
                add_object_to_hash(room->inventory, object_id, object) 
                
            ++room_id;
    }
`

**Comment by a-matai** [comment]
Note:

This issue relies pretty heavily on our other two issues, so we'll provide implementations for these functions once those have been clarified.

**Comment by liuyifan-eric** [comment]
We have provided various user-friendly functions and macros that facilitate WDL & checkpointing teams build or save the game-state in the memory. The names and the arguments are rendered as intuitive and concise as possible. Also, we wrote a tentative detailed documentation (README.md), which includes both explanations and examples, to help other teams (not only WDL & checkpointing) understand the usage of these structs, macros, and functions. 
The full documentation file is here: [README.md](https://github.com/uchicago-cs/chiventure/blob/game-state/dev/src/game-state/README.md)
In the next sprints, we will try to make the header files more concise and readable.

**Comment by lydiafilipe** [comment]
Issue Score: ✓-

Comments:
Good title, summary, and closing. However, you are not providing any progress comments, please make sure you do this as you go through the task. Also, the README link in your closing statement is broken (I believe it was renamed). And in the summary, the code you provided is much too detailed - you should only be showing snippets of the part relevant to you, and describing everything else at a higher level
