### ISSUE TITLE
Design user ability to give/take items to/from NPC

### ISSUE THREAD

**Issue by lilyehsani** [uchicago-cs/chiventure#581]
For this task, we plan to create a design doc on the Wiki outlining a way for the user in a game (player) to be able to add and remove items from an NPC's inventory. This will be useful in creating merchant NPCs who can trade items, friendly NPCs that give gifts, or hostile NPCs that drop their items when killed. It will involve collaborating with action management, as well as doing an in-depth code review of UI and CLI code.

**Comment by lilyehsani** [comment]
We have met with Eric from action management to discuss existing action-related code and how we should go about writing functions for NPC-related actions. We have start a Wiki page [here ](https://github.com/uchicago-cs/chiventure/wiki/NPC-Player-Interaction-Design-and-Planning) that will serve as the design document for all NPC actions (including the dialogue-related actions of issue #582  ).

**Comment by alexjsun** [comment]
I updated the wiki page with info about what the npc_game_action.h should contain. I included possible functions that can be implemented in Sprint 4, such as functions that involve searching for and conducting actions, condition functions, and effect functions: [https://github.com/uchicago-cs/chiventure/wiki/NPC-Player-Interaction-Design-and-Planning#npc_game_actionh](url)

**Comment by lilyehsani** [comment]
The design is documented on the [Wiki](https://github.com/uchicago-cs/chiventure/wiki/NPC-Player-Interaction-Design-and-Planning) and we are ready to start trying to implement the integration of the NPC module and future npc_action module with the existing CLI module, so that players will be able to exchange items with NPCs. I am closing this issue, and I encourage anyone who has ideas on this topic to add them directly to the Wiki page.

**Comment by ecoble** [comment]
Issue Score: ✔️+
Comments:
Great job, this will definitely help future teams! When you give updates on meetings, you should give a summary of the meeting and its outcomes.
