### ISSUE TITLE
Design user ability to talk to NPC

### ISSUE THREAD

**Issue by lilyehsani** [uchicago-cs/chiventure#582]
For this task, we plan to create a design doc on the Wiki outlining a way for a user in a game (player) to be able to converse with an NPC. This will have to wait until we have a dialogue module up and running. It will involve manipulating the dialogue module in game-state within UI and CLI code, as well as collaborating with action management to discuss NPC dialogue mode. We should detail how the user will enter and exit NPC CLI dialogue mode.

**Comment by lilyehsani** [comment]
We have met with Eric from action management to discuss existing action-related code and how we should go about writing functions for NPC-related actions. The dialogue module is not quite ready yet, but we have start a Wiki page [here ](https://github.com/uchicago-cs/chiventure/wiki/NPC-Player-Interaction-Design-and-Planning) that will serve as the design document for all NPC actions (including the item-related actions of issue #581 ).

**Comment by lilyehsani** [comment]
The design is documented on the [Wiki](https://github.com/uchicago-cs/chiventure/wiki/NPC-Player-Interaction-Design-and-Planning) and we are ready to start trying to implement the integration of the NPC module, dialogue module, and future npc_action module so that players will be able to talk to NPCs. I am closing this issue, and I encourage anyone who has ideas on this topic to add them directly to the Wiki page.

**Comment by ecoble** [comment]
Issue Score: ✔️+
Comments:
Great job, this will definitely help future teams! When you give updates on meetings, you should give a summary of the meeting and its outcomes.
