### ISSUE TITLE
Document actions related to NPC CLI mode with action management

### ISSUE THREAD

**Issue by lilyehsani** [uchicago-cs/chiventure#583]
For this task, we plan to meet with action management and produce a design document for actions related to NPCs. This will include talking with NPCs, which will cause the game to enter NPC CLI mode (the focus of Issue #582). It will also include discussing actions related to items and inventory, specifically letting a player give/take items from NPCs (the focus of Issue #581).

**Comment by lilyehsani** [comment]
We have just met with Eric from action management and realized that their work and our work overlaps a bit less than anticipated, but he helpfully pointed us towards some existing CLI code such as operations.c that will help us write functions related to NPC CLI mode.

**Comment by lilyehsani** [comment]
The documentation of relevant existing action-management code can be found on this Wiki page: https://github.com/uchicago-cs/chiventure/wiki/NPC-Player-Interaction-Design-and-Planning. I am closing this issue, and I encourage anyone who has additions to this topic to edit the Wiki page directly or get in touch with the relevant team.

**Comment by ecoble** [comment]
Issue Score: ✔️++
Comments:
Great job, this will definitely help teams in the future!
