### ISSUE TITLE
Create a sandbox program that displays both a graphical image and a text box in a window using raylib

### ISSUE THREAD

**Issue by aherman33** [uchicago-cs/chiventure#585]
To get closer to creating a GUI that can be integrated into the chiventure code, we plan on creating a sandbox program that successfully displays an image as a "background," as well as a text box that populates with text that would hypothetically appear after the user enters a command. This will be done using features of the raylib library which were explored by the team in Sprint 2.

**Comment by aherman33** [comment]
I've added to the sandbox program created in issue #513, so now the window that opens contains both the loaded image with a textbox beneath it. This textbox would hypothetically contain the output after a command is entered by the player. Right now the string contained in the textbox is hard-coded, so we will have to further explore how to make it so the string is updated with the correct output. Additionally, we will have to explore adding an input box so the user can see their input.

**Comment by ambikalv** [comment]
In order to get the input from the user, we want a signal for the user to be able to input text, we want the program to save the user inputted text (for as long as the program needs it) and then we want that text to display. I will be working on the first two parts.

**Comment by ambikalv** [comment]
In order to initialize the user input we are using mouse hovering and keyboard pressed as our conditions to capture when the user is ready to type. This code I found from raylib's website as a text example https://www.raylib.com/examples.html. My question then would be, in addition should I being using fgets to read in user input and save it somewhere for the game to use/where should I be saving and storing input.

**Comment by ambikalv** [comment]
I have currently written the code which will read the user's input (up to a maximum character count) and dynamically (i hope) display it onto the screen -- I am currently having trouble getting raylib to run, but hopefully during this week's sprint we will have a way of doing it on the cs VM.

**Comment by aherman33** [comment]
I've added the user input box into the interface so now the program includes both an image, an output text box beneath it, and a user input text box at the bottom of the screen. 

<img width="800" alt="Screen Shot 2020-05-20 at 2 51 32 PM" src="https://user-images.githubusercontent.com/63211362/82491161-e88e1e80-9aa9-11ea-9748-157ec1fe7f88.png">

As of right now, this looks like a viable template/design for the overall graphical UI for games. Raylib provides a good general framework for creating windows, which will be the basis of chiventure games. From here, we need to start exploring how to update the game window such that the input text box can accept input upon a key interaction (ie. pressing enter) and then the output text box is updated correctly based on that user input.

**Comment by ecoble** [comment]
Issue Score: ✔️++
Comments:
Great work here, and great job giving frequent updates!
