### ISSUE TITLE
Implementing basic Stat functions (init, new, and free)

### ISSUE THREAD

**Issue by carlosazpurua1004** [uchicago-cs/chiventure#587]
The init, new, and free stat functions have been stubbed and now need to be implemented. This Issue will be resolved by a pull request with these functions implemented.

**Comment by carlosazpurua1004** [comment]
tried making a branch of the rpg-stats branch to make progress on this, but stuff got weird and I didn't save my work (wasn't much).

**Comment by richardxd** [comment]
I have created a new branch rpg-stat/basic_functions. My tests for the basic functions will be implemented under this branch

**Comment by carlosazpurua1004** [comment]
Things left to do:
- debug implementation
- get the include of context.h in stats.h working and add it back as a parameter
- modify stat_new to make sure that the initialization value isn't greater than the global maximum

**Comment by carlosazpurua1004** [comment]
Stuff got messy because I went beyond the scope of global_stat_new tried to add new globals to the tables on creation; so I inlucded ctx.h to access the global table but this caused a circular inclusion and a lot of issues I couldn't fix.

So I didn't include ctx.h and wrote the new functions within a scope that made more sense (i.e. not doing those things)

-I added a free function for tables as will as for individual stats (for both global&local)

**Comment by ecoble** [comment]
Issue Score: ✔️++
Comments:
Great work, especially with the updates! Issues that are closed by PR do still need closing statements.
