### ISSUE TITLE
Update documentation for skill tree module to reflect code design

### ISSUE THREAD

**Issue by michaelleestuy** [uchicago-cs/chiventure#588]
As code begins to be added to the skilltrees/skeleton_code branch, I will update the wiki page located [here](https://github.com/uchicago-cs/chiventure/wiki/Design-Documentation-for-Skill-Trees-Implementation) to maintain accurate documentation in regards to interfacing functions.

**Comment by michaelleestuy** [comment]
[Wiki page](https://github.com/uchicago-cs/chiventure/wiki/Skill-Trees:-Design-Document-and-Interface-Guide) has been updated to reflect the code in the `skilltrees/skill_tree` branch and commit `d633904`. The added content covers the same points as before, with updated code snippets and function namings. While before, the document served as a roadmap for future implementation, now it will be a reflective documentation of written code. 

(note: The heading of the wiki page was changed to allow for better categorization based on team name, and so the previous link to the wiki page will dead end.)

**Comment by firatciftci** [comment]
Issue Score: ✔️+

Comments:
Good work! The only thing I'll point out is that the summary should have been a bit more detailed; ideally, it is a paragraph long and outlines the purpose and the exact goal of the issue.
