### ISSUE TITLE
Rewriting command structure

### ISSUE THREAD

**Issue by Gestalt-R** [uchicago-cs/chiventure#59]
Task will probably be done by end of day, almost certainly should be finished before anyone else starts doing anything.

Never mind, this is actually much bigger. Rewriting commands to be a list of tokens and a pointer to a function which handles them.

**Comment by Gestalt-R** [comment]
This is important, because it enables us to add new commands in that are not hardcoded.

**Comment by Gestalt-R** [comment]
Now almost works. Just need to migrate over functionality.

**Comment by Gestalt-R** [comment]
Also, just adding in someone who should have been put in earlier.

**Comment by Gestalt-R** [comment]
Finished everything but hash-table implementation and cleaning up comments. This is pretty close to resolved.

**Comment by ecoble** [comment]
The new command struct includes a list of words that have been split up by the parser, and a pointer to a function that will process this command. There are currently 7 types of possible functions a command can be associated with, a quit function, help function, history function, and four types of action functions based on the four types of actions that the action management team has created.

**Comment by Gestalt-R** [comment]
Also, all functions in relevant modules have been rewritten to spec.

**Comment by ecoble** [comment]
Closing Statement: The command structure has been rewritten, it now includes a list of individual words from the parser and a pointer to a function that will process the command.

**Comment by lydiafilipe** [comment]
Issue Score: ✓

Comments:
Good job overall! For the summary, you shouldn't be editing it after you start. If something becomes bigger than you think, it's better to post that as an update with what you've encountered/what you want to do moving forward. Also, the updates are  bit brief, I would include  bit more detailed on what was done and why it is useful
