### ISSUE TITLE
Implement and write tests for add_stat and display_stat

### ISSUE THREAD

**Issue by sumedhsarwate** [uchicago-cs/chiventure#591]
The add_stat and display_stat functions have already been stubbed, and I will implement the functions such that add_stat adds a stat to the player's stats hash table and display_stat returns a list of the stats the player has. I will also write tests for these functions.

**Comment by sumedhsarwate** [comment]
As per our team meeting, add_stat_player (renamed to avoid confusion with the global add_stat function) will now take in a pointer to a global stats struct as a parameter instead of the string name of the stat. The player stats struct is also going to be updated so that it will contain a pointer to a global stat instead of a string for its name.

**Comment by sumedhsarwate** [comment]
Now that our previous pull request has been approved, I've created a new branch to implement the add and display functions.

**Comment by richardxd** [comment]
I have created a new rpg-stat branch that includes the test files. 23dca317a29370767069421dc03fc6b30aae4a01
This could result in a merge conflict if the branch you created also contains test folder/files. Please check this out before you started working on the test!

**Comment by sumedhsarwate** [comment]
@richardxd and I fixed the conflict between the branches so that we have the same folder/files for the tests

**Comment by sumedhsarwate** [comment]
In order for the tests to pass and to follow the UTHash documentation, I had to change the parameter of add_stat_player to take in a pointer to a pointer for the hash table. The updated header is:

int add_stat_player(stats_hash_t **sh, stats_t *s)

**Comment by sumedhsarwate** [comment]
Closing Statement: This issue is being closed by a pull request that includes the implementation and tests for both add_stat and display_stat. We've updated the stats struct so that the key is a string, and the implementation for add_stat has been updated accordingly (the changes can be seen in commit 2ac017a).

**Comment by ecoble** [comment]
Issue Score: ✔️++
Comments:
Great work, especially with the frequent updates!
