### ISSUE TITLE
Implement a global_effect struct

### ISSUE THREAD

**Issue by Rusah1129** [uchicago-cs/chiventure#596]
A team discussion brought up the idea and rough design of a global effect struct as part of a better player stats design. I aim to implement it. This issue will be closed with a pull request with a working global_effect implementation.

**Comment by richardxd** [comment]
A new rpg-stat branch has been created 23dca317a29370767069421dc03fc6b30aae4a01. Feel free to check out the branch and work on the struct implementation!

**Comment by Rusah1129** [comment]
Branch merged! The global_effect struct is implemented.

**Comment by ecoble** [comment]
Issue Score: ✔️++
Comments:
Great work implementing this!
