### ISSUE TITLE
Implement paths struct in rooms module

### ISSUE THREAD

**Issue by CCalderon01** [uchicago-cs/chiventure#597]
In the current state of the rooms module, a given room is characterized by its name, short description, long description, list of items, and room_type. Now, I want to add a paths structure to connect rooms to each other. This struct is inspired from the paths struct found in room.h in game-state.

**Comment by CCalderon01** [comment]
I implemented an items-based path module that, given an item with a valid "exit" attribute, returns an updated path list in a room. The game-state model for the path struct was dependent on "direction" (i.e. north, south, east, west), but I removed this feature in order to have paths more heavily tied to items. I added the basic init, new, free, list_all functions as well as some more complex functions to connect two rooms to each other.  I still need to write tests to check the functionality of this feature.

**Comment by CCalderon01** [comment]
Upon further consultation with my senior developer, we're shifting the focus of this issue to implementing a path generation feature.

**Comment by CCalderon01** [comment]
Unfortunately, the bulk of Sprint 3 was spend on my other issue (making default rooms and items), so this was effectively placed on the backlog. However, moving forward, once my pull request goes through, I should be able to switch to the autogeneration branch to work with Bryan more on this. We met during the week to discuss the implications of path generation on the general generation purpose for the module.

**Comment by williamhu314** [comment]
This issue is currently too big to complete in a single sprint. I have created a new issue that is aimed just at creating an algorithm for path generation rather than at fully implementing path autogeneration. The new issue is provided below:

https://github.com/uchicago-cs/chiventure/issues/1178
