### ISSUE TITLE
Writing tests for our pseudo-type module (custom-scripts/custom_types.c), specifically the new(), init(), and get() functions for each of the three pseudotypes.

### ISSUE THREAD

**Issue by hugo-chan** [uchicago-cs/chiventure#598]
In issue #594, we created a new module to implement pseudo-types that, in short, contain either the underlying type or a Lua script. In this module, we created new(), init(), and get() functions for each of the three types. 

Since we are planning to incorporate these functions all throughout Chiventure, it is important these functions are correct. Furthermore, due to the union field in each of these pseudo-types, there are effectively two versions of the same function we have to test for (one for the underlying type and one for the Lua script). Thus, it is crucial our code is able to accurately handle both cases, and therefore tests will be written.

The tests will be written in the Criterion framework. I will not only have to write the tests but also integrate them into the build process (CMake). This will involve looking at how existing tests integrate with CMake, and emulating that for the tests I write. This is my biggest uncertainty.

I will know this issue is done when my tests are written and they successfully integrate with the build and run.

**Comment by hugo-chan** [comment]
I have finished writing tests for the new() and init() functions, testing for normal cases as well as edge cases such as when the strings passed in are NULL. I have written tests that test the correctness of get()'s ability to retrieve the data of the underlying type but not for when the data is the Lua script. 

Nevertheless, I am now confident that these functions work as they are designed and can start incorporating these pseudotypes into the current existing code.

**Comment by hugo-chan** [comment]
Since we had to redesign our module (as described in #594), we will have to rewrite our tests as well.

**Comment by hugo-chan** [comment]
The tests for the new design of our pseudotype have been written and pass. The tests can be found in `test_types.c` in PR #640. This issue is therefore complete and can be closed.

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Great work!
