### ISSUE TITLE
Write draft specification of supported actions

### ISSUE THREAD

**Issue by borjasotomayor** [uchicago-cs/chiventure#6]
Write a human-readable document that specifies the actions we will support, and a high-level explanation of how conditions and effects are associated with actions.

**Comment by borjasotomayor** [comment]
Following up on our discussion at the team meeting, here is a list of actions that are common across many adventure games:

- Open
- Close
- Push
- Pull
- Walk to
- Pick up
- Talk to
- Give to
- Use (and "Use X on Y")
- Look at
- Turn on
- Turn off

**Comment by lucyyutingli** [comment]
This is the current list of supported actions the team has come up with:

Interactions w/ Environment
Open
Close
Push
Pull
Look at, examine
Turn on
Turn off
Interactions w/ NPCs
Talk to
Give to
Movement
Walk to, go to
Pick up, take
Items
Inventory (checking to see what you have)
Use (and "Use X on Y")
Drop (item)
Consume, Drink, Eat

**Comment by borjasotomayor** [comment]
These look good, although "inventory" is not something that would fall under Action Management, because checking your inventory would never have associated conditions, nor associated effects. Instead, it is something that can unconditionally be done from the CLI (similar to saving and loading). You may also want to more concretely specify what the "parameters" to each action are, and what constraints there may be on these parameters (e.g., you can only pick an object that is in the same room as you are)

Please remember that this task also involves specifying how conditions and effects are associated with actions. The distaff.wdl file suggests one way of doing this, but you should specify this in a way that isn't tied to a specific file format (yet).

**Comment by Gestalt-R** [comment]
(In the CLI Team)
If we are doing this, how about a list of words we _can't_ use, like "SAVE," "LOAD", and "INVENTORY"?

**Comment by borjasotomayor** [comment]
@Gestalt-R: It would be the other way around: CLI _would_ support commands like "SAVE", "LOAD", etc. but those would not result to a call to Action Management. They would involve calls to other components (e.g., "SAVE" and "LOAD"  would call Checkpointing, and "INVENTORY" would call Game State)

**Comment by SnowballAntrobus** [comment]
https://docs.google.com/document/d/1UjTysW83lE7zJO-1dw9HXyHowZpgEsopxye1WQk3qx8/edit?usp=sharing is not final but a good idea of what we are going to do. We will move the information over to a format on the repo proper soon.

**Comment by ellychoi** [comment]
To convert our table into a markdown:
Dante will take the first 6 of the draft: General - look at
Elly will take the next 6 of the draft: Turn on - walk to
Lucy will take the rest: Pick up - Consume/medly

**Comment by yoonsjeong** [comment]
After considering the action structures, Melinda and I have concerns about the actions "Go to" and "walk to". Syntactically, they seem to do the same thing as "Go" and "Walk", only specifying that you would move to an object rather than a direction.

What are your guys's thoughts on this?

**Comment by yoonsjeong** [comment]
Wait, follow up on this comment. After reading the document, it seems like "Go to" and "walk to" are synonymous the the actions "examine" and "look at". Was this the original intention? I found this a little confusing

**Comment by lucyyutingli** [comment]
@yoonsjeong We're trying to figure that out right now, but I'm thinking we won't need that category of functions. I think it can be assumed that a player moves in an object's direction in order to interact with it.

**Comment by lucyyutingli** [comment]
@borjasotomayor @mpcsh The team was hoping to get your opinions on having drink and eat split into to actions, or having them in the "use" action. Some of us think that having them split into drink and eat is better for the player experience and can help avoid confusion, but others think that having them in use makes it easier since you can "use" any object.

**Comment by yoonsjeong** [comment]
@lucyyutingli From the specifications me and @MTUC08 (melinda) set up, we allow for synonyms and interpreted the three commands USE, DRINK, and EAT as being in a singular "enum action" category of CONSUME, meaning we collapsed all three commands as being the same.

We can pretty easily refine this so that it disallow a weird command (e.g. DRINK potato) as it would any other (e.g. OPEN potato) since our idea for object struct (which game state team should be responsible for) was having a linked list of "allowed" actions.

**Comment by lucyyutingli** [comment]
@yoonsjeong I think we can still keep them in the list of supported actions, I don't think it'll have too much affect on what you and Melinda are writing. If the they can be differentiated within the functions I think it should be fine.

**Comment by borjasotomayor** [comment]
A sensible approach might be to consider it as a single action on your end (e.g., "use" or "consume"), but then specify valid synonyms that could be used in the CLI for certain objects (this would have repercussions for CLI and WDL). For example, an object "potato" could have an associated "use" action, but you could specify that "eat" would be an allowed synonym for this object (but internally it would be handled exactly the same as "use")

**Comment by mpcsh** [comment]
+1 for Borja's suggestion - I had the same thought about using one `consume` verb with aliases.

**Comment by Gestalt-R** [comment]
As part of the CLI team, I have to ask: why do we need prepositions for verbs with obvious choices? Is it necessary? Part of the parsing system involves knowing where to "cut off" when a section of input ends, and using the strtok library to parse uses delimiters like spaces to divide the command into actions and arguments.

Keeping a consistent word length for actions (or position of words within commands) is really helpful for parsing, and given that, say, most commands fit in the form "ACTION argument PREPOSITION argument" i.e "WALK left" or "GO right" or even "TURN switch ON", and that generally things modifying "GO" are either meaningless/pointless: "GO FROM" is confusing, as we know where we are, "GO TOWARDS" is the same as "GO TO", as is "GO IN", it seems like most (possibly not all, but certainly the ones listed in the doc) commands could elide the preposition if there is no object in the sentence being modified.

**Comment by mpcsh** [comment]
@Gestalt-R: In short, ease of parsing should not take precedence over closeness to human speech. We want to strike a balance somewhere on the spectrum between natural language processing (hardest to parse) and literal Racket (easiest to parse). Some things will end up being supported and some won't (as you mentioned, `GO FROM` is pointless, while others are meaningful) - all of these decisions will have to be done case-by-case, balancing these two conflicting ideals of parsing simplicity and readability.

**Comment by lucyyutingli** [comment]
https://docs.google.com/document/d/1MoLpXWxUaaFTCgoOU_KjhgBC88C6toJx0mobU2FHTpg/edit?usp=sharing

This is our final draft in the Markdown format we want to include. I was just a little unsure where we add a "action_management" file in our branch. Would it be under src files so there would be a src/action_managment repository?

**Comment by borjasotomayor** [comment]
Please add it under the `docs/` directory using the `actions/dev` branch (please note that this branch doesn't have the latest changes from `master`, so you will need to merge `master` _into_ `actions/dev` to update the branch with the latest changes (including the `docs/` directory)

In the future, please do not use Google Docs for writing Markdown; simply create a Markdown file directly (or, at most, use the built-in wiki to edit Markdown content before you create a file).

**Comment by MTUC08** [comment]
Just an update: I merged master into actions/dev if y'all want to move your document now.

**Comment by mpcsh** [comment]
@lucyyutingli Specifically, please put it in `docs/actions/README.md`. Files named exactly `README.md` automagically render in Github's file browser.

**Comment by lucyyutingli** [comment]
Sounds good, I'll upload the document if no one else is opposed @ellychoi @SnowballAntrobus @yoonsjeong @MTUC08. I don't think this requires a pull request.

**Comment by lucyyutingli** [comment]
@mpcsh Should we create a pull request from our actions/dev branch to the master branch after I've added the document?

**Comment by mpcsh** [comment]
Yep! You can also close out this issue. Sorry for not getting to this last night.

**Comment by lucyyutingli** [comment]
Closing the issue now! Good work team!

**Comment by mpcsh** [comment]
Issue Score: ✓-

Comments:
The closing statement needs to summarize the future-relevant work done in the task. Also, don't use google docs in the future! Either make comments directly in the issue, or use a `.md` file in the repository so that changes can be tracked.

**Comment by lucyyutingli** [comment]
@mpcsh I’ll fix the closing statement now
