### ISSUE TITLE
Writing tests and debugging for stats_init, stats_new, and free_stats in the stats module  

### ISSUE THREAD

**Issue by richardxd** [uchicago-cs/chiventure#605]
This issue involves writing tests for functions in the stats module. Specifically, this issue will provide tests for stats_init, stats_new, and free_stats. Depending on the progress of the implementation, there could be more test functions.

**Comment by richardxd** [comment]
A new rpg-stat branch has been checked out with the rpg-stat test folder. 23dca317a29370767069421dc03fc6b30aae4a01

**Comment by richardxd** [comment]
The tests will be verified later and debugged once the implementation is finished to ensure a successful build

**Comment by richardxd** [comment]
Given that some aspects of the implementation remain unclear, the tests are to be updated once the implementation is done. For the sake of this sprint, I will close it, and I have checked that the build is successful with the added test module.

**Comment by richardxd** [comment]
The tests have been edited by Carlos to accommodate for the changes in our struct design.

**Comment by ecoble** [comment]
Issue Score: ✔️++
Comments:
Great work, especially with your updates!
