### ISSUE TITLE
Implement basic functions for player effects

### ISSUE THREAD

**Issue by sumedhsarwate** [uchicago-cs/chiventure#608]
As per our team meeting on Saturday, I will be implementing basic functions for player effects, such as new, init, free, and getter functions.

**Comment by sumedhsarwate** [comment]
@Rusah1129 and I created a new branch for effects, and once the global effects struct is added, I will add the functions for effects

**Comment by sumedhsarwate** [comment]
I added the implementation for the global and player effects new, init and free functions, but I realized that I won't be able to check if an effect has already been added to the global effects hash table in the game struct in global_effect_init, so I'm going to add an add_effects_to_game function to game.c

**Comment by sumedhsarwate** [comment]
I had to change the function name for effect_new to stat_effect_new because effect_new() already exists in game-action. (The change is in commit f495c15)

**Comment by sumedhsarwate** [comment]
`effect_free` has been renamed to `delete_single_effect` and `global_effect_free` has been renamed to `delete_single_global_effect` to make the purpose of the function more clear. Each now also takes in a pointer to a hash table as a parameter to delete the single effect from the hash table. The changes can be seen in 3953d6a

**Comment by sumedhsarwate** [comment]
Closing Statement: The new, init, and free functions for global effects and the new, init and free functions for global and player effects have been implemented along with their tests. I did not see a need at the moment for getter functions, so those have not been implemented, but if we see a later need to have those functions, a new issue can be created.

**Comment by ecoble** [comment]
Issue Score: ✔️++
Comments:
Great work, especially with your updates and closing statement!
