### ISSUE TITLE
Design/Implement a global data structure for game stats

### ISSUE THREAD

**Issue by carlosazpurua1004** [uchicago-cs/chiventure#609]
Aftering meeting with Professor Borja, he explained that some stats might contain global properties (like global max values), so it would be a good idea to implement a global table of all stats in a game written in chiventure. 
This table would keep track of such global properties for every stat, and whether or not a stat is in the game at all, since in our current implementation of stats, different players/npcs can have different stats.

Issue will be resolved by a pull request with the data structure written, and possibly some stubbed functions if time permits.

**Comment by richardxd** [comment]
Updates on stats_global struct 
e292496
eee554c

**Comment by richardxd** [comment]
The bugs have been removed after I figured out how to make Chiventure. The stubbed out functions in stats.h corresponds to stats.c right now ,and they are ready to be implemented.

**Comment by carlosazpurua1004** [comment]
The struct and stubs of functions have been merged in https://github.com/uchicago-cs/chiventure/pull/653

**Comment by ecoble** [comment]
Issue Score: ✔️++
Comments:
Great work, especially with your summary!
