### ISSUE TITLE
Design special WDL handling for custom action sequences

### ISSUE THREAD

**Issue by namanhd1nh** [uchicago-cs/chiventure#613]
Now that WDL team has met and designed the structs and a rough idea of the interface for other teams to access WDL data, the next goal is to add some special handling for custom action sequences.

This is because most other objects which have lists as attributes only have 1-layer-deep lists. (The lists only store literal string values, like object IDs to refer to). However, custom action sequences are denoted with a list of JSON objects which have further keys and values (block name, and block parameters). 

The plan is to either work off of structures that Custom Actions team has set up for action blocks (to avoid having to go through our own WDL data wrappers), or make new ones that can easily be passed along to Custom Actions team for their parsing into an AST.

**Comment by namanhd1nh** [comment]
I pushed some skeleton functions and the corresponding structs to a new branch `wdl/action-block-list`. The implementation of the sequence creation function is pending, since it depends on the JSON object representation of the WDL data, which is a work-in-progress for now.

**Comment by namanhd1nh** [comment]
I've since found out that the WDL generic object struct (`obj_t`) and its attributes (`attribute_t `) which other members are working on are capable of representing nested objects, and I have also added in support for a *list* of objects (not necessarily of the same type) acting as an attribute (see commit https://github.com/uchicago-cs/chiventure/commit/43a62ac7fe9143344e52490baf6de4d1dd659c5b in [this code](https://github.com/uchicago-cs/chiventure/blob/wdl/libobj-hash/src/libobj/sandbox/sample_obj_documentation.h)) in the `wdl/libobj-hash` branch). 

This means that our generic JSON object representation is now fully capable of representing these action sequences and there is now no longer need for new special structs. All that's needed to hand over to the Custom Actions team are some shorthand functions to help them access the right keys and get to the (utlist) sequence of attributes. This should be incorporated into our object and attribute interface; this part of the work can probably be incorporated into the corresponding issue, or made as a separate new issue in the next sprint (as this one concerns the structs). As such, I am now closing this issue.

(However, I will leave the action_block_sequence branch up, as reference for the interface later, or when it needs to be revisited in case using our generic obj_t interface turns out to be insufficient still.)

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Great work! The title and description of this issue are very clear and easy to understand, and the updates and closing statement are very nicely elaborated, so that anyone reading this issue understands exactly what happened and why it's no longer relevant.
