### ISSUE TITLE
Update the skeleton code testing suite to add more nuanced tests for functions that act upon allskills_t struct. 

### ISSUE THREAD

**Issue by steeltrapp** [uchicago-cs/chiventure#618]
I will add, and improve tests in the testing suite for the following functions:
pop_passive_skill(),pop_active_skill(),push_passive_skill(),pop_active_skill(), has_active_skill(), and has_passive_skill() that test functionality in more complex situations that are not currently tested, such as when multiple items are in the list, and I will further test memory-related functionality in each function. I will provide updates to this issue whenever a function's tests are completed. Finally, this task will culminate in a pull request that contains the new testing suite.

**Comment by steeltrapp** [comment]
During the completion of this task, the skeleton code was updated such that these functions and structs are no longer in the code. Furthermore, other team members have already added unit tests for the new skeleton code. After consulting with our team's senior developer, I am closing this issue as it is no longer relevant.

**Comment by firatciftci** [comment]
Issue Score: ✔️

Comments:
Good work on this issue! The only things I'll point out are that the summary card should have more detail in terms of the purpose, the steps needed to be taken, and the goal of the issue, and that the issue should have had some update comments regarding your progress with the task, as it is difficult to quantitatively and qualitatively assess the issue with just a summary and a closing comment.
