### ISSUE TITLE
Visualizing skill trees

### ISSUE THREAD

**Issue by VannStrasen** [uchicago-cs/chiventure#619]
Many games that have skills allow for a neat way of visualizing these skills in what's called a skilltree. In order to do so there are a few steps that need to be taken:

1) Talk with the graphics to see if this is something they think is possible by the end of class, as well as asking them what would be the best way to form these structs so that the graphics team can easily run with the format of the skilltrees.
2) Whether possible or not, I should create a skilltree struct that can most easily be used by the graphics team when it is being visualized. 
3a) If it is not possible, the code can be left for next year's class to work on.
3b) If it is possible, I should finish working on the structs soon so that the graphics team can visualize the skilltree. 

I will be working on this project following these steps, and this issue might be pushed partly into sprint 4 because it is a larger project.

**Comment by VannStrasen** [comment]
I talked with @seanrryan and @aherman33 about what a good skill trees struct would look like, and wrote additional code in branch skilltrees/skill_trees based off of their recommendations. The graphics team should feel free to look at that branch to see what the skilltrees struct will look like so that they can think about what more they might need/begin their implementation phase. 

Throughout the process I also made critiquing comments/additional edits about our current code partially related to the skill trees. Comments imply 1) skilltrees needs to discuss this topic, but 2) the graphics team doesn't need this part fully implemented to begin their work.

**Comment by firatciftci** [comment]
Issue Score: ✔️

Comments:
Good work on this issue! The only things I'll point out are that the title is too generic (ideally it should be a proper sentence), and that it needs to state a clear and also non-generic goal. Another thing is that if the issue mentions a meeting, there should be comments about who the meeting was with, what were the meeting points, and what are the exact outcomes of the meeting.
