### ISSUE TITLE
Writing tests and sample Lua files to test the Lua scripting functionality that custom script module provides, specifically the int_t_get, string_t_get, bool_t_get function

### ISSUE THREAD

**Issue by tammytran134** [uchicago-cs/chiventure#620]
In issue #594 , we created a custom script module to implement pseudo-types that, in short, contain either the underlying type or a Lua script. In this module, each type has a get() function that, depends on whether the union contains the underlying type itself or a Lua path, will return the type.
I'm responsible for writing tests for cases when the pseudo-type union contains a Lua path, and thus have to make sure that Lua library is linked successfully to the build process (Cmake), and the communcation between .c files and .lua files so Lua scripting can actually provide the functionality we expect it to have (return desired type).
I will know the task is successful when Lua library linking works and all the tests that involve calling Lua files pass.

**Comment by tammytran134** [comment]
Managed to link Lua library to Chiventure. Here's the wiki page on how to do so: https://github.com/uchicago-cs/chiventure/wiki/Linking-Lua-library-to-Chiventure-on-CSIL-machine

**Comment by tammytran134** [comment]
Finished writing tests that involve Lua files. All tests have passed.

**Comment by firatciftci** [comment]
Issue Score: ✔️+

Comments:
Great work! The only thing I'll point out is that the issue should have had a longer and more detailed closing comment to describe the exact changes.
