### ISSUE TITLE
Document the stat struct design and the purposes of functions.

### ISSUE THREAD

**Issue by richardxd** [uchicago-cs/chiventure#634]
Our team has implemented stats_t and stats_effect_t struct that focuses primarily on the RPG side of the game. This issue is hence created after we are getting started to implementing functions. There will be a wiki page that explains how the struct works and what the functions do.

**Comment by richardxd** [comment]
The stats_global struct has just been added. Though effects_global struct has not been added, they should behave similarly. I will start documenting the struct right away.

**Comment by richardxd** [comment]
[text](https://github.com/uchicago-cs/chiventure/wiki/RPG-stats-implementation:-Current-stats-struct-design)

**Comment by richardxd** [comment]
[Link to the wiki page](https://github.com/uchicago-cs/chiventure/wiki/RPG-stats-implementation:-Current-stats-struct-design)
The wiki page has updated the global effect implementation. Although certain design concerns raised by Carlos remain unclear, I will close this issue for now for this sprint. There will another issue in sprint 4 that addresses those concerns and will be documented accordingly.

**Comment by ecoble** [comment]
Issue Score: ✔️++
Comments:
Great work, this will be helpful for future teams!
