### ISSUE TITLE
Enhance the current implementation for the module of NPC movement through rooms.

### ISSUE THREAD

**Issue by shayna-k** [uchicago-cs/chiventure#644]
The current implementation for NPC movement through rooms includes a very basic set of functionalities that simply set up the possibility for npcs to exist in different rooms (this is referenced in the following issue: #572. This task is to enhance this and add functionality to actually move the NPCs through rooms and update the hash table that stores rooms with the respective NPC hash tables. This will take a significant amount of implementation given that it would require interacting with both the npc module, room module, as well as our own module that deals with npcs in rooms. We plan on implementing and testing this code by the end of this sprint, culminating in a pull request for this issue.

**Comment by shayna-k** [comment]
We have not been able to begin implementation of this task since we are currently in the process of fixing unexpected bugs that came up in the code of our previous [pull request](https://github.com/uchicago-cs/chiventure/pull/641), after editing the locations of our files. 

Implementations regarding this movement feature are, hence, on hold for the time being.

One the pull request has been approved with correct code, we shall continue working on this feature. Updates shall follow.

**Comment by shayna-k** [comment]
We are in the process of fixing all the bugs in the previous code ([pull request](https://github.com/uchicago-cs/chiventure/pull/641)). We have managed to sort out a lot of them, but are having some issues with the hash implementation.

We have also begun working on outlining what we would need to implement code for this issue and will keep the [wiki](https://github.com/uchicago-cs/chiventure/wiki/RPG-NPC:-Independent-Feature:-NPC-Movement-Design-Document) for the NPC movement module updated.

**Comment by shayna-k** [comment]
Our previous pull request was merged.

We have created a new branch [ [rpg-npc/npc_movement_adv](https://github.com/uchicago-cs/chiventure/tree/rpg-npc/npc_movement_adv) ]. 
We will be implementing this feature as well as we can in the little time we have and update this page in the process.

**Comment by philipchenaux** [comment]
We have implemented the main function that allows for npcs with a definite movement type to move between rooms in the following function alongside its tests:
```C
int move_npc_def(npc_mov_t *npc_mov)
```
For this sprint, we have decided that we will just focus on implementing this feature for npcs with a definite movement type, and therefore we will add the feature of implementing this for indefinite movement types as an issue on the backlog for the next class. We will update the main wiki covering this issue.

**Comment by philipchenaux** [comment]
We have submitted a pull request #775 which covers the above function and the implementation of further tests from the issue #645.

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Great work!
