### ISSUE TITLE
Implement more robust tests for npc movement between rooms

### ISSUE THREAD

**Issue by philipchenaux** [uchicago-cs/chiventure#645]
For the moment, the test for the code that addresses the implementation of npcs moving between rooms is not very robust #572. What I mean by this, is that it only tests whether the function works at a superficial level, instead of inspecting the new structs that are created (e.g. iterating through the linked lists and seeing whether the code has properly implemented the linked list functionalities). Therefore in this sprint we would like to a series of more robust tests in particular for the functions of higher abstraction. I will largely be working on the functions:
```C
int extend_path_def(npc_mov_t *npc_mov, room_t *room_to_add);

int extend_path_indef(npc_mov_t *npc_mov, room_t *room_to_add, int time);

int register_time_in_room(npc_mov_t *npc_mov, room_t *room, int time);

int reverse_path(npt_mov_t *npc_mov);
```
As well as the `npc_move()` function that we will be working on in this sprint as referenced in issue #644

**Comment by philipchenaux** [comment]
I have started to improve the testing algorithms in the [rpg-npc/npc_room_movement](https://github.com/uchicago-cs/chiventure/tree/rpg-npc/npc_room_movement) branch of chiventure. In particular I have added more robust tests to the more complex functions such as:
```C
int register_time_in_room(npc_mov_t *npc_mov, room_t *room, int time);

int add_npc_to_room(npcs_in_room_t *npcs_in_room, npc_t *npc)
```
I have added HASH_FIND functionalities that improve the accuracy of the tests that we are running. Now, I plan to implement testing functions that will include utlist functions for similarly complex functions including:
```C
int extend_path_def(npc_mov_t *npc_mov, room_t *room_to_add);

int extend_path_indef(npc_mov_t *npc_mov, room_t *room_to_add, int time) ;

int reverse_path(npc_mov_t *npc_mov)
```
These tests will be slightly more complex as it will require iterating through the lists and checking each input within the linked list.

**Comment by philipchenaux** [comment]
I have moved to the new branch: [rpg-npc/npc_movement_adv](https://github.com/uchicago-cs/chiventure/tree/rpg-npc/npc_movement_adv) where I will be implementing further tests alongside implementing the issue #644.

**Comment by philipchenaux** [comment]
I have been working on this issue alongside issue #644 which have just been submitted in the pull request #775. I was able to implement more robust tests for all the remaining functions that used either the utlist or uthash functionalities, in particular:
```C
int register_npc_room_time(npc_mov_t *npc_mov, room_t *room, int time)

int extend_path_def(npc_mov_t *npc_mov, room_t *room_to_add)

int extend_path_indef(npc_mov_t *npc_mov, room_t *room_to_add, int time)

int reverse_path(npc_mov_t *npc_mov)

int move_npc_def(npc_mov_t *npc_mov)
```
All of these function have been robustly tested, therefore showcasing the fact that the hash and linked list implementation has been used correctly. The tests have all passed under the current pull request, therefore I will close this issue as I have sufficiently tested all the functions that I have written. In the future if additional functions are written for this module, similar robust tests are required.

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Good work!
