### ISSUE TITLE
Add AST_block_t *next capabilities to AST_block_t interface

### ISSUE THREAD

**Issue by emmamedeiros** [uchicago-cs/chiventure#648]
We will be using UT lists in order to add an AST_block_t *next parameter into the existing AST_block_t struct. In doing so, we also want to spend time learning more about this functionality in order to implement this function in a way that will best serve eventual parsing capacities for custom-actions.

**Comment by emmamedeiros** [comment]
The ast_block.h and ast_block.c files have been implemented, the AST block struct having added an linked list of AST blocks (AST_block_t **next), as well as an integer to specify the number of AST blocks in a sequence (held within the struct) in order to aid in the implementation of the AST_block_free function. The testing for the AST block module will now be refactored in order to support this new struct.

**Comment by emmamedeiros** [comment]
Testing has been completed and debugged, and this updated AST block module will now be submitted as a pull request.

**Comment by emmamedeiros** [comment]
The pull request has been submitted. A minor change to the custom action struct, the addition of a UT hash handle in order to aid in storing custom actions, has also been added to the custom action module in this pull request.

**Comment by emmamedeiros** [comment]
During the pull request, the AST block was slightly altered to include a double linked list, so that an AST block now contains a pointer to an AST *next as well as an AST *prev. These changes are reflected in the implementation that was merged into dev. Our team also realized that only custom_action.h needed to be altered to add a hash handle to the custom actions struct, and so the presence of a UT hash handle in the new and init functions and related tests for the custom actions struct were removed. The pull request has now been merged into dev, and this issue will now be closed.

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Good work! The mention in the closing statement about the decision to add a `prev` field was a very helpful thing to note.
