### ISSUE TITLE
Integrate the NPC movement module and structs in the main NPC struct

### ISSUE THREAD

**Issue by shayna-k** [uchicago-cs/chiventure#649]
Our team implemented spawning NPCs in rooms and are working on movement of NPCs through rooms. We created one consolidated struct that includes details of the movement path of an NPC and have created types for it, which is included as well. This struct would define the movement of a particular NPC and, hence, it would be appropriate to include this in the NPC struct. We will speak with the NPC team on this and implement it thereafter, according to their view and implementation as well.

**Comment by shayna-k** [comment]
We have not been able to begin with this task since our code for the [NPC movement feature](https://github.com/uchicago-cs/chiventure/wiki/RPG-NPC:-Independent-Feature:-NPC-Movement-Design-Document) has not been finalized yet. 

The current code in our [pull request](https://github.com/uchicago-cs/chiventure/pull/641) might be subject to changes in structs, functions, or certain implementation. This is why we cannot begin integration in the NPC struct at the moment.

As soon as our code is finalized, we will correspondence with the NPC team and update this page regularly.

**Comment by shayna-k** [comment]
This task was on standby since we wanted to implement the feature correctly and then move on to collaborating with other teams (and we would have to collaborate with the NPC team for this issue). 

It is very late in the sprint and it is not feasible for other teams to integrate our structs. I will be moving this to the backlog since it seems to be something that would be needed for the complete implementation of our feature. 

For the demo, we will be finding a way to integrate it such that we can work with the current code. If we find that we should add or change something else with respect to this issue, we will be updating the page.

**Comment by torresszy** [comment]
The integration of NPC movement module into the main NPC struct has been achieved in #879, and this issue will therefore be closed.
