### ISSUE TITLE
Environment interactions based on skill characteristics

### ISSUE THREAD

**Issue by ly-chen** [uchicago-cs/chiventure#661]
Many games have skills with unique or common characteristics that can be used and/or trigger interactions with the environment; for example, certain types of combat spells being able to destroy or change certain compatible items, certain types skills (like fire) being able to change the environment (lighting torches), or certain areas that are locked without certain skills (and the absence or presence of certain skills may also trigger hints and/or NPC interactions).

It may be prudent to research how other games implement this sort of skill-characteristic-related environment interaction. My hunch is that certain groups of skills have optional tags / identifiers that can be read to understand if a skill is part of a group that can be used for a specific environment interaction. Currently, we do not have a global implementation of such a tag; theoretically, skills can affect the environment on a case-by-case basis by modifying the skill function itself, but it may be simpler and more scaleable to add an optional tag in our skill data structures.

I intend to:
1. Research implementation strategies to determine if this task is feasible by the end of class
2. Create basic implementational changes if feasible

This task may be split into smaller tasks depending on how large the task gets.

**Comment by ly-chen** [comment]
With regards to my stated goals:

1. I documented several examples of the noted functionality as well as two potential implementational strategies to achieve the functionality in [this wiki page](https://github.com/uchicago-cs/chiventure/wiki/Environment-interactions-based-on-skill-characteristics).

2. Based on my research, I concluded that while this can be implemented by modifying skilltree and skill structs, this would probably not be the most scaleable strategy. As such, I noted that a better method would be to create WDL functionality that could parse skill types in skill functions, which would not involve changing skill structs, but instead involve changes to skill design and WDL/WDL++.

**Comment by firatciftci** [comment]
Issue Score: ✔️+

Comments:
Good work! The only thing I'll point out is that there the title is a bit too generic; ideally we should be understand which team the issue is tied to from the title and that it should be a clear goal statement.
