### ISSUE TITLE
Implement skill TREES and associated leveling/skill acquisition functions, including unit tests

### ISSUE THREAD

**Issue by jackandthebean** [uchicago-cs/chiventure#663]
# Implement skill **TREES** and associated leveling/skill acquisition functions, including unit tests
### What
We successfully merged our skeleton code #601, which only deals with individual skills and player skill inventories. The next step is to implement a general skill tree of acquirable skills for each player in a game.
### Why
Skill trees are the MEAT of our team's chiventure feature!!

**Comment by jackandthebean** [comment]
Towards the end of Sprint 3 I created a new [branch](https://github.com/uchicago-cs/chiventure/compare/skilltrees/skill_tree) to accomplish the items described in the description of this task. At the end of Sprint 3 I was able to add all the function implementations, refactor the code to use helper functions that eliminated repeat code, and separated the skill trees implementation into better organized modules. Some tests still need to be written and some parts of the already written code need to be addressed still: @VannStrasen has written these notes up in comments on the header files.

**Comment by jackandthebean** [comment]
Our team met today to discuss our progress, after which @VannStrasen and I reviewed some final comments and changes we would need to make to our code, before making our last *significant* PR for this skill tree code.

**Comment by jackandthebean** [comment]
After meeting again with @firatciftci , we decided to separate this issue to make our pull requests more incremental. I've updated our `skilltrees/skill_tree` (4afd2947444c8aac2e0daec627def268a0de2dab) branch to be ready for our first PR, which will add the preliminary new skill tree code I wrote over the past weekend, incorporating some but not all of the edits @VannStrasen made. We will incorporate the rest of these edits in a subsequent pull request, as the changes in queue are already substantial.

**Comment by jackandthebean** [comment]
I've now made that first skill **trees** PR: #697.

**Comment by jackandthebean** [comment]
### #697 was merged, so I am closing this issue. This PR merge accomplished the following.
Beyond the addition of `skilltree.h` and `skilltree.c` files that contain the start of the new skill trees implementation, our previous code was refactored:
* `stdst.h` and `stdst.c` contain common helper functions
* `skill.h` and `skill.c` contain all the previously written functions having to do with individual skills
* `inventory.h` and `inventory.c` contain all the previously written functions having to do with skill inventories, with the addition of a `skill_levels_update()` function to update levels of all skills in an inventory
* All unit test files were removed for this PR, as @michaelleestuy and @steeltrapp are updating our unit tests in a separate PR
* Various functions/parameters were renamed for clarity, according to @firatciftci's suggestions

**Comment by firatciftci** [comment]
Issue Score: ✔️+

Comments:
Good work! The only thing I'll point out is that the summary should have been a bit more detailed; ideally, it is a paragraph long and outlines the purpose and the exact changes of the PR.
