### ISSUE TITLE
Design support to stack multiple of the same item in a room/player

### ISSUE THREAD

**Issue by ericyc16** [uchicago-cs/chiventure#666]
From issue #183: "Currently, the game-state modules do not support stacking of multiple items. For example, two apple items associated with a room cannot both be called "apple""

Design a way to allow multiple items of the same name to exist in the same room/inventory of a player.

A potential idea is that if a player wants to interact with an item identical to another in the room, one item is chosen randomly. For example: there are two apple items on the same table. If the player wants to "TAKE apple," one of the apples is chosen randomly. Something similar would occur when choosing an item from several identical ones from the player's inventory.

**Comment by ericyc16** [comment]
After brainstorming some ideas, I'm thinking of adding an additional field to the `item_t` struct. This would be a pointer to another item, which would point only to an item with the same `item_id` as the current item. The head of this list would be stored in the `item_t` hashtable.

I have more details about this design written out at [this wiki](https://github.com/uchicago-cs/chiventure/wiki/Action-Management---Item-Stacking-Design).

Another note: I found that the NPC team has an inventory field in the NPC struct, similar to the inventory for a player. It would probably be a good idea to allow stacking in NPC inventories as well. 

My next steps are to ask my team for feedback on my design and to further flesh out the design. If I decide I need to edit the NPC inventory, I will be sure to get in contact with that team.

**Comment by ericyc16** [comment]
[The wiki](https://github.com/uchicago-cs/chiventure/wiki/Action-Management---Item-Stacking-Design) has again been updated with a more fleshed-out design plan. After implementation, multiple items with the same `item_id` will be able to exist in a game, room, player's inventory, and NPC's inventory. Additionally, I have reached out to the NPC team to inform them that I will be editing some of their code to support stacking in an NPC's inventory. 

I feel satisfied with this design, so I am closing this issue.

A brief summary of my design:
- Add a new field to the `item_t` struct, `item_t *next`, which points to an item with an identical `item_id` (if such an item exists)
- Refactor some current code into three new functions: `add_item_to_hash`, `remove_item_from_hash`, and `convert_item_hash_to_item_list`
- Update refactored code to take into account possibility for multiple items with identical `item_id`s
- Update `do_item_action` and `do_item_item_action` to try the action on all items with identical `item_id`s until a successful action occurs
- Update `look_operation` to mention that there are multiple of an identical item if the user specifies "look [item]"
- Update & write tests

Todo:
- Implementation and unit tests for item stacking (this has been created into a separate issue #703)

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Great work! This issue does a great job of providing tangible updates, even when code isn't involved.
