### ISSUE TITLE
Create a sample game to demonstrate new action management mechanisms

### ISSUE THREAD

**Issue by ericyc16** [uchicago-cs/chiventure#667]
While I have written tests to ensure that the end conditions mechanism introduced in pull #611 works as expected, they have yet to be tested in an actual Chiventure game. Write a sample game that utilizes end conditions to demonstrate how they work. This will require hard coding several components of the game because there is currently no WDL support for game authors to define end conditions.

**Comment by ericyc16** [comment]
I've added the rest of the action management team to this issue so that this sample game can incorporate all of their features that we've been working on all quarter

**Comment by ericyc16** [comment]
I've created an `examples` subdirectory in the `action_management` directory, which contains the file `spring2020-demo.c`. I've also added/updated the relevant `CMakeLists.txt` files so that a `spring2020-demo` executable is built when `make examples` is run from the command line. This executable can be run by entering `./src/action_management/examples/spring2020-demo` into the command prompt. For now, this executable simply outputs the message "Hello world!", but that was just to ensure I got all the CMakeLists things right.

**Comment by ericyc16** [comment]
I fixed `spring2020-demo.c` to set up and run a chiventure game from a WDL file. The WDL file I wrote for our demo is a simple game where the player eats dinner and then goes to bed. This will demonstrate our new features in the following ways:
- End conditions - dinner must be eaten before the game can be over (this along with going to the bedroom)
- Inventory conditions - a fork must be in the inventory before eating spaghetti or salad
- Conditional room connections - a door must be open before entering the bedroom
- Action synonyms - show that walk/go perform identical functions, show that eat/consume/use/drink perform identical functions
- Stackable items - put more than one fork in the kitchen

The next step is to hard code the features implemented by our team that are not currently supported by WDL/CLI. These include:
- End conditions
- Inventory condition
- Conditional connection between room
- CLI support for synonyms for "EAT" ("CONSUME", "USE", "DRINK")
- Some other small attributes/conditions/effects that currently cannot be specified by WDL

**Comment by ericyc16** [comment]
Various attributes/action conditions/action effects have been hard-coded into the game. I ran a playthrough of the binary, and they all seem to be functioning as I expect them to. The next step is for me to hard-code end conditions.

**Comment by ericyc16** [comment]
End conditions have been hard-coded into the game. Again, based on a few playthroughs, everything seems to be functioning as expected. 

The next steps are:
- Finish implementation of other features and get them pulled into the dev branch
- Hard-code these features into the game

**Comment by ericyc16** [comment]
After talking to Isaac, it sounds like he currently has a PR open to merge CLI support for "EAT" synonyms into dev. Therefore, it should be unnecessary to monkeypatch those in, and the skeleton function for that was removed

**Comment by ericyc16** [comment]
CLI support for "CONSUME" synonyms have been merged with dev, so now they're included in this branch as well. They seem to work as expected

**Comment by ericyc16** [comment]
Inventory conditions and stackable items have been merged with dev. I monkeypatched inventory conditions into the .c file, and added an identical object to the wdl file. After a couple of runthroughs of the game, everything seems to work as expected

**Comment by ericyc16** [comment]
We weren't able to get conditional room connections added to the demo in time, but all other features have been added to the demo. This code has been pulled into the dev branch, so I am closing this issue.

In summary, this issue accomplished the following:
- Created a sample WDL file
- Created a demo game in the `src/action_management/examples` directory
- Hard-coded the following features not currently supported by WDL:
  - Attributes, conditions, and effects
  - End conditions
  - Inventory conditions

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Great work! This issue is clear and well-written throughout, and the updates are very useful for understanding what ultimately in PR.
