### ISSUE TITLE
Finish updated testing/implementation of single/multi-room autogeneration, make a PR

### ISSUE THREAD

**Issue by bryan22lee** [uchicago-cs/chiventure#671]
Now that the context structs of the [gen_structs](https://github.com/uchicago-cs/chiventure/blob/dev/include/openworld/gen_structs.h) module have been defined and PR-approved, we want to update the [test_autogenerate.c](https://github.com/uchicago-cs/chiventure/blob/openworld/autogen/tests/openworld/test_autogenerate.c) tests for the [autogenerate.h](https://github.com/uchicago-cs/chiventure/blob/openworld/autogen/include/openworld/autogenerate.h) module in the [openworld/autogen](https://github.com/uchicago-cs/chiventure/tree/openworld/autogen) branch. We want to ensure all tests pass and make a Pull Request for the [autogenerate.h](https://github.com/uchicago-cs/chiventure/blob/openworld/autogen/include/openworld/autogenerate.h) module (single-room autogeneration). Another goal for this PR is to use single-room generation to support a simple multi-room generation model; it generates rooms _around_ the current room of the game when the current room is a "dead end", i.e. there are no outward paths. multi_room_generate() in [autogenerate.h](https://github.com/uchicago-cs/chiventure/blob/openworld/autogen/include/openworld/autogenerate.h) should iterate through all the speclist items (roomspec_t) and generate rooms _around_ the current room for exploration. The hope is to scale this for "openworld" generation in the future. We then want to work on merging this implementation with the [default_rooms.h](https://github.com/uchicago-cs/chiventure/blob/dev/include/openworld/default_rooms.h) and [default_items.h](https://github.com/uchicago-cs/chiventure/blob/dev/include/openworld/default_items.h) module to pull from and autogenerate the desired room. This issue will be linked to the eventual Pull Request.

**Comment by bryan22lee** [comment]
PR has been made and merged into dev, and it can be seen [here](https://github.com/uchicago-cs/chiventure/pull/681). Some major updates to the [autogenerate](https://github.com/uchicago-cs/chiventure/blob/dev/include/openworld/autogenerate.h) module are (1) we no longer generate rooms in "dead end" situations; it is better to generalize room generation for any room as long as there is room for more paths to be added. (2) room_generate() now checks the current room of the game for path directions that are already there (path_exists_in_dir()), and randomly generates both forward and backward paths (with opposing directions) for the newly generated room. (3) added a num_built field to roomspec_t struct that keeps track of the number of times the roomspec is used to generate a room. It is appended to the room_name to create a _unique_ room_id to pass into roomspec_to_room. The num_built field of the input roomspec is incremented each time it is passed into the low-level roomspec_to_room() function to keep track of the number of times it was used for generating rooms, either in room_generate() or multi_room_generate().

See [autogenerate.c](https://github.com/uchicago-cs/chiventure/blob/dev/src/openworld/src/autogenerate.c) to see the implementation of the above changes.

**Comment by dwahme** [comment]
Issue Score: ✔️+

Comments:
Great job! Here are a few things you may want to improve in future issues:

Your issue did not include any status updates between the opening of the issue and the closing of the issue (and this issue was not small enough to justify having no status updates at all). If you make any intermediate progress before finishing the task, then it should be documented on the GitHub issue via a comment.
