### ISSUE TITLE
Get CLI/split screen example into examples folder

### ISSUE THREAD

**Issue by xmvalencia** [uchicago-cs/chiventure#676]
_Sprint Summary:_
A CLI screen with an image is a large checkpoint for the graphics team. This means being able to display graphics and the command line interface at the same time. An example of what that looks like has been previously made by members within the graphics team, the main hurdle for this sprint is to implement the cli/split screen into examples, this will be a major step into integration into chiventure. This will allow us to map dependencies between the ui module and the larger chiventure program. 

_Products of Sprint:_
This main goal of this issue is to be able to integrate it into chiventure and create examples into the examples folder. 

_Example Image:_
![image](https://user-images.githubusercontent.com/52059114/83214801-507fdd00-a11a-11ea-9658-88f34f147e99.png)

**Comment by xmvalencia** [comment]
_Sprint Summary:_
The CLI screen with raylib textures is a large checkpoint for the graphics team. This means being able to display graphics and the command line interface at the same time. The main hurdle for this sprint was trying to integrate the CLI module into our sandbox example from an [earlier issue](https://github.com/uchicago-cs/chiventure/issues/675) this was a major step for developing graphics into chiventure. This will allow us to map dependencies between the ui module and the larger chiventure program. 

_Pull Request Summary:_
The pull request can be found [here](https://github.com/uchicago-cs/chiventure/pull/801)

_Product:_
![ezgif-5-b85fc8197660](https://user-images.githubusercontent.com/52059114/84074073-d0ae0a00-a986-11ea-88de-12cba1a47fef.gif)

**Comment by ecoble** [comment]
Issue Score: ✔️++
Comments:
Great work here, and your summary and closing statement are really good!
