### ISSUE TITLE
Implement OpenWorld Sample Game

### ISSUE THREAD

**Issue by navila-luna** [uchicago-cs/chiventure#678]
Purpose is to create a sample game that demonstrates the work that the OpenWorld team has done since sprint 1. This task requires default rooms and autogeneration module to be completed beforehand.  This demo will then be used to showcase what we did in our team presentation.

**Comment by navila-luna** [comment]
As a team we decided to use an existing test.wdl instead to run chiventure with autogenerate. And that room B calls room_generate and room C calls multi_room_generate so we show both functions in autogenerate.h. While we tried to, we did not end up showcasing the NPC Mocks in the demo because the pr is still in process. Items and item descriptions were shown in the demo. This demo was recorded by Bryan.

**Comment by navila-luna** [comment]
To conclude, the demo was completed and presented in the recorded presentation. The length of the video demo is about 6 minutes and showcases multiple rooms.

**Comment by navila-luna** [comment]
While we tried to, we did not end up showcasing the NPC Mocks in the demo because the pr is still in process.  To conclude, the demo was completed and presented in the recorded presentation. The length of the video demo is about 6 minutes and showcases multiple rooms and items in those rooms.

**Comment by dwahme** [comment]
Issue Score: ✔️+

Comments:
Great job! Here are a few things you may want to improve in future issues:

The title of an issue has to convey what the issue will be producing. In the future, try using simple titles with a "Verb-Object" structure that clearly states what you will be doing in the issue (e.g., “Design and implement a ‘circle’ module”, “Research libraries for drawing simple geometric shapes”, etc.)
