### ISSUE TITLE
Create Design Documents for Future Students 

### ISSUE THREAD

**Issue by nmartinez233** [uchicago-cs/chiventure#683]
At the beginning of the quarter, we created design documents outlining the modules and functions inside of those modules. Since implementing them (mostly in our last sprint) some structs and functions have been changed, deleted, and new functions added. Because of that, especially for next year's rpg-battle team, it is important to document the code we have written thus far.

**Comment by nmartinez233** [comment]
After some final pull requests, I updated the design document which includes the most up to date structs, functions and their purposes.

**Comment by dwahme** [comment]
Issue Score: ✔️+

Comments:
Great job! Here are a few things you may want to improve in future issues:

Status updates on an issue should have something tangible to share.
