### ISSUE TITLE
Update documentation for the openworld module to more accurately represent the current state.

### ISSUE THREAD

**Issue by edward3-uchi** [uchicago-cs/chiventure#684]
After some pull requests and many changes to the module, the anticipated designs from the design documents aren't necessarily accurately representing our code anymore. We need to update the design documents to show the state of the structs, the autogeneration module and our method of pulling room details into openworld.

**Comment by edward3-uchi** [comment]
Going to take a look at the original design document and make it more comprehensive. Going to adjust the generation structs document. Going to work on the autogeneration document and adjust expectations/current state.

**Comment by edward3-uchi** [comment]
Finished the [wishlist](https://github.com/uchicago-cs/chiventure/wiki/Openworld:-Feature-Wishlist), There's a bunch of stuff on here that we would love to see added to openworld. last issue :( its been great!

**Comment by dwahme** [comment]
Issue Score: ✔️++

Comments:
Great job! Well done keeping this task straightforward and to the point.
