### ISSUE TITLE
Finalize the new object structs

### ISSUE THREAD

**Issue by noahklowden** [uchicago-cs/chiventure#685]
In order to implement the WDL++ system, we need to redesign the interface for libobj to better suit accessibility by other teams. Currently, in #565, some basic structs were set up to store this information along with the declaration of some basic functions. These can be found [here](https://github.com/uchicago-cs/chiventure/blob/wdl/libobj-interface/src/libobj/sandbox/sample_obj_documentation.h).

By Thursday evening, the new structs created to replace ones in the current libobj file should be finalized. Part of confirming this task is to reach out to Borja to get his input on the final version of the structs. This can be done via message over slack instead of meeting, as we are low on time.

**Comment by noahklowden** [comment]
At the suggestion @ela-ine, moved the union for data to be stored in attributes out of the attribute_t struct so it could be used on its own as parameters. This should finalize the structs for the new object system, which means that I will send them to @borjasotomayor for review.

I also moved the code from the libobj/sandbox directory to the include/wdl and renamed the file to [object.h](https://github.com/uchicago-cs/chiventure/blob/wdl/libobj-interface/include/wdl/object.h) as we are transitioning this code into more practical, final code.

**Comment by noahklowden** [comment]
Borja reviewed the code and gave it the okay. After some minor revisions of the comments for legibility, it should be good to go. I have submitted the pull request to merge it with dev.

**Comment by noahklowden** [comment]
Branch was successfully merged. Next step is to finish up the low level implementation of the functions in #687.

**Comment by MaxineK36** [comment]
Issue Score: ✔️+

Comments:
Good work! The link in the closing statement to the next issue is very helpful. One thing to work on for future issues: Even though you can add labels to issues to categorize them, you should avoid titles that could plausibly apply to multiple teams (in chiventure, many teams have an object struct, which makes this ambiguous)
