### ISSUE TITLE
Create high level interface for teams to be able to access libobj attributes

### ISSUE THREAD

**Issue by noahklowden** [uchicago-cs/chiventure#686]
In order for teams to be able to use the new WDL++, we need to provide simple functions for accessing objects from the hashtable of objects and then access their contents. Part of this means creating high level functions for non-WDL team members to be able to use to easily access these objects.

This will naturally rely on the creation of lower level interfaces for accessing the objects and attributes directly from the hashtable. The issue for this is located in #687. Using these, we can create higher level functions for other teams to use that won't require directly accessing the hashtable or the lower level aspects of the new libobj.

**Comment by noahklowden** [comment]
`get_object()` implementation is written. I have also gone and created a `wdl_ctx` struct which will be used to store the object_store hashtable.

I have written basic tests for wdl_obj and tests for `get_obj_attr()`. However, I'm going to wait until tomorrow when I can ask @ela-ine about how to use the hash table before I finish my implementation.

**Comment by noahklowden** [comment]
All tests pass except for those for get_obj_attr(). This may be because I do not yet have the latest attribute functions, however it is difficult to tell.

**Comment by noahklowden** [comment]
Tests for get_obj_attr() now work fine. With that, all functions we need should be written.

**Comment by noahklowden** [comment]
After merging into dev, all interface functions to access objects, their attributes, and the data in those attributes should be complete. I have created a PR (#787) to merge this into dev, at which point we just will need the parsing of JSON objects to wdl objects should be left.

**Comment by noahklowden** [comment]
With the pull request complete, the code implementing `object_t` structs and `attribute_t` structs should be complete. It is now possible to create and free these structs, as well as modify as needed.

The high level access functions are also now operation, which means that everything needed for final implementation is complete.

The `asset_t` struct, while it now has new(), init(), and free() functions, it does not have implementation for accessing. This has been added to the backlog as #791 for future teams to implement.

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Great work! The links to relevant issues are very helpful here.
