### ISSUE TITLE
Create low-level interface functions for accessing libobj attributes

### ISSUE THREAD

**Issue by noahklowden** [uchicago-cs/chiventure#687]
In order to be able to use the new WDL system, we will need teams to be able to access the attributes of the new libobj objects and their attributes created during parsing. This will require the creation of simple functions to grab objects from the hash table of the objects and then from there access the attributes of that object. 

Elaine has already been designing and implementing the basics of the hash table for the objects themselves in #549. This sprint will involve designing and implementing similar functions for the attributes hash table, and implementing a few basic linked list functions.

**Comment by ela-ine** [comment]
Started branch [wdl/attrs-hash](https://github.com/uchicago-cs/chiventure/tree/wdl/attrs-hash) and started header file for attribute_t querying functions

**Comment by ela-ine** [comment]
Wrote out basic implementation yesterday (essentially copied over from objstore), found an issue with the anonymous union under the attribute struct — currently in Noah's design, it's not accessible by outside functions, but I'll need it to type items to be added into the hash table.

**Comment by noahklowden** [comment]
Now that [object.c](https://github.com/uchicago-cs/chiventure/blob/wdl/libobj-interface/src/wdl/src/object.c) has been created, implementation of the actual functions to create and use objects must be completed.

**Comment by ela-ine** [comment]
Started writing test file for hashing functions

**Comment by ela-ine** [comment]
Updated objstore free function (realized it didn't free objs despite description saying it does) and have written most of the tests.

**Comment by ela-ine** [comment]
Wrote some free functions, but trying to delete from both the hash and the linked list is sort of confusing, and I haven't figured out a way to do so. Wrote more tests, currently append and get_prev are crashing for unknown reasons. Have yet to test all free functions.

**Comment by ela-ine** [comment]
Maxine helped me fix the tests, but I'm getting stuck with the `free_attr_list` function... Seems like the `DL_FOREACH_SAFE` function is failing for some reason. Have the PR written up, but I just need this test to pass.

**Comment by ela-ine** [comment]
This new attributes module includes functions to add/find/delete from an attributes hash, append/delete/count a linked list of attributes, and a few very basic interfacing functions that return elements of an attribute struct.
Future WDL teams might be interested in further developing the linked list capabilities.

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Great work! The summary on this issue is particularly clear and concise.
