### ISSUE TITLE
Implement the new interfaces for accessing libobj to create the game_t and room_t objects in game-state and use as example code

### ISSUE THREAD

**Issue by noahklowden** [uchicago-cs/chiventure#689]
The final task for setting up the new libobj interface is to provide an example of how to use these new interface and objects to create something saved in the game-state. This code should implement the interface to take the global game-state object and set up the basic game-object and then create room-objects from libobj objects. This may, depending on the current status of other teams, involve working with other teams, but theoretically could be written properly without need for much cross-team consultation.

This will serve two functions. First, the code may serve as an example for other teams to be able to implement their own use of the interface. Second, this will allow us to replace the previous libobj's implementation that would set up the game and rooms directly from the wdl document.

**Comment by noahklowden** [comment]
I have modified the existing chiventure code by splitting up `load_wdl` into two functions: `load_wdl()` and `load_objects()`, respectively.

`load_wdl()` remains in the same location, however it now solely calls functions that parse the WDL. Instead of returning a game, it now returns a `wdl_ctx` struct, which contains either a hash table of `object_t`s or a tree of `obj_t`s.

This is passed to `load_objects()` which is in a module `common/load_objects`. This converts these intermediary objects into a game.

For YAML files, it calls the same functions as old Chiventure did. However for WDZ, instead this is where various teams will write up their code for converting these objects into game aspects. Ideally, this means that future WDL teams will not need to be involved in any changes to code that converts from `object_t`s to a `game_t`.

**Comment by noahklowden** [comment]
The merge is complete. Developers in Chiventure now have all interfaces needed to implement conversion from wdl `object_t`s to a `game_t`. This should mean, overall, the WDL team will run into much less issues of needing to rewrite different parts of code for every single team.

**Comment by MaxineK36** [comment]
Issue Score: ✔️+

Comments:
Good work overall! One thing to work on for future issues: for a task of this size, we would have expected to see more status updates in between the initial issue creation and the creation of the relevant PR.
