### ISSUE TITLE
Implement basics of actions needed to tie NPCs into game

### ISSUE THREAD

**Issue by lilyehsani** [uchicago-cs/chiventure#690]
Following the specification on the [Wiki page](https://github.com/uchicago-cs/chiventure/wiki/NPC-Player-Interaction-Design-and-Planning), create an npc_action file that implements the basic actions necessary to integrate NPCs into chiventure (such as "talk to").

**Comment by lilyehsani** [comment]
I have created an npc/actions branch and added blank npc_action.h and npc_action.c files in the existing npc module for work on this issue.

**Comment by vallarymuhalia** [comment]
We have implemented basic functions : npc _action_new, npc_iaction_nit and npc_action_free in the npc_action.c file. We have also included the header functions and descriptions for these particular functions in npc_action.h file.

**Comment by vallarymuhalia** [comment]
The npc_action.h file has been committed and pushed to our include directory under the npc/actions branch. There are no errors at this point. The npc_action.c file has been pushed to the  src directory in our branch with no errors either.

**Comment by vallarymuhalia** [comment]
We have created a new file- npc_game_action.h in which we intend to implement structs for npc_game_action as well as definitions for basic functions: new, init and free.

**Comment by vallarymuhalia** [comment]
We have added header functions and descriptions in the npc_game_action.h file. These functions allow one to get and npc_action, view possible actions, add conditions to action, check if all conditions are met as well as adding effects to npc_actions. We have also created an npc_game_actions.c file and anticipate to implement the functions by the end of this sprint.

**Comment by vallarymuhalia** [comment]
The dev branch in chiventure has been frozen and no new code can be merged. Unfortunately, this happened before we had a chance to complete implementing the functions in npc_game_action.c. The existence of the header functions in npc_game_action.h under the include folder will make it easier for any team that chooses to further develop the npc functions.

**Comment by alexjsun** [comment]
We have begun writing a module for implementing NPC actions, but we think it would be more beneficial to refactor action management code to accept npc_action_type instead of writing new functions that are simply copy-and-paste versions of action management. That way, if we decide to implement other action types, we can easily implement them in the future. I am closing this issue, but it can be revisited if we decide that the module should be completed or action management should be refactored.

**Comment by ecoble** [comment]
Issue Score: ✔️++
Comments:
Great job! Even though this wasn't merged in time, you did a great job documenting and updating this issue. You can also create a backlog task for this for future development!
