### ISSUE TITLE
Implement test skill trees interaction in the chiventure CLI

### ISSUE THREAD

**Issue by jackandthebean** [uchicago-cs/chiventure#691]
# Implement test skill trees interaction in the chiventure CLI
### What
Now that our final few modules are nearly finished and are on the way to a final `rpg-skilltrees` team pull request, we will use the functions we've written to create a sample skill trees interaction set for the chiventure CLI. We will also pull from `action_management` and `cli` code to do so.
### Why
This test skill trees interaction is a good way to ensure our code works in the greater context of chiventure—beyond unit testing—and to have something to demonstrate in our final presentation.

**Comment by jackandthebean** [comment]
Yesterday, @VannStrasen and I met to discuss our skill trees demo design/implementation and opened the branch [`skilltrees/demo`](https://github.com/uchicago-cs/chiventure/tree/skilltrees/demo) to complete our work

**Comment by jackandthebean** [comment]
@VannStrasen and I have made the PR to merge our complete chiventure demo game that makes use of skill trees. #788 elaborates on the details of the added/changed files. We are also adding a custom command `SKILLS` to print all skills in a given inventory to the CLI.

**Comment by jackandthebean** [comment]
I added a README to describe the Demo game and help those unfamiliar with its creation to navigate it.
https://github.com/uchicago-cs/chiventure/blob/skilltrees/presentation/src/skilltrees/examples/README.md

**Comment by firatciftci** [comment]
Issue Score: ✔️+

Comments:
Great work on this issue! The only thing I will point out is that there should have been more detail put into the meeting update comment; ideally, it should include who the meeting was between, what topics were discussed, and what are the exact outcomes.
