### ISSUE TITLE
Implement apply_effect function

### ISSUE THREAD

**Issue by sumedhsarwate** [uchicago-cs/chiventure#692]
Once the basic player effect functions have been implemented, I will implement the `apply_affect` function. The purpose of the function is to apply an effect on a player, given an array of stats, the durations for the effect on each stat, and the modifiers for each stat.

The header for this function is:

`apply_effect(stat_effect_t  *effect, stats_t **stats, float *intensity, int *duration, int number_stats)`

**Comment by sumedhsarwate** [comment]
I've updated `apply_effect` so that it also takes in a pointer to a hash table. This way, if the player's effect hash table does not currently have the effect, it can be added. I've also added and implemented an `add_stat_effect` function to add an effect to the player's hash table. 

The updated for `apply_effect` is:

`int apply_effect(effects_hash_t *hash, stat_effect_t  *effect, stats_t **stats, 
                           double *intensities, int *durations, int num_stats)`

**Comment by sumedhsarwate** [comment]
In order to actually add the effect to the hash table, I had to change the header so that it takes a pointer to a pointer for the hash table, just as with `add_stat_player` and `add_stat_effect`.

The updated header:

`int apply_effect(effects_hash_t **hash, stat_effect_t  *effect, stats_t **stats, 
                 double *intensities, int *durations, int num_stats)`

**Comment by sumedhsarwate** [comment]
To make the implementation for `apply_effect` neater, I've added a function called `stat_mod_new`, which creates a new stat_mod_t struct given a pointer to a stat, a modifier, and a duration.

**Comment by sumedhsarwate** [comment]
Closing Statement: This issue has been closed through PR #758. The `apply_effect` function has been implemented so that it will apply an effect on a player based on the arrays of stats, modifiers and durations passed through the function. It will also add the effect to the player's effects hash table if the effect does not already exist there. New, init and free functions for stat_mods have also been implemented and merged.

**Comment by ecoble** [comment]
Issue Score: ✔️++
Comments:
Great work, especially with the thorough updates and closing statement!
