### ISSUE TITLE
Write/Update unit tests for skill trees module, specifically refactored skilltree.c

### ISSUE THREAD

**Issue by michaelleestuy** [uchicago-cs/chiventure#693]
There are potential changes in line to be pushed to refactor ```skilltree.c```, and once these changes are pushed, the tests will need to be updated to reflect these changes. The goal is to create a PR with updated tests.

**Comment by michaelleestuy** [comment]
Today, me and @steeltrapp worked on and finished the unit testing for not only the refactored `skilltree.c`, but also the rest of the source code. These are shown in commit 64c0f0b, and is also included in PR #746.

**Comment by firatciftci** [comment]
Issue Score: ✔️

Comments:
Good work on this issue! The only things I'll point out are that the summary card should have more detail in terms of the purpose, the steps needed to be taken, and the goal of the issue, and that the issue should have had some update comments regarding your progress with the task, as it is difficult to quantitatively and qualitatively assess the issue with just a summary and a closing comment.
