### ISSUE TITLE
Resolve redundancies in NPC Struct (involving playerclass playerstat) by meeting with teams and finalizing overall structs

### ISSUE THREAD

**Issue by avianurag** [uchicago-cs/chiventure#699]
- This issue relates to issues #600 #524, which involved integrating the playerstat and playerclass structs respectively into the NPC struct.
- A subsequent issue (#566) is also relevant here.

- The current situation is that the class_t struct includes a pointer to stat_t. Currently, a stat_t struct also exists in the overall NPC struct.
- This poses a few problems, the first of which is the obvious redundancy of having two stat_t structs in the NPC struct.
- This must be investigated and the redundancy removed (or explained)
- We will first meet with the relevant teams to discuss this issue.
- The outcome of this issue would either be a pull request resolving the redundancy or a wiki/pull request documenting why both stat_t structs need to be included in the NPC struct.

**Comment by avianurag** [comment]
Update after Meeting with rpg-playerclass and rpg-playerstat:
- In the game-state player.h: the stat_t struct needs to be removed from the player struct, and the class_t struct needs to be added.
- In the playerclass class_structs.h: the playerstat stub needs to be replaced with the actual player_t struct (and include the relevant struct). 
- The npc struct needs to use the playerclass struct.

**Comment by avianurag** [comment]
Closing Remarks:
The relevant updates were made to the code based on the previous comment. This issue/redundancy has been appropriately resolved, and we are closing the issue.

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Amazing work!
