### ISSUE TITLE
Refactor existing custom actions code to include a comprehensive custom actions struct

### ISSUE THREAD

**Issue by emmamedeiros** [uchicago-cs/chiventure#702]
Now that functions and modules have been implemented for custom actions block structs, we want to refactor the code in order to create a more comprehensive struct to hold a custom actions block, which we will define as custom_action_t. This struct will hold the updated AST_block struct, once implemented, and include the information for the title, context, item, and class of a custom action.

**Comment by emmamedeiros** [comment]
The module for the custom actions struct has been implemented and tested, and a pull request will be submitted for the new, init, and free functions for the custom action struct including a custom_action.h, custom_action.c, test_custom_action.c file and relevant updates to makefiles. The update to the AST block struct has not been implemented yet, as shown in the code implementation for the custom action struct, but will be implemented as a next step and and separate pull request, and will thus be reflected in an update to the custom action module code.

**Comment by emmamedeiros** [comment]
The custom_action_t struct implementation has now been approved and merged into dev. The refactored AST block struct is currently being prepared as a pull request, which includes the appropriate changes to the custom action struct implementation as well as the other block modules. Subsequently, this issue will now be closed.

**Comment by MaxineK36** [comment]
Issue Score: ✔️+

Comments:
Good work overall! Some things to work on for future issues: for a task of this size, we would've expected to see more status updates, not just a singular update when a PR has been submitted and a closing statement once it's merged. Additionally, the related PRs/issues should be linked here.
