### ISSUE TITLE
Implement ability to stack multiple identical items

### ISSUE THREAD

**Issue by ericyc16** [uchicago-cs/chiventure#703]
Issue #666 developed a design for the support of stacking multiple identical items (found [here](https://github.com/uchicago-cs/chiventure/wiki/Action-Management---Item-Stacking-Design)). This design specifies adding a field `item_t *next` to the `item_t` struct. Therefore, if multiple items with identical `item_id`s exist, they will be stored in a linked list with the head stored in the hashtable.

To realize this design, implementation of the following is necessary:

- In the item struct, a field that points to another item
- Functions to add/remove items to/from a hashtable (refactoring & updating current code)
- Function to convert an item hashtable to a linked list (refactoring & updating current code)
- Update `do_item_action` and `do_item_item_action` in `actionmanagement.c` and `look_operation` in `operations.c` to take into account the possibility for multiple items with identical `item_id`s

Additionally, perform unit tests to ensure that this new mechanism functions as expected.

**Comment by ericyc16** [comment]
Code has been refactored from `add_item_to_game`, `add_item_to_room`, `add_item_to_player`, and `add_item_to_npc` to new function `add_item_to_hash`. 

Took a while to figure out that `add_item_to_hash` needed to take an `item_hash_t**` rather than an `item_hash_t*` as a parameter. Luckily I figured it out after reading the "Passing the hash pointer into functions" section of [the uthash user guide](http://troydhanson.github.io/uthash/userguide.html).

**Comment by ericyc16** [comment]
Added `remove_item_from_hash` and created functions to remove an item from a room/player/npc. I need to write some tests for this function next.

Currently, all of my work has been with refactoring current code + adding trivial functions to prepare for actually implementing stackable items. I will likely be pulling this refactored code into dev before I begin work on implementation, that way there isn't one massive, horrible PR for someone to suffer through

**Comment by ericyc16** [comment]
I ended up doing a little more refactoring first, but now I'm actually going to write some new tests. Currently, running `-ctest --extraverbose` does not produce any errors. Since I primarily have been refactoring, hopefully it stays that way after my new tests are written.

**Comment by ericyc16** [comment]
Wrote tests for the new functions in the item module: `add_item_to_hash`, `get_all_items_in_hash`, and `remove_item_from_hash`. They all pass when running ctest.

Next step is to write functions in the game, room, player, and npc modules to test that their `remove_item_from_[blank]` functions work. Since those functions are essentially just calls to `remove_items_from_hash`, they should all work. However, I'm adding these tests for completeness.

**Comment by ericyc16** [comment]
Wrote functions for room/player/npc modules to test `remove_item_from_[blank]` functions. Ended up finding an issue in the `remove_item_from_npc` function where it used `add_item_to_hash` rather than `remove_item_from_hash`. This has been fixed, and now all tests pass.

Now that all of the refactoring is done, the next step is to pull that code in and then begin work on supporting item stacking.

**Comment by ericyc16** [comment]
I'm going the test-driven development route for implementing stackable items. The tests have been written, and running `ctest --extra-verbose` returns the expected errors. There are also a few unexpected errors coming from the `test_stats.c` file. Looking at the `test_stats.c` and `stats.c` files, though, this honestly looks like a problem that the stats team themselves need to fix, so I'm gonna ignore that for now and focus on my own issue.

**Comment by ericyc16** [comment]
Edited the `item_t` struct to include a pointer to an item with an identical item id. Also updated `add_item_to_hash`. This function does not add an item to the hashtable if this item occupies the same memory address as an item in the hashtable. If the two items are different in memory but have the same item id, then the identical item is added to the hashtable.

Also fixed a test in `test_rooms.c` so it doesn't throw an error when duplicate items are successfully added to a room.

**Comment by ericyc16** [comment]
Made another change to `add_item_to_hash`: 
- Before this change, the function only would not add an item to the hashtable if the new item occupied the same memory address as the head item in the hashtable
  - If the new item occupied the same memory address as an item pointed to later down the line, it would've gotten added
- After this change, that should no longer be the case
  - All items in the list of items with identical ids should occupy different areas of memory.

Additionally, updated `get_all_items_in_hash` so that all items with identical ids are included in the returned linked list. Before, only the head item would have been included.

**Comment by ericyc16** [comment]
The refactored hashtable code has made it into dev (PR #730).

I believe that all I have left to do before making a final PR that will close this issue is the following:
- Update `remove_item_from_hash` to take pointer into account
- Rework `do_item_action` and `do_item_item_action` to check all identical items if anything fails
- Update `look_operation` (operations.c) to mention there being multiple of an item
- Update/write tests

**Comment by ericyc16** [comment]
Updated `remove_item_from_hash`, and it seems to work as expected.

I also decided to try running the demo game that I'm making (in issue #667) to see if it works in an actual game, and these functions seem to be working how I want them to. However, doing this has made me realize that I'm going to need to update the `ITER_ALL_ITEMS_IN_ROOM` and `ITER_ALL_ITEMS_IN_INVENTORY` macros in the `item.h` file. 

So currently, my todo list for this issue is:
- Rework `do_item_action` and `do_item_item_action` to check all identical items if anything fails
- Update `look_operation` (operations.c) to mention there being multiple of an item
- Update item iteration macros in item.h
- Update/write tests

**Comment by ericyc16** [comment]
Updated the macros, and they seem to work properly. I once again tried running the demo game, and now all items (even duplicate ones) are printed when the `inv` command is inputted.

**Comment by ericyc16** [comment]
I decided that it'd make more sense to have `kind1_action_operation` and `kind3_action_operation` check an action on identical items if necessary rather than `do_item_action` and `do_item_item_action`, respectively. 

I also wrote a chiventure game with the sole purpose of testing duplicate items in game. This way I don't have to keep checking against my demo game, which is in a whole separate branch. I have no idea why I didn't think to do this earlier.

The test game has 10 objects with item id "FORK". Some forks have identical actions, but most have different actions that are legal. 

Running through this test game, I found an issue with `remove_item_from_hash` that I hadn't considered: the item that was removed from the hash still pointed to another item in its `next` field. I updated that function and wrote some more tests in `test_items.c` to check for this. These tests pass, and the test game run through happens as I expect.

I think all I have left to do is update `look_operation` to mention there being multiple of an item.

**Comment by ericyc16** [comment]
When specifying "look [item]", if there are multiple items in a room then this information is included in the standard output. 

Additionally, implementing this made me realize that there was an issue with how I had dealt with string concatenation in my end conditions issue. The `sprintf` function writes over the string passed as the first parameter rather than appending to what already exists. This was a problem because with in `do_item_action` and `do_item_item_action`, getting a game over was supposed to add a game over message to the action success string, but instead just the game over message would have been displayed. I went ahead and fixed that.

**Comment by ericyc16** [comment]
Added a couple of small tests to check adding/removing duplicate items from a room, a player's inventory, and an npc's inventory. The tests are simple since the functions that directly interact with the item hashtable are so thoroughly tested. Everything compiles, all tests run, and the sample playthrough works as expected. I'm going to open a PR soon, and once it's merged with dev then this issue will be closed.

**Comment by ericyc16** [comment]
Pull request #765 has been approved and merged, so I am closing this issue.

In summary, in this issue I accomplished the following:

- Edited the `item_t` struct to include a pointer to an item with an identical item id
- Updated `add_item_to_hash`, `*get_all_items_in_hash`, and `remove_item_from_hash`
- Updated the `ITER_ALL_ITEMS_IN_ROOM` and `ITER_ALL_ITEMS_IN_INVENTORY` macros (item.h).
- Updated `kind1_action_operation` and `kind3_action_operation` (operations.c) to try an action on all items with identical ids until a successful action occurs (or until all items have been tried)
- Updated `look_operation` (operations.c) to mention there being multiple of an item when the user inputs "look [item]"
- Wrote a sample WDL file (`duplicate_test.wdl`) to test/demonstrate items with identical ids in an actual chiventure game
- Wrote/updated tests

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Awesome work! As usual, the bulleted format is extremely helpful, and your closing statement is particularly clear.
