### ISSUE TITLE
Update game over mechanism to support never-ending games

### ISSUE THREAD

**Issue by ericyc16** [uchicago-cs/chiventure#708]
Currently, a chiventure game should end when one of three cases happens:
1. A final room is entered and all end conditions are met
2. No end conditions exist, but a final room is entered
3. No final room exists, but all end conditions are met

However, there is currently a fourth possible case: if no final room is defined and no end conditions are defined, a game ends after any single action occurs. Pull #698 noticed this and suggests that if no final room is defined and if no end conditions exist, a game should continue indefinitely (or "never end"). 

To support this, the following changes will be necessary:
* Change `end_conditions_met` (in `game.c`) to return false when end conditions do not exist
* Change conditional statements in `actionmanagement.c` that check if a game is over, likely refactoring this into a separate `is_game_over` function
  * Note that this is necessary because implementing the change to `end_conditions_met` without updating the conditional statements will cause game over case 2 to never be caught
* Updating/adding tests appropriately

**Comment by ericyc16** [comment]
end_conditions_met (in game.c) now returns false when end conditions do not exist. Additionally, tests in test_game.c have been updated. 

I have added the header for a function `is_game_over` in `game.c`. This will check if one of the three game-ending conditions described above has been met.

Currently, the game-ending case where no end conditions exist, but a final room is entered is no longer caught by actionmanagement.c. This will be fixed once I refactor code into `is_game_over` and update it there.

**Comment by ericyc16** [comment]
`is_game_over` now should return true if one of the three game-ending cases has been met. The conditional statements in `actionmanagement.c` that used to check for game over conditions have been replaced with calls to `is_game_over`. In theory, everything should be working fine, but I still need to write some tests for `is_game_over` to ensure that this is true in practice.

**Comment by ericyc16** [comment]
Wrote a bunch of tests for `is_game_over`, and they all pass. I don't believe anything else is necessary, so I will create a pull request for the action-management/end-conditions-update branch.

**Comment by ericyc16** [comment]
Pull request #718 has been approved and merged, so I am closing this issue.

In summary, in this issue I accomplished the following:

- Changed `end_conditions_met` to return false when end conditions do not exist
- Wrote an `is_game_over` function to check all possible game-over cases, using it to replace conditional statements in `actionmanagement.c` that check if a game is over
- Updated/Added tests appropriately
- Merged this code with the dev branch

Todo:

- Create a mechanism to make the game-over message customizable (right now it’s just `Moved into %s. This is the final room, you've won the game! Press ctrl+D to quit.` , which is quite boring; issue #729 has been created for this task)

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Great work! The links to PRs/issues and bullet style of the summary make this issue particularly clear.
