### ISSUE TITLE
Apply object_t struct functionalities to the NPC struct working with the npc-team

### ISSUE THREAD

**Issue by suday18** [uchicago-cs/chiventure#711]
Description: For this sprint, our goal is to apply the object_t struct to create lua functionality and customizability for the overall npc struct specifically by modifying the integer and char* variables inside it. We've already had discussions with the npc-team specifically with @Lily-Ehsani regarding this and hope to have a completed a pull request for this as well by the end of this sprint.

**Comment by suday18** [comment]
We've made the changes to the npc struct specifically modifying the npc_id from a char* to now a object_t struct. We have also created a pull request for this and have made @firatciftci and @tammytran134 reviewers for this. Here is the link to our pull request: https://github.com/uchicago-cs/chiventure/pull/750

**Comment by suday18** [comment]
Once this pull request has been approved, we will then close this issue.

**Comment by suday18** [comment]
The pull request for this issue: https://github.com/uchicago-cs/chiventure/pull/755 
has passed on Travis and is awaiting a merge with dev

**Comment by suday18** [comment]
Closing Comment: Since our work is now focused on making updates to the pull request for this issue. We are going to be closing this issue. We have made sure to integrate the object_t struct into the npc modules and have also made changes to the CMaketests that will ensure that the Lua libraries are correctly called.

**Comment by firatciftci** [comment]
Issue Score: ✔️+

Comments:
Great work on this issue! The only thing I will point out is that there should have been more detail put into the meeting notes (mentioned in the summary); ideally, it should include who the meeting was between, what topics were discussed, and what are the exact outcomes.
