### ISSUE TITLE
Apply object_t struct functionalities to the skills structs created by the rpg-skilltrees team

### ISSUE THREAD

**Issue by hugo-chan** [uchicago-cs/chiventure#716]
Communicating with the `rpg-skilltrees` team, we have identified a potential application for the `object_t` module that we created. Therefore, we will be working on applying the `object_t` struct to the structs responsible for handling skills implemented by the `rpg-skilltrees` team in order to make sure the skills module has LUA functionality. In particular, we are hoping to add customizability to skills such as combat, where randomization and conditional flow may be useful, and will maintain close communication with the `rpg-skilltrees` team to understand their wants and requirements. We will know this issue is complete when we have written the code and written tests for our Lua functionalities by stubbing, unit-testing, or writing in-code sample games.

**Comment by hugo-chan** [comment]
Apologies for opening this issue three days late. Can and I had to communicate with the skill-trees team to ensure this issue was feasible and that this application would be valuable to chiventure.

**Comment by hugo-chan** [comment]
We just met with Team skill-trees and discussed potential applications with their current code. For now, it seems like there may not be any applications for `object_t` in the skills and skilltrees struct. However, during our meeting, we have identified an aspect in `battles` related to damage that has potential synergies with our struct. We will discuss this idea with their team and our work will be in the `custom-scripts/custom-damage` branch.

**Comment by hugo-chan** [comment]
After talking to Vann from the skill-trees team and Dawson about our idea of implementing a critical damage feature to skills, we learned and recognize that adding such a feature might just be a short-term solution, since we are targeting such a specific field, and may add technical debt to `chiventure`. Therefore, we decided to not pursue this feature and instead focus on a more general feature which was providing an argument list to our `object_t` design as recommended by Dawson.

The above documents the steps we took and based on these steps, we decided not to move forwards with this issue. Please ignore this issue for grading purposes.

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Great work!
