### ISSUE TITLE
Updating NPC struct to include dialogue and descriptions

### ISSUE THREAD

**Issue by lilyehsani** [uchicago-cs/chiventure#719]
In this issue, I plan to update the current NPC struct to include short descriptions, long descriptions (exactly the same as how items have these), and dialogue. It should be a fairly small task, involving only the struct updates and a few related functions similar to those that already exist with items.

**Comment by lilyehsani** [comment]
I have created a branch called npc/struct-updates for this issue.

**Comment by ecoble** [comment]
Issue Score: ✔️+
Comments:
Nice work keeping the NPC struct up to date! Issues that are closed by PR do still need closing statements.
