### ISSUE TITLE
Fix tests and errors that are coming up for conditional rooms

### ISSUE THREAD

**Issue by victoriavillalba** [uchicago-cs/chiventure#723]
The functions that we've made for the ability of conditional rooms are producing errors in the tests we've made so we're trying to fix those errors.
This relates to closed issue #575

**Comment by victoriavillalba** [comment]
So far I've fixed the path_new problem and the infinite include loop problem and now I'm getting errors in create_connections, which I haven't touched but I'll look into to find the problem.

**Comment by victoriavillalba** [comment]
Errors are now gone, but my tests crashed and I think I just need to malloc. I also need to reorganize how we were going to implement the trigger and conditions parameters, and make a few more functions to simplify everything.

**Comment by victoriavillalba** [comment]
tests still crashing, She is working on that, but I've added path_new_conditions() and action_type_trigger() functions to assign the necessary values for conditional rooms

**Comment by victoriavillalba** [comment]
There were problems with merging but now it's all fixed. Functions have also been integrated into the do_... functions in actionmanagement.c but there are a lot of errors that we're currently working on.

**Comment by victoriavillalba** [comment]
Fixed stupid mistakes in test_delete_action.c so now two of the tests work but one of them doesn't.

**Comment by svedwards23** [comment]
delete_action fixed, all tests pass

**Comment by victoriavillalba** [comment]
game-state finally passes, we just need to make a few tests for path_new_conditions, remove_condition, and action_type_init_room_dir

**Comment by victoriavillalba** [comment]
There were many errors but basically, we had to incorporate a lot of utlist functions to work with the linked lists and instead of calling the action we wanted to remove, we had to call the node that contains the action we want to remove. We wrote up all the tests and they all pass.

**Comment by victoriavillalba** [comment]
We also had to make a few more functions: actioncmp(), find_act(), and then change an if statement in do_path_action() so that it checks if there are no more actions to do before using the path

**Comment by MaxineK36** [comment]
Issue Score: ✔️+

Comments:
Good work overall! One thing for future issues: the summary for this issue is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/policies/#a-descriptive-summary for examples).
