### ISSUE TITLE
Repackage player class info into battle's move struct

### ISSUE THREAD

**Issue by Purrsephone** [uchicago-cs/chiventure#726]
After meeting with player class, we decided that we want to have moves/spells associated with the different classes. Player class will make a function that generates a list of moves and their associated class, damage, IDs, etc. I will repackage this info into battle's move struct so that we can use it in an executable battle.

**Comment by Purrsephone** [comment]
The function build_moves in battle_move_maker.c accomplishes the above by taking a linked list from player class and adding the appropriate move (determined by class) to a player's move list. See PR #745 . This collaboration will be seen in battle's executable.

**Comment by dwahme** [comment]
Issue Score: ✔️++

Comments:
Great job! Well done with a small and targeted task.
