### ISSUE TITLE
Implement Functionality for Action Synonyms

### ISSUE THREAD

**Issue by isaacfink21** [uchicago-cs/chiventure#731]
A previous pull request (#492) reintroduced legality for the `WALK`, `PICKUP`, `USE`, and `EAT` and `DRINK` action synonyms. However, functionality was only available for `WALK`. By the end of the fourth sprint, I will need to implement functionality for the rest of the synonyms.

**Comment by isaacfink21** [comment]
Rather than directly implement the synonyms in CLI as I had originally planned, I have decided to simply switch the action names later on in `actionmanagement.c`. Though this requires supporting an action synonym until it reaches its do_*_action function, this would make it easier to customize messages based on synonym type in the future (e.g. "You may not walk east" rather than "You may not go east").

**Comment by isaacfink21** [comment]
Closed via PR #736. Action synonyms `WALK`, `PICKUP`, `EAT`, `DRINK`, and `USE` are now fully implemented. These synonyms are recognized separately in CLI, but upon being processed in action management, they are converted to their appropriate parent action such that they are functionally identical for the purposes of altering the game state.

**Comment by isaacfink21** [comment]
It turns out I implemented some of the string comparisons for action synonyms incorrectly as '==' rather than using 'strcmp'. I am making a new PR to fix this.

**Comment by isaacfink21** [comment]
Closed via PR #754. Comparisons in the implementation of action synonyms have been patched from == to strncmp, and now operate correctly in a demo game.

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Great work! The updates are very clear and helpful here, as is the note about why the issue was re-opened later.
