### ISSUE TITLE
Create an example skill_tree inventory that can be used by rpg-battle

### ISSUE THREAD

**Issue by ly-chen** [uchicago-cs/chiventure#734]
A hardcoded demo of skill_tree structs being utilized in a battle environment should be possible by creating an example skill_tree inventory with skills that have effects that can be parsed and used to deal damage / build defense. Battle will then take my example to showcase.

**Comment by ly-chen** [comment]
#748 adds files skill-list.c/h alt-skill-list.c and skill-example.c/h. skill-example.c creates hardcoded example skills and skill inventories, which are then called upon by skill-list.c and alt-skill-list.c to create an example list of skills that can be used to demo a battle. As such, the task is complete; however, integration of these files with a working executable to run a demo battle is not yet supported, and can be done in a different issue / PR.

**Comment by firatciftci** [comment]
Issue Score: ✔️+

Comments:
Good work! The only thing I'll point out is that the summary should have been a bit more detailed; ideally, it is a paragraph long and outlines the purpose and the exact changes of the issue.
