### ISSUE TITLE
Use skills in example battle 

### ISSUE THREAD

**Issue by Purrsephone** [uchicago-cs/chiventure#735]
To showcase their work, the skill tree team would like player skills to be executed in an example battle. To that end, they will hard code some skills in a linked list. Battle will take items in this linked list and package them into a move structs which will be added to the move list. These skills will be showcased in battle.

**Comment by Purrsephone** [comment]
After speaking with Leon, we decided that, given the time constraints, we will not be able to accomplish this. Since this issue was created for the purpose of the executable, I will not add this to the backlog.

**Comment by dwahme** [comment]
Issue Score: ✔️++

Comments:
Great job! Well done recognizing what is feasible under the given time constraints.
