### ISSUE TITLE
Add effects to items

### ISSUE THREAD

**Issue by sumedhsarwate** [uchicago-cs/chiventure#738]
As we discussed in our team meeting on Monday, I will add an effects hash table to the items struct and update the `add_item_to_player` function so that the function applies an effect to the player if the effects hash table is not equal to NULL. We should then be able to incorporate this into our demo presentation.

**Comment by sumedhsarwate** [comment]
I've implemented a new function called `stat_mod_new` which, among other things, will make the tests for `add_item_to_player` neater since each field of the struct won't have to be set individually.

**Comment by sumedhsarwate** [comment]
I've added `stat_mod_init` and `stat_mod_free` functions to follow the style of the other structs.

**Comment by sumedhsarwate** [comment]
I realized that there currently is not an easy way to add an effect to and item, so I added and implemented an `add_effect_to_item` function to make this easier now and when we create our demo.

**Comment by sumedhsarwate** [comment]
Closing Statement: This issue has been closed through PR #758. A hashtable of effects has been added to the item struct, so that now, if pointer to the hashtable is not set to NULL and an effect has been added to the hashtable, an effect will be applied to the player when `add_item_to_player` is called. I also added and implemented an `add_effect_to_item` function that will add an effect to an item, and new, init, and free functions for stat_mods

**Comment by ecoble** [comment]
Issue Score: ✔️++
Comments:
Great job, this was a cool addition to chiventure!
