### ISSUE TITLE
Adding a linked list for arguments to be passed to Lua in object_t

### ISSUE THREAD

**Issue by hugo-chan** [uchicago-cs/chiventure#739]
With our current implementation of `object_t`, we recognized that our custom scripts are limited to scripts that take in no arguments. For example, a script that is supported by our current implementation is a random number generator script (the script does not take in any arguments from C and simply returns a number generated within the Lua script). This limitation significantly diminishes the usefulness of Lua scripts in chiventure because we would like our custom scripts to be dynamic. The custom scripts should be able to return different values based on the game state (i.e. some aspect of conditional flow). To achieve this, we would require a way for C to communicate with Lua, which this issue aims to create by passing arguments.

Specifically, we will modify the `object_t` struct to have a linked list of arguments that will be pushed to the virtual stack when calling the function inside the Lua script. The arguments inside the linked list can be any type specified in the union (this enables modification in the future).

There are several steps we foresee:
1. Need to create the struct representing the nodes of the linked list (this will require functions similar to the ones written for object_t)
2. Need to write an argument add function that will append add an argument (node) to the linked list
3. Need to modify current object_t functions and tests to accommodate for this design change
4. Need to significantly modify the getter functions. The arguments in the linked list of the object_t need to be pushed to the virtual stack one-by-one
5. Write test Lua scripts (that take in arguments unlike before) and unit tests for our functions

We will know this issue is complete when these steps are completed and we successfully submit a PR.

We will be working on the `custom-scripts/argument-list` branch.

**Comment by suday18** [comment]
We've added  a number of additional tests for the arg_t struct, specifically with respect to the following functions:` arg_t_new, arg_t_bool, arg_t_char, arg_t_int, arg_t_str, arg_t_add`. 

In addition, we have further tested and all these tests are passing. We're currently working on adding a few more Lua tests that will check if the correct arguments are passed to Lua and that the script is making the expected changes to those arguments.

**Comment by hugo-chan** [comment]
We have achieved what we described in the description and have written tests for our code. The current supported types for the arguments are `bool`, `char`, `int`, and `string`, but more can be added in the future to make `object_t` even more dynamic.

We submitted a pull request here #752.

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Amazing work!
