### ISSUE TITLE
Finalize WDL++ documentation and make it more visible in the repository

### ISSUE THREAD

**Issue by namanhd1nh** [uchicago-cs/chiventure#741]
Right now, the documentation for the wdz file format and the json files are buried in the `wdl/documentation` branch (located at `docs/wdl++.md`) and are mentioned nowhere else, making it difficult for people new to the project to find them. We should move our docs and update docs across the whole repository (wherever wdl is mentioned) so that our specification can be more visible.

Moreover, now that we've merged into dev the related object representations and interface functions, we should now also finish the function interface definitions in the documentation and finally have the docs ready for next year's team to continue where we left off.

**Comment by namanhd1nh** [comment]
@blakemoss is now working on documentation on the previously created issue #688, so I am no longer maintaining this one; we hope to still be able to push cleaner documentation after the dev freeze to help out future iterations of the course to know where we are at.

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Great work! The link to the other issue in the closing statement makes it easy to follow what happened here.
