### ISSUE TITLE
Load the parsed WDL file into game_state room struct

### ISSUE THREAD

**Issue by thoranderskow** [uchicago-cs/chiventure#75]
Use a combination of functions from game_struct/dev and our own functions to parse a WDL file and load them into the given structs.

**Comment by thoranderskow** [comment]
Created a new branch: wdl/game_state to work on the issue.

**Comment by thoranderskow** [comment]
Merged with game_state/dev branch to have access to functions.

**Comment by thoranderskow** [comment]
Goal: Link two rooms within the game structs we were provided, using game_struct's functions.

**Comment by thoranderskow** [comment]
We made two functions: 
create_room(), which takes an attr_list pointer and loads the information into game_struct's room_new() function.
get_items_in_room(), which takes a room id, and a list of all items in the game, which produces a list of items in the given room.

**Comment by thoranderskow** [comment]
We are unsure how to handle the hash table structs that room_new() takes, so we have implemented the create_room() function under the assumption they can take linked_lists instead.

**Comment by bansals10** [comment]
We are requesting game state team to update functions at a higher level with more abstractions such that we can implement through function calls. We have currently assumed functions that we were told would be created. Once we have received these functions, we will update our code accordingly.

**Comment by Kate32815** [comment]
We've re-evaluated this issue and realized it would make more sense to break it up into three more specific issues:
1. Issue #140 A function that takes a room from the WDL file and creates a room in game state
2. Issue #139 A function that takes an item from the WDL file and creates an item in game state
3. Issue #141 A function that calls the functions written in (1) and (2) to load the entire game.

**Comment by Kate32815** [comment]
We've re-evaluated this issue and realized it would make more sense to break it up into three more specific issues:
Issue #140 A function that takes a room from the WDL file and creates a room in game state
Issue #139 A function that takes an item from the WDL file and creates an item in game state
Issue #141 A function that calls the functions written in (1) and (2) to load the entire game.
I am closing this issue now as we have split it up into the above three.
