### ISSUE TITLE
 Implementing and redesigning  NPC-Mocks for autogenerate_test.c

### ISSUE THREAD

**Issue by navila-luna** [uchicago-cs/chiventure#753]
Goal is to modify the sample_npc modules to fit accordingly to the changes made in the default_rooms and autogenerate module. These changes consist of reconsidering the design of returning the npcs in a linked list. Moreover, it requires discussing the implementation of a function that will randomize the npcs  within a room. The purpose of this sprint is to adapt the mock-npcs so that they can be later used in the autogeneration module to randomly produce a max of two npcs in a room. 

OLD (initial issue): Purpose is to fix the errors in autogenerate_test.c caused by the addition of npc_t * possible_npcs within the *room_spec struct. This and the modification of the roomspec_room  led to persistent errors within autogenerate_test.c. Apart from this, there were a couple of errors in the test_structs due to  a missing argument (not of type NPC) that was forgotten.

**Comment by navila-luna** [comment]
I went ahead and all tests pass now. The issues within test_struct was due to (mainly) not including something for char* room_name.

**Comment by navila-luna** [comment]
To conclude, the most recent tests within Autogenerate have been fixed to include the NPC mocks. Additionally, minor errors in test_structs were fixed. All tests pass now.

**Comment by navila-luna** [comment]
Pull Request is actually located in closed issue #639.  The commits can be tracked there.
Since this task requires default_room and autogenerate to be done first, there were numerous challenges in terms of completing this task. This task was initially to fix the errors in Bryans tests caused by the implementation of NPCs in the room_spec struct. However, all 37 errors I fixed within Bryans file were automatically removed during the merge to the latest update of autogenerate. Moreover, the added argument of npc_t within the rooms_spec_new was deleted because of the modification of the autogeneration and default_rooms.h design. That being said, the implementation of where NPCs should be located had to be reconsidered. For instance, they are no longer included within default rooms, but instead remain just in the autogeneration module. As a  consequence, where I initially placed the mock-Npc in rooms had to be removed due to this modification. 
We decided that having the npcs in terms of a hash would be better for the implementation of the the random npc function ( and in general be more efficient). Therefore, the initial design of returning the NPCs in a linked list was changed to being returned as a hash. 

While the idea of having the mock-npc in a hash is a change, the information and mock npc_t struct hasn't changed significantly. The only modification in the struct was the inclusion of a char * npc_name, which is used in random_npc_lookup() and is added within get_generic(),  get_hostile(), and, get_friendly().

Apart from this, given the new design for the NPCs and autogeneration module, the way that NPCs would be randomly generated was something else to consider and took time to understand.
These two npc randomization functions required there to be testings involved.

**Comment by navila-luna** [comment]
To conclude, the overall redesign of the npc module has been completed. Moreover, a passing and error free random NPC generation functions have  been created and implemented in the autogeneration module within the samples-npcs branch. While initially it was hoped to have this pr done, given the amount of work and reworking on the files, the pr itself is a separate task. If the pr is approved an update will be provided here, otherwise it will remain closed.

**Comment by dwahme** [comment]
Issue Score: ✔️++

Comments:
Great job! Well done documenting challenges you came across
