### ISSUE TITLE
Finalize and document stats function implementation and testing

### ISSUE THREAD

**Issue by richardxd** [uchicago-cs/chiventure#767]
Goals of this issue:
1. make sure functions that have been stubbed out are all implemented and worked.  Some tests are broken because of the inclusion of ctx struct. 
> 1. debug not working stat functions /test as requested by Carlos 
> 2. the branch Ruhi checked out was too old and needs to be rebased to dev

2. document each function implementation and finish up the wiki page, which comes from issue #634

**Comment by richardxd** [comment]
1. It turns out that the non-working stat tests are the result of our design that passes a NULL pointer to the stat functions. We have refactored our design and this should solve the problem that Criterion tests were crashing

**Comment by richardxd** [comment]
1.2 Per issue #595, we checked out a new branch and is finalizing Ruhi's implementation and tests right now.

**Comment by richardxd** [comment]
Closing statement:
The PRs have both been approved and merged before the code freeze. The [wiki page](https://github.com/uchicago-cs/chiventure/wiki/RPG-stats-implementation:-Current-stats-struct-design) is updated in accordance with what we have had in the dev branch. The functions, however, are not yet documented in the wiki page for rpg-stats. I will add this to the sprint backlog and pick it up if I'm available.

**Comment by ecoble** [comment]
Issue Score: ✔️++
Comments:
Great job, especially with debugging those tests!
