### ISSUE TITLE
Create example program for stats

### ISSUE THREAD

**Issue by sumedhsarwate** [uchicago-cs/chiventure#768]
I will create a sample program for stats that will display the functionality of player stats in an executable program.

**Comment by sumedhsarwate** [comment]
I've added display functions for global stats/effects and for player effects so that the monkey patched CLI functions can call the display functions and we can demo the existence of the stats and the changes to them.

**Comment by sumedhsarwate** [comment]
I've created items called poison, potion, and elixir (I might change the names later) with effects that we can demonstrate during our presentation. Poison will have a "poisoned" effect and will decrease health. Potion will have a "healed" (again, names might change) effect and will increase health. Elixir will have a "stunned" effect that will decrease health and xp and a "boost" effect that will increase speed and stamina. I've also added a CLI command that we can use to print the effects an item has.

**Comment by sumedhsarwate** [comment]
(Commits got duplicated when I rebased for some reason when I rebased my branch)

**Comment by sumedhsarwate** [comment]
(I am so sorry, it happened again. Please ignore the commits following the last comment)

**Comment by sumedhsarwate** [comment]
Adding an action to the items was becoming a little too complicated, as I don't completely understand how the action management system works and how I would then call add_item_to_player, so for the purposes for our demo, I defined a new command called "grab" that would add an item to a player's inventory.

**Comment by sumedhsarwate** [comment]
I took out the grab command that I created and instead just added the "TAKE" action to all the items. I also re-added the playerclass struct/implementation after issues with WDL were addressed, so the example program now reflects the fact that stats and effects are stored in the player class struct.

**Comment by sumedhsarwate** [comment]
Closing Statement: The example program has been merged through PR #789. It includes monkey patched CLI commands to print player stats/effects and global stats/effects, add a stat/effect to the player, and increase the max for a stat. It also includes items called poison, potion and elixir, each of which has different effects on the player when the "TAKE" action is used. To run the example program: build chiventure as defined in the README, then in build, run `make examples` then `src/game-state/examples/stats_example`

**Comment by ecoble** [comment]
Issue Score: ✔️++
Comments:
Great job getting this example program working! It really showcased your work!
