### ISSUE TITLE
Implement Add_stat function so we can get stats into the games memory

### ISSUE THREAD

**Issue by carlosazpurua1004** [uchicago-cs/chiventure#770]
This issue will be solved by doing two things
- on startup, calling global_stat_new for every stat we want in the game, and similarly for global_stat_effect_new

- modifying startup code so initialization of players/npc gives them all global stats

In particular, I'll add a function called add_stat_to game for the first part, which adds global stats to the global hash_table

**Comment by carlosazpurua1004** [comment]
Added the add_stat_to game function, I think I will also add a function that takes a player/npc stat hashtable and gives them all the global stats

**Comment by carlosazpurua1004** [comment]
Since the player is already initialized inside of the ctx_init function, I'll be calling these things inside of the ctx_init function.

**Comment by carlosazpurua1004** [comment]
Some of the stuff I've been adding is really just stuff we need in the monkey patch, not the game, so I'm moving most stuff over to the monkey patch.

This issue will instead be resolved by implmentation of the add_stat_function

**Comment by ecoble** [comment]
Issue Score: ✔️+
Comments:
Great job integrating your work with the global elements of chiventure! Issues that are closed by PR should still have closing statements.
