### ISSUE TITLE
Function player_free does not correctly free player struct

### ISSUE THREAD

**Issue by Dumplingz** [uchicago-cs/chiventure#785]
Currently, `player_free(player_t *plyr)`, located in game-state, passes the tests given to it. However, when attempting to use player_free in test_item_item_actions.c in action management's tests, player_free caused a crash.

Suggestions/observations for helping fix this problem:
 - `free(plyr)` is never called. Not sure if intended.
 - The tests for `player_free` do not add items to the player and then check if free works. Issue ma, in part, be caused by that.

**Comment by LapsededPacifist** [comment]
`player_free(player_t *plyr)` was modified to include `free(plyr)` and to check if an inputted hash table was null before attempting to free it.
However, it still crashes on the same 4 test cases. I used valgrind to look at it and it appears to be issues with double freeing items. Still attempting to figure out how that is happening, but it seems to be an error with delete_all_items.

**Comment by LapsededPacifist** [comment]
I just had the brilliant realization that the issue comes from him calling `item_free(direct)` and `item_free(indirect)` and then `player_free(player)`, which is the root of the double free. We are freeing both the items individually and then again in player. There were still memory leaks in player_free, which are now patched. However, the source of the problem is in the tests not player_free.

**Comment by adishpan** [comment]
I want to have some sort of clever roast for the person who made the tests, but honestly, I think the above is roast enough.

**Comment by adishpan** [comment]
The main issue here occurred because the test was structured in such a way that a double free was inevitable. We have fixed the error so that this should not occur anymore, and so we are closing this issue.

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Great work! Your updates are particularly useful. For the future, when picking up a backlog issue please remember to update the milestone to the current sprint.
