### ISSUE TITLE
CLI/Split Screen image instead of rectangles

### ISSUE THREAD

**Issue by xmvalencia** [uchicago-cs/chiventure#811]
add to the cli/split screen example by adding images instead of boxes and have them change with the room change. This will require changing the example (split_screen.c in src/ui/examples)

**Comment by grkapoor17** [comment]
There exists Draw_Rectangle functions that need to be replaced by similar Load_Image functions from Raylib. It is unclear at the moment whether we need to upload specific images. We see that there is one png file inside src/ui/examples/sandbox/images, but there are 3 rooms. Thus, we are unclear on which room we use this image for.

**Comment by eao10000** [comment]
We has successfully able to replace the loaded rectangle with a loaded image. However the only image currently working is the example3.png which was already in chiventure. When trying to bring in other images from outside sources and load them in the Load_Image function it it reporting that is failing to load the data.

**Comment by grkapoor17** [comment]
We have successfully replaced the Draw_Rectangle functions with functions related to drawing images: LoadImage, DrawTexture, etc. The problem mentioned in the previous comment had to do with the fact that the images were jpegs and they were too large; only pngs and images under 500 times 500 pixels work. We added 2 more pictures to sandbox/images and named all 3 pictures according to their room number, i.e room1, etc. Thus, the split_screen_example executable now displays images of rooms on the top half of the split screen for each room.

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Great work! You did a particularly good job providing clear updates as you got caught up with this backlog issue and as you discovered some of the limitations of the raylib commands. For future Backlog issues, please make sure you update the milestone to the relevant sprint.
