### ISSUE TITLE
Finish integrating skill trees into playerclass

### ISSUE THREAD

**Issue by jackcasey067** [uchicago-cs/chiventure#817]
Currently, the player class code has skill trees stubbed out.  Work began last year to fully integrate the two features (issue #571), but completion of the task had to wait for a skill trees pull request.  

It seems now that the pull request went through, and we are good to implement these changes.

- Make sure the changes in branch playerclass/skilltree-integration are sufficient and up to date with the skilltree module.
- Get the branch up to date.  It is currently way behind dev.
- Confirm with the skill trees team that this is how we want to integrate the feature.

**Comment by jackcasey067** [comment]
I have successfully merged `dev` into `playerclass/skilltree-integration`, and nothing badly conflicted.  I am beginning to examine the code in this branch more thoroughly: I had previously missed the files `class_skills.c` and `class_skills.h`, and I am unsure if we should keep them honestly.

**Comment by jackcasey067** [comment]
I've rearranged the code a bit (mainly making the new class_skills module deeper), and I think it is ready to be shared with the skill trees team.

My last code concern is how we generate the tree id.  I remember seeing in the skill trees code that they may want to divvy up certain id ranges between teams, so I may try to do that.  I may also leave this for later.

**Comment by jackcasey067** [comment]
I'm currently happy enough with my code, so I have reached out to the skill trees team to get their feedback.

**Comment by jackcasey067** [comment]
This last lecture has me a bit concerned about the if-else ladder in `class_skills_init()`.  At some point, we are probably going to want to differentiate between the current class status (with current unlocked skills and traits) and the class prototype (with all unlockable skills and traits, base stats, and perhaps a function pointer to skills_init()).  

I don't intend to make that split in this issue, but I intend to discuss this with the team at some point.  Maybe this will be a task for the next sprint.


Also, I don't know why we decided to have 10 default classes (there is nothing documenting that decision), and we could take some of them out.

**Comment by jackcasey067** [comment]
I met with Rohan Gupta (@rohangupta2806) from the skill trees team today, and we talked through the changes.  There are two things that I am changing or at least thinking about changing:
- Tree ids: We are not the only user of the skill tree struct.  While we handle class skill trees, devs might a) not want to have classes in their game or b) want to have class skill trees, but also have common skill trees as well.  Each tree is defined by a unique tree id, so it is important that no one in the code base allocates trees with the same id.
    - The solution to this is that each team that might use skill trees gets its own range of possible ids to use.  We get 3000-3999, so I will update our code to reflect this.
- Passive vs Active Skills: We talked about how our code differentiates between combat skills and non-combat skills.  The skill trees team makes a similar, but the subtly different distinction between active and passive skills.  Maybe we should ensure that our distinction matches theirs.
    - In my opinion, this is out of the scope of this issue, and I am wary about making this change since others' code might already need combat skills and non-combat skills.  That distinction is useful as well as the passive vs active one.
        - I will leave code comments about this, and may bring it up in future meetings.

**Comment by jackcasey067** [comment]
Completed the tree id change.  I went ahead and devised a system for assigning ids to prefab classes, but it is fairly rudimentary and subject to change.

Also poked around and discovered how to run tests, which revealed the intention the add a Warrior class.  I did that too.

**Comment by jackcasey067** [comment]
Perhaps I should've known that the error messages in the test were problematic, even if the tests themselves counted as successes.

Now we store names internally as lowercase, to avoid the issue where we have to constantly check uppercase vs lowercase.

**Comment by jackcasey067** [comment]
Some changes were made after receiving feedback on the pull request.  There is one big change worth noting:
I split the class_new function so that skill trees were not mandatory; you can create classes with or without skill trees.

**Comment by jackcasey067** [comment]
Closing statement: 
After a little bit of restructuring, the changes in this issue were merged with `dev`.  The player-class and skill-trees features have now been integrated.

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Good job! This issue is very detailed and well-organized; the updates really reflect the amount of work you've put into it.
