### ISSUE TITLE
Create a wiki page detailing incorporation of quests in existing rpg code

### ISSUE THREAD

**Issue by ddelgado60** [uchicago-cs/chiventure#818]
We wish to learn more about existing quests/npc/battles/general rpg code, and want to explore the incorporation of quests into this. We plan to create a wiki page from our findings, and potentially create future backlog tasks from our research.

Updated: Finished this issue, will now move onto more implementation heavy issues stemming from this issue. Wiki page is here: https://github.com/uchicago-cs/chiventure/wiki/Future-Prospects-of-Incorporation-of-Quests-into-Existing-RPG-features

team:quest
Assignees: Devon, Dillon

**Comment by ddelgado60** [comment]
Updated: Finished this issue, will now move onto more implementation heavy issues stemming from this issue. Wiki page is here: https://github.com/uchicago-cs/chiventure/wiki/Future-Prospects-of-Incorporation-of-Quests-into-Existing-RPG-features

**Comment by lilyehsani** [comment]
Issue Score: ✔️++

Comments:
Great work overall! The summary is to-the-point and the closing statement is thorough. In the future, you could benefit from more updates, but for a straightforward task like this, the closing statement is enough.
