### ISSUE TITLE
Research packcc library

### ISSUE THREAD

**Issue by Mich0608** [uchicago-cs/chiventure#819]
Our goal is to research the packcc library (https://github.com/arithy/packcc), a C parsing library, and assess whether it is suitable for use in the CLI++/DSL features. We will create a list of pros and cons and hopefully try out the library with some code in sandbox. The research process will be documented under this issue.
Assignees: Tessie and Michelle

**Comment by Mich0608** [comment]
After an initial read-through of the packCC documentation, I've identified a few caveats:
1. the parser seems to depend on a grammar called PEG (parsing expression grammar), which will require users to learn a new grammar/syntax
2. there is only one example, and it isn't thoroughly explained.
In conclusion, as somebody with no previous experience with parsing, the documentation and requirements of the library isn't super beginner friendly.

**Comment by tessied** [comment]
I've identified a few pros and cons of the packCC library:
Pros:
1.  PEG (the grammar used) is a top-down parsing language which is unambiguous.
2. The usage of packrat parsing lets any input be parsed in linear time.
Cons:
1. The documentation itself is difficult to follow and understand; it lacks adequate and thorough explanation.
2. I personally find the syntax to be rather confusing and non-intuitive.

Echoing the comment above, I was not able to build and run the library following the documentation.

**Comment by Mich0608** [comment]
We had a team meeting and decided that we preferred the other libraries over packCC due to better documentations and better success with code experimentations. The current consensus is to not use this library.

**Comment by Mich0608** [comment]
After the whole team met on Monday April 26, we decided not to use packCC because:
1. packCC seems to be less user-friendly than the other C libraries we looked into
2. we want to use Python libraries

**Comment by ecoble** [comment]
Issue Score: ✔️++

Comments:
Great job assessing this library! The frequent updates and clear closing statement are great. Next time it would be better to put this research documentation into a Wiki page for your team, so that it is easier to reference in the future.
