### ISSUE TITLE
Create a new up-to-date skilltree wiki page summarizing everything.

### ISSUE THREAD

**Issue by tgao564** [uchicago-cs/chiventure#821]
There are 6 wiki pages for skill trees written in different formats and tenses. We will look through the existing wiki articles for skill trees to develop a strong understanding of the topic, then summarize the information into a master doc while also doing additional research for any missing supplemental material. 
Assignees: Tyler and Joshua
team:skilltrees

**Comment by Joshuashou** [comment]
Finished by Joshua and Tyler!

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Good job! The only feedback I have is that, as the final outcome of this issue is a wiki page, the closing comment should ideally link to the wiki page for easier access.
