### ISSUE TITLE
Create a wiki page detailing the current implementation of NPC dialogues, improving it and integrating it into Chiventure

### ISSUE THREAD

**Issue by JeYeong** [uchicago-cs/chiventure#823]
The aspects of NPC design is currently spread across several wiki pages. We will review these pages and either update existing pages or create an new page to provide an overview of the NPC module as it stands, propose design changes for future sprints, and detail methods for integrating NPC dialogue into chiventure.
Assignees: James, Peter
team:npc2

**Comment by JeYeong** [comment]
(1) Determined that NPC dialogue integration will likely require collaboration with the CLI team.
(2) Determined that in order to include conditional dialogue options (e.g. based on attributes, items, relationships, etc.), we could borrow the condition_t struct from game_state/conditions.h

**Comment by pkasner** [comment]
The branch npc/action contains data structures for implementing NPC actions in order to integrate with chiventure. The action options are those described in the NPC Player Interaction Design and Planning wiki. The functions for executing these actions are currently marked as to do.

**Comment by JeYeong** [comment]
Updated the [NPC Design and Planning](https://github.com/uchicago-cs/chiventure/wiki/NPC-Design-and-Planning) wiki page, with proposed changes/improvements for implementing dialogue. We also detailed primary integration problems of dialogue and documented possible solutions.

**Comment by pkasner** [comment]
I'm closing the issue on account of the previous comment. Information detailed in the NPC Design and Planning wiki page will be used to define tasks for future sprints.

**Comment by lilyehsani** [comment]
Issue Score: ✔️++

Comments:
Great work on this issue! The summary and updates are detailed and to-the-point. In the future, it would be good to make a closing statement a bit more detailed (but for an issue of this size, it makes sense).
