### ISSUE TITLE
Create and/or update wiki pages for current player class implementation

### ISSUE THREAD

**Issue by farm-zaq** [uchicago-cs/chiventure#825]
Read through the wiki pages for playerclass and through the actual implementation in code. Ensure that we understand both of these. Check for discrepancies between the two; this includes looking for changes in the code that require updates in the wiki pages and unimplemented elements mentioned in the wiki pages that should be implemented or marked as currently unimplemented plans (or flag them and then work on them).

**Comment by farm-zaq** [comment]
I realize I never made final comments or closed this issue, so I'll do that here.
The wiki pages have been updated. Mentions to code that has been changed has been updated, and code that is certainly unimplemented has been marked as so. Most of this code seems minor and does not seem strictly necessary or even high priority, so no moves to implement them have been made.
While closing this issue, I am making updates to reflect changes to the prefabricated classes (mostly a significant cut to the number) in the wiki.
I apologize for the lateness of this comment and of this closure.

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Good job! In the future, make sure to write the closing statement of an issue as soon as the task at hand is finished.
