### ISSUE TITLE
Update documentation to reflect current needs for integrating player struct

### ISSUE THREAD

**Issue by WPDolan** [uchicago-cs/chiventure#826]
Current documentation details an action plan for integrating the player struct into action management based on requests from the former RPG stats, skill trees, and class teams: https://github.com/uchicago-cs/chiventure/wiki/Action-Management-Player-Integration-Plan. 

We should communicate with the current iterations of these teams and determine if the implementation requests from the document are still desired, and update the documentation if necessary.

**Comment by afranzese99** [comment]
Reached out to rpg-playerclass team who suggested clarifying the health field in the player struct so that it is clear it represents current health and that max health would be a stat. They also mentioned that it seems strange to have a stat such as max health in the player struct. I will continue to discuss the topic with them.

**Comment by WPDolan** [comment]
I've reached out to the skill trees team who mentioned that there should be no changes to the way skills would be stored with the exception of adding new fields in the future once they implement and exp/leveling system. There should be no changes to the way that skill_inventory_t is stored in the player struct

**Comment by afranzese99** [comment]
After further discussion with the rpg-playerclass team, we agreed that the `class struct` will contain the base-health and other base-values of stats while the `player struct` will contain a current/up-to-date representation of health and other stats. We need to make this clear in the documentation/comments.

**Comment by WPDolan** [comment]
@afranzese99 have updated the integration plan to accommodate the requests of the current relevant RPG teams. Documentation is completed and we are now ready to implement the plan in #875.

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Great work! You did a particularly good job providing documenting meeting **outcomes** (and not just that the meeting had occurred).
