### ISSUE TITLE
Review npc/rpg-npc/battle code and make a plan to integrate them. 

### ISSUE THREAD

**Issue by amymorrill** [uchicago-cs/chiventure#828]
The NPC teams from last year worked on battles with NPCs but were not able to fully integrate NPCs and battles. To continue their work, we will review npc, rpg-npc, and battle code, as well as consulting with the battle team, to formulate a plan for this integration. Moreover, we will consider possible additions to NPCs' current attributes (like weapons, skills, etc.) which could be added helpful in integrating them with battles.

**Comment by northofsophia** [comment]
Amy and I discussed how to integrate npcs into battles, including adding hostility levels to npcs, integrating weapons, surrender levels, npc death statuses and item drops post-death. We could also remove the npc-enemy struct in the battle module as this info could be directly integrated into the npc struct. We've reached out to the battle team about these changes and hopefully we can start implementing them soon.

**Comment by amymorrill** [comment]
> Amy and I discussed how to integrate npcs into battles, including adding hostility levels to npcs, integrating weapons, surrender levels, npc death statuses and item drops post-death. We could also remove the npc-enemy struct in the battle module as this info could be directly integrated into the npc struct. We've reached out to the battle team about these changes and hopefully we can start implementing them soon.

**Comment by amymorrill** [comment]
To add to Sophia's comment, we updated the Npc Design and Planning wiki page to include our plans.

**Comment by amymorrill** [comment]
We have decided on a course of action to integrate npc and battle code — talking with the battle team, changing the information in the npc struct to include pertinent information for battles, and having the battle team delete their npc-enemy struct, instead just using the npc struct. While designing this, we noticed some inconsistencies in the npc struct in general (like multiple versions of the same parameter), so we will also clean those up. Finally, we realized that having npcs drop items post death will take a bit more planning, so we will tackle that issue separately from general npc/battle integration. The npc design and planning wiki page (https://github.com/uchicago-cs/chiventure/wiki/NPC-Design-and-Planning) has been updated to include this information.

**Comment by lilyehsani** [comment]
Issue Score: ✔️++

Comments:
Great work on this issue! The summary and closing statement are detailed and to-the-point. In the future, you could benefit from more updates, but for a straightforward task like this, the closing statement is enough.
