### ISSUE TITLE
Research PortAudio library

### ISSUE THREAD

**Issue by jiguba** [uchicago-cs/chiventure#829]
We are currently researching the implementation of PortAudio, a free, open-source, audio I/O library that writes simple audio programs in C/C++. Below are the following links that will aid in our research of the PortAudio library.
http://www.portaudio.com/
http://www.mega-nerd.com/libsndfile/

The purpose of this research is to explore the documentation and implementation of the PortAudio library. We will report the advantages and disadvantages of using PortAudio on a wiki that reports our research on various sound libraries. 

Some noticeable benefits are that it currently maintained by a community of PortAudio developers and that PortAudio has supported many applications for audio I/O.

**Comment by jiguba** [comment]
On April 19th, the members of the sound team conducted a meeting with Elizabeth, our senior developer. After introductions, we discussed our visions for the implementation of sound for chiventure and did a brief overlook of the chiventure repository. Various members were assigned to conduct research on sound libraries. Kyu and I have been assigned PortAudio.

**Comment by jiguba** [comment]
April 23rd: To begin my research of PortAudio, I download the source code from [http://files.portaudio.com/download.html](url) and extracted the folders which created a 'portaudio' directory. I attempted to follow the [PortAudio tutorials](http://files.portaudio.com/docs/v19-doxydocs/compile_windows.html) to compile the portaudio library for Windows using Microsoft Visual Studio. However, compiling the library was unsuccessful. Conducting an online search, I found a [tutorial ](https://www.youtube.com/watch?v=PIswwa4UlRE) using a macOS system and xCode. I am currently downloading xCode and have installed the portaudio source files on a macOS system. The current goal right now is to successfully compile the portaudio library.

**Comment by gypark23** [comment]
April 25th: I have also downloaded the source code from the [main website](http://files.portaudio.com/download.html), in .tgz format. I have extracted the folder and I have also followed the [PortAudio tutorials](http://files.portaudio.com/docs/v19-doxydocs/compile_mac_coreaudio.html) for MacOS. I am using Visual Studio Code, not Xcode, and I attempted compiling it using `./configure && make` on terminal, and it successfully compiled. The new goal would be to be able to run test files using PortAudio library.

**Comment by gypark23** [comment]
> April 25th: I have also downloaded the source code from the [main website](http://files.portaudio.com/download.html), in .tgz format. I have extracted the folder and I have also followed the [PortAudio tutorials](http://files.portaudio.com/docs/v19-doxydocs/compile_mac_coreaudio.html) for MacOS. I am using Visual Studio Code, not Xcode, and I attempted compiling it using `./configure && make` on terminal, and it successfully compiled. The new goal would be to be able to run sample files (paex_saw.c is the sample file I am using) using PortAudio library.

Update: I tried to compile the sample c file, however it prints out error that my ARM processor cannot find the references to some of the x86 commands. I will try to compile it using x86 CS linux machine.

**Comment by jiguba** [comment]
April 25: I was able to compile the PortAudio library using a macOS system. I reattempted to build the portaudio library on the Windows system. To test that I was able to properly use the header file, I used VS Code to create a simple hello world program that include the portaudio header file. I was able to compile, but whenever I called a function from the portaudio library, I got a reference error. Successfully compiling the portaudio library generates a .dll file on Windows and I attempted to compile a .dll using VS Code. After many unsuccessful attempts, I transitioned to Visual Studio to familiarize myself with the interface.

**Comment by jiguba** [comment]
Using this [guide ](https://docs.microsoft.com/en-us/cpp/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp?view=msvc-160) I was able to create a project that utilized the portaudio library by adding references and pathways to access the required portaudio header file and port audio library (the .dll file). Using one of the example sound programs from port audio, (paex_saw.c), I attempted to build a program to playback sound. I originally ran into a [C2440](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2440?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C2440)%26rd%3Dtrue&view=msvc-160). However, I realized my mistake was using a .c file format instead of a .cpp file format. After converting my TestSound.c file to TestSound.cpp, the program successfully built and created an executable file that played back the sound (that nearly blew out my ears).

**Comment by jiguba** [comment]
This issue is pending closure because research on the PortAudio library has been posted to the Sound wiki. However, this may need to be reopened because the executable sound file was created locally rather than the Linux server. I will need to identify how to connect Visual Studio to the CS linux servers in order to save the files I create.

**Comment by jiguba** [comment]
Closing Statement: The benefits and potential drawbacks have been added to the sound [wiki](https://github.com/uchicago-cs/chiventure/wiki/Sound:-Research-Implementation-and-User-Stories).  An executable file was made that played back sound, so moving forward, we may want to experiment with making our own sounds by developing a deeper understanding of the PortAudio API. In conclusion, PortAudio is a potential sound library that we can use.

**Comment by ecoble** [comment]
Issue Score: ✔️+

Comments:
Great job researching this library! The research and updates are really thorough. In the future, be sure to convert cards into issues shortly after the sprint meeting.
