### ISSUE TITLE
Read the skilltrees markdown doc file and summarize it in a wiki page.

### ISSUE THREAD

**Issue by m-ghosal** [uchicago-cs/chiventure#832]
Assignee: Maya
team:skilltrees

**Comment by m-ghosal** [comment]
Summarized the skill trees md doc file - summarized the info from all 3 versions (1.0, 2.0,2.1) into one concise wiki. Got an idea of the implementation and interface of the two main modules - global skill tree and individual skill trees.

**Comment by firatciftci** [comment]
Issue Score: ✔️+

Comments:
Good job! I only have one thing to comment on:
- The issue did not include a descriptive summary (see https://uchicago-cs.github.io/cmsc22000/project/policies.html#tasks-issues for more details and concrete examples)
