### ISSUE TITLE
Research potential parsing libraries in other languages

### ISSUE THREAD

**Issue by tessied** [uchicago-cs/chiventure#834]
Our goal is to briefly research parsing libraries in other languages (e.g. python) in case our team decides to work on the DSL feature. We will assess the pros and cons, and the research process will be documented under this issue.
Assignees: Tessie and John

**Comment by tessied** [comment]
I've identified a potential parsing library in Python called pyparsing: https://github.com/pyparsing/pyparsing

From reading the documentation and a sample program, the usage of this library seems fairly intuitive. The module also handles a few problems to simplify the parsing process for the user, including handling extra or missing spaces and quoted strings.

**Comment by tessied** [comment]
Another promising library is the lark-parser: https://github.com/lark-parser/lark

Some of the pros I've identified include:
1. It boasts great beginner-friendliness: "it can parse any grammar you throw at it, no matter how complicated or ambiguous, and do so efficiently". 
2.  It automatically builds an annotated parse-tree.
3. It is great at handling ambiguity (e.g. handles situations where a word can be used as multiple parts of speech, for example, when a word can be both a verb and an adverb, both a noun and an adjective, etc.)

Comparing this parsing library with pyparsing (mentioned in the comment above), Lark is faster and more memory-efficient.

**Comment by ecoble** [comment]
Issue Score: ✔️

Comments:
Great job, especially with the updates! In the future, be sure to have a clear closing statement to the issue, and convert the card to an issue shortly after the sprint meeting. Also, it would be better to keep documentation on research in a Wiki for your team, so that it is easier to reference in the future.
