### ISSUE TITLE
Look into current state of CLI and WDL and decide whether you want CLI++ or DSL

### ISSUE THREAD

**Issue by r-e-stern** [uchicago-cs/chiventure#837]
John will investigate and describe the current state of the CLI/WDL, and as a team we'll decide which direction to take.

**Comment by john-hahn** [comment]
**Current state of CLI:**
There are four modules of cmd, operations, parser, and shell
- the `cmd` module includes a set up of the data struct for commands and functions that help navigate and manipulate elements of the struct
- the `operations` module links the operation to the corresponding action, which includes functions that validate the action inputted by the user, show the current inventory, and match the action input to the correct category to be run. (the bulk of the CLI work is done in this module)
- the `parser` module includes one function that parses the input string into a list of words for easier manipulation in the lower-level modules
- the `shell` module runs shell actions such as printing the greeting message, the help menu, the history of valid commands, and error messages

_Overview_: The current state of CLI includes parsing capabilities that are able to handle basic actions, such as handling a single path, a single item, or two items. There is room for work for functions that handle more complex tasks that are inputted by the user.

**Current state of WDL:**
There are a total of 12 modules: attributes, load_game, load_item, load_room, load_wdz_internal, load_wdz, object, objstore, parse, validate, wdl_common, wdl_ctx
- the `attributes` module has a struct for attributes stored in an object and includes functions for accessing the hash table and linked lists and manipulating its elements
- the `load...` modules are self-explanatory and load the stated feature
- the `object` module has structs for object type and attribute type and includes functions for creating and accessing the specified type
- the `objstore` module has a struct for the storage of objects that are attained from parsing from WDL++ format. It also includes functions that create the struct and access the elements within
- the `parse` module is responsible for getting room, item, and player objects from a YAML file
- the `validate` module is responsible for checking objects have all the required fields and checking that those fields are of the right type

_Overview_: The current state of WDL implemented numerous structs to extract objects from a YAML file that is compiled down to the WDL++ format. There are many unfamiliar terms that would require self-guided research, but it is very low-level that can be made sense of by looking at each module and seeing how each layer is connected to its previous or following layer.

**Comment by Mich0608** [comment]
We had a team meeting today to discuss whether we want to work on CLI++ or DSL. The current consensus is to work on DSL. Several things we considered in our decision were:
1. Working on a feature that's separate but dependent on the chiventure code
2. Producing something tangible by the end of the quarter
3. Coding in another language, like Python

**Comment by ecoble** [comment]
Issue Score: ✔️+

Comments:
Great job! You have great updates here and a concise closing statement. In the future, be sure to convert the backlog cards into Github issues shortly after the sprint meeting.
