### ISSUE TITLE
Edit and Update wiki page on npc/skilltrees integration

### ISSUE THREAD

**Issue by matiasp-10** [uchicago-cs/chiventure#838]
Assignee: Matias, Andrew, Dylan
team:npc2

**Comment by matiasp-10** [comment]
Currently, there is an NPC Design and Planning wiki page that does not contain information on the integration of skill trees into the NPC design. We will update this page by reading through the existing code to provide a clearer overview of how skill trees can possibly be integrated with their currently available design and that of NPCs.

**Comment by andrewg23** [comment]
There does not seem to be any previous intention to integrate skill trees with NPCs. We found that the current NPC struct does not include a skill tree but does include two player class structs which are possibly redundant. We will look into player classes next.

**Comment by andrewg23** [comment]
We found that the player class struct currently contains a stub skill tree struct. It seems like skill trees are planned to be integrated into player classes and through that into NPCs as well.

**Comment by andrewg23** [comment]
Subject to a pull request (issue  #833), skill trees will be integrated with player classes. This means that the implementation of skill trees into player classes will be done and therefore indirectly integrated with NPCs.

**Comment by MaDDylan** [comment]
Clarification for skill_trees within player class. 
Are skill trees defined in the player class a general skill tree or a specific skill tree dependent on class? In other words, does the player class-defined skill tree represent a specific set of skills inherent to a specific player_class or does it represent a player's/npc's complete skill tree?

**Comment by matiasp-10** [comment]
Updated [NPC Design and Planning](https://github.com/uchicago-cs/chiventure/wiki/NPC-Design-and-Planning) with RPG - Player Class and Skill Trees Overview section and with Task allocation between NPC teams section.

Below is the new recommended npc struct fixing the double class field problem:

`typedef struct npc {
    /* hh is used for hashtable, as provided in uthash.h */
    UT_hash_handle hh;

    /* NPC identifier */
    char *npc_id;

    /* short description of the npc, <51 chars */
    char *short_desc;

    /* long description of the npc, <301 chars */
    char *long_desc;

    int health;

    /* pointer to an existing convo struct */
    convo_t *dialogue;

    /* pointer to inventory hashtable */
    item_hash_t *inventory;

    /* the npcs class */
    class_t *class;
} npc_t;
`

**Comment by jackcasey067** [comment]
@MaDDylan
> Clarification for skill_trees within player class.
Are skill trees defined in the player class a general skill tree or a specific skill tree dependent on class? In other words, does the player class-defined skill tree represent a specific set of skills inherent to a specific player_class or does it represent a player's/npc's complete skill tree?

There is room for this to go either way in the future.  However, at the moment each class has one skill tree associated with it (one tree id), and it seems the skill trees team might intend for there to be multiple skill trees available to a player.  Therefore, at the moment, the playerclass skill tree does not represent the entirety of skills available to the player / an npc, just skills associated with a class.

I would say we are still working out the details though.  We may want more complex interactions between the two features in the future.

**Comment by MaDDylan** [comment]
Closing Comment: Implementing skill trees into NPCs will not be pursued at this time. The implementation of Skill trees into player_class is in progress between their respective teams. Integration of skill trees into the npc feature will depend on how the two teams proceed.

**Comment by lilyehsani** [comment]
Issue Score: ✔️+

Comments:
Great work! The summary, updates, and closing comment are thorough and on topic. In the future, be sure to convert the backlog cards into GitHub issues shortly after the sprint meeting.
