### ISSUE TITLE
Draft design document for quest trees

### ISSUE THREAD

**Issue by gabigarc03** [uchicago-cs/chiventure#840]
The quest infrastructure currently uses linked lists to create quests out of a list of achievements. This allows for exactly one possible set of achievements to be used to complete a quest, which is rather inflexible. We want to redesign the module to use trees to allow for multiple different pathways for completing a quest.

**Comment by oliviajerdee** [comment]
Yesterday all three of us met on Zoom and discussed the old code and tried to start a rough plan for our design. We created a Google Doc for our design document and added notes about our ideas and identified issues we currently have and need to address in the future.

**Comment by zsp255** [comment]
Created initial design document for quest struct detailing the current design, potential new design, and reason for this change. Still need to discuss how we plan to change the existing functions to accommodate this as well as maintain backwards compatibility if necessary.

**Comment by zsp255** [comment]
Completed design document detailing incorporation into the quest struct as a whole and future direction for the upcoming sprints which will involve restructuring existing code and adding tree search functions.

**Comment by oliviajerdee** [comment]
Added information about possible future features such as path traversal (having the player commit to a path and not being able to go back) and displaying all tree paths before they choose their path

**Comment by zsp255** [comment]
Completed wiki page on updated quest struct using trees and future directions: https://github.com/uchicago-cs/chiventure/wiki/Version-2.0-of-Quests-Struct-to-Include-Trees. We will need to make some conceptual design decisions for implementation next sprint.

**Comment by lilyehsani** [comment]
Issue Score: ✔️+

Comments:
Great work! The summary and updates are thorough and on topic.
- Status updates on an issue should have something tangible to share.
- Remember that Scrum board cards should be converted to issues shortly after the Sprint meeting. Think of the Scrum board card as a rough outline of the issue, which you then need to flesh out with a more descriptive title and summary when converting it to an issue.
