### ISSUE TITLE
Research SDL library

### ISSUE THREAD

**Issue by jiguba** [uchicago-cs/chiventure#845]
We will explore the documentation of the SDL library and identify the advantages and disadvantages of using SDL. 

Research on the SDL library will be added to the sound [wiki](https://github.com/uchicago-cs/chiventure/wiki/Sound:-Research-Implementation-and-User-Stories). 

The following link will help aid in the research of the SDL Library.

https://www.libsdl.org/projects/SDL_mixer/

**Comment by jiguba** [comment]
April 26th: I downloaded the source files for SDL and began a simple project in Visual Studio with the aid from the following [video](https://www.youtube.com/watch?v=Sfn7yOiwJLw). The only error in building the project file was the use of the wrong library file. Instead of using the library file from the /x86 pathway, I used the /x64 pathway (this is covered in the video).

From my initial search, SDL is under the zlib license, allowing us to use SDL in our software. The SDL Wiki also provides many helpful links to installation, tutorials, and documentation using the API. I will update the research wiki with helpful links and a basic summary of SDL. 

Previous research on closed issues revealed that libsdl was researched for graphics and UI implementation. We may want to explore their code from the previous year and see if we can implement sound.

**Comment by jiguba** [comment]
Added research to the sound wiki along with useful links that guide future developers to tutorials, documentation, and the SDL repository.

**Comment by jiguba** [comment]
Research on the SDL library was added to the Sound wiki. By building the SDL library, we can begin developing a further understanding of the SDL API by building simple audio programs. We may also want to confirm if the SDL library was used in chiventure during a previous implementation.

**Comment by ecoble** [comment]
Issue Score: ✔️+

Comments:
Nice job researching this library! The frequent updates and clear closing statement great. In the future, be sure to convert the card into an issue shortly after the sprint meeting.
