### ISSUE TITLE
Research libsoundio library

### ISSUE THREAD

**Issue by DemS2000** [uchicago-cs/chiventure#850]
https://github.com/andrewrk/libsoundio
Assignees: Shuwen and Vivian
team:sound

**Comment by DemS2000** [comment]
https://github.com/andrewrk/libsoundio
I think the library just standardizes all the different sound drivers into the same API. A sound driver converts ‘raw signals’ into a format that can be understood by speakers, and the library enables you to program using the same API regardless of the sound driver (e.g. mac, windows, linux can have different sound drivers).  
It supports the following backends, though I’m not sure what that means (is it the driver?):
JACK
PulseAudio
ALSA
CoreAudio
WASAPI
Dummy (silence)

**Comment by vivianwu00** [comment]
Added Libsoundio findings to Wiki: Libsoundio is an open source API that provides cross-platform audio input and output. The library linked to the GitHub is an abstraction with an emphasis on performance for heavy, real-time software like digital audio workstations and consumer software like music players. (VW)
JACK: A low-latency audio server, used to connect several client applications to an audio device, and allow them to share audio with each other. There is no difference in how an application sends or receives data regardless of whether it comes from/goes to another application or an audio interface.

PulseAudio: A modular, general purpose sound server. Its main purpose is to ease audio configuration, its modular design allows more advanced users to configure the daemon precisely to best suit their needs. PulseAudio

ALSA: The Advanced Linux Sound Architecture (ALSA) provides kernel driven sound card drivers. It replaces the original Open Sound System (OSS). Besides the sound device drivers, ALSA also bundles a user space driven library for application developers. They can then use those ALSA drivers for high level API development.

CoreAudio: Core Audio is the digital audio infrastructure of iOS and OS X. It includes a set of software frameworks designed to handle the audio needs in your applications. Read this chapter to learn what you can do with Core Audio.

WASAPI: The Windows Audio Session API (WASAPI) enables client applications to manage the flow of audio data between the application and an audio endpoint device. Every audio stream is a member of an audio session. Through the session abstraction, a WASAPI client can identify an audio stream as a member of a group of related audio streams. The system can manage all of the streams in the session as a single unit.

**Comment by ecoble** [comment]
Issue Score: ✔️+

Comments:
Great job researching this issue and creating thorough documentation! Be sure that the summary of issues has a description of the task, and that issues have proper milestones.
