### ISSUE TITLE
Update Player Class/Attribute Integration

### ISSUE THREAD

**Issue by ideclue** [uchicago-cs/chiventure#851]
Currently, the only way Player Classes can interact with items is through class item restrictions. In order to add to this functionality and clean up existing class item restriction code, it will be helpful to improve the Player Class/attribute integration in order to eventually brainstorm and add more features. This issue will consist of two primary components:

1. Updating the current class item restriction code to reflect changes from Pull Request #846: The return and function parameters of many of the attribute linked list functions were altered after the review of this Pull Request 
2. Altering the method for creation of attributes of an item (by adding `attribute_new` and `attribute_init` functions) in order to make it easier to add class item restrictions inside `playerclass` code, and eventually, add more interactions between player classes and items

**Comment by ideclue** [comment]
Component (1) of the three components of this issue (outlined above) has been completed. The main changes completed in this component included:

- Updating functions and tests in `class_item_restriction.c` that were using outdated versions of `attribute_list_t` functions
- Changing the `remove_attribute_from_list` function in `item.c` so attributes can be removed when referenced only by their name. This change allows for clearer class item restriction code

Once PR #847 is merged, these changes will be reflected in `dev`.

**Comment by ideclue** [comment]
In order to complete component (2), it will be necessary to choose between two designs of modifying attribute creation, both of which will involve significant changes to `item.c`. Currently, the only way attributes can be created is through type-specific `set_attr` functions (e.g. `set_bool_attr`, `set_char_attr`) that create attributes and immediately add them to `attributes` hash table. However, in order to streamline class item restriction creation, it is necessary to be able to create an attribute without immediately adding it to the hash table, since class item restrictions are now managed independently via the `class_restrictions` linked list field in the `item` struct.

The two design options include:

1. Only adding `attribute_new` and `attribute_init` functions and leaving all other functions as is. **Downside**: Only allows certain types of attributes (boolean) to be created via this method, therefore limiting the ways in which player classes and items could potentially interact.
2. Refactoring the current `set_attr` functions to be `attribute_init` functions, with a separate function being called to add these attributes to the hash table. **Downside**:` May cause unexpected changes in other parts of chiventure that currently use item attributes.

After reviewing the code base, I have decided to go with option 2, as it will allow for more types of interactions between player classes and items to be developed.

**Comment by ideclue** [comment]
I added and implemented several type-specific functions in `item.c` in order to facilitate attribute creation inside of the `playerclass` module. These functions include:

- `str_attr_new` for creating string-specific attributes
- `int_attr_new` for creating integer-specific attributes
- `double_attr_new` for creating double-specific attributes
- `char_attr_new` for creating character-specific attributes
- `bool_attr_new` for creating boolean-specific attributes

Now, the creation of type-specific attributes is streamlined and can occur in different modules, rather than being constrained to the `set_attr` functions in `item.c`. In order to finish component (2) of this issue, two tasks remain:

- Create and successfully run test cases for these functions
- Refactor current class item restriction code to use these new functions

**Comment by ideclue** [comment]
- Test cases have been added and successfully run for the five new functions (listed above)
- Class item restriction code now uses the new type-specific attribute creation code

All test cases in `playerclass` and `game-state` currently pass. Code is ready to be reviewed in a Pull Request.

**Comment by ideclue** [comment]
Closing Statement:

Both components of this issue have been merged with `dev` following successful Pull Requests. Attributes can now be created in modules outside of `game-state`, and the stage is set to develop a more complex relationship between player classes and items.

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Great work! Your updates are very detailed and provide an extensive understanding of the progression of your work.
