### ISSUE TITLE
Determine which sounds library to use

### ISSUE THREAD

**Issue by jiguba** [uchicago-cs/chiventure#852]
The purpose of this task is to discuss the pros and cons of all the sound libraries. We will plan a meeting to discuss our research and decide on the sound library we will use for sound implementation.

**Comment by jiguba** [comment]
April 26th: An invitation was sent out to other sound team members to discuss our research on the assigned sound libraries.

**Comment by vivianwu00** [comment]
4/28/21 6pm meeting: Decided to use Libsdl library for its ease of integration into game software and for the availability of tutorials and examples.

**Comment by ecoble** [comment]
Issue Score: ✔️++

Comments:
Great job with the meeting update! If there are any documents from the discussion, please include them in the wiki as well.
