### ISSUE TITLE
Make token list size flexible

### ISSUE THREAD

**Issue by dchen0258** [uchicago-cs/chiventure#853]
Currently the token list, which is the list that contains the actions and objects within a command, is capped at 4. We should make the list size more flexible especially with the implementation of "and" in the parser. For example, a command such as "put [item] and [item] on [item]" would not currently be supported, even though this would be a reasonable action to complete.

**Comment by dchen0258** [comment]
How this issue is dealt with depends on what who we think should control the list size. Perhaps the game author wants to allow for more token commands, so we can give them the choice. However, this could allow things to get out of hand. For example we don't really/want a token list of size 100.

**Comment by dchen0258** [comment]
We decided to leave this issue for when we have a more clear idea of what the size should be exactly, and whether we want the author or developer to change it.

**Comment by Beza20** [comment]
Go to issue #1070
