### ISSUE TITLE
Change the implementation of skills from returning a string to a more full fledged modification of attributes.

### ISSUE THREAD

**Issue by rohangupta2806** [uchicago-cs/chiventure#855]
Currently skills just seem to return a string that gets fed to the CLI.  Ideally, we would like to work with player classes (and maybe other teams related to the RPG aspect), and have a more full fledged implementation where a skill is actually a modification of attributes.

**Comment by rohangupta2806** [comment]
Implementation of certain functions depends upon pull request #898 being approved as we require access to the stats hash table belonging to the player.

**Comment by rohangupta2806** [comment]
This has resulted in implementation of v1 of effects.  There are currently three different types of effects, each requiring their own distinct implementation that require collaboration with other teams.  As a result, the implementation of each type of effect will now be its own separate issue.

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Great work! The only thing I can comment on is that, make sure to assign new issues to the sprint they are worked on (by selecting the appropriate sprint under "Milestone").
