### ISSUE TITLE
Brainstorm ideas on how to add a leveling system to the skills.

### ISSUE THREAD

**Issue by m-ghosal** [uchicago-cs/chiventure#856]
Assignee: Maya, Joshua
Team: Skill Trees

**Comment by Joshuashou** [comment]
Met and decided to divide up tasks into researching skills leveling and skills leveling implementation into ChiVenture. Creating a Wiki documenting progress for the research

**Comment by Joshuashou** [comment]
We closed this issue after sprint 2. Maya and I were able to do extensive research into the potential ways we could implement skill levelling and level-locks on skills in a skill tree, and hope to continue on actually implementing the changes in our next issue over the course of the next week / 2 weeks. We also hope to flush out some of the code, especially regarding the structs and header files, to make it more clear and convenient.

**Comment by m-ghosal** [comment]
Below is a link to the wiki outlining the leveling system that we intend to integrate:
https://github.com/uchicago-cs/chiventure/wiki/Integration-of-a-leveling-system

**Comment by firatciftci** [comment]
Issue Score: ✔️+

Comments:
Good job! I only have one thing to comment on:
- The issue did not include a descriptive summary (see https://uchicago-cs.github.io/cmsc22000/project/policies.html#tasks-issues for more details and concrete examples)
