### ISSUE TITLE
Research on skill tree implementation beyond combat skills and clean up the skill tree wiki docs.

### ISSUE THREAD

**Issue by tgao564** [uchicago-cs/chiventure#857]
Existing research on skill tree implementation focuses on active and passive combat-related skills. Research needs to be done on how skill trees can interact with things such as adding options to NPC dialogue or interacting with the open world. Additionally, the current skill tree summary wiki is formatted badly and the six other skill tree wikis need to be linked to the summary page.

Assignee: Tyler
Team: Skill Trees

**Comment by tgao564** [comment]
5/1
- Added some more information and improved upon the format of the skill trees wiki summary page
- Linked summary page to the other skill tree pages

**Comment by tgao564** [comment]
5/3 
Research into non-combat based skills and skill trees including
-Dialogue skills with npcs
-Dialogue skills with enemies
-Stealth skills
-Travel skills

**Comment by tgao564** [comment]
Updated wiki summary: https://github.com/uchicago-cs/chiventure/wiki/SkillTree-Wiki-Summary
Research on non-combat skill trees found here: https://github.com/uchicago-cs/chiventure/wiki/Skill-tree-design-ideas-in-connection-to-other-features

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Great work!
