### ISSUE TITLE
Read CLI Documentation and discuss possible improvements

### ISSUE THREAD

**Issue by dchen0258** [uchicago-cs/chiventure#858]
Go through CLI documentation, make note of things that maybe need fixing or could be improved, larger improvements for sprint 3 and 4 etc.

**Comment by dchen0258** [comment]
Currently based on what was discussed during the team meeting, these are some possible new features that could be added:
Hints: A player could ask for a hint for a quest etc.
Items in a room: A player could ask for a list of the items in a room
Battles and NPC integration: features that the battles and NPC teams want to add should be properly integrated into the CLI

**Comment by dchen0258** [comment]
Looking at the operations.c file, there is a function called the "hist_operation" with the comment saying "backlog" and I think that this issue #271 and issue #273  could be a good thing to work on.

**Comment by dchen0258** [comment]
In the shell.c file there is mention of a load and save command that has not been implemented yet. Possible issue to work on in the upcoming sprints.

**Comment by dchen0258** [comment]
Also issue #413 regarding better line wrapping could be looked at.

**Comment by dchen0258** [comment]
Currently implementing the history command, and further items on this issue can be looked at in the future.

**Comment by ecoble** [comment]
Issue Score: ✔️++

Comments:
Great job looking into this! I would definitely recommend adding this to the CLI documentation, possibly as part of the "clean up documentation" issue that we have for later in sprint 4.
