### ISSUE TITLE
Play Sound using SDL library on linux machine

### ISSUE THREAD

**Issue by Imagineham** [uchicago-cs/chiventure#863]
The purpose of this issue is to further research the SDL library and its applications with sound. The sound team hopes to use the SDL library to successfully play an audio file, and throughout, document files required, functions used, and other important details in our [wiki](https://github.com/uchicago-cs/chiventure/wiki/Sound:-Research-Implementation-and-User-Stories)

**Comment by Imagineham** [comment]
5/3 Elizabeth updated the team and told us that SDL was successfully installed onto the linux machines. For the sake of transparency and for future reference here are the SDL libraries we have installed ($ dpkg -l | grep sdl):

ii  libsdl-image1.2:amd64                                       1.2.12-12                               amd64        Image loading library for Simple DirectMedia Layer 1.2, libraries
ii  libsdl1.2-dev                                               1.2.15+dfsg2-5                          amd64        Simple DirectMedia Layer development files
ii  libsdl1.2debian:amd64                                       1.2.15+dfsg2-5                          amd64        Simple DirectMedia Layer
ii  libsdl2-2.0-0:amd64                                         2.0.10+dfsg1-3                          amd64        Simple DirectMedia Layer
ii  libsdl2-dev:amd64                                           2.0.10+dfsg1-3                          amd64        Simple DirectMedia Layer development files
ii  libsdl2-mixer-2.0-0:amd64                                   2.0.4+dfsg1-2build1                     amd64        Mixer library for Simple DirectMedia Layer 2, libraries
ii  libsdl2-mixer-dev:amd64                                     2.0.4+dfsg1-2build1                     amd64        Mixer library for Simple DirectMedia Layer 2, development files

**Comment by Imagineham** [comment]
5/3 We were also able to get SDL_mixer to work on a linux machine using virtual box! We followed the tutorial on this [page](https://soundprogramming.net/programming/tutorial-using-sdl2-and-sdl_mixer-to-play-samples/#:~:text=Using%20SDL_Mixer%20lets%20you%20use%20multiple%20audio%20playback,need%20to%20have%20is%20a%20working%20build%20environment.) and we able to successfully play Kick-Drum-1.wav and Snare-Drum-1.wav. We had to make some changes to the instructions and so a step by step of how we played sound using the virtualMachine can be found on our wiki here.

**Comment by Imagineham** [comment]
5/3 While working on playing sound using SDL_mixer, we realized that many google searches to using the mixer will point to this [page](https://www.libsdl.org/projects/SDL_mixer/docs/index.html). This page works for SDL and not SDL2 which is the library we want to use. The difference is important because the code and tutorials on this page have deprecated. We will use this [migration guide](https://wiki.libsdl.org/MigrationGuide) in order to adapt the code we have to SDL2.

**Comment by Imagineham** [comment]
5/25 After downloading the UChicago CS Linux image from [here](https://howto.cs.uchicago.edu/vm:index) and following the install tutorial using VirtualBox found [here](https://howto.cs.uchicago.edu/vm:install), we were able to compile and play sound. Tech staff has been working on fixing the bug that prevents sound to be played through the CSIL machines (whether through ssh or noMachine).  At this point, we can confidently utilize the SDL library to play sound.

**Comment by ecoble** [comment]
Issue Score: ✔️++

Comments:
Great job getting this working, I know this was really tough especially with the bug on the Linux machines!
