### ISSUE TITLE
Begin implementing "mode" functionality in the CLI in order to integrate NPC dialogue

### ISSUE THREAD

**Issue by pkasner** [uchicago-cs/chiventure#864]
Currently, the CLI can only interpret user input as game commands (push, pick up, look, etc). To implement dialogue, we would like to isolate user input from this function by creating a mode struct or field accessible by the game context. In "conversation mode" the CLI does not treat the user input as a command, but only checks for dialogue options.
Assignees: Peter, James
team: npc2

**Comment by pkasner** [comment]
Verified the planned structural changes necessary to implement mode functionality with Senior Developers for CLI and NPC team. Determined that the necessary fields would be something akin to the mode name, the mode's run function, and the mode's context

**Comment by pkasner** [comment]
Created npc/mode branch. Wrote a basic implementation of mode struct, added mode field to game struct.
fc94c2d15084725b2f825cee9e8902916af66e1b

**Comment by pkasner** [comment]
Chiventure now loads in normal mode, and everything compiles

**Comment by lilyehsani** [comment]
Issue Score: ✔️++

Comments:
Great work overall! You opened the issue very quickly after the sprint meeting and the updates are thorough.
