### ISSUE TITLE
Begin quest integration into chiventure RPG modules and Create Formal Design Document

### ISSUE THREAD

**Issue by ddelgado60** [uchicago-cs/chiventure#870]
In Sprint 1, we made good progress in learning about how quests are currently integrated into chiventure, and understand what we need to do in order to allow users to interact with quest modules in the future. We plan to create a formal design document detailing how and where quests will be integrated, and hope to begin the implementation process in sprint 3.

Assignees: Devon, Dillon
team: quests

**Comment by ddelgado60** [comment]
We reached out to the NPC and the Battles teams to learn more about how their modules are structured, and how we could possibly forsee the quests module being incorporated. We should have a quick chat with the teams soon, and with the information we gain, will move on to create a design document.

**Comment by dillonoloughlin** [comment]
Spoke with the NPC team about integrating quest functionality with NPCs. We spoke of two potential implementations, adding a start_quest function pointer to NPC dialogue nodes to allow different dialogue nodes to offer different quests and of adding a Quest Action to action management and then creating entirely different dialogue trees designated specifically for quests. We were leaning toward the function pointer integration but the NPC team is currently working on updating and better integrating dialogues into Chiventure in this sprint and would like us to wait until next sprint before moving forward on either of the ideas.

**Comment by ddelgado60** [comment]
We created a design document, which is linked here: https://github.com/uchicago-cs/chiventure/wiki/Quest-API-Design-Document

**Comment by dillonoloughlin** [comment]
Spoke with the Battles team about our design document's implementation of battles into quests. We agreed that the current implementation of using npc_ids and checking if an npc's health is zero could work for very specific NPCs to kill like if you wanted to slay a dragon. We also came to the conclusion that for quests like "Kill 5 werewolves", that could be accomplished by having werewolves drop a specific item when they die and use quest's current implementation of items to check if the user has collected 5.

**Comment by dillonoloughlin** [comment]
We finished the design document and are moving ahead with confirming our designs with other team and implementing our designs in the next sprint
