### ISSUE TITLE
Review npc/action branch and update/edit the existing Wiki page pertaining to NPC actions.

### ISSUE THREAD

**Issue by MaDDylan** [uchicago-cs/chiventure#871]
Assignee: Dylan, Andrew, Matias
Team: npc-2

Review the code started by last years team for player and npc interaction. We should familiarize ourselves with the action_management code, and then discuss how to move forward.

Post our feedback and plans for implementation to the wiki page: https://github.com/uchicago-cs/chiventure/wiki/NPC-Player-Interaction-Design-and-Planning

**Comment by matiasp-10** [comment]
Found out that the New NPC Action Module header within the [Wiki page](https://github.com/uchicago-cs/chiventure/wiki/NPC-Player-Interaction-Design-and-Planning#new-npc-action-module) describes .h files that are not currently found within the npc/actions branch. However, the code described within those files seems to be spread about other files. We will look to contact our senior developer for more details as to whether:
1. These file structures described in the Wiki page were for future planning and restructuring of function locations
2. This was an initial plan for file structures and it was later changed and just not updated within the Wiki page

**Comment by matiasp-10** [comment]
For the time being, I decided to update the Wiki page for the current file structure within npc/actions/include/npc and where specific functions are located. This was done for ease of work across other teams that need to work with the current npc/actions code, and because we are yet to make a final decision on whether or not the current file structure is necessary to change. This decision will be based off of upcoming discussions within our own and possibly the other npc team so as to be careful with running into conflicting changes.

**Comment by MaDDylan** [comment]
Noticed that the Wiki page points to some uncertainty about the future of integrating an extra field within the existing NPC struct to hold possible NPC actions. Planning to meet with senior developer, action management team, and possibly game state team this weekend to better understand current and future plans with the game action hash structs. Also to clarify why the previous npc team thought to work with a standalone game action struct for npcs, but decided to utilize a game_action struct defined in game-state's item.h.

**Comment by matiasp-10** [comment]
Meeting with the @x/action-management clarified the lack of necessity for extra abstraction away from the current game_action struct for implementation with NPCs. I finished updating the [Wiki page](https://github.com/uchicago-cs/chiventure/wiki/NPC-Player-Interaction-Design-and-Planning) by removing conflicting comments from last year about extra necessary abstraction with a npc_game_action struct, reforming the npc_game_action.h section by clarifying our intended use of the game_action struct, and making other small changes on clarification of functions that will be used in npc_game_action.h. The Wiki page now reflects a full update of current structure and future changes to be made to npc actions.

**Comment by lilyehsani** [comment]
Issue Score: ✔️++

Comments:
Great work overall! Make sure to assign new issues to the sprint they are worked on (by selecting the appropriate sprint under "Milestone").
