### ISSUE TITLE
Finish designing NPC action interface, and prep for implementation.

### ISSUE THREAD

**Issue by MaDDylan** [uchicago-cs/chiventure#872]
Revise and complete the interface npc_game_action header and c file. The interface and implementation for npc_action are complete, although the design for implementing it into the large game state needs completion.  
Assignee: Dylan, Andrew, Matias
Team: npc-2

**Comment by MaDDylan** [comment]
npc_action header and c file design are complete. The c file has most implementation done, but the three "do_npc_xyz" functions still need to be implemented.

**Comment by MaDDylan** [comment]
npc_game_action header file seems complete. We previously thought the team still needed to include new, init, and free functions as well as define a npc_game_action struct. However, after conferring with the action management team and getting a better understanding of the included definitions from game-state, it is apparent that last years team decided to use the struct, game_action, defined in item.h.

**Comment by MaDDylan** [comment]
Merged dev branch into npc/actions branch. Updated npc_game_action.h includes and function parameters. Furthermore, the design for this module is finished and the c files are ready for implementation.

**Comment by lilyehsani** [comment]
Issue Score: ✔️++

Comments:
Great work overall! You opened the issue very quickly after the sprint meeting and the summary is thorough.
