### ISSUE TITLE
Update ui README

### ISSUE THREAD

**Issue by xWngl** [uchicago-cs/chiventure#873]
The ui README was last updated before the implementation of cmake. Need to, at the very least, update the section about creating the example files, and make sure all other information is consistent with current ui modules.

**Comment by eao10000** [comment]
Updated the coordinate section in the README.md 
Commit: 5454b2417921f588d84fcec1d0e153aaeef97ba0

**Comment by eao10000** [comment]
Updated make description
Commit: 1779a7e02a8f4e9546dc8835a2cf2a40083e88f9

**Comment by eao10000** [comment]
Removed DFS module in README
Commit: ac28546e602471fbd7f2b5892ca3469503ddb99f

**Comment by eao10000** [comment]
@xWngl  and I have finished cleaning up and updating the READMME.md in the ui directory. We added additional information about the coordinates module while also removing the DFS module from the README.md as it was no longer needed. We were also able to update the how to use section making it easier and more accurate on how to run the ui directory.

**Comment by MaxineK36** [comment]
Issue Score: ✔️+

Comments:
Good work! While you had a good number of status updates, they weren't particularly informative; please make sure you explain what's happening in a little more detail so someone reading this issue could understand what happened without having to read through your code.
