### ISSUE TITLE
Memory management in game-state, action-management, and related tests

### ISSUE THREAD

**Issue by jasulcaf** [uchicago-cs/chiventure#877]
Currently a lot of tests in game-state and action-management are leaking memory. We need to determine if only the tests are leaking memory or if the functions themselves are responsible. Using valgrind on the test executables, it is possible to find uninitialized memory leakage which can lead to a debugging phase.

**Comment by LapsededPacifist** [comment]
5/1/21 - Progress (So far)
Delete_all_items seems to have issues freeing all the items in a given item_hash_t. See test add_item_to_hash_duplicate_items in /game-state/test_items.c for an example. The first item in the hash is not freed. 
Other things to note, there is no free function for the condition struct. Delete_condition_llist frees manually from a list of conditions. Not sure if intended, but seems a bit off.
Fixed an error in player.c where strncpy was being used with strlen to cause strings to not be null terminated and get uninitialized memory errors.

**Comment by jasulcaf** [comment]
Resolving Delete_all_item issue mentioned above by @LapsededPacifist. As a summary as to what was happening, the implementation of removing a duplicate item in the hash was:
- Delete from hash the "head" item duplicated
- Add the "tail" item duplicates _back_ to the hash

However, the issue was that in delete_all_items, when we re-add an item with the same item_id, it will get hashed to the same spot in the hash table. This movement was not being caught by HASH_ITER, which resulted in the duplicate items not being successfully deleted/freed.

As a brief example to illustrate this, suppose HASH_ITER would go through A, B, and C. However, in A there is an item that is duplicated. When removing item in A, one iteration of the duplicated item was removed and deleted, while the other iterations was _re-hashed_ to A. However, HASH_ITER would already have moved on to B. This results in Memory Loss.
Solution: Add a loop for when we have duplicate items in the hash to remove _all_ iterations of the item before moving to the next spot in the hash table.

**Comment by LapsededPacifist** [comment]
Several free functions are totally busted currently(Or don't exist). Player_free() crashes and burns if there are effects in play. 
Specifically, add_item_effect_to_player has a lot of problems. Currently, I have manually freed all of the items, but work will need to be put in to making those frees work. 
An example of free functions that don't exist, there is not currently a function to free conditions. The function to free a list of conditions, simply frees each individual one manually. 

It is also important to note that when creating a lot of these functions by hand, strings need to be inputted as a strndup value. Most of the tests were not doing this, which is only fine if you don't try to free the memory.
Several free functions (Such as game_free, player_free, and free_stats) aren't freeing all of their pointers. Not sure if intended or not. Might need to talk with the people implementing the specific pointers.

**Comment by jasulcaf** [comment]
Update: All tests run without memory leakage now. 
As @LapsededPacifist has mentioned, there are certain free functions that simply do not exist/don't work effectively that could lead to complications as chiventure continues developing such as: 
- Trying to free chiventure related objects in `/tests/action_management/test_item_actions.c` results in severe memory loss. This happened due to missing free functions in `/common/src/ctx.c` as there is literally a comment line saying "Add calls to component-specific freeing functions here" which gives the impression that perhaps some work was scheduled to be done but backlogged some time ago (could not find a closed issue on this however). This is something that should be addressed in the future by the associated team in charge of ctx.c, but in the mean time we manually freed things in our test.
- Another issue was that there appeared to be some complications/strangeness between stats and global stats and how they where being freed. While it is possible to manually free these things, looking into the interconnections of the how stats and global stats free are implemented (deep copies of memory vs. sharing memory with pointers) could be helpful.
- Expanding on the second issue mentioned with regards to deep copies of memory vs. sharing memory, in general there are situations where a linked list item shares the same memory as an item in hash tables. This results in situations where someone can free a hash_table item which that can indirectly free an item in a linked list.

As we currently have a Pull Request open, we will further update in case something changes or if a new issue pops up.

**Comment by MaxineK36** [comment]
Issue Score: ✔️+

Comments:
Good work overall! 
For next time, please also remember that merging a linked pull request closes an issue, so when your PR is merged you should include a final comment summarizing what was done, and why the issue is being closed. (Your current final statement leaves open the possibility for additional changes.)
