### ISSUE TITLE
Accomodate new player fields as conditions for actions

### ISSUE THREAD

**Issue by WPDolan** [uchicago-cs/chiventure#880]
Currently, as defined by `condition.c`, conditions limiting player actions may either be defined as `inventory_type` or `attribute_type`, which require the possession of an item in the inventory or the possession of some attribute (in this case, if the relevant item has the desired attribute). Currently, only items are considered to have attributes.

While these condition types sufficiently handle current games, additional fields in the player struct storing the player's statistics, skills, statuses, and more are planned to be implemented with #875. We may want these new fields to be conditions for certain actions. For example: opening a jar requires 15 strength.

We could feasibly describe these as player "attributes" for use with the current `attribute_type`, the downside being that we would need to store every skill, statistic, etc. in an attribute linked list in the player struct along with their current fields. This may be cumbersome when a player has multiple skills.

Alternatively, we could introduce new condition types for skills, statistics, etc. This might be more intuitive but it will require the creation of additional functions to handle these new types in the `game_action` and `condition` modules.

Suggestions: 

Place player skills, class, and stats  into an attribute list stored in the player struct for use with  `attribute_condition`
 
Design corresponding condition types and associated functions for new fields

**Comment by WPDolan** [comment]
After implementing the new fields for the player struct in Issue #875, @afranzese99 and I determined that the new fields in the player struct will have corresponding condition types. This would require these new condition types, and their associated functions to be implemented in a future issue. New condition types would most likely be `skill_type` (or two noncombat and combat types),  `class_type`, `level_type`, and potentially a `race_type`.

**Comment by MaxineK36** [comment]
Issue Score: ✔️+

Comments:
Good work overall! A few areas of improvement for next time:
- The title of an issue has to convey what the issue will be producing. In this case, your title makes it seem like you'll be producing code, not documentation. This also should have resulted in a wiki page.
- It seems like there was additional conversation that happened and decisions that were made between the opening and closing of this issue; this should be reflected in updates.
