### ISSUE TITLE
Add functionality that allows players to use items (consumables) during battles

### ISSUE THREAD

**Issue by Elsa-Athiley** [uchicago-cs/chiventure#881]
Currently players are only able to use 3 commands in battle,  MOVE USE move_name ON enemy_name , MOVE LIST and HELP . Players are  unable to use items in battle, specifically consumables that would increase health or attack and defense strength. I need to add functionality for USE item_name.

**Comment by Elsa-Athiley** [comment]
Added a print_items function that is called when the command HELP is used. It will print the available battle items and list name, attack, defense, and hp values.  There is currently  find_item and use_item functions that I will use to create the functionality for the USE <item_name> command. These are being tested in the battle _command_example.c file.

**Comment by Elsa-Athiley** [comment]
Added functionality for USE <item_id> had to change it to take in the id instead of name because of the way the commands are parsed. Also printed stat changes due to using the item. The only thing left is to clean up the spacing of print statements in the terminal and clean up the code so there is less repetition.

**Comment by Elsa-Athiley** [comment]
Submitted a pull request with the changes (#905 ). I was able to implement a command that allows users to use items during battle in the `battle_command_example.c` file and also updated other commands to include items. The HELP command will now also list the available items and their associated information. Another team member is now working on implementing temporary effects with the items consumed during battle.

**Comment by firatciftci** [comment]
Issue Score: ✔️+

Comments:
Great work on this! I only have one thing to comment on, which is regarding the summary:
- The summary for this issue is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/policies.html#tasks-issues for examples).
