### ISSUE TITLE
Add support for level oriented room generation

### ISSUE THREAD

**Issue by wmingyan** [uchicago-cs/chiventure#882]
The current room generation algorithm generates new rooms by randomly picking rooms. We want to develop a new generation algorithm that could pick roomspec_t's based on the player's level. For this task, we need to update the autogenerate module.

**Comment by wmingyan** [comment]
revised structures for rooms_level and difficult_level_scale and added related functions in commit 484e7d758eda1944a419d4e557dd43805901a58d

**Comment by Justin08784** [comment]
fixed compilation errors and changed rooms parameter to add_rooms_to_gen from type room_level_t* to room_level_t**–– pointers to hash tables [must be dereferenced](https://stackoverflow.com/questions/12743465/why-is-my-hash-empty-when-returning-it-from-a-function) before passing into the function.

**Comment by Justin08784** [comment]
While making tests, realized that all init functions for openworld data types actually calloc space for struct fields. This doesn't seem ideal because you might want to initialize automatic structs that dont need callocing. 

Move all calloc to struct 'new' functions?

**Comment by Justin08784** [comment]
While making tests, realized that in gen_structs.c functions, callocing for all struct-fields occurs in 'init' functions. This means that every time we call init_struct, we're initializing new blocks of memory for the pointer to point.

Why that's bad:
https://stackoverflow.com/questions/19435433/what-happens-if-i-use-malloc-twice-on-the-same-pointer-c

**Comment by Justin08784** [comment]
Added tests for all new functions except multi_room_level_generate

**Comment by Justin08784** [comment]
Addressed Maxine's comments from pull request.

**Comment by Justin08784** [comment]
9eea6fe9fe780780497c653912c76ab0d7919b40

**Comment by Justin08784** [comment]
9eea6fe9fe780780497c653912c76ab0d7919b40 #896

**Comment by Justin08784** [comment]
> Addressed @MaxineK36 's comments from pull request. [9eea6fe](https://github.com/uchicago-cs/chiventure/commit/9eea6fe9fe780780497c653912c76ab0d7919b40)

**Comment by MaxineK36** [comment]
Issue Score: ✔️+

Comments:
Great work! One area of improvement for next time: when an issue is done, you should include a final comment summarizing what was done, and why the issue is being closed.
