### ISSUE TITLE
Integrate the npc and battle modules according to the design done in issue #828

### ISSUE THREAD

**Issue by amymorrill** [uchicago-cs/chiventure#883]
In the last sprint, we made plans to integrate the npc and battle modules. Now, we want to implement those plans, in consultation with the battle team. Specifically, we will move information in the npc-enemy struct in the battle module to be contained in the npc struct, allowing the battle team to get rid of that struct. We also will discuss with the battle team any further ways that npcs and battles can be integrated.

**Comment by amymorrill** [comment]
After talking with @Elsa-Athiley and @lczielinski from the Battle team, we have decided that our plan to integrate NPCs and Battle structs will work (moving info from the npc-enemy struct into an npc-battle struct, which will be a part of the main npc struct). The next step is to actually create the npc-battle struct, modify the existing npc struct, and then modify and functions explicitly reference the fields of npc struct (like npc_new, etc.).

**Comment by amymorrill** [comment]
We have decided to carry this issue over into Sprint 3. The main reason for this is that we are temporarily closing the associated pull request (see #899 for more details). 

We also have realized that we need to edit our code to avoid breaking tests that other teams have written which include npc_new and npc_init. To address this, we will make npc_battle default to NULL in npc_new and npc_init and will then create additional functions to add an npc_battle struct to an npc. We will implement these functionalities before reopening pull request #899.

**Comment by amymorrill** [comment]
We are still waiting on two pull requests to go through (#904, #941) before editing our code and re-opening our previous pull request (#899). In the meantime, I have updated the npc design and planning wiki page (https://github.com/uchicago-cs/chiventure/wiki/NPC-Design-and-Planning#integration-of-NPC-module) to reflect our planned changes to the npc struct (and those implemented in #904) as well as more details about our plans for npc/battle integration.

**Comment by amymorrill** [comment]
I have just updated the npc/clean_structs branch with a few changes from the original plan. 

First, we decided to have a separate npc_battle module incorporating the definition for the npc_battle struct, new/init/free functions for that struct, and any other battle related functions we create in the future. Accordingly, I have create an npc_battle.h and an npc_battle.c file. 

Second, we decided to move the parameter "will fight" (a boolean describing whether the npc will engage in battle) to the npc struct instead of the npc_battle struct. We have decided to have npc_battle default to NULL when initializing npcs, and for npcs that never fight it makes sense to keep npc_battle as NULL. However, to avoid confusion, we need a parameter in the npc struct (will_fight) that shows if npc_battle should be NULL or if it shouldn't be NULL. 

The next step will be to resolve merge conflicts between our branch the dev branch (of which there will be many because other branches have merged since we created this one) and to re-open pull request #899. To deal with errors, we may need to change other teams' tests that include npc_new to give them a dummy will_fight value (probably false).

**Comment by amymorrill** [comment]
I have now updated the npc/clean_structs branch to get rid of merge conflicts with that branch and dev and to resolve issues with tests. Accordingly, I have re-opened pull request #899, which is pending review.

The next steps will be to create a function to add a battle to an npc, functions to get/set different npc_battle parameters, and maybe a function to check if an npc's will_fight matches their npc_battle status (ie if will_fight = true, then npc_battle shouldn't be NULL, but if will_fight = false, then npc_battle should be NULL). I also will need to create tests for the npc_battle new/init/free functions (and any other functions I create). However, all of these future steps should be completed in subsequent issues.

**Comment by lilyehsani** [comment]
Issue Score: ✔️++

Comments:
Great work overall! The summary, and especially updates, of this PR are very thorough.
