### ISSUE TITLE
Clean up npc code according to issue #828

### ISSUE THREAD

**Issue by amymorrill** [uchicago-cs/chiventure#884]
When reviewing existing NPC code, we found several small inconsistencies (such as repeated parameters in the NPC struct). We will fix those inconsistencies to clean up the code.

**Comment by northofsophia** [comment]
A new npc/clean-structs branch has been checked out where the code in the npc struct has been cleaned up, as well as creating a new npc_battle struct.

**Comment by amymorrill** [comment]
We are continuing this issue into Sprint 3, and we have decided to temporarily close the associated pull request (see #899 for more details). This is because our teammates also submitted a pull request (#904) editing the main npc struct, which conflicts with our edits to the npc struct. After our teammates' pull request goes through, we will revisit this issue and see if the npc code / npc struct need to be cleaned up further, or if we can close this issue based on their edits.

**Comment by amymorrill** [comment]
I have just finished cleaning up the code for the npc.c struct in the npc/clean_structs branch. The most important task related to this was deleting the duplicated class fields. While I was doing this, I also noticed that the npc_new, npc_init, and npc_free functions do not match the updated (or even the previous, non-updated) npc struct, so I also changed those to match the struct. 

The next step will be to deal with merge conflicts between the dev branch and npc/clean_structs branch and to re-open pull request #899.

**Comment by amymorrill** [comment]
I have resolved merge conflicts between the dev branch and npc/clean_structs branches and have re-opened pull request #899 which is pending review.

Notably, as I mentioned in my last comment, I thought that npc_new and npc_init did not match the npc struct because they were missing dialogue and inventory fields. However, I have since realize that an npc's inventory and dialogue are meant to initialize to NULL, and should be filled in later. Thus, I again got rid of the dialogue and inventory fields in npc_new and npc_init in this last round of edits.

**Comment by lilyehsani** [comment]
Issue Score: ✔️++

Comments:
Great work overall! The updates of this issue are very thorough.
