### ISSUE TITLE
Look through wiki, and communicate with other teams, to write up documentation explaining chiventure's updated graphic wants/needs

### ISSUE THREAD

**Issue by eao10000** [uchicago-cs/chiventure#885]
The point of this issue it to go through the wiki pages and look through the new implementations. Doing this process to see if there is any new addition that would have a need in graphics. Which would lead to discussion with the given groups.

**Comment by eao10000** [comment]
Created initial Graphics: Feature Wishlist (Spring 2021) wiki page

**Comment by eao10000** [comment]
Created the three section top priority, medium priority, low priority.

**Comment by eao10000** [comment]
Looking through the wiki pages and trying to take notes down to transfer to the wiki page.

**Comment by eao10000** [comment]
After going through every wiki page I have collected a wishlist of wants/need of graphic implementations for the future. Where in the list I set in bolded text the associated team to the given feature to make it easier when needing to talk to a given team about an implementation.

**Comment by eao10000** [comment]
Added a When was last updated header, so in the future people can look and see if the wish list needs to be changed and/or updated.

**Comment by eao10000** [comment]
After showing Maxine I am going to add example ideas under each bullet point and making it easier to see which team it is associated with.

**Comment by eao10000** [comment]
The wiki page has been completed, this includes the priority of the issues on the wish list, examples, as well as the teams that it is associated with making it easier for future issues. With this I will be closing this issue.

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Good work! Your updates are particularly frequent and concise. In the future, it would also be helpful to link the wiki page you created.
