### ISSUE TITLE
Create and document design of module & struct decomposition 

### ISSUE THREAD

**Issue by DemS2000** [uchicago-cs/chiventure#886]
The issue was created to create and design the module and structure of the sound library using SDL library. The goal is to have a design of the module and structures as well as functions for loading, playing and editing the sound file in-game, and to document this design on wiki. 

At next sprint, we envision to be able to implement/develop based on the design we have provided.

**Comment by DemS2000** [comment]
Sound struct
{
	Path_to_sound_file 
	File_type
	Duration
	Name
} 


Load_sound 
Play_sound
Manipulating sound (volume, duration, etc)

**Comment by gypark23** [comment]
4/28
After the sound team meeting, we have determined to create three different modules that are each responsible for
1. Loading sound
2. Playing sound
3. Manipulating sound

Further design will follow.

**Comment by gypark23** [comment]
4/30
After the sound meeting, we have created an initial draft of the design document and have published it to wiki.
The whole sound team will edit and develop the document.

**Comment by gypark23** [comment]
The wikipedia now has brief explanations for the necessary features of the sound module. Since the sound team published the documentation of the sound module draft, this issue will be closed. The design will be implemented in #912 and #913

The wiki will be updated as needed throughout the course.

**Comment by ecoble** [comment]
Issue Score: ✔️++

Comments:
Great job on this issue! The design wiki is super thorough and you did a great job updating this issue! It looks like multiple people may have worked on this issue but there is only one assignee, please make sure assignees are accurate.
