### ISSUE TITLE
Write a design document for chosen integration approach for open world into chiventure

### ISSUE THREAD

**Issue by ahmed-sumaiya** [uchicago-cs/chiventure#891]
Based on [wiki page](https://github.com/uchicago-cs/chiventure/wiki/Open-World:-Deciding-an-integration-approach) created last sprint in which we have detailed potential approaches to integrate open world into chiventure (dynamic, static or both), create design documentation outlining a static integration approach. We should create a wiki page at the end of this sprint.

We envision the need to carefully map module dependencies around chiventure.c–– where game startup occurs and thus represents the most likely area for change.

**Comment by Justin08784** [comment]
Met and discussed with Sumaiya today. We discussed how the gencontext struct (a paramter for our autogenerate function, multi_room_generate) can be constructed during game start-up.

During game startup, parsing is used to convert info stored in a WDL file into a game struct. We realized that the gencontext struct can be constructed in a similar fashion–– though this would require creating a specialized parsing function for it (for example, gencontext doesn't need specification of paths between rooms).

Furthermore, some data types, like int num_rooms_generated and a specifier for generation method (like enum type gen_mode), are not yet specifiable in WDL files and thus need parsing support.

We hope to read about parsing over the weekend to incorporate it into our integration approach design.

**Comment by Justin08784** [comment]
Produced a [wiki page](https://github.com/uchicago-cs/chiventure/wiki/Open-world:-Designing-approach-for-statically-integrating-openworld-into-chiventure) for integration approach design. Ideally, we would gone into more detail and sketched out modules/interfaces/functions for parsing/loading, but we were informed that chiventure game-loading is about to be revamped.

Given this, we decided to postpone our considerations involving loading/parsing implementation to a later date.

**Comment by ahmed-sumaiya** [comment]
After discussing with Maxine, we decided to close the issue with the current [wiki page](https://github.com/uchicago-cs/chiventure/wiki/Open-world:-Designing-approach-for-statically-integrating-openworld-into-chiventure) that we have produced for integration approach design. Given that the game file format is currently being updated, we decided to defer the details involving loading/parsing to a later sprint.

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Excellent work! You did a great job providing concise but substantive updates, and making the outcome of this issue clear by linking the wiki in both the summary and the closing statement.
