### ISSUE TITLE
Update npc testing frameworks after the integration between rooms-npc and npc module

### ISSUE THREAD

**Issue by torresszy** [uchicago-cs/chiventure#893]
The rooms-npc module has integrated into the npc module by adding another field into the npc struct, and relevant functions are updated as well. We need to now update the tests for npc and rooms-npc to reflect the latest changes in the source codes

**Comment by torresszy** [comment]
I have created a new test file, `test_npc_move.c` and refactor the `test_rooms_npc.c` so the tests related to `npc_mov` struct will now go to `test_npc_move.c` and tests related to `npcs_in_room` struct will stay in `test_rooms_npc.c`. I will also be writing new tests to any new functions we added from last sprint.

**Comment by torresszy** [comment]
I have also written a new test for `delete_npc_from_room` in `test_rooms_npc.c`. All the tests have passed now with the new updates, and I have mde a pull request to this issue

**Comment by lilyehsani** [comment]
Issue Score: ✔️++

Comments:
Great work overall! The updates of this issue are very clean and to the point.
