### ISSUE TITLE
Update Existing NPC Documentation

### ISSUE THREAD

**Issue by andrewg23** [uchicago-cs/chiventure#894]
Assignee: Andrew, Matias, Dylan, Peter, James 
Team: npc-2

Review and update existing NPC documentation found on the npc/documentation branch. Update src/npc/README.md and create a markdown documentation file to add to the docs directory.

**Comment by andrewg23** [comment]
I read through the /src/npc/README.md file and made minor changes to it. Everything seems up to date. I think this file would better serve its purpose in the /docs directory. I am not sure about how up to date the dialogue aspects of the file is so I will contact @jeyeong and @pkasner in regards to the dialogue documentation.

**Comment by pkasner** [comment]
With regards to the Next Steps for the Dialogue Module, the "mode" solution described in issue #864  lets us get around all the issues described in the next steps for the dialogue module. Once that is finished, all that needs to be done is the implementation of a runconvo function described in issue #868 and the implementation of a TALK action, which would be done through completion of the npc/action branch

**Comment by andrewg23** [comment]
After talking with @jeyeong and @pkasner, I have updated the the dialogue documentation in src/npc/README.md to reflect the current state of NPC dialogue and what changes are planned for it. Specifically, I included how numeric options will replace keywords, and how the CLI mode feature will help integrate dialogue with chiventure's CLI.

**Comment by andrewg23** [comment]
I moved the src/npc/README.md file to the docs directory and renamed it npc.md. I also updated the docs/README.md file to reflect this change. It is more intuitive to have the npc documentation in the docs directory as it will make it more easily accessible to anyone trying to familiarize themselves with the NPC module.

**Comment by andrewg23** [comment]
I added a list of all the files associated with the NPC module to the `/docs/npc.md` file. I also added short descriptions of each file.

In this processes I noticed that I had overlooked the lack of documentation regarding NPC movement and NPCs in rooms. I will begin working on documenting the NPC in rooms module by referencing the [NPC Movement Design Document](https://github.com/uchicago-cs/chiventure/wiki/RPG-NPC:-Independent-Feature:-NPC-Movement-Design-Document) and looking through the current code on NPCs in rooms, specifically `/include/npc/rooms-npc.h` and `/src/npc/src/rooms-npc.c`. If documenting this seems too complex, I may need to contact the npc1 team.

**Comment by andrewg23** [comment]
I updated the documentation in the `/docs/npc.md` file to include NPCs in rooms to reflect what is currently implemented.

The next step would be to have other team members look over the `/docs/npc.md` file to make sure everything is up to date with the current implementation of NPCs. If everything is good then I can create a pull request to merge the `npc/documentation` branch with the `dev` branch in order to resolve this issue.

**Comment by andrewg23** [comment]
A pull request (#927) has been made to merge the npc/documentation branch into dev. Upon aproval, the pull request will close this issue. Afterwards, the npc/documentation branch can be deleted.
