### ISSUE TITLE
Add functionality for temporary duration items

### ISSUE THREAD

**Issue by jintae412** [uchicago-cs/chiventure#895]
Currently, items used maintain their effects for the entire duration of the battle. Ideally, we would be able to support the creation of items with temporary durations (IE an item could boost a stat for X-amount of turns before the stat boost wears off).

**Comment by jintae412** [comment]
The current plan is to create a linked list in battle_structs.h that represents any current status changes (currently intended for consumable item temporary stat changes, but could also be used for stat-changing moves). This would require getters, setters, a function to initiate, and a function to free. Likely located in battle_state.c. A node in the linked list would consist of the id of the item used, as well as its stats (currently item_t only has attack, defense, and hp stats) which represent the modification made, and an integer representing how many turns the item's effects last.

Note: A linked list is being suggested to start, as there is no reason to correlate order in the data structure with when it is being removed. A given effect may last 3 more turns while an effect added later only 2, or as many as 5 turns.

A field for this struct would likely need to be added into battle_t so modifications would need to be made to start_battle() and set_battle() in battle_flow.c. 

item_t in battle_structs.h and the functions that create them/etc (unclear where) would be modified to add a field (probably a boolean) that states whether the item is supposed to have temporary effects or not.

consume_item() in battle_logic.c would be modified so that it would check if the item is temporary, and if so would create a new entry in the linked list.

battle_flow() in battle_flow.c would be modified such that at the beginning of the player's turn (or at the end of the enemy's) all effects in the status changes linked list would be incremented down by 1. If the turns field for an item's effect is 0, the effect is reversed and then the entry is removed. Functions will need to be created to facilitate this process.

**Comment by jintae412** [comment]
Implemented the linked list for stat changes and made it a double linked list for ease of implementation. Currently still requires a getter and setter before it can be considered finished and work on the rest of the issue can continue. As implementation currently stands, the head node for this double linked list will be differentiated by its item ID being -1. This issue will carry over into the next sprint for completion.

**Comment by firatciftci** [comment]
Issue Score: ✔️+

Comments:
Good work on this! I only have two things to comment on, which are regarding the summary and the issue title:
- Even though you can add labels to issues to categorize them, you should avoid titles that could plausibly apply to multiple teams
- The summary for this issue is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/policies.html#tasks-issues for examples).
