### ISSUE TITLE
Complete creation of temporary status changes struct and functions

### ISSUE THREAD

**Issue by jintae412** [uchicago-cs/chiventure#908]
A double linked list has been created to track temporary status changes (stats being raised/lowered). Now further support should be made so that status changes can be added, removed, and disappear after x amount of turns have been completed. An example would be using an item that grants +50 attack for 3 turns. The player would use it on their turn 0, and presumably that would be their entire turn. Before/after their next turn (it depends on how integration is handled) all items in the double linked list will be decremented by 1. After 3 total additional turns, the turn count (3) will now be 0, and upon reaching such the double linked list will remove the node for the +50 attack buff, and as it does so will remove the stat boost itself from the player.

Furthermore, changes need to be made to the item_t struct and its associated functions so that they can inflict/cure temporary status effects.

Edit: It has been determined that the changes to the currently existing code to integrate this struct and its functions should be another issue.

**Comment by jintae412** [comment]
Finished the creation of the new functions, those being the ones directly related to the new stats_changes double linked list. There is a function to decrement all of the turn counts of the double linked list save for the very first node, which has a turn count of -1 and is required as a header. When a turn count decrements to 0 all stat changes are undone before the node is removed from the list. There is a function for the addition of a stat change from the current implementation of the item struct, but it does not yet have support for adding a turn count because the item struct doesn't support it yet. Currently existing code needs to still be overhauled to support temporary stat changes.

**Comment by jintae412** [comment]
Updated the definitions of item used in the relevant function, and moved the add_item_node function to battle_logic.c where it seems like it fits more. Will submit a Pull Request and if that works, close this issue. Integration of these functions and the currently existing code can be a new task.

**Comment by jintae412** [comment]
Created tests and reworked code until it compiled and the tests passed. Next up is to submit the Pull Request and then close this issue, so that we can integrate this code as a new issue.

**Comment by jintae412** [comment]
The pull request has been approved. This issue is now closed. To continue working on this path, integration with current code would be required, IE making it so that the struct is created when a battle is, as well as making allowances for the code to work such as getting items to tell us if they need to add a stat change to this struct when used.

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Great job on this! The updated that you have provided give a really detailed overview of your work.
