### ISSUE TITLE
Confirm hash table functions with game state

### ISSUE THREAD

**Issue by ellynliu** [uchicago-cs/chiventure#91]
Communicate with game state to confirm the formats (input, output) of the two hash table functions that game state will provide. One function could return an array of room IDs so we can save it; the other could take an array and convert to a hash table to load back in.

Edit: they provided macros instead of two specific functions for our use. See comments below for more info.

**Comment by ellynliu** [comment]
So far game state has provided us with macros for us to iterate through their hash tables. Their example is:
` room_t *room_i;
   ITER_ALL_ROOMS(my_game, room_i) {
       printf(“%s”, room_i->short_desc);
       // Technically it should be frpintf if it should be written to a file
       // Other operations
       item_t *item_i;
       ITER_ALL_ITEMS_IN_ROOM(room_i, item_i) {
           printf(“%s”, item_i->short_desc);
           // other operations
       }
       // Other operations
   }`
Their macros take two arguments, the first being the parent-level struct, the second being the iterator. We will look into how exactly to use these macros to store info into an array.

**Comment by jarvislam1999** [comment]
In addition, there are functions such as add_room_to_game() that really help us with the loading part, which we will really need to look at.

I'm also thinking of expanding this issue to include learning about their functions which set a specific struct to a specific value, such as set_attribute_to_value() because it would be related to the integrating issue, but it may be better to pose this in the new integrating issue itself.

It may be helpful to post any useful functions from gamestate here, however.

**Comment by jarvislam1999** [comment]
After our talk on Monday, we have come to a good course of action on what will be implemented:

- We will use and have used their iterator in our save and load functions, as opposed to what we have discussed before.
- Game state agreed to ask functions to count the number of objects in a hash table, which will be under the general format COUNT_OBJECTS(object_t obj)
- We have written some structs based on what game state have promised but have not pushed to master and will likely not during this sprint. All of this code has been commented out but should not be removed as we will need them in the future. 

Per this, I believe this issue has been completed and should be closed. Please let me know your thoughts, @ellynliu

**Comment by ellynliu** [comment]
Now that we have code from game state to access the information stored in hash tables, we were able to write functions in save.c by converting the information in the hash table to an array, part of issue #93. They did not provide a new function going from an array to a hash table, but since there are functions to add to hash table, we can iterate through the array ourselves and create the hash table in load.c.

**Comment by mpcsh** [comment]
Issue Score: ✓+

Comments:
