### ISSUE TITLE
Implement Sound Data Structures

### ISSUE THREAD

**Issue by gypark23** [uchicago-cs/chiventure#913]
In the previous sprint, we have designed and documented the modules, structures and functions necessary for game sound. In this sprint, we are going to implement the design. Our goal is to provide a compilable header file that include all the features described in the document.

**Comment by gypark23** [comment]
The separate branch for the sound team is created and pushed [here](https://github.com/uchicago-cs/chiventure/tree/sound). The implementation will be pushed to the sound branch.

**Comment by gypark23** [comment]
The header file for sound structure had been pushed. Further modifications will follow.

**Comment by gypark23** [comment]
We are referencing [this website](https://gigi.nullneuron.net/gigilabs/playing-a-wav-file-using-sdl2/) for our sound module, and we have noticed that modifications are needed for sound module.

**Comment by gypark23** [comment]
After the team meeting, this issue had been moved to Sprint 4

**Comment by gypark23** [comment]
Sound structure is now moved to sound.c and sound.h so that it could be used for play/load functions

**Comment by gypark23** [comment]
Sound structure had been updated to accommodate SDL library structs necessary for sound-playing, and the wiki had been updated as well

**Comment by gypark23** [comment]
Closing Statement: 
This issue will close as the pull-request had been submitted. The initial goal of this issue, to implement sound data structure, had ben successfully done in sound.h .

**Comment by DemS2000** [comment]
(This is a late update). Wrote sound.h file for sound data structure in include/ folder. 

Wrote hashtable-related functions for testing purposes in the src/hashtable.c file. Functions include add_user and find_user but are not yet thorough tested.

**Comment by ecoble** [comment]
Issue Score: ✔️++

Comments:
Nice work creating these structs and documenting this issue!
