### ISSUE TITLE
Design a system for creating complex skill effects (such as conditional skills, or random skills)

### ISSUE THREAD

**Issue by jackcasey067** [uchicago-cs/chiventure#917]
Trying to implement prefab classes has revealed how we need a more robust system for designing player skill effects (particularly combat skills, which can be fairly complex).  Many games allow for skills that are more elaborate than "deal X damage" and "apply Y debuff".  Our goal is to extend the skill effect system to allow for more elaborate types of skills (ideally, leaving room for further extension and growth in the future).

Some example skills we might want to implement:
- Chaotic blast: Has a random chance to either freeze or burn the target (Random Skill)
- Holy strike: Deal 40 damage if the target is undead, or 20 damage otherwise (Conditional Skill)
- Poison Dart: Deal 12 damage with 50% accuracy; if you succeed, the target is also poisoned (Sequential Skill)
- Channel Magic: Gain 10 magic attack AND 10 magic defense (Combined skill)

It is not important to develop these specific skills, but rather to be able to combine skills in such a manner so that complex skills like these are possible.

**Comment by jackcasey067** [comment]
This issue will probably culminate in a wiki page rather than actual code, especially considering that I am not in the skill-trees team.  That also gives us room to dream big; implementors can put together the final result bit by bit later on.

**Comment by jackcasey067** [comment]
Maria and I just had a super productive meeting on the topic of designing this system.  We think we are gonna add two types to the internal union in skill effect, one for "Combined Skills" and one for "Sequential Skills", both of which execute a list of other skills (through pointers, of course).  Combined skills try to do every effect in their list (returning SUCCESS if any succeed), whereas Sequential skills stop (and return FAILURE) when the first one fails.  This way, developers can give their skills complex and varied behavior.

We also discussed some other types of skills, but we are holding off on rigorously defining them for now.  I will still add _ideas_ to the wiki, so that we can get a better idea of how these might look concretely. 

We are going to work on the wiki, and reconvene in a meeting on Thursday to work on the next skill types.

**Comment by jackcasey067** [comment]
Update: The wiki is basically done, but we are going to meet tomorrow and talk over some of the more complex skill types I proposed in the wiki. After this issue, we might take off a chunk of the wiki stuff and implement it (the whole thing would take many issues).

Some unrelated thoughts, from a bunch of conversations on Slack over the past few days:
- We thought about Custom Actions but we decided against using just those, for a bunch of reasons:
    - They are actions, not combat effects, so there are subtle differences at the top level.
    - They are very incomplete, and no team is assigned to them this quarter.  We would basically have to give up on effects or devote ourselves to finishing the custom actions code.
    - They are a bit overbuilt for our taste; they are capable of more, but you don't gain that much in the context of RPG skills.  Their complexity might bleed through to game devs too, which would be unfortunate if it is unnecessary.
- We are thinking about making these effects available to other components: perhaps combat associates moves with them (cool monster attacks), or items get their own effect, etc.

**Comment by jackcasey067** [comment]
Closing Statement:

We met today (along with @rohangupta2806), and we are in agreement about the current design plan.  The wiki page is finished: [Integrating complex skill (combined, random, sequential, etc.) implementation into skill trees](https://github.com/uchicago-cs/chiventure/wiki/Integrating-complex-skill-(combined,-random,-sequential,-etc.)-implementation-into-skill-trees)


Moving forward, Rohan and Maria will begin actually implementing some of the new effect types (Combined and Sequential).  I will remain in the loop, but probably will not write code soon, as I am on a different team.

As progress is done, I will integrate the new skills into the player class code, resulting in prefab classes that showcase chiventure's newest skill types.

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Great work on this! The updates that you have provided give a really detailed overview of your work.
