### ISSUE TITLE
Add NPC field to chiventure's game struct and write mode operation function for conversation mode

### ISSUE THREAD

**Issue by pkasner** [uchicago-cs/chiventure#922]
In the previous sprint, we added a "conversation" mode to chiventure. To fully integrate npc dialogue, we require a mode_run function that adheres to the mode_operation function type defined in mode.h. Said function will parse the users input, call a conversation step function, and print the corresponding output to the cli.
To implement such function, chiventure needs to store NPCs, which it currently doesn't. I will add a hash table to chiventure's game struct, as well as implement a add_npc_to_game function to store npcs.
Assignees: Peter
team:npc2

**Comment by pkasner** [comment]
I've created a npc/mode_operation branch with a basic implementation of a run_conversation_mode function. However this function needs to call the run_conversation_step function currently being implemented in the dialogue module, which has not yet been merged into chiventure.

**Comment by pkasner** [comment]
To gain access to an npc's conversation struct, there needs to be a field containing NPCs in the game struct, presumably a hash table as the NPC struct itself has a bit of the infrastructure for that built in (hash handle, id). The primary question to ask is whether we can add that field to the game struct without yet having a good way to load/initialize it into chiventure.

**Comment by pkasner** [comment]
I've added an npc_hash_t field called all_npcs to the game struct. I've also written a add_npc_to_game() function to add already created npcs to that hash table and a delete_all_npcs() function that removes and frees all npcs in the hash table.

**Comment by pkasner** [comment]
The mode operation function seems to be working based on testing through the dialogue example in #984. It's possible that the player could get stuck in conversation mode if the entire conversation is a leaf (in which case their is no need to switch to dialogue mode), but that seems like something that would be better checked by a "talk" action.

**Comment by pkasner** [comment]
I've determined that it makes more sense for a "talk" action to handle the case where a conversation is just a leaf, and have changed the example in #984  to reflect that specification. I've linked a pull request to get this branch merged into dev.

**Comment by lilyehsani** [comment]
Issue Score: ✔️++

Comments:
Great work overall! The summary and updates of this issue are very thorough.
