### ISSUE TITLE
Implement statistic modifying effects in effect.h and effect.c

### ISSUE THREAD

**Issue by rohangupta2806** [uchicago-cs/chiventure#923]
The v1 implementation of effects resulted in the creation of 3 different effect types- one of them being statistic modifying effects.  We need to finish the implementation of this type of effect.  The minimum requirement is to finish the functions define_stat_mod_effect, make_stat_mod_effect, and execute_stat_mod_effect.

**Comment by rohangupta2806** [comment]
Reassigning myself to work first on creating a wiki page for the current implementation of effects as we do not have any concrete documentation on that yet.  Once the previous pull request is completed, I will continue work on the implementation of statistic modifying effects.

**Comment by rohangupta2806** [comment]
Pull request has been merged, restarting work on this issue

**Comment by rohangupta2806** [comment]
Code for this has been implemented in skilltrees/effect_v2.  The code in that branch has some conflicts with rpg-battles but this is being resolved in another issue.

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Good work!
