### ISSUE TITLE
Implement autogeneration for rooms within a radius for openworld module

### ISSUE THREAD

**Issue by Justin08784** [uchicago-cs/chiventure#925]
Currently, our autogeneration functions (room_generate and multi_room_generate) are able to load only rooms that are directly adjacent (one path away from) the current room. It would offer more flexibility to game authors if they could specify all rooms that are within an arbitrary radius/number of paths (or as time and memory allows) from the room to be generated. This is similar to how we can adjust render distance in minecraft (essentially 'radius') to determine how many chunks we load.

We anticipate the use of a queue to keep track of visited rooms as the implementation will likely involve a breadth-first search, and we would have to enable room_generation around rooms beside the current_room.

**Comment by wmingyan** [comment]
We three had a meeting, discussed the effects we want to achieve with this implementation, and tentatively decided to use recursive algorithm without queue for implementing this functionality.

**Comment by Justin08784** [comment]
Added tests for recursive_generate for cases when radius is 0 (do nothing), 1, and 3.

**Comment by Justin08784** [comment]
Recursive_generate tests were crashing. Bug was discovered at ~random_item_lookup()` in autogenerate.c. It was incorrectly passing in `tmp->item_id` not `current->item_id`.

**Comment by Justin08784** [comment]
Summarizing last two commits:

- Added `char **directions` and `int num_dirs` parameters to recursive_generate so that users can specify exactly which paths are filled with rooms at each level of recursion. 

Note: each directions in the `directions` array can only be part of the default six: NORTH, EAST, UP, SOUTH WEST, DOWN. Since the directions parameter is not guaranteed to be ordered like so, recursive_generate internally constructs an `all_directions` array and uses strcmp to find the correct `directions` index `all_directions` mapping. This eats up a lot of stack memory.

It might be worth considering defining a new struct to map each direction to its reverse and structuring the directions parameter as an array of these structs. This would also enable support for any custom directions.

- Added `char *dir_to_parent` parameter to recursive_generate which removes a lot of redundant computations. Previously, recursive_generate would backtrack and make recursive calls on already generated rooms. Benchmarking using criterion tests reveals a 36% decrease in time, or 50% faster computation. Performance gains were not as significant as expected.

**Comment by Justin08784** [comment]
Added test for dir_to_parent parameter. Checks that recursive_generate–– when given dir_to_parent "SOUTH"––generates no rooms in the "SOUTH" direction of the original room.

**Comment by Justin08784** [comment]
The pull request for 

Currently, our autogeneration functions (room_generate and multi_room_generate) are able to load only rooms that are directly adjacent (one path away from) the current room. It would offer more flexibility to game authors if they could specify all rooms that are within an arbitrary radius/number of paths (or as time and memory allows) from the room to be generated. This is similar to how we can adjust render distance in minecraft (essentially 'radius') to determine how many chunks we load.

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Excellent work! In your closing statement, it may also be helpful to note why multiple PRs were opened/closed, as that history shows up in the issue.
