### ISSUE TITLE
Meet with the NPC teams and create a design document for NPC generation in openworld

### ISSUE THREAD

**Issue by ahmed-sumaiya** [uchicago-cs/chiventure#926]
Currently the openworld module does not take non-player characters (NPCs) into account when autogenerating rooms. Since there is a plan to fully implement the openworld module into chiventure, it makes sense to incorporate the other modules of the game into openworld as well.

In this sprint, we plan to write a design document detailing how to implement NPC generation in the openworld module. For this, we find it necessary to consult the NPC teams to better understand the details behind how the NPC module is currently incorporated into chiventure so that we can implement it into openworld as well.

**Comment by Justin08784** [comment]
Met with Sumaiya on zoom today.

- Autogeneration could be used to spawn NPCs throughout–– analagous to mob generation in minecraft–– giving more incentive to design a dynamic generation integration approach for openworld
- NPCs can be categorized, similarly to rooms, into different difficulty levels and specifics NPC enemies can be spawned based on player level–– offers a way to extend level-oriented generation
- NPCs are not currently supported in the game struct, so we need more info on how this year's NPC team hopes to integrate/organize their module in the game; resolved to join NPC team chat/schedule a meeting

**Comment by ahmed-sumaiya** [comment]
[Wiki page](https://github.com/uchicago-cs/chiventure/wiki/Design-Document-for-NPC-Generation-in-Openworld) has been mostly completed. After further research, we found:
- The NPC module already provides support for room-to-room movement in openworld with an "indefinite" move type struct for the NPCs. This allows us to add rooms dynamically instead of having them predefined for the NPCs, and thus makes integrating NPC movement into openworld a lot easier.
- However, there appears to be an issue with room-to-room movement in cases where two rooms do not have the same room_tag, so that needs to be addressed before NPC movement can be implemented in openworld.
- The NPC team is also working on integrating with the battle module to make it possible for the player to battle NPCs. They are also updating their npc-action module and their dialogue module to allow the player to speak to the NPCs and trade with them.

We will meet up with the NPC teams to discuss their plans for integrating into chiventure once they respond to our message on slack.

**Comment by ahmed-sumaiya** [comment]
After further research into the NPC module, we found it was not necessary to meet with the NPC teams over zoom because the current source document and code for the NPC module was quite self-explanatory. We have updated the [wiki page](https://github.com/uchicago-cs/chiventure/wiki/NPC-~-Design-Document-for-NPC-Generation-in-Openworld) to reflect this and closed the issue because the design document wiki page for the NPC generation in openworld has officially been completed.

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Excellent work! Your post-meeting updates are particularly well-written.
