### ISSUE TITLE
Integrating map.c into chiventure

### ISSUE THREAD

**Issue by xWngl** [uchicago-cs/chiventure#928]
ui.c current makes use of the old graphics library ncurses. Update the start_ui loop in ui.c to include the updated functions from map.c. This will integrate the new graphics library, raylib, into chiventure.

**Comment by xWngl** [comment]
This issue is being closed because we have decided to make a new gui.c that will integrate map.c rather than update ui.c. As this issue is encapsulated by the issue linked below, we have decided to close it.

https://github.com/uchicago-cs/chiventure/issues/973

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Good work! This is a good example of a clearly written issue that resulted in neither code nor documentation; your summary of what happened is easy to understand, and linking the follow-up issue makes it easy to follow along and understand what happened.
