### ISSUE TITLE
(small issue) Add free_condition function to condition.c

### ISSUE THREAD

**Issue by jasulcaf** [uchicago-cs/chiventure#932]
There currently is no function to free conditions as mentioned here: https://github.com/uchicago-cs/chiventure/issues/877#issuecomment-831014707. As such, this Issue is being created to develop a solution to properly free resources associated with a condition

**Comment by jasulcaf** [comment]
Seeing how the implementation of conditions are at the moment, when freeing a condition I have discovered that I will _not_ be freeing all associated fields in the struct. To make this clear, at the moment there are two types of conditions:

1. Attribute Conditions:  contain fields that point to an associated item and an attribute. 
2. Inventory Condition: contains field that point to an associated player and item.

It is not hard for me to imagine that perhaps we will want to get rid of a condition _but not_ the associated item and attribute. This also seems to be what the prior implementation of `delete_condition_llist` wanted to accomplish since it did not free those fields mentioned above. Instead we would just free the condition and the condition wrapper pointers (the `condition_value_t` and `condition_t` respectively in include/game-state/condition.h)

**Comment by jasulcaf** [comment]
In conclusion:
This Issue set out to simply abstract the method of freeing a condition so there wouldn't be pieces of the same code scattered in different functions. The specific name of the function is called `free_condition` and this function will only delete the resources that made the condition, _not_ all fields contained in a condition (if a condition is bound to a player for example, then calling `free_condition` will not free the player, just the condition).

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Great work! Good job linking to the related issue; that makes it particularly easy for readers to follow the flow of why this issue was created.
