### ISSUE TITLE
Add functionality for creating deep copies of structs for Effects and Stats

### ISSUE THREAD

**Issue by jasulcaf** [uchicago-cs/chiventure#933]
When working on #877 in the last Sprint, Stephen and I discovered that there are situations where the same memory is being shared by hash tables _and_ some lists with different pointers. What this implies is that when we free the memory associated with one, then the other is indirectly being affected as well. As such, this Issue sets out to create functionality that provides Deep Copies of Effects and Stats so that more flexibility with freeing memory can be done as well as give users the option to copy data without having any unknown dependencies.

**Comment by jasulcaf** [comment]
Something odd that I have noticed when working on implementing a copy_stat function was the fact that a stat points to a `global_stat_t.` This seems odd to me as none of the functions in the stat.c module seem to utilize this field. I am not sure if other modules/other teams utilize this so I have gone ahead and just decided to put two types of copy functions:

1.  Create a deep copy of the actual stat but just make it point to the same global_stat_t from original stat
2. Create a deep copy of both the actual stat as well as the global_stat_t that is in the stat->global field

Finding out some more specifics on what purpose the `global_stat_t` in the `stat_t` struct is used for, would be pretty helpful since I am not sure if it is necessary to have both types of copy functions

**Comment by jasulcaf** [comment]
As I was working on global effects, I realized that there was no `free_global_effect` function. There is included in `delete_single _global_effect `what `free_global_effect` would do, so I have taken the liberty to abstract this code. This abstracted version will be much more beneficial to me in testing my functions (and also for anyone else that is wanting to free a global effect that is not strictly in a hash)

**Comment by jasulcaf** [comment]
> As I was working on global effects, I realized that there was no `free_global_effect` function. There is already included in `delete_single _global_effect `what `free_global_effect` would do, so I have taken the liberty to abstract this code. This abstracted version will be much more beneficial to me in testing my functions (and also for anyone else that is wanting to free a global effect that is not strictly in a hash)

As mentioned above, I found a similar thing happening with there being a lack of a `free_stat_effect` function. I have taken the liberty to abstract this code to once again test my functions more easily as well as provide a way for anyone to free a stat_effect that is not strictly in a hash.

**Comment by jasulcaf** [comment]
> Something odd that I have noticed when working on implementing a copy_stat function was the fact that a stat points to a `global_stat_t.` This seems odd to me as none of the functions in the stat.c module seem to utilize this field. I am not sure if other modules/other teams utilize this so I have gone ahead and just decided to put two types of copy functions:
> 
> 1. Create a deep copy of the actual stat but just make it point to the same global_stat_t from original stat
> 2. Create a deep copy of both the actual stat as well as the global_stat_t that is in the stat->global field
> 
> Finding out some more specifics on what purpose the `global_stat_t` in the `stat_t` struct is used for, would be pretty helpful since I am not sure if it is necessary to have both types of copy functions

I have decided to go against implementing these two types of copy functions by getting rid of the second option mentioned in the above comment. This was done for the following reasons:
- It creates a situation where the User would have to know a lot of external information about the stat and effect struct, mainly that there exists a global field in the struct
- It doesn't make sense (with the current implementation), to have a stat with the name "health" not point to the same global stat "health". This was very helpfully pointed out to me by in my Slack Team as every stat with one name  share a common global stat 
- If in the future there is some need to implement this functionality it should be extremely straight forward as it really is just a wrapper for deep copying a global stat and deep copying a stat structure (both of which are functions I am implementing)

**Comment by jasulcaf** [comment]
As a summary:

This Issue was opened up to find a solution (through the implementation of deep memory copy functionality) to weird dependencies occurring due to the same stat and effect struct memory being shared by various pointers. These dependencies where uncovered in prior Issue #877

This Issue can now be closed as the primary goal is accomplished (with the functions accomplish this being: `copy_global_stat` and `copy_stat` for the stat structs ; `copy_global_effect` and `copy_effect` for the effect structs ) as well as the accomplishment of a secondary task that involved abstracting free functions for effect structs (`free_global_effect` and `free_stat_effect`). For a brief description of all these functions and how they got approved in Pull Request, go [here](https://github.com/uchicago-cs/chiventure/pull/1003#issuecomment-841952548)

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Awesome job! Your updates are incredibly detailed while remaining precise and concise, and your links to related issues make it incredibly easy to follow what happened.
