### ISSUE TITLE
Design and implement attribute modifying skill effects into the effect module

### ISSUE THREAD

**Issue by mariakravtsova** [uchicago-cs/chiventure#934]
Implementation for different effects that are currently supported by chiventure (damage, statistic modification and attribute modification) is in progress of development, and each effect implementation has to be designed separately.

Attribute modifying skills will most likely require communicating with game state, action management and player class teams.

**Comment by mariakravtsova** [comment]
Basic implementation of define and make functions for attribute effects were added. As we figure out more specific details, the execution functions will be modified and integrated into our implementation of effect execution for skills. 
For now, I will close this issue.

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Great work! The only thing I can comment on is that, make sure to assign new issues to the sprint they are worked on (by selecting the appropriate sprint under "Milestone").
