### ISSUE TITLE
Update battle code structs that have the same name as structs in the game-state code so they have different names.

### ISSUE THREAD

**Issue by Elsa-Athiley** [uchicago-cs/chiventure#935]
Currently the we have three structs item_t , player_t, and game_t that are named the same as structs in game-state code. This is causing duplicate declaration errors for the skilltrees team when they make a pull request. The immediate solution is to change the name of our battle structs so the skilltree team can continue to work. Later on we will talk to the game-state team to see if we could use their structs instead of our own.

**Comment by Elsa-Athiley** [comment]
Finished renaming item_t struct to battle_item_t, and changing all instances of the name to match the new one, including in functions and comments. Currently have a PR #941 out with these updates. I will wait for the two PRs that are out the other being #905 to be merged before continuing. This PR has code that uses the old naming conventions so it would be simpler to merge that first and then continue updating the remaining 2 duplicate structs.

**Comment by Elsa-Athiley** [comment]
PR #941 has been merged so the item_t struct has been renamed to battle_item_t wherever it appeared. I will now work on renaming the final 2 duplicated structs.

**Comment by Elsa-Athiley** [comment]
finished renaming player_t to battle_player_t and waiting for PR #967 to be merged. There is one more struct left to be renamed

**Comment by Elsa-Athiley** [comment]
Finished changing the names of all the necessary sturcts, now I need to address some merge conflicts and errors that were caused by other branches being merged into dev

**Comment by Elsa-Athiley** [comment]
Fixed all issues in PR #969 and PR #967.

**Comment by Elsa-Athiley** [comment]
Closing Statement: All PR's have been merged and the renaming of item_t, player_t, and game_t is finished. This renaming should resolve any duplicate naming errors other teams using both battle code and gamestate code were facing. The next big step would be to reach out to the gamestate team and see if we could use their strructs instead of our own and integrate that way. This would solve and duplication that could happen in the future

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Great work on this! The updates that you have provided give a really detailed overview of your work.
