### ISSUE TITLE
Load: update transfer functions (ignore hash tables)

### ISSUE THREAD

**Issue by ellynliu** [uchicago-cs/chiventure#94]
In load.c, write/update functions to take a serialized file (that was created in issues #92 and #93)  and convert to game state structs. Ignore anything with hash tables, as this will be its own issue.

Edit: we were originally planning on dumping the entire game state contents and loading them fully by malloc-ing a new game_t struct. Now, we are planning on taking an existing game_t struct and writing over it with serialized data from save.

**Comment by ellynliu** [comment]
I updated and wrote new load functions in the same style as we used in sprint 2. But, we will likely go back and change/write new functions that will write into a game struct instead of mallocing a new game struct. This way, we eventually will not have to save the entire game state, only the mutable parts of the game. But as of now, the functions will save and load up a new game state.

**Comment by ellynliu** [comment]
As of now, we have decided to take a semi-incremental approach instead of dumping the entire game state. Functions in load.c are being edited to write directly into a game struct. We will be ignoring conditions entirely, as they should be present from the WDL.

**Comment by ellynliu** [comment]
Closing message: we decided not to load conditions, attributes, or attribute values since they will not change in between saves. As stated above, we will be loading into a game state that has already been populated by the WDL. Functions to load from a serialized file have been merged into checkpointing/dev

**Comment by mpcsh** [comment]
Issue Score: ✓+

Comments:
Great work!
