### ISSUE TITLE
Error when freeing effects_global_t and stat_effect_t causes double free

### ISSUE THREAD

**Issue by LapsededPacifist** [uchicago-cs/chiventure#942]
Currently only seen in add_item_effect_to_player, but the player free function is crashing in the case where there are effects added to the player and an item the player is carrying. This seems to be caused by errors inside of item_free. However, I am not sure of the exact root of the problem. The temporary fix in place is setting the item->stat_effects field to NULL and manually freeing all of the components. 
I believe that the error stems from effects being shared between items and players (Or at least the global effect being shared between two different stat_effect_t structs). More investigation will need to be done and more tests written as this seems to be the only test for testing the interaction between effects and player.

**Comment by LapsededPacifist** [comment]
Quick update with the exact error:
Happens when player free is called with no other calls and comes  from delete_single_stat_effect. 
The specific error is a segfault from not being able to access memory at 0x0 in the delete_single_stat_effect function call.
The input pointers for effect and hash for that function seem to be fine, but are the same. I am not sure how the HASH_DEL functions interacts with that when effect is the only item in the hash. Might be the source of the problem, but needs a bit more poking around to be certain.

**Comment by LapsededPacifist** [comment]
Valgrind is not proving to be helpful in finding the underlying problem. The effects hash on the item is vanishing into HASH_DEL and having an invalid read. The next step in progression is to use gdb to access the hash struct as it goes into HASH_DEL and then follow it through the macro.
As far as I can tell, there should only be a single effect in the effects hash, but I am not entirely sure how this effect got there. The pointer is initially set to NULL, but it is 0x4e3fa50 by the time of the HASH_DEL call.

**Comment by LapsededPacifist** [comment]
It turns out none of those were actually the source of the bug.
The delete_single_stat_effect function was apparently fine this entire time. The error was in new_item->stat_effects. This was supposed to be a effects_global_hash_t, however it was being incorrectly set. 
`new_item->stat_effects = e2;` was previously running for `stat_effect_t *e2 = stat_effect_new(g1);`
This did not result in an error because the hashes don't have a real function declaration. 
`typedef struct effects effects_hash_t;` is the entire declaration, so I think it is just acting effectively as a void pointer. This allows it to be used in the macros with whatever strangeness they are doing with HH, so I am not sure it can be fixed despite it not being very ideal.
The lack of a real declaration allowed it to point to a stat_effect_t instead of an effects_hash_t. This was causing HASH_DEL to break because it was assuming the input was in the form of a hash, when it wasn't. 
The fix was to replace the initialization line with `add_stat_effect(&(new_item->stat_effects), e2);` to properly add the stat_effect to the hash in item. 

No code ended up being modified. I don't think that more tests need to be written because as far as I can tell, the interaction between player and effects that I thought was breaking doesn't exist. So long as items, classes, and players all have unique stats there will be no conflicts freeing. 

Notes: 
The global stat still needs to be freed manually as it is shared between the (non-global) stats and can't be freed by them and are kept track of in game, which isn't part of these tests.
Class_free() does not currently free class->stats or class->effects. I am not sure if this is intended, but I do not believe it is.

A bit of an unrelated note, but GDB does not play nice with the tests running child processes. Telling GDB to track the child processes resulted in totally unrelated segfaults, so GDB was not used in the debugging process.

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Great work! Your updates were particularly detailed and helpful.
