### ISSUE TITLE
Understand and document how other teams will interact with the player module

### ISSUE THREAD

**Issue by afranzese99** [uchicago-cs/chiventure#944]
Before implementing/editing more components of the player module it would be useful to reach out to teams who will interact with the player module to get an understanding of how they will use the module. This will allow for greater cohesion down the line if we are able to make the player module fit the needs and desires of these other teams. It will be useful to document the types of interactions for current player implementations and for future reference.

Teams to reach out to: rpg-playerclass, rpg-skilltrees, possibly rpg-battles, and rpg-quests.

**Comment by afranzese99** [comment]
After meeting with the rpg-quests team they mentioned wanting one or two lists in the player struct (more likely two) to represent "completed quests" and "active quests". I discussed the possibility of using a hash instead (the quest struct in quests_structs.h in the dev branch is built to be a hash table) so I will follow up to confirm the best implementation (and since the quest struct has a status option to represent whether the quest has been completed or not it'd replace the need for two separate data structures for completed and active quests).

We also discussed how dependent quests were to completing the game. Will certain quests needed to be finished in order to win or advance further in the game? Currently it is unclear how important completing quests are for finishing the game (it seems like they don't need to be finished to complete the game, but that could be an interesting feature to add if it's not currently being considered). Further discussion on quest conditionals for the player is needed.

NPCs are one source for a player to receive a quest, so a meeting with the npc-dialogue team will likely be needed for proper integration of quests into the player module.

**Comment by afranzese99** [comment]
After further discussion with the rpg-quests team we will use a `quest_hash_t` field in the player struct, which would contain all of the necessary quest information (list of `achievements`, soon to be a tree, that make up a quest, `reward` for the quest, and `status` of the quest, i.e. whether it's been completed or not).

Also @WPDolan and I are trying to figure out if there are built-in functions to effectively make deep copies of a struct and it's fields (we will inquire at our weekly meeting tomorrow, since it may be a bit difficult to convey our needs over slack). If there aren't built-in functions for deep copying a hash table we may need to ask the rpg-quests team and rpg-playerclass team to implement copy functions for their respective quests and class structs (while we implement copy functions for stats and effects).

@WPDolan and I have created a new [Wiki Page](https://github.com/uchicago-cs/chiventure/wiki/Player-Interface-Implementation-Plan) detailing the `rpg-playerclass,` `rpg-quests`, and `rpg-skilltrees` wishlist for the player interface and the necessary corresponding functions to achieve these teams' desires. We also list the necessary functions for `stats` and `effects` for proper implementation of the player interface (no other teams were consulted for these two fields given the Action-Management team has taken on responsibility of the Game-State module, since there is no designated game-state team this year).

**Comment by WPDolan** [comment]
After additional discussion with the `rpg-skilltrees` team, the wiki page has been updated to confirm that our predicted functions for interacting with the player's `player_combat_skills` and `player_noncombat_skills` fields should still be implemented. 

The skilltrees team mentioned that they also intend to use our planned interface to interact with the `player_stats` field to implement functionality for changing player statistics when skills are used.

**Comment by WPDolan** [comment]
After discussion with the `rpg-battles` team, we will add an additional `player_moves` field to the playerstruct to store any moves that they player may make while in a battle. Currently, battle functionality uses the `combatant_t` struct to handle both players and enemies in battle, so the only functionality that we would need to add would be functions to set/retrieve the `player_moves` field. The wiki has been updated to reflect the planned additions.

The location of the wiki page has changed, and can now be found [here](https://github.com/uchicago-cs/chiventure/wiki/Player:-Interface-Implementation-Plan)

**Comment by WPDolan** [comment]
After further discussion, @afranzese99 and I have determined that the wiki page documents all of the functions that we intend to add to player module's interface. The interface will be implemented in Issue #952.

The link to the wiki pages has moved again, and all of the comments referencing it have been edited with the updated link.

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Excellent work! Your updates are extremely detailed and helpful for making it easy to follow the progress of this issue, and are a great example of how to provide useful updates after meetings.
