### ISSUE TITLE
List items in a room

### ISSUE THREAD

**Issue by Beza20** [uchicago-cs/chiventure#945]
Assignees: Sam and Beza
team:cli

**Comment by Beza20** [comment]
This issue largely follows doing what has already been done to list items in the inventory. So far, I have added a function "get_items_in_room" that utilized the hashtable defined in items module as "ITER_ALL_ITEMS_IN_ROOM." And returns a list of the items. But there needs more change in the background such as to what command this function is to be called. We need to further look into a a struct called "table" which I believe is a table for all of the commands to be used in chiventure.

**Comment by Beza20** [comment]
In addition to implementing the "get_items_in_room" operation in the operations module, we just needed to add the exact command that is to be used to use this operation. After doing so a player can go into a room and put in the command "items" and have a list of the items in the room listed out with a message "there are the items in the room" at the end of the list. A pretty fun issue to work with and can be a template for many cli functions that can be implemented.

**Comment by ecoble** [comment]
Issue Score: ✔️+

Comments:
Great work adding this feature! The summary portion of issues should have a description of the task, not just the assignees. Additionally, be sure issues have the proper milestone associated with them.
