### ISSUE TITLE
Integrate quests into chiventure according to design document https://github.com/uchicago-cs/chiventure/wiki/Quest-API-Design-Document

### ISSUE THREAD

**Issue by dillonoloughlin** [uchicago-cs/chiventure#946]
We hope to confirm our current planned implementation of quests into Chiventure with other teams based on our Design document: https://github.com/uchicago-cs/chiventure/wiki/Quest-API-Design-Document

We hope to:
    -Add killing an npc and finding a specific room as 
     missions to quests
    -Convert current mission struct into a union of passive 
   and active mission structs
              -In doing this we want to create passive and active 
              mission structs
    -Store quests as a linked list the player struct
    -Add skill requirements to the quest struct
    -Change the reward from an item to a struct to allow for 
    different types of rewards
    -Integrate quests into NPC dialogues so NPC could add quests to a player struct's linked list of current quests
    

Assignees: Devon, Dillon
team: quests

**Comment by dillonoloughlin** [comment]
Spoke with the action-management team and they are going to move forward with integrating quests into a player struct hopefully within this sprint. We considered either adding the quests as a hash or as a linked list, but the most likely implementation will be two linked lists of quests. One linked list for currently active quests and another linked list for completed quests.

**Comment by dillonoloughlin** [comment]
Also spoke with the NPC team about adding quest implementation to the dialogue of NPCs. We decided that we want to try to create a polymorphic action function inside of dialogues that takes in a single hash id string as a parameter. This function could be used to implement action functions like start quest, start battle, or give item. We plan to use this function to allow npcs to add quests to the player struct's quest hash table.

**Comment by ddelgado60** [comment]
Added a new branch called add-new-quest-structs and implemented most of what was detailed in the design document https://github.com/uchicago-cs/chiventure/wiki/Quest-API-Design-Document. As detailed above by Dillon, ideally the quest struct gets incorporated into the player struct, and we can move ahead with designing a scenario within our examples directory. During this week of sprint 3, we hope to update quests_state.c file to work with the new structs and updated older structs, and design a few new functions for use.

**Comment by ddelgado60** [comment]
This issue will rollover into Sprint 4 for the first few days as we are waiting on a pull request that this implementation will rely on.

**Comment by lilyehsani** [comment]
Issue Score: ✔️+

Comments:
Great work overall! I have one comment:
- When an issue is done, you should include a final comment summarizing what was done, and why the issue is being closed.
