### ISSUE TITLE
Implement Play Sound Function

### ISSUE THREAD

**Issue by gypark23** [uchicago-cs/chiventure#947]
The goal is to implement functions in the sound module that could directly play the sound necessary for game playing

**Comment by gypark23** [comment]
The initial commit for play sound function had been pushed.

**Comment by gypark23** [comment]
After the team meeting, this issue had been moved for Sprint 4

**Comment by gypark23** [comment]
@Imagineham had success in playing wav files with SDL library, and the play function is currently being designed accordingly to it.

**Comment by gypark23** [comment]
Due to lack of time, we were unable to implement compilable play functions as it contains many compiler errors. I have left my work in comment block, so next team could review my code and improve them, while maintaining the current code compilable for pull request.

**Comment by gypark23** [comment]
To separate working code and developing code, two separate branches of sound were made, sound/dev and sound/inprogress. sound/dev contains a skeleton function for play, and sound/dev has implementation that needs to be improved.

**Comment by gypark23** [comment]
Closing statement:

This issue is closed since a pull-request with play implementation had ben submitted. The initial goal was to implement play sound functions. Currently, there are only skeleton functions for play implementation in sound/dev branch and incomplete implementation in sound/inprogress branch. The future sound could build up on this issue and finish the implementation of play sound function.

**Comment by ecoble** [comment]
Issue Score: ✔️++

Comments:
Great work getting the module set up! I know this was tough under the time constraint and the original goal of this issue had to be modified, nice work keeping this issue up to date with documentation of that.
