### ISSUE TITLE
Implement npc-game-actions according to design

### ISSUE THREAD

**Issue by matiasp-10** [uchicago-cs/chiventure#948]
Summary: We will be working on implementation of the npc_game_action.c functions in the npc/actions branch as outlined in the NPC Player Interaction Design and Planning Wiki Page: https://github.com/uchicago-cs/chiventure/wiki/NPC-Player-Interaction-Design-and-Planning. This will involve implementation of functions that, for example, search for/conduct NPC actions, add/check/delete NPC action conditions, and add/set/delete the effects of NPC actions.
Assignees: Dylan, Matias, Andrew
team:npc2

**Comment by matiasp-10** [comment]
Ran into problems with the npc struct over the past few days. Many of the commands in npc_game_action take an npc struct as an input and an npc_action_t struct as an output, but there does not seem to be any sort of link between npc actions and the npc struct. The current code for these functions is being written with this complication in mind and will be adjusted once a final conclusion is reached on the basis of whether or not, and if so, how the npc struct must be adjusted to allow for these functions.

**Comment by matiasp-10** [comment]
After full team discussion, we decided that it will most likely be necessary to add a list of game actions (game_action_hash_t) to the NPC struct in order to perform all of the functions in npc_game_action. This will be confirmed for next sprint in an upcoming meeting with our senior developer. This is being modeled after the implementation of item actions in game-state, which allows an item to have a list of actions as a field. This is also helpful for future considerations, as after these npc_game_action functions are implemented, we are considering how we could possibly make more general functions for anything that could perform an action, whether it be an item or npc. Such a change would likely require a conversation with the x/action-management team.

**Comment by andrewg23** [comment]
I contacted the action management team to schedule a meeting to discuss refactoring item actions code into more general actions that can be used by NPCs.

**Comment by andrewg23** [comment]
We talked to the action management team about our idea to abstract the action code to include items and NPCs. They aren’t working on anything related to the actions so we are good to go ahead and work on abstracting actions. We will have to make a plan for how exactly this will be done.

We also discussed the idea of later implementing stats into NPCs similar to what’s being done with the player. This way, actions would modify these stats rather than individual fields in the NPC struct. This would have to be done after we do the abstraction and may require a discussion with the other NPC team.

**Comment by matiasp-10** [comment]
The work in this issue has led towards a new path of working on abstracting functions that deal with actions to work with both items and NPCs, this issue will be closed. A new issue (#990), will be opened to track and address the issue of this abstraction working at the intersection of NPCs and action-management. That issue will resolve this issue when completed.

**Comment by lilyehsani** [comment]
Issue Score: ✔️++

Comments:
Great work overall! Make sure to assign new issues to the sprint they are worked on (by selecting the appropriate sprint under "Milestone").
