### ISSUE TITLE
Integrate split_screen into chiventure with corresponding graphics

### ISSUE THREAD

**Issue by perenewang** [uchicago-cs/chiventure#950]
Chiventure currently only displays the chiventure banner for the split screen. We will implement the draw_room function in ../include/ui/draw_images.h so that it will load room images based on the room the player is in for the split screen graphic. Integrate it into chiventure by updating ui.c to call the function.

**Comment by perenewang** [comment]
This issue is being closed because our team graphics came up with a different approach on how to integrate split screen graphics with chiventure, which includes creating a new GUI.c file and functionality. These are the new issues that are taking the place of this issue:

https://github.com/uchicago-cs/chiventure/issues/973
https://github.com/uchicago-cs/chiventure/issues/975
https://github.com/uchicago-cs/chiventure/issues/980

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Great work! This is an excellent example of a closing statement where the issue needed to be closed even though no changes were made. It might also be helpful to put the titles of the new issues along with their links.
