### ISSUE TITLE
Write unit tests for start_conversation() and run_conversation_step(); rewrite tests for the dialogue module

### ISSUE THREAD

**Issue by jeyeong** [uchicago-cs/chiventure#951]
Following the changes to the dialogue module, plus the implementation of the run_conversation() function, new tests have to be added/updated to test the functionality of these functions.

**Comment by jeyeong** [comment]
Although some tests were written last sprint (Sprint 2) to facilitate the building of Chiventure, those tests were not very well written. Following last week's lessons on unit tests, I want to try to rewrite the tests we have.

**Comment by jeyeong** [comment]
Rewrote the tests for the struct functions (i.e. new, init, free functions). I used the style of test-writing that we went through in the homework.

**Comment by jeyeong** [comment]
Rewrote tests for dialogue building functions (create_new_convo, add_node, add_edge). Similar to the comment above, I used the style of test-writing we used in the homework, in order to make the tests cleaner and more readable.

**Comment by jeyeong** [comment]
Wrote tests for the start_conversation() and run_conversation_step() functions. They tested for the following.

start_conversation():
- 1 node, 0 edges (ends)
- 2 nodes, 1 edge (does not end)
- 3 nodes, 2 edges (does not end)

run_conversation_step():
- 2 nodes, 1 edge (ends)
- 3 nodes, 2 edges (ends)
- 4 nodes, 3 edges (does not end)

**Comment by jeyeong** [comment]
I also wrote and committed, to the npc/dialogue branch, a new file called dialogue_example_2020.c. This was the example that last year's team used in their dialogue showcase, for future developers to have a reference to it.

**Comment by jeyeong** [comment]
In light of implementing quest integrations and conditional dialogue, I have made modifications to the definitions of structs in the dialogue module. As such, the tests will have to be revised. I will do this by the end of the sprint.

**Comment by jeyeong** [comment]
The previous tests have been updated to work with the new struct definitions.

**Comment by jeyeong** [comment]
Wrote unit tests for conditional dialogue. The following were tested for:

- A node that has 1 conditional edge, which is **not satisfied**, resulting in 0 available edges. (Note: conversation ends)
- A node that has 1 conditional edge, which is **satisfied**, resulting in 1 available edge.
- A node that has 2 normal edges and 1 conditional edge, which is **not satisfied**, resulting in 2 available edges.
- A node that has 2 normal edges and 1 conditional edge, which is **satisfied**, resulting in 3 available edges.

**Comment by jeyeong** [comment]
Wrote three tests for actions:

- Giving the player **one item** (from one node).
- Giving the player **two items** (from one node).
- Giving the player **one item** (one node), followed by **another item** (another node).

I note that only the first test passes. The second and third tests fail because of an oversight in the implementation of items.

Also, I did not implement tests for quests / battles as the required functions have not yet been fully implemented by the Quest / Battle team.

**Comment by jeyeong** [comment]
[Pull request](https://github.com/uchicago-cs/chiventure/pull/1008) has been made.

**Comment by lilyehsani** [comment]
Issue Score: ✔️+

Comments:
Great work overall! I have one comment:
- The summary for this issue is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/policies.html#tasks-issues for examples). If this issue was generated from a Scrum board card, please remember that the summary you write in the Sprint meeting is meant to be a quick draft; it needs to be fleshed out when you convert the card to an issue.
