### ISSUE TITLE
Update openworld documentation on wiki to include level-oriented generation

### ISSUE THREAD

**Issue by Justin08784** [uchicago-cs/chiventure#955]
Last sprint, we implemented level-oriented generation ([issue #882](https://github.com/uchicago-cs/chiventure/issues/882)), which picks and generates rooms based on the player's level. The open world [source document](https://github.com/uchicago-cs/chiventure/wiki/Open-World:-Source-Document) wiki page should be updated to inform users and other developers regarding these changes.

**Comment by Justin08784** [comment]
[Source document](https://github.com/uchicago-cs/chiventure/wiki/Open-World-~-Source-Document) has been updated to explain level-oriented generation features (including the recent refactoring mentioned above by @wmingyan). We also added a note on the [openworld feature wishlist](https://github.com/uchicago-cs/chiventure/wiki/Open-World-~-Feature-Wishlist) to indicate our team's progress on the feature.

This marks the end of this issue.

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Excellent work! Your links to the wiki are extremely helpful, and you did a great job providing relevant updates, including linking to an issue you were waiting on.
