### ISSUE TITLE
Implement trees in quest struct according to design document https://github.com/uchicago-cs/chiventure/wiki/Version-2.0-of-Quests-Struct-to-Include-Trees

### ISSUE THREAD

**Issue by oliviajerdee** [uchicago-cs/chiventure#957]
We plan on implementing trees into the quest structure as we planned out in our wiki page. To do this, we will have to change the current linked list structure for achievements into one with trees. This will also entail changing many functions, as the current ones are designed for a linked list structure for achievements. It might be particularly challenging to find a way to traverse the tree and evaluate if quests have been completed. As we implement trees, we will also update the documentation for the functions as many will change.

Assignees: Olivia, Gabi, Zach
Team: quests

**Comment by oliviajerdee** [comment]
All three of us met on Zoom today and discussed the specific functions we need to modify. At this point, we predict that three functions will need more minor type changes: quest_new, quest_init, and quest_free. There will likely also be three functions which will entail more work and potentially will need their own helper functions: add_achieve_to_quest, complete_achievement, and is_quest_completed. We may end up changing these function names. We also plan to add an ID to the achievement struct to make searching the tree for achievements easier.

**Comment by oliviajerdee** [comment]
Added an ID string to the achievement struct and a function to compare quests for future use in searching through trees.

**Comment by gabigarc03** [comment]
(With regards to commits #60a6ca8 and #b55d22b) Replaced the `achievement_llist_t` component in the `quest_t` struct with the new `achievement_tree_t` component. Pretty much everything in `quests_state.c` is broken because of this, and that's OK.

**Comment by gabigarc03** [comment]
Just added a method (`find_achievement`) to traverse the non-binary achievement tree with EXTREMELY informal comments describing the method. I have not yet implemented it in `complete_achievement` but I plan to do so soon.

**Comment by gabigarc03** [comment]
Refactored `complete_achievement` to use `find_achievement`. Also updated inputs to `complete_achievement` to take a `char *id` instead of an `item_t` and an `npc_t` to allow for greater flexibility with mission types as we implement more options.

**Comment by gabigarc03** [comment]
Refactored `quest_new`, `quest_init`, and `quest_free` to take the achievement tree struct.

**Comment by zsp255** [comment]
Refactored is_quest_completed to accommodate the new tree struct. Note: I could not pull the updated .h files so I was unable to make sure this compiled. Need to make sure everything runs smoothly.

**Comment by oliviajerdee** [comment]
Refactored add_achievement_to_quest to work with the new tree struct.

**Comment by oliviajerdee** [comment]
Just updated the achievement_new and achievement_init functions to include the achievement id. I also updated the header file as the parameters for the functions changed.

**Comment by gabigarc03** [comment]
While working on tests, I realized that `add_achievement_to_quest` had no way to handle an empty achievement tree, so I updated it to make the added achievement the root if the tree is empty.

**Comment by gabigarc03** [comment]
Realized I forgot to leave a comment on this - I refactored all the tests. More details can be found in issue #1078.

**Comment by gabigarc03** [comment]
Non-binary achievement trees have now been implemented in the quest module as seen in PR #1080.

**Comment by lilyehsani** [comment]
Issue Score: ✔️++

Comments:
Great work overall! The summary and updates of this issue are very thorough.
