### ISSUE TITLE
Updating Player Class/Item Integration to add more functionality

### ISSUE THREAD

**Issue by ideclue** [uchicago-cs/chiventure#959]
Currently, the only interactions chiventure supports between player classes and items are class item restrictions (implemented in `class_item_restriction.c`) that allow certain player classes to be restricted form using certain items. We would like to add new methods of interaction, and after brainstorming a bit, we agreed that we should expand the class item restriction system into a more full-fledged system, where classes can actually have proficiencies with certain items (as well as being banned from other items as before).

**Comment by ideclue** [comment]
After some discussion, we have decided to refactor the `class_restrictions` field in `item.c` to be `class_competencies` or `class_multipliers`, with a numerical scale that determines what effect a player's class will have on their ability to use an item. Several steps will be involved in implementing this feature, including:

1. Updating relevant documentation to explain how the `class_multipliers` feature will work, adding user stories to display what their effect would be in a combat situation.
2. Updating code in `item.c` and `class_restrictions.c` to reflect these design changes.
3. Updating and adding new tests for functions in `class_restrictions.c`. 
4. Updating `pc_demo.c`, which currently uses class item restrictions functions that will be replaced in step (2).

**Comment by jackcasey067** [comment]
I took a look at item 2 above (Updating code), and ran into some issues.  If we want to keep these attributes in their current list form, we are going to need to add code or modify the `get_XXX_attribute` functions so that we can actually see the attributes in our list (those functions currently take items).

If we want to instead store our attributes in the main attribute spot, we would not be able to delete the attributes without writing code in item.c.

**Comment by jackcasey067** [comment]
Ok, I went ahead and added `list_get_XXX-attr` functions, and I switched the item restriction code to use them instead.  We still need to add class competencies.

I am not presently working on this, so I will notify you (Isabell and Max), if I start working on it again.  In the meantime, feel free to work on this.

**Comment by ideclue** [comment]
Test have been added and successfully passed for the type-specific `list_get_attr` functions. Once `pc_demo.c` and documentation related to player class and item interactions is updated, code will be ready for a Pull Request.

**Comment by jackcasey067** [comment]
I am opening a Pull Request since the code side of this issue is done.  However, this issue will remain open until we finish the documentation.

**Comment by jackcasey067** [comment]
Closing Comment: We successfully added the code, tests, and examples.  Classes can now have proficiencies with certain items.  See Pull Request #991.

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Great work!
