### ISSUE TITLE
Write higher save and load function and update Makefile

### ISSUE THREAD

**Issue by ellynliu** [uchicago-cs/chiventure#96]
Update and write the higher save and load function that take in a Game struct and return a pointer to the Game struct. Also update the Makefile once the transfer functions are complete (dependent on save.c and load.c)

Update: this should be where all the debugging activities for save.c and load.c take place since it's part of running the make file

**Comment by jarvislam1999** [comment]
To clarify, this task is literally just to write the save_game(game_t *g1, Game *g2) and load_game functions once the transfer functions are finished. After that is done, the person in charge of this task is also responsible for updating the Makefile necessary to build the libcheckpointing library. So generally deal with higher level code.

**Comment by jarvislam1999** [comment]
Any updates on whether you guys have been able to run make on our pushed save file to see if there are any bugs yet? @schin99 @chrisfernandes18

**Comment by schin99** [comment]
Makefile is updated to include "uthash.h" since that was creating a fatal error. Makefile for testing was also made and added to the main Makefile.

**Comment by schin99** [comment]
@jarvislam1999 after the pull requests are completed we will merge and check for bugs etc.  As of now, there are a few bugs, but I think most of them were fixed in from what i saw of Jonah's review of the code.

**Comment by schin99** [comment]
Main Makefile for checkpointing as well as the test Makefile for checkpointing is complete. It successfully makes checkpointing.a, and includes game-states library and the common library. Thank you Mark.

**Comment by schin99** [comment]
save.c and load.c compile with no errors as does test_save.c (test_load.c can not compile for reasons listed in testing load task) which indicates our Makefiles are work and our save and load has no bugs.

**Comment by mpcsh** [comment]
Issue Score: ✓

Comments:
No closing statement.
