### ISSUE TITLE
Complete npc-move functions

### ISSUE THREAD

**Issue by mbutera17** [uchicago-cs/chiventure#966]
In the npc_move module, functions move_npc_indefinite() and auto_gen_movement() were left unimplemented. These functions will be implemented as part of the npc/mov-integration branch. 

Assignees: Torres, Matthew, Xavier
team: npc1

**Comment by xlewellen** [comment]
I implemented `move_npc_indefinite()` in npc_move as follows:
`int move_npc_indefinite(npc_mov_t *npc_mov)
{

    assert(npc_mov->mov_type == NPC_MOV_INDEFINITE);

    room_list_t *test = malloc(sizeof(room_list_t));
    test->next = NULL;
    test->room = room_new(npc_mov->track,"test","test");
    room_list_t *current_room = malloc(sizeof(room_list_t));

    LL_SEARCH(npc_mov->npc_mov_type.npc_mov_indefinite->npc_path,
                current_room,test,room_id_cmp);

    if(current_room->next == NULL)
    {
        return 1;
    }
    if((strcmp(current_room->room->room_id,npc_mov->track)) == 0)
    {
        room_t *next_room = current_room->next->room;
        npc_mov->track = next_room->room_id;
        return 2;
    }
    else
    {
        return 0;
    }
}`

This implementation is near identical to `move_npc_definite()`, so it may be possible to combine these into a single function. Alternatively, it might be a good idea for `move_npc_indefinite()` to take `npc_move_indefinite->room_time` into account prior to executing the actual movement of the npc (i.e. the function would wait the given amount of milliseconds before moving the npc) so that the time does not need to be tracked by an external function that then calls `move_npc_indefinite()` once the time has elapsed.

**Comment by torresszy** [comment]
One challenge I found is that the concept of time is not well defined in chiventure currently. The only function we have about time is `register_npc_room_time`, but how time is counted in chiventure is unclear (for example, do we start counting the moment the a game starts or does time get to renewed in certain ways everytime the player type in a command, etc). I think the progress we can make in the indefinite move type is limited before we can figure out how time really works in chiventure

**Comment by torresszy** [comment]
Mattew and I are also working on `auto_gen_movement`, and we are trying to let the function generates a list of rooms to visit given a `npc_mov_t` struct as the input

**Comment by torresszy** [comment]
The next step would be writing tests for these functions. Since they are fairly complex functions, we may need some time to test out if they are really doing what we want them to do without producing buggs

**Comment by mbutera17** [comment]
Documentation for the [above comment](https://github.com/uchicago-cs/chiventure/issues/966#issuecomment-835938307) from Torres was outdated, so I just updated the npc_move.h and npc_move.c files to better reflect the changes described in his comment. Also, documentation on our wiki page was outdated with regards to the same comment as before and has been updated. We plan on working with the open world team very soon to discuss integration with them, so keeping our documentation up to date is critical. Expect an update regarding tests for the two functions `auto_gen_movement()` and `move_npc_indefinite()` shortly.

**Comment by xlewellen** [comment]
I have added tests for `move_npc_indefinite()` in the `npc/move_tests` branch. However, it appears that move_tests branch has not yet been merged with the mov-integration branch, so does not yet have the implementation of `auto_gen_movement()` and `move_npc_indefinite()`, so actual testing of the functions will have to wait for when the branches are merged.

**Comment by mbutera17** [comment]
While writing tests for `auto_gen_movement()` and brief discussion on Slack, we realized that a function to determine the number of rooms that an npc will move through (length of the list in the npc move struct: `room_list_t *npc_path`) was necessary for the test. We figured that this function may be useful for future teams, and thus we will be implementing this new function in the npc_move module. The name of this function is `get_npc_num_rooms()` and is defined as:

```
/*
 * Gets the number of rooms in an NPC's path
 *
 * Parameters:
 *  - npc_mov: The NPC movement struct
 *
 *  Returns:
 *  - number of rooms in an NPC's path, represented as an int
 */
int get_npc_num_rooms(npc_mov_t *npc_mov)
```
This will be implemented on the npc/mov-funcs branch.

**Comment by torresszy** [comment]
I have fixed all the bugs in the two major functions, `move_npc_indefinite` and `auto_gen_movement`, as well as two helper functions, `get_num_rooms`,and `auto_gen_movement`. They have now been implemented successfully under the file `npc_move.c` and their headers in `npc_move.h`. In addition, I have updated all the tests related to these functions in `test_npc_move.c` and they have all been passed. I think we have reached our goal for this issue and thus, made a pull request for branch `npc/mov-funcs`. Successfully merging the pull request may close this issue. 

The new features in the `npc_move` are:
```
/* 
 * helper function for auto_gen_movement to find number of rooms in game
 * 
 * Parameters:
 *  - game: current game
 *
 * Returns
 *  - # of rooms in game
 *
 */
int get_num_rooms(game_t *game);

/*
 * Generates a random movement struct for an NPC based on the current rooms in
 * the map and a given npc_mov_t struct. 
 *
 * Parameters: 
 *  - npc_mov: npc_mov_t struct with a known npc_mov_type
 *  - game: current game, this is necessary for determining the current rooms in the map
 *
 * Returns:
 *  - returns SUCCESS on success, returns FAILURE on failure
 *  - Updates npc_mov to have a new, randomly generated movement path. 
 *    Maintains the same type of movement (indefinite / definite)
 *
 */
int auto_gen_movement(npc_mov_t *npc_mov, game_t *game);

/*
 * Moves the npc to the next room for npcs with indefinite movement
 * 
 * Paramters:
 * npc_mov: The NPC movement struct
 * 
 * Returns:
 * SUCCESS, OR FAILURE
*/
int move_npc_indefinite(npc_mov_t *npc_mov);

/*
 * Gets the number of rooms in an NPC's path
 *
 * Parameters:
 *  - npc_mov: The NPC movement struct
 *
 *  Returns:
 *  - number of rooms in an NPC's path, represented as an int
 */
int get_npc_num_rooms(npc_mov_t *npc_mov);
```

And the new tests added for these functions in `test_npc_move.c` are the following:
```
/* Tests get_npc_num_rooms function for definite move */
Test(npc_mov, get_npc_num_rooms_def)

/* Tests get_npc_num_rooms function for indefinite move */
Test(npc_mov, get_npc_num_rooms_indef)

/* Tests move_npc_indef function */
Test(npc_mov, move_npc_indefinite)

/* Tests auto_gen_movement for definite movement function */
Test(npc_mov, auto_gen_movement_definite)

/* Tests auto_gen_movement for indefinite movement function */
Test(npc_mov, auto_gen_movement_indefinite)

**Comment by lilyehsani** [comment]
Issue Score: ✔️+

Comments:
Great work overall! I have one comment:
- The summary for this issue is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/policies.html#tasks-issues for examples). If this issue was generated from a Scrum board card, please remember that the summary you write in the Sprint meeting is meant to be a quick draft; it needs to be fleshed out when you convert the card to an issue.
