### ISSUE TITLE
Check implementation of skill-prequisite levelling, and create adequate tests to make sure skill levelling system is correct.

### ISSUE THREAD

**Issue by Joshuashou** [uchicago-cs/chiventure#976]
Assignees: Joshua, Mayur
Team: Skill Trees

**Comment by Joshuashou** [comment]
Create new branch for pull request for implementing changes

**Comment by Joshuashou** [comment]
Correctly finished implementing code for skill pre-requisite leveling in the skilltree files, as well as changed playerclass to accommodate structural changes. Due to the testing feature is reliant on the effects that haven't been fully implemented yet, we will have to wait until those changes go through to fully check that our tests work, which I will plan on doing in the next sprint

**Comment by firatciftci** [comment]
Issue Score: ✔️+

Comments:
Good work overall! I only have one thing to comment on:
- The issue did not include a descriptive summary (see https://uchicago-cs.github.io/cmsc22000/project/policies.html#tasks-issues for more details and concrete examples)
