### ISSUE TITLE
Support for escape characters in strings

### ISSUE THREAD

**Issue by jacknugent1529** [uchicago-cs/chiventure#977]
The dsl should allow users to include quotations marks, newlines, and other escape characters in strings using backslash syntax (e.g. `\"` for quotes).

**Comment by jacknugent1529** [comment]
The dsl now supports escape characters. Simply use `\"`,`\t`, etc. and the character will be replaced by the Unicode equivalent. Now quotation marks can be included in strings without any issues.

**Comment by jacknugent1529** [comment]
The pull request #1029 resolves this issue. The code for recognizing escaped characters in a string and replacing them with the proper unicode characters has been merged into dev, closing this issue.

**Comment by ecoble** [comment]
Issue Score: ✔️++

Comments:
Great work, and nice examples!
