### ISSUE TITLE
Integrate move-awarding skills from skilltrees with battle code

### ISSUE THREAD

**Issue by lczielinski** [uchicago-cs/chiventure#979]
A member of the skilltrees team @tgao564 reached out to us about integrating skills with battles. His idea was that when a player unlocked a certain skill, it would award them with a move that could be used in battle. We discussed possible implementations of this and specifics of what would be required. On our end, we will create a function that adds a move to a player's linked list of moves. We will also restructure the move-giving functions, possibly moving the function in battle_move_maker to another file. Then, the skilltrees code would create a function that took in a player struct, determined what skills they possess, and add moves its field. We will then use this function to award skill moves when initializing a battle.

**Comment by Elsa-Athiley** [comment]
Made some small adjustments necessary because of the movement of battle_move_maker from the battle/examples directory into the battle/src directory. Also finished implementing the add-move function inside of the battle_flow module. We now will create some tests to see if the new function works as expected.

**Comment by lczielinski** [comment]
To summarize, we started integrating move-awarding skills with battles by creating a function, add_move, that will allow the skilltrees team to add a move to the battle_player struct. We also moved the battle_move_maker file from the example directory to the src directory, and added the new function in that file.

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Great job!
