### ISSUE TITLE
Load: write tests

### ISSUE THREAD

**Issue by ellynliu** [uchicago-cs/chiventure#98]
Write tests for each of the load functions in load.c. Also write tests for the higher level load function written in issue #96. More elaboration coming

**Comment by chrisfernandes18** [comment]
We are going to use the criterion library to help us create tests to see if the functions we make for deserializing a file containing the serialized game state structs will actually deserialize the information as well as put the information back into the structs using the functions game state gave us. We are going to test each on of the smaller functions as well as the higher level overall load function which uses all of the smaller functions.

**Comment by schin99** [comment]
Finished test_load.c for the most part. Only now need to go over and check for small errors. Similar to test_save.c, condition and path testing was taken out. Attribute_value and attribute might be taken out in the future as load.c might be changed. Only current problem is we don't have a way to check if a player or room is saved into the data structure game-state implements.

**Comment by chrisfernandes18** [comment]
I'm going to do a PR to dev from our testing branch so we can have Jarvis look at our code. Overall we are close to having the tests done. We just need some functions from game-state.

**Comment by schin99** [comment]
test_load.c currently relies on a bunch of game-state functions that have not been written yet, but is in their documentation. Therefore it will not compile at the moment, but should after their pull request to master is complete.

**Comment by schin99** [comment]
load.c also relies on game-states iterators which currently doesn't work with our code. Since we will be provided with a new function to go through the data structure, we will resolve this task.

**Comment by mpcsh** [comment]
Issue Score: ✓+

Comments:
Great work!
