### ISSUE TITLE
Implement a singular image on the top half of the split-screen in gui.c

### ISSUE THREAD

**Issue by grkapoor17** [uchicago-cs/chiventure#980]
gui.c aims to have the implementation for a chiventure game with a command box as the bottom half and images specific to the chiventure game rooms as the top half. This issue aims to implement the top half of the split screen by displaying a singular image.

**Comment by grkapoor17** [comment]
After discussing with Professor Borja, I have decided to take another approach to this issue: merging the code in split_screen_example.c into gui.c. However, split_screen_example.c hard codes a chiventure game and produces the split_screen specifically for this sole example. So, in gui.c, I will implement a start_gui() function that takes in a general chiventure context struct and tries to produce the split screen for a general game.

**Comment by grkapoor17** [comment]
We have implemented the start_gui function such that in the lower half of the screen a command box and an output text box will be displayed. The command box will be where the user types in their commands and the output text box will relay information pertaining to descriptions of rooms and objects. On the top half of the screen, images related to the actual chiventure game will be displayed. I have had to update the CMAKE.lists.txt file to include the raylib library. However, when trying to run a game using the gui interface, a segmentation fault pops up, which I need to fix.

**Comment by grkapoor17** [comment]
The segmentation fault was caused due to a call to a draw_room function in the draw_images module. This function attempted to draw each room in the game when it is called. I have removed it for now and have instead hard coded the implementation of drawing a single image on the top half of the screen. This image is "room1.png" and is located in src/ui/sandbox/images. So for now gui.c can run a chiventure game with a single image being displayed at the top.

**Comment by grkapoor17** [comment]
I realized that in the test I was running (tests/wdl/examples/wdl/connected-rooms.wdl) there were no images, and so I added three images to this test labelled room_A, room_B, room_c in correspondence with the room_id. However, when I tried using my draw_room_gui function (the name changed, due to another function in map.c having the same name) the images would load, but there would be an issue with the 'enter' and 'backspace' key in the input box. Thus, I decided to move everything from my draw_room_gui function directly into gui.c, which surprisingly yielded nothing abnormal. So, now gui.c can display an image on the top half of the screen, which changes as a user moves into another room. I still need to work on making the path string for the image more generic, so this can work for any chiventure game and not just this specific test. For example, my current path for the image is ""/home/grkapoor/cs220/chiventure/tests/wdl/examples/wdl/", which would obviously not work for any other game or test.

**Comment by grkapoor17** [comment]
Instead of making the path string more generic for now, I will only depict a single image on the top half of the split screen, labelled chiventure.png in "src/ui/src/". I changed the name of the function in gui.c from start_gui to run_gui as we do not need stop_gui anymore. Thus, this resulted in a change in chiventure.c as well, to include the change of the name of the function. This issue has successfully displayed a chiventure image on the top half of the screen while loading a chiventure game, and in doing so has integrated a graphical interface with chiventure. I will do a pull request for chiventure.c as well as  src/ui/src/chiventure.png and gui.c.

**Comment by grkapoor17** [comment]
#1075

**Comment by grkapoor17** [comment]
It must be noted that the code was merged twice through the pull request. This is because there was initially an error that would not let the code compile unless the user had raylib installed and this was problematic as a user does not need raylib to run the normal ui interface. Thus, changes were made to chiventure.c as well as the CMakeLists to fix this issue.

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Excellent work! Your issue updates are particularly detailed.
