### ISSUE TITLE
Assign properties to items

### ISSUE THREAD

**Issue by tessied** [uchicago-cs/chiventure#981]
The DSL should allow properties to be attributed to specific items. Currently, the DSL grammar allows for properties to be associated with only the item above; this is not ideal and can be confusing when more items/rooms are added.

Assignee: Tessie and John
team: dsl

**Comment by tessied** [comment]
I have modified the grammar defined for `property`, now we are able to assign the properties to a specific object (`[commit 64acc6a](https://github.com/uchicago-cs/chiventure/commit/64acc6a5ea9ee15b3879432efb864de6a39fd006#diff-af9289b34b6a239aea9e5dbda121cfbd39ae53c8f46d0a2456ffe9ace1efaaff)`). Instead of specifying properties using `property: value`, the dsl now supports `property FOR ROOM A: value` or `property FOR ITEM A: value`, for example. Now properties can be assigned to both rooms and items with a higher level of specificity.

This feature enhances the flexibility of assigning properties and decreases ambiguity. For example, if we declare a room followed by a declaration of an item, a property declared after that will be assigned to the item. But now with this feature, we are able to assign that property to the room itself or other items not immediately above the property.

**Comment by tessied** [comment]
During a team meeting today, we decided that we wanted to support `property: value` without assigning them to specific items as well. `property FOR ITEM: value` and `property FOR ROOM: value` will be an option for users to specify properties if they choose to do so. 

I implemented this feature in the dsl grammar, now the grammar supports both `property: value` and `property FOR ITEM: value` (commit [`b7eda2f`](https://github.com/uchicago-cs/chiventure/commit/b7eda2fb43d8d465eed046989e5c30d4059a8763#diff-af9289b34b6a239aea9e5dbda121cfbd39ae53c8f46d0a2456ffe9ace1efaaff))

**Comment by tessied** [comment]
The pull request linked to this issue reflects the changes made, that is, the grammar now allows users to assign properties to items if they want. Pull request has been merged, closing the issue.

**Comment by tessied** [comment]
The pull request linked to this issue reflects the changes made, that is, the grammar now allows users to assign properties to items if they want. Pull request has been merged, closing the issue.

**Comment by ecoble** [comment]
Issue Score: ✔️++

Comments:
Great job on this issue! Excellent documentation, especially connecting this to other issues and commits.
