### ISSUE TITLE
Refactor level-oriented generation code with adding a function for filtering speclist

### ISSUE THREAD

**Issue by wmingyan** [uchicago-cs/chiventure#982]
Currently, the level-oriented generation algorithm is a part of the multi_room_level_generate function (#882 ), which means it cannot be used for other generation functions like recursive_generate. We decide to put this functionality (filtering the given speclist with a given difficulty level) into a separate function so that we can take a filtered speclist as a parameter for other autogeneration functions, and this might also be useful for later features.

**Comment by wmingyan** [comment]
The relevant [pull request](https://github.com/uchicago-cs/chiventure/pull/987) has been approved, and the refactored code, including a new function filter_speclist and tests for it, has been merged into the dev branch. This marks the end of this issue.

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Great work! Your summary is particularly detailed and helpful.
