### ISSUE TITLE
Write an updated dialogue example utilizing mode functionality

### ISSUE THREAD

**Issue by pkasner** [uchicago-cs/chiventure#984]
The previous dialogue example implements a conversation into chiventure by monkey patching individual dialogue options as actions into the game. Now that conversation mode has been implemented, I will write an example that runs a conversation in an instance of chiventure by utilizing that feature.
Assignee: Peter
team:npc2

**Comment by pkasner** [comment]
I've written a basic example that runs chiventure with a simple two room example and adds an npc which can be talked to. I've monkey patched in a "talk" operation which switches the game to conversation mode and starts a conversation with the npc named steve.

**Comment by pkasner** [comment]
The example seems to be working perfectly with conversation mode. I may write more elaborate conversations to run in the future, but for now I've linked a pull request to merge the branch into dev.

**Comment by lilyehsani** [comment]
Issue Score: ✔️++

Comments:
Great work overall! The summary and updates of this issue are to-the-point.
