### ISSUE TITLE
Work with action management team to Implement quests into player struct as a hash and look into implementing a hash table containing all of the quest structs in a game.

### ISSUE THREAD

**Issue by dillonoloughlin** [uchicago-cs/chiventure#985]
The current implementation of quests was copied and pasted from the NPC code and then adapted to work for quests. As a result of this, the quest struct has the field for implementing quests as a hash but does not have any actual implementation behind it. We want to look into integrating this hash functionality for all quests. Additionally we want to add a hash to the player struct of all the quests the player acquires throughout the game.
Assignees: Dillon
Team: Quests

**Comment by dillonoloughlin** [comment]
Spoke with action management about the implementation of the quest hash into the player struct and other useful functions to incorporate in the player module to interact with quests. The potential functions and future implementation is outlined in this wiki https://github.com/uchicago-cs/chiventure/wiki/Player-~-Interface-Implementation-Plan, along with other aspects of the player struct. We have decided to hold off onto creating some of these functions until after the hash containing of the quests has been added to the game state.

**Comment by dillonoloughlin** [comment]
Spoke with action management about the implementation of the quest hash into the player struct and other useful functions to incorporate in the player module to interact with quests. The potential functions and future implementation is outlined in this wiki https://github.com/uchicago-cs/chiventure/wiki/Player-~-Interface-Implementation-Plan, along with other aspects of the player struct. We have decided to hold off onto creating some of these functions until after the hash containing of the quests has been added to the game state.

**Comment by dillonoloughlin** [comment]
I have updated the Quest Design API document to reflect the new integration of quests in the player struct. I have also outlined the current plan to implement the all_quests hash table into the game at the end of the document: https://github.com/uchicago-cs/chiventure/wiki/Quests-~-API-Design-Document.
We hope to move forward with these implementations in the next sprint.

**Comment by lilyehsani** [comment]
Issue Score: ✔️++

Comments:
Great work overall! The summary and updates of this issue are very thorough.
