### ISSUE TITLE
create weapons in battle code

### ISSUE THREAD

**Issue by sonnykaiyuenlee** [uchicago-cs/chiventure#989]
There is currently no weapon-like item that can be used in a battle. Should distinguish between consumable-item(potion), items that we created in the previous sprints, and weapons items. Ideally these weapons items could also contain durability information that would decrement with each use. Should also consider other features of weapons that can be put to use.
assignees: Sonny
Team: battles

**Comment by sonnykaiyuenlee** [comment]
created new branch, discussed with Matthew and Laura about the features of a weapon. Right now the idea is to have a struct almost identical to an item, with an added "effectiveness" field. This will indicate the value with which to decrement the effectiveness of the weapon with each use.

**Comment by sonnykaiyuenlee** [comment]
upon much consideration and discussion with Laura and Matthew, it makes more sense and I believe is easier to implement weapons by simply adding fields to the battle_item_t struct. I added an is_weapon field which is true when the item is a weapon and false when it is not. Additionally I added an effectiveness_decrement field which will hold the value to decrement the attack value by with each use. I added these fields to the struct within battle_structs.h. I also added a get_random_default_weapon() function to battle_default_objects.c file. NOTE: For normal items, the is_weapon field is false while the effectiveness_decrement field is 0. The actual implementation of this can be a separate issue.

**Comment by sonnykaiyuenlee** [comment]
Modified battle_default_objects.h, battle_structs.h, battle_defualt_objects.c, test_battle_default_objects.c. I've added a function to generate random default weapons, as well as adding the fields mentioned in previous comments to the battle_item_t struct, added tests for generating default weapons in test_battle_default_objects.c-- all tests pass. Will submit pull request next

**Comment by firatciftci** [comment]
Issue Score: ✔️+

Comments:
Good work! The only things I can comment on are that, make sure to assign new issues to the sprint they are worked on (by selecting the appropriate sprint under "Milestone"), add anyone who is working on this issue as an Assignee, and select your team's identifier under "Labels".
