### ISSUE TITLE
Merge Player Class: Class List and Player Class: Example Stats and Abilities wiki pages

### ISSUE THREAD

**Issue by maxsamengo** [uchicago-cs/chiventure#994]
The wiki page _Player Class: Example Stats and Abilities_, initially created to document the implementation of prefabricated classes (#916), has come to be very similar to the existing wiki page _Player Class: Class List_. @farm-zaq requested that two missing entries in _Player Class: Class List_ -- bard and wizard -- be completed, however I think it would be best to fix this issue and merge the two pages at the same time, because they currently contain very similar information which is inconveniently spread across two separate, similarly name documents. Specifically, I wish to:
- Merge the information in the two documents
- Organise the classes by currently-implemented prefabricated classes and non-implemented example classes (_Player Class: Class List_ does not currently distinguish between the two). 
- Add skill trees and the rationale for them for the prefab classes, as @jackcasey067 continues to work with the skill trees team to implement them.

**Comment by maxsamengo** [comment]
Adding to the to-do: 
- Include documentation for prefabricated starting items, as they are implemented.

**Comment by maxsamengo** [comment]
It turns out that battles have created a function which creates randomised default weapons. I am currently in the process of communicating with that team, but, as for now, including documentation for prefabricated starting items will not be part of this issue. Depending on the battle team's implementation of their default weapon function, if any room to add our own prefab_weapons function, then it and its documentation will be part of its own issue.

**Comment by maxsamengo** [comment]
Almost done. 
Specifically:
-  _Player Class: Example Stats and Abilities_ has been renamed to _Player Class: Prefabricated Classes_ 
- the playerclasses wiki page called _Class List_ has been deleted. Find all its content (plus more) on the _Player Class: Prefabricated Classes_. This wiki page was half redundancies with _Player Class: Example Stats and Abilities_ (now _Player Class: Prefabricated Classes_), which contained more detailed and up to date information, and the rest has been pasted into the Class List section in _Player Class: Prefabricated Classes_
- Multiple formatting changes implemented to improve readability. The issue will be closed very soon, there are only a few small formatting things left to do.
I expect to work on adding features the rest of the team implemented into `class_prefabs.c` in the future, and the documentation for that will go on this new wiki page too. I think it is also possible to use a fleshed-out `class_prefabs.c` in the final demo.

**Comment by maxsamengo** [comment]
- Added final formatting changes to improve readability.

Wiki is at: 
https://github.com/uchicago-cs/chiventure/wiki/Player-Class-~-Prefabricated-Classes

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Great work! The only thing I can comment on is that, make sure to assign new issues to the sprint they are worked on (by selecting the appropriate sprint under "Milestone").
