### ISSUE TITLE
Implement conditional NPC dialogue options

### ISSUE THREAD

**Issue by jeyeong** [uchicago-cs/chiventure#995]
Having developed a working simple dialogue system, we now want to explore giving game designers more complex functionalities.

Conditional dialogue options would allow designers to only give a player access to a dialogue option if they meet certain conditions. This could be an item requirement, a stat requirement, and so on.

**Comment by jeyeong** [comment]
Designed the conditional dialogue system. It makes use of the work that has been done in the game-state/condition module.

The concept is that:
- Each edge has a new "condition" field, which can either be a pointer to a condition struct, or NULL
- Condition creation/checking will be done through functions in the condition module

To facilitate this new addition, some changes had to be made to the existing dialogue design:
- Since at some node, certain edges will be "Available" and other "Unavailable," we can no longer use the option_number design
- We removed the "option_number" field on the edge list struct, replacing it with an "availability" field
- The "availability" field, along with rewritten logic in the run_conversation_step() and associated functions, ensures that output is printed to the CLI correctly, and the module works as before

**Comment by jeyeong** [comment]
The conditional dialogue system now supports multiple conditions, which can be created using functions defined in the _condition_ module.

**Comment by jeyeong** [comment]
[Pull request](https://github.com/uchicago-cs/chiventure/pull/1008) has been made.

**Comment by lilyehsani** [comment]
Issue Score: ✔️++

Comments:
Great work overall! The summary and updates of this issue are very thorough.
