### ISSUE TITLE
Integrate actions (quests, items, battles, etc.) in dialogues

### ISSUE THREAD

**Issue by jeyeong** [uchicago-cs/chiventure#996]
To make dialogues even more useful, we are exploring the possibility of integrating game actions into dialogues.

This mean that, upon landing on a certain dialogue node, the player will be able to receive a quest, receive an item, gain stats, start a battle, etc.

**Comment by jeyeong** [comment]
We are currently in talks with the Quest team to explore integrating quest start / progression functionalities into dialogues.

**Comment by jeyeong** [comment]
Created a simple switch based action execution system. In order to work with this system, we added an "action" field into the node struct, along with an "action id."

The idea of how this will work is that whenever run_conversation_step() is run, there will be an intermediate step that checks whether the "action" field is empty. If the "action" field is not empty, then do_action() will be run. do_action() features a switch based system that specifies certain function calls based on the value in the "action" field.

**Comment by jeyeong** [comment]
Spoke to the Battle team about the integration of battles into dialogue. However, as they shared that they have yet to integrate battles with the CLI, they will likely focus on getting that done first. The integration of battles with dialogue will thus be put on hold for now.

**Comment by jeyeong** [comment]
Multiple actions per node is now supported.

This was done by developing a node_action struct, which is a linked list. Accordingly, I had to change the implementation of functions like do_node_action, to deal with linked lists of actions rather than a single action.

**Comment by jeyeong** [comment]
[Pull request](https://github.com/uchicago-cs/chiventure/pull/1008) has been made.

**Comment by jeyeong** [comment]
I remodelled the GIVE_ITEM action (and added a TAKE_ITEM action) so that they now interact with the NPC as opposed to the game.

GIVE_ITEM should now take the item from the NPC's inventory (if it exists, otherwise it will return an error), and add it to the player's.

TAKE_ITEM does the inverse.

**Comment by lilyehsani** [comment]
Issue Score: ✔️+

Comments:
Great work overall! I have one comment:
- If, as part of an issue, you have a meeting or conversation with other developers, make sure to include a summary of that conversation, with an emphasis on any decisions that were made in that conversation. It is not enough to just state that you talked with someone.
