### ISSUE TITLE
Add variables to grammar

### ISSUE THREAD

**Issue by r-e-stern** [uchicago-cs/chiventure#998]
We'll work on assigning variables to the DSL grammar (per the DSL specifications on the wiki) such that users can declare and reuse a variable within a DSL world description file.

**Comment by jacknugent1529** [comment]
Right now we have a simple implementation of variables, where we can define a variable as a string and reuse it in different locations. Here is an example of how to define variables
```
$Room = """
ROOM room
    short desc: "this is a room"
"""
```
Note that the name of the variable `room` in this case must be a is similar in syntax to a variable name in c (or any other common language). It must be a single word and can include numbers. To separate between multiple words, we recommend using snake case when the variable represents simply a string such as a description or a property-value pair. We recommend using CamelCase for a variable represents a room, item, or any other compound objects which contains its own properties.

Additionally, the syntax has been changed to triple quotes (from single quotes). This allows us to place single quotes inside the variable declaration, which is necessary for more complicated structures.

We still need to add the ability to substitute strings into variables such as
```
$greeting = """hello {name}"""
```

**Comment by jacknugent1529** [comment]
Now we also support simple escaped strings as variables. For example instead of using triple quotes, we can write
```
$intro = "introduction to the game"
```

**Comment by jacknugent1529** [comment]
Variables are now fully implemented including support for template strings (similar to python f-strings). In summary, there remain two types of variable declarations:
```
$var1 = """
multi-line
replacement
"""

$var2 = "escaped string replacement"
```
Both of these variables can be referenced with the `$varname` syntax. For the first type, the text within the quotes is inserted directly into the document, so the reference to `$var1` evaluates to
```
multi-line
replacement
```
Notice that this does not include quotes. Therefore, this variable type is better to create objects such as items or rooms which can be reused. 

The second declaration evaluates to an escaped string *surrounded by quotes*. Specifically, `$var2` would evaluate to
```
"escaped string replacement"
```

We have just added support for template strings, where for either type of declaration, we can include unspecified inner variables such as
```
$intro = "Hello {name}"
```
Then to reference this variable, we would write
```
GAME ...
    intro: $intro { name: "John" }
```
This would evaluate to
```
GAME ...
    intro: "Hello John"
```
Note that we don't need to include the quotes around "John", and we could instead reference the variable as `$intro { name: John}`. However, the quotes would be necessary if we wanted to include escaped characters in one of the replacements.

Overall, the variables functionality acts as a pre-parsing addition to the language. A dsl file first runs through the `evalVars` function, and then is parsed by the dsl grammar specified elsewhere. In this manner, variables are not necessary to the language and can be entirely avoided by new users while still providing experienced users with more powerful tools to write a game file quickly.

**Comment by jacknugent1529** [comment]
The linked pull request fully implements variables as we intended them, thus closing this issue. Modified versions of the descriptions in the comments above will soon be included in the documentation.

**Comment by ecoble** [comment]
Issue Score: ✔️++

Comments:
Great work on this issue! The documentation here is super thorough as always!
